### PR TITLE
fix: reconnect modal google sheets

### PR DESCRIPTION
**Pull request by akash-codemonk**
https://www.notion.so/appsmith/Reconnect-Datasource-Modal-is-broken-62201e5b77834410a114801dd80ce752?pvs=4#5fcc5745b17e43f7a7a641e90125c062
https://www.notion.so/appsmith/Reconnect-Datasource-Modal-is-broken-62201e5b77834410a114801dd80ce752?pvs=4#6a03b3688f274dda8fd350ff3e63992a
Update z index for UI fix. 
The picker doesn't have focus at all as when the ads modal is visible all pointer events are disabled elsewhere which includes the filepicker, fixed this by adding pointer events auto to the file picker. 
This also means we have to handle closing of modal ourselves, so I am checking if the user clicks on the overlay around the modal or the close button and then closing the modal. 

https://www.notion.so/appsmith/The-list-of-pages-in-submenu-in-entity-explorer-are-not-visible-and-no-scroll-present-28a0e21491a44abbb1d18a5b14c8359b?pvs=4#9991ff86ac954e368cd4eead2154f6b0
Updated max height

### CODE REVIEW

**Review by albinAppsmith — DISMISSED** [review]

**Comment by shadabbuchh** [comment]
I am still able to reproduce the below two issues:
https://www.notion.so/appsmith/Reconnect-Datasource-Modal-is-broken-62201e5b77834410a114801dd80ce752?pvs=4#5fcc5745b17e43f7a7a641e90125c062
https://www.notion.so/appsmith/Reconnect-Datasource-Modal-is-broken-62201e5b77834410a114801dd80ce752?pvs=4#6a03b3688f274dda8fd350ff3e63992a

Please find the recording of the same:

https://github.com/appsmithorg/appsmith/assets/39921438/c7aee3dd-af8b-4637-8803-321b4396e364

The 3rd issue (list of pages in the sub menu) is fixed.

**Comment by shadabbuchh** [comment]
All the above reported issues in this PR are fixed.
However if while trying to authorise multiple GSheets Datasources at once, only one gets authorised & not all. Please have a look at the below Loom:
https://www.loom.com/share/18e09fd87c2a4623b70158e1e91749d7

**Pull request merged**
