### PR TITLE
fix: start with data onboarding issue fixes

### LINKED ISSUE #29163: [Bug]: Onborading start with data bugs
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

- [The container is not according to design](https://www.notion.so/appsmith/The-container-is-not-according-to-design-67ae217134354edf83f0a44a5892629e?pvs=4)
- [exception when adding a REST or graphql datasource](https://www.notion.so/appsmith/exception-when-adding-a-REST-or-graphql-datasource-80289c94dde34d7cacdd671d42a36902?pvs=4)

### Steps To Reproduce

1. Select start with data during onboarding

### Public Sample App

_No response_

### Environment

Deploy Preview

### Issue video log

_No response_

### Version

Cloud/ Self-Hosted - 1.8.4

### PR DESCRIPTION
**Pull request by sneha122**
## Description

This PR fixes:
- UI issues with respect to the container that we show when users go through start with data flow
- Issue with Authenticated and Authenticated GraphQL API, when user select start with data flow, if we they select any of these two and save datasource, it was leading to invalid URL page. 

#### PR fixes following issue(s)
Fixes #29163 
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
- Bug fix (non-breaking change which fixes an issue)
>
>
>
- [x] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Comment by AmanAgarwal041** [comment]
Tested and it looks good. There are 2 observations adding those in comment for ref :
- When there is a small space then the form is itself scrolling instead of the full screen. : [Notion doc](https://www.notion.so/appsmith/388dd3256916464c827dcea4710ec1a1?v=cc232076788f424fadaa6fe1db86c5b4&p=76f4871977d34c3fb2dfc23ddcf57944&pm=s)
- Rest API & Graphql API still present, that needs to be removed
@sneha122

**Comment by sneha122** [comment]
Thanks @AmanAgarwal041 For first observation we already have a bug listed on notion, As for the second part, I will take that as part of [task](https://www.notion.so/appsmith/Fix-confusion-with-REST-API-Authenticated-API-and-GraphQL-848b2f4a72cf47e8b302c200961b533f?pvs=4).

**Comment by sneha122** [comment]
@AmanAgarwal041 Please review the PR as well

**Review by AmanAgarwal041 — APPROVED** [review]

**Pull request merged**
