### PR TITLE
fix: add ellipsis to table search input when blur

### LINKED ISSUE #10562: [Bug]: Long table search value gets covered by the clear icon button
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When a user tries to search for a value that is long, the search text gets covered by clear icon.

### Steps To Reproduce

1. Type in a long value in the search box in the table

Screenshot 2022-01-22 at 11 05 04

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by vicky-primathon**
## Description

Fixes #10562 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/table-searchbar 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 55.43 **(-0.02)** | 37 **(-0.02)** | 35.3 **(-0.09)** | 55.81 **(-0.03)**
 :red_circle: | app/client/src/components/ads/StepComponent.tsx | 40.91 **(-52.19)** | 66.67 **(-23.33)** | 0 **(-100)** | 40.91 **(-52.19)**
 :red_circle: | app/client/src/constants/IconConstants.tsx | 100 **(0)** | 83.33 **(-4.17)** | 100 **(0)** | 100 **(0)**
 :red_circle: | app/client/src/icons/ControlIcons.tsx | 68.42 **(-1.5)** | 100 **(0)** | 35.38 **(-3.08)** | 68.42 **(-1.5)**
 :green_circle: | app/client/src/selectors/commentsSelectors.ts | 85.25 **(1.64)** | 64.71 **(2.95)** | 73.33 **(0)** | 90.59 **(2.35)**</details>

### CODE REVIEW

**Review by sbalaji1192 — APPROVED** [review]

**Comment by sbalaji1192** [comment]
@vicky-primathon Lets get this tested before merging to the release

**Comment by shwetha-ramesh** [comment]
@vicky-primathon tested this PR. DP looks good. There is no UI overlap. Ellipsis is now added for long search text.
image

Moving to Done

**Comment by shwetha-ramesh** [comment]
@vicky-primathon tested this PR. DP looks good for Table widget. Ellipsis is now seen and there is no UI overlap.

However similar issue is observed in Currencyinput & Phoneinput widget
image

**Comment by YogeshJayaseelan** [comment]
@vicky-primathon Tested this PR and looks good now on table search , Currency and Phone Widget

**Pull request merged**
