### PR TITLE
fix: EE sync failure merge conflict

### PR DESCRIPTION
**Pull request by sumitsum**
- Change error code to avoid conflict with identical error code in the EE repo. 
- https://theappsmith.slack.com/archives/CGBPVEJ5C/p1689685924631149?thread_ts=1689678350.353869&cid=CGBPVEJ5C

### CODE REVIEW

**Review by nidhi-nair — APPROVED** [review]

**Comment by sumitsum** [comment]
Force merging as per the conversation [here](https://theappsmith.slack.com/archives/CGBPVEJ5C/p1689746137113229?thread_ts=1689692778.871619&cid=CGBPVEJ5C).

**Pull request merged**
