### PR TITLE
fix: offset while pasting widget from mouse position in Desktop mode

### LINKED ISSUE #18710: [Bug]: Offset while pasting the widget on canvas in desktop mode
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

There seems to be an offset while pasting the widget on cavas using the mouse position while on desktop mode.

### Steps To Reproduce

1. Copy a widget
2. Switch app to Desktop mode
3. Resize the browser window to make it smaller
4. un-select all widgets
5. Move mouse pointer to an empty space on canvas
6. press cmd + V
7. Observe that there is an offset while pasting the widget near the mouse pointer

### Public Sample App

_No response_

### Issue video log

https://loom.com/share/b1f64851661f4547bd5848a8a291cf5e

### Version

Cloud / Self hosted

### PR DESCRIPTION
**Pull request by rahulramesha**
## Description

The canvas used to calculate the mouse position and grid props gets truncated in Desktop mode because of the size of the browser. So using drop target to calculate the values whose size does not change.

Fixes #18710

Media

https://user-images.githubusercontent.com/71900764/209565076-e18ee424-bdd4-4410-a82a-d8d06f7cbac9.mp4

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manual
Was unable to add cypress test for the same, It does not seem to be recognising mouse positions while verifying positions

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Comment by marks0351** [comment]
unrelated to the PR, i think getStickyCanvasName and getSlidingCanvasName both are misleading.
`div-selection-${widgetId}` - is the sliding arena (getSlidingArenaName)
`canvas-selection-${widgetId}` - is the sticky canvas(getStickyCanvasName).
it is my bad that i missed this during reviewing copy paste.
@rahulramesha cud you replace these functions with appropriate names.

**Review by marks0351 — CHANGES_REQUESTED** [review]
the PR looks good. 
have suggested a few improvements for existing code to make it more readable.

**Review by marks0351 — APPROVED** [review]

**Comment by Sripriya93** [comment]
Working as expected, tried to copy paste in the canvas and also in container and tabs

**Pull request merged**
