### PR TITLE
docs: Updating contribution guidelines

### PR DESCRIPTION
**Pull request by Pranay105**
The contribution guidelines for documentation are outdated due to the recent migration. Here are the fixes/updates -
- Removed the following files from `contribution/docs/` -
  - [CONTRIBUTING.md](https://github.com/appsmithorg/appsmith/blob/release/contributions/docs/CONTRIBUTING.md)
  - [DB Integrations.md](https://github.com/appsmithorg/appsmith/blob/release/contributions/docs/DB%20Integrations.md)
  - [UploadingAssets.md](https://github.com/appsmithorg/appsmith/blob/release/contributions/docs/UploadingAssets.md)
  - [Widgets.md](https://github.com/appsmithorg/appsmith/blob/release/contributions/docs/Widgets.md)
  - [adding_guides.md](https://github.com/appsmithorg/appsmith/blob/release/contributions/docs/adding_guides.md)
- Removed [Documentation Improvement](https://github.com/appsmithorg/appsmith/blob/release/.github/ISSUE_TEMPLATE/--documentation-improvement.yaml) template as we have created [new templates](https://github.com/appsmithorg/appsmith-docs/issues/new/choose) in the [appsmith-docs](https://github.com/appsmithorg/appsmith-docs) repository.
- Updated the relevant links in the [Documentation Improvement](https://github.com/appsmithorg/appsmith/blob/release/CONTRIBUTING.md#-improve-the-documentation) section ( template links and contribution guidelines for docs) of [CONTRIBUTING.md](https://github.com/appsmithorg/appsmith/blob/release/CONTRIBUTING.md) file.

### CODE REVIEW

**Comment by Pranay105** [comment]
@Aishwarya-U-R updated a link in [TestAutomation.md](https://github.com/appsmithorg/appsmith/blob/release/contributions/docs/TestAutomation.md) (the hyperlink on Appsmith locally was giving a 404 error.) Please have a look.

**Review by jnikhila — APPROVED** [review]
Looks good to me.

**Review by somangshu — APPROVED** [review]

**Review by rimildeyjsr — APPROVED** [review]

**Comment by jnikhila** [comment]
@somangshu / @rimildeyjsr - Does this PR needs auto-merge? Could you please do the needful?

**Comment by somangshu** [comment]
Should this skip the changelog? @jnikhila 
I can force merge in that case

**Comment by jnikhila** [comment]
> Should this skip the changelog? @jnikhila
> I can force merge in that case

Sorry! I'm not sure about the changelog.

**Pull request merged**
