### PR TITLE
fix: Disturbed canvas due to css transition in chrome

### LINKED ISSUE #25697: [Bug]: Canvas layout is disturbed for codescanner/video/camera widgets
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Attached video : 
https://www.loom.com/share/568af83fa0504a708e2cd08099d89766?sid=e202c0c3-b206-4eea-bc3a-756a90d06682

Note : Not reproducible on Production but exists on release.

**Note : Clear the cookies and cache**

### Steps To Reproduce

1. Go to canvas
2. drag and drop any of the widgets like Codescanner/camera/video 
3. Make sure property pane is opened 
4. Go to  preview mode and then come back to canvas via clicking preview option again

### Public Sample App

_No response_

### Environment

Release

### Issue video log

https://www.loom.com/share/568af83fa0504a708e2cd08099d89766?sid=e202c0c3-b206-4eea-bc3a-756a90d06682

### Version

Appsmith Business v1.9.30-SNAPSHOT

### PR DESCRIPTION
**Pull request by rahulramesha**
## Description
This PR changes the CSS transitions  on different components so that it prevents the Disturbed canvas issue on chrome..

#### PR fixes following issue(s)
Fixes #25697 

#### Type of change
- Bug fix (non-breaking change which fixes an issue)

#### How Has This Been Tested?
This fix has been tested manually. Since the issue is inconsistent automated tests cannot be added

#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by jsartisan — APPROVED** [review]

**Review by jsartisan — APPROVED** [review]

**Review by aswathkk — APPROVED** [review]

**Comment by rahulramesha** [comment]
@kavitasmoolya could you please verify with the above dp?

**Comment by kavitasmoolya** [comment]
> @kavitasmoolya could you please verify with the above dp?

Looks good to me @rahulramesha

**Pull request merged**
