### PR TITLE
fix: Button group icon aligment improved

### LINKED ISSUE #9547: [Bug]: Button group icon is not properly aligned
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I add a button group widget from the widget panel to the canvas, the created widget have icons which are not properly aligned with texts.

Screenshot 2021-12-03 at 12 41 52 PM

I'm using Firefox 94.0.1 (64-bit) on Mac

### Steps To Reproduce

1. Open canvas
2. drag button group widget from widget panel

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by techbhavin**
## Description

>  updated an alignment of icon in button group widget

Fixes #9547 

## Type of change

- Bugfix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/buttongroup-icon-alignment 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 55.12 **(-0.01)** | 37.04 **(-0.01)** | 34.02 **(0)** | 55.65 **(0)**
 :red_circle: | app/client/src/widgets/ButtonGroupWidget/component/index.tsx | 25.3 **(-0.31)** | 11.02 **(-0.36)** | 5 **(0)** | 27.78 **(-0.39)**</details>

### CODE REVIEW

**Review by jsartisan — DISMISSED** [review]

**Comment by wealthz01** [comment]
Who

**Comment by vivekverma2312** [comment]
@techbhavin The alignment is fine on Deploy Preview.

**Comment by shwetha-ramesh** [comment]
@techbhavin tested this PR. Icon and text are aligned.
Moving to Done.

**Review by jsartisan — APPROVED** [review]

**Pull request merged**
