### PR TITLE
Fix: Adding checks before we check for disallowCopy

### LINKED ISSUE #6030: [Bug] TypeError: Cannot read property 'disallowCopy' of undefined
Sentry Issue: [APPSMITH-ZA](https://sentry.io/organizations/appsmith/issues/2522520932/?referrer=github_integration)

```
TypeError: Cannot read property 'disallowCopy' of undefined
  at None (sagas/WidgetOperationSagas.tsx:1387:30)
  at Array.some (<anonymous>)
  at call (sagas/WidgetOperationSagas.tsx:1386:44)
  at copySelectedWidget (pages/Editor/GlobalHotKeys.tsx:233:31)
  at Object.onKeyDown (pages/Editor/GlobalHotKeys.tsx:127:26)
...
(35 additional frame(s) were not displayed)
```

### LINKED ISSUE #6167: [Bug] TypeError: Cannot read property 'children' of undefined
Sentry Issue: [APPSMITH-ZG](https://sentry.io/organizations/appsmith/issues/2527574769/?referrer=github_integration)

```
TypeError: Cannot read property 'children' of undefined
  at None (sagas/WidgetOperationSagas.tsx:808:61)
  at Array.forEach (<anonymous>)
  at None (sagas/WidgetOperationSagas.tsx:762:24)
  at Array.reduce (<anonymous>)
  at call (sagas/WidgetOperationSagas.tsx:744:46)
...
(10 additional frame(s) were not displayed)
```

### LINKED ISSUE #6168: [Bug] TypeError: Cannot read property 'disallowCopy' of undefined
Sentry Issue: [APPSMITH-ZK](https://sentry.io/organizations/appsmith/issues/2530699109/?referrer=github_integration)

```
TypeError: Cannot read property 'disallowCopy' of undefined
  at None (sagas/WidgetOperationSagas.tsx:1394:30)
  at Array.some (<anonymous>)
  at call (sagas/WidgetOperationSagas.tsx:1393:44)
  at copySelectedWidget (pages/Editor/GlobalHotKeys.tsx:233:31)
  at Object.onKeyDown (pages/Editor/GlobalHotKeys.tsx:127:26)
...
(35 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by marks0351**
## Description

Sentry#6030 error when other items in the list widget expect for the first item are copied.
Sentry#6167 error when any widget inside a tab is deleted and before the undo toast goes away if the user deletes the parent tab and manages to click on undo.

Fixes #6030
Fixes #6167
FIxes #6168 

> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/6030 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 53.35 **(-0.01)** | 34.79 **(-0.01)** | 31.46 **(-0.02)** | 53.9 **(-0.01)**
 :red_circle: | app/client/src/sagas/WidgetOperationSagas.tsx | 44.22 **(-0.07)** | 30.89 **(0.36)** | 48.86 **(-0.57)** | 44.52 **(-0.07)**
 :red_circle: | app/client/src/utils/helpers.tsx | 54.88 **(-1.83)** | 28.77 **(-4.11)** | 25 **(-3.57)** | 48.84 **(-1.55)**</details>

### CODE REVIEW

**Review by jsartisan — DISMISSED** [review]

**Review by jsartisan — APPROVED** [review]

**Review by jsartisan — DISMISSED** [review]

**Review by somangshu — DISMISSED** [review]
Approving to run tests

**Review by jsartisan — DISMISSED** [review]

**Comment by vivekverma2312** [comment]
@marks0351 I am still getting `Cannot read property 'defaultProperties' of undefined` error for #6167 
https://www.loom.com/share/91d59924f96547959686ce26949d993d

#6030 This is working fine.

**Comment by vivekverma2312** [comment]
@marks0351 I am getting error on undo tab widget for issue #6167 
https://www.loom.com/share/750dbb1b4aca4e50914f3aba5a89b306

**Review by somangshu — DISMISSED** [review]

**Comment by vivekverma2312** [comment]
@marks0351 Working fine on latest deploy preview.

**Comment by vivekverma2312** [comment]
@marks0351 LGTM

**Review by jsartisan — APPROVED** [review]

**Pull request merged**
