### PR TITLE
fix: update HikariCP package version

### LINKED ISSUE #17803: [Task]: Update HikariCP version to the latest
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- Update HikariCP version to the latest stable version as of now.

### PR DESCRIPTION
**Pull request by sumitsum**
## Description
- update HikariCP package version. This update will allow us to use new configuration knobs that HikariCP has added as well as the fixes that would have gone in making the new version of the package. 

Fixes #17803 

## Type of change
- Chore

## How Has This Been Tested?
- Not possible to write a separate automated test for this at the moment. As long as all the CI tests pass it should be sufficient. 

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by nidhi-nair — APPROVED** [review]

**Comment by sumitsum** [comment]
Adding `test plan approved` label since it is only a POM file change cc: @prapullac

**Comment by Rhitottam** [comment]
/perf-test ref=rhito/feat-create-run-meta-before-test-starts-compare-lt-st-for-prev-runs

**Pull request merged**
