### PR TITLE
fix: prevent cyclic dependency with action.clear

### LINKED ISSUE #11633: [Bug]: Cyclic dependency when action.clear is called
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

With a particular binding, if action.clear() is called, a cyclic dependency error occurs

### Steps To Reproduce

Follow this steps exactly or else this error cannot be reproduced

1. Have a query that returns data like the users query
2. Run the query
3. Add an Input and 2 Button widgets
4. Add a binding to the Input widget `{{Query1.data[2].name}}` (an index access is necessary)
5. Go back to the query and turn of on page load
6. Remove the binding on the input
7. on the two buttons bind {{Query1.run()}} and {{Query2.run()}} respectively
8. refresh the page in edit mode
9. Click the button that will run the query
10. Add the binding again on the Input widget `{{Query1.data[2].name}}`
11. Click the button that will clear the query

### Environment

Production

### Version

Cloud

### LINKED ISSUE #12367: [Bug]: Dependency persists even after removal of binding to an Api
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After the removal of a binding to an API on the submit field of a `Button Widget`, there is still a dependency on that API;  As seen by the loading state when the API is executing.

### Steps To Reproduce

[LOOM DEMO](https://www.loom.com/share/b43672a56cec4e7cb86851356ea81081)

### Public Sample App

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by ohansFavour**
## Description

Fixes #11633 
Fixes #12367 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Jest

## Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/action-clear-creates-cyclic-dependency 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 56.33 **(-0.01)** | 37.73 **(-0.01)** | 35.94 **(0)** | 56.56 **(0)**
 :red_circle: | app/client/src/selectors/commentsSelectors.ts | 83.61 **(-1.64)** | 61.76 **(-2.95)** | 73.33 **(0)** | 88.24 **(-2.35)**
 :green_circle: | app/client/src/utils/WorkerUtil.ts | 89.76 **(0.78)** | 72.55 **(1.96)** | 100 **(0)** | 93.33 **(0.95)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.71 **(-0.23)** | 40.83 **(-0.84)** | 36.21 **(0)** | 56.74 **(-0.25)**
 :red_circle: | app/client/src/workers/DataTreeEvaluator.ts | 76.35 **(-0.12)** | 57.51 **(0)** | 75 **(0)** | 76.07 **(-0.13)**
 :green_circle: | app/client/src/workers/evaluationUtils.ts | 62.24 **(0.23)** | 60.2 **(-0.1)** | 67.19 **(0)** | 60.37 **(0.26)**</details>

### CODE REVIEW

**Review by ramsaptami — APPROVED** [review]
Changes have been tested and verified on DP

**Review by eco-monk — APPROVED** [review]

**Pull request merged**
