### PR TITLE
feat: Datasource exportWithConfiguration checked while forking/cloning app to a workspace

### LINKED ISSUE #21691: [Enahcement]: ExportWithConfiguration flag is ignored when forking app with Authenticated REST API Datasource
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When forking an app with an Authenticated REST API datasource, the new workspace receives a working copy of the datasource (with credentials intact) regardless of the `exportWithConfiguration` flag's value. 

This property is missing in the app JSON at first, so I tested all 3 states:
`exportWithConfiguration=true` 
`exportWithConfiguration=false` 
`exportWithConfiguration=undefined` _initial state_ 

In all cases, the new app continues to function with the API credentials intact in the new workspace. This flag is not being checked when forking an app. 

### Steps To Reproduce

1. Create an app with an authenticated API datasource
2. Enable forking of an app by setting `forkingEnabled=true` 
3. View the app from a different account, then fork it to a new workspace
4. Observe that the datasource is copied with credentials and the app continues to function. 

Note: The forkingEnabled and exportWithConfiguration flags are not exposed on the UI. These values must be set via MongoDB query. This can be done using the Template Uploader app. 

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

Appsmith v1.9.12-SNAPSHOT

### PR DESCRIPTION
**Pull request by NilanshBansal**
## Description

This PR adds check for `exportWithConfiguration` flag while cloning/forking any application in a new workspace. 
If `exportWithConfiguration` flag is set to True in the application, the datasource credentials are shared.
For any application, `exportWithConfiguration` is False by default i.e. datasource credentials are not shared. 

Fixes #21691 

## Type of change

- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested?

- JUnit

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by nayan-rafiq — APPROVED** [review]
LGTM

**Review by AnaghHegde — APPROVED** [review]

**Comment by NilanshBansal** [comment]
Closing this PR as using the same flag `exportWithConfiguration` for exporting and forking is not the best possible solution. 
We are introducing a new field `forkWithConfiguration`, raising a separate PR for this.

**Pull request closed without merging**
