### PR TITLE
fix: added allowDeselection in ads/dropdown

### LINKED ISSUE #11484: [Bug]: Drop-down option is getting deselected on second click on property pane
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://www.loom.com/share/db505685cf394c94a2cb3d7c5504f441

### Steps To Reproduce

1. Drag and drop a button widget
2. Click on placement property
3. Change the default selected option
4. Click on same option again
5. Observe that the option is getting deselected

### Environment

Release

### Version

Cloud

### PR DESCRIPTION
**Pull request by rashmi-rai**
## Description

Fixes #11484

Fixes dropdown height in case of multi-selection.
Fixes deselection of values in single selection.
Added `allowDeselection` in ads/Dropdown. This will prevent behaviour of deselection of selected value in single select.

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/dropdown-selection 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 55.74 **(0.02)** | 37.08 **(0.02)** | 35.82 **(0.02)** | 56.1 **(0.02)**
 :green_circle: | app/client/src/components/ads/Dropdown.tsx | 84.23 **(3.3)** | 62.76 **(1.67)** | 73.61 **(4.17)** | 83.26 **(3.6)**</details>

### CODE REVIEW

**Comment by vivekverma2312** [comment]
@rashmi-rai Tested the issue and now it's working fine.
cc: @aswathkk @Tooluloope

**Review by Irongade — APPROVED** [review]

**Pull request merged**
