### PR TITLE
fix: Fix table height issue

### LINKED ISSUE #23697: [Bug]: Lower boundary for table is missing in the query response.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Ref: https://theappsmith.slack.com/archives/C040LHZN03V/p1684916741025529 
Screenshot 2023-05-24 at 1 50 37 PM

### Steps To Reproduce

Ref: https://theappsmith.slack.com/archives/C040LHZN03V/p1684916741025529 

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

cloud, self hosted

### PR DESCRIPTION
**Pull request by Irongade**
The table height seems to always be higher than the total height of its rows. This PR ensures the height of the table fits the content perfectly.

Fixes #23697 

- Bug fix (non-breaking change which fixes an issue)

- [x] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [x] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by AmanAgarwal041 — APPROVED** [review]

**Comment by tanvibhakta** [comment]
I can't seem to find the correct issue, can you take another look and drop a link?

**Comment by Irongade** [comment]
> I can't seem to find the correct issue, can you take another look and drop a link?

Done @tanvibhakta

**Comment by tanvibhakta** [comment]
I see the issue still exists.

**Comment by tanvibhakta** [comment]
Screenshot 2023-06-13 at 2 52 04 PM

credentials: test@appsmith.com/test@appsmith.com

**Comment by Irongade** [comment]
> I see the issue still exists.

No it doesn't, Notice that the table container (The blue background in the picture below) does not extend to fill the entire height of the response view

Screenshot 2023-06-13 at 10 24 55

**Comment by prapullc** [comment]
Hey Ade I dont see the black finishing line on the table

**Review by AmanAgarwal041 — APPROVED** [review]

**Pull request merged**
