### PR TITLE
fix: show library diffs in git modal

### LINKED ISSUE #19646: [Task] Use a different JS script for Supabase
The current Supabase script throws errors during usage. However, [this script ](https://cdn.jsdelivr.net/npm/@supabase/supabase-js@1) works fine. Please point the Supabase script to the new one to prevent errors.

### LINKED ISSUE #19691: [Task] Show library changes in git modal

### PR DESCRIPTION
**Pull request by arunvjn**
## Description
This PR contains some design changes and modifications to recommended libraries

* Added Library modifications in git status modal.
* Removed segment from recommended libraries.
* Added AWS-SDK.
* Added Papa parse 5.
* Added Appwrite.
* Removed the URL regex that checks to see if the URL ends with .js
* Changed supabase library URL to one that works with Appsmith.
* Added animation to libraries section in explorer.

Fixes #19691
Fixes #19646 

## How Has This Been Tested?
- Manual
- Jest

### Test Plan
https://github.com/appsmithorg/TestSmith/issues/2125

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [x] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by Rishabh-Rathod — DISMISSED** [review]
The changes look good to me.

**Comment by ramsaptami** [comment]
Gtg to release. All tests have been completed.
CC: @arunvjn

**Review by albinAppsmith — APPROVED** [review]

**Pull request merged**
