### PR TITLE
fix: add getMetaPropertiesMap() to code scanner

### LINKED ISSUE #16900: [Bug]: Code scanner widget does not reset its internal property
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On resetting the code scanner widget, its internal property value is not reset

### Steps To Reproduce

1. Drop a code scanner widget on the canvas
2. Use a text widget to bind its internal property `CodeScanner1.value`
3. Scan a QA code and observe text widget display the stored value of the code scanner
4. Use a button widget to reset the code scanner and observe that the action is executed but the internal properties are not reset

https://www.loom.com/share/ecd83ef1189b4f05b7c0f6707c4a92ec

### Public Sample App

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by dhruvikn**
## Description
Define getMetaPropertiedsMap for code scanner. Now the widget can reset using resetWidget()

Fixes #16900

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manually
  - Drop a code scanner widget on the canvas
  - Use a text widget to bind its internal property CodeScanner1.value
  - Scan a QR code and observe text widget display the stored value of the code scanner
  - Use a button widget to reset the code scanner and observe that the action is executed but the internal properties are not reset

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by sbalaji1192 — APPROVED** [review]

**Comment by chandannkumar** [comment]
Tested this PR and LGTM
- Tested resetWidget functionality
- Tested functionality on adding widgets on container widgets and modals as well

**Pull request merged**
