### PR TITLE
fix: URL column in table widget not working correctly

### LINKED ISSUE #16108: [Bug]: Issue occurring in the URL column of Table widget
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I define a column type as URL in a table widget, and pass both display and computed URL, the relative path is taken into consideration and not absolute URL.

### Steps To Reproduce

When I set only "Computed Value", on clicking the URL from the table takes me to the correct link (absolute URL).
But when I add the "Display Name" as well, then clicking on the URL takes only the relative path and I land on an incorrect link (relative path).

I have attached a video below about the issue.
https://user-images.githubusercontent.com/5265702/185100492-8a4392d3-3425-48d8-b2f5-31ec943a5620.mov

### Public Sample App

_No response_

### Version

1.7.13

### PR DESCRIPTION
**Pull request by souma-ghosh**
## Description

> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change.

Fixes #16108 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manually tested

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by sbalaji1192 — COMMENTED** [review]
Please add cypress cases

**Review by sbalaji1192 — DISMISSED** [review]

**Comment by chandannkumar** [comment]
Tested this PR and working as expected

**Pull request merged**
