### PR TITLE
feat: Migrated color picker v2 to property controls

### LINKED ISSUE #17361: [Task]: Move color picker v2 from ads folder to property controls
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- Move ColorPickerV2 component propertyControls folder.
- Replace the imports for the same.

### PR DESCRIPTION
**Pull request by albinAppsmith**
## Description

Moved ColorPickerV2 component from ads folder to propertyControls. This component is not being migrated since it is using redux state and it's being used only in property pane.

Fixes #17361

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Tested in local

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by jsartisan — APPROVED** [review]

**Review by tanvibhakta — APPROVED** [review]

**Comment by shadabbuchh** [comment]
This PR has been tested. No issues found.

**Pull request merged**
