### PR TITLE
fix: #5980 added clear all filters button and close filter pane button

### LINKED ISSUE #5980: [Enhancement] Table Widget Filter Pane - clear button to remove all filter
## Description
Deploy Preview - https://github.com/appsmithorg/appsmith/pull/5886
Table Widget - Filter pane - Suggestion to have clear button in the filter pane so that the user can clear applied filters without removing the applied filters.

### Steps to reproduce the behaviour:

1.Launch Appmsith app in the Deploy Preview - https://github.com/appsmithorg/appsmith/pull/5886
2.Drag and Drop Table Widget 
3.Open filter pane 
4.Apply any filter and check there is no option to clear applied filter

### Important Details

- Version: [11.3 ]
- OS: [MacOS  Big Sur]
- Browser [chrome, safari]
- Environment [
Screenshot 2021-07-20 at 9 30 12 AM
deploy preview]

## Figma Designs Link
New modal design: https://www.figma.com/file/trkiMc12VVpQBqsm7natiU/Table-Changes-Wed-7-Apr-2021?node-id=816%3A1266
Cancel (X) button on hover: https://www.figma.com/file/trkiMc12VVpQBqsm7natiU/Table-Changes-Wed-7-Apr-2021?node-id=841%3A1186

### LINKED ISSUE #8476: [Bug]: Unable to close Filter popup without choosing a filter selection
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On a table widget, clicking the Filter button at the top opens a movable Filter popup. But then this popup is impossible to close, unless a selection for filtering is made.

https://user-images.githubusercontent.com/120119/136984927-9efc9a04-5502-4d2d-b654-4049a0c5d463.mov

### Steps To Reproduce

```markdown
Just open Filter box for a Table widget and try to close it.
```

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by vibhandikyash**
## Description

> Added button for clearing all filters.

Fixes #5980 
Fixes #8476

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Tested locally.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/5980-table-widget-filter-pane-enhancement 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 54.65 **(-0.01)** | 36.34 **(-0.01)** | 33.11 **(0)** | 55.17 **(-0.01)**
 :red_circle: | app/client/src/selectors/commentsSelectors.ts | 83.61 **(-1.64)** | 61.76 **(-2.95)** | 73.33 **(0)** | 88.24 **(-2.35)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.04 **(-0.22)** | 40.42 **(-0.83)** | 34.48 **(0)** | 55.96 **(-0.26)**
 :green_circle: | app/client/src/widgets/TableWidget/component/TableFilterPaneContent.tsx | 31.58 **(1.39)** | 29.27 **(0)** | 0 **(0)** | 32.73 **(1.36)**</details>

### CODE REVIEW

**Review by somangshu — DISMISSED** [review]

**Comment by vibhandikyash** [comment]
https://github.com/appsmithorg/appsmith/actions/runs/1448308731

**Comment by somangshu** [comment]
@vibhandikyash when can we merge this

**Review by jsartisan — APPROVED** [review]

**Pull request merged**
