### PR TITLE
fix: reorder IconButtonWidget properties

### LINKED ISSUE #7063: [Bug] Icon Widget: reorder properties in the logical order
## Description

For the IconButton widget following is the order for properties:
- General
    - Icon
    - disable
    - visible
- Actions 
- Styles: the rest of the styling properties go here in the order its currently in

### PR DESCRIPTION
**Pull request by aswathkk**
## Description

Re-orders IconButtonWidget properties

Fixes #7063 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Manually tested

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by somangshu — APPROVED** [review]
LGTM.

@allcontributor add @aswathkk for code

**Comment by somangshu** [comment]
@all-contributors please add @aswathkk for code

**Comment by somangshu** [comment]
@aswathkk please remerge the release here once!

**Review by somangshu — APPROVED** [review]

**Comment by somangshu** [comment]
@aswathkk looks like this a forked repository and hence the tests are not running, Can you clone the appsmith repo and then create a new PR with the above change. Close this later

**Comment by aswathkk** [comment]
@somangshu Am I not supposed to push to the forked repository and raise PR?

**Comment by somangshu** [comment]
@aswathkk you are supposed to clone the original appsmith repo, Create a new branch, Make changes and create the PR

Now that you have push / pull access this should be possible

**Comment by aswathkk** [comment]
Closing this since a new PR has been raised #7088

**Pull request closed without merging**
