### PR TITLE
Fixed next working on last page table widget

### LINKED ISSUE #22477: [Bug]: Disable clicking on Next page button when Table record reached to last page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In Table widget, when pagination reach to it's last page the icon seems disabled but we can still Click on it and see rendering of data.

### Steps To Reproduce

1. Drag & drop a Table widget
2. Run a server side pagination query `SELECT * FROM users ORDER BY id LIMIT {{Table2.pageSize}} offset {{Table2.pageOffset}}`
3. Enable server side pagination and configure onPageChange & Total records
4. Reach to last page of the table records
5. Observe that Next page button is disabled but clickable

### Public Sample App

_No response_

### Environment

Production

### Issue video log

https://www.loom.com/share/bad8d690647c4583b7e82d6092a1ccbe

### Version

Cloud / Production

### PR DESCRIPTION
**Pull request by harrybasra95**
## Description

Added the disable condition on onClick event
#### PR fixes following issue(s)
Fixes #22477

#### Type of change
- Bug fix (non-breaking change which fixes an issue)
#### How Has This Been Tested?
- [ * ] Manual
#### Test Plan
1. Drag & drop a Table widget
2. Run a server side pagination query SELECT * FROM users ORDER BY id LIMIT {{Table2.selectedRow.pageSize}} offset {{Table2.pageOffset}}
3. Enable server side pagination and configure onPageChange & Total records
4. Reach to last page of the table records
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Comment by dilippitchika** [comment]
@keyurparalkar can you check this pr?

**Comment by dilippitchika** [comment]
CC @somangshu

**Review by keyurparalkar — COMMENTED** [review]
@harrybasra95 Please add cypress test for this fix.

**Comment by keyurparalkar** [comment]
@somangshu I will take this up, add a cypress test to it and move it to QA

**Comment by somangshu** [comment]
@keyurparalkar re-raise it internally if required to avoid hassle managing this external PR

**Comment by chandannkumar** [comment]
@harrybasra95 @keyurparalkar 
I can still observe the issue on the generated DP
https://www.loom.com/share/9c41f3a963894fc0a93348b8dc749038?sid=d680eb4d-d528-4b4c-89ee-eeaf29d39cd6

**Comment by keyurparalkar** [comment]
Closing this PR since there wasn't any activity from the contributor. Will raise the PR and move forward.

**Pull request closed without merging**
