### PR TITLE
fix: tighten controls for fuzzy search in widget sidebar

### PR DESCRIPTION
**Pull request by prsidhu**
## Description

Issue - Widget search in sidebar brings up unrelated widgets.
Cause - Loose controls for fuzzy search (threshold and distance).
Fix - Tighten the aforementioned controls. Since the total number of widgets in only 40 and not likely to grow exponentially, performing a more strict search will yield better results without impacting performance.

Fixes # (issue)

https://github.com/appsmithorg/appsmith/issues/14848

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

1. Create an app.
2. In the widget sidebar, search for phrase: "submit". The result should render three button widgets and nothing else.
3. Clear the search. Search for phrase: "Upload". The result should only display the file upload widget.
4. Refer to the original issue to check for other test phrases.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by SatishGandham — APPROVED** [review]

**Comment by aswathkk** [comment]
Hi @prsidhu,
After this change, the search is not respecting any typos. Is this intentional?

**Comment by prsidhu** [comment]
> Hi @prsidhu, After this change, the search is not respecting any typos. Is this intentional?

@aswathkk That would conflict with ask of the original issue that is being solved, [https://github.com/appsmithorg/appsmith/issues/14848] which demands precision.

@rohitagarwal88 How do you suggest we proceed? Do we need product feedback on this?

**Comment by rohitagarwal88** [comment]
@prsidhu let's have a product opinion. @dilippitchika please help here. @prsidhu went for precision which in turn brought in new issues. Check the comments.

**Review by SatishGandham — APPROVED** [review]

**Pull request merged**
