### PR TITLE
fix: Replace initEval binding success event

### LINKED ISSUE #14642: [Bug]: User Application crash with `out of memory error`
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

A discord user is facing out of memory error when opening Appsmith application in edit mode. Everything works fine in view mode.

Video where user is showing RAM consumption and crash issue - https://monosnap.com/file/za6wp0F6fIjrGh7kGO6UOFhQDGzfi9

Discord link - https://discord.com/channels/725602949748752515/985986271073693697/986691121205882982

### Steps To Reproduce

Not yet clear, @Rishabh-Rathod can help with application where this issue is reproducible.

### Public Sample App

_No response_

### Version

1.7.2

### PR DESCRIPTION
**Pull request by Rishabh-Rathod**
## Description

We remove logging successful binding for 1st evaluation as we don't aim to capture events for bindings not added by user in this case.

Fixes #14642

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by Rishabh-Rathod** [comment]
Using segment analytics batching of API seems better solution here.

**Review by rimildeyjsr — APPROVED** [review]
LGTM

**Comment by ramsaptami** [comment]
Tested user's app on DP and the issue is not reproducible anymore

**Pull request merged**
