### PR TITLE
fix: fix git related issues in Custom JS Library feature

### LINKED ISSUE #19764: [Bug]: Git merge does not work for custom libraries and queries
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Git merge does not work for custom libraries and datasource query even though merge action returns a success message

### Steps To Reproduce

1. Go to app at [this](https://release.app.appsmith.com/app/cloak-of-invisibility-copy/page1-63bfd27a9998a05cbaa8e21d/edit?branch=master) location and try to merge the child branch to the maste branch.
2. Observe the success message after merge but both branches are not in sync

[git merge does not work_logs.zip](https://github.com/appsmithorg/appsmith/files/10401984/git.merge.does.not.work_logs.zip)

### Public Sample App

https://release.app.appsmith.com/app/cloak-of-invisibility-copy/page1-63bfd27a9998a05cbaa8e21d/edit?branch=master

### Issue video log

https://www.loom.com/share/6dbb5ab9400b47ec847b19213302a1d8

### Version

Cloud

### PR DESCRIPTION
**Pull request by sumitsum**
## Description
- Remove published JS libraries from becoming part of the exported application when exporting for Git. 
  - This was causing a problem with git status because git status would consider the published libraries as well when fetching git diff however, when creating commit only unpublished libraries are used. 
  - I am not sure why, but it seems to fix the git merge issue as well - not sure at the moment. Waiting for a verification from QA on this. (Update: QA has verified this as well)
 
Fixes #19764 #19766 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manual
- JUnit TC

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Comment by Parthvi12** [comment]
This issue https://github.com/appsmithorg/appsmith/issues/19766 is fixed , verified on the PR.

**Review by abhvsn — APPROVED** [review]
LGTM

**Comment by arunvjn** [comment]
@sumitsum Would you be able to incorporate this in the PR if this is a small fix ?
https://github.com/appsmithorg/appsmith/pull/19929#issuecomment-1397978194

**Comment by sumitsum** [comment]
> @sumitsum Please look at [#19929 (comment)](https://github.com/appsmithorg/appsmith/pull/19929#issuecomment-1397978194). Would you be able to incorporate this in the PR if this is a small fix ?

@arunvjn as Parthvi has mentioned here, this issue has already been taken care of in this PR: 
https://github.com/appsmithorg/appsmith/pull/19929#issuecomment-1397986753

**Pull request merged**
