### PR TITLE
chore: added application name in JDBC url for connection URI

### LINKED ISSUE #22659: [Task]:  Optimisations of opened connection by Hikari CP
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks
[QA] https://app.zenhub.com/workspaces/data-platform-pod-6322a78c9f446835b89a3f82/issues/zh/8

## Descriptions

While executing the queries, the hikari CP driver opens connections which are more than expected.
This task is to explore the Plugins with Hikari Driver and find the problem, and possibly fix it as well

The following are the possible plugins to look into:
MSSql
Redshift
SnowFlake
Oracle

### PR DESCRIPTION
**Pull request by sondermanish**
## Description

This PR includes changes for:

- Snowflake
- Redshift

> TL;DR: Modifying connection string to reduce auxiliary connection to datasources in order to required properties.

Fixes #22659 

#### Type of change
- Chore (housekeeping or task changes that don't impact user perception)

#### How Has This Been Tested?
 This has been tested
- [x] Manual
- [ ] Jest
- [ ] Cypress
>
>

#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Comment by sondermanish** [comment]
The setting of applicaiton name in url seems to be exacerbating the situation, reverting the changes for redshift

**Comment by AnandShahs123** [comment]
@sondermanish - getting this message on snowflake connection. Failed to initialize pool: Invalid parameter value Appsmith%20JDBC%20Driver for parameter type APPLICATION.

**Comment by AnandShahs123** [comment]
@sondermanish - For snowflake, no data is coming on the table on executing the connection query

**Review by nidhi-nair — APPROVED** [review]

**Comment by AnandShahs123** [comment]
@sondermanish As discussed, this is tested for Snowflake. There was no extra connection found. Looks good from my end.

**Comment by sondermanish** [comment]
Manually added test plan approved as testing has been done.

**Comment by nidhi-nair** [comment]
Merging since we do not have Snowflake integration tests, server tests have passed, and manual QA has been approved.

**Pull request merged**
