### PR TITLE
feature/add a helm chart to deploy appsmith

### PR DESCRIPTION
**Pull request by jmvizcainoio**
> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Type of change

- New feature:  Add a helm chart to deploy AppSmith into Kubernetes cluster. 

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce. 
> Please also list any relevant details for your test configuration.

- Install several times in Kubernetes cluster in a staging environment. 

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by hetunandu** [comment]
@jmvizcainoio Thank you for this PR. Please do the following things before we can start the review process

- Please go through our [contribution guide](https://github.com/appsmithorg/appsmith/blob/release/contributions/CodeContributionsGuidelines.md) once to make sure you have followed all required steps
- Update the PR description to properly explain the changes requested
- Add an issue for the same (if it does not exist ) and tag it in this PR

**Comment by alonp99** [comment]
Hey, is this PR going to be merged soon?

**Comment by Hokwang** [comment]
please take care of this pr. I am waiting this.

**Comment by zdb999** [comment]
@Hokwang you asked me to take a look at this. (Just to be clear, I am not part of the Appsmith team in any way, I'm just a happy and supportive user of the project.) This Helm seems like a really good start, and it has many of the features a K8s cluster operator would want.

I think there are two issues with it, as it stands.

- There should be better support for all of the environment variables that Appsmith supports. Otherwise, you cannot fully configure the App with email and other important integrations.
-  There should be more flexibility with the Mongo database. Users should be able to use a provider other than Bitnami, and they should be able to connect to a preexisting DB. (This may already possible, but if so I'm not sure how to configure it.)

**Comment by mohanarpit** [comment]
Closing in favour of #7343

**Pull request closed without merging**
