### PR TITLE
fix: After cloning the page with JSObject creating a new branch copies all the JSObject in a single page

### LINKED ISSUE #12724: [Bug]: Js objects are merged to single page when user creates a new branch
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Js objects are merged to single page when user creates a new branch 

### Steps To Reproduce

1. Connect an application to the git 
2. Create an app with Page1
3.Add JSObject names JSObject1
4..Create new page Page2
5.Add JSObject names JSObject1
6.Clone the page 1
6.Now create a sub-branch from the master
7.All the js object will be displayed under the single page 

### Public Sample App

_No response_

### Version

release

### PR DESCRIPTION
**Pull request by abhvsn**
## Description

As per our current implementation we use `gitSyncId` to connect different resources in multiple Appsmith instances like pages, actions, JSObjects etc. This fiels should be unique across the instances for a resource in DB. 

Consider we have branch1 with JSObject1 and now user creates the branch2 from earlier branch in the same isnatnce. In this scenario we create the JSObject1 in branch2 but will have same `gitSyncId`. Considering we also have instance 2 where branch1 is already present but we are creating a branch2 from remote we can easily connect the JSObject1 from branch2 pulled from remote to already available JSObject1 of branch1 as we have same `gitSyncId`.

In the import application flow we use these gitSyncIds to find out the existing resources which can be connected to the imported resource. Also as we want to connect the resources across the instances we commit this field to repo as well.

The problem we were facing earlier was related to cloning the JSObject when we try to clone the page, this action resulted in duplicating the `gitSyncId` for 2 different resources in a single branch as we have not handled it in the actionCollection create method (Added a comment in the review to make this clear). Now that we have the JSObjects with duplicate gitSyncIds we end up accumulating all the JSObjects in a single page if the user tries to create a new branch, this happened because we fetch the resource with gitSyncId and then assign the `unpublishedCollection.defaultResources.pageId` to the imported resource.

Fixes #12724 #12000

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Manual test
> JUnit testcase

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by AnaghHegde — APPROVED** [review]
LGTM.
But does it make sense to add a test case where we do the clone operation and then do create branch ?

**Comment by abhvsn** [comment]
> LGTM. But does it make sense to add a test case where we do the clone operation and then do create branch ?

That will not be required as the root cause was cloning, resulted in incorrect assignment for `gitSyncId` in cloned JSObjects. Also we will be asking @Parthvi12 for cypress test for the exact scenario you have described here

**Comment by Parthvi12** [comment]
@abhvsn I have added tests for this bug, will add the scenario @AnaghHegde mentioned in PR https://github.com/appsmithorg/appsmith/pull/12751 and merge it, after this PR is merged.

**Pull request merged**
