### PR TITLE
feat: Progress bar widget enhancements

### LINKED ISSUE #10496: [Enhancement]: Progress bar widget enhancements
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There's no difference between indeterminate and determinate progress bar. We want to support the indeterminate or infinite loading progress bar in the widget.

### Steps To Reproduce

Select the indeterminate type of progress bar

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by wmdev0808**
## Description
- There's no difference between indeterminate and determinate progress bar. We want to support the indeterminate or infinite loading progress bar in the widget.
- Merge two widgets(Progressbar and Circular) into one.
- Support steps in Circular, either.

Fixes #10496 

## Type of change

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

## How Has This Been Tested?

- Test A
- Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: feat/10496-progress-widget 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 55.7 **(-0.02)** | 37.18 **(0.03)** | 35.41 **(-0.03)** | 55.96 **(-0.02)**
 :green_circle: | app/client/src/utils/WorkerUtil.ts | 89.76 **(0)** | 72.55 **(1.96)** | 100 **(0)** | 93.33 **(0)**
 :sparkles: :new: | **app/client/src/widgets/ProgressWidget/constants.ts** | **100** | **100** | **100** | **100**
 :sparkles: :new: | **app/client/src/widgets/ProgressWidget/index.ts** | **100** | **100** | **100** | **100**
 :sparkles: :new: | **app/client/src/widgets/ProgressWidget/component/index.tsx** | **31.31** | **42.99** | **0** | **34.07**
 :sparkles: :new: | **app/client/src/widgets/ProgressWidget/widget/index.tsx** | **55.26** | **0** | **54.55** | **57.14**</details>

### CODE REVIEW

**Review by rahulramesha — COMMENTED** [review]
Code changes look good to me. Nice work on this feature :). 

Had one doubt regarding steps, 
I feel like it should round off the progress shown to the previous progress step.

For example in the image below, 
image
It has 4 steps, with 85% progress, and 3.5 steps are shown. 
Since it is in the form of steps, it should show only the 3 steps as shown and show the 4th step should be shown only when it reaches 100%.

@somangshu need your inputs on this.

**Comment by somangshu** [comment]
> It has 4 steps, with 85% progress, and 3.5 steps are shown.
Since it is in the form of steps, it should show only the 3 steps as shown and the 4th step should be shown only when it reaches 100%.

@rahulramesha we want to take this request separately, we will raise another issue.

Otherwise please give your approval.

cc @vivekverma2312 moving this to needs QA

**Comment by vivekverma2312** [comment]
@wmdev0808 Can we please look into this [issue](https://github.com/appsmithorg/appsmith/issues/10611). I guess implementing steps on circular progress bar with this issue will be confusing in few cases.
cc: @dilippitchika Can you please leave a comment here if we need to priorities the commented issue.

**Review by rahulramesha — DISMISSED** [review]

**Comment by wmdev0808** [comment]
@vivekverma2312 ,
I've looked into the above issue.
From my understanding, he requested to let the circular progress act like linear progress.
So I've made changes for that in the latest commit.
BTW, I can't fully understand what you mean by above comment.
Could you please let me know what are you confused by?

**Review by rahulramesha — APPROVED** [review]

**Comment by dilippitchika** [comment]
@vivekverma2312 i guess the issue is fixed in this. Can you please also get this checked?

@wmdev0808 leaving notes here
1. For the circular progress infinite loading state the padding is more compared to when infinite loading is off, is there a reason for this?
Screenshot 2022-03-25 at 12 52 45 PM
Screenshot 2022-03-25 at 12 52 50 PM

2. Please remove the circular progress bar and progress bar widgets and only keep the "progress" widget. Users should not be able to see the "circular progress bar" and "progress bar" widgets in the entity list anymore.
Screenshot 2022-03-25 at 12 54 45 PM

3. Please remove the "JS" option from Infinite loading switch for now. 
Screenshot 2022-03-25 at 12 58 07 PM

**Review by rahulramesha — DISMISSED** [review]

**Comment by YogeshJayaseelan** [comment]
@wmdev0808 Tested this PR and please find the status below,

Issue 1 - When the progress is in decimal the linear type shows the decimal values but the circular type shows the rounded off value 

https://www.loom.com/share/c9c21e212e824527bb87532076cd75ea

Observation 1 - Noticed a JS option for the 'Infinite Loading' Property initially when the PR was ready and now I couldn't see the JS option on the 'Infinite Loading property. Is JS required for the 'Infinite Loading' Property?

**Comment by wmdev0808** [comment]
@YogeshJayaseelan ,
The JS toggle for "Infinite loading" has been removed according to @dilippitchika 's  request.
Please refer to No. 3 from this [comment](https://github.com/appsmithorg/appsmith/pull/12053#issuecomment-1078734155)

**Comment by YogeshJayaseelan** [comment]
@wmdev0808 Tested this PR and it is working as expected

**Review by rahulramesha — DISMISSED** [review]

**Comment by Aishwarya-U-R** [comment]
@wmdev0808 - Please move the ProgressBar_spec.js from app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/ProgressBar_spec.js to app/client/cypress/manual_TestSuite/CommentedScriptFiles/

Cypress will end in infinite loop if it finds empty spec files inside integration.

**Review by rahulramesha — APPROVED** [review]

**Pull request merged**
