### PR TITLE
fix: added placement support in button, button group, and menu widget

### LINKED ISSUE #7913: [Feature] Need more alignment options for button widget
## Description

Current button widget has text aligned to extreme right when we have an icon. Its better if we provide the user option to align the text and icon in the way they desire

Screenshot 2021-09-29 at 09 53 49

This should change for the menu button widget as well

### Requirement
- An option to provide alignment of the icon and label, centered or space-between

### PR DESCRIPTION
**Pull request by techbhavin**
## Description

>  added placement support in button, button group, and menu widget

Fixes #7913

## Type of change

- Bugfix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: feature/alignment-options-button-widget 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 55.05 **(0)** | 36.92 **(0)** | 33.92 **(0.01)** | 55.57 **(0)**
 :red_circle: | app/client/src/selectors/commentsSelectors.ts | 83.61 **(-1.64)** | 61.76 **(-2.95)** | 73.33 **(0)** | 88.24 **(-2.35)**
 :red_circle: | app/client/src/widgets/WidgetUtils.ts | 79.37 **(-5.25)** | 50 **(-9.38)** | 53.85 **(-0.7)** | 74.51 **(-6.44)**
 :red_circle: | app/client/src/widgets/ButtonGroupWidget/component/index.tsx | 25.61 **(-0.64)** | 11.38 **(0)** | 5 **(-0.26)** | 28.17 **(-0.4)**
 :green_circle: | app/client/src/widgets/ButtonWidget/component/index.tsx | 52.08 **(1.55)** | 31 **(1)** | 47.83 **(2.38)** | 51.19 **(1.79)**
 :red_circle: | app/client/src/widgets/MenuButtonWidget/component/index.tsx | 24.59 **(-0.41)** | 13.89 **(0)** | 0 **(0)** | 30 **(-0.61)**</details>

### CODE REVIEW

**Review by Tooluloope — CHANGES_REQUESTED** [review]
found an issue with the button group widget
[LOOM DEMO](https://www.loom.com/share/5109300aabe846f58fa66a002d4c905a)

Also, could you add cypress tests for these changes

**Review by Tooluloope — APPROVED** [review]

**Comment by vivekverma2312** [comment]
@techbhavin 1. If icon is not selected then selecting `Between` option in placement property does nothing.
https://www.loom.com/share/03bc17af0fcc47bd94b0e118375f00a3

**Comment by techbhavin** [comment]
@vivekverma2312  `between` property only works with an icon reason is `between`  is `justify-content: space-between`.

**Comment by vivekverma2312** [comment]
@techbhavin Deploy preview is tested and looks good.

**Pull request merged**
