### PR TITLE
fix: CSS broken after action selector redesign changes

### LINKED ISSUE #22210: [Bug]: CSS styles are broken at multiple places
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

CSS is broken at multiple places in the app due to a global style that was added in [this Action Selector Redesign PR](https://github.com/appsmithorg/appsmith/pull/21582)
A few examples of CSS broken have been added below. Since, this is a global style there is no definitive way to find out what else could be broken.
Screenshot 2023-04-10 at 12 11 16 PM
CleanShot 2023-04-10 at 12 54 53@2x

### Steps To Reproduce

Open any app dev page

### Public Sample App

_No response_

### Environment

Release

### Issue video log

_No response_

### Version

1.9.16

### PR DESCRIPTION
**Pull request by ravikp7**
## Description
After the [Action selector redesign PR](https://github.com/appsmithorg/appsmith/pull/21582) was merged into release. Due to some newly added global styles, the existing CSS was broken at few places. This PR ensures the styles added for action selector are scoped only inside the action selector popup to avoid globally applying those styles.

Fixes #22210

**Media**
Fix for the originally reported issue. See the linked issue above.
Screenshot 2023-04-10 at 2 13 20 PM

Screenshots to ensure Action selector CSS is not broken.
Without CSS styles | With CSS styles scoped inside popup
-- | --
Screenshot 2023-04-10 at 2 04 54 PM|Screenshot 2023-04-10 at 2 05 58 PM

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manual

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by rimildeyjsr — APPROVED** [review]

**Comment by ramsaptami** [comment]
LGTM, admin pages will be tested when PR is merged to release
cc: @ravikp7

**Pull request merged**
