### PR TITLE
fix: added placement default value

### LINKED ISSUE #9970: Button icon fix center position
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When i add new buton, and add new icon, text and icon move away in opposite directions

I expect center position to icon and text as in default placement settings
yCByxO1HdR

### Steps To Reproduce

Add button
Add icon
Again select placement to center

### Environment

Deploy Preview

### Version

Cloud

### PR DESCRIPTION
**Pull request by techbhavin**
## Description

> Add placement is button widget property panel

Fixes #9970 

## Type of change

- Bugfix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/button-icon-position 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 55.02 **(0)** | 36.45 **(-0.01)** | 34.43 **(0)** | 55.55 **(0)**
 :green_circle: | app/client/src/components/propertyControls/ButtonListControl.tsx | 24.72 **(0.86)** | 25 **(0)** | 9.09 **(0)** | 26.92 **(0.95)**
 :red_circle: | app/client/src/utils/WorkerUtil.ts | 88.98 **(-0.78)** | 70.59 **(-1.96)** | 100 **(0)** | 92.38 **(-0.95)**</details>

### CODE REVIEW

**Comment by YogeshJayaseelan** [comment]
@techbhavin Verified this PR and please find the status below,

Adding icons to button widget now the alignment is center

Issue 1 - Issue still exists for Menu button widget

https://www.loom.com/share/da364d9f58834d368e70c9474c04a85f

**Comment by YogeshJayaseelan** [comment]
@techbhavin Verified the fix and PR and it is working as expected now

**Review by jsartisan — APPROVED** [review]

**Pull request merged**
