### PR TITLE
chore: Remove echarts feature flag

### PR DESCRIPTION
**Pull request by rajatagrawal**
This PR removes the feature flag for ECharts. ECharts feature needs to enabled by default and doesn't need to be behind a feature flag anymore.

## Summary by CodeRabbit

- **New Features**
  - Enhanced the Chart Widget by integrating Custom ECharts as a standard option.

- **Bug Fixes**
  - Addressed the Chart Widget selection issue by marking the deprecated chart type accordingly.

- **Refactor**
  - Streamlined Chart Widget properties and configuration for better usability.
  - Improved database query performance with new indexes.

- **Tests**
  - Updated end-to-end tests to align with the Chart Widget changes.

- **Chores**
  - Removed obsolete feature flags related to charting functionalities.

### CODE REVIEW

**Review by sbalaji1192 — DISMISSED** [review]

**Review by Aishwarya-U-R — APPROVED** [review]
Proxy approval.

**Pull request merged**
