### PR TITLE
fix: Conditionally call for profile photo api

### LINKED ISSUE #9322: [Bug]: Profile pic error on console when home page is loaded
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Browser console shows errors when display pic of users in not found.

[LOOM DEMO](https://www.loom.com/share/2b646192610b4f7b908cb2daa19a02cc)

### Steps To Reproduce

1. Go to app.appsmith.com and open up console. Observe 404 errors for display pic API calls.

### Environment

Production

### Version

Cloud

Front logo [Front conversations](https://app.frontapp.com/open/top_6zcgc)

### PR DESCRIPTION
**Pull request by hetunandu**
## Description

We used to blindly call for profile photos of all users in the applications page. This lead to 404 errors getting printed in the console when the photo does not exist. After fix: #20132 we were able to conditionally decide if we wanted to call for a profile photo or not

> Removes the tons of 404 error messages from the console when a user does not have a profile photo

Fixes #9322

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual

### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by ankitakinger — COMMENTED** [review]
There are more components that are using this API. Should we update them as well?
`WorkspaceInviteUsersForm`
`RealtimeAppEditors`

**Comment by hetunandu** [comment]
> There are more components that are using this API. Should we update them as well? `WorkspaceInviteUsersForm` `RealtimeAppEditors`

Those APIs have not been updated yet. For now we are just updating the applications page

**Review by ankitakinger — APPROVED** [review]

**Pull request merged**
