### PR TITLE
fix: anonymous CE users mixpanel issue fixed

### LINKED ISSUE #27221: [Task]: Investigation of metric discrepancies between the cloud and CE numbers (Anonymous users)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

This task is to investigate the discrepancies between cloud and CE numbers for Anonymous users for an event `Execute query on own datasource`

### PR DESCRIPTION
**Pull request by sneha122**
## Description

This PR fixes discrepancy in mixpanel event numbers for anonymous CE users. For self hosted instances, in mixpanel funnel, number of Execute Action backend events was much lesser compared to corresponding frontend events, Also much lesser when compared to corresponding cloud numbers. 

**Root cause of issue**:
Issue was not because events were not getting triggered for CE for anonymous users, but issue was with the distinct Id which is assigned to each event on mixpanel. This distinct ID is based on the username, In case of logged in users, it simply gets username and uses that as distinct ID, in case of anonymous users:
- for cloud users, it sets this userId as anonymousUser which then the segment library evaluates to the value of X-Anonymous-User-Id header, this value is a unique UUID, hence we get unique distinct ID for all anonymous cloud users
- for self hosted instance, since we hash all the values, this anonymousUser username gets hashed to 68385f9726ad05c8e551a8d5be5cd8213f1e733346a9eb00e86f83df94639555 this value and the segment library considers this as a valid id and assigns it to distinct id, hence for all self hosted instances, irrespective of their device or instance id, distinct id stays the same
           
Hence it would club all such anonymous events into a single unique event for CE, thus giving lesser number in the funnel.

#### PR fixes following issue(s)
Fixes #27221 
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
#### Type of change
- Bug fix (non-breaking change which fixes an issue)
>
>
>
- [x] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by sumitsum — CHANGES_REQUESTED** [review]
Hi @sneha122 can you please add a test case for this ? One way I think we can do this by creating a new function named `shouldHashUserId(...)` and the `if` statement could be re-written as `if(shouldHashUserId(...))` - then we can write a test case for the function `shouldHashUserId` to return false on anonymous user.

**Comment by sneha122** [comment]
> shouldHashUserId

@sumitsum Added unit tests please check once

**Review by sumitsum — DISMISSED** [review]

**Review by sumitsum — APPROVED** [review]

**Comment by sneha122** [comment]
@btsgh QA is not required for this PR as it fixes issue with mixpanel config. Adding test plan approved label

**Pull request merged**
