### PR TITLE
fix: gsheet file picker ui fixes

### LINKED ISSUE #23999: [Task]: Gsheet File Picker UI/UX improvements
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Google sheet file picker improvements:
- Update title from select a file to "select google sheets to query"
- Capture events on file picker actions like close/cancel/picker
- Change default file picker view from grid to list view

### PR DESCRIPTION
**Pull request by sneha122**
## Description
This PR fixes:
- Title of the google sheet file picker dialog from select a file to "select google sheets to query"
- Change default file picker view from grid to list view
- Events like `GOOGLE_SHEET_FILE_PICKER_CANCEL` (added on file selection cancel/ close the file picker dialog), GOOGLE_SHEET_FILE_PICKER_PICKED (added on file selection complete)

#### PR fixes following issue(s)
Fixes #23999 
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
- New feature (non-breaking change which adds functionality)
>
>
>
## Testing
1 ) Create a Gsheet with scope "Selected Gsheet" 
2) Selected Gsheet must open the Filepicker 
3) Cancel the Gsheet flipicker and observe if the logs are visible 
4) Select the Gsheet from the filepicker and observe that the following is displayed 
a) Event success is displayed 
b) number of files selected must be displayed 
5) Auth for other scopes as well as try to create a query and observe the logs
6) created the query and run the query 

- [x] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [x] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [x] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by Irongade — APPROVED** [review]

**Comment by prapullc** [comment]
Have tested the PR and looks good and not identified any issue

**Pull request merged**
