### PR TITLE
fix: handle duplicate tab name in tab widget

### LINKED ISSUE #11017: [Bug]: Tab names in Tab Widget can be renamed to same name from Property Pane
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Current: The tab names should not be of same name. If you change the name from the Entity Explorer, it shows error if you are changing it to used names but from property pane the tab names can be set to same names.

Expected: The tab names should be unique, so should not be able to change to same names. 

Property Pane

### Steps To Reproduce

1. Drag and drop a tab widget.
2. Try to change the name of the tab to similar name of other tab from entity explorer, it shows error.
3. Now try to change the name of the tab to similar name of other tab from property pane, it will be changed.

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by techbhavin**
## Description

> Tab names can be renamed to the same name from the property panel in tab widget to fix the current issue 
- add validation on tab rename

Fixes #11017 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: bug/handle-duplicate-tabname 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 56.28 **(-0.02)** | 37.74 **(-0.02)** | 35.92 **(0)** | 56.51 **(-0.01)**
 :red_circle: | app/client/src/components/ads/DraggableListCard.tsx | 13.46 **(0)** | 3.17 **(-0.11)** | 0 **(0)** | 15.56 **(0)**
 :red_circle: | app/client/src/components/propertyControls/TabControl.tsx | 51.89 **(-6.78)** | 34.62 **(-10.38)** | 39.13 **(-2.98)** | 52.48 **(-5.63)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.71 **(-0.23)** | 40.83 **(-0.84)** | 36.21 **(0)** | 56.74 **(-0.25)**</details>

### CODE REVIEW

**Comment by jsartisan** [comment]
@techbhavin Can't we use validation like we do in table widget?
image

**Comment by YogeshJayaseelan** [comment]
@techbhavin Tested this PR and now Tab name does not accept the name.

@somangshu @jsartisan - Do we need to have the same behaviour for the Menu button widget as well? Currently, Menu button widget accepts the same name

**Comment by somangshu** [comment]
@YogeshJayaseelan let's raise a separate issue for that, And this time let's also mark any other user case where this might be required. Please check throughly.

**Comment by YogeshJayaseelan** [comment]
@techbhavin Tested this PR and now Tab name does not accept the same name.

**Comment by techbhavin** [comment]
> @techbhavin Can't we use validation like we do in table widget? image

@jsartisan  
validation run when isBindProperty true, that effected computed value in a table so lately we have changes isBindProperty to false. that's why validation is not implemented in the tabs widget

**Review by jsartisan — APPROVED** [review]

**Comment by somangshu** [comment]
Related test failing here @techbhavin

**Comment by techbhavin** [comment]
@somangshu 

Yes, a Related test case is failing. It works locally but fails in Ci WorkFlow. so working on it

**Review by jsartisan — APPROVED** [review]

**Pull request merged**
