### PR TITLE
fix: misalignment of checkboxes in table

### PR DESCRIPTION
**Pull request by rhlc**
> Fix for no affect of alignment in check box type column in a table

## Description
 - Checkbox alignment was unaffected on changing in a table 

Fixes https://github.com/appsmithorg/appsmith/issues/21790
 
Media
> https://www.loom.com/share/f881d6e7e23b437584fb8185300ff393

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manual

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Comment by rhlc** [comment]
Hey @ramsaptami, can you please review the changes

**Comment by ramsaptami** [comment]
@ashit-rath @somangshu please review this when you get the time
@rhlc could you please generate a deploy preview by running the following command: `/build-deploy-preview env=release`

**Comment by somangshu** [comment]
Right now, the header and the column value is adhering to the horizontal alignment. 
@dilippitchika @momcilo-appsmith What is expected?

**Review by keyurparalkar — CHANGES_REQUESTED** [review]
@rhlc can you make this change in [CheckboxCellWrapper](https://github.com/appsmithorg/appsmith/blob/a03477ea053df249aaf40d5c86cf234c0f72fb83/app/client/src/widgets/TableWidgetV2/component/cellComponents/CheckboxCell.tsx#L33) rather than in the CheckboxWidget?

**Comment by dilippitchika** [comment]
@keyurparalkar the alignment is not perfect because some space is always being blocked off for the hidden arrow. 

https://www.loom.com/share/239d83730dc9426fa041c63a30dc30f8

What do you suggest we do?

**Comment by somangshu** [comment]
> @keyurparalkar the alignment is not perfect because some space is always being blocked off for the hidden arrow.

@dilippitchika this is more of a _design decision_. We need to understand what need to happen when there is a hidden control. From dev POV, if we do not allocate the space for caret, on column header hover, we will see some kinda flickering happen.

**Pull request closed without merging**
