### PR TITLE
fix: Google sheet datasource fix

### LINKED ISSUE #18102: [Bug]: On trying to create a Gsheets page using the "Generate Page from data table" - Unexpected format for table header index error pops up
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I try to create a G-sheets page (the datasource should be existing for it to populate in the Select Datasource list) using the "Generate Page from data table" - on choosing the spreadsheet, and then the sheet,  **Unexpected format for table header index error pops up**.

### Steps To Reproduce

1. In app.appsmith.com, create a new workspace, create an application. 
2. Create a gsheets datasource (if one does not already exist)
3. Now create a new page by using the Generate page with data option
4. Select the Gsheets ds, the spreadsheet that you want to access, and also the sheet that you want to access.

An error pops up to the effect - 
Unexpected format for table header index

### Public Sample App

_No response_

### Issue video log

https://ddpa7mfuvv.vmaker.com/record/3hb9g0T3n37BFarr

### Version

Production

### PR DESCRIPTION
**Pull request by vaibh1297**
## Description

> Generate page from google sheet datasource was throwing exception.
> Fixed that exception using simple null check.

Fixes #18102

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual

### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Comment by subrata71** [comment]
In order to get the context I was trying to reproduce the issue locally and later planning to verify the fix. Here's some updates from my end. 

- I was able to reproduce the same on local or on production without this fix
- I was trying to verify whether this fix solves the issue or not but unfortunately there's a new error occurs when I click on `generate page`

Screenshot 2022-11-17 at 1 04 51 PM

cc: @vaibh1297 @btsgh

**Review by subrata71 — CHANGES_REQUESTED** [review]
In order to get the context I was trying to reproduce the issue locally and later planning to verify the fix. Here's some updates from my end. 

- I was able to reproduce the same on local or on production without this fix
- I was trying to verify whether this fix solves the issue or not but unfortunately there's a new error occurs when I click on `generate page`

Screenshot 2022-11-17 at 1 04 51 PM

cc: @vaibh1297 @btsgh

**Review by subrata71 — APPROVED** [review]
The problem that I mentioned earlier seems to be specific to my local env. Hence I am approving this PR.

**Comment by btsgh** [comment]
@vaibh1297 - Tested and found the issue to be fixed. Tried the CRUD flow on two environments with local setup.  
cc: @prapullac

**Pull request merged**
