### PR TITLE
fix: accept non-empty commit messages

### LINKED ISSUE #15050: [Bug]: Empty commit message can be committed using spaces.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I have changes in a git-connected app, I can commit using just the spaces. I should not be able to do so.

### Steps To Reproduce

1. Make a change
2. go to Deploy tab
3. add spaces in commit message box
4. click Commit&Push
5. See that it is committed

### Public Sample App

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by IAmAnubhavSaini**
## Description

We were allowing empty commit messages, this PR doesn't allow that. We are also trimming message ourselves before sending it to backend service.

Fixes #15050 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by IAmAnubhavSaini** [comment]
Failing build.

Screenshot 2022-07-07 at 9 53 30 AM

**Comment by IAmAnubhavSaini** [comment]
Passing tests

Screenshot 2022-07-11 at 6 51 04 AM

**Comment by IAmAnubhavSaini** [comment]
@RakshaKShetty  please test and verify that now empty commit messages cannot be used to commit.

**Review by albinAppsmith — APPROVED** [review]

**Pull request merged**
