### PR TITLE
chore: include client build source map

### LINKED ISSUE #29654: Don't delete source map from client build
This will help to debug performance profiles shared by customers which are redacted.

We can then use these source maps to hydrate the profiles with function signatures to help debug the performance profiles better.

### PR DESCRIPTION
**Pull request by sumitsum**
- Include client build source map as part of the final client package so that it can be used to debug performance related or other issues on self hosted instances ([ref](https://theappsmith.slack.com/archives/C024GUDM0LT/p1706008076714349?thread_ts=1706004908.892919&cid=C024GUDM0LT)). 

#### PR fixes following issue(s)
Fixes #29654 

#### Type of change
- Chore (housekeeping or task changes that don't impact user perception)

- [x] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

## Summary by CodeRabbit

- **Chores**
	- Modified the build process to retain sourcemaps for enhanced debugging capabilities.

### CODE REVIEW

**Review by pratapaprasanna — APPROVED** [review]

**Review by sharat87 — CHANGES_REQUESTED** [review]
Can we remove the `OUTPUT_PATH` variable as well? Doesn't look like we're using it anymore.

**Comment by sumitsum** [comment]
build-deploy-preview skip-tests=true recreate=true

**Comment by sumitsum** [comment]
> Can we remove the `OUTPUT_PATH` variable as well? Doesn't look like we're using it anymore.

Done.

**Comment by sumitsum** [comment]
Closing for now because this only proivdes partial source maps.

**Pull request merged**
