### PR TITLE
feat: import changes for step component

### PR DESCRIPTION
**Pull request by tanvibhakta**
## Description

Progresses https://github.com/appsmithorg/appsmith/issues/17251

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Locally 

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by albinAppsmith — DISMISSED** [review]

**Comment by shadabbuchh** [comment]
This PR has been tested. No issues found.

**Review by albinAppsmith — APPROVED** [review]

**Pull request merged**
