### PR TITLE
chore: search for templates with a given datasource or widgets

### PR DESCRIPTION
**Pull request by akash-codemonk**
## Description

Make templates searchable by datasources or widgets as well.

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Manually

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/template-search-fix 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 56.34 **(-0.01)** | 37.73 **(-0.01)** | 35.94 **(0)** | 56.57 **(0)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.71 **(-0.23)** | 40.83 **(-0.84)** | 36.21 **(0)** | 56.74 **(-0.25)**
 :green_circle: | app/client/src/workers/lint.ts | 94.87 **(0)** | 70 **(3.33)** | 100 **(0)** | 94.44 **(0)**</details>

### CODE REVIEW

**Review by arunvjn — APPROVED** [review]
Looks good!

**Comment by akash-codemonk** [comment]
ok-to-test sha=7f75e5e

**Comment by akash-codemonk** [comment]
ok-to-test sha=eb9d769

**Pull request merged**
