### PR TITLE
fix: datepicker popover adjust height and width.

### PR DESCRIPTION
**Pull request by techbhavin**
Fixes # (#4290) , (#4410)

## Type of change

- Bugfix (non-breaking change which fixes an issue)

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>
No changes to code coverage between the base branch and the head branch</details>

### CODE REVIEW

**Comment by somangshu** [comment]
Deploy preview tested

**Review by somangshu — APPROVED** [review]

**Comment by SatishGandham** [comment]
@techbhavin , This is happening because some months have 6 rows of number and some have 5. 
This is changing the height of the component, and when there is no room for the month with 6 rows, its jumping.

Even with position set to  bottom, there is still a flicker/jump. Ideal solution would be to leave space for the 6th row even when there isn't one.

**Review by SatishGandham — CHANGES_REQUESTED** [review]
This isn't an ideal solution. Please read my comment above.

**Review by SatishGandham — APPROVED** [review]

**Comment by vivekverma2312** [comment]
@techbhavin Issue #4290 is fixed and working fine.

**Comment by vivekverma2312** [comment]
@techbhavin Issue #4290 is working fine but new observation for issue #4410 is by default the calendar overlaps the min date field.
Screenshot 2021-05-13 at 1 54 06 PM

**Comment by techbhavin** [comment]
@vivekverma2312
In date-picker popover position is `auto`, so in that case, if we don't have enough space to open the popover.  it's normal behavior for the date-picker popover.

if we get the required height then you can see it show as per expectation.
image

**Comment by vivekverma2312** [comment]
@techbhavin How are you able to achieve the above case attached in the screen shot. In my case calendar by default overlapping the field.

**Comment by vivekverma2312** [comment]
@techbhavin Thanks for the update Looks good to me. We can go ahead with merging it in release.

**Review by somangshu — APPROVED** [review]

**Pull request merged**
