### PR TITLE
fix: fix debugger logs for performance

### LINKED ISSUE #16489: [Bug]: Multiple debugger logs updating state many times causing lots of computations
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

This Issue is mainly with Debugger logs updating states multiple times, In Debugger Saga, Action is being triggered in a loop, that action is in turn updating Redux State in a loop, This is bad for performance as they end up notifying the all the subscribers of the state.

### Steps To Reproduce

https://theappsmith.slack.com/archives/C024GUDM0LT/p1661870471009029

1. Import app from above slack thread
2. Navigate to Regulations page
3. Of the Regulations table widget, modify tableData code
4. Observe the UI freezes for few seconds

### Public Sample App

_No response_

### Version

Release/Prod/self hosted

### PR DESCRIPTION
**Pull request by rahulramesha**
## Description

This Change includes two parts, 
- In Debugger Saga, Action is being triggered in a loop, that action is in turn updating Redux State in a loop, This is bad for performance as they end up notifying the all the subscribers of the state. Changed it to update state once rather than doing it individually.
- In the Reducer, changed it to ImmerReducer so that only particular object of the local state changes on update rather than updating reference of the entire state.

Fixes #16489 

## Type of change

performance fix

## How Has This Been Tested?

Visual improvement in performance and performance indicators in DevTools

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by SatishGandham — APPROVED** [review]
LGTM

**Comment by somangshu** [comment]
@rahulramesha when is this expected to merge in?

**Review by ApekshaBhosale — APPROVED** [review]

**Pull request merged**
