### PR TITLE
fix: modal deselect issue auto height

### LINKED ISSUE #18697: [Bug]: the widget gets deselected when we change height property in Modal widget
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

he widget gets deselected when we change height property in Modal widget

### Steps To Reproduce

1. DnD a modal widget
2. Change the height 
You'll notice each time I change the height, the widget gets deselected

### Public Sample App

_No response_

### Issue video log

https://www.loom.com/share/85fe3285d14944d680c4ebfe083f601a

### Version

Production

### PR DESCRIPTION
**Pull request by ankurrsinghal**
## Description

-- Issue
The modal widget deselects when it's changed from AutoHeight to Fixed and vice-versa.

-- Reason
When Auto Height is enabled every widget is wrapped around `AutoHeightContainerWrapper` in BaseWidget but for canvas-like widgets, in this case, Modal Widget, it just returns its children back, so no change in the UI as such, but for react it's a completely new node and therefore it unmounts the previous component, and ModalWidget in one of its effect, deselects itself on unmount.

-- Fix
Added another check for ModalWidget using its `detachFromLayout` props before wrapping `AutoHeightContainerWrapper` in BaseWidget class. This allows ModalWidget to never enter `AutoHeightContainerWrapper` ever therefore the node remains the same hence no unmount.

Fixes #18697

Media
(https://www.loom.com/share/85fe3285d14944d680c4ebfe083f601a)

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by riodeuno — APPROVED** [review]
This is a good solution, makes things faster. We do have to make sure there aren't any side effects.

**Comment by kamakshibhat-appsmith** [comment]
Looks good, we can proceed @ankurrsinghal

**Pull request merged**
