### PR TITLE
fix: Removing unnecessary cloning

### PR DESCRIPTION
**Pull request by ApekshaBhosale**
## Description
evaluateSync was unnecessary here because it only needs to change string to function format but by using evaluateSync and providing triggered true it is cloning data tree while creating global data. All we need to do is transform string to function so using eval function directly

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

- Manual
- Jest
- Cypress

### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by arunvjn — APPROVED** [review]

**Comment by ApekshaBhosale** [comment]
closing this because if the function is defined as `myFun1(){ console.log("hey}}` while sending to eval throws an error as parsing doesn't give the function name. creating new PR which will still reduce cloning

**Pull request closed without merging**
