### PR TITLE
fix: fixed margins

### LINKED ISSUE #12158: [Bug]: Margin issues in Forms
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

- The spacing between the label and the tooltip seems to be wrong.
- The spacing between the helper text and the Switch To GUI Editor seems off.
- We are still using the older icon for tooltip, we have revised the icon with the new design system.
- Add the line number in the JSON editor as well.
- The tooltip icon size is also smaller than what in the designs.

Ref: https://theappsmith.slack.com/archives/C02KTH6EHUG/p1647497213055009?thread_ts=1647449257.951359&cid=C02KTH6EHUG

https://www.figma.com/file/i80YbQLLs5mXthjIHclPpX/Appsmith-Design-System?node-id=1267%3A5149

### Steps To Reproduce

Spacing issues in query editor and Datasource forms

### Public Sample App

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by rashmi-rai**
## Description

Fixes #12158

- Spacing between the label and the tooltip
- Spacing between the helper text and the Switch To GUI Editor
- Update tooltip icon.
- Tooltip icon size.

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Test for the following controlType:
- SWITCH 
- CHECKBOX
- WHERE_CLAUSE
- DROP_DOWN
- INPUT_TEXT
- FIXED_KEY_INPUT
- KEYVALUE_ARRAY
- FILE_PICKER
- QUERY_DYNAMIC_TEXT
- QUERY_DYNAMIC_INPUT_TEXT
- ARRAY_FIELD
- SORTING
- PAGINATION

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/form-control-margins-2 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 56.47 **(0)** | 37.92 **(0)** | 36.19 **(0)** | 56.7 **(0.01)**
 :red_circle: | app/client/src/components/formControls/PaginationControl.tsx | 54.84 **(-3.98)** | 33.33 **(-16.67)** | 25 **(0)** | 53.33 **(-4.25)**
 :green_circle: | app/client/src/pages/Editor/FormConfig.tsx | 28.57 **(8.57)** | 5.97 **(5.97)** | 0 **(0)** | 31.25 **(9.03)**
 :green_circle: | app/client/src/utils/WorkerUtil.ts | 89.76 **(0)** | 72.55 **(1.96)** | 100 **(0)** | 93.33 **(0)**</details>

### CODE REVIEW

**Comment by nidhi-nair** [comment]
@rashmi-rai Could you please attach screenshots here so that Parth can approve on the designs?

**Comment by rashmi-rai** [comment]
screenshot2
screenshot1
@parth-appsmith

**Pull request closed without merging**
