### PR TITLE
feat: Audio Recorder Reskinning

### LINKED ISSUE #10992: [Enhancement]: Audio recorder widget

### PR DESCRIPTION
**Pull request by dhruvikn**
## Description
This PR fixes UI inconsistencies in the Audio Recorder widget.

- Close button position and color
- Update spacing
- Font-size, Font-weight
- Permission denied "know more" link

Fixes #10992 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manually

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by dhruvikn** [comment]
@dilippitchika wrt to this [in the PRD](https://www.notion.so/appsmith/Audio-recorder-4b6d61f9677e46dfb85fdb6231fbeaaa#9e6d12cbad194e2c92ab5556987c0549)
image

The change cannot be done without changing the resize logic. Currently, the size of the icon is [set to be 80% of the widget's height](https://github.com/appsmithorg/appsmith/blob/9884b76d9cba31ab183817554a854e7a70d381ce/app/client/src/widgets/AudioRecorderWidget/component/index.tsx#L93).
```css
height: ${({ dimension }) => dimension * 0.8}px;
width: ${({ dimension }) => dimension * 0.8}px;
```

As the default height of the audio recorder widget is 72px, the icon's dimensions are 57.6px.

Thoughts on how we can proceed?

cc: @jsartisan @andrewdietekoki

**Review by jsartisan — APPROVED** [review]

**Comment by dilippitchika** [comment]
@dhruvikn i don't think we need to change the icon size here. This looks good to me. Let's change the default height of the widget when it's dragged and dropped though. Can you please decrease it by 1 row?

**Review by jsartisan — APPROVED** [review]

**Pull request merged**
