### PR TITLE
fix: Check for parent widget existence to render drop target

### LINKED ISSUE #28241: [Bug]: Nested List: Oops Something went wrong
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hi,

I'm getting an "oops something went wrong" error on my nested list

to reproduce

### Steps To Reproduce

I added a modal, inside it I added a list with 2 buttons, inside that list I added another list
the first item on the list is OK, the second one returns error,
even if I remove what I did and add a vanilla list, same result

image

thanks

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

self hosted 1.9.41

### PR DESCRIPTION
**Pull request by marks0351**
> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.
>
## Description
In the legacy architecture, List Widget meta first item was rendering in edit mode allowing DnD, resize, etc while the rest of the items were rendering in view mode restricting any editing experience. 
The first item was being used as a template to decide what the template was going to be for rest of the items.
However after the overhaul of BaseWidget and CanvasWidget render mode is always EDIT or VIEW for all widgets so DropTarget had to render a meta canvas widget which it was not written to handle. so have added checks to make sure DropTarget does not render and wrap widgets that do not have a parent.

Ideally this should have been caught in the CI, there are tests already but the checks were happening to check if List widget was allowed inside another List widget but the other items that were rendering in view mode were not being asserted.
I have added tests to check if all nested widgets are properly rendered and there is no "Oops, something went wrong" error. This should make sure this issue does not get past CI in the future.

#### PR fixes following issue(s)
Fixes #28241
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
- [ ] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by riodeuno — DISMISSED** [review]

**Review by ashit-rath — DISMISSED** [review]

**Comment by kamakshibhat-appsmith** [comment]
Issues: 
1. The text box is overlapping with Image widget inside List and also the position is different
Screenshot 2023-10-23 at 1 21 06 PM

**Comment by kamakshibhat-appsmith** [comment]
Issue 2: 
1. The child widget is taking much more space than intended .This issue is again on release but not Prod
https://www.loom.com/share/440866f44c1249d39120858a8c86935a

**Comment by kamakshibhat-appsmith** [comment]
PR looks good

**Review by riodeuno — APPROVED** [review]

**Pull request merged**
