### PR TITLE
chore: Check new git permissions for respective git operations

### LINKED ISSUE #29963: Integrate new Git permissions with Git flows
We've added 4 new permissions for Git operations. We need to use them in the corresponding features.

### PR DESCRIPTION
**Pull request by nayan-rafiq**
## Description
This PR uses the new Git permissions for Connect to Git, disconnect from Git, Protect branch and manage auto commit settings.

#### PR fixes following issue(s)
Fixes #29963

#### Type of change
- Chore (housekeeping or task changes that don't impact user perception)

#### How Has This Been Tested?
- [x] Manual
- [x] JUnit

#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

## Summary by CodeRabbit

- **New Features**
  - Expanded Git-related permissions, including the ability to connect to Git, manage protected branches, default branch, and auto-commit settings.

- **Improvements**
  - Enhanced Git permission checks for more granular access control within the app.

- **Refactor**
  - Updated components to utilize new Git permission hooks for better permission management.
  - Refined Git service logic to accommodate additional permission parameter.

- **Tests**
  - Adjusted test cases to align with the updated permission handling at the application level.

### CODE REVIEW

**Review by sondermanish — COMMENTED** [review]
Server side changes LGTM

**Review by dipyamanbiswas07 — APPROVED** [review]
FE changes LGTM

**Review by AnaghHegde — APPROVED** [review]

**Pull request merged**
