### PR TITLE
fix: improve camera widget

### LINKED ISSUE #14069: [Bug]-[508]:Camera widget bugs
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

We can see that when Appsmith is run on an Android, pictures are not having all the quality than the camera on the phone can capture. Also, using iPhone, pictures taken are only a completely black image where nothing can be seen

### Why should this be worked on?

The use case for this is to capture pictures of documentation (like bills, receipts, etc.) that should be in a resolution that can be read easily. 
In our case, we are storing the pictures in Cloudinary but pictures have reduced size (around 350x350 pixels) that make them very hard to read their content (letters cannot be read easily). We have tried to change the resolution of the camera on the phones with no result

So far we are finding:
* On Android, it works but we get low resolution pictures
* On iPhone, pictures are completely black

The goal will be to be able to select the resolution required on the picture before it's taken. It could be done either from the widget (more preferred way) or from the running camera on the application.

Thank you so much!

### PR DESCRIPTION
**Pull request by techbhavin**
## Description

Fixed Below Blocker issue in camera widget

- When I tap the full screen, the tooltip stays open and I am unable to see any other button
- When I turn on/off the video, the icon jumps a few pixels to the top right and back.
- Low resolution of the image leading to hazy images for app developers

Fixes #14069

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by jsartisan — DISMISSED** [review]

**Review by jsartisan — APPROVED** [review]

**Comment by chandannkumar** [comment]
@techbhavin The DP link is broken

**Review by jsartisan — DISMISSED** [review]

**Review by jsartisan — DISMISSED** [review]

**Comment by vivekverma2312** [comment]
@techbhavin On ios device we are not getting option to switch camera and mic.

**Comment by vivekverma2312** [comment]
@techbhavin LGTM

**Review by jsartisan — APPROVED** [review]

**Pull request merged**
