### PR TITLE
fix: Update list of global worker identifiers

### LINKED ISSUE #23172: TypeError: performance.now is not a function
Sentry Issue: [APPSMITH-6B0](https://appsmith.sentry.io/issues/4169069967/?referrer=github_integration)

```
TypeError: performance.now is not a function
  at <anonymous> (workers/Evaluation/evaluation.worker.ts:15:33)
```

Steps to reproduce 

1. Create a JSObject with the name as `performance` 
2. Check the logs for errors.

### PR DESCRIPTION
**Pull request by ohansFavour**
## Description
Global identifiers present in the worker context should not be valid entity names. This PR updates the list of global identifiers present in the worker context.

#### PR fixes following issue(s)
Fixes #23172 

#### Type of change
- Bug fix (non-breaking change which fixes an issue)

#### How Has This Been Tested?
- [x] Jest 
- [x] Manual

#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [x] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [x] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by Rishabh-Rathod — APPROVED** [review]

**Comment by ramsaptami** [comment]
LGTM. Restricted word `performance` has been handled
image

**Pull request merged**
