### PR TITLE
feat: Add support for custom 'this' and 'global' variables during evaluation

### LINKED ISSUE #6732: [Bug] this.params shows an error in IIFE
### Steps to reproduce the behaviour:

1. Create an API
2. Create a new parameter that has an IIFE which returns a value from `this.params`
`(function() { return this.params.name })()` (also test with arrow function)
3. TypeError: cannot read params of undefined
image

Note: When a param is passed @`Api.run({ name: "abcd" })`, it is successfully passed to the server.

### PR DESCRIPTION
**Pull request by hetunandu**
## Description

Adds a feature in evaluate to allow defining custom "this" and "global" variables that are not part of the data tree. It can help in defining field / entity level properties that we would not want to exist in the data tree during evaluation

Fixes #6732

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Jest
Test that these variables are available and evaluated
Test that errors are not raised

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/this.params-reference-issue 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 55.14 **(0.01)** | 37.07 **(0.02)** | 34.03 **(0.01)** | 55.66 **(0.01)**
 :green_circle: | app/client/src/workers/DataTreeEvaluator.ts | 77.64 **(0.48)** | 61.97 **(0.27)** | 76.74 **(0.88)** | 77.38 **(0.51)**
 :green_circle: | app/client/src/workers/evaluate.ts | 87.91 **(1.32)** | 76.67 **(5.84)** | 77.78 **(1.31)** | 87.21 **(0.96)**</details>

### CODE REVIEW

**Review by ApekshaBhosale — DISMISSED** [review]

**Comment by eco-monk** [comment]
This may be pre-existing or a different issue altogether.

I don't suppose we make a difference between a `function` and an `arrow function`, when using `this` keyword?

e.g.
image

**Review by eco-monk — DISMISSED** [review]
@hetunandu 
This may be pre-existing or a different issue altogether.

I don't suppose we make a difference between a `function` and an `arrow function`, when using `this` keyword?

e.g.
image

**Comment by hetunandu** [comment]
> @hetunandu This may be pre-existing or a different issue altogether or may not be an issue at all.
> 
> I don't suppose we make a difference between a `function` and an `arrow function`, when using `this` keyword?
> 
> e.g. image

The concern is correct. That is why I have bound the context in the inner function when an anonymous callback function is evaluated

https://github.com/appsmithorg/appsmith/pull/9651/files#diff-4a2c93894396387e40ad1347d6b5a2c35de845478385af1f304457e690098530R40

**Review by ApekshaBhosale — APPROVED** [review]

**Pull request merged**
