### PR TITLE
chore: copy old ads components and move them to packages

### LINKED ISSUE #22988: [Task]: Remove the usage of Design System components from WDS
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

**Components being used in WDS**
- Icon
- Toast
- Tooltip
- Dropdown
- SearchComponent
- MenuDivider
- ScrollIndicator

**Impacts that will be caused by new DS release**
- Default icon color will change to `#4c5664`
- Tooltip design for platform got changed.
Screenshot 2023-05-04 at 1 46 00 PM

- Menu divider color will change to `#cdd5df`

***Apart from these there are some constants or functions also being used***
- Variant
- DropdownOption
- LABEL_MAX_WIDTH_RATE
- IconSize
- labelLayoutStyles
- LABEL_CONTAINER_CLASS
- multiSelectInputContainerStyles
- getTypographyByKey

### PR DESCRIPTION
**Pull request by KelvinOm**
## Description
Move [old ADS components](https://github.com/appsmithorg/design-system/tree/release/packages/design-system-old) used in widgets to a local package.
Fix prettier, linter and type check errors

List of widgets that may be affected:
1. BaseInputWidget
2. ButtonWidget
3. CurrencyInputWidget
4. InputWidget
5. PhoneInputWidget
6. DropdownWidget
7. ListWidget
8. ListWidgetV2
9. MultiSelectTreeWidget
10. MultiSelectWidget
11. MultiSelectWidgetV2
12. RateWidget
13. SelectWidget
14. SingleSelectTreeWidget
15. TableWidget
16. TableWidgetV2
17. TabsWidget
18. TextWidget

#### PR fixes following issue(s)
Fixes #22988 

#### Type of change
- Chore (housekeeping or task changes that don't impact user perception)

- [x] Manual
- [x] Jest
- [x] Cypress
>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by albinAppsmith — APPROVED** [review]

**Review by albinAppsmith — DISMISSED** [review]

**Comment by laveena-en** [comment]
Ran a regression on all the widgets mentioned and found no issues specific to this PR. LGTM.

cc: @shadabbuchh

**Pull request merged**
