### PR TITLE
fix: Autocomplete object value binding

### LINKED ISSUE #15950: [Bug]: For Select widget or a Checkbox group widget, Auto-complete does not show up in the Options section on Refresh
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On binding the Options of Checkbox group to a text widget, on refreshing the page, the autocomplete options do not show up. 
Similar behavior is seen even on Select widget. 

### Steps To Reproduce

Drop a checkbox group widget and a text widget onto canvas.
Try binding one of the options to the text widget. We can see the auto complete options come on. 
Refresh this page.
Retry the binding. No auto complete suggestions come up this time. 
Screenshot 2022-08-11 at 10 31 37 PM

### Public Sample App

_No response_

### Version

Production

### LINKED ISSUE #16141: [Bug]:  Autocomplete does not work as expected
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we use the mustache syntax inside the form fields for MongoDB query `{{}}` the autocomplete does not work as expected. When we hit enter the word is coming outside the mustache braces `{{}}`. 

Please check the recording - https://www.loom.com/share/b7721ca088bd4f2ab5743725349f5a2f

### Steps To Reproduce

1. Navigate to a mongo query.
2. Say for the query field type the mustache syntax and hit enter for the autocomplete

### Public Sample App

_No response_

### Version

Release

### PR DESCRIPTION
**Pull request by Rishabh-Rathod**
## Description

Fixes #15950
Fixes #16141

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
**Test plan**
- [ ] https://github.com/appsmithorg/TestSmith/issues/1982
- [ ] https://github.com/appsmithorg/TestSmith/issues/2049

## Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Rishabh-Rathod — COMMENTED** [review]
Fix `TernServer.test.ts` test and add new test cases

**Review by arunvjn — APPROVED** [review]
Looks good

**Comment by ramsaptami** [comment]
DP testing is complete and mentioned issues have been fixed - though there's an internal server error being observed for CRUD apps which isn't reproducible on release

**Comment by ramsaptami** [comment]
The issue with CRUD app cannot be reproducible anymore. Jest tests have been written but cypress will be covered as part of a separate task CC: @Rishabh-Rathod

**Pull request merged**
