### PR TITLE
fix: change to lodash wrapper

### LINKED ISSUE #23671: Lodash is undefined in derived.js of Currency Widget TypeError: Cannot read properties of undefined (reading 'isNaN')
Sentry Issue: [APPSMITH-6EM](https://appsmith.sentry.io/issues/4196272454/?referrer=github_integration)

```
TypeError: Cannot read properties of undefined (reading 'isNaN')
  at hn.value (widgets/CurrencyInputWidget/widget/derived.js:80:13)
  at transformValue (widgets/JSONFormWidget/fields/CurrencyInputField.tsx:138:29)
  at onTextChangeHandler (widgets/JSONFormWidget/fields/BaseInputField.tsx:284:31)
  at <object>.onValueChange (widgets/JSONFormWidget/fields/BaseInputField.tsx:382:35)
  at _this.onNumberChange (widgets/BaseInputWidget/component/index.tsx:471:16)
...
(19 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by keyurparalkar**
## Description
This issue is happening because we are getting lodash library as `undefined` when we pass it to` derived.value` function here. This is happening because of the following reason:
* [Bundle optimisation PR](https://github.com/appsmithorg/appsmith/pull/21667) introduces a new plugin called: `babel-plugin-lodash`. It helps in transforming the imports. 
* But this plugin doesn't work on the following pattern: `import _ from "lodash"`. Here it replaces `_` with `undefined`
[ This file](https://github.com/appsmithorg/appsmith/blob/3bc50d9632cf269935aed6657092ddb8b7e8c92f/app/client/src/workers/common/JSLibrary/lodash-wrapper.js#L1) explains the exact scenario that we are facing.
There is also [an open bug](https://github.com/lodash/babel-plugin-lodash/issues/235) for this issue on the `babel-plugin-lodash` repository.

This PR imports lodash from the lodash-wrapper instead of directly importing as follows: `import _ from "lodash"`
>
#### PR fixes following issue(s)
Fixes #23671

#### Type of change
- Bug fix (non-breaking change which fixes an issue)

#### How Has This Been Tested?

- [x] Manual
- [ ] Jest
- [x] Cypress
    - should check that value entered in currency field appears in the actual field
>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by ashit-rath — COMMENTED** [review]
Can you add a cypress test where a field is currency field in JSONForm and a value can be entered into field?

**Comment by keyurparalkar** [comment]
> Can you add a cypress test where a field is currency field in JSONForm and a value can be entered into field?

@ashit-rath I have added the cypress test

**Review by ashit-rath — APPROVED** [review]

**Comment by chandannkumar** [comment]
Tested & Verified on Release environment and LGTM

**Pull request merged**
