### PR TITLE
Fix-Date type column sort in Table widget

### LINKED ISSUE #5780: [Bug] The date sorting on Table widget is not working
## Description

The table widget is not able to sort the column of type date correctly.
tablesort

### Steps to reproduce the behaviour:

1. Add table widget and add a column with random dates
2. Set column's type to date 
3. Sort this column in descending order
4. Notice the sorting is not correct

### Important Details

- Version: Cloud
- Environment: Production

### LINKED ISSUE #6207: [Bug] Table filtering on Date has mismatched 'before/after' options
## Description

Filtering based on date does the opposite of expected behavior; 'After 07/01/2021' returns all results before and including 07/01/2021; 'Before 07/01/2021' returns all dates including 07/01/2021 and after.

### Steps to reproduce the behaviour:
* Create a Data Source that returns a JSON response with date in the following format:  "2021-07-10"
* Create a table that uses that data source
* Set Original Date Format for the column to be YYYY-MM-DD
* Set Formatted Date Format for the column to be MM/DD/YYYY
* Filter on 'Date is before/after' a given date; getting the opposite expected behavior.

Screen Shot 2021-07-27 at 1 05 36 PM
Screen Shot 2021-07-27 at 1 08 52 PM
Screen Shot 2021-07-27 at 1 08 39 PM

### Important Details

- Version: Cloud
- OS: MacOS 10.15.7
- Browser: Chrome Version 90.0.4430.212 (Official Build) (x86_64
- Environment: Staging environment

### PR DESCRIPTION
**Pull request by vicky-primathon**
## Description
Use input date format to sort date type columns in Table Widget

Fixes #5780 
Fixes #6207

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/table-widget-date-column-sort 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 53.29 **(0.01)** | 34.75 **(0.01)** | 31.33 **(0)** | 53.85 **(0)**
 :green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 50.71 **(0.24)** | 38.6 **(0.88)** | 36.21 **(0)** | 55.35 **(0.27)**
 :green_circle: | app/client/src/widgets/TableWidget/derived.js | 54.26 **(0.25)** | 56.25 **(0)** | 37.84 **(0)** | 54.07 **(0.27)**</details>

### CODE REVIEW

**Review by hetunandu — APPROVED** [review]

**Comment by vivekverma2312** [comment]
@vicky-primathon Calendar on table filter is getting closed every time I try to change the month/year.
https://www.loom.com/share/f4767d85e2294f5db2a22b07248cbfe4

**Comment by vicky-primathon** [comment]
> @vicky-primathon Calendar on table filter is getting closed every time I try to change the month/year.
> https://www.loom.com/share/f4767d85e2294f5db2a22b07248cbfe4

This is working on deploy preview

**Comment by YogeshJayaseelan** [comment]
@vicky-primathon  verified this PR and both the issues are working as expected.

**Pull request merged**
