### PR TITLE
fix: broken line in page settings

### LINKED ISSUE #30922: [Bug]: broken line in page url settings
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

coming from [here](https://theappsmith.slack.com/archives/C02JT9CSE6L/p1706698534445299)

Screenshot 2024-02-06 at 14 23 12

this should be changed to `Please update your app URL to the new format to set the page URL`

### Steps To Reproduce

1. open a very old app
2. go to settings
3. page settings
4. see broken line

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by rohan-arthur**
## Description
for old pages that were created before the new url style, the page settings has a prompt to ask the user to change the URL.
The line in this prompt is broken
Screenshot 2024-02-06 at 14 23 12

This PR changes this line to:
Screenshot 2024-02-06 at 14 33 41

For testing, you can get an example old app from [here](https://theappsmith.slack.com/archives/C02JT9CSE6L/p1707204475068809?thread_ts=1706698534.445299&cid=C02JT9CSE6L)

#### PR fixes following issue(s)
Fixes #30922 

- Bug fix (non-breaking change which fixes an issue)

## Testing

- [x] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress

#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

## Summary by CodeRabbit

- **Refactor**
	- Updated the wording of messages related to setting page URLs for enhanced clarity and consistency.
	- Changed test tags from `@tag.Settings` to `@tag.Visual` for improved test categorization.
	- Modified JSEditor indentation visual tests to include additional test cases and adjustments in test descriptions.
	- Updated test tags from `@tag.JS` to `@tag.Visual` for consistency in test categorization.
	- Added `@tag.Visual` to the list of tags for test categorization.

### CODE REVIEW

**Comment by rohan-arthur** [comment]
going to rerun failed tests because the three failures seem unrelated.

**Comment by rohan-arthur** [comment]
second rerun after pulling latest changes from release, as the three failures look completely unrelated.

**Review by albinAppsmith — DISMISSED** [review]

**Review by albinAppsmith — APPROVED** [review]

**Pull request merged**
