### PR TITLE
Minor comments feature fixes

### PR DESCRIPTION
**Pull request by rishabhsaxena**
## Description
- Allow interaction with the app while the comment thread is open
- Close comment intro on clicking outside the modal / escape
- Progressively load intro images with low res images bundled
- Update tour toolip msg to 'type Hello'
- Fix scroll for the display image upload component, make cropper a circle

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manually

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>

    // Code coverage diff between base branch:release and head branch: minor-fixes-comments-feature 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | app/client/src/comments/CommentCard/CommentCard.tsx | 32.6 **(-0.18)** | 23.14 **(0)** | 7.14 **(0)** | 34.32 **(-0.2)**
 :red_circle: | app/client/src/pages/Editor/ToggleModeButton.tsx | 64.29 **(-0.46)** | 26.15 **(0)** | 40 **(0)** | 62.79 **(-0.49)**</details>

### CODE REVIEW

**Comment by Rishabh-Rathod** [comment]
Screenshot 2021-07-30 at 1 59 56 AM

I think there is this small edge case when the page is empty and the comment tutorial begins at that time there is no canvas to click on.

**Comment by rishabhsaxena** [comment]
@Rishabh-Rathod Yeah there's this edge case currently there, we do have an issue for this. I'll check if we can have a quick fix for this

**Review by Rishabh-Rathod — APPROVED** [review]
LGTM

**Review by Rishabh-Rathod — APPROVED** [review]

**Comment by rishabhsaxena** [comment]
Merging this as an exception: the failing test is unrelated to this PR and we need to push this to release on a priority

**Pull request merged**
