### PR TITLE
chore: fix tests in ee

### PR DESCRIPTION
**Pull request by eco-monk**
Updated imports.

Fixes `WindowMessageListener_spec.ts`.

### CODE REVIEW

**Comment by ohansFavour** [comment]
@eco-monk  I will update this branch with a test that mocks the behaviour in ee. Don't trigger CI yet

**Review by arunvjn — APPROVED** [review]

**Comment by eco-monk** [comment]
@ohansFavour could we create a separate PR for that?
We can merge this, since it breaking EE tests now.

**Review by ohansFavour — APPROVED** [review]

**Pull request merged**
