### PR TITLE
fix: improve styled for button list in property

### LINKED ISSUE #9156: Button group widget - issues
I tested the button group widget and there are a few bugs and one enhancement that's necessary for the button to be more useful than just putting 3 individual buttons together.

Bugs:
1. The button variant option is placed incorrectly and should be in styles section(exactly like in other button widgets)
2. There's no way to change the color of a button
3. The list of button names has a visual bug. The top of the field is cut off. See screenshot below:
Screen Shot 2021-11-13 at 2 18 29 AM

Enhancement:
Allow users to use a JSON object to generate buttons on the fly. The button group and even the menu button should have a data property to achieve this. This enhancement will be incredibly useful because a user can generate a list of actions on the fly.

_Originally posted by @areyabhishek in https://github.com/appsmithorg/appsmith/issues/4889#issuecomment-967634844_

### PR DESCRIPTION
**Pull request by techbhavin**
## Description

> Improve Style For Button List in Property Panel and Move Button Variant option in Style Section

Fixes #9156 

## Type of change
- Bugfix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/button-group-widget 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 55.05 **(0.01)** | 36.93 **(-0.01)** | 33.8 **(0.02)** | 55.53 **(0.01)**
 :red_circle: | app/client/src/components/propertyControls/ButtonListControl.tsx | 23.86 **(0.2)** | 25 **(-4.41)** | 9.09 **(1.4)** | 25.97 **(0.36)**</details>

### CODE REVIEW

**Review by jsartisan — APPROVED** [review]

**Comment by shwetha-ramesh** [comment]
@techbhavin tested this PR. 
Bug 1 is fixed,
Bug 2: There is already an option to change button color under button settings
Bug 3 is fixed

As discussed a separate ticket #9144 has been created for the _enhancement_ mentioned under this issue.

**Moving this to DONE**

**Review by jsartisan — APPROVED** [review]

**Pull request merged**
