### PR TITLE
fix: Changed error message during import when fields are missing in the JSON

### LINKED ISSUE #20493: [Bug]: Error message while importing corrupted JSON is not clear
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

While importing corrupted JSON file, Resource not found error is thrown, we should show clear error message stating the issue.

### Steps To Reproduce

1. Import corrupted json file.
2. Observe resource not found error is shown.

### Public Sample App

_No response_

### Issue video log

_No response_

### Version

https://ce-14939.dp.appsmith.com/

### PR DESCRIPTION
**Pull request by nayan-rafiq**
## Description
Instead of throwing 404, this PR informs the user which field is missing in the JSON.
#### PR fixes following issue(s)

Fixes #20493

#### Media
N/A

#### Type of change
- Bug fix (non-breaking change which fixes an issue)

#### How Has This Been Tested?
- [x] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by AnaghHegde — COMMENTED** [review]
Does it require any changes in test cases?

**Comment by nayan-rafiq** [comment]
@AnaghHegde you were right. I've updated few unit tests that were failing.

**Review by AnaghHegde — APPROVED** [review]

**Review by Parthvi12 — APPROVED** [review]

**Pull request merged**
