### PR TITLE
fix: Removed inputText from Input widget autocomplete

### LINKED ISSUE #22265: [Bug]-[1800]:Remove inputText from autocomplete suggestion for input widget
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Input widgets' autocomplete suggestion shows `Input.inputText` and `Input.text` where `inputText` is an internal property that shouldn't be exposed as a suggestion.

[Slack thread](https://theappsmith.slack.com/archives/C02K0SZQ7V3/p1677757204941789)

### Steps To Reproduce

1. Drop an input widget on canvas and try to bind it's properties
image

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by Druthi**
## Description
fix: Removed inputText from Input widget autocomplete

#### PR fixes following issue(s)
Fixes #22265

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
- [x] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [x] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by Rishabh-Rathod — APPROVED** [review]

**Comment by ramsaptami** [comment]
LGTM @Druthi

**Review by Rishabh-Rathod — APPROVED** [review]

**Pull request merged**
