### PR TITLE
Fix/4266 smart ordering tableheader

### PR DESCRIPTION
**Pull request by haojin111**
## Description

> When user ordering of column header by using drag-n-dnd of it, it'll be working as smoothly more.
> Also when ordering them over property pan, scrolling is added with dnd

Fixes # 4266

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Please reference linked issue.
- On property panel, user can use wheeling or page up/down for scrolling with dnd item.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: FIX/4266-smart-ordering-tableheader 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 54.79 **(-0.04)** | 36.43 **(-0.24)** | 33.23 **(-0.02)** | 55.35 **(-0.06)**
 :red_circle: | app/client/src/components/ads/DraggableList.tsx | 12.12 **(-7.23)** | 2.02 **(-12.27)** | 0 **(0)** | 14.29 **(-11.24)**
 :red_circle: | app/client/src/components/designSystems/appsmith/TableComponent/Table.tsx | 54.07 **(-7.56)** | 18.69 **(-18.56)** | 32.14 **(-6.75)** | 51.97 **(-9.01)**
 :red_circle: | app/client/src/components/designSystems/appsmith/TableComponent/TableUtilities.tsx | 40.77 **(-4.15)** | 20 **(-4.05)** | 17.65 **(-1.1)** | 39.17 **(-4.35)**
 :green_circle: | app/client/src/components/designSystems/appsmith/TableComponent/index.tsx | 43.48 **(16.21)** | 4 **(1.37)** | 14.29 **(-1.5)** | 43.48 **(17.8)**</details>

### CODE REVIEW

**Comment by marks0351** [comment]
@haojin111 can u pls fix the build errors.

**Review by marks0351 — CHANGES_REQUESTED** [review]
Pls check the build errors. there seem to be some unwanted imports.

**Comment by somangshu** [comment]
@haojin111 seems like the merge here is not clean, Can you create another PR with your changes and the latest release. There are too many unrelated files here that are not required for review.

**Review by marks0351 — CHANGES_REQUESTED** [review]
Please resolve conflicts and clean up the PR.

**Comment by haojin111** [comment]
Hello, @marks0351 !
I just created new PR for above issue.
Because this branch has a lot of unnecessary commits, so you can't review easily.
Please check following [PR](https://github.com/appsmithorg/appsmith/pull/6672) instead of it.

**Comment by somangshu** [comment]
Closing this in favour of #6672

**Pull request closed without merging**
