### PR TITLE
test: Fix for gsheet Misc_spec

### PR DESCRIPTION
**Pull request by sarojsarab**
## Description
- Fixed test failures in Gsheet Misc_spec.ts
- Removed all the static waits from the spec

#### Type of change
- Gsheet/Misc_Spec.ts
>
#### How Has This Been Tested?
- [x] Cypress

## Summary by CodeRabbit

- **Refactor**
  - Optimized search operations by adjusting timeouts and removing unnecessary sleep calls for a smoother user experience.
- **Tests**
  - Enhanced end-to-end test stability with improved wait mechanisms during table loads.

### CODE REVIEW

**Review by Aishwarya-U-R — APPROVED** [review]

**Comment by Aishwarya-U-R** [comment]
@sarojsarab - Lets once run in CI & then PR is merge ready 🤞

**Comment by Aishwarya-U-R** [comment]
@sarojsarab - Please fix [Prettier](https://github.com/appsmithorg/appsmith/actions/runs/7419206721/job/20188332528?pr=30055)

**Comment by sarojsarab** [comment]
https://github.com/appsmithorg/appsmith/actions/runs/7419553193/attempts/1

**Comment by sarojsarab** [comment]
> @sarojsarab - Lets once run in CI & then PR is merge ready 🤞

https://github.com/appsmithorg/appsmith/actions/runs/7419553193/attempts/1

**Review by Aishwarya-U-R — APPROVED** [review]

**Pull request merged**
