### PR TITLE
fix: Button Group Menu Item Label Misaligned

### LINKED ISSUE #18867: [Bug]: New menu item titles are misaligned
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we add new menu items in the Button Group widget, they are not aligned with the rest of the menu items by default.

Screenshot 2022-12-12 at 11 54 48 AM

### Steps To Reproduce

1. D&D a Button Group widget.
2. In the property pane click on the settings for the `More` button.
3. Click on `Add a new Menu Item`.

### Public Sample App

_No response_

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by dhruvikn**
## Description

This PR fixes a minor bug that caused the label of new menu items inside the button group widget to be misaligned.

Fixes #18867

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manual

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by jsartisan — APPROVED** [review]

**Comment by laveena-en** [comment]
@dhruvikn Looks like the DP isn’t up yet. Can you please check? 
image

**Comment by dhruvikn** [comment]
@laveena-en here you go - https://appsmith-8ulngq98e-get-appsmith.vercel.app/

**Comment by laveena-en** [comment]
Tested and verified for the misalignment of new items in the button group widget on this DP. LGTM!

**Pull request merged**
