### PR TITLE
fix: make the FormButtonWidget to have properties of ButtonWidget

### LINKED ISSUE #7260: [Bug] Form widget buttons don't respond to styling options
## Description
The form buttons retain only primary styling and don't respond to button styling options. The new button styling options haven't been applied to them.
Old form buttons were updated to primary button style automatically.

Reported by a user on intercom.

### PR DESCRIPTION
**Pull request by aswathkk**
## Description

Modified FormButtonWidget to inherit the properties of ButtonWidget.

Fixes #7260 

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested?

Manually tested

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by riodeuno** [comment]
@aswathkk This PR seems to want to merge into another branch. Do we have a PR for the other branch? 
Or, is it possible to create a PR which merges into release here?

**Comment by riodeuno** [comment]
@ashwathkk Can we confirm if we need any migrations here?

**Comment by aswathkk** [comment]
@riodeuno We've [PR-7166](https://github.com/appsmithorg/appsmith/pull/7166) created for the other branch. The changes that I've made is closely related to the other branch. I'm not sure whether I should create a PR which merges into release.

I don't know about migrations. Can you tag someone so that I can understand about migrations from them?

**Comment by riodeuno** [comment]
@aswathkk Based on the feature description, we need to understand whether properties of any existing buttons need to be updated for these changes to work correctly. We can easily test this by creating a form in the release environment, changing the form button styles and opening the same application in the deploy preview (or locally), if the button functions and looks like it should, then we don't need migrations, otherwise, we do.

If we don't need migrations, this looks good to merge.

**Review by riodeuno — APPROVED** [review]

**Comment by aswathkk** [comment]
@riodeuno We need migrations since we changed style options for FormButtonWidget. Also, I tested like the way you told me.
([Here](https://github.com/appsmithorg/appsmith/issues/7046#issuecomment-916805858)'s a glimpse of what needs to be changed wrt button styling if you don't have the context)

How should I write migrations?

**Comment by riodeuno** [comment]
@aswathkk Looks like we need to simply update the properties of the existing widgets of the type `FORM_BUTTON_WIDGET` in the page DSLs. Please refer to `DSLMigrations` file (`transformDSL` function) to see the existing migrations. Basically, we simply update the DSL before rendering the Canvas.

**Comment by aswathkk** [comment]
@riodeuno I've written migrations. Can you do a review now?

**Review by riodeuno — APPROVED** [review]
Looks good to me! We will need a QA for the migrations and the changes.

**Pull request merged**
