### PR TITLE
fix: Empty space at the start of Topstacked navigation page list

### LINKED ISSUE #23751: [Bug]: Empty space at the start of Top + Stacked navigation's page list
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Noticed the issue post ADS v2 changes. Attaching a screenshot.

CleanShot 2023-05-26 at 12 07 12@2x

### Steps To Reproduce

1. Create an app.
2. Add two pages.
3. Observe the empty space at the left/start of the pagelist.

### Public Sample App

_No response_

### Environment

Release

### Issue video log

_No response_

### Version

Appsmith v1.9.20.5-SNAPSHOT

### PR DESCRIPTION
**Pull request by iSatVeerSingh**
## Description
This PR removes the empty space at the start of Topstacked navigation plage list in Preview Mode and Deploy.
#### PR fixes following issue(s)
Fixes #23751
#### Media
Screenshot from 2023-06-05 20-24-49

#### Type of change

- Bug fix (non-breaking change which fixes an issue)

- [x] Manual
- [x] Jest
- [ ] Cypress

#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an impl mentation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by dhruvikn — APPROVED** [review]

**Comment by dhruvikn** [comment]
Thanks for contributing yet again @iSatVeerSingh. 🙌

**Comment by laveena-en** [comment]
Verified. Changes LGTM in preview and deploy mode.

**Comment by dhruvikn** [comment]
Awesome, thanks @laveena-en!

@iSatVeerSingh, could you please merge the latest release branch into your branch and run the `/ok-to-test` command by commenting on this thread so that we can start the CI?

**Comment by dhruvikn** [comment]
@somangshu, can we please merge this PR?

Thanks a lot @iSatVeerSingh for contributing. Much appreciated! 🎉

**Pull request merged**
