### PR TITLE
fix: underline style for text

### LINKED ISSUE #5631: An underline style for text

### PR DESCRIPTION
**Pull request by Tooluloope**
## Description

>Add Underline style to text on table column

Fixes #5631 

## Type of change
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: feat/underline-style-for-text 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 55 **(0)** | 36.87 **(-0.02)** | 33.88 **(-0.01)** | 55.55 **(0)**
 :red_circle: | app/client/src/components/designSystems/appsmith/TableComponent/TableStyledWrappers.tsx | 67.82 **(0)** | 21.69 **(-0.16)** | 50 **(0)** | 67.82 **(0)**
 :red_circle: | app/client/src/icons/ControlIcons.tsx | 57.6 **(-0.12)** | 100 **(0)** | 13.11 **(-0.22)** | 57.6 **(-0.12)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 50.47 **(-0.24)** | 37.72 **(-0.88)** | 36.21 **(0)** | 55.08 **(-0.27)**
 :red_circle: | app/client/src/widgets/TableWidget/index.tsx | 27.25 **(0.11)** | 5.92 **(0)** | 24.53 **(-0.47)** | 27.39 **(0.12)**</details>

### CODE REVIEW

**Review by somangshu — DISMISSED** [review]
Approving for tests to run

@Tooluloope how come so many updates on the lock file

**Comment by vivekverma2312** [comment]
@Tooluloope Please check the console error while writing JS query for Font Style property

Screenshot 2021-08-30 at 4 03 46 PM

**Comment by Tooluloope** [comment]
> @Tooluloope Please check the console error while writing JS query for Font Style property. Also widget crash.
> 
> Screenshot 2021-08-30 at 4 03 46 PM


@vivekverma2312 This is an issue on release.
Could you raise an issue and assign it to me.
Screenshot 2021-08-30 at 11 54 07

**Comment by vivekverma2312** [comment]
@Tooluloope Raised issue #6965 for release.

**Comment by Tooluloope** [comment]
> @Tooluloope Raised issue #6965 for release.

Okay @vivekverma2312 ,
Any other issue with this PR?

**Comment by Tooluloope** [comment]
> > @Tooluloope Raised issue #6965 for release.
> 
> Okay @vivekverma2312 ,
> Any other issue with this PR?

@vivekverma2312, could you confirm this fixes the issue https://github.com/appsmithorg/appsmith/pull/6980

**Review by somangshu — DISMISSED** [review]

**Comment by vivekverma2312** [comment]
@Tooluloope Issue #6980 has been fixed. Can you please merge that fix here and let me do a round of sanity before moving to release.

**Comment by Tooluloope** [comment]
> @Tooluloope Issue #6980 has been fixed. Can you please merge that fix here and let me do a round of sanity before moving to release.

@vivekverma2312  Done

**Comment by vivekverma2312** [comment]
@Tooluloope Working fine on deploy preview.

**Comment by somangshu** [comment]
@Tooluloope there is a conflict here, that too java 🤔 , Please check. Also the next time you see your task in the done state, Please dont let it get stale for more than 24 hrs, Try and merge it or get a review if required. Thanks :)

**Comment by somangshu** [comment]
Please let me know once you resolve this, Ill give an approval again

**Review by somangshu — APPROVED** [review]
Its weird to see some JAVA file getting conflicted in this PR.

Approving to run the tests

**Comment by Tooluloope** [comment]
> Its weird to see some JAVA file getting conflicted in this PR.
> 
> Approving to run the tests

Yeah, I wasn't sure why, 
But I just used the same version with release.

**Pull request merged**
