### PR TITLE
feat: Change default label position of RTE to top

### LINKED ISSUE #15141: [Feature]: Default Label position of Rich Text Editor should be made better
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Positioning the label to the top by default would be nice.

https://user-images.githubusercontent.com/10436935/178429908-9e527951-4e69-478b-a90b-9a6bf750f9b7.mov

### Why should this be worked on?

Rich Text Editor’s default Label position doesn’t look good.

### PR DESCRIPTION
**Pull request by dhruvikn**
## Description

This PR changes the default label position of the Rich Text Editor widget from "Left" to "Top"

Fixes #15141 

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Manually tested

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by somangshu — APPROVED** [review]
LGTM

**Comment by dhruvikn** [comment]
Have raised a WIP PR since Cypress tests were failing locally. Getting on a call with Nandan later for fixing that. Will remove the WIP tag then.
cc: @somangshu

**Comment by somangshu** [comment]
@dhruvikn another challenge I am noticing is that the rte widget is aligning itself in the vertical center, which is different from what is observed in the release env

> PR
Screenshot 2022-08-05 at 3 42 14 PM

> Release
Screenshot 2022-08-05 at 3 42 21 PM

**Comment by dhruvikn** [comment]
> @dhruvikn another challenge I am noticing is that the rte widget is aligning itself in the vertical center, which is different from what is observed in the release env
> 
> > PR
> > Screenshot 2022-08-05 at 3 42 14 PM
> 
> > Release
> > Screenshot 2022-08-05 at 3 42 21 PM

Taking a look, @somangshu.

**Comment by dhruvikn** [comment]
It seems consistent on my end @somangshu 

> [PR](https://appsmith-hvxgd14eq-get-appsmith.vercel.app/)
> CleanShot 2022-08-05 at 15 50 19@2x

> [Prod](https://app.appsmith.com/)
> CleanShot 2022-08-05 at 15 50 26@2x

> [Release](https://release.app.appsmith.com/)
> CleanShot 2022-08-05 at 15 50 34@2x

**Comment by somangshu** [comment]
Seems like the change pointed out here was intended, Dhruvik will find where this is happening. 
Once we merged the latest release the behaviour was similar.

**Comment by dhruvikn** [comment]
This is the change that's causing this. 
[Line 100 (app/client/src/components/ads/LabelWithTooltip.tsx)](https://github.com/appsmithorg/appsmith/pull/15329/files#diff-f9cd78a613ae9a344c6bf091710e0131e4b9b0c336f7083732fe402eca129cc2R100) in PR #15329 
image

cc: @somangshu @jsartisan

**Comment by dilippitchika** [comment]
No migrations, only a change in default config of the widget @somangshu

**Comment by laveena-en** [comment]
Tested and verified.
P.S Label's intended position behaviour would be on top (for left alignment) due to flex-start.
cc: @dhruvikn

**Comment by dhruvikn** [comment]
Let's merge, please, since it's QA approved and UI tests passed, but not reported. @somangshu. TIA.

**Comment by somangshu** [comment]
@laveena-en what do you mean
> P.S Label's intended position behaviour would be on top (for left alignment) due to flex-start.

**Comment by dhruvikn** [comment]
@somangshu she meant this is the expected behavior. So all is good there.

image

**Comment by somangshu** [comment]
@allcontributors add @dhruvikn as a contributor for code

**Pull request merged**
