### PR TITLE
refactor: Seperate out service level methods to helper classes to have custom implementation in business edition 

### LINKED ISSUE #21522: [Task]: Disable the cron to fetch release notes for airgapped instances

### PR DESCRIPTION
**Pull request by abhvsn**
## Description

For air gap instances, public internet will be restricted and as a result, cron jobs that depend on cloud-services won't be supported. As a part of this, the current PR creates a helper class to have a custom implementation on the EE repo.
Corresponding EE PR: https://github.com/appsmithorg/appsmith-ee/pull/1252

Fixes #21522 #21521 #21882 

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Manual

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by trishaanand — APPROVED** [review]

**Comment by abhvsn** [comment]
Attaching a screenshot from local to verify testcase failure is not related to the change.
Screenshot 2023-04-10 at 4 18 25 PM

**Pull request merged**
