### PR TITLE
Add Cloud Service end point to external-client-tests.yml

### LINKED ISSUE #5582: [Task] Mock data set API
We need to support the on prem instances as well for mock data set workflow. The main problem in achieving this with migration script is that DatabaseChangelog class doesn’t have access to any of the spring services. Hence we will not be able to create a template datasource for these mock datasets using datasourceService.create. Directly inserting them in the datasource collection in a migration would mean hardcoding the datasource structure in a migration, as well as including the passwords of mock databases in plaintext in the migration’s source code.
So we had to involve cloud service where we store the mock database credentials and available mock datasets in its database.
Right now the GET mocks on the backend-server gets these info from appsmith mongo database. With the new flow this will call cloud service API and cache this info for 2hrs approximately. Now when the user clicks on create mock data -
Current flow clones the datasource from the template datasource.
New flow will fetch the necessary credentials from the cloud services API and then calls create method of datasource service class

### PR DESCRIPTION
**Pull request by AnaghHegde**
## Description

In order to support the ok-to-test added the Cloud services env to the .yml file. 
Fixes #5582 

## Type of change
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
- Test A

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by nidhi-nair** [comment]
@AnaghHegde the reason we do not have this endpoint attached to the tests is because every test would trigger a new "installation" request on release cloud services and that would bloat really fast. Can we mock this connection to cloud-services in your tests?

**Comment by mohanarpit** [comment]
> @AnaghHegde the reason we do not have this endpoint attached to the tests is because every test would trigger a new "installation" request on release cloud services and that would bloat really fast. Can we mock this connection to cloud-services in your tests?

@nidhi-nair Doesnt this already happen in client-test.yml file?

**Comment by AnaghHegde** [comment]
@mohanarpit @nidhi-nair My only concern with mocking the cloud service call is that, entire mock data creation flow depends on the data that comes from the cloud service. So if i mock this, and some entry is changed in Cloud service mongo collection. We will not be aware of this because the unit tests doesn't detect that change.

**Comment by AnaghHegde** [comment]
We have the cypress tests fro this flow. There was some changes made when the UI was not loading because of mock data call failing. If i remember correctly, this failure to mock data call was not hard requirement or something like that. @pranavkanade Can you please confirm about this ?

**Comment by mohanarpit** [comment]
OK. If we already have Cypress tests for this flow, why are we trying to repeat an integration test case across various layers of the system? We can safely mock the cloud-services invocation from the Appsmith server and rely on the Cypress test to raise a flag if the data contract ever changes.

**Comment by pranavkanade** [comment]
@AnaghHegde small correction - in the interest completing the changes in time, I did not add the cypress tests for this. I have some time today, so I'll add those with separate PR

**Comment by nidhi-nair** [comment]
@mohanarpit Shoot, you're right, this never got reverted. @AnaghHegde do you plan to ship this change and then revert it afterwards as you'd mentioned? We'll need to handle both these scenarios accordingly.

**Comment by AnaghHegde** [comment]
@nidhi-nair @mohanarpit I would like to merge it now and raise separate PR with mocked test cases and reverted yml test config files. Would that be okay ?

**Review by mohanarpit — APPROVED** [review]

**Comment by mohanarpit** [comment]
Approving this PR. 

@AnaghHegde Please take the rest of this sprint to refactor your implementation for mock data sets and page order. The more you delay this refactor, the higher the amount of tech debt will need to be paid. Hence, please prioritize & fix these problems while the code is still fresh in your mind.

**Comment by AnaghHegde** [comment]
@mohanarpit Build i s failing because of some error in js code. Can i still merge this or do i need to wait ?

**Comment by mohanarpit** [comment]
Which branch did you fork from? The error is in the file `WidgetOperationSagas.tsx`. Please merge the latest release into this branch and the Typescript compile error should go away.

**Comment by AnaghHegde** [comment]
> Approving this PR.
> 
> @AnaghHegde Please take the rest of this sprint to refactor your implementation for mock data sets and page order. The more you delay this refactor, the higher the amount of tech debt will need to be paid. Hence, please prioritize & fix these problems while the code is still fresh in your mind.

@mohanarpit Yes I will do that. But on the mock data test refactor i realised this just now. Say if i mock the call to cloud service API and hardcode the values in the test class, i would end up exposing credentials for RDS and Mongo. Is that okay ?

**Review by mohanarpit — APPROVED** [review]

**Pull request merged**
