### PR TITLE
fix: ui fixes for git connect v2

### LINKED ISSUE #27346: [Bug]: Issues with Git Connect Modal v2
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

- Container background changes with theme (Should not happen)
- Repository settings link color
- Title while importing
- Scroll issue in modal
- Modal height could be greater
- More test cases

### Steps To Reproduce

1. Create a new application
2. Try to connect it to Git

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by brayn003**
## Description
Fixes minor UI issues with Git Connect V2 modal

#### PR fixes following issue(s)
Fixes #27346

#### Media

- [ ] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Comment by sneha122** [comment]
Client side changes LGTM

**Review by sneha122 — APPROVED** [review]

**Comment by brayn003** [comment]
> /ok-to-test

cancelling this test and re-running with sha

**Pull request merged**
