### PR TITLE
chore: move orientation and label position to content tab"

### LINKED ISSUE #29428: Move orientation setting from style to content
Move the **orientation** setting from the **styles** tab to the **content** tab for all group components (radio, checkbox and switch)

Related thread https://theappsmith.slack.com/archives/C04P60V0VQE/p1700480370654429

orientation-1

### PR DESCRIPTION
**Pull request by jsartisan**
Fixes #29428 

## Summary by CodeRabbit

- **New Features**
  - Introduced new configuration options for widget orientation and label position, allowing users to customize their widgets to be either horizontal or vertical and to position labels on the left or right.

- **Refactor**
  - Simplified the property pane configurations by removing unused style configurations, streamlining the setup for users.

- **Chores**
  - Cleaned up widget configuration code for Checkbox Group, Radio Group, and Switch Group widgets to enhance maintainability and user experience.

### CODE REVIEW

**Review by KelvinOm — APPROVED** [review]
LGTM! May I also ask you to  make right position by default. I'm sure this is more common.

cc @ichik

**Comment by ichik** [comment]
Yes! Definitely for checkbox / radio buttons. For switches convention is a bit less defined, but keeping it same as others helps when building an app, I think.

**Comment by jsartisan** [comment]
@ichik @KelvinOm Change the default of label position as right for all three of them.

**Comment by KelvinOm** [comment]
> @ichik @KelvinOm Changed the default value of label position as right for all three of them. 👍

We have to change this for switch and checkbox as well.

Снимок экрана 2023-12-21 в 11 10 13

**Comment by ichik** [comment]
Yes

**Review by KelvinOm — APPROVED** [review]

**Pull request merged**
