### PR TITLE
feat: Fetch Appsmith version when browser tab comes on focus 

### LINKED ISSUE #9740: [Bug] expected expression, got '<'
Sentry Issue: [APPSMITH-G5](https://sentry.io/organizations/appsmith/issues/2129275999/?referrer=github_integration)

```
UnhandledRejection: Non-Error promise rejection captured with keys: code, message, show
```

### LINKED ISSUE #16235: [Task] Deprecate auto refresh on chunk load fail
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Background
With the use of RTS to identify release version mismatch and prompts to refresh the page, the auto-refresh approach is moot.

- Remove references to `donotReloadOnChunkLoadFail`
- Remove auto-refresh mechanism handled [here](https://github.com/appsmithorg/appsmith/blob/5cf06cd071072959b04b8bf516cec1120a928e70/app/client/public/index.html#L122)

### PR DESCRIPTION
**Pull request by hetunandu**
## Description
Problem:
- When Appsmith upgrades, the older version JS files are no longer hosted on the server.
- When a browser tab with Appsmith is left open for a long time and not in focus, and Appsmith has upgraded in the mean time, the client will request for the older JS files. In this case, an html file is returned by Nginx while the browser expected JS

Solution:
- Ping the RTS server about the tab being back in focus, which will then respond with the current version of Appsmith.
- Version match will kick in on the client and if they don't match, it will ask the user to refresh the page

Fixes #9740 
Fixes #16235

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Manual Test plan:
Run RTS and Appsmith client locally
Switch to another tab on the browser
Update the version number on the RTS code (version.js)
Come back to the Appsmith tab

Assert: A toast is shown to indicate a refresh is needed to update the client

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by riodeuno — APPROVED** [review]

**Comment by ramsaptami** [comment]
- [ ] The refresh prompt is persistent no matter how many times user hits 'REFRESH'
- [ ]  The refresh prompt appears after every page refresh even after version has been updated
- [ ] Refresh prompt appears on the login window after user has logged out (which includes a page refresh action)
cc: @hetunandu @btsgh

**Comment by btsgh** [comment]
After trying steps to test provided by @hetunandu -

1. Stop docker (local instance). Check version.js in appsmith/app/rts/src .. It should have the text - export const VERSION = SNAPSHOT;
2. In terminal Run export REACT_APP_VERSION_ID="SNAPSHOT" 
3. Build normally (from appsmith folder) with ./scripts/local_testing.sh on this PR branch
4. The toast message should not be visible
5. Now - go to some other tab in your browser.
6. Update the rts/version.js (appsmith/app/rts/src) such that it reads -
 export const VERSION = SNAPSHOT_2;
7. Go to the root of appmith in terminal and then run the following commands.
a-pushd app/rts > /dev/null && ./build.sh > /dev/null
b-popd docker build -t appsmith/appsmith-ce:local-testing . > /dev/null
c-(docker stop appsmith || true) && (docker rm appsmith || true)
docker run -d --name appsmith -p 80:80 -v "$PWD/stacks:/appsmith-stacks" appsmith/appsmith-ce:local-testing

(While doing the above steps, at point 7b I get an error on terminal - popd: too many arguments)

**Comment by Rishabh-Rathod** [comment]
Hey, @hetunandu thanks for working on this. 

QQ: Did we also verify if the `index.html` is not being cached? 

Concern: If `index.html` is being cached in the browser then a refresh might result in serving in the cached `index.html` directly from the browser and that `index.html` will still have old chunk hash names.

https://raphael-leger.medium.com/react-webpack-chunkloaderror-loading-chunk-x-failed-ac385bd110e0

**Comment by hetunandu** [comment]
> Hey, @hetunandu thanks for working on this.
> 
> QQ: Did we also verify if the `index.html` is not being cached?
> 
> Concern: If `index.html` is being cached in the browser then a refresh might result in serving in the cached `index.html` directly from the browser and that `index.html` will still have old chunk hash names.
> 
> https://raphael-leger.medium.com/react-webpack-chunkloaderror-loading-chunk-x-failed-ac385bd110e0

In my debugging, I never saw index.html being cached.

**Comment by btsgh** [comment]
Trying the following on QA localhost environment -

**Stop docker (local instance). Check version.js in appsmith/app/rts/src .. It should have the text - export const VERSION = SNAPSHOT;
In terminal Run export REACT_APP_VERSION_ID="SNAPSHOT"
Build normally (from appsmith folder) with ./scripts/local_testing.sh on this PR branch (also tried on release branch)
The toast message should not be visible
So far works well.** 

Now - go to some other tab in your browser.

Update the rts/version.js (appsmith/app/rts/src) such that it reads -
export const VERSION = SNAPSHOT_2;
Go to the root of appmith in terminal and then run the following commands - .

**a-pushd app/rts > /dev/null && ./build.sh > /dev/null

b-popd 
docker build -t appsmith/appsmith-ce:local-testing . > /dev/null

c-(docker stop appsmith || true) && (docker rm appsmith || true)

docker run -d --name appsmith -p 80:80 -v "$PWD/stacks:/appsmith-stacks" appsmith/appsmith-ce:local-testing**

Now on coming back to the localhost tab, check for toast message.

Observation - no toast message is seen. No toast message either on Refresh. 
Discussed and as per @hetunandu - issue with rts as Network tab has no version shown. 
The same scenario also being tried by Yatin now on his QA environment.

**Comment by mohanarpit** [comment]
> export const VERSION = SNAPSHOT_2;

@btsgh Is this line correct? I'm asking because we have to set `export REACT_APP_VERSION_ID="SNAPSHOT_2"` when we change the version itself. Could this be the reason that the RTS isn't responding to the client with a new version ID?

**Comment by btsgh** [comment]
> > export const VERSION = SNAPSHOT_2;
> 
> @btsgh Is this line correct? I'm asking because we have to set `export REACT_APP_VERSION_ID="SNAPSHOT_2"` when we change the version itself. Could this be the reason that the RTS isn't responding to the client with a new version ID?

Hmm. I tried the steps with this statement added in the version.js - `export REACT_APP_VERSION_ID="SNAPSHOT_2"` .. as suggested above, that also did not help. :( 
Still - no toast message is seen. No toast message either on Refresh.
Rts in Network tab still has no version shown.

cc: @mohanarpit @hetunandu

**Review by btsgh — APPROVED** [review]
Tried once again with @hetunandu  - We started from a clean slate (deleting old files / docker container etc) and ran all the scripts mentioned in the above comments again. The test was successful this time. When there was a difference in the client version and the rts version, the toast message correctly came up. Also when the versions were the same, the toast message did not come up.

**Pull request merged**
