### PR TITLE
fix: reset meta keys instead of deleting it

### LINKED ISSUE #6492: [Bug]The File picker button is retained with the "1 file selected " text when the user tries to select the second file
## Description

[What happened] The File picker button is retained with the "1 file selected " text when the user tries to select the second file

### Steps to reproduce the behavior:
1.Click on Generate app 
2.Select s3 datasource 
3.Select bucket as "Assets-test.appsmith.com"
4.click on generate app button
5.Now click on Add file button 
6.Select one file 
7.click on the upload
8.now click on add file again 
9.verify the display

[LOOM DEMO](https://www.loom.com/share/c233efa813404e54b531d5a93e801546)

### Important Details

- Version: [Cloud ]
- OS: [.MacOS]
- Browser [chrome]
- Environment [ deploy preview->6264]

### PR DESCRIPTION
**Pull request by techbhavin**
## Description

>  default property and metaProperty value was different in props so the condition was not executed properly that's why 
> updated data was not reached to file widget

Fixes #6492

## Type of change

- Bugfix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/reset-filepicker 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 54.94 **(0)** | 36.38 **(-0.01)** | 34.61 **(0)** | 55.35 **(0)**
 :red_circle: | app/client/src/utils/WorkerUtil.ts | 88.98 **(-0.78)** | 70.59 **(-1.96)** | 100 **(0)** | 92.38 **(-0.95)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.71 **(-0.23)** | 40.83 **(-0.84)** | 36.21 **(0)** | 56.74 **(-0.25)**</details>

### CODE REVIEW

**Comment by sbalaji1192** [comment]
@techbhavin Shall we close this PR?

**Comment by techbhavin** [comment]
@sbalaji1192 this PR is in review state. Kindly plz review it so we can send it to QA

**Comment by sbalaji1192** [comment]
@techbhavin Could you check the comment I posted on the corresponding issue ?

**Comment by techbhavin** [comment]
closing this PR this issue is solved By [issue-9603](https://github.com/appsmithorg/appsmith/issues/9603)

**Pull request closed without merging**
