### PR TITLE
fix: auto height limits deploy mode

### PR DESCRIPTION
**Pull request by ankurrsinghal**
Added the dynamic container into the deploy mode as well by enhancing the `getWidgetComponent` to add the dynamicHeightContainer in the getPageView. I didn't try to refactor the code because that will involve removing some code from the `getCanvasView` (ErrorBoundary).

### CODE REVIEW

**Comment by riodeuno** [comment]
@ankurrsinghal The vercel deploy failed here, could you push another update to this PR, so that it runs again? We want to make sure that the deploy previews work before merging, otherwise, we'll be blocking the QA.

**Comment by riodeuno** [comment]
Also, we will need this for the preview mode as well.

**Comment by riodeuno** [comment]
@ankurrsinghal Does this work in preview mode?

**Review by riodeuno — APPROVED** [review]

**Comment by riodeuno** [comment]
@ankurrsinghal Please make sure that vercel deployment succeeds before merging this in.

**Comment by ankurrsinghal** [comment]
@riodeuno deployment successful, merging the changes.

**Pull request merged**
