### PR TITLE
fix: Fixing unwanted GRID_DENSITY_MIGRATION_V1 based configs.

### LINKED ISSUE #9946: [Bug]: Enforcing validation on the row value for widgets
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It is observed that for widgets with row value to be `rows: <FLOAT> * GRID_DENSITY_MIGRATION_V1,` e.g. `rows: 1.1 * GRID_DENSITY_MIGRATION_V1,` causes misalignment with the grid lines present on the canvas. 

This needs to be incorporated to maintain the integrity of the widget configs.

### Steps To Reproduce

Observe the line of code in the file: https://github.com/appsmithorg/appsmith/blob/release/app/client/src/widgets/CheckboxWidget/index.ts#L11

`    rows: 1.1 * GRID_DENSITY_MIGRATION_V1,`

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by marks0351**
## Description

Have made a mistake of using  GRID_DENSITY_MIGRATION_V1 to update the then config file used to declare default dimensions of widgets. removing those references since it is just a constant whose usage was supposed to be deprecated after the migration.
also have added validation checks to make sure no float values are added for a widget dimension as default.

Fixes #9946

> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/grid-constant-misused 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 55.08 **(-0.05)** | 36.87 **(-0.02)** | 34.99 **(-0.05)** | 55.56 **(-0.05)**
 :red_circle: | app/client/src/sagas/OnboardingSagas.ts | 16.46 **(-0.21)** | 1.32 **(0)** | 10.91 **(0)** | 16.72 **(-0.24)**
 :green_circle: | app/client/src/utils/WorkerUtil.ts | 89.76 **(0.78)** | 72.55 **(1.96)** | 100 **(0)** | 93.33 **(0.95)**
 :red_circle: | app/client/src/utils/helpers.tsx | 63.12 **(-3.99)** | 29.44 **(-4.45)** | 50.98 **(-9.8)** | 60.68 **(-4.28)**
 :green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.94 **(0.23)** | 41.67 **(0.84)** | 36.21 **(0)** | 56.99 **(0.25)**
 :red_circle: | app/client/src/widgets/SkeletonWidget.tsx | 93.33 **(-0.42)** | 100 **(0)** | 75 **(0)** | 92.86 **(-0.47)**</details>

### CODE REVIEW

**Review by jsartisan — APPROVED** [review]

**Comment by vivekverma2312** [comment]
@marks0351 Tested and LGTM.

**Pull request merged**
