### PR TITLE
fix: Theming is not applied to Table's 'Delete' & JSONForm's 'Reset & Update' buttons in Crud template

### LINKED ISSUE #14106: [Bug]: CURD >> JSONForm | Theming is not applied to Table's 'Delete' & JSONForm's 'Reset & Update' buttons
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

**New CRUD page - observe the Table's Delete button & JSON From's Reset/Update buttons:**
Screenshot 2022-05-24 at 2 40 53 PM

**As opposed to theming applied on a normal Table & JSON form widgets:**
Screenshot 2022-05-24 at 3 46 44 PM

### Steps To Reproduce

1. Create new CRUD page from any data source
2. Apply some theme per user wish
3. **Observe the buttons' in the page - the theme properties is not applied**
4. **Observe - In Delete modal & Insert Modal also - the theme properties for buttons are not applied**
5. **Expected: New CRUD page should also comply with the theme applied**

### Public Sample App

_No response_

### Version

Prod/Release v1.7.1

### PR DESCRIPTION
**Pull request by jsartisan**
## Description
This PR makes the changes required in crud templates in order for theming to work

Fixes #14106

## Type of change

- Bug fix

## How Has This Been Tested?
- Manually tested

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Aishwarya-U-R — DISMISSED** [review]

**Comment by abhvsn** [comment]
@jsartisan which app are you using to fix this as I'm seeing the theming changes pending in template app https://release.app.appsmith.com/app/crud-app-templates/postgresql-61764fbeba7e887d03bc3643

**Review by abhvsn — APPROVED** [review]

**Pull request merged**
