### PR TITLE
fix: Spacing for encrypted tag for form control

### LINKED ISSUE #11046: [Bug]: Encrypted tag for form control lacks spacing
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Screenshot 2022-02-09 at 4 43 48 PM

### Steps To Reproduce

1. Go to Authenticated API datasource
2. Select API Key authentication type
3. Look at `Value` field

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by danieldare**
## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
Manually

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>

    // Code coverage diff between base branch:release and head branch: fix/encryted-tage-form-spacing 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | app/client/src/components/editorComponents/form/fields/StyledFormComponents.tsx | 67.86 **(2.48)** | 17.39 **(1.83)** | 0 **(0)** | 67.86 **(2.48)**</details>

### CODE REVIEW

**Comment by nidhi-nair** [comment]
@danieldare could you please add someone from the frontend as reviewer? I'm not aware of the practice followed for styling components myself.

**Review by Irongade — APPROVED** [review]

**Pull request merged**
