### PR TITLE
chore: removed onboarding flags ab_create_new_apps_enabled , ab_start_with_data_default_enabled

### LINKED ISSUE #31279: [Task]: Remove the code for ab_start_with_data_default_enabled feature flag
### SubTasks

- [ ] Remove the code that uses `ab_start_with_data_default_enabled` flag for the conditions to render components
- [ ] Check about the status of `ab_create_new_apps_enabled` whether it should be enabled for all or not

### PR DESCRIPTION
**Pull request by AmanAgarwal041**
## Description
- Removed flags from codebase `ab_create_new_apps_enabled` & `ab_start_with_data_default_enabled`
- Updated the signup cypress function to skip to application on user signing up

Fixes #31279  

## Automation

/ok-to-test tags="@tag.Datasource, @tag.Workspace"

## Summary by CodeRabbit

- **New Features**
	- Added dynamic `key` prop to `ApiCard` component to enhance UI responsiveness.

- **Bug Fixes**
	- Improved reliability of API and DataSource interactions in test scripts by utilizing `agHelper.GetNClick`.
	- Refined MySQL datasource interaction in Cypress tests for increased stability.

- **Refactor**
	- Streamlined and optimized the `CreateNewAppsOption` component for better performance and maintainability.
	- Enhanced test scripts by replacing direct clicks with utility function calls for better code reuse and readability.

- **Chores**
	- Removed obsolete feature flags related to app creation and data management, simplifying feature management.

> [!IMPORTANT]  
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/8280765705>
> Commit: `d8bbb7f2a32d9604b134d88995c911e7f83f4f06`
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=8280765705&attempt=1" target="_blank">Click here!</a>
> All cypress tests have passed 🎉🎉🎉

### CODE REVIEW

**Comment by sneha122** [comment]
@AmanAgarwal041 Changes LGTM, asking @Parthvi12 to review cypress files

**Review by sneha122 — APPROVED** [review]

**Comment by sneha122** [comment]
@AmanAgarwal041 Tested the onboarding flow once along with that widget binding and query creations, looks good. Let me know if you want me to specifically test any other areas, otherwise looks good!

**Review by Parthvi12 — APPROVED** [review]

**Pull request merged**
