### PR TITLE
fix: reinstating multienv switcher for view mode

### LINKED ISSUE #31266: [Bug]: Datasource Environment Selector Not Appearing in Deployed Version of App
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

According to the docs -- https://docs.appsmith.com/connect-data/how-to-guides/setup-datasource-environments#switch-environments :

```In addition, users with the necessary permissions can also switch to the Staging environment configuration when accessing the app in View mode. For more information on permissions, you can refer to the [Granular Access Control](https://docs.appsmith.com/advanced-concepts/granular-access-control).```

However, I don't see any selector in the View mode for switching environments. I'm assuming that since I can Edit the app I should have the permissions to switch datasources.

### Steps To Reproduce

1. Open any app that has multiple enviornments configured
2. Open that app in view mode
3. There is no selector to switch environments

### Public Sample App

_No response_

### Environment

Production

### Issue video log

https://www.loom.com/share/89371ffff6de43859e4e0829a99f808d

### Version

Self Hosted -- Appsmith v1.10

### PR DESCRIPTION
**Pull request by brayn003**
## Description
Adds multiple env switcher to the bottom bar

Fixes #31266 

## Automation
/ok-to-test tags="@tag.MultiEnv"

### :mag: Cypress test results

> [!IMPORTANT]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/8440725278>
> Commit: `eae7d87a07c270a460049f124fe90277f997cd58`
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=8440725278&attempt=1" target="_blank">Click here!</a>
> All cypress tests have passed 🎉🎉🎉

## Summary by CodeRabbit

- **New Features**
	- Introduced a `BottomBar` component in the `AppViewer` for enhanced navigation and quick actions, conditionally displayed based on multiple environments and specific feature flags.
	- Added a custom React hook `useShowEnvSwitcher` to determine the visibility of the environment switcher based on various conditions.
- **Refactor**
	- Improved visibility of the `SwitchEnvironment` component and `QuickGitActions` by adjusting their rendering logic, ensuring they are always visible when `viewMode` is false.

### CODE REVIEW

**Comment by somangshu** [comment]
@ayushpahwa please review if needed. 

@brayn003 is this still relevant, seems like open for quite a while now. Kindly close this ASAP.

**Comment by brayn003** [comment]
@somangshu I am still actively working on it. It has been open for sometime because the scope had changed during the implementation. I am planning to push it out within this week

**Review by ankitakinger — APPROVED** [review]

**Pull request merged**
