### PR TITLE
fix: function undefined error after resetWidget is called due to sync…

### PR DESCRIPTION
**Pull request by rishabhrathod01**
## Description

Fixed the error of async function like `Api.run` being `undefined` after running `resetWidget`. 

#### Context:-
we have 2 types of evaluation i.e., sync and async evaluation.

These are dependent on the field we are evaluating, for the data field we use sync evaluation and for the trigger field, we use async evaluation. In Async evaluation, we also define entity functions like `Api.run`.
- In resetWidget code, internally we were switching to sync evaluation and we forgot to add code to switch back to async and due to this code that was after it was throwing an `undefined` error. 

Fixes https://github.com/appsmithorg/appsmith/issues/33601

### Steps to reproduce 

1. Import user’s application ( shared on slack )
2. Go to JSObj_Main JSObject
3. Check the onClickCopySheetTemplate function 
4. Comment the  await Qry_C_CopySheetTemplate.run(); line and run the function.
5. On release it will throw error for Qry_R_SheetTemplate.run(); not being defined but will work fine on DP. 

## Automation

/ok-to-test tags="@tag.JS"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9170093222>
> Commit: f9e8893d12cedbd9d2368cd9609bda7b86816588
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9170093222&attempt=1" target="_blank">Click here!</a>

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by ApekshaBhosale** [comment]
@rishabhrathod01 in the issue created you have written "resetWidget function causes the next async method to be undefined". so we need to switch it back to async for next method. why can't we do this before calling next async rather than depending on previous one to be in the right context?

**Comment by rishabhrathod01** [comment]
> in the issue created you have written "resetWidget function causes the next async method to be undefined". so we need to switch it back to async for next method. why can't we do this before calling next async rather than depending on previous one to be in the right context? 

@ApekshaBhosale 

1. As the next async method will be undefined in the eval context, we won't be able to trigger the switch of sync to async evaluation as we won't know when the code got executed. 

For example:- 
```
resetWidget(WidgetName);
Api.run();
```
Here once the resetWidget is executed, we won't be able to switch back to async eval as `Api.run()` itself is not defined to let us know if this was called. Also, we want to default evaluation context to be always async this is because any async operation could be picked from the task queue.

2. By design itself, an async method is not supposed to change the evaluation from async to sync, in the case of `resetWidget` it was a bug that internally it was doing a sync eval but we didn’t switch back.

**Comment by ApekshaBhosale** [comment]
> > in the issue created you have written "resetWidget function causes the next async method to be undefined". so we need to switch it back to async for next method. why can't we do this before calling next async rather than depending on previous one to be in the right context?
> 
> @ApekshaBhosale
> 
> 1. As the next async method will be undefined in the eval context, we won't be able to trigger the switch of sync to async evaluation as we won't know when the code got executed.
> 
> For example:-
> 
> ```
> resetWidget(WidgetName);
> Api.run();
> ```
> 
> Here once the resetWidget is executed, we won't be able to switch back to async eval as `Api.run()` itself is not defined to let us know if this was called. Also, we want to default evaluation context to be always async this is because any async operation could be picked from the task queue.
> 
> 2. By design itself, an async method is not supposed to change the evaluation from async to sync, in the case of `resetWidget` it was a bug that internally it was doing a sync eval but we didn’t switch back.

Understood! then reset Widget should be in async always isn't it? rather than setting it back. AFAIK we were treating all Appsmith platform functions as async and executing them in async context. @rishabhrathod01

**Comment by rishabhrathod01** [comment]
> Understood! then reset Widget should be in async always isn't it? rather than setting it back. AFAIK we were treating all Appsmith platform functions as async and executing them in async context. @rishabhrathod0

@ApekshaBhosale `resetWidget` is an async API as shown in below code screenshot. 
image

We added an sync evaluation inside the resetWidget to fix bug explained in this comment https://github.com/appsmithorg/appsmith/pull/29151/files#r1607899227

**Review by ApekshaBhosale — APPROVED** [review]

**Pull request merged**
