### PR TITLE
fix: Date picker must exit on pressing esc key when 'close on selecting' is turned off 

### LINKED ISSUE #6798: [Enhancement] Date picker must exit on pressing esc key when 'close on selecting' is turned off
## Summary
When **date picker widget** has 'close on selection' turned off, then user has to click away from the date picker pop-up in order to close the calendar. Pressing on **Esc key** must also close the calendar - which is not supported currently. Only the property pane exits on pressing the **Esc key**.

### PR DESCRIPTION
**Pull request by onifs10**
## Description
Date picker now closes on **escape** key down and **tab** key down 

Fixes #6798

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by onifs10** [comment]
> @onifs10 I'm finding someone from the team to review this for you

Alright

**Comment by somangshu** [comment]
@onifs10 you PR is failing semantic tests, Your commit messages and PR title need to be properly formatted to pass, Kindly check [here](https://github.com/zeke/semantic-pull-requests)

**Comment by SatishGandham** [comment]
@vivekverma2312 This needs QA.

**Comment by somangshu** [comment]
@SatishGandham please merge this once done!

**Comment by keyurparalkar** [comment]
@SatishGandham The feature of closing the pop-up is actually working both on the Release app and on the netlify preview link. Can you please take a call on this?

**Review by SatishGandham — APPROVED** [review]

**Pull request merged**
