### PR TITLE
fix: theme updated with new variant keys

### LINKED ISSUE #8533: TypeError: Cannot read properties of undefined (reading 'hoverColor')
Sentry Issue: [APPSMITH-199](https://sentry.io/organizations/appsmith/issues/2717988459/?referrer=github_integration)

```
TypeError: Cannot read properties of undefined (reading 'hoverColor')
  at getCustomHoverColor (widgets/WidgetUtils.ts:99:7)
  at id (widgets/MenuButtonWidget/component/index.tsx:76:9)
  at he (../../src/models/Keyframes.js:20:51)
  at isCompositeComponent (../../src/utils/isStaticRules.js:6:54)
  at isCompositeComponent (../../src/models/StyledComponent.js:194:9)
...
(16 additional frame(s) were not displayed)
```

### LINKED ISSUE #8646: [Bug]: The button widgets breaks when label and color properties are empty
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the user delete Label and Button color from the property pane " Oops something went wrong  click here to retry" message is displayed 
[LOOM DEMO](https://www.loom.com/share/9d7eea811cdf4e3dabde48f9d13ff254)

### Steps To Reproduce

```markdown
1. Go to canvas
2. Click on the widget tab
3. Drag and drop the button widget
4. Now delete Label and button color 
5. the " Oops something went wrong  click here to retry" message is displayed "
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/9d7eea811cdf4e3dabde48f9d13ff254-00001.gif)](https://www.loom.com/share/9d7eea811cdf4e3dabde48f9d13ff254)
```

### Environment

Release

### Version

Cloud

### PR DESCRIPTION
**Pull request by techbhavin**
## Description

> update default theme 

Fixes #8646 
Fixes #8533 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: bug/btn-wid-theme-break 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 54.82 **(0.01)** | 36.58 **(0.04)** | 33.45 **(0)** | 55.36 **(0.01)**
 :green_circle: | app/client/src/widgets/WidgetUtils.ts | 83.33 **(10.41)** | 59.38 **(31.25)** | 50 **(0)** | 79.49 **(12.82)**</details>

### CODE REVIEW

**Comment by marks0351** [comment]
@techbhavin I think there are some review comments that are still not addressed, can you pls check.

**Comment by somangshu** [comment]
@techbhavin [comment](https://github.com/appsmithorg/appsmith/issues/8646#issuecomment-949292849) on issue as well

**Review by marks0351 — APPROVED** [review]

**Comment by YogeshJayaseelan** [comment]
@techbhavin Verified this PR now Hovercolor or Textcolor error are not occurring by removing button colour or label names on icon, menu and button widgets and looks good to me

**Comment by somangshu** [comment]
@techbhavin do not forget to run the CI, and also paste the correct action link here, Once you see everything passing, Please let me know, Ill merge it

**Comment by techbhavin** [comment]
https://github.com/appsmithorg/appsmith/actions/runs/1428591189

**Pull request merged**
