### PR TITLE
feat: remove collapse sections

### PR DESCRIPTION
**Pull request by ayushpahwa**
#### PR fixes following issue(s)
Fixes EE issue !427

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
- [x] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [x] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [x] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Comment by tanvibhakta** [comment]
Hey folks, is this still relevant? If so, I'd like to approve it after QA has gone through it once.

**Comment by ayushpahwa** [comment]
> Hey folks, is this still relevant? If so, I'd like to approve it after QA has gone through it once.

Yes @tanvibhakta , this needs to go in soon. I fixed an ADS bug with the checkbox control also. Please do go through once more. Thanks!

**Comment by AmanAgarwal041** [comment]
@ayushpahwa Are we still working on this ? Asking because many of the test cases are failing

**Comment by ayushpahwa** [comment]
@AmanAgarwal041 yup, working on this. Actually this is blocked by #23920 . Once that is merged in, we'll be able to proceed here. Setting it as draft for now.

**Review by AmanAgarwal041 — APPROVED** [review]

**Pull request merged**
