### PR TITLE
fix: Widget Property Pane Updates

### PR DESCRIPTION
**Pull request by Nikhil-Nandagopal**
## Description

This change updates the property panes of different widgets to make controls more discoverable with lighter text
It also updates the default sizes and configurations of a few widgets to make them easier to drag and drop and maintain consistency

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: property-pane-updates 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 54.8 **(0)** | 36.54 **(-0.01)** | 33.93 **(0)** | 55.35 **(0)**
 :red_circle: | app/client/src/pages/Editor/Explorer/PluginGroup/PluginGroup.tsx | 88.46 **(0)** | 60.78 **(-0.62)** | 60 **(0)** | 88 **(0)**</details>

### CODE REVIEW

**Review by somangshu — APPROVED** [review]
LGTM

@vivekverma2312 lets test this at priority, We want to be able to close this ASAP. Let me know if you need any help

**Review by somangshu — APPROVED** [review]
Approving for tests to run

**Review by somangshu — DISMISSED** [review]
Approving to rerun tests

**Comment by vivekverma2312** [comment]
@Nikhil-Nandagopal List of issues observed:
1. Image widget name is getting cropped in List widget

Screenshot 2021-09-17 at 2 16 44 PM

2. JS Object is not coming in Entity Explorer to test js action line 21


Screenshot 2021-09-17 at 2 16 58 PM
3. Placeholder for fusion chart is not proper
Screenshot 2021-09-17 at 2 16 36 PM

**Review by Rishabh-Rathod — APPROVED** [review]
For test

**Pull request merged**
