### PR TITLE
fix: clean implementation of isAutoHeightEnabledForWidget 

### LINKED ISSUE #20110: Clean the implementation of isAutoHeightEnabledForWidget
- [ ] Using flags for a specific purpose is difficult in terms of readability.
- [ ] Create a new function which does this special computation that is done today using the flag.
- [ ] Refactor any references.

_Originally posted by @marks0351 in https://github.com/appsmithorg/appsmith/pull/19082#discussion_r1086240821_

### PR DESCRIPTION
**Pull request by nikhil-babar**
## Description

The previous implementation of isAutoHeightEnabledForWidget function was having flag for checking feature with limits which did not fit in clean code principles 
The PR consist of a clean implementation of isAutoHeightEnabledForWidgetWithLimits and change in references accordingly.

Fixes #20110

## Type of change

- Bug fix 

## How Has This Been Tested?

- Manual

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by riodeuno — DISMISSED** [review]
@nikhil-babar  Thank you for contributing to the codebase! The changes look good to me. I'm running the tests on this.

**Comment by riodeuno** [comment]
@nikhil-babar There is a conflict in one of the files, would you mind resolving the conflict? I'll run the automated tests once this is resolved.

**Comment by nikhil-babar** [comment]
@riodeuno conflict is resolved

**Review by riodeuno — APPROVED** [review]
Looks good to me!

**Comment by mohanarpit** [comment]
@all-contributors Please add @nikhil-babar as a contributor for refactoring our code and making it easier to maintain.

**Comment by sharat87** [comment]
@mohanarpit, FYI, we don't use all-contributors, we have an automation that runs regularly to update the whole list based on all commits and issue discussion participation.

**Comment by pranavkanade** [comment]
@nikhil-babar Great job! I want to celebrate your contribution. Can you share your discord username with me?

**Pull request merged**
