### PR TITLE
fix: Resize form.png

### PR DESCRIPTION
**Pull request by Swatigupta-droid**
Resized form.png
Changed the size to fit screen

## Description

After resizing we can see the image without scrolling by just fit to screen size

Fixes https://github.com/appsmithorg/appsmith/issues/8088

### CODE REVIEW

**Comment by areyabhishek** [comment]
Thank you @Swatigupta-droid for the issue and the fix! Welcome to Appsmith! This is a simple fix for a better UX.
We'll merge this in

**Comment by ps-19** [comment]
Can someone tell what issue is this PR is facing? why it isn't merged yet!

**Comment by Rishabh-Rathod** [comment]
@Swatigupta-droid and @ps-19 this PR is not yet reviewed from our side which is required for few checks to run.

**Comment by Rishabh-Rathod** [comment]
@vihar Can you review this PR?

**Comment by Swatigupta-droid** [comment]
opened a new PR #8929 .It has conflicts which i dont know how to resolve so hoping for the best.
@vihar @Rishabh-Rathod @areyabhishek

**Comment by Rishabh-Rathod** [comment]
> opened a new PR #8929 .It has conflicts which i dont know how to resolve so hoping for the best. @vihar @Rishabh-Rathod @areyabhishek

You will need to fetch and merge changes from Appsmith's repo.
https://stackoverflow.com/questions/7244321/how-do-i-update-or-sync-a-forked-repository-on-github

**Comment by mohanarpit** [comment]
Apologies for the delay in getting to this PR. 😞 

I'm closing this PR for now because I'm unable to resolve the conflicts & push to this branch. Please re-open this PR after resolving the conflicts from the base `release` branch & we'll fast track this merge.

**Pull request closed without merging**
