### PR TITLE
fix: Add meta to eval cycle and update it when default changes

### LINKED ISSUE #10026: [Bug]: Input updates with default values are not captured
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This happens intermittently. At times the input widget value with default value does not update correctly

### Steps To Reproduce

This happens intermittently

- Have a table row value bound to an input widget default value
- Call a query/Api to save these inputs
- Switch rows and update the input with the same values
- Sometimes the input does not get saved with the right value

### Environment

Production

### Version

Self-Hosted

### PR DESCRIPTION
**Pull request by Rishabh-Rathod**
## Description
Fixes #10026

Why do we need to make these changes?
The below video has a demo of the issue and a workaround suggested.
[LOOM DEMO](https://www.loom.com/share/25988c2943624bbab04c54cd0f23f096)

App link - https://release.app.appsmith.com/applications/61cf0a7e36b4fc684f391ee8/pages/61cf0a7e36b4fc684f391eeb

This PR changes how we use meta values in Appsmith, note the following points to understand better  

1. Previously meta values stored in metaReducer were used to directly overwrite changes to the data tree. (`unEvalDataTree` )
for eg:- For InputWidget's  `text` field, the update in metaReducer used to directly update the `text` field in the widget data tree.
2. The problem arises when the input widget is bound to widget property which changes with user interaction, for example - `selectedRow` of Table widget.
As we don't update the meta reducer's value with a new evaluated default value, it often has a stale value.
3. When user tried to make an update to Input Widget value with same value as old stale value, as there is no change in reducer this change doesn't reach to evaluation and hence doesn’t get reflected.

meta discussion - Frame 1

### Changes made

1. Meta values are also stored in the data tree and when the default value is evaluated on change, it overrides both the main value and meta value. for eg- `defaultText` updates both `meta.text` and `text`.
2. This meta value in the data tree then is updated in the meta reducer to keep values in sync.

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Cypress

## Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix-meta-eval 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 55.03 **(0.03)** | 36.56 **(0)** | 34.93 **(0)** | 55.44 **(0.04)**
 :red_circle: | app/client/src/actions/metaActions.ts | 65 **(-16.82)** | 0 **(-100)** | 20 **(-13.33)** | 56.25 **(-18.75)**
 :green_circle: | app/client/src/entities/DataTree/dataTreeFactory.ts | 47.5 **(4.26)** | 100 **(0)** | 50 **(7.14)** | 46.15 **(4.48)**
 :green_circle: | app/client/src/entities/DataTree/dataTreeWidget.ts | 98.08 **(13.23)** | 75 **(50)** | 100 **(20)** | 97.83 **(13.45)**
 :sparkles: :new: | **app/client/src/entities/DataTree/utils.ts** | **100** | **90.91** | **100** | **100**
 :red_circle: | app/client/src/pages/Editor/WidgetsEditor/index.tsx | 93.65 **(-0.2)** | 62.07 **(0)** | 100 **(0)** | 93.33 **(-0.22)**
 :red_circle: | app/client/src/reducers/entityReducers/metaReducer.ts | 32.5 **(-10.36)** | 0 **(0)** | 20 **(-8.57)** | 34.21 **(-8.65)**
 :red_circle: | app/client/src/sagas/EvaluationsSaga.ts | 20.09 **(-0.09)** | 2.13 **(0)** | 8 **(-3.11)** | 23.04 **(-0.04)**
 :red_circle: | app/client/src/sagas/WidgetDeletionSagas.ts | 42.68 **(-0.09)** | 26.39 **(0)** | 42.11 **(0)** | 43.48 **(-0.09)**
 :green_circle: | app/client/src/utils/DynamicBindingUtils.ts | 84.44 **(0.37)** | 72.32 **(0.89)** | 75.86 **(0)** | 83.85 **(0.41)**
 :red_circle: | app/client/src/utils/WorkerUtil.ts | 88.98 **(-0.78)** | 70.59 **(-1.96)** | 100 **(0)** | 92.38 **(-0.95)**
 :green_circle: | app/client/src/widgets/MetaHOC.tsx | 85.25 **(2.9)** | 57.89 **(0)** | 92.31 **(0)** | 83.93 **(0.88)**
 :green_circle: | app/client/src/workers/DataTreeEvaluator.ts | 76.49 **(0.14)** | 57.24 **(-0.71)** | 74.42 **(1.3)** | 76.37 **(0.09)**
 :green_circle: | app/client/src/workers/evaluation.worker.ts | 8.11 **(0.52)** | 0 **(0)** | 33.33 **(0)** | 8.63 **(0.58)**
 :green_circle: | app/client/src/workers/evaluationUtils.ts | 58.41 **(-0.92)** | 56.61 **(1.7)** | 64.52 **(0.73)** | 57.75 **(0.61)**
 :red_circle: | app/client/src/workers/validations.ts | 76.79 **(-0.29)** | 69.37 **(-1.68)** | 67.65 **(0)** | 78.59 **(-0.32)**</details>

### CODE REVIEW

**Review by ohansFavour — APPROVED** [review]

**Comment by ohansFavour** [comment]
Requires quality assurance.

cc: @ramsaptami

**Review by ramsaptami — APPROVED** [review]
Tested ok on deploy preview

**Pull request merged**
