### PR TITLE
fix: handle dropdown flickers

### LINKED ISSUE #12714: [Bug]-[480]:Tree select widget - dropdown flickers when we click on the default selection area and filter has text entered.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In tree select widget, in the dropdown on attempt to filter, with the text entered, if we click on the tree select default field, dropdown flickers and does not get expanded. 

### Steps To Reproduce

1. Drag and drop a tree select widget
2. Click on the dropdown arrow
3. Enter a letter to filter. The options having that letter will get highlighted
4. Now click on the default selection area. Dropdown gets closed
5. Again click on the default selection area. 
 The dropdown flickers. It does not get displayed completely. Only when user clicks on the arrow to the right of the select area, the dropdown appears properly.

Expected behaviour - dropdown should get displayed even on clicking on default selection area, with filter applied.

[LOOM DEMO](https://www.loom.com/share/9041091f41e44e509a247a989092d781)

### Public Sample App

_No response_

### Version

Release

### PR DESCRIPTION
**Pull request by techbhavin**
## Description

> fixed flickers issue on SelectTree widget while clicking on the default selection area and filter has text entered

Fixes #12714

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>

    // Code coverage diff between base branch:release and head branch: fix/issue-12714 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 56.45 **(-0.01)** | 37.92 **(0.01)** | 36.17 **(0)** | 56.68 **(0)**
 :green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.94 **(0.23)** | 41.67 **(0.84)** | 36.21 **(0)** | 56.99 **(0.25)**
 :red_circle: | app/client/src/widgets/SingleSelectTreeWidget/component/index.tsx | 15.91 **(-0.56)** | 0 **(0)** | 0 **(0)** | 17.72 **(-0.7)**</details>

### CODE REVIEW

**Review by jsartisan — APPROVED** [review]

**Comment by YogeshJayaseelan** [comment]
@techbhavin Can you share the DP link for this PR

**Comment by YogeshJayaseelan** [comment]
@techbhavin Tested this PR and it is working as expected now

**Pull request merged**
