### PR TITLE
fix: #8528 Added default Icon column 

### LINKED ISSUE #8528: [Bug]: Default icon is not displayed by changing the table column type to icon button
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It is observed that by changing the table column type to icon - default icon is not displayed due to which that particular column looks like empty 

https://loom.com/share/0a351269eaac495cbf01d6206ab21f98

### Steps To Reproduce

```markdown
1.Launch Appmsith app in release/Prod Environment 
2.Drag and drop table widget 
3.Change any of the column type to icon and observe
```

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by vibhandikyash**
## Description

> Default icon was not displayed by changing the table column type to icon button, Added default Icon name for control type.

Fixes #8528 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Tested Locally.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/8528-default-icon-column-type-icon-button 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 54.57 **(0)** | 36.42 **(-0.02)** | 33.17 **(0)** | 55.09 **(0)**
 :red_circle: | app/client/src/components/propertyControls/IconSelectControl.tsx | 41.94 **(-1.39)** | 22.22 **(-4.45)** | 20 **(0)** | 45.45 **(0)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.04 **(-0.22)** | 40.42 **(-0.83)** | 34.48 **(0)** | 55.96 **(-0.26)**
 :green_circle: | app/client/src/widgets/TableWidget/widget/index.tsx | 26.67 **(0.18)** | 6.05 **(-0.04)** | 28 **(0)** | 26.56 **(0.2)**</details>

### CODE REVIEW

**Review by somangshu — DISMISSED** [review]
LGTM

**Comment by vibhandikyash** [comment]
https://github.com/appsmithorg/appsmith/actions/runs/1448325124

**Review by somangshu — APPROVED** [review]

**Pull request merged**
