### PR TITLE
fix: cyclic dependency on array of objects removal

### LINKED ISSUE #13308: [Bug]: occasional cyclic dependency on user's app (potentially due to array bindings)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Happens randomly when changing select widget option.
Data sensitive app, so not sharing screenshots.

[cyclic-dependency-error-object.txt](https://github.com/appsmithorg/appsmith/files/8560971/cyclic-dependency-error-object.txt)

Update: (steps to repro)
[LOOM DEMO](https://www.loom.com/share/044a520a6a9e4bbdb9b63c35f508d2e9)

---

Suggested to use promise chaining for consequent async actions.

---

Suggested changes to bindings
```
{{ 
function() {
    const data = get_client_info.data;
    return appsmith.store.cust_id === "" ? "" : data[0]["id"];
}()
}}
```

instead of 
```
{{ 
    appsmith.store.cust_id === "" ? "" : get_client_info.data[0]["id"];
}}
```

---

### Steps To Reproduce

Happens randomly when changing select widget option.

### Public Sample App

_No response_

### Version

Self hosted - v1.6.20

### PR DESCRIPTION
**Pull request by eco-monk**
## Description
Add array accessors in `translatedDiffs` so they're updated properly in the `dependencyMap`

Fixes #13308

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Unit tests
If any code change causes this error again. 
Unit tests written here should catch this. (as shown below)
image

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

**Test Plan**
- [x] https://github.com/appsmithorg/TestSmith/issues/1737

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/cyclic-dependency 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 56.68 **(0.03)** | 38.73 **(0.05)** | 35.99 **(0.02)** | 56.94 **(0.03)**
 :red_circle: | app/client/src/selectors/commentsSelectors.ts | 83.61 **(-1.64)** | 61.76 **(-2.95)** | 73.33 **(0)** | 88.24 **(-2.35)**
 :green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.94 **(0.23)** | 41.67 **(0.84)** | 36.21 **(0)** | 56.99 **(0.25)**
 :green_circle: | app/client/src/workers/evaluationUtils.ts | 65.4 **(1.56)** | 63.9 **(1.71)** | 69.7 **(0.95)** | 63.73 **(1.76)**
 :green_circle: | app/client/src/workers/helpers.ts | 83.87 **(0)** | 50 **(6.25)** | 100 **(0)** | 88 **(0)**
 :green_circle: | app/client/src/workers/validations.ts | 81.79 **(1.4)** | 72.7 **(1.37)** | 77.42 **(3.23)** | 82.87 **(1.52)**
 :green_circle: | app/client/src/workers/DataTreeEvaluator/DataTreeEvaluator.ts | 80.62 **(0)** | 60.57 **(0.63)** | 78.65 **(0)** | 80.59 **(0)**
 :sparkles: :new: | **app/client/src/workers/DataTreeEvaluator/test/mockData/ArrayAccessorTree.ts** | **100** | **100** | **100** | **100**
 :sparkles: :new: | **app/client/src/workers/DataTreeEvaluator/test/mockData/NestedArrayAccessorTree.ts** | **100** | **100** | **100** | **100**
 :sparkles: :new: | **app/client/src/workers/DataTreeEvaluator/test/mockData/mockUnEvalTree.ts** | **100** | **100** | **100** | **100**
 :x: | ~~app/client/src/workers/DataTreeEvaluator/test/mockUnEvalTree.ts~~ | ~~100~~ | ~~100~~ | ~~100~~ | ~~100~~</details>

### CODE REVIEW

**Review by ApekshaBhosale — APPROVED** [review]

**Comment by eco-monk** [comment]
Resolved merge conflicts.

**Review by ApekshaBhosale — APPROVED** [review]

**Pull request merged**
