### PR TITLE
fixed mysql plugin tests

### LINKED ISSUE #13998: [Bug]: mysqlPlugin tests failing on WSL and Ubuntu
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

mysqlPlugin tests fail

### Steps To Reproduce

Run mysqlPlugin tests on WSL on windows
or
Run mysqlPlugin tests on Ubuntu
Tests fail with the following error
`
[ERROR] Tests run: 28, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 139.706 s <<< FAILURE! - in com.external.plugins.MySqlPluginTest
[ERROR] testExecuteDataTypesExtensive(com.external.plugins.MySqlPluginTest)  Time elapsed: 0.144 s  <<< FAILURE!
java.lang.AssertionError
        at com.external.plugins.MySqlPluginTest.lambda$45(MySqlPluginTest.java:863)
`

### Public Sample App

_No response_

### Version

Appsmith v1.6.26-SNAPSHOT

### PR DESCRIPTION
**Pull request by sidhantgoel**
## Description

Fix for mysqlPlugin tests failing on WSL and Ubuntu.

The reason testcases were failing because queries to create tables was executed in a batch, batch returns result for each query executed. The problem was we were creating Mono from batch.execute and blocking on it. Since Mono is a single value publisher, blocking on it will only block till the result of first query. Later on test cases fail because not all create queries have completed by the time.

Using Flux instead of Mono solves that because it is a multi value publisher and we are calling blockLast on it, which will block until the result of last query, to make sure that all the queries have been executed when the block is complete.

Fixes #13998

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- NA

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by sumitsum** [comment]
Hi @sidhantgoel can you please mention in the description why the tests were failing earlier and why the proposed change would fix it ?

**Comment by sidhantgoel** [comment]
Updated the description

**Review by sumitsum — APPROVED** [review]

**Pull request merged**
