### PR TITLE
fix: Copy and paste

### LINKED ISSUE #10357: [Bug]: RichTextEditor no value when copy patse
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I copy any content to RichTextEditor then I read content of RichTextEditor by RichTextEditor.text but no value

### Steps To Reproduce

1. Copy content
2. Paste content to RichTextEditor
3. Read content of RichTextEditor but no value

### Environment

Release

### Version

Cloud

### LINKED ISSUE #10407: [Bug]: The data is not retained inside the rich text editor widget when the user navigate to datasource
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The data is not retained inside the rich text editor widget when the user navigate to data source with in the same page
[LOOM DEMO](https://www.loom.com/share/2c45821ee9ae46e4a08e643233dde746)

### Steps To Reproduce

1. go to canvas
2. Drag and drop the Rich text editor
3. Add a text inside the editor
4. Now navigate to query pane and come back to the canvas
5. The default text is displayed instead of edited text

### Environment

Production

### Version

Cloud

### LINKED ISSUE #10418: [Bug]: The reset widget functionality doesn't work for rich text editor
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The reset widget functionality doesn't work for rich text editor 
[LOOM DEMO](https://www.loom.com/share/5db64902a69a44e5b136edd243859231)

### Steps To Reproduce

1. Go to the canvas
2. Drag and drop the Rich text editor 
3. Add a reset functionality on the button click 
4. click on the button, the RTE widget doesn't reset.

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by Tooluloope**
## Description

- Copy and Paste fails to reflect in `{{RichTextEditor.text}}`
- Removing all text fails to reflect in `{{RichTextEditor.text}}`
- Reseting RichTextEditor
- Navigating away from page

Fixes #10357
Fixes #10407
Fixes #10418 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/Rich-text-editor-copy 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 55.01 **(0)** | 36.61 **(0.01)** | 34.82 **(0)** | 55.5 **(0.01)**
 :green_circle: | app/client/src/widgets/RichTextEditorWidget/widget/index.tsx | 72.22 **(7.22)** | 18.18 **(2.8)** | 58.33 **(0)** | 73.53 **(7.74)**</details>

### CODE REVIEW

**Review by jsartisan — APPROVED** [review]
LGTM!

**Review by jsartisan — APPROVED** [review]

**Comment by YogeshJayaseelan** [comment]
@Tooluloope Tested this issue and now the text entered remains in the RTE upon switching between datasource to canvas and API queries to canvas

**Comment by YogeshJayaseelan** [comment]
@Tooluloope Tested the fix for issue #10418 reset functionality works fine now

**Comment by YogeshJayaseelan** [comment]
@Tooluloope Verified the fix for issue #10357 - there are two issues mentioned

Issue 1 - Still not fixed - Copy pasting content inside RTE and clicking on confirm stills show no value in the alert - Refer the video attached below

Issue 2 - Fixed - Typing text inside RTE and clicking on confirm shows the message in the alert and removing the text typed and clicking on confirm shows empt alert 

Question - With respect to the issue2 should we still show empty alert when there is not text in the RTE 

https://www.loom.com/share/4bc76eef09594aa5b7e44eb175426359

**Comment by Tooluloope** [comment]
@YogeshJayaseelan All fixed now.
WRTto issue2 as long as the text is empty the alert should be empty

**Comment by YogeshJayaseelan** [comment]
> @YogeshJayaseelan All fixed now. WRTto issue2 as long as the text is empty the alert should be empty

@Tooluloope Verified the fix the copy scenario is working fine now..

**Pull request merged**
