### PR TITLE
feat: support iframe.srcdoc in iframe widget

### LINKED ISSUE #7118: [Feature] support iframe.srcdoc in iframe widget
## Summary

iframe's srcdoc property will allow users to set HTML code as source instead of source URL. This will make it easier to render template based iframes.

User on discord:
Can an iframe display raw HTML code, instead of binding it to a URL? I'm trying to use Mermaid JS by running the code within the page.

Once the custom JS library feature is released, I'll probably use that method instead. Just wondering if this is even possible to build the HTML on the client side like this.
image

### PR DESCRIPTION
**Pull request by wmdev0808**
## Description
iframe's srcdoc property will allow users to set HTML code as source instead of source URL. This will make it easier to render template based iframes.

Fixes #7118 

## Type of change

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

## How Has This Been Tested?

- Test A
- Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: feat/iframe-add-srcdoc 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 55.13 **(0)** | 36.63 **(-0.01)** | 34.56 **(-0.01)** | 55.66 **(0)**
 :green_circle: | app/client/src/selectors/commentsSelectors.ts | 85.25 **(1.64)** | 64.71 **(2.95)** | 73.33 **(0)** | 90.59 **(2.35)**
 :green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.94 **(0.23)** | 41.67 **(0.84)** | 36.21 **(0)** | 56.99 **(0.25)**
 :red_circle: | app/client/src/widgets/IframeWidget/component/index.tsx | 25 **(-6.25)** | 11.43 **(-4.57)** | 0 **(0)** | 26.32 **(-7.01)**
 :red_circle: | app/client/src/widgets/IframeWidget/widget/index.tsx | 43.24 **(-5.24)** | 0 **(0)** | 50 **(-7.14)** | 42.86 **(-5.53)**</details>

### CODE REVIEW

**Review by jsartisan — DISMISSED** [review]
LGTM!

**Review by jsartisan — DISMISSED** [review]

**Comment by vivekverma2312** [comment]
@wmdev0808 
1. After entering HTML code in srcDoc if we delete source url then the widget displays `valid source url is required`
https://www.loom.com/share/a7f2f70f1b5c4250aba0fd0da8496540

**Review by jsartisan — APPROVED** [review]

**Comment by vivekverma2312** [comment]
@wmdev0808 Deploy preview is tested and working fine.

**Pull request merged**
