### PR TITLE
test: Commands file organised

### PR DESCRIPTION
**Pull request by NandanAnantharamu**
## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>
No changes to code coverage between the base branch and the head branch</details>

### CODE REVIEW

**Review by yatinappsmith — COMMENTED** [review]
Please add note in command.js which will prevent users from adding new functions

**Comment by NandanAnantharamu** [comment]
> Please add note in command.js which will prevent users from adding new functions

Sure , i will publish the same in group as well.

**Review by yatinappsmith — APPROVED** [review]

**Pull request merged**
