### PR TITLE
fix: hidden page was not being checked for route change

### LINKED ISSUE #35557: [Bug]: `navigateTo` hidden pages is not working properly and breaking apps in deployed mode
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

NavigateTo function to go to hidden page is breaking. Users see blank page, if they refresh they can see the actual page but, this results in loss of the query params, which is not ideal. This is breaking the deployed apps in user's prod.

### Steps To Reproduce

[NavigateTo (1).json](https://github.com/user-attachments/files/16551065/NavigateTo.1.json)

1. Create 2 pages
2. Hide one
3. Try to navigate to from page 1 to hidden page.

I've uploaded a sample app.

### Public Sample App

_No response_

### Environment

Production

### Severity

Critical (Broken Production apps)

### Issue video log

_No response_

### Version

Latest

### PR DESCRIPTION
**Pull request by AmanAgarwal041**
## Description
There was a selector which was returning the pages array without hidden pages, that array was being used to update the app viewer component to render the page, since the hidden page object was not present in the array, hence the UI was not updating for the hidden page.

Fixes #35557  
_or_  
Fixes `Issue URL`
> [!WARNING]  
> _If no issue exists, please create an issue first, and check with the maintainers if the issue is valid._

## Automation

/ok-to-test tags="@tag.All"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/10312684750>
> Commit: e8064dc03d62ce87399bf8ac4f93aca5ff04c556
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=10312684750&attempt=1" target="_blank">Cypress dashboard</a>.
> Tags: `@tag.All`
> Spec:
> <hr>Fri, 09 Aug 2024 03:28:11 UTC

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [ ] No

## Summary by CodeRabbit

- **New Features**
	- Enhanced page list retrieval now includes hidden pages in the AppViewer component.
	- Introduced a new selector for improved filtering of pages based on their visibility status.
	- Updated the source of page list data to improve navigation and display functionality.

These changes aim to provide users with a more comprehensive view of available content, improving overall user experience.

### CODE REVIEW

**Review by nidhi-nair — APPROVED** [review]

**Comment by btsgh** [comment]
@AmanAgarwal041  - checking back here, is there automation test added for this bug fix so that we don't regress on this in the future?

**Comment by AmanAgarwal041** [comment]
@btsgh There is no such automation I think. @nidhi-nair Can you ask the person who was working on this piece to add an automation test for the above scenario ?

**Comment by btsgh** [comment]
Sorry @AmanAgarwal041  - Probably @rishabhrathod01  is the right person to be adding an automation test for this case?

**Comment by AmanAgarwal041** [comment]
@btsgh I think this comes under IDE pod. Maybe anyone from that pod can take that over, if they are occupied we can also pick that up.

**Pull request merged**
