### PR TITLE
chore: Make delete page services transactional

### LINKED ISSUE #23808: Make create page and delete page operations transactional
When we create page or delete page, we've to make changes to two collections - NewPage and Application. If one of them fails, it'll put us in a bad state. This PR fixes this issue by making these services transactional.

### PR DESCRIPTION
**Pull request by nayan-rafiq**
## Description
When we create page or delete page, we've to make changes to two collections - NewPage and Application. If one of them fails, it'll put us in a bad state. This PR fixes this issue by making these services transactional.

#### PR fixes following issue(s)
Fixes #23808 

#### Type of change
- Chore (housekeeping or task changes that don't impact user perception)

- [x] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by NilanshBansal — APPROVED** [review]

**Review by AnaghHegde — COMMENTED** [review]
@nayan-rafiq Can we add tests to verify the error state?

**Review by AnaghHegde — APPROVED** [review]

**Pull request merged**
