### PR TITLE
fix: Encode query params in URLs

### LINKED ISSUE #16918: [Bug]-[1150]: navigateTo() cannot pass & in url queryparams between two pages
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I want to pass the value `A&B Ltd` from Page1 to Page2, so that I can display the value on Page2. 
Please see [this](https://app.appsmith.com/app/between-pages/page1-6329ee267f7b8d288db3707d/edit) app (shared with support email)

### Steps To Reproduce

video demo of the issue

https://user-images.githubusercontent.com/94514895/191317011-85ec2eba-3ae5-4017-8773-43eed7a0202a.mov

### Public Sample App

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by rimildeyjsr**
## Description

URLs created from `navigateTo()` having query params that were non-string values or special characters were not being displayed in the URL. To fix this we encoded these values.

Fixes #16918 #12177 

## Media
https://www.loom.com/share/b9a9705770f04172ba1580d4a5b48739

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual
- Jest

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by arunvjn — APPROVED** [review]
Changes look good. Can you please test your changes once with a git branch that has a "/" in it ?

**Comment by rimildeyjsr** [comment]
https://github.com/appsmithorg/appsmith/actions/runs/4806704363

**Comment by shwetha-ramesh** [comment]
Working as expected. Moving to Done.

**Pull request merged**
