### PR TITLE
fix: Add a toolbar option for the line height in Rich Text Editor

### LINKED ISSUE #17710: [Feature]: Rich Text Editor Widget: Reduce space between two lines
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Currently the space between two lines in the Rich Text Editor seems a little more than required and looks ugly. Pasting the difference between `Rich Text Editor` and `Google Sheet`: 
Screenshot 2022-10-19 at 1 53 14 PM

Screenshot 2022-10-19 at 1 51 52 PM

### Why should this be worked on?

Improve Rich Text Editor asthetics.

### PR DESCRIPTION
**Pull request by sanjus-robotic-studio**
## Description
Added the toolbar for line height in rich text editor

Fixes #17710

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

locally

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by somangshu — APPROVED** [review]
LGTM

**Comment by Rhitottam** [comment]
@sanjus-robotic-studio testing a perf-infra feature. Can ignore the results.

**Review by Tooluloope — APPROVED** [review]

**Comment by sanjus-robotic-studio** [comment]
@somangshu @mohanarpit can you merge this PR

**Pull request merged**
