### PR TITLE
ISSUE-4023 : [Bug] Incorrect placeholder in the datepicker widget

### LINKED ISSUE #4023: [Bug] Incorrect placeholder in the datepicker widget
## Description

The placeholder shows `DD/MM/YY HH:mm` which is incorrect and cannot be parsed internally to generate a correct ISO string. 
It should show `YYYY-MM-DD HH:mm` or `ISO 8601` which can be parsed correctly.

We also need to update the documentation to advise users on how this works.

### Important Details
Release 1.4.9

### PR DESCRIPTION
**Pull request by wmdev0808**
## Description
- Changes the dateFormat prop value from `DD-MM-YYYY` into `YYYY-MM-DD HH:mm`
- Fixes #4023 

## Type of change
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by mohanarpit** [comment]
@wmdev0808 Please follow the format specified in the pull request template to ensure that all PR descriptions are consistent. It also ensures that you have a handy checklist to show the reviewer the tests that you've written, changes made etc.

**Comment by wmdev0808** [comment]
> @wmdev0808 Please follow the format specified in the pull request template to ensure that all PR descriptions are consistent. It also ensures that you have a handy checklist to show the reviewer the tests that you've written, changes made etc.

Hi, I've just made changes on PR description

**Comment by somangshu** [comment]
Updated documentation with format required for datepicker default data.

**Review by riodeuno — DISMISSED** [review]

**Comment by somangshu** [comment]
closing this in the favour of #4128

**Pull request closed without merging**
