### PR TITLE
feat: camera widget

### LINKED ISSUE #7033: [Feature] Camera widget
## Summary

As a dev, I should be able to provide the end user an option to take a picture or record videos through there system camera using browser permissions

## Motivation

I want to be able to use the system camera and process the data further in an API/Query

## Requirements

| Title | Desc | Default | Comment |
| ---- | ----- | ----- | ----- |
| mode | Camera \| Video | Camera | Mode will let the user choose if picture is required or video recording |
| capture photo / video | Option available on the widget in the camera mode. On click we should provide the base64 output | - | - |
| base64 | internal property to fetch the image captured | - | Need to check what format can the video be exported in |
| custom height / width | custom resolution of the exported image is allowed | fallback to package default | - |
| capturing side | widget should have an option to list all devices and let the user choose one of them | first available | - |
| mirrored | show camera preview and get the screenshot mirrored | boolean:false | - |
| permission | request for the necessary permission through the browser. If the user has denied the permission show the message clearly | requesting permission | - |

> Recommended [package](https://www.npmjs.com/package/react-webcam) to be used

## Developer Design Handoff:
https://www.figma.com/file/9E6h3DaPTEZX1uhMye89bi/Camera-Widget?node-id=2%3A263

### PR DESCRIPTION
**Pull request by wmdev0808**
## Description
This widget provides the end user an option to take picture or record videos through there system camera using browser permissions

Fixes #7033 

## Type of change

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

## How Has This Been Tested?

- Test A
- Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: feat/7033-camera-widget 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 54.99 **(-0.3)** | 36.98 **(-0.15)** | 34.17 **(-0.16)** | 55.52 **(-0.28)**
 :red_circle: | app/client/src/icons/WidgetIcons.tsx | 62.03 **(-0.31)** | 100 **(0)** | 18.92 **(-0.52)** | 62.03 **(-0.31)**
 :red_circle: | app/client/src/utils/AppsmithUtils.tsx | 53.97 **(-3.24)** | 30.36 **(-1.12)** | 35.42 **(-0.75)** | 49.27 **(-3.09)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.71 **(-0.23)** | 40.83 **(-0.84)** | 36.21 **(0)** | 56.74 **(-0.25)**
 :sparkles: :new: | **app/client/src/widgets/CameraWidget/constants.ts** | **100** | **100** | **100** | **100**
 :sparkles: :new: | **app/client/src/widgets/CameraWidget/index.ts** | **100** | **100** | **100** | **100**
 :sparkles: :new: | **app/client/src/widgets/CameraWidget/component/index.tsx** | **10.56** | **14.72** | **0** | **12.45**
 :sparkles: :new: | **app/client/src/widgets/CameraWidget/widget/index.tsx** | **32** | **0** | **42.86** | **31.51**</details>

### CODE REVIEW

**Comment by wmdev0808** [comment]
@jsartisan , For smooth responsiveness, I need your help

**Comment by wmdev0808** [comment]
> @wmdev0808 what is the update here?



> @wmdev0808 what is the update here?

I talked about this, and @jsartisan said he agreed with my implementation

**Review by jsartisan — DISMISSED** [review]

**Comment by somangshu** [comment]
@jsartisan if required please move this to the QA pipeline

**Comment by shwetha-ramesh** [comment]
@wmdev0808 retested this PR based on @prapullac comments. Here are the below findings for the same and some new issues found.

#8785: Fixed

#8788: Still exists. 
https://loom.com/share/7997622dd9cf4bcbbd3aff8250a5854d

#8789: Working fine

#8791: Fixed

#8792 : Still exists. In figma document the widget appears grey when permission is denied, where as in DP the widget appears black
In figma doc
image
In DP
image

#8793 : Fixed

#8795: Still exists

#8798 : Still exists.

**_NEW ISSUES_**

1. As per figma document Disabled state must appear grey, in DP it appears black
In figma doc
image
In DP
image

2. As per figma doc the tooltip has a black background and then a white text, in DP it has white background and black text.
In figma doc
image
In DP
image

3. No setting icon found when user clicks on 'refresh' button as per figma doc
image

4. Each time user changes from Desktop mode to different mode the transition does not appear smooth.
https://loom.com/share/0690b5f2c4d14e6bb0958820f3366a81

**Moving to In Progress.**

**Comment by shwetha-ramesh** [comment]
@wmdev0808 new issues found

5. As per figma in Camera mode Mic icon is not present where as in DP there is Mic option
image

6. As per figma doc Mirrored is true by default, where as in DP when widget is placed by default its false
image

7. When the camera is placed on the canvas, the widget appears black for the first few seconds and then the image is loaded.
https://loom.com/share/a956e215678843a9bdb89708e877385d

8. In camera mode, when user clicks on 'take photo' button, the captured image is not seen.
https://loom.com/share/7731ea642fba408383068e2ce41d5ed6

9. There is no access to check where the saved image and recordings are present.

10. As per figma the submenu under 'Actions' must be **OnImageCapture** and not _onMediaCapture_
image

11. As per figma in Video mode the submenu under 'Actions' must be **'OnRecordingStart'** & **'OnRecordingStop'**, where as in DP for video mode the submenu still remains 'onMediaCapture'.
https://loom.com/share/b2b11ae69de34bd4bfa3bd204d4ea62c

12. Also when the widget is resized occasionally 'Video source not found' is shown
https://loom.com/share/077a4ef46d4942528f967923e39292f3

13. As per figma 'Mirrored' option is not present for Video mode
image

**Comment by wmdev0808** [comment]
> 



> 2\. As per figma doc the tooltip has a black background and then a white text, in DP it has white background and black text.
>     In figma doc

@shwetha-ramesh , I cannot reproduce this issue

**Comment by wmdev0808** [comment]
> 3\. No setting icon found when user clicks on 'refresh' button as per figma doc

@shwetha-ramesh , The settings icon in Figma does not make sense, you can ignore it

**Comment by wmdev0808** [comment]
> 13\. As per figma 'Mirrored' option is not present for Video mode

@shwetha-ramesh , this does not make sense, you can ignore it

**Review by jsartisan — APPROVED** [review]

**Comment by shwetha-ramesh** [comment]
> > 3. No setting icon found when user clicks on 'refresh' button as per figma doc
> 
> @shwetha-ramesh , The settings icon in Figma does not make sense, you can ignore it

@wmdev0808 need more insight on this. @sbalaji1192 @momcilo-appsmith.

**Comment by shwetha-ramesh** [comment]
#8788: Fixed
#8792: Fixed
#8795: Fixed
#8798:
1. Fixed
2. **Still exists.** Hover over camera icon and tooltips that display 'Take photo' and others must follow figma doc design which has black background and white text. In DP its otherwise (Refer video)
https://loom.com/share/6cf6cd4c3cb24c4d96087a318a3138d1
3. Still Exists. Need clarification
4. Fixed
5. Fixed
6. Fixed
7. **Still exists**
8. Fixed
9. **Still exists.**
10. Fixed
11. Fixed
12. Fixed. 
13. **Still exists.**

_New Issues found._

14. Camera icon not present for Camera widget in Entity explorer
image

15. Disable on/off make the screen appear black for a few seconds. Similar video recorder button on/off shows the same behavior
https://www.loom.com/share/ce641e4a184a4e52ba96231eeffc78f1

16. . JS option for OnImageCapture shows empty. Similarly for OnRecordingStart & OnRecordingStop
image
image

17. Action must be  **OnRecordingStop** and not onRecordingStop. 
image

18. Recorded video is lost when is widget is dragged to a different place. Similar for image.
https://www.loom.com/share/522f2896db514f5ab832d0572982c024

19. Video recording stops in between when mic is turned off
https://loom.com/share/0c5c3852d6c648e38d2ae35856a406ba

20. 'Enter fullscreen' cuts the video and image; the full image/video recorded in default size is not seen when user enters full screen
https://loom.com/share/e31f3bc628a94da3aba0167a71774239

**Moving to Inprogress**

**Review by jsartisan — DISMISSED** [review]

**Comment by shwetha-ramesh** [comment]
> > 13. As per figma 'Mirrored' option is not present for Video mode
> 
> @shwetha-ramesh , this does not make sense, you can ignore it

@somangshu 

> > 3. No setting icon found when user clicks on 'refresh' button as per figma doc
> 
> @shwetha-ramesh , The settings icon in Figma does not make sense, you can ignore it

image


> > > 3. No setting icon found when user clicks on 'refresh' button as per figma doc
> > 
> > 
> > @shwetha-ramesh , The settings icon in Figma does not make sense, you can ignore it
> 
> @wmdev0808 need more insight on this. @sbalaji1192 @momcilo-appsmith.

@somangshu any update on this ? On figma it shows _setting_ icon but there is no description on what that icon must perform.
image

**Comment by somangshu** [comment]
@shwetha-ramesh the setting icon does not resolve to any functionality and henceforth can be safety ignored. Let me know if you need a discussion around this

**Comment by shwetha-ramesh** [comment]
2. Fixed
3. Need not be implemented.
7. Fixed 
9. Fixed
13. Fixed
14. Fixed
15. Fixed
16. Fixed
17. Fixed
18. Fixed
19. Fixed
20. Fixed

**_New Issues_**

21. There is no Mirrored option for Video mode. However after the video records the recorded video gets mirrored automatically.
https://loom.com/share/7994e3a2fd054e41bb9a8065cfbe5d02

**Moving to Inprogress**

**Review by jsartisan — APPROVED** [review]

**Comment by shwetha-ramesh** [comment]
@wmdev0808 all issues are resolved. DP looks good. Moving to Done.

**Review by somangshu — APPROVED** [review]

**Review by somangshu — APPROVED** [review]

**Pull request merged**
