### PR TITLE
fix: Refactor GitSyncModalV2 component

### LINKED ISSUE #24988: [Bug]: Commit Message Disappears when switching tabs
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the user is typing a commit message and switches tab in the modal, the draft commit message disappears when the user returns back to the commit tab.

Expected behavior : The commit message should still remain because the user is still inside the modal and the modal hasn't been dismissed.

### Steps To Reproduce

1. Write a commit message and but don't deploy it
2. Switch to Merge tab.
3. Come back to Deploy tab.
4. Notice that the commit message is gone.

Expected behavior : The commit message should still be present.

### Public Sample App

_No response_

### Environment

Production

### Issue video log

https://www.loom.com/share/43ee69d458f4444b98d828291adaddf3

### Version

Cloud

### PR DESCRIPTION
**Pull request by Saadat-B**
## Description
This PR updates the GitSyncModalV2 component to conditionally display the Deploy and Merge components based on the currently active tab.

Changes:

The Deploy component is now only visible when the DEPLOY tab is active.
The Merge component is now only visible when the MERGE tab is active.
These changes improve the user experience by ensuring that messages within the 'Deploy' component persist and remain visible to the user when switching between tabs. This resolves the issue of disappearing messages upon tab switch, providing a more consistent and reliable user interface.

Videos for reference - 

Before - https://www.loom.com/share/43ee69d458f4444b98d828291adaddf3

After - https://www.loom.com/share/d417d058d3fa49429764c0fb55d25dc8?sid=3f0c39d5-6022-4ba8-ab87-28967fb0aec1

Fixes #24988  

## Automation

/ok-to-test tags="@tag.Git"

### :mag: Cypress test results

> [!CAUTION]  
> If you modify the content in this section, you are likely to disrupt the CI result for your PR.

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by brayn003** [comment]
Hi @Saadat-B thanks for raising this PR. Could you also add a couple of unit test cases for the solution you have raised?

**Comment by Saadat-B** [comment]
Hi @brayn003 I've added the unit test cases as requested

**Comment by brayn003** [comment]
I will need to create a separate PR to run tests

**Comment by brayn003** [comment]
Using PR #33473 for running tests

**Comment by brayn003** [comment]
Hi @Saadat-B I have raised a PR to run the complete test suite for these changes. You can find the PR reference in the thread.
A couple of Cypress tests are failing for the changes. Would appreciate if we could resolve them before merging

**Comment by Saadat-B** [comment]
Cool will have a look at them thanks @brayn003

**Pull request closed without merging**
