### PR TITLE
Adds support for base64 image strings to image cells

### PR DESCRIPTION
**Pull request by osis**
## Description

Work in progress for a fix for #2753

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- This change requires a documentation update?

## How Has This Been Tested?

Submitting as a draft until testing is figured out in my new WSL2 environment.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by riodeuno** [comment]
@osis Can I ask you to pull the latest release and push again to this branch. One of the tests in the datepicker has failed. This will work when the latest release is pulled.

**Review by riodeuno — DISMISSED** [review]
Looks good to me.

**Comment by osis** [comment]
Awesome! will do!

**Review by riodeuno — DISMISSED** [review]

**Comment by osis** [comment]
Looks like the way DSL for widgets has changed a bit. Will make this work through UI interactions.

**Comment by osis** [comment]
@riodeuno this should be in an alright state. Mind taking a look?

**Review by riodeuno — APPROVED** [review]

**Comment by riodeuno** [comment]
@all-contributers please add @osis for code

**Comment by riodeuno** [comment]
@all-contributors please add @osis for code

**Pull request merged**
