### PR TITLE
fix: reset page number server side pagination is just enabled in List widget

### LINKED ISSUE #20635: [Bug]: The page number doesn't reset when we switch from client side to server side pagination
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The page number doesn't reset when we switch from client side to server side pagination 

### Steps To Reproduce

https://www.loom.com/share/bae46c2c56a74edc8d3ddb4688e0ffde 

### Public Sample App

_No response_

### Issue video log

_No response_

### Version

Release/Cloud

### PR DESCRIPTION
**Pull request by Tooluloope**
## Description

Reset Page Number when server-side pagination is just turned on.

Fixes #20635

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Cypress

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [x] Test plan has been approved by relevant developers
- [x] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Comment by chandannkumar** [comment]
@Tooluloope @ashit-rath 
Shouldn't we also reset the Page to 1 when switching from Server side pagination to client side?

**Comment by Tooluloope** [comment]
@chandannkumar , No, we don't reset the page number since that page exists on the client side. And if the page doesn't exist, we reset it to the maximum page number on the client side pagination.

**Comment by chandannkumar** [comment]
Tested this PR and LGTM

**Comment by chandannkumar** [comment]
Tested this PR and LGTM

**Pull request merged**
