### PR TITLE
fix: 8537 submenu color when disabled

### LINKED ISSUE #8537: [Bug]: The Sub Menu options are transparent when disabled in the table widget
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It is observed that in the Menu button column type when the sub menu's are disabled the disabled sub menu are transparent 

[LOOM DEMO](https://www.loom.com/share/60ef203e092c470684eecd6e582eb8df)

### Steps To Reproduce

```markdown
1.Launch Appmsith app in the release/Prod Environment 
2.Drag and drop table widget 
3.Change any of the column type to Menu button 
4.Add sub menus to the menu button column
5.Choose colours to the Sub Menus
6.Disable any of the sub menu 
7.Click on the Menu column button and observe
```

### Environment

Release

### Version

Cloud

### PR DESCRIPTION
**Pull request by vibhandikyash**
## Description

> Updated Submenu color when disbaled. 

Fixes #8537 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Tested locally.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/8537-menubutton-submenu-disabled-color 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 54.59 **(0.01)** | 36.44 **(0)** | 33.22 **(0)** | 55.11 **(0)**
 :green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.26 **(0.22)** | 41.25 **(0.83)** | 34.48 **(0)** | 56.22 **(0.26)**
 :green_circle: | app/client/src/widgets/TableWidget/component/components/menuButtonTableComponent.tsx | 31.25 **(1.46)** | 14.71 **(0)** | 0 **(0)** | 36.59 **(1.59)**</details>

### CODE REVIEW

**Review by Tooluloope — COMMENTED** [review]
@vibhandikyash LGTM
Could you help add a cypress test for this. `Table_Widget_Add_button_spec.js`

**Comment by vibhandikyash** [comment]
https://github.com/appsmithorg/appsmith/actions/runs/1442921765

**Comment by vibhandikyash** [comment]
https://github.com/appsmithorg/appsmith/actions/runs/1448335767

**Review by Tooluloope — APPROVED** [review]

**Pull request merged**
