### PR TITLE
fix: updated internal selectedDate condition

### LINKED ISSUE #11409: [Bug]: Need to refresh the screen to populate date in date picker after I use moment object in Default date
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Date do not populate on date picker widget after using {{moment()}} in edit mode.

### Steps To Reproduce

1. Drag and drop a date picker widget
2. Use {{moment()}} in default date property
3. Observe the date do not populate on the widget
4. Refresh the screen and see that date gets populated

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by techbhavin**
## Description

>  In DatePicker Widget when DefaultDate value is moment Object then a date is not visible without refresh, To fix this issue update internal selected date condition

Fixes #11409 

## Type of change

- Bugfix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/datepicker-state 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 55.68 **(-0.01)** | 37.08 **(0)** | 35.25 **(0)** | 55.94 **(-0.01)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.71 **(-0.23)** | 40.83 **(-0.84)** | 36.21 **(0)** | 56.74 **(-0.25)**
 :red_circle: | app/client/src/widgets/DatePickerWidget2/component/index.tsx | 30 **(0)** | 2.99 **(-0.09)** | 6.25 **(0)** | 28.99 **(0)**</details>

### CODE REVIEW

**Review by Tooluloope — CHANGES_REQUESTED** [review]
LGTM

Could you help with a Cypress test

**Review by Tooluloope — APPROVED** [review]

**Comment by chandannkumar** [comment]
Tested the PR and it is working as expected

**Pull request merged**
