### PR TITLE
Fix: Auto scroll to specific section when reloading with same url fixed.

### PR DESCRIPTION
**Pull request by devrk96**

### CODE REVIEW

**Comment by hetunandu** [comment]
@appsmithorg/design Need a selected state on list of orgs on the left

**Review by rishabhsaxena — COMMENTED** [review]
@devrk96 
I suppose there are a couple of optional changes:
- listen to location changes (https://reactrouter.com/web/api/Hooks/uselocation) and keep one variable for `selected` state
- we could use id=`#orgName` so that the browser would automatically (for example http://jsfiddle.net/U6aKT/)

**Comment by devrk96** [comment]
@rishabhsaxena Please review the PR. For the scroll-spy feature, I have created another [issue](https://github.com/appsmithorg/appsmith/issues/2294) as it is not a blocker right now. I have talked to Arpit about it.

**Comment by rishabhsaxena** [comment]
@devrk96
cool, when we do it finally, can do that for internal links with css as well `html {scroll-behavior: smooth;}`
We could also create a clean up issue for using `useLocation` here instead of using two variables for tracking selected organisation

**Review by rishabhsaxena — APPROVED** [review]

**Pull request merged**
