### PR TITLE
chore: add box-shadow to onboarding welcome popup

### LINKED ISSUE #8208: [Enhancement] Add shadow to welcome tour pop-up's in line with Design System changes
## Summary
Design system changes provides a shadow for dropdowns and pop-up. So keeping with this theme, the pop-up's during welcome tour also needs a shadow effect to keep up with current changes

## Additional Context
image

### PR DESCRIPTION
**Pull request by ashish-patwal**
> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Description

> Added box-shadow to onboarding welcome tour pop up . 

Fixes #8208 

> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

> Please delete options that are not relevant.

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
> Added necessary box-shadow property through developer tools to preview and confirm the changes

2021 10 09-11 01 33 screenshot

> To reproduce this simple open developer tools on the welcoming tour pop up window . Select the welcome tour pop element and inspect it's properties in styles tab . Double click the style properties and enter a new value for box-shadow as < box-shadow: 0px 12px 28px \#df613c > . You can now see a faint box-shadow property applied to the welcome tour pop-up .

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by ashish-patwal** [comment]
> Remove the space after 'feat' in PR title, this will solve the semantic test. `feat: A PR title`

Thanks @AR10X . It did the trick .

**Comment by akash-codemonk** [comment]
@ramsaptami @ashish-patwal Can we keep the border? Shadow looks great.

**Comment by mohanarpit** [comment]
Closing this PR as it is no longer relevant. Apologies for not prioritizing this PR earlier. 🙏🏽

**Pull request closed without merging**
