### PR TITLE
fix: Updates + icon to take user to select pages page instead of direclty importing a template

### PR DESCRIPTION
**Pull request by rahulbarwal**
## Description

When in add pages from template flow, if a user clicks on `+` icon in the templates list.
Current: the template gets added automatically
New: now user will be taken to page selection view(similar to when users click on template image)

- Adds test case for + button now redirects to select pages
- Adds test case for + icon in the similar templates

Fixes # (issue)
[21200](https://github.com/appsmithorg/appsmith/issues/21200)

Media

## Type of change

- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested?

- Cypress

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [X] Test plan has been approved by relevant developers
- [X] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by akash-codemonk — APPROVED** [review]

**Comment by rahulbarwal** [comment]
Hey @ramsaptami , Can you please do QA for this? 
this PR fixes this issue: https://github.com/appsmithorg/appsmith/issues/21200 

I've added some cypress tests and all of them are passing.

**Comment by Richarex** [comment]
This is working as expected, tested **Use Template** complete flow on the DP url.

**Review by akash-codemonk — APPROVED** [review]

**Pull request merged**
