### PR TITLE
feat: Admin settings page to tinker with env variables

### LINKED ISSUE #9686: [Task]: Make Admin settings page public
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- Remove ADMIN_SETTINGS feature flag

### PR DESCRIPTION
**Pull request by sbalaji1192**
## Description

Moving Admin settings page out of feature flag.

Fixes #9686

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Manual

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: feat/admin-settings-inauguration 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 55.25 **(0.12)** | 37.13 **(0.08)** | 34.15 **(0.13)** | 55.77 **(0.12)**
 :green_circle: | app/client/src/components/ads/Icon.tsx | 52.9 **(0.51)** | 36.2 **(0.62)** | 100 **(0)** | 52.78 **(0.51)**
 :sparkles: :new: | **app/client/src/pages/Settings/SettingsConfig.ts** | **68.37** | **25** | **21.05** | **69.47**
 :sparkles: :new: | **app/client/src/pages/Settings/Main/Button.tsx** | **100** | **87.5** | **100** | **100**
 :sparkles: :new: | **app/client/src/pages/Settings/Main/Common.tsx** | **100** | **88.89** | **100** | **100**
 :sparkles: :new: | **app/client/src/pages/Settings/Main/Link.tsx** | **100** | **80** | **100** | **100**
 :sparkles: :new: | **app/client/src/pages/Settings/Main/Text.tsx** | **100** | **100** | **100** | **100**
 :green_circle: | app/client/src/pages/common/ProfileDropdown.tsx | 68.75 **(1.1)** | 28.57 **(1.3)** | 0 **(0)** | 68.75 **(1.1)**
 :sparkles: :new: | **app/client/src/selectors/settingsSelectors.tsx** | **72.22** | **100** | **16.67** | **54.55**</details>

### CODE REVIEW

**Review by mohanarpit — APPROVED** [review]

**Review by pranavkanade — COMMENTED** [review]
FE changes LGTM

**Comment by pranavkanade** [comment]
Approving for tests

**Review by pranavkanade — DISMISSED** [review]

**Review by pranavkanade — DISMISSED** [review]

**Review by pranavkanade — APPROVED** [review]

**Pull request merged**
