### PR TITLE
fix: rename file 

### LINKED ISSUE #16670: [Task]: Rename TriggerUtils.java
### Is there an existing issue for this?

- [x] I have searched the existing issues

### SubTasks

Rename `TriggerUtils.java` to `RestApiTriggerUtils.java`
Ref: https://github.com/appsmithorg/appsmith/pull/16554#discussion_r967011552

### PR DESCRIPTION
**Pull request by bhuvanaindukuri**
## Description
- Rename file.

Fixes #16670 

## Type of change
- Technical debt fix

## How Has This Been Tested?
- Ensured that the build is successful after the change
- Ensured that the tests are successful after the change

## Checklist:
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] My changes generate no new warnings
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by sumitsum — APPROVED** [review]

**Comment by sumitsum** [comment]
Skipping manual test since the change is only a function rename.

**Comment by nidhi-nair** [comment]
@sumitsum @bhuvanaindukuri Can we avoid the term "Trigger" in this context? We're using triggers for the dynamic trigger functionality that got introduced with UQI and I'd like to avoid confusion in the future.

**Comment by sumitsum** [comment]
> @sumitsum @bhuvanaindukuri Can we avoid the term "Trigger" in this context? We're using triggers for the dynamic trigger functionality that got introduced with UQI and I'd like to avoid confusion in the future.

@bhuvanaindukuri can you please replace the word `trigger` with `activate` everywhere in the change set ? e.g. now the function would be called `RestApiActivateUtils`

**Comment by sumitsum** [comment]
Hi @bhuvanaindukuri please let us know if you are still actively working on this PR, otherwise we may have to re-assign the issue.

**Comment by bhuvanaindukuri** [comment]
Closing the pull request since the requested changes seems to be implemented by a different pull request.

**Pull request closed without merging**
