### PR TITLE
fix: toast width to fit-content

### LINKED ISSUE #8102: [Bug] The undo/redo alert should have width based on the content
Currently, the width of alert that we show in undo/redo feature has a fixed width which looks odd.
screenshot_2021-10-01_at_11 13 03_pm

Ideally, the width of the alert should be same as the width of the content instead of a fixed width like the image below:
screen_shot_2021-10-02_at_12 40 50_am

### PR DESCRIPTION
**Pull request by aswathkk**
## Description

Fixes #8102 

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

Manual

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>

    // Code coverage diff between base branch:release and head branch: fix/toast-width 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | app/client/src/components/ads/Toast.tsx | 77.36 **(-1.49)** | 62.5 **(0)** | 80 **(-4.21)** | 77.36 **(-1.49)**</details>

### CODE REVIEW

**Review by somangshu — APPROVED** [review]
LGTM, 
We should probably add a margin left for the command shown `cmd + z`. 

Also fit-context gives a wrap like behaviour, In that case the command shown should not move to the next line

**Comment by aswathkk** [comment]
@somangshu Do you think we should set a minimum width also?
When the content is really small, the toast itself is not being that visible

https://user-images.githubusercontent.com/10436935/139826568-078c8979-d20e-464f-9988-4498e5f07ea1.mov

.

**Comment by somangshu** [comment]
Looks alright to me @aswathkk we could leave it as it is.

I meant that _in no way_ the command should go to the next line below message. I just want some more space between message and the command

**Comment by aswathkk** [comment]
@somangshu Here's one issue I'm stuck at

Screenshot 2021-11-03 at 12 04 35 PM

Can't find a way to align all toasts to the right so that the shadow will be hidden.

**Comment by somangshu** [comment]
@aswathkk cant seem to reproduce this, How are you seeing the additional white space

**Comment by aswathkk** [comment]
@somangshu Try creating multiple messages of different length

**Comment by somangshu** [comment]
@aswathkk looks like the container is supposed to have a fixed width as per the implementation, However we can check if the toastContainer can be modified to have a transparent background. Might not be suck a clean implementation

**Review by somangshu — CHANGES_REQUESTED** [review]
@aswathkk the change is not appropriate, Because of this different sized toasts, they keep jumping on enter and exit

**Comment by aswathkk** [comment]
https://github.com/appsmithorg/appsmith/actions/runs/1433644782

**Review by somangshu — APPROVED** [review]
LGTM

**Pull request merged**
