### PR TITLE
[GlobalSearch Results] Update sorting order based on the index of the query

### PR DESCRIPTION
**Pull request by rishabhsaxena**
## Description
Sort the globalsearch results based on the following logic:
- Search Index priority (index of matching query within the entity name)
- Current Page priority (if the entity belongs to the current page)

## Type of change
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested?
- manually

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: update-globalsearch-results-sort 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 53.85 **(-0.01)** | 35.8 **(-0.01)** | 32.49 **(0)** | 54.43 **(-0.01)**
 :green_circle: | app/client/src/components/editorComponents/GlobalSearch/index.tsx | 58.33 **(-0.21)** | 14.86 **(0.48)** | 40.48 **(0.95)** | 58.92 **(-0.22)**
 :red_circle: | app/client/src/components/editorComponents/GlobalSearch/utils.tsx | 65.71 **(-3.04)** | 16.67 **(-3.67)** | 63.64 **(-6.36)** | 63.64 **(-4.36)**</details>

### CODE REVIEW

**Review by akash-codemonk — DISMISSED** [review]

**Review by pranavkanade — APPROVED** [review]
LGTM!

**Review by pranavkanade — APPROVED** [review]
approving for tests

**Pull request merged**
