### PR TITLE
fix: rich text editor is buggy

### LINKED ISSUE #17402: [Bug]: Rich Text Editor is buggy
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

bugs found:
1. text modifiers (bold, italic, underline) remove text color (but background color is fine)
2. no icon for `underline` modifier but keyboard shortcut `Cmd+U` works
3. headings can be inserted in list items
4. text alignment (left, center, right) on list items don't move list marker (bullet, number)
5. text color & background color widgets rendered twice

Screenshot 2022-10-09 at 12 39 00 AM

### Steps To Reproduce

bug 1
- select text
- apply modifier
- change color

bug 2
- select text
- press `Cmd+U` or `Ctrl+U`

bug 3
- select "paragraph" text
- convert to list
- change block style to any heading

bug 4
- change alignment on list item

bug 5
- check last 2 widgets in toolbar

### Public Sample App

_No response_

### Version

cloud

### PR DESCRIPTION
**Pull request by iamrkcheers**
## Description

Fixes
- Text modifiers (bold, italic, underline) remove text color
- No icon for underline modifier
- Text color & background color widgets are rendered twice

Fixes #17402

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual
- Cypress

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by jsartisan — APPROVED** [review]

**Comment by chandannkumar** [comment]
@iamrkcheers 
DP link is broken. Can you please check

**Comment by chandannkumar** [comment]
Tested this PR and LGTM
- Tested for text modifier color removal issue - Fixed
- Tested the added icon of Underline in toolbar
- Regression on RTE

**Pull request merged**
