### PR TITLE
Update FilepickerWidget.tsx

### LINKED ISSUE #949: [Bug] File upload is not putting picker in loading state
## Steps to Reproduce
1. Drag a file picker
2. Create an API
3. Bind the onFileSelected to the API
4. Pick a file
5. The File picker does not go into loading state

### PR DESCRIPTION
**Pull request by ng29**
## Description
Made isLoading as a state variable and defined in the constructor. And it should be false inside handleFileUpload function whereas true inside onFileSelected in order to achieve proper flow and thus not creating a reported bug.

Fixes #949 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
Same steps mentioned in the issue

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by hetunandu** [comment]
This looks good. Can we also add a Cypress test for this functionality to ensure it does not break again?

**Comment by ng29** [comment]
> This looks good. Can we also add a Cypress test for this functionality to ensure it does not break again?

Hey @hetunandu , could you please elaborate as i am not aware of cypress test term

**Comment by hetunandu** [comment]
[Cypress](https://www.cypress.io/how-it-works) is an E2E test suite used to automate ui testing.
We use this to write ui tests to ensure product quality is maintained. File for filepicker test is [here](https://github.com/appsmithorg/appsmith/blob/release/app/client/cypress/integration/Smoke_TestSuite/FormWidgets/FilePicker_spec.js)
You can add an assertion to the test here for loading sign when this button is clicked

**Comment by ng29** [comment]
> [Cypress](https://www.cypress.io/how-it-works) is an E2E test suite used to automate ui testing.
> We use this to write ui tests to ensure product quality is maintained. File for filepicker test is [here](https://github.com/appsmithorg/appsmith/blob/release/app/client/cypress/integration/Smoke_TestSuite/FormWidgets/FilePicker_spec.js)
> You can add an assertion to the test here for loading sign when this button is clicked

Ohh , got it.. .But main concern is i am not much into testing , so is it mandatory or can be catered at your end ? I hope you understand my concern

**Comment by hetunandu** [comment]
> > [Cypress](https://www.cypress.io/how-it-works) is an E2E test suite used to automate ui testing.
> > We use this to write ui tests to ensure product quality is maintained. File for filepicker test is [here](https://github.com/appsmithorg/appsmith/blob/release/app/client/cypress/integration/Smoke_TestSuite/FormWidgets/FilePicker_spec.js)
> > You can add an assertion to the test here for loading sign when this button is clicked
> 
> Ohh , got it.. .But main concern is i am not much into testing , so is it mandatory or can be catered at your end ? I hope you understand my concern

You should give it a try. Never too late to start learning something new 🙂

**Comment by ng29** [comment]
> > > [Cypress](https://www.cypress.io/how-it-works) is an E2E test suite used to automate ui testing.
> > > We use this to write ui tests to ensure product quality is maintained. File for filepicker test is [here](https://github.com/appsmithorg/appsmith/blob/release/app/client/cypress/integration/Smoke_TestSuite/FormWidgets/FilePicker_spec.js)
> > > You can add an assertion to the test here for loading sign when this button is clicked
> > 
> > 
> > Ohh , got it.. .But main concern is i am not much into testing , so is it mandatory or can be catered at your end ? I hope you understand my concern
> 
> You should give it a try. Never too late to start learning something new 🙂

hEY, @hetunandu i tried to understand already cypress test cases for file picker and button widget too but it seems quite unfeasible for me due to bandwidth issues also, but if you can guide to set up on my local(few commands to build and all) then i can test and verify that bug has been fixed. 


Cheers

**Comment by hetunandu** [comment]
Sure @ng29 ! Please join our discord and ping me there and ill be happy to help you setup on local.

**Comment by hetunandu** [comment]
Closing since no activity seen in some while.

**Pull request closed without merging**
