### PR TITLE
feat: Divider Reskinning

### LINKED ISSUE #10976: [Enhancement]: Divider widget reskinning
https://www.notion.so/appsmith/Divider-1acc4d9ec8ed4a1f9b248d1a99448ec1

### PR DESCRIPTION
**Pull request by dhruvikn**
## Description
This PR fixes UI inconsistencies in the divider widget.

Fixes #10976 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manually

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by laveena-en** [comment]
Tested and verified.

**Comment by dhruvikn** [comment]
Thanks @laveena-en! 🙌

**Pull request merged**
