### PR TITLE
chore: migrate AWS SDK for JavaScript v2 APIs to v3

### PR DESCRIPTION
**Pull request by trivikr**
## Description

From AWS SDK for JavaScript v2 [README](https://github.com/aws/aws-sdk-js):
> We are formalizing our plans to make the Maintenance Announcement (Phase 2) for AWS SDK for JavaScript v2 in 2023.

This PR migrates AWS SDK for JavaScript v2 APIs to v3 using [aws-sdk-js-codemod](https://www.npmjs.com/package/aws-sdk-js-codemod).

```console
$ npx aws-sdk-js-codemod@0.26.1 -t v2-to-v3 app/client/cypress/scripts/util.ts
```

#### PR fixes following issue(s)

Required as AWS SDK for JavaScript v2 will be put into maintenance

#### Media

N/A

#### Type of change

- Chore (housekeeping or task changes that don't impact user perception)

## Testing

ToDo

#### How Has This Been Tested?

- [ ] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress

#### Test Plan

ToDo

#### Issues raised during DP testing

ToDo

#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Comment by Aishwarya-U-R** [comment]
@sarojsarab - Can you please review this PR? There is a change regarding how we use the S3 for internal dashboard.

**Review by sarojsarab — APPROVED** [review]
LGTM

**Review by KelvinOm — APPROVED** [review]

**Comment by sarojsarab** [comment]
@Aishwarya-U-R  Seems like the artefacts are not uploaded to S3.

**Comment by sarojsarab** [comment]
> @Aishwarya-U-R Seems like the artefacts are not uploaded to S3, may be due to Cypress browser crash, rerunning the tests to check if that is the only issue.

@Aishwarya-U-R  It seems like the artefacts failed to be uploaded due to a browser crash in Cypress, but now they look fine.

**Comment by trivikr** [comment]
cc @Aishwarya-U-R @sarojsarab

**Pull request merged**
