### PR TITLE
fix: added backdrop for menubutton

### LINKED ISSUE #11176: [Bug]: Menu options scroll beyond table/container/tabs/form widget area when scroll horizontally/Vertically
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[LOOM DEMO](https://www.loom.com/share/0d228678db9646e4b1090d5cdaf84c1f)

### Steps To Reproduce

1. Drag and drop a Table widget
2. Bind with query
3. Add a column with menu widget type
4. Add few options in menu widget 
5. Now click on menu widget and open the option drop-down
6. Scroll the table data horizontally 

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by techbhavin**
## Description

Menu options scroll beyond table/container/tabs/form widget area when scrolling horizontally/Vertically to fix this issue we added `backdropProps`.

 - user can't perform an action when a menu is open
 - on Click on the menu option or outside of options, the menu will close so it will not visible while scrolling.

Fixes #11176

## Type of change

- Bugfix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>

    // Code coverage diff between base branch:release and head branch: fix/table-menubutton-popover 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.71 **(-0.23)** | 40.83 **(-0.84)** | 36.21 **(0)** | 56.74 **(-0.25)**</details>

### CODE REVIEW

**Review by Tooluloope — APPROVED** [review]
The solution LGTM

@dilippitchika I couldn't think up any edge case with this approach.

**Comment by YogeshJayaseelan** [comment]
@techbhavin Tested this PR and it is working as expected

**Pull request merged**
