### PR TITLE
fix: 12456 - oauth redirection issue

### LINKED ISSUE #12456: [Bug]: Gsheet authentication fails in the reconnect datasource modal
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The google auth fails when the user tries to authentication the google sheet as a last datasource

[LOOM DEMO](https://www.loom.com/share/1bc6143a7e4e47aeaeb3f0c801fa94b3)
### Steps To Reproduce

1. Import the application which as multiple data source along with google sheet
2. authenticate all the datasource now at the last authenticate the google sheet 
3. The user is navigated to the application instead of authenticate  page

### Public Sample App

_No response_

### Version

release

### PR DESCRIPTION
**Pull request by haojin111**
## Description

> fixed issue with redirecting urls from oauth

Fixes #12456 

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Please refer linked issue

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/12456-oauth-redirecting-issue 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 56.43 **(0)** | 37.81 **(0.01)** | 36.07 **(0)** | 56.65 **(0)**
 :red_circle: | app/client/src/pages/Editor/DataSourceEditor/DBForm.tsx | 48.53 **(0)** | 13.64 **(-0.31)** | 9.09 **(0)** | 50 **(0)**
 :green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.94 **(0.23)** | 41.67 **(0.84)** | 36.21 **(0)** | 56.99 **(0.25)**</details>

### CODE REVIEW

**Comment by haojin111** [comment]
https://www.loom.com/share/0fd1c1d876174aac8431727f64b5ee01

**Comment by mohanarpit** [comment]
@haojin111 Is there a Cypress test to assert this fix?

**Comment by haojin111** [comment]
not now! we can't process cypress testing with gsheet authorization.

**Review by IAmAnubhavSaini — APPROVED** [review]

**Pull request merged**
