### PR TITLE
fix: Dropdown ui fixes - hover and highlight color, keyboard navigation

### LINKED ISSUE #16388: [Bug]: Google Sheets | Drop-downs close abruptly when a space or wrong/random text is entered
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In the Google sheet API page when we enter a random/wrong text in the dropdown search bar or enter a space, the dropdown closes abruptly.

https://www.loom.com/share/1ced86a1b63c4b049bcbfebf1a13027f 

### Steps To Reproduce

1. Go to any application.
2. Add a GSheet query.
3. In the drop-downs enter any random text or enter a valid text followed by a space.

### Public Sample App

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by albinAppsmith**
## Description

This new version of design system package includes the fix for Dropdown v1 UI inconsistencies fix and search auto close fix.

Fixes #16388, #16756

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Tested locally

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by ankitakinger — DISMISSED** [review]

**Comment by shadabbuchh** [comment]
Noticed a couple of issues in this PR:

1. On the first try if we press space after entering any text in the dropdown, the `space` does not reflect in the search text.
2. If we select any option and then try to enter something in the search text and then press `space`, the dropdown closes.

https://www.loom.com/share/faf074f358e14f2d90b3d7cb1544b294

**Comment by shadabbuchh** [comment]
Below are some issues that are on this PR:

1. For single select dropdown keyboard navigation does not work if not option is selected.
2. For single select dropdown if an option is already selected and the we try to press the up/down arrow keys, the selected option disappears and we cannot navigate further.
3. For multi select dropdown clicking `Enter` does not select the options.
4. For multi select dropdown there is an infinite scroll i.e. if we press down arrow key after the last option, the first option does not get selected rather the highlight disappears.
5. Dropdown height increases when we select multiple options.

**Comment by shadabbuchh** [comment]
Above mentioned issues are fixed. However below bugs still exist:

1. There is a padding for dropdowns in user invite modal/fork template.


2. The Homepage > User invite modal dropdown does not have a hover/highlight state on keyboard navigation.
3. In the Git > Merge tab when the dropdown is disabled, we are still able to see the hand icon which indicates that the dropdown is clickable (when actually it is disabled)
https://www.loom.com/share/ba4aa74d9e9749d9b728e52076bdf74b
4. In Property pane the highlight/hover state in the incoming/outgoing connections dropdown does not work on keyboard navigation.
5. The App Font dropdown does not highlight the selected option.
https://www.loom.com/share/36b886c8a9994897bd58a73f20511b2b
6. Auto scroll does not work in Phone/Currency Input widgets. e.g. when we search a keyword in the currency input widget and then press the up arrow on the keyboard the last item in the dropdown gets highlighted but user cannot see the option as auto scroll does not work. **(This issue exists throughout all dropdowns)**
https://www.loom.com/share/d4345670c88b4bcba3819633bb2403f7
7. We see additional space in the dropdown for when the dearch does not match any options in the Currency/PhoneInput widgets.

8. In GSheet query page, when we click on any dropdown and the press the down/up arrow key, the first/last option is highlighted respectively. Ideally the option above or below the already selected option should get highlighted.
https://www.loom.com/share/e5d2668f3d1b4d789e6bd6eb80e1d953

**Comment by albinAppsmith** [comment]
@shadabbuchh  3, 4 & 6 should be separate tickets since it exists in prod as well. Everything else is fixed.

**Comment by shadabbuchh** [comment]
Retested the above issues. Below is the status:

1. Fixed
2. Fixed
3. Will raise a separate issue
4. Fixed
5. Will raise a separate issue
6. Still exists
7. Still exists
8. Still exists.

Additionally now text inside some of the drop-downs is getting chipped.

**Comment by shadabbuchh** [comment]
The issue where text of selected options was getting chipped is fixed in this PR.

**Review by tanvibhakta — APPROVED** [review]

**Pull request merged**
