### PR TITLE
fix: section titles according to new ads on datasource list page

### LINKED ISSUE #29214: [Bug]: Update the section titles to use new design system on datasources pagee
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Screenshot 2023-11-29 at 4 49 42 PM

### Steps To Reproduce

1. Go to datasources page
2. Observe section titles

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

Both

### PR DESCRIPTION
**Pull request by AmanAgarwal041**
## Description
- Updated the section titles on the datasource page according to new ads changes
- Updated the title of secure banner

#### PR fixes following issue(s)
Fixes #29214 

Figma link : https://www.figma.com/file/kbU9xPv44neCfv1FFo9Ndu/User-Activation?type=design&node-id=2365-20296&mode=design&t=x5YSnNQ2mNiVAnUO-4

> if no issue exists, please create an issue and ask the maintainers about this first
>
>
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
- [ ] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

## Summary by CodeRabbit

- **Refactor**
	- Updated text styling properties for improved visual consistency across the app.
- **Style**
	- Enhanced text elements with new style definitions for better readability and aesthetics.

### CODE REVIEW

**Review by sneha122 — APPROVED** [review]

**Comment by AmanAgarwal041** [comment]
Adding `Test plan approved` as been approved by @carinanfonseca

**Pull request merged**
