### PR TITLE
fix: api error update full error object instead of only defined keys

### LINKED ISSUE #26941: [Bug]: Inconsistent Api error after the invalid chars are removed from header key
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

No invalid Header key added: 
Screenshot 2023-09-04 at 6 32 34 PM

Invalid Header key added: 
Screenshot 2023-09-04 at 6 32 45 PM

Invalid Header key removed: 
Screenshot 2023-09-04 at 6 32 55 PM

[Error Video](https://theappsmith.slack.com/files/UTK3MJTH9/F05P31U1GLE/shot-2023-08-24-05-05-20.mp4)
Slack thread : https://theappsmith.slack.com/archives/C040LHZN03V/p1692853714647789

### Steps To Reproduce

1. Create an api with url that don't exist
2. Run the query and observe the error
3. Added invalid char `>` to one of the header's key
4. Run the query and observe the error
5. Remove the invalid char `>` 
6. Run the query and observe the error

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by AmanAgarwal041**
## Description
Earlier `_.assign` was being used to update the error response of the api call but post this change full object is being replaced to update all the existing keys from the error response of the api call. So when the header was being updated with invalid chars the response had some plugin details error which was persisting due to `_.assign` function on removal of invalid chars too, thereby persisting the wrong errored response.

#### PR fixes following issue(s)
Fixes #26941 

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
- [x] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [x] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [x] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by Irongade — DISMISSED** [review]

**Comment by prapullc** [comment]
@AmanAgarwal041 :tested the PR and observed that when we add the wrong header the API does not get validated and gets executed. I prefer we need to validate the header at the client end as well.
cc: @rohan-arthur

**Comment by rohan-arthur** [comment]
@prapullc , I move this issue back to QA after today's discussion, summarising below:
1. since this change adds value to the user, we should go ahead with this change
2. if we want to validate on illegal characters in the headers, this should be tracked in a separate issue

**Comment by prapullc** [comment]
Moving it to the done state as per the above comment. We can go to Release

**Review by Irongade — APPROVED** [review]

**Pull request merged**
