### PR TITLE
test: Disable status check for deleteApp step after each test

### PR DESCRIPTION
**Pull request by NandanAnantharamu**
There is an exclusive test to validate Delete App workflow. Hence, we now disable the status check for the delete app step executed after each test case to clean up the database. Any failure in this `after` step doesn't fail the test suite. 

This is being done to prevent flaky test failures in Cypress which is causing legitimate tests to fail randomly. 

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>
No changes to code coverage between the base branch and the head branch</details>

### CODE REVIEW

**Review by yatinappsmith — APPROVED** [review]

**Review by yatinappsmith — DISMISSED** [review]

**Comment by mohanarpit** [comment]
Test result: https://github.com/appsmithorg/appsmith/runs/4150683584

**Review by yatinappsmith — APPROVED** [review]

**Comment by mohanarpit** [comment]
Test result: https://github.com/appsmithorg/appsmith/runs/4151471685?

**Review by yatinappsmith — APPROVED** [review]

**Pull request merged**
