### PR TITLE
chore: Add Rename context menu

### LINKED ISSUE #36968: [Task]: Add Rename context menu option
### SubTasks

Add the new context menu option called rename in App IDE query and Js (where tabs show up)

This would make the tab go in editable mode

https://app.zeplin.io/project/6683c698d2210f2b0697d978/styleguide/components?coid=6683c86139af06c2db8c8dac

### PR DESCRIPTION
**Pull request by hetunandu**
## Description

Adds the Rename context menu in the Action Redesign Epic

Fixes #36968

## Automation

/ok-to-test tags="@tag.IDE"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/11606861448>
> Commit: da150b1d0f049ce73a04af83bc9a634b3ec3c26c
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=11606861448&attempt=1" target="_blank">Cypress dashboard</a>.
> Tags: `@tag.IDE`
> Spec:
> <hr>Thu, 31 Oct 2024 06:29:54 UTC

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [ ] No

## Release Notes

- **New Features**
  - Introduced the `InputCursorMoveIcon` for enhanced visual representation.
  - Added `RenameMenuItem` component for improved renaming functionality.
  - New `useIsRenaming` hook to manage renaming state effectively.
  - Added context menu option for renaming JavaScript collections.

- **Enhancements**
  - Updated `EditableName` component to improve editing control and validation.
  - Enhanced `EditableText` component with better styling and error handling.
  - Streamlined `EditableTab` component integration with Redux for renaming interactions.

- **Bug Fixes**
  - Refined test cases for the `EditableName` component to ensure accurate behavior during editing.

- **Chores**
  - Consolidated exports in the IDE module for better organization.

### CODE REVIEW

**Comment by ankitakinger** [comment]
@hetunandu 
1. On outside click, the new name is not getting saved
2. JS objects doesn't have the rename context menu added, will that be handled in a separate PR?
3. Wasn't able to check for modules, workflows & module instances. Do we have a EE PR as well for testing?

**Comment by hetunandu** [comment]
@ankitakinger 

> 1. On outside click, the new name is not getting saved
Done
> 2. JS objects doesn't have the rename context menu added, will that be handled in a separate PR?
Done
> 3. Wasn't able to check for modules, workflows & module instances. Do we have a EE PR as well for testing?
https://github.com/appsmithorg/appsmith-ee/pull/5456

**Comment by ankitakinger** [comment]
@hetunandu when I'm trying to edit the name, and end up giving the same name and press "enter" or click outside, it calls the API and gives error.

**Review by albinAppsmith — APPROVED** [review]

**Pull request merged**
