### PR TITLE
fix: restricting passphrase to be sent to client

### LINKED ISSUE #34601: [Bug]: Encrypted value of passphrase is being seen after saving the datasource
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the snowflake db with key pair auth is stored. The passpharse gets saved but on editing the datasource, it is shown in the passphrase field as encrypted string. 
Ideally it shouldn't be returned on the client end.
Screenshot 2024-06-27 at 12 38 33 PM

### Steps To Reproduce

1. Create a snowflake db with key pair auth
2. Save the db with some passphrase field data
3. Edit the datasource and observe the passphrase field

### Public Sample App

_No response_

### Environment

Production

### Severity

Low (Cosmetic UI issues)

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by AmanAgarwal041**
## Description
Restricting the passphrase field for Snowflake datasource auth type `keypair` to be sent to the client.

Fixes #34601 
_or_  
Fixes `Issue URL`
> [!WARNING]  
> _If no issue exists, please create an issue first, and check with the maintainers if the issue is valid._

## Automation

/ok-to-test tags="@tag.Datasource"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9757014679>
> Commit: e3699b1ace9b4ae661ad2790c525f28ce872e298
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9757014679&attempt=2" target="_blank">Cypress dashboard</a>.
> Tags: `@tag.Datasource`

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [ ] No

## Summary by CodeRabbit

- **Security Enhancement**
  - Improved data protection by ensuring the `passphrase` field in authentication is no longer exposed in public JSON views.

### CODE REVIEW

**Review by NilanshBansal — COMMENTED** [review]
Code LGTM. Also tested the changes on DP. 
Nit: @AmanAgarwal041 can we please add some test case to assert the passphrase value is not getting sent in the API response. The reason I am saying this is, let's say someone reverts this change back to Views.Public.class, the test case can catch it and start failing.

**Comment by AmanAgarwal041** [comment]
> Code LGTM. Also tested the changes on DP. Nit: @AmanAgarwal041 can we please add some test case to assert the passphrase value is not getting sent in the API response. The reason I am saying this is, let's say someone reverts this change back to Views.Public.class, the test case can catch it and start failing.

We can add the integration test later when we will be adding test cases for saving and testing datasources. @NilanshBansal

**Comment by NilanshBansal** [comment]
> > Code LGTM. Also tested the changes on DP. Nit: @AmanAgarwal041 can we please add some test case to assert the passphrase value is not getting sent in the API response. The reason I am saying this is, let's say someone reverts this change back to Views.Public.class, the test case can catch it and start failing.
> 
> We can add the integration test later when we will be adding test cases for saving and testing datasources. @NilanshBansal

Sure @AmanAgarwal041 that works! Can you please create an issue for the same and mention it here so that we don't miss it 🙏

**Comment by AmanAgarwal041** [comment]
> > > Code LGTM. Also tested the changes on DP. Nit: @AmanAgarwal041 can we please add some test case to assert the passphrase value is not getting sent in the API response. The reason I am saying this is, let's say someone reverts this change back to Views.Public.class, the test case can catch it and start failing.
> > 
> > 
> > We can add the integration test later when we will be adding test cases for saving and testing datasources. @NilanshBansal
> 
> Sure @AmanAgarwal041 that works! Can you please create an issue for the same and mention it here so that we don't miss it 🙏

Added this link to the notion issue.

**Comment by NilanshBansal** [comment]
The test case [task](https://github.com/appsmithorg/appsmith/issues/34631) will be taken up separately as per discussion with @AmanAgarwal041

**Review by NilanshBansal — APPROVED** [review]

**Pull request merged**
