### PR TITLE
ci: Calculate pr cost

### PR DESCRIPTION
**Pull request by sarojsarab**
> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.
>
#### PR fixes following issue(s)
Fixes # (issue number)
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
- [ ] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Comment by Aishwarya-U-R** [comment]
@sarojsarab - can we add what are these used for : 
Eg - something like for understanding of end-users like me:
UBUNTU (CI-test & perf runs): $0.00
UBUNTU_8_CORE (client_build): $0.77
UBUNTU_4_CORE (server build): $2.27

**Comment by Aishwarya-U-R** [comment]
> The total cost for this **PR** is **$6.08**. **Breakdown:** UBUNTU: $0.00 UBUNTU_8_CORE: $0.77 UBUNTU_4_CORE: $2.27

And how is total cost 6.8 here.. its 0.77+2.27 = 3.04 know 🤔

**Comment by sarojsarab** [comment]
> > The total cost for this **PR** is **$6.08**. **Breakdown:** UBUNTU: $0.00 UBUNTU_8_CORE: $0.77 UBUNTU_4_CORE: $2.27
> 
> And how is total cost 6.8 here.. its 0.77+2.27 = 3.04 know 🤔

There is a small bug, it's still work in-progress...

**Comment by Aishwarya-U-R** [comment]
> > @sarojsarab - can we add what are these used for : Eg - something like below for understanding of end-users like me: UBUNTU (CI-test & perf runs): $0.00 UBUNTU_8_CORE (client_build): $0.77 UBUNTU_4_CORE (server build): $2.27
> 
> No it's not possible as GitHub is not providing the details of what jobs has run in a specific machine.

Oh, I thought it was local variable `const cost = { UBUNTU: 0.008, UBUNTU_4_CORE: 0.016, UBUNTU_8_CORE: 0.032 };`

And can be a text update here? No is it?

**Pull request closed without merging**
