### PR TITLE
fix: prevent invalid property assesment lint error

### LINKED ISSUE #19925: [Bug]: False lint error showing up when assessing entity property using square brackets
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Screenshot 2023-01-19 at 15 02 39
Screenshot 2023-01-19 at 15 02 04

### Steps To Reproduce

1. Navigate to any JS Object
2. Add the following function

myFun: ()=>{
const prop = "mode"
const appMode = appsmith[prop]
}

Observe lint error.

### Public Sample App

_No response_

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by ohansFavour**
## Description

When a property of an object (or entity) is accessed and the property name is a computed value, linting should be ignored. This is because we can not statically determine what the computed value is, and secondly, this value can be an argument of a JS function that can change at run time.

Fixes #19925 

Media

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual
- Cypress

### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by Rishabh-Rathod — APPROVED** [review]
LGTM.

 
Could we add eslint & prettier config to ast module to avoid code formatting. ( This could be done separately or the maintainer of the module could be tagged )

**Comment by ohansFavour** [comment]
> LGTM.
> 
> Can we add eslint & prettier config to ast module to avoid code formatting. ( This could be done separately or the maintainer of the module could be tagged )

Nice point, I will add it and assign the maintainer for review.

**Pull request merged**
