### PR TITLE
feat: Datepicker reskinning

### LINKED ISSUE #11024: [Enhancement] : Datepicker widget reskinning
https://www.notion.so/appsmith/Datepicker-5c65ea190a4146609d300d0c770dc1b3

### PR DESCRIPTION
**Pull request by jsartisan**
It Fixes UI inconsistency in datepicker widget.

Fixes #11024

## Type of change
- Bug fix

## How Has This Been Tested?
- Manually

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by dhruvikn — APPROVED** [review]
LGTM! 🚀

**Comment by chandannkumar** [comment]
@jsartisan 
- The bg color on hover for Month, Year and Pagination Arrow is not as per theming color as mentioned in design
https://www.loom.com/share/2d5fc23d190845d78d5c7d05ca5463aa

**Comment by chandannkumar** [comment]
Tested this PR it's LGTM
- Tested updated theming changes in this PR
- Tested disabled state
- Tested Date picker on JSON Form
-

**Pull request merged**
