### PR TITLE
fix: Added an Indice.Layer to the Border and Indicator of the Guided …

### LINKED ISSUE #21798: [Bug]: On-boarding flow's marker overlaps with text
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On-boarding flow's the circle on step 8/9 is being overlayed by the Deploy container

### Steps To Reproduce

Screenshot 2023-07-21 at 08 44 42

### Public Sample App

Just start a "Welcome Tour" and go into step 8/9

### Environment

Production

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by nerbos**
fix: Added an Indice.Layer to the Border and Indicator of the Guided)Tour and use one higher than the portal and header to make sure this issue doesn't happen again
>
#### PR fixes following issue(s)
Fixes #21798 
>
#### Type of change
- Bug fix (non-breaking change which fixes an issue)
>
#### How Has This Been Tested?
- [x] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by akash-codemonk — APPROVED** [review]

**Comment by nerbos** [comment]
> Workflow run: https://github.com/appsmithorg/appsmith/actions/runs/5621239703. Commit: ``. Cypress dashboard url: Click here! All cypress tests have passed 🎉🎉🎉

I love flaky test!

**Comment by akash-codemonk** [comment]
@nerbos CI seems to be stuck for some reason. Can you try pulling the latest release and re-running the test? Everything should pass then.

**Comment by nerbos** [comment]
@akash-codemonk I was re-running stages due to flaky tests or timeouts. Thank you for helping!

**Pull request merged**
