### PR TITLE
added condition to reset lib files

### LINKED ISSUE #743: [BUG] FilePicker widget screen isn't clearing after submitting the form.
## Description
FilePicker widget screen isn't clearing after submitting the form.

### Steps to reproduce the behaviour:
1. Upload any file using FilePicker.
2. Submit form & the form is getting reset.
3. But the FilePicker `file browse` screen is persisting.

[Video In Action](https://drive.google.com/file/d/1UQDSBenesC9wMxb7ZP5ja6mI2pF6eq5f/view?usp=sharing).

### Important Details
 - Version: Cloud
 - OS: MacOs 10.14.6
 - Browser: Firefox 80.0.1 (64-bit).

### LINKED ISSUE #6124: [Bug] Clear file picker's previous file uploads on reset widget
## Description
After uploading a file through the file widget on success if the user tries to clear the file widget it gets cleared but the next time user tries to upload a file previous file is shown in the file picker modal. 

### Steps to reproduce the behavior:

1. upload a file using the file picker
2. Create button and add action to reset wiget(filePicker)
3.  After upload successfull click button - file picker gets cleared
4. upload a file again by clicking file picker, see the previous file is shown

link - https://www.loom.com/share/d135ce2558734efa99f008bd77e72bd1

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment [production, release, deploy preview]

### PR DESCRIPTION
**Pull request by techbhavin**
> Clear file picker's previous file uploads on reset widget

Fixes #6124 

Fixes #743

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ]  I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>

    // Code coverage diff between base branch:release and head branch: bug/clear-filepicker-on-reset 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 50.71 **(0.24)** | 38.6 **(0.88)** | 36.21 **(0)** | 55.35 **(0.27)**</details>

### CODE REVIEW

**Review by somangshu — APPROVED** [review]
LGTM

**Comment by YogeshJayaseelan** [comment]
@somangshu verified the fix and still the issue exists for both #6124 and #743 for the first time unless the user refresh the page manually 

https://loom.com/share/4dadb47b84854a2bbbecb0bb42525dbf

**Comment by somangshu** [comment]
@YogeshJayaseelan can you check to see if this issues exist in other places too, I feel this might not be related to the fix.

@techbhavin let me know if you have identified the problem.

**Comment by techbhavin** [comment]
@somangshu  In my observation  

I have gone through the current flow and found few things that are the cause of current resetWidget behavior. When New file widget is added on canvas and a reset widget action is fired for that widget the updates fired by redux are as shown in the image 

image

In this case file widget selected file metaProperty value becomes "undefined". Due to this, a mismatch with the default property occurs, an empty array "[]" for this property.

image

MetaHOC componentDidUpdate if condition returns false and meta state is not updated

But once a page is refreshed and the same button click is fired to resetWidget very different redux update happens as shown in image 2

image

After this update selected file, metaProperty value is `[  ]` which is the same as default property check-in MetaHOC and state is reset and file widget reset works as expected.

If I can get more details on why the same action ( resetWidget ) for the same widget sets the same meta property "undefined" at first but "[]" after page reload then we can get to a solution

**Comment by somangshu** [comment]
@hetu need you help with☝️ here

**Pull request closed without merging**
