### PR TITLE
fix: Filtering out empty value env variables from /admin/env API response in backend

### PR DESCRIPTION
**Pull request by vivonk**
## Description
This PR is part of adding improvements in /admin/env API - https://github.com/appsmithorg/appsmith/issues/18423 
And with that, it fixes main issue which is - https://github.com/appsmithorg/appsmith/issues/17846

When we are sending empty value env variables in /admin/env API response, it's causing incorrect state in toggle buttons (Toggle button gets enabled for empty value variables). Because of which, we were facing incorrect config update issues in Admin settings like Email. As part of fixing that, we are sending only non-empty valued env variables so that frontend interprets it correct.

Screenshot 2022-11-24 at 11 06 55
Screenshot 2022-11-24 at 11 07 04

Fixes
https://github.com/appsmithorg/appsmith/issues/18423
https://github.com/appsmithorg/appsmith/issues/17846

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manual - after running appsmith server locally with this change, https://github.com/appsmithorg/appsmith/issues/17846 seems to be resolved

### Test Plan
- PENDING, incase required

### Issues raised during DP testing
- NA

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Comment by trishaanand** [comment]
@vivonk : Nirmal, is this change a breaking change? Are we dependent on the FE changes to take this to release?

**Comment by vivonk** [comment]
No, @trishaanand . It's a backend change only. Frontend works fine with this change.

**Review by trishaanand — APPROVED** [review]

**Pull request merged**
