### PR TITLE
fix: bug- Audio recorder does not reset UI when a recording is taking place #14693

### LINKED ISSUE #14693: [Bug]-[21]:Audio recorder does not reset UI when a recording is taking place
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When audio recorder/camera widget on video mode are reset while they are recording then the widget continues to record without any changes occurring on the UI, i.e. the UI continues to record.

### Steps To Reproduce

1. Using a binding as follows on a button widget's trigger field
`{{resetWidget("AudioRecorder1",true).then(() => showAlert('success'))}}`
2. Add a an audio recorder and text widget to the canvas
3. Bind internal widget properties of the audio recorder to the text widget as seen in the video
4. Click on the record on the audio recorder and then click on the button widget - observe the success toast displayed but audio recorder continues to record
5. When recorder is paused or stopped then the widget resets as expected
6. Similar behaviour is observed with the camera widget on video mode - but UI retains ok and discard icons even after a reset as seen in issue #14692 

https://www.loom.com/share/0122d91c7ed345fa8493f8a149e79e29

### Public Sample App

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by akshat8605**
Fixes #14693
_or_  
Fixes https://github.com/appsmithorg/appsmith/issues/14693
> [!WARNING]  
> _If no issue exists, please create an issue first, and check with the maintainers if the issue is valid._

media : https://www.loom.com/share/fb1c08173024427d96e483e782d41ee3?sid=49f2fdd8-ca3f-449f-ad09-aec8b294642a

## Automation

/ok-to-test tags="@tag.Widget"

### :mag: Cypress test results

> [!CAUTION]  
> If you modify the content in this section, you are likely to disrupt the CI result for your PR.

## Summary by CodeRabbit

- **Bug Fixes**
	- Updated the Audio Recorder Widget to reset the blob URL property to `null` after use, enhancing the control flow and logic for handling audio recordings.

### CODE REVIEW

**Comment by jsartisan** [comment]
@somangshu PR looks good to me.

**Review by jsartisan — APPROVED** [review]

**Comment by somangshu** [comment]
@jsartisan kindly run the test suit to be sure.

**Pull request merged**
