### PR TITLE
chore: replaced babel loader with esloader

### PR DESCRIPTION
**Pull request by arunvjn**
## Description
This is an attempt to improve client build time by replacing babel loader with esbuild-loader. [https://github.com/privatenumber/esbuild-loader](url)

| Processor  |  RAM  | babel-loader  | esbuild-loader |
|------------|-------|--------------|----------------|
| M1               | 16GB  |  180-190s      | 100 - 115s |
| i5                 | 16GB  |  280 - 300s    | 160 - 170s |

Fixes #

## How Has This Been Tested?
- Manual

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: esloader_experiment 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 55.01 **(0.01)** | 36.56 **(0)** | 34.93 **(0)** | 55.41 **(0.01)**
 :green_circle: | app/client/src/utils/WorkerUtil.ts | 89.76 **(0.78)** | 72.55 **(1.96)** | 100 **(0)** | 93.33 **(0.95)**</details>

### CODE REVIEW

**Comment by SatishGandham** [comment]
@arunvjn ,
Can you list the improvements here.

**Comment by riodeuno** [comment]
@SatishGandham @arunvjn I can identify the following changes in this PR:
- A [custom webpack config](https://nextjs.org/docs/api-reference/next.config.js/custom-webpack-config) which removes the `babel-loader` and uses `esbuild-loader` instead.
- Since `IconWidget` is unlisted in the widgets panel, it may not have the icon SVG to represent, resulting in esbuild-loader complaining about it, which babel-loader did not -- the icon value has been changed to null. We need to confirm if this works fine when listed in the entity explorer, we can check by adding a modal widget to the canvas and looking at its children


The changes look fine to me

@arunvjn  The vercel build here took [9 minutes](https://vercel.com/get-appsmith/appsmith/6oAiiFpQV414JKLPM7nJSoqDu1or). While in other cases (babel) it takes [6 minutes](https://vercel.com/get-appsmith/appsmith/D35gfaJVszPEMvVEWN91UyFUbfW6)

Can we figure out a way to benchmark this for a reliable result?
I would also recommend a quick regression before merging this in.

**Review by riodeuno — CHANGES_REQUESTED** [review]
Adding a request changes tag here so that it doesn't show up in my review requests notification. Please re-request again if you'd like for me to review this PR again.

**Comment by riodeuno** [comment]
@arunvjn @SatishGandham This PR is open, so I was wondering if there is any activity which requires review or attention? If we're moving ahead with the changes, let's do so, alternatively, let's put this PR in to draft mode.

**Pull request closed without merging**
