### PR TITLE
fix: App deploying when git push fails

### LINKED ISSUE #15176: [Bug]-[1646]:App is deploying even when Git commit fails
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Even when a branch is marked as protected and committing fails, the view mode still has the new app. This is a blocker for deployments

### Steps To Reproduce

1. Connect an app to git
2. Mark the master branch as protected
3. Commit changes and see a failure
4. Open the view mode, the changes are there
Alternatively, if you add a pre-commit hook to the local docker image to fail the commit, this still works
```
#!/bin/sh

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "master" ]; then
  echo "You can't commit directly to master branch"
  exit 1
fi
```
### Public Sample App

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by vishnu-gp**
## Description

This fixes the bug even when a git push fails due to various reasons, the view mode still has the new app.

Fixes #15176

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual test
- Test cases

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by trishaanand — DISMISSED** [review]

**Review by AnaghHegde — COMMENTED** [review]
Minor nit, rest looks good to me.

**Comment by abhvsn** [comment]
@vishnu-gp `not urgent` but can we also try to remove the unnecessary commit if the push fails as described in the issue?

**Comment by AnaghHegde** [comment]
@abhvsn Are you saying we should do git reset so that the commit is also reversed

**Comment by abhvsn** [comment]
> @abhvsn Are you saying we should do git reset so that the commit is also reversed

@AnaghHegde yes that's correct. Also this will be a safe operation as remote doesn't know about this commit so no there won't be any issue if other users are syncing the changes as well.

**Comment by abhvsn** [comment]
> > > @abhvsn Are you saying we should do git reset so that the commit is also reversed
> > 
> > 
> > @AnaghHegde yes that's correct. Also this will be a safe operation as remote doesn't know about this commit so no there won't be any issue if other users are syncing the changes as well.
> 
> Can this be done as a chore/feat separately to not further complicate this fix?

Yes this is not a immediate requirement just create a ticket to pick this up later 🙂

**Review by trishaanand — APPROVED** [review]

**Comment by vishnu-gp** [comment]
> > > > @abhvsn Are you saying we should do git reset so that the commit is also reversed
> > > 
> > > 
> > > @AnaghHegde yes that's correct. Also this will be a safe operation as remote doesn't know about this commit so no there won't be any issue if other users are syncing the changes as well.
> > 
> > 
> > Can this be done as a chore/feat separately to not further complicate this fix?
> 
> Yes this is not a immediate requirement just create a ticket to pick this up later 🙂

@abhvsn Here's the issue opened for this https://github.com/appsmithorg/appsmith/issues/15349

**Pull request merged**
