### PR TITLE
feat: vite upgrade

### PR DESCRIPTION
**Pull request by yaldram**
## Description

- Use vite for the project - https://vitejs.dev/

Fixes https://github.com/appsmithorg/appsmith/issues/12066

## Type of change

- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested?

- Tested Manually on the canvas

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by yaldram** [comment]
- Please rimraf the node_modules - `rm -rf node_modules` and then run `yarn install`.

Two major issues that we are facing : - 
1. Derived properties are not working for the `Select` widget and `TreeSelect` widget. I think there is a problem under the `src/workers/validations.ts` file.
2. Vite reload does not work for some `.ts` files here is one issue that I found maybe someone can look into it - https://github.com/vitejs/vite/issues/4259

**Comment by yaldram** [comment]
We removed the `raw-loader` webpack plugin now we are using `vite-raw-plugin` for loading the `derived.js` files. I have renamed all the `derived.js` files in the widgets to `_derived.js` and because we are using a new loader the regex under the `parseDerivedProperties.ts` was failing so as a work-around I added a dummy `noop function` in these files.

**Comment by yaldram** [comment]
https://www.loom.com/share/3e758138c9444a7aba896cc095287676

Video Recording of the failing derivedProperties, it fails for the select, treeselect, multiselect, multitreeselect widgets.

**Comment by yaldram** [comment]
I have setup jest following this guide - https://egghead.io/lessons/jest-adding-jest-with-typescript-support-to-a-vite-application but we have the following issues : - 
1. jest setup is failing to read our `babel.config.js`.
2. There is an error for the `worker loading` we need to change it in the jest.config.ts.
3. Tests are failing.

**Comment by yaldram** [comment]
Some Caveats : - 
- We need to solve for the hot reload, re-load after the file changes - https://github.com/vitejs/vite/issues/4259, it is also an issue for cypress test cases, when cases re-load.
- @riodeuno encountered some issues with the routing when serving with `build`.
- Jest test cases are failing for GlobalHotKeys related files.
- We need to check if the `vite-sentry` plugin is working as expected, to pass the auth token to Sentry plugin inside the `vite.config.ts`, we need to have .env files. I am thinking of not using the Sentry plugin and use their components instead needs some investigation.
- We need to check whether the `vite-pwa` plugin a replacement for `workbox plugin` is working as expected.
- We need to make sure everything is working as expected.

**Comment by Rishabh-Rathod** [comment]
Temporarily removing as a reviewer. Add again when PR is ready for review.

**Comment by taowen** [comment]
@yaldram has the issue been fixed? https://github.com/taowen/vite-howto/discussions/4

**Comment by yaldram** [comment]
@taowen Hey, no unfortunately we decided to move forward with cra-5 for now. Inline with this comment - https://github.com/vitejs/vite/issues/7608#issuecomment-1094951352 we might have to re-structure our codebase for faster hot reloads. But unfortunately we don't have any docs, guides from the vite team on how to restructure large projects with redux.

**Comment by riodeuno** [comment]
Closing this in favour of #14000

**Pull request closed without merging**
