### PR TITLE
Button UI test cases

### PR DESCRIPTION
**Pull request by arslanhaiderbuttar**
## Description
Created new UI Automated test cases for the Button widget. 

## Type of change

- New feature (non-breaking change which adds functionality)

Automated following UI test cases:
- for button regarding the property pane:
- Button Style Validation
- Button Copy and paste
- Button Delete
- Create api, and then call it upon clicking the button widget.
- Create query, and then call it upon clicking the button widget.
- All above using JS

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>
No changes to code coverage between the base branch and the head branch</details>

### CODE REVIEW

**Review by yatinappsmith — DISMISSED** [review]

**Comment by NandanAnantharamu** [comment]
@arslanhaiderbuttar There is a conflict in your branch, please resolve

**Comment by NandanAnantharamu** [comment]
@arslanhaiderbuttar also one more thing , we don't commit cypress.json file if there isnt anything specific to add. Please remove it

**Comment by arslanhaiderbuttar** [comment]
I have updated the QueryEditor.json file. Missing values are added.

**Review by NandanAnantharamu — APPROVED** [review]
LGTM

**Review by yatinappsmith — APPROVED** [review]

**Review by NandanAnantharamu — APPROVED** [review]
approved for testing

**Review by yatinappsmith — APPROVED** [review]

**Review by NandanAnantharamu — APPROVED** [review]
approved for test

**Pull request merged**
