### PR TITLE
fix: Google Sheets Scope Label Change

### LINKED ISSUE #22327: Migration For old Datasource
When we open data source configuration for the existing Gsheet DS, I should be able to see the “Whole drive Access” option preselected, so that existing Gsheet data sources continue work as before.

### PR DESCRIPTION
**Pull request by PiyushPushkar02**
## Description

- The following PR changes the label values seen by the user in the scope selection drop-down menu while creating a Google Sheet data source.
- The changes accommodate for one specific scope that was present in the previous implementation and is not present now i.e read/write without delete permission for which a new scope has been added.
- Also with these changes the migration for old data sources is not required since we have added all the previously used scopes here.
- Figma Link: https://www.figma.com/file/TcFhqEbAc8ymHTRF5wR1qv/Limited-GSheet-Access?node-id=506-32761
- Notion link for migration: https://www.notion.so/appsmith/Google-Sheet-Migration-ab7bbfbdae1f40189a957b6ae5374145

Fixes #22327 

## Type of change

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

## How Has This Been Tested?

- Manual

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Comment by prapullac** [comment]
@PiyushPushkar02 @sneha122 
Issue on PR
1) In cancel the scope is not displayed to the user on review page(https://www.loom.com/share/67ba9419b74a421bbff15d466fba8357)
2) We are telling the user read/write and taking permission to delete from google. However on the review screen after authorise we show them its read create and edit but delete action also works (https://www.loom.com/share/7862d2b7ff424c7b85f1a5dad8acf3cb)

**Comment by PiyushPushkar02** [comment]
Hi, @prapullac  for the 2nd issue mentioned above the delete permission has a different meaning. For " Read/ Write/ Delete " the delete permission says a user can delete an entire sheet while for " Read/ Write" it means a user can delete a row inside a sheet but not the entire sheet.

**Pull request merged**
