### PR TITLE
fix: preventing objects from collapsing in the debugger when resizing

### LINKED ISSUE #21423: [Bug]: resizing debugger causes log item to collapse
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have am sending an array of objects to `console.log()`.
When I expand one of these objects and then adjust the height of the debugger (to get a better view perhaps), my expanded object is getting collapsed.

### Steps To Reproduce

https://user-images.githubusercontent.com/94514895/225254158-89ff01bf-8f19-4897-a305-58806d73a1c0.mov

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by saiprabhu-dandanayak**
## Description
i have raised this pr in-order to prevent objects from collapsing in the debugger when resizing.

This pull request includes a small change to the `LogItem` component in the `Debugger` directory. The change optimizes the component by wrapping it with `React.memo` to prevent unnecessary re-renders.

Fixes #21423 

## Summary by CodeRabbit

- **New Features**
	- Enhanced performance of the `LogItem` component by optimizing its rendering with memoization.
  
This change ensures that the component only re-renders when its props change, leading to a smoother user experience.

### CODE REVIEW

**Comment by saiprabhu-dandanayak** [comment]
**@appsmithorg/query-js-pod** , can you pls assign a reviewer for this PR.
Thanks in advance.

**Comment by alex-golovanov** [comment]
@saiprabhu-dandanayak the fix is working, thank you. Just need to run some tests in a separate PR.

**Comment by saiprabhu-dandanayak** [comment]
Sure , please let me know if any changes needs to be done.

**Review by alex-golovanov — APPROVED** [review]

**Comment by alex-golovanov** [comment]
[Shadow PR](https://github.com/appsmithorg/appsmith/pull/36787) tests are passing.

**Pull request merged**
