### PR TITLE
fix: selected row issue

### LINKED ISSUE #9175: [Bug]: Selected row gets unselected and index goes to -1 when menu widget is used in table widget
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[LOOM DEMO](https://www.loom.com/share/9d99e9da5e0b4c3394a09d2a67636ce9)

### Steps To Reproduce

1. Drag and drop a Table widget
2. Drag and drop a Text widget
3. Bind text widget with table widget selectedRowIndex
4. Change action column to Menu widget
5. Change the option in the menu widget and observe the issue.

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by Tooluloope**
## Description

> Menu button Column type issues with SelectedROW

Fixes #9175 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>

    // Code coverage diff between base branch:release and head branch: fix/Selected-Row-with-menu-button-column-type 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.71 **(-0.23)** | 40.83 **(-0.84)** | 36.21 **(0)** | 56.74 **(-0.25)**</details>

### CODE REVIEW

**Review by marks0351 — APPROVED** [review]
thanks for the test cases.

**Comment by vivekverma2312** [comment]
@Tooluloope Tested on deploy preview and it's working fine.

**Pull request merged**
