### PR TITLE
fix: handle undefined filterdata props in table widget

### LINKED ISSUE #9812: [Bug] TypeError: Cannot read properties of undefined (reading '0')
Sentry Issue: [APPSMITH-1F1](https://sentry.io/organizations/appsmith/issues/2864021561/?referrer=github_integration)

```
TypeError: Cannot read properties of undefined (reading '0')
  at getOriginalRowIndex (widgets/TableWidget/widget/utilities.ts:10:5)
  at selectRowIndex (widgets/TableWidget/widget/utilities.ts:37:22)
  at updateMetaRowData (widgets/TableWidget/widget/index.tsx:705:32)
  at componentDidUpdate (widgets/TableWidget/widget/index.tsx:576:12)
...
(45 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by sbalaji1192**
Fixes #9812 #9813 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/undefined-filterdata-props-table 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 55.23 **(0)** | 37.11 **(0.01)** | 34.08 **(0)** | 55.74 **(0)**
 :green_circle: | app/client/src/widgets/TableWidget/widget/utilities.ts | 100 **(0)** | 77.78 **(2.78)** | 100 **(0)** | 100 **(0)**</details>

### CODE REVIEW

**Comment by somangshu** [comment]
@vivekverma2312 this [apps](https://app.appsmith.com/applications/61b9da60c70f2742893b91aa/pages/61b9da60c70f2742893b91ac/edit?isCommentMode=true) on prod replicates the issues, We can use it to verify the solve

**Comment by Tooluloope** [comment]
This was how I managed to reproduce the Error
https://www.loom.com/share/7e93c1b0c67340d1a1534900f8d034f7

**Review by Tooluloope — APPROVED** [review]
LGTM

**Comment by sbalaji1192** [comment]
@Tooluloope Could you open an issue for the issue with undo/redo ?

**Pull request merged**
