### PR TITLE
chore: Release v1.9.8

### PR DESCRIPTION
**Pull request by nsarupr**
## Description

> Release - 14th Feb
> Version - CE-1.9.8

### CODE REVIEW

**Comment by nsarupr** [comment]
Following tests failing on the Branch:
UI test (`Regression_TestSuite/ClientSideTests/ThemingTests/Basic_spec.js`) and Perf Test
The above UI test case failure is a flaky test.

**Review by trishaanand — APPROVED** [review]

**Comment by nsarupr** [comment]
CI Update:
Link:  https://github.com/appsmithorg/appsmith/actions/runs/4190971752
Tests Failing: 
1. Regression_TestSuite/ClientSideTests/Workspace/MemberRoles_Spec.ts
2. Perf Test

**Pull request merged**
