### PR TITLE
feat: Anvil section space redistribution

### PR DESCRIPTION
**Pull request by marks0351**
## Description

Anvil Section Space distribution

In this pr, we are adding a feature to sections to redistribute a sections space within its zones.
you can find details of it over [here](https://www.notion.so/Sections-and-Zones-design-WIP-cbcb8b0ab2514aaf90d04aa3309ad56c)

As part of it we have three parts of changes
- UI components
- Middleware(Redux and Sagas)
- Space redistribution algorithm

UI/UX:

https://github.com/appsmithorg/appsmith/assets/35134347/092ba31f-d2e5-400e-80d7-45878d75ff98

Middleware changes:
- have added a new state in WidgetDragResizeState `anvil` and into it have added `isDistributingSpace` to capture when space distribution is active.
- added `anvilSpaceDistributionSagas` to capture all sagas wrt space redistribution

Space redistribution algorithm:
- Have added algorithm for redistributing space, have noted down details about it [here](https://www.notion.so/appsmith/Space-distribution-and-responsiveness-questions-517d140e83864c2287765c99dcd7c8da?pvs=4#9b33c84bcea24cfca63d7caef036f896).
>
#### PR fixes following issue(s)
Fixes # (issue number)
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
- [ ] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

## Summary by CodeRabbit

- **New Features**
  - Enhanced widget resizing capabilities with space distribution handles in Anvil layout system.
  - Introduced preview mode support for widget size configuration.

- **Enhancements**
  - Improved Anvil layout system with dynamic space distribution during resizing.
  - Added flexibility to widget size configuration by considering preview mode.

- **Bug Fixes**
  - Corrected widget border styles to reflect space distribution and resizing states.

- **Refactor**
  - Streamlined space distribution logic in Anvil layout sagas and selectors.
  - Updated `AnvilFlexComponent` to conditionally assign `flexGrow` property.

- **Documentation**
  - Updated comments to clarify new space distribution behavior in Anvil layout.

- **Style**
  - Adjusted styles for space distribution handles in section layouts.

- **Chores**
  - Added new action types for Anvil space distribution process.
  - Enhanced Redux state structure for drag and resize operations.

### CODE REVIEW

**Review by prsidhu — APPROVED** [review]
Looks good. @marks0351 I would suggest to break down the util and related functions further as it is hard to keep track of the logic in such large functions.

**Review by riodeuno — APPROVED** [review]

**Pull request merged**
