### PR TITLE
fix: add defaultTab as selectedTab when selectedTab is not available

### LINKED ISSUE #5255: [Bug] Tabs Widget's selectedTab is not populated in time for onPageLoad in view mode
## Description
If you have a onPageLoad Api that needs the TabWidget selectedTab value, it works sometimes in edit mode but fails always in view mode

### Steps to reproduce the behaviour:

1. Create a Tab widget with a default selected tab
2. Create an API to read from the `TabWidget.selectedTab` property and set it onPageLoad
3. Deploy and check in view mode
4. The value is not evaluated in time and fails the API

### Important Details
- Environment: Production

### PR DESCRIPTION
**Pull request by vicky-primathon**
## Description

Add defaultTab as selectedTab when selectedTab is not available

Fixes #5255 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/selectedTab-onPageLoad 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 55.12 **(0)** | 37.05 **(0.01)** | 34.02 **(0.01)** | 55.64 **(0)**
 :sparkles: :new: | **app/client/src/widgets/TabsWidget/widget/derived.js** | **100** | **83.33** | **100** | **100**
 :green_circle: | app/client/src/widgets/TabsWidget/widget/index.tsx | 77.42 **(0.25)** | 47.14 **(0)** | 78.95 **(0)** | 77.27 **(0.26)**
 :sparkles: :new: | **app/client/src/widgets/TabsWidget/widget/parseDerivedProperties.ts** | **38.46** | **0** | **0** | **38.46**</details>

### CODE REVIEW

**Review by Tooluloope — APPROVED** [review]
LGTM,
Could you add test cases

**Comment by vivekverma2312** [comment]
@vicky-primathon Issue is working fine on deploy preview.

**Review by Tooluloope — APPROVED** [review]

**Pull request merged**
