### PR TITLE
feat: dynamic height select widget standardisation

### LINKED ISSUE #13055: [Task]: Standardise structure of Select widget to enable Dynamic Height.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

_No response_

### PR DESCRIPTION
**Pull request by ankurrsinghal**
## Description

**Created it again because there were merge conflicts with the release branch.**

1. Passed the `contentRef` to `SelectComponent` from `SelectWidget`.
2. Wrapped the `SelectComponent` class component in the React.forwardRef, and added a new optional prop `innerRef` to pass it to its child `DropdownContainer`.
3. Set the final `ref` to `DropdownContainer` which is a styled `div`.

Fixes #13055

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Manually

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by riodeuno** [comment]
@ankurrsinghal Something is wrong with this PR. It has a diff of 737 files. I guess you have pulled the latest release in this one. I would recommend, that you pull the latest release in the base branch, not this one, so that the diff between the base branch and release don't show the extra files. You can also pull the base branch into this one, if it helps.

**Review by riodeuno — CHANGES_REQUESTED** [review]
Please resolve the extra diffs which are showing up here.

**Review by rahulramesha — APPROVED** [review]

**Pull request merged**
