### PR TITLE
fix: Correctly update trigger field dependency map

### LINKED ISSUE #15695: [Bug]: TypeError: undefined is not an object (evaluating 't.triggerFieldDependencyMap[e].filter')
Sentry Issue: [APPSMITH-3J9](https://sentry.io/organizations/appsmith/issues/3465441991/?referrer=github_integration)

```
TypeError: undefined is not an object (evaluating 't.triggerFieldDependencyMap[e].filter')
  at None (workers/DependencyMap/index.ts:264:19)
```

### PR DESCRIPTION
**Pull request by ohansFavour**
## Description

This PR simply re-orders the update of the triggerfieldDependencyMap. Deleted trigger fields are deleted from the map after updating their references. So that in the case where there is a self-referencing (eg, button1.onClick depending on button1), we don't try to update deleted entries.

Fixes #15695 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
 Jest
   
- [x] https://github.com/appsmithorg/TestSmith/issues/1999

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Rishabh-Rathod — APPROVED** [review]
LGTM

**Comment by ramsaptami** [comment]
Tested and verified on DP

**Pull request merged**
