### PR TITLE
chore: [Cherry Pick] Remove extra event and old disable var (#20624)

### PR DESCRIPTION
**Pull request by sharat87**
1. Remove the `disableTelemetry` app config field, and the `APPSMITH_DISABLE_TELEMETRY` runtime env variable in client, since it is unused and is misleading.

2. There's a bug where the page event is being sent even if telemetry is turned off. This is just one event, all the others are still disabled when telemetry is off. The reason for this is because Segment automatically sends this event on load. Quoting from [their docs](https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/#page):
> Analytics.js includes a Page call by default as the final line in [the
Analytics.js
snippet](https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/quickstart/#step-2-copy-the-segment-snippet).

(cherry picked from commit 12cf30687f4a567409e7004b635ec6c048791433)

3. test: TED support for GITEA (https://github.com/appsmithorg/appsmith/pull/20477)

### CODE REVIEW

**Review by trishaanand — APPROVED** [review]

**Comment by trishaanand** [comment]
TBD : https://github.com/appsmithorg/appsmith/actions/runs/4194611944

**Comment by nsarupr** [comment]
https://github.com/appsmithorg/appsmith/actions/runs/4201995219

**Pull request merged**
