### PR TITLE
fix: [Custom widget] update default dynamic height value

### PR DESCRIPTION
**Pull request by sbalaji1192**
## Description
Add migration to set default value of custom widget dynamic height.
#### PR fixes following issue(s)
Fixes https://github.com/appsmithorg/appsmith/issues/31077
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
- [x] Manual
- [ ] JUnit
- [x] Jest
- [ ] Cypress
>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

## Summary by CodeRabbit

- **New Features**
	- Added a migration feature for custom widgets to support dynamic height adjustments, ensuring widgets can now have a fixed height setting by default.
- **Tests**
	- Introduced test suites for validating the migration of custom widget dynamic height settings.

### CODE REVIEW

**Review by rajatagrawal — APPROVED** [review]

**Comment by vhmartinezm** [comment]
@sbalaji1192 @rajatagrawal it seems like this pr introduced this bug:

https://github.com/appsmithorg/appsmith/assets/11355392/a5b7bdbc-ab74-42e7-8555-32716baf18cb

**Comment by sbalaji1192** [comment]
@vhmartinezm Are you facing this issue on the Appsmith cloud?

**Comment by sbalaji1192** [comment]
The default value of the custom widget dynamic height property should be "FIXED", So this should not be happening.

Uploading Screen Recording 2024-02-15 at 10.20.19 AM.mov…

**Comment by vhmartinezm** [comment]
@sbalaji1192 yep, Appsmith cloud. I'm using Auto layout, could you try there?

**Comment by sbalaji1192** [comment]
@vhmartinezm Yeah. I'm able to repro this. Let me get back with a RCA and a fix. Thanks for raising this!

**Pull request merged**
