### PR TITLE
feat: add template metadata fields

### PR DESCRIPTION
**Pull request by abm17**
## Description
Add new fields pertaining to template metadata

#### PR fixes following issue(s)
Fixes https://github.com/appsmithorg/appsmith/issues/23416

#### Type of change
- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

#### How Has This Been Tested?
- [X] Manual

#### Dev activity
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by nayan-rafiq — APPROVED** [review]
LGTM

**Comment by shwetha-ramesh** [comment]
@abm17  QA done.

**Comment by abm17** [comment]
No tests are added as the CS API is mocked [here](https://github.com/appsmithorg/appsmith/blob/feat/add-template-metdata-fields/app/server/appsmith-server/src/test/java/com/appsmith/server/services/ApplicationTemplateServiceTest.java).
Tests for this API are present in CS repo [here](https://github.com/appsmithorg/cloud-services/blob/d079869d467a14777193d0d0f5c4cb057db85ca3/server/appsmith-cloud-services/src/test/java/com/appsmith/cloudservices/services/ApplicationTemplateServiceTest.java#L190)

**Pull request merged**
