### PR TITLE
chore: Revert "fix: numeric type input widget should accept zero after decim…

### LINKED ISSUE #11833: [Bug]: The old file is replaced with new file in s3 crud page upload
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If the user tries to upload the 2nd file in the same folder of the s3 crud page the Images are overlapped instead of Creating the new file
Note: This issue is occurring because all the file names are displayed as undefined
[LOOM DEMO](https://www.loom.com/share/f6e37cf91f504d9aa63ed6e2949f30c4)

### Steps To Reproduce

1. generate a S3 crud page
2. now add a folder name as folder 1 and add a file no 1
3. upload a file 
4. Now search for the folder name folder one there will a file 1 displayed
5. Now Try to add a file 2 to the same folder that is folder 1
6. Now the uploaded file 2 replaces file 1 instead of being added as a new file

### Public Sample App

_No response_

### Version

release

### PR DESCRIPTION
**Pull request by sbalaji1192**
…al point (#11579)"

This reverts commit 342fec4462bcbc55f658e02360ae4a8ed5a27657.

## Description
The solution provided in https://github.com/appsmithorg/appsmith/pull/11579 is causing an issue when Input widget is placed inside the List widget since it won't support derived properties.

Fixes #11833 

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/revert-input-widget-numeric-type-changes 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 55.85 **(-0.03)** | 37.2 **(-0.04)** | 35.22 **(0)** | 56.16 **(-0.03)**
 :red_circle: | app/client/src/selectors/commentsSelectors.ts | 83.61 **(-1.64)** | 61.76 **(-2.95)** | 73.33 **(0)** | 88.24 **(-2.35)**
 :red_circle: | app/client/src/widgets/BaseInputWidget/widget/index.tsx | 65 **(-2.5)** | 6.25 **(-0.89)** | 66.67 **(5.13)** | 68.42 **(-2.63)**
 :red_circle: | app/client/src/widgets/InputWidgetV2/widget/derived.js | 78.72 **(-1.98)** | 77.36 **(-1.33)** | 100 **(0)** | 78.72 **(-1.98)**
 :red_circle: | app/client/src/widgets/InputWidgetV2/widget/index.tsx | 73.6 **(-10.61)** | 60.87 **(-9.13)** | 81.25 **(3.47)** | 72.95 **(-10.83)**
 :green_circle: | app/client/src/widgets/PhoneInputWidget/widget/index.tsx | 40.63 **(1.24)** | 6.52 **(0)** | 42.86 **(2.86)** | 40.43 **(1.25)**</details>

### CODE REVIEW

**Review by jsartisan — APPROVED** [review]

**Comment by vivekverma2312** [comment]
Tested and working fine on DP.

**Pull request merged**
