### PR TITLE
fix: minor improvement to UI controls for updating JS function settings

### PR DESCRIPTION
**Pull request by Rhitottam**
## Description
- Change UI for controlling JS function settings from radio buttons to switch toggles. 
#### PR fixes following issue(s)
Fixes # [(30098)](https://github.com/appsmithorg/appsmith/issues/30098)

#### Media
Screenshot 2024-01-31 at 10 31 50 AM

#### Type of change

- Bug fix (non-breaking change which fixes an issue)

## Testing

- [x] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

## Summary by CodeRabbit

- **New Features**
	- Introduced a new `Switch` component in the JavaScript function settings for a more intuitive user interface.
- **Refactor**
	- Updated test support for the JavaScript editor to align with the new `Switch` component, enhancing test reliability and coverage.
- **UI Enhancements**
	- Replaced `RadioGroup` components with `Switch` components in the `JSFunctionSettings` file to improve user interaction.

### CODE REVIEW

**Comment by Rhitottam** [comment]
Hi @somangshu, @pedro-santos-rodrigues  Can you please take a moment to review it? Your feedback would be greatly appreciated! Thank you!

**Comment by somangshu** [comment]
@pedro-santos-rodrigues please check the preview is ready

**Review by albinAppsmith — APPROVED** [review]

**Comment by pedro-santos-rodrigues** [comment]
I've tried it out and it works well! Well done and thank you for contributing!

**Comment by somangshu** [comment]
@albinAppsmith can you help verify if the failing tests are related?

**Comment by albinAppsmith** [comment]
Screenshot 2024-01-31 at 6 03 24 PM
@somangshu  yeah it looks like related failures.

**Comment by Rhitottam** [comment]
HI @somangshu @albinAppsmith Will fix the tests.

**Comment by somangshu** [comment]
Tests still fail. Maybe run them locally and find what is failing. 
Cant take this forward

**Comment by Rhitottam** [comment]
@somangshu  Will run the tests locally and let you know.

**Comment by Rhitottam** [comment]
Hi @somangshu Good Evening! I have finished testing locally and pushing my changes. The tests should be passing now!!

**Comment by Rhitottam** [comment]
Hi @somangshu  Good Morning! I have fixed the tests after running them locally. Would you take a moment to re-run the tests to check if they pass? Thank you!

**Comment by somangshu** [comment]
@Aishwarya-U-R I tagged you on review of test to make sure the change made is appropriate, let me know if it should be someone else!

**Review by Aishwarya-U-R — COMMENTED** [review]
@somangshu Cypress changes looks ok. We can wait for the CI pass before merge.

**Review by somangshu — APPROVED** [review]

**Pull request merged**
