### PR TITLE
fix: Fix/additional rows api header section

### LINKED ISSUE #11832: [Bug]-[1400]:Additional rows gets added into the header section on new created REST API
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the user navigates to the Header section on the API it is observed that the additional two rows are automatically added into the section 

### Steps To Reproduce

1) Create an API 
2) Ensure the Header section has two rows
3) Click on the Back option
4) Now navigate to Entity explorer an open the API that was created
and observe

Observation 
It is observed that the rows have been added (From 2 rows to 4 rows have been displayed to the user)

Video Link 
[LOOM DEMO](https://www.loom.com/share/6ebf2db7bde14c93938905c4d852d964)

### Public Sample App

_No response_

### Version

Cloud Release v1.6.14

### PR DESCRIPTION
**Pull request by sneha122**
## Description

When the user navigates to the Header section on the API it is observed that the additional two rows are automatically added into the section

Fixes #11832

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manually Tested
- Jest Unit Test

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by AmanAgarwal041 — DISMISSED** [review]

**Review by AmanAgarwal041 — APPROVED** [review]

**Comment by SatishGandham** [comment]
@sneha122 , where is this used. I see a lot of failures in perf test.

**Comment by sneha122** [comment]
> @sneha122 , where is this used. I see a lot of failures in perf test.

It is used in API Editor, in headers, params tabs, to load key value pairs form.

**Pull request merged**
