### PR TITLE
fix: slider widgets remove design system label component.

### PR DESCRIPTION
**Pull request by yaldram**
## Description
- Slider widgets were still using the `Label component from design system package`. Replace it with the `Label component from widgets/components`.

Fixes # (issue)

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual

### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by ankurrsinghal — DISMISSED** [review]

**Comment by yaldram** [comment]
Components to test - 
1. All Slider widgets.
2. Select Widget.

**Comment by Sripriya93** [comment]
Have done regression testing all sliders and select widget

Apart from already known issue [#19241](https://github.com/appsmithorg/appsmith/issues/19241), other properties for the widgets are working fine. Moving to done

**Review by ankurrsinghal — APPROVED** [review]

**Pull request merged**
