### PR TITLE
fix: Queries do not get exported in a git connected app, by using partial export.

### PR DESCRIPTION
**Pull request by AnaghHegde**
## Description
The issue happens on a feature branch for a git connected application. Works fine on master branch.
The reason is how the ids are handled for a git connected application. We use the defaultResource and map the actual id with defaultResourceId when sending the data to client. So for a git connected app the backend code was using the mongo _id to filter the selected action but the client sent the defaultResourceId in the request payload. Hence even though the mongo query returned the correct result the filter on the list was returning the empty list.

Used the default resource id for filtering

#### PR fixes following issue(s)
Fixes https://github.com/appsmithorg/appsmith/issues/29917

#### Type of change
- Bug fix (non-breaking change which fixes an issue)

#### How Has This Been Tested?
- [ ] Manual
- [ ] JUnit

#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

## Summary by CodeRabbit

- **New Features**
	- Enhanced export functionality in git-connected applications to allow filtering by branch name.

### CODE REVIEW

**Review by rahulbarwal — COMMENTED** [review]
Don't we have any unit test changes with this?

**Comment by AnaghHegde** [comment]
@rahulbarwal Working on adding the tests for this

**Comment by laveena-en** [comment]
Tested and verified. PR looks good to me!

**Review by nayan-rafiq — APPROVED** [review]

**Pull request merged**
