### PR TITLE
fix: delete multiple apps feature ui updated

### LINKED ISSUE #28751: [Bug]: Update designs for multiple apps delete functionality
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

- Update the designs [Figma link](https://www.figma.com/file/he7KmzTW71QjdzygyxXtZO/%F0%9F%97%91%EF%B8%8F-Select%2FDelete-Multiple-Apps?type=design&node-id=7-5771&mode=design&t=Y9qE4906O4oLPUJu-4)
- Change the functionality for entering the delete multiple app mode from `cmd+click` to `checkbox click` (on hover and in selection mode)

### Steps To Reproduce

1. Go to `/applications` page
2. Try cmd + click on applications on the screen to enter multiple delete mode

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

Both

### PR DESCRIPTION
**Pull request by AmanAgarwal041**
## Description
- Updated the designs [Figma link](https://www.figma.com/file/he7KmzTW71QjdzygyxXtZO/%F0%9F%97%91%EF%B8%8F-Select%2FDelete-Multiple-Apps?type=design&node-id=7-5771&mode=design&t=Y9qE4906O4oLPUJu-4) for the delete multiple apps feature
- Changed the functionality for entering the delete multiple app mode from `cmd+click` to `checkbox selection`

Updated design
Screenshot 2024-01-09 at 2 00 50 AM

EE Pull request to handle the conflicting change : https://github.com/appsmithorg/appsmith-ee/pull/3348

#### PR fixes following issue(s)
Fixes #28751
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
- [ ] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

## Summary by CodeRabbit

- **New Features**
	- Added multiple selection functionality to application cards for batch operations.
	- Introduced new styling for multiple selection mode.

- **Enhancements**
	- Improved search experience with updated margin properties.
	- Enhanced button designs with new properties for kind, size, and icons.

- **Bug Fixes**
	- Fixed application deletion flow to ensure proper selection before deletion.

- **Testing**
	- Updated Cypress tests to align with the new multiple selection feature.
	- Added new Cypress methods for improved test reliability.
	- Included Cypress-real-events plugin for enhanced testing capabilities.

- **Refactor**
	- Streamlined import statements and removed unnecessary code.
	- Optimized width calculations for responsive design on various screens.

- **Chores**
	- Removed unused messaging call during application deletion process.

### CODE REVIEW

**Review by sneha122 — DISMISSED** [review]

**Comment by sneha122** [comment]
@AmanAgarwal041 Tested the PR for following cases:
1. Created multiple workspaces with multiple apps, on hover I could see the checkbox below the application card, on clicking the checkbox, it highlighted selected application and showed delete Apps CTA on top right, on clicking the CTA it deleted all selected Apps.
2. Checked in mobile view, on hover I could see the checkbox and perform the same steps to delete apps

Looks good to me!!

**Comment by carinanfonseca** [comment]
Context: On deleting an application, the toast message stays on for 10-15 seconds whereas the app gets deleted from UI instantly: https://ru2fwekpma.vmaker.com/record/Q8NRJDCLD4orfUWA. 

Can we remove the toast message since we are doing some work on Appsmith Home now? Thanks

**Pull request merged**
