### PR TITLE
chore: Address misc one click binding feedback

### PR DESCRIPTION
**Pull request by sbalaji1192**
## Description
Fixes miscellaneous feedback in the one-click binding feature.

 - Order of queries - show select queries on top and order by last executed query
 - Converting from JS to dropdown should be possible for the following cases
   - {{Query.data}}
-  Improve query names to be generated using the data table or collection we use
- undefined table data value should show an error on the property pane
-  Download option should be disabled when table is generated using one click binding
-  Remove the insert binding option from the dropdown

#### PR fixes following issue(s)
Fixes https://github.com/appsmithorg/appsmith/issues/24605
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
- [x] Manual
- [x] Jest
- [x] Cypress
>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by berzerkeer — DISMISSED** [review]

**Comment by laveena-en** [comment]
LGTM!
Tested and verified for:

- Order of queries - show select queries on top and order by last executed query
-  Converting from JS to dropdown should be possible for the following cases
{{Query.data}}
-  Improve query names to be generated using the data table or collection we use
-  undefined table data value should show an error on the property pane
-  Download option should be disabled when table is generated using one click binding
-  Remove the insert binding option from the dropdown

**Review by berzerkeer — DISMISSED** [review]

**Review by keyurparalkar — APPROVED** [review]

**Pull request merged**
