### PR TITLE
chore: Stub /features call in tests

### PR DESCRIPTION
**Pull request by hetunandu**
This change will stub the call to `users/features` to get the feature flags. By default it will return an empty list and rely on the client default flag list to enable/disable features

### CODE REVIEW

**Review by akash-codemonk — APPROVED** [review]

**Review by Aishwarya-U-R — APPROVED** [review]
Approving Cypress changes!

**Comment by Aishwarya-U-R** [comment]
@rahulbarwal - adding you as FYI - since you added the the fixtures that are removed now in this PR.

**Pull request merged**
