### PR TITLE
fix: showing invalid credentials message on  MongoDB test datasource if there is an unauthorized error

### LINKED ISSUE #11067: [Bug]: MongoDB datasource test shows ok when authentication is invalid
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When we have a MongoDB datasource that needs authentication, the test datasource button show ok even if we enter invalid credentials. This comes from the way that mongoPlugin `testDatasource()` is implemented and it ignores `Unauthorized` error when testing a datasource.

It's related to number 8 of this issue: https://github.com/appsmithorg/appsmith/issues/5005#issuecomment-1002032009

### Steps To Reproduce

1. Create a MongoDB datasource that needs authentication( user & password ).
2. In the **Authentication** section enter invalid credentials or leave them empty.
3. Hit the **Test** datasource button and it shows **OK** even that queries will not work.

### Environment

Release

### Version

Self-Hosted

### PR DESCRIPTION
**Pull request by mojtab23**
## Description

When calling test datasource on MongoDB if it encounters an unauthorized error plugin ignores that and shows a successful message. It's because in test datasource logic we call a query that tries to access the admin database of MongoDB, so it's possible to get an unauthorized error even if we have access to other user-defined databases. 
Now after this fix if it gets an unauthorized error accessing the admin database it will try to access the default database to make sure that credentials are valid or not.

Fixes #11067 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Tested manually with a MongoDB datasource that needed credentials accessing it.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by nidhi-nair — COMMENTED** [review]
@mojtab23 Will you be addressing the other scenarios in a separate PR?

**Comment by mojtab23** [comment]
> @mojtab23 Will you be addressing the other scenarios in a separate PR?

No, It's just addressing datasource test scenario, for other cases we need more information about the problem and desired behavior.

**Review by nidhi-nair — APPROVED** [review]

**Review by nidhi-nair — APPROVED** [review]

**Comment by nidhi-nair** [comment]
Merging in because we have different cases failing in each iteration, and they are all unrelated to the change.

**Pull request merged**
