### PR TITLE
fix: fixes google sheets datasource global search error

### LINKED ISSUE #15012: [Bug]: App crash on Quick search when we search with google data source name
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://www.loom.com/share/d56db7f420d745578b460dfe60e19499

### Steps To Reproduce

1. Create a new data source using Google sheet
2. Rename the sheet eg vivek
3. Now search with the same name vivek on quick search
4. Once you select the option vivek the app crashes

### Public Sample App

_No response_

### Version

Cloud

### LINKED ISSUE #15089: [Bug]:  Navigating to Gsheet Queries from global search leads user to empty page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Navigating to a Google sheets query from the global search redirects you to an empty page.

### Steps To Reproduce

1. Go to Global search 
2. Enter the name of any Google sheets query
3. Select the query and notice how you are redirected to an empty page.

### Public Sample App

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by Irongade**
When navigating to a google sheets datasource using the global search bar, the app crashes, this was caused due to an improperly placed return code written in the render method of the DatasourceEditorRouter.

Fixes #15012
Fixes #15089 

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
Manual, Cypress

## Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Aishwarya-U-R — APPROVED** [review]
Approving Cypress tests!

**Comment by Aishwarya-U-R** [comment]
@vivekverma2312 - Can you please verify bug #15012 in this PR's dp & add the Test Plan Approved if it looks Ok? Cypress test is added fine for the scenario.

**Comment by Irongade** [comment]
> @ade : Identified an Issue :
> 
> 1. Navigating to Gsheet Queries from global search leads user to empty page

This can be treated as a separate issue. @prapullac

**Review by AmanAgarwal041 — APPROVED** [review]

**Review by Aishwarya-U-R — APPROVED** [review]
Approving cypress test!

**Pull request merged**
