### PR TITLE
fix: remove duplicate case for context menu

### LINKED ISSUE #7951: (JS-0008) Duplicate case labels found in switch case
## Description
If a `switch` statement has duplicate test expressions in its `case` clauses, the clause may be repeated or mistyped. It ensures that the offending `case` clause is correct. We support Autofix for this issue. During Autofix, we remove the duplicate switch case (i.e., the second case) as all javascript engines …

## Occurrences
There is 1 occurrence of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/appsmithorg/appsmith/issue/JS-0008/occurrences/](https://deepsource.io/gh/appsmithorg/appsmith/issue/JS-0008/occurrences/)

### PR DESCRIPTION
**Pull request by aayushbisen**
## Description

Removed duplicate case for context-menu in `Icon.tsx`

Fixes #7951

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by sbalaji1192 — APPROVED** [review]
LGTM

**Comment by sbalaji1192** [comment]
@Rishabh-Rathod IIRC, we were not able to merge due to the github workflow.let me reopen and merge it.

**Comment by sbalaji1192** [comment]
@aayushbisen Could you resolve conflicts?

**Comment by aayushbisen** [comment]
> @aayushbisen Could you resolve conflicts?

Yeah sure.

**Comment by mohanarpit** [comment]
Closing as this has been resolved as part of the redesign project. The issue no longer exists.

**Pull request closed without merging**
