### PR TITLE
fix: calculateHoverColor typo

### PR DESCRIPTION
**Pull request by torcoste**
## Description
Renaming the widget utility function `calulateHoverColor` to `calculateHoverColor`.
Reason: typo

Fixes: 
#28473

#### Type of change
- Chore (housekeeping or task changes that don't impact user perception)

#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by dhruvikn — APPROVED** [review]

**Comment by somangshu** [comment]
@dhruvikn can you link a relevant issue to this?

**Comment by dhruvikn** [comment]
> @dhruvikn can you link a relevant issue to this?

@somangshu - there is no issue created for this. I think @torcoste just saw this in our code and fixed it.

**Comment by somangshu** [comment]
Should we create a task to link with?

**Comment by dhruvikn** [comment]
Have created the issue here - https://github.com/appsmithorg/appsmith/issues/28473

@somangshu - CI has passed and I don't think we need QA for this change. I have tested it on the DP generated and have done the code review. Can we please force-merge this then?

**Pull request merged**
