### PR TITLE
fix: NPE when application has no page

### LINKED ISSUE #10779: Return page slugs in response of applications list API
The FE calls `GET /api/applications/new` API to get list of organizations and applications. Currently the list of pages inside each application object does not have slugs. We need page slugs to generate the link of an application.

When user clicks on a application, we'll redirect them to this page: `/apps/application-slug/page/page-slug/pageid` where page-slug and pageid are from the default page. Hence we need page slug to generate this URL.

### PR DESCRIPTION
**Pull request by nayan-rafiq**
## Description

This PR fixes a NPE when application has no page or page are missing.

Fixes #10779

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manually

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by sharat87 — APPROVED** [review]

**Comment by nayan-rafiq** [comment]
> @nayan-rafiq Can you help me understand the bug & the fix better? Why would an application not have any pages in it? Wouldn't that become an invalid application?

Home page was not loading for @sharat87 in release because there was an app that has no page in `newPage`. It seemed that this app was created by cypress quite a long time ago. As this somehow happened, we suspect this may happen for other users also. That's why we added a check to make sure list of pages is not null. 

You are right, the app will be an invalid one.

**Pull request merged**
