### PR TITLE
Accept PUT requests for thread updates

### PR DESCRIPTION
**Pull request by sharat87**
We were using PATCH, because that was semantically more correct for what we are doing here. But since PUT is used everywhere else in the project, changing this to PUT for consistency.

### CODE REVIEW

**Comment by nidhi-nair** [comment]
No! Why! :(

**Comment by sharat87** [comment]
@nidhi-nair, because consistency trumps correctness. Either we changes this to `PUT`, or we change everything else to `PATCH`. 🍰

**Comment by nidhi-nair** [comment]
I agree, but I'm sad. 😞

**Comment by sharat87** [comment]
For the record, I'm not happy with this either. 😀

**Review by nidhi-nair — APPROVED** [review]

**Pull request merged**
