### PR TITLE
fix: set the min width to allow all content to load with a scroll 

### LINKED ISSUE #24520: [Bug]: Onboarding form page elements are not resized on browser resizing
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Resize the onboarding form. 
Unable to see the form fields completely on horizontal scrolling 
 
vertical_Scroll_components_resizing_bug

### Steps To Reproduce

1. Go to onboarding page 
2. Resize 
3. scroll horizontal

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

Self hosted

### PR DESCRIPTION
**Pull request by dipyamanbiswas07**
## Description

Fixes an issue with the welcome screen not loading the complete form if the browser was resized to a very small size.

#### PR fixes following issue(s)
Fixes #24520 
#### Media
image

- Bug fix (non-breaking change which fixes an issue)

>
>
- [x] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Comment by dipyamanbiswas07** [comment]
@sharanya-appsmith could you take a look at the DP and see if the fix is working fine?

**Review by ankitakinger — APPROVED** [review]

**Comment by dipyamanbiswas07** [comment]
@dipyamanbiswas07 test

**Pull request merged**
