### PR TITLE
fix: Checkbox group widget fails to display the updated values 

### LINKED ISSUE #19474: [Bug]: Checkbox group widget fails to display the updated values
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Even though the evaluated value of default selected values changes, the Checkbox group fails to update the state of options.

You can go back and forth between page 1 & 2 and you'll see the issue in the shared sample app.

### Steps To Reproduce

1. Add a checkbox group
2. Create fetch query using user data
3. Add checkbox options as - label: username, value: ids
4. Create a new query using user data and only fetch the first two rows. Create a default value array out of it and assign to the checkbox group.

### Public Sample App

https://app.appsmith.com/app/checkbox-group/page1-63b522bd0bc0a80b3001a30c

### Issue video log

_No response_

### Version

v1.8.16

### PR DESCRIPTION
**Pull request by jsartisan**
## Description

In the issue report by the user the component was not checked values for defaultSelectedValues. That was because we had componentDidUpdate which was checking the change in the options property. If there was a change, it was setting the selectedValues. We found out that this check is not required. Because of this check only, the component was re-rendering, and sometimes it was unchecking all the checked values. So we just removed the check and added the cypress check.

Fixes #19474

## Type of change
- Bug fix 

## How Has This Been Tested?
- Cypress

### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [x] Test plan has been approved by relevant developers
- [x] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by ashit-rath — COMMENTED** [review]
@jsartisan Can you explain what was the problem and how removing a bunch code is fixing that issue?

**Comment by jsartisan** [comment]
@ashit In the issue report by the user the component was not checked values for defaultSelectedValues. That was because we had `componentDidUpdate` which was checking the change in the `options` property. If there was a change, it was setting the `selectedValues`. We found out that this check is not required. Because of this check only, the component was re-rendering, and sometimes it was unchecking all the checked values. So we just removed the check and added the cypress check.

**Review by ashit-rath — DISMISSED** [review]

**Comment by chandannkumar** [comment]
Tested this PR and LGTM

**Review by dhruvikn — APPROVED** [review]

**Pull request merged**
