### PR TITLE
fix: removed -1 and 2d array population error in the selectedRowIndices

### LINKED ISSUE #9109: [Bug]: -1 or a 2d array is shown in selectedRowIndices
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When in multi-select mode in the Table Widget, the `selectedRowIndices` has `-1` in the array. When selecting rows, the -1 entry still exists.

We need to remove -1 from the list of `selectedRowIndices`

### Steps To Reproduce

1. Add a Table
2. Bind a text widget with `{{Table1.selectedRowIndices}}`
3. See -1 as the value
4. Enable multi-select in the table.
5. The array in the text widget shows `[-1]`

Screenshot 2021-11-11 at 11 48 35 AM

To reproduce the above error, the user needs to enable the enable multi-row select option. Then change the value of the default selected row. Now if the user disables the enable multi-row select and re-enable it then we get a 2d array.

Screenshot 2021-12-07 at 14 54 29

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by keyurparalkar**
> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Description

This PR fixes following issues:

- `-1` was populating inside `selectedRowIndices`. This is fixed by adding a validation of in the property pane of default selected row.
- During the above fix I found out one bug which causes the `selectedRowIndices` to populate with the an array with previous value of `selectedRowIndices`. Thus this leads to a 2d array e.g. [[1]]. To reproduce the above error, the user needs to enable the `enable multi row select` option. Then change the value of `default selected row`. Now if the user disables the `enable multi row select` and re-enable it then we get a 2d array. 3
Please find below video for reference:

https://user-images.githubusercontent.com/14138515/145007503-cb55e88a-6bfd-4349-a98f-3dce57a59c10.mp4

Fixes #9109 

> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Added cypress test named: `table_with_text_no_2dArray_spec.js` for testing if the `selectedRowIndices` does not consists of 2d array.
- Added cypress test named: `table_with_text_selRowIndices_spec.js` for testing if the `selectedRowIndices` does not contain -1.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/fix-selectedRowIndices_neg_value 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 55.13 **(0)** | 37.05 **(0)** | 34.03 **(0.01)** | 55.66 **(0.01)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.71 **(-0.23)** | 40.83 **(-0.84)** | 36.21 **(0)** | 56.74 **(-0.25)**
 :red_circle: | app/client/src/widgets/TableWidget/widget/index.tsx | 29.64 **(0)** | 9.66 **(-0.03)** | 29.41 **(0)** | 29.29 **(0)**
 :green_circle: | app/client/src/widgets/TableWidget/widget/propertyUtils.ts | 28.57 **(4.14)** | 10.78 **(2.78)** | 26.67 **(6.67)** | 27.42 **(4.47)**</details>

### CODE REVIEW

**Review by Tooluloope — DISMISSED** [review]
LGTM.
@keyurparalkar could you help add selectedRowIndices to the list.
I noticed it doesn't show normally

Screenshot 2021-12-07 at 15 03 27

**Comment by keyurparalkar** [comment]
> LGTM. @keyurparalkar could you help add selectedRowIndices to the list. I noticed it doesn't show normally
> 
> Screenshot 2021-12-07 at 15 03 27

@Tooluloope, I have added `selectedRowIndices` as an option in the autocomplete list. 
Screenshot 2021-12-10 at 11 24 08 AM

**Review by Tooluloope — APPROVED** [review]

**Comment by shwetha-ramesh** [comment]
@keyurparalkar Tested this PR for both the conditions. Working as expected on DP. Now ```selectedRowIndices``` is added as an option in the autocomplete list. 

**Moving to Done.**

**Review by Tooluloope — APPROVED** [review]

**Pull request merged**
