### PR TITLE
fix: Resolve issues related to disconnect git repo flow 

### PR DESCRIPTION
**Pull request by abhvsn**
## Description

> While disconnecting the repo because of the remote branches server was throwing NPE as the remote branches are not present in local

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Manual test
> JUnit TC update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by AnaghHegde — DISMISSED** [review]

**Review by AnaghHegde — DISMISSED** [review]

**Comment by AnaghHegde** [comment]
@abhvsn The changes for the disconnect flow is present in PR 9800. Do we need this PR as well ?

**Comment by abhvsn** [comment]
> @abhvsn The changes for the disconnect flow is present in PR 9800. Do we need this PR as well ?

Hey I guess we can still keep these separate PRs as the aim is different. 9800 is just the enhancement so this can wait but current PR deals with the fix so I guess lets have them separate and test this first in release

**Review by AnaghHegde — APPROVED** [review]

**Pull request merged**
