### PR TITLE
fix: firestore pagination issue

### PR DESCRIPTION
**Pull request by rishabhrathod01**
## Description

As per the documentation the where clause must always come before the order by clause, and the startAfter clause must come after the order by clause i.e the recommended order : `where clause --> order by --> start after`. However, the way code was written it applies the where clause after the startAfter i.e as per the code : `order by --> start after --> where clause` .

In this PR, we change the logic to make sure we follow the order `where clause -> order by and startAfter / endBefore` when generating query. 

Fixes https://github.com/appsmithorg/appsmith/issues/32604

documentation link. - https://firebase.google.com/docs/firestore/query-data/query-cursors 

Changes were taken from the PR created by @sumitsum here https://github.com/appsmithorg/appsmith-ee/pull/4001

## Automation

/ok-to-test tags="@tag.Datasource"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/8814737910>
> Commit: 4c7ed97cc1808a537d40682fc0e930cd0e30be70
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=8814737910&attempt=1" target="_blank">Click here!</a>

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [x] No

## Summary by CodeRabbit

- **Refactor**
	- Improved the order of operations in Firestore queries to enhance query performance and reliability.

### CODE REVIEW

**Review by NilanshBansal — COMMENTED** [review]
@rishabhrathod01 the changes LGTM. 
Can we also please assert this in a test case?

**Comment by NilanshBansal** [comment]
Tested the functionality on dp, and everything looks good except for the test cases.

**Comment by rishabhrathod01** [comment]
Unit test will be added in the upcoming PR. We can goahead with the change here.

**Comment by NilanshBansal** [comment]
> Unit test will be added in the upcoming PR. We can goahead with the change here.

@rishabhrathod01 since this initially originated from an a-force query and it is a production issue, we can go ahead with the fix and raise a separate PR for test cases.

**Review by NilanshBansal — APPROVED** [review]

**Pull request merged**
