### PR TITLE
fix: autocomplete fixes & enhancement

### LINKED ISSUE #13613: [Bug]-[168]:Document viewer widget does not appear on autocomplete suggestion
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Document viewer widget does not appear on autocomplete suggestion

### Steps To Reproduce

1. Drag and drop a document viewer widget on canvas
2. Drop a text widget and attempt to bind properties of document viewer widget - observe autocomplete does not suggest this widget even if the widget has been renamed

https://www.loom.com/share/07a868bd87134f3a8418a74713839ff5

### Public Sample App

_No response_

### Version

Cloud

### LINKED ISSUE #15568: [Bug]: No autocompletion hint for supported Browser APIs
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In the editor today, there are certain web APIs like console, navigator, crypto, e.t.c. which are supported but do not have hints.

Relevant link - [A list of all browser API defs ](https://github.com/ternjs/tern/blob/master/defs/browser.json).

### Steps To Reproduce

1. Open any code editor field and type "console."
2. Notice that there is no hint available.

### Public Sample App

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by Rishabh-Rathod**
## Description

- Add Auto-completion for Document viewer widget
- Add Auto-completion for complex objects making array of object autocompletion work.
- Add Auto-completion statement to get a code snippet for loops, conditions and so on.

Fixes #15568
Fixes #13613

## Type
- Bug fix (non-breaking change which fixes an issue)
- Enhancement

### Cypress test
- [x] Document viewer widget autocompletion test
- [x] complex local variable autocompletion test
- [x] Api data response autocompletion test
- [x] https://github.com/appsmithorg/TestSmith/issues/2022 
Autocompletion test for code snippets ( Not added as cypress test due to complexity to calculate indentation for each case )
- [x] https://github.com/appsmithorg/TestSmith/issues/2020
- [x] https://github.com/appsmithorg/TestSmith/issues/2021

## Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by ramsaptami** [comment]
Edge case where `this.` suggests own function
image

**Comment by Rishabh-Rathod** [comment]
> Edge case where `this.` suggests own function image

This issue if fixed in this PR now. @ramsaptami

**Comment by ramsaptami** [comment]
We have 2 suggestions that come up after impletmenting this PR, is this how VS handles it as well? @Rishabh-Rathod 
image

**Comment by ramsaptami** [comment]
DP testing has been completed for all scenarios mentioned in the issue description

**Comment by Rishabh-Rathod** [comment]
@ohansFavour will be reviewing the PR. Updating the reviewer list to avoid duplicate effort.

**Review by ohansFavour — APPROVED** [review]

**Review by ohansFavour — APPROVED** [review]

**Pull request merged**
