### PR TITLE
fix: Renaming new JS Object not working instantly

### LINKED ISSUE #29482: [Bug]: Renaming new JS Object not working instantly
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Creating a new JS object for custom code works fine but after creation if I try to rename this new object from default name (JSObject1), it doesn't work instantly. It shows some error popup which is confusing too with text `<js_object_name> is already being used or is a restricted keyword`

Refreshing the page however solves this problem and renaming takes effect immediately.

### Steps To Reproduce

1. Open any AppSmith Page.
2. Try to create New JS Object.
3. New JS Object is created with name JSObject1.
4. Try to rename it for better readability as per choice.
5. Error is shown to restrict the renaming.
6. Refresh the page, renamed JS Object appears fine.

Attached screen recording to understand the steps.

### Public Sample App

_No response_

### Environment

Production

### Issue video log

https://www.loom.com/share/079c300282d84574a6bf0e827dc73b62?sid=441feb86-f0a6-4355-98fc-967929d20729

### Version

v1.9.50

### PR DESCRIPTION
**Pull request by vaibhavchobisa**
## Description
This PR fixes the issue of the error tooltip appearing every time on saving a new 'JS Object name' even though it is neither a restricted keyword nor already in use.

#### PR fixes following issue(s)
Fixes #29482 

#### Type of change
- Bug fix (non-breaking change which fixes an issue)

#### How Has This Been Tested?
- [x] Manual
- [ ] Jest
- [ ] Cypress

#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

## Summary by CodeRabbit

- **New Features**
  - Enhanced error handling in text editing with user-friendly error messages.

### CODE REVIEW

**Review by arunvjn — APPROVED** [review]
Looks good!

**Comment by arunvjn** [comment]
@vaibhavchobisa Just came across this issue on the DP. Please follow these steps to replicate it
- Create 2 JSObjects
- Edit a JSObject1 to a reserved keyword and make sure the error tooltip shows up.
- Now switch to a different JSObject2. 
Observe that the tooltip remains.

You would need to clear the errorMessage and error from state in such scenarios.

**Comment by vaibhavchobisa** [comment]
Good observation @arunvjn. I will push its fix to the PR as well. Thanks!

**Comment by vaibhavchobisa** [comment]
@arunvjn I have just pushed the new fix, can you please review again?

**Review by arunvjn — APPROVED** [review]

**Pull request merged**
