### PR TITLE
fix: response table misalignment

### LINKED ISSUE #13406: [Bug]-[30000]:Query Response screen table misaligned when screen height increased
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I increase the height of the query response screen for say a postgresql query, the last column border of the table in the response page is not aligned correctly.

### Steps To Reproduce

1. Create a datasource for any PostGreSql DB. Get credentials from: https://www.notion.so/Servers-and-Credentials-665f00d9505745d59db4f3b4eda27c79#cd6a1610a7e84073b0491cd2c020de4e
2. 
Screenshot 2022-04-28 at 1 01 26 PM

3. Create a simple query: SELECT  gender, latitude, longitude FROM users ORDER BY id LIMIT 10;
4. Run it. When the mouse pointer turns to a divider above the Response / Errors tabs, drag the bottom screen to close the query, right below the query name. 
5. The last column table border is not aligned correctly.
query_response_tablealignment

### Public Sample App

_No response_

### Version

Release

### PR DESCRIPTION
**Pull request by sneha122**
## Description

When creating and executing a query for postgres datasource, Query Response screen table misaligned when screen height increased, The issue occurred because when we increase height of table response, scroll bar disappears and creates misalignment. 

Fixes #13406

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- cypress test

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by ayushpahwa — APPROVED** [review]
Looks good! Just a small thing, can you please add some comments to the newly added functions? Thanks!

**Comment by sneha122** [comment]
> Looks good! Just a small thing, can you please add some comments to the newly added functions? Thanks!

Yes will do. Thanks @ayushpahwa

**Review by ayushpahwa — APPROVED** [review]

**Pull request merged**
