### PR TITLE
fix: throttle git status api

### LINKED ISSUE #11551: [Bug]-[660]:Avoid un-necessary status API call for git connected application for better performance
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When we open the git connected application in edit mode, on the first load we make the status API call(which is heavy in nature, avg is 4 sec RTT) to get information like uncommitted changes, remote status etc. But suppose say even before this API call is not completed and if you click on the commit button you can observe that another call is triggered to the same API. 

The same happens when we switch between commit and merge tab in git sync modal.

image

### Steps To Reproduce

When we open the git connected application in edit mode, on the first load we make the status API call(which is heavy in nature, avg is 4 sec RTT) to get information like uncommitted changes, remote status etc. But suppose say even before this API call is not completed and if you click on the commit button you can observe that another call is triggered to the same API. 

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by IAmAnubhavSaini**
## Description

Throttling git status API eases burden on server.

Fixes #11551 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by ankitakinger — DISMISSED** [review]

**Comment by IAmAnubhavSaini** [comment]
### Bug

https://user-images.githubusercontent.com/1573771/174240719-c88537d5-472a-4701-9e62-247984c370ec.mov

### Fix

https://user-images.githubusercontent.com/1573771/174240756-4ad1175f-e58b-4f2f-b20e-c196283ef82e.mov

**Review by ankitakinger — APPROVED** [review]

**Comment by IAmAnubhavSaini** [comment]
Screenshot 2022-07-01 at 10 08 48 AM

**Comment by IAmAnubhavSaini** [comment]
Finally, all tests pass.

Screenshot 2022-07-03 at 9 48 29 AM

**Pull request merged**
