### PR TITLE
feat: Update commit push flow when there are upstream changes in remote repo

### LINKED ISSUE #13256: [Task]: Improve the UX for commit and push flow when there are upstream changes alongwith the local changes
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Desctiption

As we don't have a separate CTA for commit and push we need to think through the scenario when user have local as well as upstream changes. This is because in the current flow commit succeeds but push fails to maintain the git history.

### PR DESCRIPTION
**Pull request by abhvsn**
## Description

As we don't have a separate CTA for commit and push, this flow breaks when user have local as well as upstream changes. This is because in the current flow commit succeeds but push fails to maintain the git history. This is not a expected UX as Appsmith should intelligently detect if there are any remote changes and update the flow. Current PR assumes the optimistic approach as follows:
1. Client requests to commit local changes and sync with remote
2. Server commits the local changes
3. Server tries to make a push
  a. Push goes through as there are no remote commits  
  b. Push fails because of upstream changes
    - Pull remote no merge conflicts: make merge commit to sync with remote
    - Pull remote ends up in merge conflicts: Throw an exception to let the client know to execute sequential steps  
More discussion on this issue: https://theappsmith.slack.com/archives/C02K2MZERSL/p1650876597888719

https://www.notion.so/appsmith/Modified-commit-push-flow-aa20c9f46c2a46b1ad15ea1ef5339e16

Fixes #13256

## Type of change

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

## How Has This Been Tested?

> JUnit testcase
> Manual testing

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by AnaghHegde — APPROVED** [review]

**Comment by abhvsn** [comment]
Closing this as not required as this is open for a long time.

**Pull request closed without merging**
