### PR TITLE
fix: unread indicator behaviour

### LINKED ISSUE #8289: Bug: Unread comments indicator is shown even if there are no unread comments

### PR DESCRIPTION
**Pull request by pranavkanade**
## Description
- Unread comments indicator will be shown to the user if store actually has unread comment or user has not completed their comments on boarding

Fixes #8289 

> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- automated tests

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/comment-notification-indicator 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 54.89 **(0)** | 36.57 **(0.03)** | 33.76 **(0.01)** | 55.44 **(0)**
 :red_circle: | app/client/src/actions/commentActions.ts | 79.29 **(-0.58)** | 100 **(0)** | 42.22 **(-1.53)** | 79.45 **(-0.81)**
 :red_circle: | app/client/src/comments/AppComments/AppCommentThreads.tsx | 60.47 **(-0.89)** | 22.73 **(0)** | 40 **(0)** | 59.52 **(-0.95)**
 :red_circle: | app/client/src/comments/CommentCard/CommentCard.tsx | 71.98 **(0)** | 57.25 **(-1.81)** | 44.19 **(0)** | 72.35 **(0)**
 :green_circle: | app/client/src/comments/CommentThread/CommentThread.tsx | 95.52 **(0)** | 65.42 **(0.77)** | 85.71 **(0)** | 98.41 **(0)**
 :green_circle: | app/client/src/comments/inlineComments/InlineCommentPin.tsx | 87.36 **(-1.15)** | 75.76 **(5.07)** | 94.44 **(0)** | 88.75 **(-1.25)**
 :green_circle: | app/client/src/components/ads/Icon.tsx | 50.95 **(0.54)** | 33.99 **(0.66)** | 100 **(0)** | 50.82 **(0.55)**
 :green_circle: | app/client/src/pages/Editor/ToggleModeButton.tsx | 78.03 **(1.27)** | 55.84 **(4.45)** | 80 **(3.33)** | 76.03 **(0.46)**
 :red_circle: | app/client/src/reducers/uiReducers/commentsReducer/commentsReducer.ts | 56.25 **(-0.54)** | 50 **(0)** | 50 **(-1.52)** | 61.43 **(-0.54)**
 :red_circle: | app/client/src/reducers/uiReducers/commentsReducer/handleNewCommentThreadEvent.ts | 85.71 **(-0.96)** | 75 **(0)** | 100 **(0)** | 85.71 **(-0.96)**
 :red_circle: | app/client/src/reducers/uiReducers/commentsReducer/handleUpdateCommentThreadEvent.ts | 78.57 **(-21.43)** | 33.33 **(-37.72)** | 100 **(0)** | 78.57 **(-21.43)**
 :green_circle: | app/client/src/reducers/uiReducers/commentsReducer/handleUpdateCommentThreadSuccess.ts | 100 **(6.67)** | 100 **(40)** | 100 **(0)** | 100 **(7.14)**
 :red_circle: | app/client/src/sagas/ApplicationSagas.tsx | 17.43 **(-0.68)** | 3.61 **(-3.29)** | 8 **(0)** | 20.3 **(-0.78)**
 :red_circle: | app/client/src/sagas/CommentSagas/index.ts | 45.59 **(-3.04)** | 17.14 **(-3.37)** | 50 **(-5)** | 45.19 **(-3.48)**
 :green_circle: | app/client/src/sagas/WebsocketSagas/handleAppLevelSocketEvents.ts | 17.95 **(1.59)** | 0 **(0)** | 0 **(0)** | 18.42 **(1.11)**
 :green_circle: | app/client/src/selectors/commentsSelectors.ts | 85.25 **(7.02)** | 63.24 **(8.83)** | 76.67 **(6.67)** | 88.24 **(4.15)**</details>

### CODE REVIEW

**Comment by pranavkanade** [comment]
@rishabhsaxena 
> If the thread is marked as read when resolved, viewedByUsers won’t be populated with all the users, instead it’s viewedBy field is set

Hey along with `viewedByUsers` we are also looking at `resolved` state to figure out if we should show indicator.
```
const isThreadFromEventViewed = thread?.viewedByUsers?.includes(currentUser?.username)
isViewed: isThreadFromEventViewed || thread?.resolvedState?.active;
```

**Comment by rishabhsaxena** [comment]
@pranavkanade
Yeah that's a great point! Should we instead rely on the get unread count API instead then, that seems more foolproof across all cases?

**Pull request merged**
