### PR TITLE
fix: Spaces are not allowed on widgets children names (tabs, menus, buttons etc.)

### LINKED ISSUE #9443: [Bug]: Spaces are not allowed on widgets children names (tabs, menus, buttons etc.)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

User cannot use space in tab widget naming. Space can only be included as an afterthought.

[LOOM DEMO](https://www.loom.com/share/9485d1bd690b4c9f99855fffd57fdd45)

### Steps To Reproduce

1. Go to tab widget and try to name it First Tab. Since space isn't allowed, type FirstTab and then try to add in a space after typing out the entire name and observe that this is possible.

### Environment

Release

### Version

Cloud

### PR DESCRIPTION
**Pull request by wmdev0808**
## Description
User cannot use space in tab widget naming. Space can only be included as an afterthought.

Fixes #9443 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Test A
- Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/9443-spaces-not-allowed-on-widget-children-names 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 55.03 **(0)** | 36.56 **(-0.01)** | 34.94 **(0)** | 55.44 **(-0.01)**
 :red_circle: | app/client/src/selectors/commentsSelectors.ts | 83.61 **(-1.64)** | 61.76 **(-2.95)** | 73.33 **(0)** | 88.24 **(-2.35)**</details>

### CODE REVIEW

**Review by somangshu — APPROVED** [review]
Change looks good to me. @vivekverma2312 kindly test this well to see if anything from before breaks or any edge cases are getting introduced

**Comment by somangshu** [comment]
@marks0351 tagging you for second opinion

**Comment by marks0351** [comment]
@haojin111 this PR is being worked on to add changes to set trimValue to false for text input component from ads, it looks like trimValue is declared to be true when not present, wanted to understand why that was done. 
https://github.com/appsmithorg/appsmith/blob/release/app/client/src/components/ads/TextInput.tsx#L297
I think it should be false by default allowing normal text input behaviour to take place.

**Comment by marks0351** [comment]
@wmdev0808 @haojin111 irrespective of the fix can we pls add a test case as well.

**Comment by shwetha-ramesh** [comment]
@wmdev0808 Tested this PR and verified able to add spaces in Table, Tab, MenuButton, GroupButton widgets.

However one issue observed below.
1. When a long name is added in default column an ellipsis gets added after a character count of 4, which is seen missing in this DP.
image

https://loom.com/share/726841833dd745589b7281ab72925423

**Suggestion**

@somangshu  For _MenuButton_ widget when a long Menu item is added an ellipsis is added at the end and on hover the whole item name is displayed there by maintaining the drop down to the width of the widget which looks neat. Whereas in _ButtonGroup_ widget when the button type are of Menu, the items with long name do not have a ellipsis and overflows from the widget which doesn't look crisp. Suggest same can be followed as MenuButton widget 

image
image

**Comment by shwetha-ramesh** [comment]
> @wmdev0808 Tested this PR and verified able to add spaces in Table, Tab, MenuButton, GroupButton widgets.
> 
> However one issue observed below.
> 
> 1. When a long name is added in default column an ellipsis gets added after a character count of 4, which is seen missing in this DP.
>    image
> 
> https://loom.com/share/726841833dd745589b7281ab72925423

Sorry, I see #10666 has a fix for this issue. Moving this to DONE.

**Review by marks0351 — CHANGES_REQUESTED** [review]
@wmdev0808 @haojin111 cud u pls check the review comments.

**Comment by wmdev0808** [comment]
> @wmdev0808 @haojin111 irrespective of the fix can we pls add a test case as well.

@marks0351 , could you be more specific for the above?
I am not sure what kind of test and where should I write a test case

**Comment by marks0351** [comment]
@wmdev0808 can u add a test case to ensure space trimming doesn't work by default.

**Comment by wmdev0808** [comment]
> @wmdev0808 can u add a test case to ensure space trimming doesn't work by default.

In the current PR, the issue somehow has fixed, how can I write the test case?

**Review by marks0351 — APPROVED** [review]

**Pull request merged**
