### PR TITLE
fix: Email domain hash in analytics event

### PR DESCRIPTION
**Pull request by abhvsn**
## Description
We are solving 2 problems with this PR:
1. For `Installation Setup Complete` event email domain hash was incorrect and earlier we were hashing the instanceId which means if user with same email tries to run 2 different instances hash was different.
2. `IP` is a reserved keyword for tracking events in Mixpanel though this is allowed in Segment. Instead of showing the ip as is, Mixpanel provides derived property. As we want derived props alongwith the ip address we are sharing the IP address in separate keys.
Ref: https://help.mixpanel.com/hc/en-us/articles/360001355266-Event-Properties

#### PR fixes following issue(s)
Fixes https://github.com/appsmithorg/cloud-services/issues/675

#### Type of change
- Bug fix (non-breaking change which fixes an issue)

#### How Has This Been Tested?
- [x] Manual

#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Comment by abhvsn** [comment]
Event details when user subscribes for marketing emails:
```
Event track call:
Analytics.track("645a17bb22b3c708bd470bbe", "Installation Setup Complete", new Props()
    .put("disable-telemetry", false)
    .put("email", "abhijeet+1@appsmith.com")
    .put("emailDomainHash", "eb93d881805376ef5297d8ac6fe95970f47d7bbd8d849b3a0d9c7af188caf648")
    .put("goal", "personal project")
    .put("instanceId", "645a17bb22b3c708bd470bbe")
    .put("ip", "103.208.71.156")
    .put("ipAddress", "103.208.71.156")
    .put("name", "Abhijeet")
    .put("originService", "appsmith-server")
    .put("role", "non technical")
    .put("subscribe-marketing", true)
    .put("version", "UNKNOWN"));

Identify call:
Analytics.identify("645a17bb22b3c708bd470bbe", new Traits()
    .put("email", "abhijeet+1@appsmith.com")
    .put("goal", "personal project")
    .put("ip", "103.208.71.156")
    .put("ipAddress", "103.208.71.156")
    .put("isInstance", true)
    .put("name", "Abhijeet")
    .put("role", "non technical"));
```

When user disables the marketing emails:
```
Event track call:
Analytics.track("645a186c6008b3474f889d5d", "Installation Setup Complete", new Props()
    .put("disable-telemetry", true)
    .put("email", "")
    .put("emailDomainHash", "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855")
    .put("goal", "work project")
    .put("instanceId", "645a186c6008b3474f889d5d")
    .put("ip", "103.208.71.156")
    .put("ipAddress", "103.208.71.156")
    .put("name", "")
    .put("originService", "appsmith-server")
    .put("role", "backend engineer")
    .put("subscribe-marketing", false)
    .put("version", "UNKNOWN"));

Identify call:
Analytics.identify("645a186c6008b3474f889d5d", new Traits()
    .put("email", "")
    .put("goal", "work project")
    .put("ip", "103.208.71.156")
    .put("ipAddress", "103.208.71.156")
    .put("isInstance", true)
    .put("name", "")
    .put("role", "backend engineer"));
```

**Review by sharat87 — APPROVED** [review]

**Comment by Aishwarya-U-R** [comment]
@abhvsn -Merge latest release & trigger new oktotest. Cancelling the re-run since its past 12 hours from initial attempt.

**Pull request merged**
