### PR TITLE
Return hint message on identical columns

### LINKED ISSUE #1438: [Bug] When I create large joins, the fields of the 3rd table and on do not show up (and other quirks)
## Description

select * from x,y where x.id=y.xid;

shows only content from x in the resulting table. 

select x.id, x.name, x...., y.id,y.name,y.... etc

works fine, however; 

select x.id, x.name, x...., y.id,y.name,y....,z.id,z.name,z.... from x,y,z where ..join them

shows no values from z, also if you rearrange them; 

select x.name,z.street,y.cheese from x,y,z 

it shows name and cheese but not street. 

### Steps to reproduce the behaviour:

Just create larger joins and click Run + Add Widget. 

This might be partially related to the width / css bugs in the table, but not completely/in all cases ; the fields are simply not there. 

### Important Details
- Self hosted, installed 1 day ago (where do I find the version)? 
- Linux/Ubuntu

There are no relevant errors in logs as far as I saw (only some synching errors which pop up but not during testing of any of these features) (either chrome or server).

### PR DESCRIPTION
**Pull request by sumitsum**
## Description
- Return hint message if identical column names are found in SQL query for postgres, MySQL, mssql, redshift plugin.
- Add a PluginUtils class to hold general utility functions for plugins.

Fixes #1438

## Type of change
- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

## How Has This Been Tested?
- Added TCs.
- Manual
{"responseMeta":{"status":200,"success":true},"data":{"body":[{"id":71,"name":71},{"id":211,"name":211},{"id":40,"name":40},{"id":9,"name":9},{"id":18,"name":18}],"isExecutionSuccess":true,`"messages":["Your PostgreSQL query result may not have all the columns because duplicate column names were found for the column(s): name, id. You may use the SQL keyword 'as' to rename the duplicate column name(s) and resolve this issue."]`,"request":{"query":"select id, id, id as name, id as name from orders limit 5;","properties":{"preparedStatement":false}}}}

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by trishaanand** [comment]
QQ : Arent the column names already being read while parsing through the result? Could we reuse the column name being read? Also, if we find another column name by a name already found, could we rename the duplicate column to a new name and in the hint message let the user know? Also, mention the alias as a way to rename the column in the SQL
@mohanarpit : Would the above solution work?

**Comment by mohanarpit** [comment]
> QQ : Arent the column names already being read while parsing through the result? Could we reuse the column name being read? Also, if we find another column name by a name already found, could we rename the duplicate column to a new name and in the hint message let the user know? Also, mention the alias as a way to rename the column in the SQL
> @mohanarpit : Would the above solution work?

I'm on the fence on renaming the columns because we are manipulating the data that the user returned. But it's not a solution I'm against. For example, we could have `user_id` and `user_id_1` columns. But we need to be careful when doing this transformation that we feed the right data into the right column. If we can achieve that reliably, this is something we can do. 
Apart from that, we should display the hint message and let users know:
1. Which column was duplicate
2. The usage of alias to rename the column name differently to see correct data

 This will go a long way in building trust in the platform.

**Comment by nidhi-nair** [comment]
This is how we're doing it for Sheets as well. Something that's troubling me about that implementation is how we'd handle updates. Do we start using Appsmith columns for them?

**Comment by sumitsum** [comment]
> QQ : Arent the column names already being read while parsing through the result? Could we reuse the column name being read? Also, if we find another column name by a name already found, could we rename the duplicate column to a new name and in the hint message let the user know? Also, mention the alias as a way to rename the column in the SQL
> @mohanarpit : Would the above solution work?

Hi @trishaanand , regarding reading the column during parsing the results - it would lead to code duplication across the three plugins - postgres, redshfit, and mssql - and any other jdbc based plugin that we add in future. Apart from this I see both the implementations as equivalent. Please tell me whichever implementation is preferred, I will modify it accordingly.

**Comment by trishaanand** [comment]
> > QQ : Arent the column names already being read while parsing through the result? Could we reuse the column name being read? Also, if we find another column name by a name already found, could we rename the duplicate column to a new name and in the hint message let the user know? Also, mention the alias as a way to rename the column in the SQL
> > @mohanarpit : Would the above solution work?
> 
> Hi @trishaanand , regarding reading the column during parsing the results - it would lead to code duplication across the three plugins - postgres, redshfit, and mssql - and any other jdbc based plugin that we add in future. Apart from this I see both the implementations as equivalent. Please tell me whichever implementation is preferred, I will modify it accordingly.

@sumitsum : I have rethought this. Yours is a more performant solution in case of large datasets being returned.

**Comment by trishaanand** [comment]
> This is how we're doing it for Sheets as well. Something that's troubling me about that implementation is how we'd handle updates. Do we start using Appsmith columns for them?

@nidhi-nair : You are re-naming the columns in case of duplicate column names? Or the current behaviour where the column gets rewritten with the last duplicate column found in the result set?

**Comment by nidhi-nair** [comment]
Renaming to column_name_1 and so on @trishaanand

**Comment by sumitsum** [comment]
@mohanarpit @trishaanand are we going forward with renaming the columns ?

**Comment by mohanarpit** [comment]
For now, let's not rename the columns. As @nidhi-nair was mentioning, renaming may lead to complications in the future when we want to write data back to the DB. Hence, for now, I think this solution is good. @trishaanand Thoughts?

**Comment by trishaanand** [comment]
> For now, let's not rename the columns. As @nidhi-nair was mentioning, renaming may lead to complications in the future when we want to write data back to the DB. Hence, for now, I think this solution is good. @trishaanand Thoughts?

I am good with not renaming the column. But I am not really for renaming in one plugin but not in the other. This breaks the user expectations. So, lets definitely take it up to ensure similar interactions across different plugins.

**Review by trishaanand — APPROVED** [review]

**Pull request merged**
