### PR TITLE
fix: Google Sheet Plugin Numeric inputs Whitespace issue.

### LINKED ISSUE #8196: [Bug] Google sheets plugin: Row limit does not parse properly
## Description

In case the row limit property in the google sheet plugin has an extra new line the query return an error saying that the row limit is not valid, We should trim such characters from the property value

### Steps to reproduce the behaviour:

Add steps to reproduce this behaviour, include console / network logs & screenshots

1. Use google sheet get query
2. While defining the row limit add an additional new line
3. Run the query to see the error

Note: We will also need to test this for the rest for the fields.
 
### Important Details

- Version: [Cloud]
- OS: [MacOSX]
- Browser [chrome]
- Environment [production]

### PR DESCRIPTION
**Pull request by leotom2000**
Fixes #8196
> By adding a trim() where an integer value is expected, this error is handle
>This fix resolves 5 input fields, and also handles enter keys before and after values

## Type of change
- Bug fix (non-breaking change which fixes an issue)
- Unit Test has been added for this issue

## How Has This Been Tested?
Use google sheet get query
-While defining the row limit add an additional new line after input value - Error was found and fixed now
-While defining the row limit add an additional new line before input value- Error was found and fixed now
-While defining the row limit add a space before input value- Error was found and fixed now
-While defining the row limit add a space before input value- Error was found and fixed now

Tested for the following input fields
(1) Table Heading Row Index - Error was found and fixed now
(2) Row Offset - Error was found and fixed now
(3) Row Limit - Error was found and fixed now
(4) Cell Range - Error was found and fixed now

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by leotom2000** [comment]
Reply to @nidhi-nair query : Do you think we could handle these by trimming all property values at L#47 instead?

Line 47 is processing almost 10 input data, out of this we need validation only for 4 items, so considering unnecessary processing ( trim() ), I have place the trim() in the required 5 places.

**Comment by nidhi-nair** [comment]
@leotom2000 I think we can safely add this check for all other inputs as well. It is valid to expect this validation to exist in all other fields as well. Could you please add the check as common for everything instead?

**Review by nidhi-nair — APPROVED** [review]

**Pull request merged**
