### PR TITLE
fix: handle selectedValues value

### LINKED ISSUE #13171: [Bug]-[160]:CheckBoxGroup not displaying options in a modal
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

CheckBoxGroup inside a modal not displaying the values even though the options property of that same checkBoxGroup shows the correct evaluated values . 
Capture

### Steps To Reproduce

1.Create a modal with a CheckBoxGroup
2.Tick the options and close the modal 
3.Reopen the modal 

### Public Sample App

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by techbhavin**
## Description

CheckBoxGroup not displaying options in a modal to fix an issue we improve the handle selected value.

Fixes #13171 

## Type of change

- Bugfix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/issue-13171 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 56.64 **(-0.01)** | 38.61 **(0)** | 35.97 **(0)** | 56.9 **(0)**
 :red_circle: | app/client/src/selectors/commentsSelectors.ts | 83.61 **(-1.64)** | 61.76 **(-2.95)** | 73.33 **(0)** | 88.24 **(-2.35)**
 :green_circle: | app/client/src/utils/WorkerUtil.ts | 89.76 **(0)** | 72.55 **(1.96)** | 100 **(0)** | 93.33 **(0)**
 :green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.94 **(0.23)** | 41.67 **(0.84)** | 36.21 **(0)** | 56.99 **(0.25)**
 :red_circle: | app/client/src/widgets/CheckboxGroupWidget/widget/index.tsx | 46.51 **(-1.11)** | 17.5 **(-3.09)** | 34.78 **(0)** | 48.1 **(0)**</details>

### CODE REVIEW

**Review by jsartisan — APPROVED** [review]

**Comment by chandannkumar** [comment]
Tested this PR and working as Expected

**Pull request merged**
