### PR TITLE
fix: updated cursor style in actionWrapper

### LINKED ISSUE #10624: [Bug]-[400]:"Disable icon" should be visible in Table widget's icon column is set to Disabled
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[LOOM DEMO](https://www.loom.com/share/787a5533764443d6a57697747b73f062)

### Steps To Reproduce

1. Drag and drop a Table widget
2. Change the action column type to Icon widget
3. Select a icon widget
4. Enable disable property
5. Observe that when we hover the cursor on disabled icons, cursor icon should be changed to disable icon same as other widgets

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by techbhavin**
## Description

In the table widget, Icon Button Cursor Type is changed when an icon isDisabled

Fixes #10624 , #12767 

## Type of change

- Bugfix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/issue-10624 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 56.49 **(-0.01)** | 37.99 **(-0.01)** | 36.29 **(0)** | 56.71 **(0)**
 :red_circle: | app/client/src/selectors/commentsSelectors.ts | 83.61 **(-1.64)** | 61.76 **(-2.95)** | 73.33 **(0)** | 88.24 **(-2.35)**
 :red_circle: | app/client/src/widgets/TableWidget/component/TableStyledWrappers.tsx | 87.78 **(-1.88)** | 55.36 **(-0.48)** | 80.7 **(-2.94)** | 87.78 **(-1.88)**</details>

### CODE REVIEW

**Review by jsartisan — DISMISSED** [review]

**Comment by YogeshJayaseelan** [comment]
@techbhavin @jsartisan Tested this PR and the disabled mouse pointer is working as expected now.

However, when the button and Menu button column type is disabled the button name and the menu button name are not visible - This also happens in prod currently. Should we fix this in this PR and this will be a separate issue? 

https://www.loom.com/share/efdf6cc099ed4e9f97f164d1a3e568ef

**Review by jsartisan — APPROVED** [review]

**Comment by YogeshJayaseelan** [comment]
@techbhavin Tested this PR and it is working as expected.

**Pull request merged**
