### PR TITLE
fix: table filter popup is overlaid on modal

### LINKED ISSUE #8000: [Bug] Table widget's filter pop-up does not collapse on opening a modal
## Description
Filter pop-up of the table widget does not automatically close when modal widget is opened. 

### Steps to reproduce the behaviour:
1. Drag and drop table and modal widget on to canvas and click on the filter option on the table widget.
2. Now open the modal widget and observe the overlap

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Release

image

### PR DESCRIPTION
**Pull request by wmdev0808**
## Description
Table widget's filter pop-up does not collapse on opening a modal

Fixes #8000 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Test A
- Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/8000-table-filter-popup-overlay-on-modal 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 55.21 **(-0.01)** | 37.02 **(-0.01)** | 34.07 **(0)** | 55.73 **(-0.01)**
 :red_circle: | app/client/src/selectors/commentsSelectors.ts | 83.61 **(-1.64)** | 61.76 **(-2.95)** | 73.33 **(0)** | 88.24 **(-2.35)**
 :red_circle: | app/client/src/widgets/ModalWidget/component/index.tsx | 20.78 **(-0.65)** | 12.77 **(-1.18)** | 0 **(0)** | 22.22 **(-0.86)**</details>

### CODE REVIEW

**Review by marks0351 — DISMISSED** [review]

**Comment by shwetha-ramesh** [comment]
@wmdev0808 Tested this PR. Verified the reported bug, the issue is resolved now. Filter pop-up now collapses when Modal is dropped on the canvas. 

**Moving this to DONE.**

**Comment by somangshu** [comment]
@wmdev0808 take the latest base update and run the tests again, Netlify have been throwing an error and we have moved on to vercel, You will see the deploy preview link as a comment from the bot

**Review by marks0351 — APPROVED** [review]

**Comment by somangshu** [comment]
@wmdev0808 please merge this, tests are passing now!

**Pull request merged**
