### PR TITLE
fix: datepicker issues in property pane 

### PR DESCRIPTION
**Pull request by tanvibhakta**
Fixes https://github.com/appsmithorg/appsmith/issues/23936

>
#### Media

https://github.com/appsmithorg/appsmith/assets/13763558/cdb8c883-ec4e-4aff-8b45-a11ef9d7a493

#### Type of change

- Bug fix (non-breaking change which fixes an issue)
>
>
>
- [ ] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Comment by shadabbuchh** [comment]
This iss has been verified in the DP. Looks good.

https://github.com/appsmithorg/appsmith/assets/39921438/192478ae-7996-400f-8a91-89e29ea8dc4e

**Review by aswathkk — APPROVED** [review]

**Pull request merged**
