### PR TITLE
fix: Logs timestamp inconsistency

### LINKED ISSUE #25656: [Bug]: System and user generated logs have different date formats
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

System generated logs are in 24h format whereas user generated logs are in 12h format without am/pm distinction

### Steps To Reproduce

image

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by Rishabh-Rathod**
## Description

Fix logs timestamp inconsistency

#### PR fixes following issue(s)
Fixes #25656

#### Type of change

- Bug fix (non-breaking change which fixes an issue)

#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by Rishabh-Rathod — COMMENTED** [review]
LGTM ( Comment added via Codesee )

**Review by Druthi — APPROVED** [review]

**Pull request merged**
