### PR TITLE
fix: enable change in background color on hover for Icon Button cell in Table widget V2

### LINKED ISSUE #17775: [Bug]: There is no hover state color change for Icon widget inside table cells
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On hovering onto Icon button widget which is added inside table cells do not have hover state i.e change of color on hover unlike other button type widgets

https://www.loom.com/share/b859cf7757c947378899065aa7eb4227

### Steps To Reproduce

1. Drag and drop Table widget
2. Add/Update a column type in Table as **Icon Button**
3. Configure onClick event for Icon button column type 
4. Observe that there is no hover state for Icon Button column type in Table cells

### Public Sample App

_No response_

### Version

Cloud/ Production

### PR DESCRIPTION
**Pull request by keyurparalkar**
## Description
This PR passes a prop named: `hasOnClickAction` as `true` to the `StyledButton` of the `IconButtonCell` component of the table widget v2. 

**Root cause:** This happens so because inside the IconButtonWidget’s component we conditionally showcase the background color. If `hasOnClickAction` exists then we show change in BG color on hover. 

**************Reason:************** People use icon button widget as icon widget as well. If there's no onclick then people just want to use the icon as a way to display something

**********Proposed solution:********** Always pass the `hasOnClickAction` as true to the IconButtonWidget’s component via table cell

#### PR fixes following issue(s)
Fixes #17775 

#### Type of change
- Bug fix (non-breaking change which fixes an issue)

- [x] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by sbalaji1192 — APPROVED** [review]

**Comment by chandannkumar** [comment]
Tested this PR and LGTM

**Pull request merged**
