### PR TITLE
Document Viewer Widget : Parse maximum number of headers present in excel file raw data

### LINKED ISSUE #25305: [Bug]: Document Viewer Widget Displays Incorrect Base64 File Uploaded Via FilePicker Widget
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When uploading an Excel file via a FilePicker widget and trying to display it in a Document Viewer Widget, it gets rendered incorrectly. Only the first column (column A) is shown.
The bug is present in the latest version, v1.9.26. This worked fine in v1.9.19; however, the bug has been reproducible since v1.9.21.

image

### Steps To Reproduce

1. Add a **FilePicker** widget to the canvas.
2. Add a **Document Viewer** widget to the canvas.
3. Use `{{FilePicker1.files[0]?.data}}` in the **Document Link** property of the Document Viewer.
4. Upload this **sample Excel file** in the FilePicker widget.
[sample file.xlsx](https://github.com/appsmithorg/appsmith/files/12014721/sample.file.xlsx)

[Front thread](https://app.frontapp.com/open/cnv_11neczkc?key=pYIHyXneSerctmPm14mNW-DNVqpCS5oh)

### Public Sample App

https://app.appsmith.com/app/documentviewer-bug/excel-file-display-64ad4d75e5b84e6550482c66

### Environment

Production

### Issue video log

_No response_

### Version

v1.9.21-v1.9.26

### PR DESCRIPTION
**Pull request by rajatagrawal**
Fixes #25305

### CODE REVIEW

**Review by sbalaji1192 — DISMISSED** [review]

**Comment by chandannkumar** [comment]
Observations:
- Unable to see fully parsed data on document viewer. In this sample file, column O is not visible on doc viewer



- Some blank space is observed at the end of excel cells. It occurs when i added some data in unformatted way at the end

**Comment by rajatagrawal** [comment]
@chandannkumar 

The blank space issue can be tracked here : https://github.com/appsmithorg/appsmith/issues/26036

**Review by sbalaji1192 — APPROVED** [review]

**Comment by rajatagrawal** [comment]
The blank space issue is happening on v1.9.19 as well which is before any changes to document viewer widget were made that caused this regression.

**Comment by chandannkumar** [comment]
Tested & Verified the callout. LGTM

**Pull request merged**
