### PR TITLE
[Enhancement] changing Widget Move DSL update into an atomic operation.

### LINKED ISSUE #5058: Composite operations
Some operations today send multiple independent updates to the DSL. We need to make sure that these operations now become atomic, but using the `batchUpdateWidgetProperty` feature.

Operations of note:
- [ ] Move widget - Updates main container height and widget positions
- [ ] Add widget - Updates main container height and widget positions
- [ ] Make widget resize operation atomic
- [ ] Make property updates from property pane atomic
- [ ] Add arch to allow multi widget / multi property updates from property control
- [ ] Make Tabs operations(Add/Remove/Tab name change) atomic.

### PR DESCRIPTION
**Pull request by marks0351**
## Description

Changing the way we update DSL when widget is moved or new widget is added.
previous: dual update DSL in app and call api once to update.
now: single update DSL in app and call api once to update.

Fixes #5058

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/drop-op-atomic 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 54.61 **(0)** | 36.67 **(-0.03)** | 33.06 **(0)** | 55.22 **(0)**
 :red_circle: | app/client/src/components/editorComponents/DropTargetComponent.tsx | 81.58 **(-7.89)** | 63.27 **(-2.04)** | 81.82 **(-9.09)** | 81.08 **(-8.11)**
 :red_circle: | app/client/src/components/editorComponents/DropTargetUtils.ts | 90 **(-10)** | 66.67 **(0)** | 100 **(0)** | 88.89 **(-11.11)**
 :green_circle: | app/client/src/sagas/DraggingCanvasSagas.ts | 84.06 **(8.45)** | 39.29 **(15.76)** | 100 **(0)** | 84.38 **(7.46)**
 :red_circle: | app/client/src/sagas/WidgetOperationSagas.tsx | 56.02 **(-0.15)** | 38.19 **(-0.32)** | 58.14 **(0)** | 56.05 **(-0.17)**
 :red_circle: | app/client/src/utils/DynamicBindingUtils.ts | 89.78 **(-0.73)** | 80 **(-2.67)** | 78.26 **(0)** | 88.24 **(-0.84)**
 :red_circle: | app/client/src/utils/hooks/useBlocksToBeDraggedOnCanvas.ts | 95.41 **(-0.32)** | 82.81 **(-1.48)** | 85.71 **(-0.65)** | 95.24 **(-0.26)**</details>

### CODE REVIEW

**Review by riodeuno — COMMENTED** [review]
Code looks fine to me. 
Next Step: Validate feature in deploy preview.

**Review by riodeuno — APPROVED** [review]

**Review by riodeuno — APPROVED** [review]

**Comment by marks0351** [comment]
@vivekverma2312 @YogeshJayaseelan  this is a code improvement. Can u guys test this out and make sure moving widget and adding new widget works fine in all cases?

**Comment by somangshu** [comment]
@all-contributors please add @marks0351 for code :)

**Comment by marks0351** [comment]
closing this in favour of https://github.com/appsmithorg/appsmith/pull/6921

**Pull request closed without merging**
