### PR TITLE
feat: Update QR Scanner Themes to Code Scanner Themes

### PR DESCRIPTION
**Pull request by dhruvikn**
## Description

This PR updates QR Scanner themes to Code Scanner themes in the System Themes. 
This should be merged before #15990 to enable testing #15990 on DPs.

Previously #16474 was merged to release, but now the QR Scanner widget is renamed to Code Scanner widget. Thus this PR.

## Type of change
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Manually tested.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by sbalaji1192 — APPROVED** [review]

**Comment by trishaanand** [comment]
@Aishwarya-U-R : Sorry, I cancelled this job. The runners were stuck and had been running for ~1 hour

**Pull request merged**
