### PR TITLE
fix: Show loading state of application until all jsobject update calls are complete

### PR DESCRIPTION
**Pull request by dvj1988**
## Description
Show loader when the jsobject update is ongoing. The loader should start showing when the body update starts and it should end when the actions update is complete.

Fixes https://github.com/appsmithorg/appsmith-ee/issues/4209
> [!WARNING]  
> _If no issue exists, please create an issue first, and check with the maintainers if the issue is valid._

## Automation

/ok-to-test tags="@tag.All"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9218512788>
> Commit: abccd2e8e12df6fe8748b3e0b7bfc29195afbf73
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9218512788&attempt=1" target="_blank">Click here!</a>

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by trishaanand** [comment]
Previous test run : 
Caution

🔴 🔴 🔴 Some tests have failed.
Workflow run: https://github.com/appsmithorg/appsmith/actions/runs/9124918410
Commit: https://github.com/appsmithorg/appsmith/commit/2379d2b74ea20665f46d30e1735a0c6b5530db74
Cypress dashboard: [Click here!](https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9124918410&attempt=2&selectiontype=test&testsstatus=failed&specsstatus=fail)
The following are new failures, please fix them before merging the PR:

cypress/e2e/Regression/ClientSide/Autocomplete/JS_AC1_spec.ts
cypress/e2e/Regression/ClientSide/Autocomplete/JS_AC2_spec.ts
cypress/e2e/Regression/ClientSide/BugTests/JSParse_Spec.ts
cypress/e2e/Regression/ClientSide/SetProperty/SetOptions_Spec.ts
cypress/e2e/Regression/ClientSide/SettingsPane/EmbedSettings_spec.ts
cypress/e2e/Regression/ClientSide/VisualTests/JSEditorIndent_spec.js
To know the list of identified flaky tests - [Refer here](https://internal.appsmith.com/app/cypress-dashboard/identified-flaky-tests-65890b3c81d7400d08fa9ee3?branch=master)

**Comment by dvj1988** [comment]
Previous test run :


🔴 🔴 🔴 Some tests have failed.
Workflow run: https://github.com/appsmithorg/appsmith/actions/runs/9167792219
Commit: https://github.com/appsmithorg/appsmith/commit/983bbab985dc2021567f2acd8ddc21d2f10c3ea7
Cypress dashboard: [Click here!](https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9167792219&attempt=2&selectiontype=test&testsstatus=failed&specsstatus=fail)
The following are new failures, please fix them before merging the PR:

cypress/e2e/Regression/ClientSide/SetProperty/SetOptions_Spec.ts
cypress/e2e/Regression/ClientSide/SetProperty/WidgetPropertySetters1_spec.ts
To know the list of identified flaky tests - [Refer here](https://internal.appsmith.com/app/cypress-dashboard/identified-flaky-tests-65890b3c81d7400d08fa9ee3?branch=master)

**Comment by dvj1988** [comment]
The following are new failures, please fix them before merging the PR:

cypress/e2e/Regression/ClientSide/BugTests/GitBugs_Spec.ts
cypress/e2e/Regression/ClientSide/Git/GitSync/SwitchBranches_spec.js

**Review by ApekshaBhosale — APPROVED** [review]

**Pull request merged**
