### PR TITLE
Replace test api with mockApi in Cypress tests

### PR DESCRIPTION
**Pull request by NandanAnantharamu**
replacing all reqres api calls with mock-api

### CODE REVIEW

**Comment by hetunandu** [comment]
@NandanAnantharamu One test is failing

**Comment by NandanAnantharamu** [comment]
> @NandanAnantharamu One test is failing

@hetunandu it's fixed now

**Review by hetunandu — DISMISSED** [review]
Since we merged categorise, there are merge conflicts. Can you fix this again?

**Comment by NandanAnantharamu** [comment]
> Since we merged categorise, there are merge conflicts. Can you fix this again?

this is resolved now, we can merge

**Review by mohanarpit — APPROVED** [review]

**Pull request merged**
