### PR TITLE
fix: tabindex and a11y

### LINKED ISSUE #4436: TabIndex and a11y in form controls
## Description

Okay. So there is two issues. Both are related to each other so I will combine it into one. 

See this gif first
I6sfJQMRsh

Bug 1) When user reaches to dropdown widget via hitting tab tab tab it is not highlighting as other controls like textbox but control has reached there, It is just not showing it. You will know it by hitting ⬆ ⬇ key
Bug 2) when dropdown is open and user is navigating in the options the same thing happens. Control is navigating but it is not showing the way when it shows with mouse hover event

### Steps to reproduce the behavior:
steps to reproduce this behavior, include console / network logs & screenshots
1. Take a form widget
2. add text box and drop down widget same as shown in gif
3. hit keyboard keys same as shown in gif

### Important Details
 - Version: Cloud
 - OS: Windows
 - Browser: Chrome

### PR DESCRIPTION
**Pull request by Tooluloope**
## Description

Fixed TabIndex and a11y for Dropdown and DatePicker Widget
Fixes #4436  (issue)

> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/tabindex-and-a11y 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 54.9 **(-0.01)** | 36.82 **(0)** | 34.31 **(-0.01)** | 55.43 **(0)**
 :green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 50.71 **(0.24)** | 39.13 **(0.87)** | 36.21 **(0)** | 55.35 **(0.27)**
 :green_circle: | app/client/src/widgets/DatePickerWidget2/component/index.tsx | 24.73 **(0.92)** | 5.48 **(2.49)** | 8.7 **(3.7)** | 24.72 **(0.97)**
 :red_circle: | app/client/src/widgets/DropdownWidget/component/index.tsx | 42.59 **(-1.64)** | 18.6 **(-0.91)** | 4.76 **(-0.24)** | 42.31 **(-1.69)**</details>

### CODE REVIEW

**Comment by somangshu** [comment]
@Tooluloope why have you picked this up when this was in the icebox and clearly the thread shows that the use cases are not yet defined? Do you have more clarity here?

**Review by SatishGandham — APPROVED** [review]

**Comment by SatishGandham** [comment]
@Tooluloope , Please resolve the conflcits. Changes look good.

**Comment by somangshu** [comment]
@riodeuno @marks0351 need you help understanding if we want to take this forward? This was in the icebox because all use cases were not really detailed out and we wanted to also look at these state changes from the design POV

**Review by somangshu — APPROVED** [review]

**Comment by marks0351** [comment]
@Tooluloope let's merge this if the functionality is good to go. we can create an issue to make this work across all widgets.
cc: @somangshu

**Review by marks0351 — APPROVED** [review]

**Pull request merged**
