### PR TITLE
fix: error handling in trigger execution flow

### LINKED ISSUE #4228: [Bug]Error message is not displayed in the Debug error section
## Description
Release Environment - For all Common errors
It is observed for all the widgets if any error occurs the particular error is not updated to the Debug Error section
 
**Expected Result:**
Error details needs to be displayed in the debug error section

**Actual Result:**
Error details are not displayed in the debug error section

### Steps to reproduce the behaviour:
1. Launch Appmsith app in the release environment 
2. Drag and drop any widget - lets consider chart widget 
3. Click edit on the chart 
4. From the property pane - under the actions section set 'On Datapoint click' to download - Create manual error
5. Leave the Data to Download field empty , so that error occurs
6. Type the file name and file type 
7. Click on Chart Data point and ensure error message occurs 
8. Click on Debug and navigate to the error section and observe

**VideoLink:**
[LOOM DEMO](https://www.loom.com/share/1c1f4e39fad3411a9aa9ca1696f39ba6)

### Important Details
 - Version: [Safari - 14.1 (16611.1.21.161.3), Chrome - 90.0.4430.93]
 - OS: [macOS Big Sur 11.3]
 - Browser [Chrome, Safari]

### PR DESCRIPTION
**Pull request by hetunandu**
## Description

Fix issues with error handling in the trigger evaluation and execution flow

Fixes #4228

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/promise-data-clone-issue 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 54.77 **(0.02)** | 36.57 **(0)** | 33.81 **(0.01)** | 55.38 **(0.01)**
 :red_circle: | app/client/src/sagas/JSPaneSagas.ts | 20.39 **(0)** | 1.49 **(-0.05)** | 7.14 **(0)** | 24.41 **(0)**
 :green_circle: | app/client/src/sagas/PostEvaluationSagas.ts | 17.73 **(0.12)** | 0 **(0)** | 0 **(0)** | 21.74 **(0.19)**
 :red_circle: | app/client/src/sagas/ActionExecution/ActionExecutionSagas.ts | 26.25 **(-6.72)** | 2.5 **(0.94)** | 20 **(-8.57)** | 26.92 **(-5.26)**
 :red_circle: | app/client/src/sagas/ActionExecution/DownloadActionSaga.ts | 33.33 **(-5.13)** | 0 **(0)** | 0 **(0)** | 33.33 **(-5.13)**
 :red_circle: | app/client/src/sagas/ActionExecution/PluginActionSaga.ts | 17.45 **(-1.2)** | 3.19 **(0.19)** | 10.53 **(-6.86)** | 20.1 **(-0.46)**
 :red_circle: | app/client/src/sagas/ActionExecution/PromiseActionSaga.ts | 17.24 **(-12.03)** | 0 **(0)** | 0 **(-33.33)** | 19.23 **(-4.3)**
 :sparkles: :new: | **app/client/src/sagas/ActionExecution/errorUtils.ts** | **64** | **0** | **46.15** | **51.35**
 :green_circle: | app/client/src/selectors/commentsSelectors.ts | 79.84 **(1.61)** | 57.35 **(2.94)** | 70 **(0)** | 86.36 **(2.27)**</details>

### CODE REVIEW

**Comment by akash-codemonk** [comment]
- Is it expected that if the success callback fails, the error callback be called? If yes then this isn't happening here.
For e.g 
```
{{query1.run(() => j, () => showModal('Modal1'))}}
```

If query 1 succeeds, then ```() => j``` would throw an error but `() => showModal('Modal1')` doesn't get called.

- Also I think the triggermeta doesn't seem to get passed on as there is no error shown in the debugger. If the [source id](https://github.com/appsmithorg/appsmith/pull/7671/files#diff-15965fa7f8035f69c84d87498ff2475a237d091e8c3d19e35575d83c11cae63dR42) is undefined the debugger will not show the error in the debugger.

**Comment by hetunandu** [comment]
> * Is it expected that if the success callback fails, the error callback be called? If yes then this isn't happening here.
>   For e.g
> 
> ```
> {{query1.run(() => j, () => showModal('Modal1'))}}
> ```
> 
> If query 1 succeeds, then `() => j` would throw an error but `() => showModal('Modal1')` doesn't get called.
> 
> * Also I think the triggermeta doesn't seem to get passed on as there is no error shown in the debugger for the above scenario. If the [source id](https://github.com/appsmithorg/appsmith/pull/7671/files#diff-15965fa7f8035f69c84d87498ff2475a237d091e8c3d19e35575d83c11cae63dR42) is undefined the debugger will not show the error in the debugger.

@akash-codemonk The first scenario is not supported.

Added changed for the second issue mentioned

**Review by akash-codemonk — DISMISSED** [review]
> 
> @akash-codemonk The first scenario is not supported.
> 

Ok was just confirming because on release and prod, onError gets called when there is an error in onSuccess

**Comment by ramsaptami** [comment]
Something to note: only **onTextChange** of Input widget trigger field is being read for errors/input on Deploy Preview but this works perfectly fine on release
https://www.loom.com/share/8d8821eb4d524977bbf6a50b99808b75

**Review by ramsaptami — APPROVED** [review]
tested ok and verified on all applicable widget triggers

**Pull request merged**
