### PR TITLE
feat: Renamed design system package

### LINKED ISSUE #19536: [Task]: Rename design-system to design-system-old and v2 to design-system
We also need to publish these two respective packages on our npm registry. We need to do this to be able to use the components we are creating on the main repository right away. 

Blocked on https://github.com/appsmithorg/design-system/pull/302, https://github.com/appsmithorg/design-system/pull/303

### LINKED ISSUE #19651: [Task]: Design system v2 basic setup
Add basic setup for design system v2

### PR DESCRIPTION
**Pull request by albinAppsmith**
## Description

This PR includes changes for renaming design system package. Since we are building new package for the refactored design system components, the old package is renaming to design-system-old.

Fixes #19536 

## Type of change

- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested?

- Manual
- Jest
- Cypress

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Comment by tanvibhakta** [comment]
Right now, if we just update the package and not the package name itself, we will have to add the new package under a different namespace. So can we instead rename the `design-system` package itself to `design-system-old` (and change all the imports as well) so when that by the time we end deduplication we don't have to deal with this at the time?

**Review by tanvibhakta — CHANGES_REQUESTED** [review]
In this commit you are only changing the package source and not the package name. Can you please change the package name as well, so all instances of `design-system` become `design-system-old` including all imports? 
This will allow us to use the design-system package right away, and we won't have to worry about renaming everything (and doing another regression on the rename) at the end of deduplication.

**Review by tanvibhakta — APPROVED** [review]

**Comment by shadabbuchh** [comment]
Tested this PR. Everything works as expected.

**Review by tanvibhakta — APPROVED** [review]

**Pull request merged**
