### PR TITLE
feat: change value to label in onItemSelect inside SelectCell of table widget

### LINKED ISSUE #26188: [Bug]: Select widget should display label instead of value while editing a table cell
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Whenever a select column type cell is editable and when user actually selects the value from drop down for the cell, then select option's value property is updated in cell's data. It is expected that select option's label property should get updated in cell data.

### Steps To Reproduce

1. Drag and drop a table widget and bind a query to this widget.
2. Change one of it's column to select type and add select options to it.
3. Make this column editable
4. Now try to edit this cell
5. Observe that selecting an option from the select dropdown sets the cell's data to the `value` property of select option instead of `label`

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

Cloud
```[tasklist]
### Tasks
- [ ] https://github.com/appsmithorg/appsmith/issues/27061
- [ ] https://github.com/appsmithorg/appsmith/issues/27093
```

Front logo [Front conversations](https://app.frontapp.com/open/top_3kid3g)

### PR DESCRIPTION
**Pull request by jacquesikot**
## Description
**Issue**
In the table widget, the select column currently displays the value from the dropdown when a user makes a selection, rather than the label. This behaviour is inconsistent with the standalone select widget, which correctly renders the label upon selection.

**Fix**
This PR addresses the inconsistency by modifying the table widget's select column to display the label of the selected item, ensuring alignment with the behaviour of the standalone select widget.

Fixes #26188

## Automation

/ok-to-test tags="@tag.Table, @tag.Binding, @tag.Widget, @tag.Sanity"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9843945454>
> Commit: 330d0d3f82ea7a8769c350f7caa0714959838f12
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9843945454&attempt=1" target="_blank">Cypress dashboard</a>.
> Tags: `@tag.Table, @tag.Binding, @tag.Widget, @tag.Sanity`
> Spec:
> <hr>Mon, 08 Jul 2024 18:21:02 UTC

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [x] No

## Summary by CodeRabbit

- **Bug Fixes**
  - Updated the `SelectCell` component to use the `option.label` instead of `option.value` for item selection.
  
- **Tests**
  - Revised test descriptions and assertions for select options in Table Widget to reflect the new functionality of using labels as values in select cells.

### CODE REVIEW

**Review by rahulbarwal — COMMENTED** [review]
Unit tests?

**Comment by jacquesikot** [comment]
@rahulbarwal I was thinking cypress tests? But i can try with a unit test first?

**Comment by rahulbarwal** [comment]
> @rahulbarwal I was thinking cypress tests? But i can try with a unit test first?

Whatever you think will be best is fine. Any kind of coverage is good.

**Review by rahulbarwal — APPROVED** [review]

**Pull request merged**
