### PR TITLE
fix: Updating the conditions for URL update on click of go to application button in import application modal

### PR DESCRIPTION
**Pull request by ankitakinger**
## Description

Reconnect datasource modal that opens up when we import an application shows a `Go to application` button. On clicking this button, sometimes the URL update for this button takes time. If the button is being clicked immediately after the modal opens, and when the app is imported via app-level import, the `pageId` used in this URL is still the old pageId that needs to be updated to new home `pageId` we get via import application API. After few seconds the URL updates correctly. Fixing this issue via this PR.

#### PR fixes following issue(s)
Fixes [#26978](https://github.com/appsmithorg/appsmith/issues/26978)

#### Type of change
- Bug fix (non-breaking change which fixes an issue)

#### How Has This Been Tested?
- [x] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress

#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Comment by ankitakinger** [comment]
@kamakshibhat-appsmith 
We need to test the below scenarios in the DP for this change:
1. Reconnect modal on home page - with non-oauth datasources
2. Reconnect modal on home page - with oauth datasources
3. Reconnect modal on app editor page - with non-oauth datasources
4. Reconnect modal on app editor page - with non-oauth datasources

3 and 4 can be tested only on EE. So we need to test 1 and 2 on CE as well as EE. While 3 and 4 can be tested on EE. Will create a PR on EE just for creating a DP to test this change and share the link with you.

**Review by ayushpahwa — DISMISSED** [review]

**Comment by kamakshibhat-appsmith** [comment]
@btsgh Can you / someone from your team please check these OAuth/non-Oauth use cases ?

**Review by ayushpahwa — APPROVED** [review]

**Pull request merged**
