### PR TITLE
chore: removes feature flag logic for flipped CTAs

### LINKED ISSUE #31045: [Task]: remove CTA flip experiment code
### SubTasks

#30394 introduced an experiment to flip the primary and secondary CTAs in the datasource form. Experiment results [invalidated the hypothesis](https://theappsmith.slack.com/archives/C05P3ME9MBR/p1707714615475319?thread_ts=1706788945.493989&cid=C05P3ME9MBR), so this task is to clean up the code and remove the flag.

### PR DESCRIPTION
**Pull request by rohan-arthur**
## Description
[#30394](https://github.com/appsmithorg/appsmith/issues/30394) introduced an experiment to flip the primary and secondary CTAs in the datasource form. Experiment results [invalidated the hypothesis](https://theappsmith.slack.com/archives/C05P3ME9MBR/p1707714615475319?thread_ts=1706788945.493989&cid=C05P3ME9MBR), so this task is to clean up the code and remove the flag.

#### PR fixes following issue(s)
Fixes #31045

#### Type of change
- Chore (housekeeping or task changes that don't impact user perception)

- [x] Manual
- [ ] JUnit
- [ ] Jest
- [x] Cypress - also, tests have passed on ee pr: https://github.com/appsmithorg/appsmith-ee/pull/3630
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

## Summary by CodeRabbit

- **Chores**
	- Removed an obsolete feature flag related to button styling in data source authentication.
- **Refactor**
	- Simplified button styling logic on the data source authentication page, ensuring consistent appearance.

### CODE REVIEW

**Comment by rohan-arthur** [comment]
tests failing on ee: https://github.com/appsmithorg/appsmith-ee/pull/3630

**Comment by rohan-arthur** [comment]
tests have passed on ee pr: https://github.com/appsmithorg/appsmith-ee/pull/3630

**Review by AmanAgarwal041 — APPROVED** [review]

**Pull request merged**
