### PR TITLE
fix: table widget header links should have pointer cursor when hovered

### LINKED ISSUE #18189: [Bug]: Cursor icon on hover to 'Filters', 'Download' & 'Add new row' buttons of Table widget is a text edit cursor on view mode
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On hovering to buttons on  'Filters', 'Download' & 'Add new row' buttons of Table widget, the cursor should be visible with Hand cursor instead of text edit cursor

### Steps To Reproduce

1. Drag & Drop Table widget
2. Deploy the app
3. Hover on Filter & Download
4. Observe that the cursor icon is text edit cursor instead of hand cursor

### Public Sample App

_No response_

### Issue video log

https://www.loom.com/share/b11ac766257f4418b5449b730d8f3249

### Version

cloud / release

### PR DESCRIPTION
**Pull request by sbalaji1192**
Fixes #18189
## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manual

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by keyurparalkar — APPROVED** [review]
LGTM!

**Comment by chandannkumar** [comment]
Tested this PR and working as expected

**Pull request merged**
