### PR TITLE
fix: show progress bar in git modal when committing library diffs

### LINKED ISSUE #19903: [Bug]: Progress bar doesnt come up for JS Library changes in git sync modal on committing and pushing changes.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://user-images.githubusercontent.com/80334441/213414870-550514ba-4f51-44e2-91c1-bd3327b96c1a.mov

### Steps To Reproduce

1. Add JS Library to git connected app
2. Open git sync modal, commit and push changes
3. Observe the progress bar doesnt come up.

### Public Sample App

_No response_

### Issue video log

_No response_

### Version

Release

### PR DESCRIPTION
**Pull request by arunvjn**
## Description
Fixes a bug with git modal not showing the progress bar while committing changes to the libraries of an application.

Fixes #19903 

### Media
**Before:**
Screenshot 2023-01-19 at 21 47 02

**After:**
Screenshot 2023-01-19 at 21 43 26

### Type of change
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
- Manual
- Jest

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Comment by Parthvi12** [comment]
@arunvjn After committing JS library changes it again shows commit and push & discard changes button, could you please check?

https://user-images.githubusercontent.com/80334441/213628969-f124676a-7535-4f34-92af-159da813672c.mov

**Comment by arunvjn** [comment]
> @arunvjn After committing JS library changes it again shows commit and push & discard changes button, could you please check?
> 
>  Screen.Recording.2023-01-20.at.11.36.02.AM.mov

This looks like a backend issue and you should be able to replicate this on release. 
@Sumit could you please look into this ? There is an `isClean` attribute that is not set when libraries are involved in the commit.

**Comment by Parthvi12** [comment]
> @arunvjn After committing JS library changes it again shows commit and push & discard changes button, could you please check?
This issue exist on release, and is fixed by Sumit in different PR, the progress bar bug is fixed on this PR, have verified the changes.

**Comment by ramsaptami** [comment]
Verified status bar while git committing library changes
GTG to release CC: @arunvjn

**Review by ApekshaBhosale — APPROVED** [review]

**Pull request merged**
