### PR TITLE
fix: file picker widgets removing files causing abnormal content

### PR DESCRIPTION
**Pull request by gzlinzihong**
#### PR fixes following issue(s)
Fixes # (issue number)
> [31411](https://github.com/appsmithorg/appsmith/issues/31411)
#### Type of change
- Bug fix 
>
- Cypress
>
>
#### Dev activity
- My code follows the style guidelines of this project
- I have performed a self-review of my own code
- I have commented my code, particularly in hard-to-understand areas
- My changes generate no new warnings
- New and existing unit tests pass locally with my changes

## Summary by CodeRabbit

- **New Features**
	- Enhanced the File Picker widget to support more interactive functionalities like setting maximum file limits and custom data formats.
- **Tests**
	- Added tests for new functionalities in the File Picker widget, including file uploading, setting restrictions, and file removal verification.
- **Bug Fixes**
	- Fixed an issue with file data retrieval in the File Picker widget to ensure accurate data is presented after files are removed.

### CODE REVIEW

**Review by sneha122 — APPROVED** [review]

**Comment by sneha122** [comment]
@gzlinzihong Can you please pull latest release branch and merge it into this branch?

**Comment by sneha122** [comment]
Hi @gzlinzihong Thank you so much for creating separate PRs, we can close this one now as all checks have passed 🚀

**Review by sbalaji1192 — APPROVED** [review]

**Pull request merged**
