### PR TITLE
fix: Replace inequality operator with the strict inequality operator

### LINKED ISSUE #7445: (JS-0050) Avoid use of `==` and `!=`
## Description
It is considered good practice to use the type-safe equality operators `===` and `!==` instead of their regular counterparts `==` and `!=`. If one of those occurs in an innocent-looking statement such as `a == b` the actual problem is very difficult to spot.

## Occurrences
There are 5 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/appsmithorg/appsmith/issue/JS-0050/occurrences/](https://deepsource.io/gh/appsmithorg/appsmith/issue/JS-0050/occurrences/)

### PR DESCRIPTION
**Pull request by bharat-patodi**
## Description

Replaced the inequality operator `!=` with the strict inequality operator `!==` in 5 different instances. 

Fixes #7445 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Manual

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Rishabh-Rathod — DISMISSED** [review]
LGTM

**Review by Rishabh-Rathod — APPROVED** [review]

**Review by sharat87 — APPROVED** [review]

**Comment by Rishabh-Rathod** [comment]
@mohanarpit can you check why cypress setup fails for this PR?

**Review by mohanarpit — APPROVED** [review]

**Review by Rishabh-Rathod — APPROVED** [review]
Looks good

**Pull request merged**
