### PR TITLE
fix: Remove datasources from Execute Query Action.

### LINKED ISSUE #11380: [Bug]: The action selector from the property pane show the list of datasources.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you select "Execute Query" on the actions selector from the property pane, with the list of all the queries/apis it also lists down all the data sources which you have created. When you select the data source it redirects to a new query flow taking the user away from the canvas.

Showing the list of data sources doesnt make sense in a list which is primarily used to bind queries/apis.  

action selector - showing datasources not query

### Steps To Reproduce

1. Add a button to canvas
2. Click on onCLick to select an action.
3. Click on "Execute a Query" 

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by yaldram**
## Description

- The action Selector for Execute Query lists all Datasources. It should only lists the Apis and Queries.

Fixes #11380 

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Tested manually on the app.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/remove-datasources-action-selector 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 55.88 **(-0.01)** | 37.24 **(-0.01)** | 35.26 **(-0.02)** | 56.21 **(-0.01)**
 :green_circle: | app/client/src/components/editorComponents/ActionCreator/index.tsx | 38.37 **(-0.74)** | 7.08 **(0)** | 43.48 **(3.48)** | 38.24 **(-0.74)**
 :red_circle: | app/client/src/selectors/entitiesSelector.ts | 45.57 **(-1.23)** | 7.8 **(0)** | 22.97 **(-2.03)** | 41.59 **(-1.58)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.71 **(-0.23)** | 40.83 **(-0.84)** | 36.21 **(0)** | 56.74 **(-0.25)**</details>

### CODE REVIEW

**Comment by somangshu** [comment]
@hetunandu can you please check this out, I am not sure about the code change. 

The DP looks fine though

**Comment by yaldram** [comment]
@eco-monk Thanks for the comment.  Great point! I agree with you.

**Review by eco-monk — APPROVED** [review]

**Comment by vivekverma2312** [comment]
@yaldram Tested and LGTM

**Pull request merged**
