### PR TITLE
fix: Dropdown issues

### LINKED ISSUE #15024: [Bug]: Multiselect widget does not close after clicking on it - On Mobile/iPad views
### Is there an existing issue for this?

- [X] I have searched the existing issues

**Issue 1**
### Description

The multi-select is no longer working on a phone or tablet, once selected the widget continues to hover and cannot be closed.  It works fine on a laptop.

### Steps To Reproduce

Open an app on mobile. Click on a multi select widget with data. Now try to close it. You will be unable to close the list. 

If the multiselect widget is inside a modal, the modal also refuses to close after the above action.

### Public Sample App

**Issue 2**
### Description

The multi-select and tree select won't open when you navigate to the query page and back

### Steps To Reproduce

1. Drag a Multiselect to canvas, 
2. navigate to the Query page, 
3. Navigate back to the canvas
4. Click the MultiSelect to open the dropdown

_No response_

### Version

Cloud/Self-Hosted - v1.7.6

### PR DESCRIPTION
**Pull request by Tooluloope**
## Description

> Fix dropdown not closing by Making the dropdown controlled
> Fixed Query page navigation

Fixes #15024

> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Visually

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by jsartisan — DISMISSED** [review]

**Comment by chandannkumar** [comment]
Tested this PR and working as expected
- Dropdown not closing on mobile/tablet - **Fixed**
- Dropdown not opening on Query page navigation - **Fixed**

**Pull request merged**
