### PR TITLE
chore: validate-divider

### PR DESCRIPTION
**Pull request by tanvibhakta**
## Description

This PR generates a DP for [the divider spacing PR](https://github.com/appsmithorg/design-system/pull/600). QA needs to go through the list of places divider is used in the image in the PR linked, and check whether or not space is being removed. 

#### PR fixes following issue(s)
Fixes # (issue number)
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
- [ ] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by KelvinOm — APPROVED** [review]

**Comment by shadabbuchh** [comment]
The above DP is throwing an Internal server error in intermittently.
Screenshot 2023-09-01 at 4 02 02 PM


Also noticed divider adding space in the reconnect datasource modal.
Screenshot 2023-09-01 at 3 52 04 PM


@tanvibhakta from the diagram in https://github.com/appsmithorg/design-system/pull/600 it is not clear as to where all the divider component is being used. For me to test all the places divider is being used, I need to know where all it is being used. As discussed I have only checked for the nodes that do not have an outgoing link. Please let me know if the scope of this PR is beyond what we had discussed.

**Comment by shadabbuchh** [comment]
Also there are some places that do not look aesthetic after removing the space around the divider:
Screenshot 2023-09-01 at 4 24 22 PM

And at some places the space is not uniform
Screenshot 2023-09-01 at 4 23 44 PM

**Comment by tanvibhakta** [comment]
This is quite helpful, thanks @shadabbuchh!

**Comment by tanvibhakta** [comment]
closing since we don't have the badnwidth to test this accurately for now.

**Pull request closed without merging**
