### PR TITLE
chore: Update Query view for side by side

### PR DESCRIPTION
**Pull request by hetunandu**
Updates view of Query / Api and JS to not show the header and right side panels in side by side view

fixes: #30658

## Summary by CodeRabbit

- **New Features**
	- Introduced a compact query editor interface for specific action types.
	- Added conditional rendering in various components based on the `isSideBySideEnabled` feature flag.
	- Launched new components for enhanced query editor functionalities, including `QueryEditorCompact`, `FormRender`, `QueryEditorHeader`.

- **Enhancements**
	- Updated selector functions to filter out falsy values, improving data quality.
	- Refined UI and functionality in the API and JS editors, focusing on user experience.

- **Refactor**
	- Removed unused imports and variables, streamlined component structures, and updated UI component placements for clarity and efficiency.
	- Optimized form rendering logic and action execution handling in the query editor.

### CODE REVIEW

**Review by albinAppsmith — DISMISSED** [review]

**Review by ashit-rath — COMMENTED** [review]
@hetunandu Can you merge this in EE and check the Package Editor?  it reuses the code that is refactored in this PR

**Review by albinAppsmith — APPROVED** [review]

**Review by albinAppsmith — APPROVED** [review]

**Review by ashit-rath — APPROVED** [review]

**Pull request merged**
