### PR TITLE
fix: Action selector form getting cut off

### LINKED ISSUE #24369: [Bug]: Slash command text is getting truncated at the bottom while setting up success/failure callbacks at 100% zoom screen
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I am trying to add an event for code scanner widget then slash command text is hidden at the bottom while setting up success/failure callbacks at 100% zoom screen but absolutely looks fine when i reduce screen size to 80%

Expected result : Slash command text should not be cut off and visible on 100% zoom screen.

### Steps To Reproduce

1. Add code scanner widget
2. Go to event section on property pane 
3. Add any event 
4. Add "Set a timer" event for success call backs as shown in below image and observe
Note : make sure browser screen is set to 100%
image

Now reduce browser screen to 80% and observe data is not cut off.
image

### Public Sample App

_No response_

### Environment

Deploy Preview

### Issue video log

_No response_

### Version

Appsmith Business v1.9.22-SNAPSHOT

### PR DESCRIPTION
**Pull request by Druthi**
## Description
fix: Action selector form getting cut off

#### PR fixes following issue(s)
Fixes #24369

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
- [ ] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by Rishabh-Rathod — APPROVED** [review]

**Comment by shwetha-ramesh** [comment]
@Druthi Working as expected.
At 100% zoom
image

**Pull request merged**
