### PR TITLE
feat: added searched address into map center data

### LINKED ISSUE #11781: [Feature]-[120]:Map Widget Enhancement - Bind searched location to input fields without clicking on map
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Add the functionality of binding the address of the searched location from the map widget to an input field, without clicking on the map.

image

### Why should this be worked on?

As an enhancement, this will improve the user experience as it will allow users to search on the Map widget, and display searched fields on other widgets without clicking on the Map widget.

### PR DESCRIPTION
**Pull request by techbhavin**
## Description

> Map Widget Enhancement - Bind searched location to input fields without clicking on map

Fixes #11781

## Type of change

- Bugfix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>

    // Code coverage diff between base branch:release and head branch: feature/issue-11781 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | app/client/src/utils/WorkerUtil.ts | 89.76 **(0.78)** | 72.55 **(1.96)** | 100 **(0)** | 93.33 **(0.95)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.71 **(-0.23)** | 40.83 **(-0.84)** | 36.21 **(0)** | 56.74 **(-0.25)**</details>

### CODE REVIEW

**Review by jsartisan — DISMISSED** [review]

**Comment by YogeshJayaseelan** [comment]
@techbhavin Tested this PR and it is working as expected

**Review by jsartisan — APPROVED** [review]

**Pull request merged**
