### PR TITLE
feat: Clear store values

### PR DESCRIPTION
**Pull request by gitstart**
## Description

At the moment developer can add to store & update store

This Implementation is to allow developer
 - Clear all store value
 - Clear specifics value from store

Fixes https://github.com/appsmithorg/appsmith/issues/11639

## Type of change

- New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Review by rimildeyjsr — APPROVED** [review]

**Comment by ramsaptami** [comment]
LGTM, can be merged to release

**Review by rimildeyjsr — APPROVED** [review]

**Comment by rohan-arthur** [comment]
@rimildeyjsr can you share an example usage for both the new functions? Can they be used directly or with `appsmith.` accessor? 
If usage is direct, then `removeValue` may need a better naming, because every other function that is to do with the store has the word `store` used somewhere, and this would be the only exception. cc @bharath31

**Pull request merged**
