### PR TITLE
feat: release start with data solution

### PR DESCRIPTION
**Pull request by sneha122**
## Description

This PR release start with data onaboarding solution to 50% of new users.

#### PR fixes following issue(s)
Fixes https://github.com/appsmithorg/appsmith/issues/29479
#### Type of change
- New feature (non-breaking change which adds functionality)
>
>
>
- [x] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

## Summary by CodeRabbit

- **Refactor**
  - Simplified the app creation process by removing unnecessary local storage checks.
  - Streamlined analytics event logging during app creation.

- **Chores**
  - Removed unused code related to local storage to enhance performance and maintainability.

### CODE REVIEW

**Review by NilanshBansal — APPROVED** [review]
LGTM

**Comment by AmanAgarwal041** [comment]
When we redirect to the openai datasource, we are not showing any information on the page and it looks confusing.
Screenshot 2023-12-08 at 6 18 52 PM
cc @sneha122 @carinanfonseca

**Pull request merged**
