### PR TITLE
fix: select widget search improvement

### LINKED ISSUE #17003: [Bug]: Select widget crashes when searching using a Numeric Label value
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I have numeric values for label in Select widget and search, the widget crashes

### Steps To Reproduce

https://user-images.githubusercontent.com/31691737/191895870-0e5ae6f4-e3f7-4330-b6ad-1d0d153e7c27.mov

### Public Sample App

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by Tooluloope**
## Description

Updated the `DropdownOption` to allow the label to be either number/string.

I left the `EXPECTED STRUCTURE` as a string because numbers shouldn't be supported by default.

Also added a cypress test to ensure filtering works and `Select.SelectedOptionLabel` outputs the correct type

Fixes #17003

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Cypress test

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by sbalaji1192 — DISMISSED** [review]

**Comment by chandannkumar** [comment]
Tested this PR and working as expected

**Comment by sbalaji1192** [comment]
@souma-ghosh Could you please fix the CI, Will approve post that

**Review by sbalaji1192 — APPROVED** [review]

**Comment by Tooluloope** [comment]
1234rtttyy

**Comment by Tooluloope** [comment]
1234

**Comment by Tooluloope** [comment]
1234

**Comment by Tooluloope** [comment]
1234

**Comment by Tooluloope** [comment]
12345

**Comment by Tooluloope** [comment]
ok-to-test sha=41e1f22

**Comment by Tooluloope** [comment]
ok-to-test sha=41e1f22

**Comment by Tooluloope** [comment]
n

**Comment by Tooluloope** [comment]
123

**Pull request merged**
