### PR TITLE
chore: Updating the graphics for Access control upgrade page

### PR DESCRIPTION
**Pull request by ankitakinger**
## Description

> Updating the graphics for the Access control upgrade page. Also, removing the feature flag.

Fixes [#19072](https://github.com/appsmithorg/appsmith/issues/19072)

## Type of change

- Uptaing images

- Manual

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by albinAppsmith — APPROVED** [review]
Check whether assets can be uploaded to CDN and use the URL

**Comment by ankitakinger** [comment]
@albinAppsmith we might update the images again so I'll take care of moving these to CDN once it's extremely final and not going to change for sure.

**Comment by SatishGandham** [comment]
/perf-test
Testing performance infra, ignore.

**Pull request merged**
