### PR TITLE
feat: Action redesign: Updating the config for MongoDB plugin to use sections and zones format

### PR DESCRIPTION
**Pull request by ankitakinger**
## Description

Action redesign: Updating the config for MongoDB plugin to use sections and zones format

Fixes [#35495](https://github.com/appsmithorg/appsmith/issues/35495)

## Automation

/ok-to-test tags="@tag.All"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/10791215638>
> Commit: 245cde9a4d5cbadfbc8f7fe917aa7c3ba257e306
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=10791215638&attempt=2" target="_blank">Cypress dashboard</a>.
> Tags: `@tag.All`
> Spec:
> <hr>Tue, 10 Sep 2024 17:47:21 UTC

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [ ] No

## Summary by CodeRabbit

- **New Features**
  - Enhanced styling capabilities for dynamic input text controls with new CSS class.
  - Improved layout and organization of UI components in MongoDB plugin with new control types, allowing for more flexible and responsive designs.
  - Added new controls for sorting and limiting criteria in query interfaces.

- **Bug Fixes**
  - Adjusted CSS to remove minimum height and width constraints for better responsiveness.

- **Refactor**
  - Updated control types across various JSON configurations to improve user experience and interface organization.

### CODE REVIEW

**Comment by AmanAgarwal041** [comment]
Is the divider after the command the is required in mongo query editor form ?
Screenshot 2024-09-09 at 11 12 17 AM
@ankitakinger

**Comment by ankitakinger** [comment]
@AmanAgarwal041 Yup, that's intentionally done in all plugin forms. The horizontal rule indicates 2 things:
1. A separate section below
2. The form below the horizontal rule changes as per the command selected

**Comment by ankitakinger** [comment]
Testing completed on EE. Everything looks good.

**Review by AmanAgarwal041 — APPROVED** [review]

**Review by albinAppsmith — APPROVED** [review]

**Pull request merged**
