### PR TITLE
feat: Updates templates filters section in appsmith platform

### PR DESCRIPTION
**Pull request by rahulbarwal**
## Description
Updates templates filters
1. Removes data sources from filters
2. Renames `functions` to `teams`

#### PR fixes following issue(s)
Fixes # (issue number)
#22959

#### Media
Screenshot 2023-05-15 at 10 14 30 PM

#### Type of change

- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Testing
- [x] Cypress

#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by akash-codemonk — APPROVED** [review]

**Comment by shwetha-ramesh** [comment]
@rahulbarwal. Tested DP https://ce-23361.dp.appsmith.com/
`Datasources` filter is hidden
Renamed from Function to Team.
But when user makes a selection from the filter the page crashes. [Demo](https://www.loom.com/share/2f3dda7c6cc849e0bc6be2482614f86d)

**Comment by rahulbarwal** [comment]
@shwetha-ramesh 
Bug has been fixed now, please use this URL to retest: https://appsmith-4d5ob803w-get-appsmith.vercel.app

**Review by akash-codemonk — APPROVED** [review]

**Comment by akash-codemonk** [comment]
cypress/e2e/Regression/ClientSide/OtherUIFeatures/ForkApplication_spec.js is flaky. Will fix this. The third argument needs to be added here https://github.com/appsmithorg/appsmith/blob/release/app/client/cypress/support/Pages/HomePage.ts#LL481C10-L481C33. In the test we are calling with a false  but it is being ignored https://github.com/appsmithorg/appsmith/blob/release/app/client/cypress/e2e/Regression/ClientSide/OtherUIFeatures/ForkApplication_spec.js#L124. The false here will ignore the error message and move on https://cloud.cypress.io/projects/eyxvp8/runs/35480/test-results/59103ec6-df34-4b71-85ba-5233009c9edf/screenshots .

I will fix this separately as it isn't related to this PR. cc @Aishwarya-U-R

**Comment by Aishwarya-U-R** [comment]
@akash-codemonk - Why should we ignore the error message? What does it imply?

**Comment by akash-codemonk** [comment]
> @akash-codemonk - Why should we ignore the error message? What does it imply?

Ignoring this https://cloud.cypress.io/projects/eyxvp8/runs/35480/test-results/59103ec6-df34-4b71-85ba-5233009c9edf/screenshots. We are trying to invite a user but the user is already invited probably by some other test running parallelly, hence we get the error so in that case we just want to ignore it and move to the next step. Will see if I ca n handle it differently as in ignore the error if the user is already invited else if it is any other error we fail.

**Comment by Aishwarya-U-R** [comment]
No, invite another user in that case then. We have CYPRESS_TESTUSERNAME3 & CYPRESS_TESTUSERNAME4 too. Do not skip it.

**Comment by Aishwarya-U-R** [comment]
@akash-codemonk - where are we with respect to fixing the discussed OtherUIFeatures/ForkApplication_spec.js. We have other PR's failing here for the same reason.

**Pull request merged**
