### PR TITLE
feat: Use RenderModes.PREVIEW for preview mode widgets

### LINKED ISSUE #17861: [Task] Make preview mode the same as view mode
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- Use RenderModes to for the preview mode widget rendering such that the view mode and preview mode both render widgets similarly
- This should also reduce the computations done when rendering in preview mode.

### PR DESCRIPTION
**Pull request by riodeuno**
## Description
This update renders the preview mode as a renderMode. This way, a lot of the code paths which otherwise would have otherwise been computed, can be avoided.

Fixes #17861 

## Type of change
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
- If existing tests pass, we haven't regressed on the preview mode features.

### Issues raised during DP testing
- NA

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [NA] I have commented my code, particularly in hard-to-understand areas
- [NA] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [NA] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by Rhitottam** [comment]
HI @riodeuno , i am testing a perf-infra test feature. Can ignore the results. Thank you

**Review by rahulramesha — DISMISSED** [review]
LGTM

**Comment by SatishGandham** [comment]
@riodeuno , switching from edit mode it preview mode is taking 3x time compared to release. Is this expected?

**Comment by riodeuno** [comment]
@SatishGandham Which app did you profile this on? There are the computations for dynamic height which are run when we switch from edit mode to preview mode. This could be the cause. I'd like to eliminate other factors.

**Comment by SatishGandham** [comment]
@riodeuno , I profiled an old aforce app. The results were consistent, 150ms vs 50ms.

Switching back from preview to edit mode was same between release and dp

**Comment by riodeuno** [comment]
Got it, I'll take a look

**Review by marks0351 — APPROVED** [review]

**Review by marks0351 — APPROVED** [review]

**Pull request merged**
