### PR TITLE
test: enhancement tests for captcha

### PR DESCRIPTION
**Pull request by NandanAnantharamu**
Added tests for Recaptcha v2 / v3.

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: test/EnchancementRecaptcha 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 55.72 **(0.01)** | 37.11 **(0.01)** | 35.29 **(0)** | 55.97 **(0)**
 :green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.94 **(0.23)** | 41.67 **(0.84)** | 36.21 **(0)** | 56.99 **(0.25)**</details>

### CODE REVIEW

**Review by Aishwarya-U-R — COMMENTED** [review]
1. Kindly retain previous case - its checking if key is empty - no recaptcha token generation - valid scenario
2. Placeholder for wrong key scenario [as bug exists]

**Review by yatinappsmith — APPROVED** [review]

**Review by yatinappsmith — APPROVED** [review]

**Pull request merged**
