### PR TITLE
fix: NPE during import when ApplicationJson has no action collection

### LINKED ISSUE #27646: NullPointerException: Cannot invoke "java.util.List.size()" because the return value of "com.appsmith.server.dtos.Appli...
Sentry Issue: [APPSMITH-SERVER-3X](https://appsmith.sentry.io/issues/4502466524/?referrer=github_integration)

```
NullPointerException: Cannot invoke "java.util.List.size()" because the return value of "com.appsmith.server.dtos.ApplicationJson.getActionCollectionList()" is null
    at com.appsmith.server.solutions.ce.ImportExportApplicationServiceCEImpl.lambda$importApplicationInWorkspace$111(ImportExportApplicationServiceCEImpl.java:1957)
```

### PR DESCRIPTION
**Pull request by nayan-rafiq**
## Description
This fixes the NPE when the user is trying to import an application JSON that has no action collection.

#### PR fixes following issue(s)
Fixes #27646

#### Media
N/A
#### Type of change
- Bug fix (non-breaking change which fixes an issue)

#### How Has This Been Tested?
- [x] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress

>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by AnaghHegde — COMMENTED** [review]
Can we assert these conditions in test cases as well?

**Comment by nayan-rafiq** [comment]
> Can we assert these conditions in test cases as well?

@AnaghHegde Updated one existing test for the case

**Review by Parthvi12 — APPROVED** [review]

**Comment by Parthvi12** [comment]
Verified the fix by removing actionCollectionList field from JSON and then importing app, works fine.

**Review by AnaghHegde — APPROVED** [review]

**Pull request merged**
