### PR TITLE
FIX #4802 : Color picker inconsistency

### LINKED ISSUE #4802: Consistency in color codes of the color picker
### Description of issue
The green color of the color picker has a RGB value whereas other colors are a HEX value

### Expected result
All colors should follow the same color code

### Actual result

recording

```
Path:      /applications/6013cb2f1ef9d52f963c7768/pages/60379b2e02c7cd7b260da470/edit
Browser:   Chrome 90.0.4430.212 on Mac OS 10.15.7
Viewport:  1680 x 914 @2x
Language:  en-GB
Cookies:   Enabled
```

[View on BrowserStack](https://live.browserstack.com/dashboard#url=https%3A%2F%2Fdeploy-preview-4685--appsmith-editor-ce.netlify.app%2Fapplications%2F6013cb2f1ef9d52f963c7768%2Fpages%2F60379b2e02c7cd7b260da470%2Fedit&os=OS+X&os_version=Catalina&browser=Chrome&browser_version=90.0&resolution=1680x914&speed=1&start=true)

Submitted from [Netlify Deploy Preview #4685](https://deploy-preview-4685--appsmith-editor-ce.netlify.app/applications/6013cb2f1ef9d52f963c7768/pages/60379b2e02c7cd7b260da470/edit)

### PR DESCRIPTION
**Pull request by vibhandikyash**
## Description
The green color of the color picker has a RGB value whereas other colors are a HEX value

Fixes #4802 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>
No changes to code coverage between the base branch and the head branch</details>

### CODE REVIEW

**Review by hetunandu — APPROVED** [review]

**Comment by somangshu** [comment]
@vibhandikyash please check the failing tests here!

**Review by somangshu — APPROVED** [review]
LGTM

**Comment by somangshu** [comment]
@yatinappsmith @NandanAnantharamu Test failing here are failing globally.

@vibhandikyash we should have the fix in the release soon.

**Review by somangshu — APPROVED** [review]

**Comment by somangshu** [comment]
@vibhandikyash Need a latest release merged here to fix the failing test

**Comment by somangshu** [comment]
@vibhandikyash this should pass now, Can you merge the latest release here and notify me after that.

**Review by somangshu — APPROVED** [review]

**Comment by somangshu** [comment]
Attempting jobs rerun - failing test

**Pull request merged**
