### PR TITLE
fix: access token refreshed if expiry time not present

### LINKED ISSUE #30239: [Bug]: Salesforce Auth Token doesn't refresh automatically
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

App Link: https://internal.appsmith.com/app/license-tracker/clients-645b6543a56f84769dcbc32d/edit
Issue Description: https://theappsmith.slack.com/archives/CNQ9Q91C0/p1702972094026239

### Steps To Reproduce

https://theappsmith.slack.com/archives/CNQ9Q91C0/p1702972094026239

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

v1.9.59-SNAPSHOT

### PR DESCRIPTION
**Pull request by NilanshBansal**
#### PR fixes following issue(s)
Fixes #30239 

#### Type of change
- Bug fix (non-breaking change which fixes an issue)

- [ ] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

## Summary by CodeRabbit

- **Bug Fixes**
    - Adjusted the authentication logic to treat null expiration as an expired session for improved security.

### CODE REVIEW

**Comment by sneha122** [comment]
@NilanshBansal @nidhi-nair I tried creating Monday OAuth2 datasource on the DP, for which I created application on monday.com and entered  all required details. I followed all steps correctly, but authorization is failing with `something went wrong` as shown in video. @nidhi-nair Please let me know if I am missing some step in this process which is causing this error. 

https://github.com/appsmithorg/appsmith/assets/30018882/c569e8df-46de-4f16-a57e-8767609bf2cc

**Comment by sneha122** [comment]
Keeping the DP active

**Comment by sneha122** [comment]
Keeping the DP active for use by sales team

**Comment by sneha122** [comment]
Keeping the DP active for use by sales team

**Comment by NilanshBansal** [comment]
Closing this as the [permanent fix](https://github.com/appsmithorg/appsmith/pull/30866) is merged to release.

**Pull request closed without merging**
