### PR TITLE
fix: retain columns on query change in deployed app

### LINKED ISSUE #23969: [Bug]: Change in table data only shows columns that are common between the query when in deploy mode
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Whenever there is a change in table data, columns that are common between the previous and the current table data is displayed. This behaviour is observed in deploy mode.

The expected behaviour is that the change in query/table data should reflect the correct columns in table when in deploy mode.

Discord query link: https://app.frontapp.com/inboxes/teams/folders/15690316/archived/79396567564

### Steps To Reproduce

1. Dnd a table widget and two buttons
2. Bind the table wdiget's tableData property with a JS expression like this: `{{appsmith.store.test === '0' ? query1.data : query2.data}}`
3. Change the appsmith store variable `test` when either of the above two buttons are clicked.
4. Deploy the app.
5. Change the data of table by click on these buttons.
6. Refresh the page.
7. Observe that on click of buttons again the above issue occurs

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by keyurparalkar**
## Description
This PR fixes the behaviour mentioned in the issue. 

This issue was happening due to table widget's column order wasn't updating. It wasn't updating because we maintained column orders in widget's DSL as well as in the meta property. Whenever the table data changes, the widget updates `columnOrder` property in the DSL but this gets overridden if you have the same property in the widget's meta property.

To solve this we update the table widget's sticky and column order property via `super.updateWidgetProperty`. We have also refactor the hydration logic for sticky columns such that table widget's DSL acts as a source of truth all the time.

Fixes #23969
#23827

#### Type of change
- Bug fix (non-breaking change which fixes an issue)

## Testing
- [x] Manual
    - To test that the column freeze functionality works as expected in edit as well as deployed mode
    - To check column freeze functionality works as expected when table query changes
    - To check if the column reordering is working as expected in view mode
- [ ] Jest
- [x] Cypress
    - should test that the number of columns needs to be same when table data changes in deployed app 
>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by sbalaji1192 — APPROVED** [review]

**Comment by laveena-en** [comment]
@keyurparalkar Columns aren’t staying frozen when table data changes: https://www.loom.com/share/0f94ee154b7b46998c4588ef775e679f

Columns that are re-ordered are reverting to their initial states when table data changes: https://www.loom.com/share/7b368a6e9ba24fb7922d7b9ac0df61b9

Columns aren’t staying frozen in edit mode either: https://www.loom.com/share/d75fbd1724744137bf3d62b111aa5033

**Comment by keyurparalkar** [comment]
@laveena-en all the above callouts are expected behaviour. 

In edit mode, since the table data changes we also re-construct the primary columns. During this process the column definitions are also reconstructed thus columns are not sticky. Exception here is that columns that are common between query change will retain their stickiness.

In view/ deployed mode, since the table data is changing therefore we also reset the column order in local storage. Thus defaulting what widget's DSL dictates.

**Comment by keyurparalkar** [comment]
@laveena-en I found a buggy scenario apart from the above callouts which is as follows:
* Load the app in deployed mode.
* Switch between queries.
* Freeze one of the columns 
* Refresh the page.
* It is observed that we loose the frozen columns

CC: @sbalaji1192

**Comment by laveena-en** [comment]
> @laveena-en I found a buggy scenario apart from the above callouts which is as follows:
> 
> * Load the app in deployed mode.
> * Switch between queries.
> * Freeze one of the columns
> * Refresh the page.
> * It is observed that we loose the frozen columns
> 
> I have pushed the fix for the same.
> 
> CC: @sbalaji1192

Apologies, missed adding this loom in the prev QA callout. Added the steps here: https://www.loom.com/share/a33cd6f4577a4e429a40c3cb0e101a8d?sid=4a76200e-d0bc-4a9d-ac16-73ee1dcc12f8

**Review by sbalaji1192 — APPROVED** [review]

**Comment by laveena-en** [comment]
@keyurparalkar As discussed, re-ordered columns aren’t staying intact when table data changes: https://www.loom.com/share/d482eb0b00494e78bb410706d9b0be0d?sid=126cb089-c4b4-4729-9613-f448f8623a24

**Comment by keyurparalkar** [comment]
> @keyurparalkar As discussed, re-ordered columns aren’t staying intact when table data changes: https://www.loom.com/share/d482eb0b00494e78bb410706d9b0be0d?sid=126cb089-c4b4-4729-9613-f448f8623a24

@laveena-en this doesn't seems to be a valid scenario. Can you tell a real case scenario if this might occur?

CC: @sbalaji1192

**Comment by chandannkumar** [comment]
Tested this PR and LGTM
- Tested on older apps as well

**Comment by keyurparalkar** [comment]
> > @keyurparalkar As discussed, re-ordered columns aren’t staying intact when table data changes: https://www.loom.com/share/d482eb0b00494e78bb410706d9b0be0d?sid=126cb089-c4b4-4729-9613-f448f8623a24
> 
> @laveena-en this doesn't seems to be a valid scenario. Can you tell a real case scenario if this might occur?
> 
> CC: @sbalaji1192

@laveena-en as discussed this is not a valid scenario because in deployed mode we prefer what user's want to see

**Review by sbalaji1192 — APPROVED** [review]

**Comment by laveena-en** [comment]
Sanity test done post code changes to resolve failing test. LGTM!

**Pull request merged**
