### PR TITLE
fix: Race condition issue of meta reducer update

### LINKED ISSUE #10818: [Bug]: Race condition in updating meta property of widgets during first evaluation
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When Currency Input gets mounted, it formats the text and stores it in meta property. This value gets overwritten by the evaluations when it updates the meta property of the widget with defaultText during first evaluations. As a result currency input value and `CurrencyInput.text` are differing. Refer loom
[LOOM DEMO](https://www.loom.com/share/12a2ac078d9a458c9dbe7636f86f0349)

### Steps To Reproduce

1. Add a currency widget
2. Set default value as 10000
3. Refresh the entire application. Currency input has 10,000 (formatted) as value but `CurrencyInput1.text` has 10000 (unformatted).

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by Rishabh-Rathod**
## Description

Fixes #10818

Changing the logic to only update metaReducer values when there is a change between previous dataTree and current data tree. 

**Caveat** - This logic assumes that when a widget property's default and meta value both change, it is okay to give preference to the default value and clear the meta.

For meta-evaluation changes refer - https://github.com/appsmithorg/appsmith/pull/10401

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/metaEval-raceCondition 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 54.94 **(0)** | 36.38 **(-0.01)** | 34.61 **(0)** | 55.35 **(0)**
 :green_circle: | app/client/src/actions/metaActions.ts | 78.57 **(13.57)** | 100 **(100)** | 25 **(5)** | 70 **(13.75)**
 :green_circle: | app/client/src/reducers/entityReducers/metaReducer.ts | 33.33 **(0.83)** | 0 **(0)** | 20 **(0)** | 35 **(0.79)**
 :red_circle: | app/client/src/workers/evaluationUtils.ts | 58.37 **(-0.04)** | 56.61 **(0)** | 64.52 **(0)** | 57.7 **(-0.05)**</details>

### CODE REVIEW

**Comment by Rishabh-Rathod** [comment]
The failing test is not relevant to the above changes.

**Review by eco-monk — APPROVED** [review]
We're doing selective updates of meta value instead of updating all the widgets every-time.
This is good to go.

**Pull request merged**
