### PR TITLE
fix: crashing of menu widget in list widget + "type" of undefined error

### LINKED ISSUE #6377: TypeError: Cannot read property 'type' of undefined
Sentry Issue: [APPSMITH-10E](https://sentry.io/organizations/appsmith/issues/2551124993/?referrer=github_integration)

```
TypeError: Cannot read property 'type' of undefined
  at checkIfPastingIntoListWidget (sagas/WidgetOperationUtils.ts:326:24)
  at call (sagas/WidgetOperationSagas.tsx:1517:26)
...
(17 additional frame(s) were not displayed)
```

### LINKED ISSUE #6851: [Bug] List goes blank with Menu Widget
## Description

A user reported that the list widget goes blank when the menu widget is added to it

### Steps to reproduce the behaviour:

1. Drag a list widget
2. Add a menu widget to one of the list items
3. Configure one of the menu options
4. Set the onClick to {{ }}
5. The List goes blank

### LINKED ISSUE #6943: [Bug] TypeError: Cannot read property 'type' of undefined
Sentry Issue: [APPSMITH-11N](https://sentry.io/organizations/appsmith/issues/2579805827/?referrer=github_integration)

```
TypeError: Cannot read property 'type' of undefined
  at None (widgets/ListWidget/ListWidget.tsx:102:27)
  at Array.map (<anonymous>)
  at generateChildrenDefaultPropertiesMap (widgets/ListWidget/ListWidget.tsx:99:29)
  at componentDidUpdate (widgets/ListWidget/ListWidget.tsx:168:12)
...
(45 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by jsartisan**
The list widget was crashing when menu widget was used in it. This PR fixes it.

## Fixes
Fixes #6851
Fixes #6377 
Fixes #6943

## Type of changes
- Bug fix 

## How Has This Been Tested?
- Manually checked

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/list-widget-bugs-2 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 54.83 **(0.08)** | 36.63 **(0.08)** | 33.86 **(0.06)** | 55.45 **(0.08)**
 :green_circle: | app/client/src/resizable/index.tsx | 59.52 **(0)** | 52.17 **(15.21)** | 35 **(0)** | 61.64 **(0)**
 :green_circle: | app/client/src/sagas/WidgetOperationUtils.ts | 61.51 **(0)** | 40.11 **(1.56)** | 55.81 **(0)** | 60.83 **(0)**
 :green_circle: | app/client/src/utils/hooks/usePositionedContainerZIndex.ts | 100 **(0)** | 92.86 **(7.15)** | 100 **(0)** | 100 **(0)**
 :green_circle: | app/client/src/widgets/ContainerWidget/component/index.tsx | 93.75 **(0)** | 72.5 **(7.5)** | 100 **(0)** | 93.75 **(0)**
 :green_circle: | app/client/src/widgets/ListWidget/widget/index.tsx | 61.97 **(12.5)** | 27.98 **(3.4)** | 54.17 **(12.5)** | 60.38 **(12.65)**</details>

### CODE REVIEW

**Review by marks0351 — DISMISSED** [review]

**Comment by vivekverma2312** [comment]
Tested 6851 and working fine. As we do not have steps to repro for #6943 did a round of sanity around it.

**Review by marks0351 — APPROVED** [review]

**Comment by mohanarpit** [comment]
@jsartisan Can we merge this PR in? A linked issue got closed because it was stale. Would like to avoid that from happening again.

**Comment by jsartisan** [comment]
> @jsartisan Can we merge this PR in? A linked issue got closed because it was stale. Would like to avoid that from happening again.

Yes. We will be merging it today.

**Review by marks0351 — APPROVED** [review]

**Review by rahulramesha — APPROVED** [review]
Approving for tests

**Pull request merged**
