### PR TITLE
BUG-4058 : Inconsistence in the meta properties fallbacks in widgets

### LINKED ISSUE #4058: [Bug] Inconsistence in the meta properties fallbacks in widgets
## Description
In the input widget, when the `defaultText` is updated, the bindings all update. However, when we clear out the text in the input widget, the bindings propagate as empty text.
This is not consistent in the date picker widget. The `defaultDate` is always a fallback when the date is cleared from the widget.

There are two solutions here:
- [ ] We should make this consistent by making sure that all meta properties behave like they do in the datepicker widget's `defaultDate`.  (fallback to default values if they exist)
- [x] Or fix this for the date picker widget.

### Steps to reproduce the behaviour:
Add steps to reproduce this behaviour, include console / network logs & screenshots
1. Add an input widget and a datepicker widget. Add `defaultText` and `defaultDate` respectively in the property panes
2. Add two text widgets, each binding to the input widget's text and datepicker's `selectedDate` respectively.
3. Try changing the text widget by making it empty and clearing the date from the date picker widget.

### Important Details
- Release 1.4.9

### PR DESCRIPTION
**Pull request by wmdev0808**
## Description
Make empty the binding value of date picker widget when it is cleared

Fixes #4058 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/bug-4058-widget-meta-property-fallback 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 53.84 **(0.02)** | 35.78 **(-0.01)** | 32.49 **(0)** | 54.41 **(0)**
 :red_circle: | app/client/src/components/designSystems/blueprint/DatePickerComponent.tsx | 27.03 **(-1.14)** | 2.9 **(-0.27)** | 6.25 **(0)** | 26.39 **(-1.15)**
 :red_circle: | app/client/src/components/designSystems/blueprint/DatePickerComponent2.tsx | 27.78 **(-1.21)** | 3.17 **(-0.11)** | 5.88 **(0)** | 27.14 **(-1.22)**
 :red_circle: | app/client/src/components/propertyControls/DatePickerControl.tsx | 26.32 **(-0.95)** | 4.35 **(-0.41)** | 13.33 **(0)** | 25.93 **(-0.99)**
 :green_circle: | app/client/src/sagas/ErrorSagas.tsx | 68.14 **(3.54)** | 52.38 **(4.76)** | 50 **(0)** | 68.63 **(3.92)**
 :green_circle: | app/client/src/sagas/CommentSagas/index.ts | 45.45 **(3.03)** | 17.86 **(0)** | 50 **(0)** | 44.12 **(1.96)**</details>

### CODE REVIEW

**Review by somangshu — APPROVED** [review]

**Review by somangshu — CHANGES_REQUESTED** [review]
@wmdev0808 This doesn't function as desired in the Deploy preview, The Date picker selectedDate value, when cleared, should be empty and not fall back to the default. 

Also with this condition, we never reach the `defaultValue` Condition.

@riodeuno please correct me if I am wrong. One clearing the datepicker the datepicker.selectedDate should also be empty and not fallback to default

**Comment by riodeuno** [comment]
@somangshu Yes, the `selectedDate` and `formattedDate`
Screenshot 2021-04-28 at 2 42 50 PM
 should both become empty when the date is cleared in the widget.

**Comment by somangshu** [comment]
@wmdev0808 the `formattedDate` and `selectedDate`, both needs to be empty when we clear the datepicker.

Currently, if I set a default date on an empty datepicker, the `selectedValue` does not get cleared.

@vicky-primathon what are your thoughts here, since you are working on the similar lines

https://user-images.githubusercontent.com/11089579/116389776-fa8c4b80-a83a-11eb-848b-6d5f0e29df74.mov

**Comment by vicky-primathon** [comment]
@somangshu, yes there should be a consistency around both formattedDate and selectedDate properties. Either both should become empty or take the default date value when the value is cleared by user.

**Review by riodeuno — APPROVED** [review]

**Comment by riodeuno** [comment]
@wmdev0808 We're fixing this in a manner which resolves the core problem for the end user where clearing the datepicker did not clear the `selectedDate` and `formattedDate`.

While the issue we discussed, where these values did not clear immediately after updating the `defaultDate` is something which needs platform changes and will be fixed as a separate issue #5052

**Comment by somangshu** [comment]
@YogeshJayaseelan @vivekverma2312 this will need to be tested well in view mode, Also we need to look out for any other cases failing in the edit mode.

**Comment by somangshu** [comment]
@wmdev0808 please merge latest release here, Failing test fixes are availabel here

**Review by somangshu — DISMISSED** [review]

**Comment by vivekverma2312** [comment]
@wmdev0808 If I clear the date field using keyboard action then the dates are changing to default date on calendar and for both` formattedDate` and `selectedDate`.

https://www.loom.com/share/0b1e89d2e17044bfb3e003b41ccaedf8

**Comment by somangshu** [comment]
> @wmdev0808 If I clear the date field using keyboard action then the dates are changing to default date on calendar and for both` formattedDate` and `selectedDate`.

@riodeuno another challenge here!

**Comment by riodeuno** [comment]
> @wmdev0808 If I clear the date field using keyboard action then the dates are changing to default date on calendar and for both formattedDate and selectedDate.

@wmdev0808 What is the value that we are setting in the `onDateSelected` when we're clearing it using the keyboard?

**Comment by wmdev0808** [comment]
> > @wmdev0808 If I clear the date field using keyboard action then the dates are changing to default date on calendar and for both formattedDate and selectedDate.
> 
> @wmdev0808 What is the value that we are setting in the `onDateSelected` when we're clearing it using the keyboard?

@riodeuno it is just empty string, ''

**Comment by somangshu** [comment]
@riodeuno any update on this. The issue is not fixed in the mentioned branch

**Comment by somangshu** [comment]
This needs to close with reference from #5382.

**Comment by somangshu** [comment]
@vicky-primathon when you are done making changes here please push this to QA pipeline again

**Comment by vivekverma2312** [comment]
@wmdev0808 Clear functionality is working but the text in `{{DatePicker1.selectedDate}}` is sowing wrong. It's selected day
-1. If we select 15th July then 14th July is showing.
Screenshot 2021-07-12 at 6 14 06 PM

**Comment by vicky-primathon** [comment]
> @wmdev0808 Clear functionality is working but the text in `{{DatePicker1.selectedDate}}` is sowing wrong. It's selected day
> -1. If we select 15th July then 14th July is showing.
> Screenshot 2021-07-12 at 6 14 06 PM

@vivekverma2312  does formatted date shows up correctly. SelectedDate property could be showing -1 day from formatted day because of timezone difference.

**Comment by vivekverma2312** [comment]
@vicky-primathon yes formatted date is showing correctly.

**Comment by vicky-primathon** [comment]
> @vicky-primathon yes formatted date is showing correctly.

@vivekverma2312  Value of selectedDate is correct. Try binding selectedDate property in a Text widget as {{moment(DatePicker1.selectedDate).format("YYYY-MM-DD HH:mm")}}

**Comment by vivekverma2312** [comment]
@vicky-primathon Thanks, I had not used time zone change while testing. After checking that it is working fine. This can be closed and merged into release.

**Review by riodeuno — APPROVED** [review]

**Pull request merged**
