### PR TITLE
fix: Map widget zoom control suffix

### LINKED ISSUE #24819: [Bug]: Map widget zoom level
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Map widget : error double '%' when entry data zoom level.
image

### Steps To Reproduce

1. Key data in text zoom level
2. Map not display and  double '%' and can't delete or change

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

1.9.23

### PR DESCRIPTION
**Pull request by albinAppsmith**
## Description

PR fixes the zoom level control suffix getting appended twice in the map widget property pane. Also this PR has fixed the text getting selected behaviour while clicking on add and subtract icon inside the number input.

#### PR fixes following issue(s)
Fixes #24819

#### Media

https://github.com/appsmithorg/appsmith/assets/87797149/ec6f4a0b-b428-492b-b6c5-6dff97f4247a

#### Type of change

- Bug fix (non-breaking change which fixes an issue)

## Testing

- [ ] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by KelvinOm — DISMISSED** [review]
LGTM

**Review by marks0351 — DISMISSED** [review]

**Comment by albinAppsmith** [comment]
@Sripriya93 Can you validate this PR? All the number input and steps field in property pane needs to be tested here.

**Comment by shadabbuchh** [comment]
@albinAppsmith if I remember correctly, the number input with step control is used at only 1 place (inside map widget) in property pane. In case it is being used some other place as well, can you please let us know where exactly?

**Comment by albinAppsmith** [comment]
@shadabbuchh I see only map widget for now.

**Comment by Sripriya93** [comment]
We have few more issues with the Map widget
1) When we click on "+" or "-" in the property pane, we are able to see the Map goes blank
2) When we click on "+" or "-" inside the Map widget and drop another Map widget we are able to see that the controls disappear
3) Controls inside the Map widget works fine if we don't touch the controls in Property pane

@albinAppsmith @rohitagarwal88 @shadabbuchh 

https://github.com/appsmithorg/appsmith/assets/104895602/8b8e85c1-7c20-401c-981d-bdbf20c6b436

**Comment by Sripriya93** [comment]
QA completed. Moving to done.

**Pull request merged**
