### PR TITLE
chore: intercom trigger added for gsheets auth failure

### LINKED ISSUE #23625: [Task]: Check if DATASOURCE_AUTHORISE_RESULT event is correctly emitted for all scopes of gsheets
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- Check if DATASOURCE_AUTHORISE_RESULT event is correctly emitted for all scopes of gsheets
- Check if it can be combined with existing event of DATASOURCE_AUTH_COMPLETE

### PR DESCRIPTION
**Pull request by sneha122**
## Description

- This PR adds intercom trigger for a case when google sheets datasource authorisation fails, either due to permissions or not selecting any files.  [Please check the intercom message CC: @rohan-arthur @sribalajig  ]
Screenshot 2023-05-23 at 9 22 37 PM

- This PR also de-duplicates the authorisation completion event. For Limiting gsheet project, `DATASOURCE_AUTHORIZE_CLICK` new analytical event was added, to get the authorisation result, but we already had existing event called `DATASOURCE_AUTH_COMPLETE`, so this PR removes `DATASOURCE_AUTHORIZE_CLICK` and instead modifies `DATASOURCE_AUTH_COMPLETE` to contain extra data.

- This PR also adds file picker specific events like `GOOGLE_SHEET_FILE_PICKER_INITIATED` and `GOOGLE_SHEET_FILE_PICKER_LOADED`.

#### PR fixes following issue(s)
Fixes #23625 
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
#### Type of change
- Chore (housekeeping or task changes that don't impact user perception)

- [ ] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Comment by sbalaji1192** [comment]
@sribalajig Please check the description.

**Comment by rohan-arthur** [comment]
@sneha122 this message looks good! Thanks for the quick addition and the detailed PR description.

**Comment by tanvibhakta** [comment]
ads review not needed here 👍

**Review by AmanAgarwal041 — DISMISSED** [review]

**Review by AmanAgarwal041 — APPROVED** [review]

**Pull request merged**
