### PR TITLE
fix: add ellipsis when the page name is longer than width 

### LINKED ISSUE #9969: [Bug]: Long page names gets truncated abruptly in view mode
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When page names have more characters it gets truncated abruptly in view mode.

Screenshot 2021-12-23 at 5 21 22 PM

### Steps To Reproduce

-

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by vicky-primathon**
## Description

Fixes #9969 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/truncate-page-name 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 55.42 **(-0.03)** | 36.99 **(-0.02)** | 35.3 **(-0.09)** | 55.8 **(-0.04)**
 :red_circle: | app/client/src/components/ads/StepComponent.tsx | 40.91 **(-52.19)** | 66.67 **(-23.33)** | 0 **(-100)** | 40.91 **(-52.19)**
 :red_circle: | app/client/src/constants/IconConstants.tsx | 100 **(0)** | 83.33 **(-4.17)** | 100 **(0)** | 100 **(0)**
 :red_circle: | app/client/src/icons/ControlIcons.tsx | 68.42 **(-1.5)** | 100 **(0)** | 35.38 **(-3.08)** | 68.42 **(-1.5)**
 :red_circle: | app/client/src/pages/AppViewer/viewer/PageTabs.tsx | 31.48 **(0)** | 23.08 **(-1.92)** | 0 **(0)** | 34 **(0)**
 :green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.94 **(0.23)** | 41.67 **(0.84)** | 36.21 **(0)** | 56.99 **(0.25)**</details>

### CODE REVIEW

**Review by sbalaji1192 — APPROVED** [review]

**Comment by shwetha-ramesh** [comment]
@vicky-primathon tested this PR. DP looks good. Long page name now is truncated and ellipsis . . . is added and on hover full page name is displayed
image

**Pull request merged**
