### PR TITLE
fix: replacing onInteractOutside with onPointerDownOutside

### LINKED ISSUE #24820: [Bug]: Deleting branch in git connected app doesn't work in Firefox
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

For git connected application, clicking kebab menu icon beside branch name doesn't do anything and user can't delete branch. This behaviour is observed in **Firefox** browser only.

### Steps To Reproduce

1. Go to git connected application in Firefox
2. Click on the bottom bar
3. Click on the 3 dots beside branch name
4. Observe it doesn't do anything

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by brayn003**
## Description
While switching branches, the ellipsis (more) button is unresponsive for Firefox. It is working fine on Chrome. This PR fixes the issue.
The underlying issue can be pointed to RadixUI library, the `onInteractOutside` seems to bug out in Firefox

PR fixes following issue(s)
Fixes #24820 

#### Media

Before:
image

After:
image

#### Type of change
- Bug fix (non-breaking change which fixes an issue)

#### How Has This Been Tested?
- [x] Manual
- [ ] Jest
- [ ] Cypress

#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Comment by brayn003** [comment]
Test cases already exists in this file - [app/client/cypress/e2e/Regression/ClientSide/Git/GitSync/DeleteBranch_spec.js](https://github.com/appsmithorg/appsmith/blob/fix/switch-branch-options/app/client/cypress/e2e/Regression/ClientSide/Git/GitSync/DeleteBranch_spec.js)

**Comment by Parthvi12** [comment]
@brayn003 Verified the changes on DP, and issue is fixed, added the label.

**Review by hetunandu — APPROVED** [review]

**Pull request merged**
