### PR TITLE
fix: Added index.d.ts file to enable auto code completion for custom commands in Cypress tests

### PR DESCRIPTION
**Pull request by gurudattgd04**
## Description
This PR contains adding a new file index.d.ts file which enable the Auto Code completion for the Cypress custom commands.

Currently the IDE like VSCode cannot detect the custom commands added and one needs to search the command manually in commands.js file and then use it

## Summary by CodeRabbit

- **New Features**
	- Introduced TypeScript declarations for Cypress custom commands to enhance API interactions, user authentication, form interactions, navigation, testing utilities, and container management in testing environments.

### CODE REVIEW

**Comment by gurudattgd04** [comment]
@nidhi-nair Can i please request your time to review this PR or redirect to the appropriate person for this ? Thanks in advance

**Comment by nidhi-nair** [comment]
Thanks for raising this PR @gurudattgd04 ! Seems pretty useful. Let me get somebody from my team to take a closer look. Also, welcome to the Appsmith contributors' pool, it's a party! 🙂

**Comment by gurudattgd04** [comment]
> Thanks for raising this PR @gurudattgd04 ! Seems pretty useful. Let me get somebody from my team to take a closer look. Also, welcome to the Appsmith contributors' pool, it's a party! 🙂

Thanks a lot :)

**Review by sarojsarab — DISMISSED** [review]
Thanks for your contribution! It'll simplify things for our existing JS specs.

**Comment by nidhi-nair** [comment]
@gurudattgd04 looks like there is some linting trouble with your PR. Could you please fix that and we'll zip your PR through.

**Comment by gurudattgd04** [comment]
> @gurudattgd04 looks like there is some linting trouble with your PR. Could you please fix that and we'll zip your PR through.

Sure, i'm working on the linting issue but could you please let me know know why PR Automation test suite / parse-tags (pull_request) is failing and how i can resolve that :)  thank you

**Comment by nidhi-nair** [comment]
Our automation required you to retain the Automation section in the PR template, and add the ok-to-test Github label when the PR is ready to be tested. However, since this PR does not really touch product code / test suite, we can consider it exempt from running CI. I'll force merge your PR once the other checks pass.

**Review by nidhi-nair — APPROVED** [review]

**Pull request merged**
