### PR TITLE
Horizontal scrollbars are not required for default table widget

### LINKED ISSUE #4242: [Feature] Default table widget should not have any scrollbars
## Summary

As a user, When I drag and drop a table widget, I should not see any scrollbars by default. 

## Motivation

Showing a scrollbar on the default view can leave an untidy experience for the end-user.

## Additional Context

The current default looks like this 
Screenshot 2021-04-30 at 3 21 01 PM

- We wish to reduce the column width to fit all the column in the default view
- We wish to increase the table size so that there is no scroll in the header value.
- In any case, the vertical scrollbar on the body should not occur as well. 

The new default should look like this:
Screenshot 2021-04-30 at 3 21 08 PM

### PR DESCRIPTION
**Pull request by vicky-primathon**
## Description
Increase width of default table widget so that horizontal scrollbars are not required

Fixes #4242 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>
No changes to code coverage between the base branch and the head branch</details>

### CODE REVIEW

**Review by somangshu — APPROVED** [review]
Works on deploy preview, Approving to run tests

**Comment by vivekverma2312** [comment]
@vicky-primathon Deploy Preview is tested and working fine. Good to go in release.

**Review by somangshu — APPROVED** [review]
Approving to run tests

**Comment by somangshu** [comment]
@vicky-primathon merge latest release, There is a resolve for the test fail

**Pull request merged**
