### PR TITLE
fix: Page name cutoff

### LINKED ISSUE #19984: [Bug]: Page name is cut off in Preview mode
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Page name is cut off in Preview mode
image

### Steps To Reproduce

1. Create an application
2. Add 2 pages with long names
3. Click on _Preview_ button and observe the page names 

### Public Sample App

_No response_

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by dhruvikn**
## Description
Previously, page names were being hidden behind overflow, and additional "..." was appended if they were long. This made the truncation look unnatural at times. We now use the CSS' text-overflow ellipsis property to avoid this.

CleanShot 2023-05-16 at 16 09 41@2x

#### PR fixes following issue(s)
Fixes #19984

#### Type of change
- Bug fix (non-breaking change which fixes an issue)

#### How Has This Been Tested?
- [x] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [x] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [x] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by jsartisan — APPROVED** [review]

**Comment by kamakshibhat-appsmith** [comment]
LGTM !

**Review by jsartisan — APPROVED** [review]

**Comment by chandannkumar** [comment]
Tested this PR and LGTM

**Pull request merged**
