### PR TITLE
fix: schema accordions don't open on search, placeholder for search input

### LINKED ISSUE #28750: [Bug]: Datasource schema accordions opened on search, clearing search
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Notion issues: 
- [All tables in schema get expanded after clearing search](https://www.notion.so/appsmith/Test-Party-datasource-previews-bcb0d3a39c2343a2a36a80e3f481cad6?p=3fff405e22124068b334fb514d11d6e3&pm=s)
- [When I search for a table, say I have 100 tables whose name starts with data, and I search for data, it shows all tables in the schema, but expands all tables, this is very annoying, is this intentional?](https://www.notion.so/appsmith/Test-Party-datasource-previews-bcb0d3a39c2343a2a36a80e3f481cad6?p=d702ff6ce83544b4bd541379ed04093c&pm=s)
- [Search box placeholder says search for table or attribute, but when I search using attribute, it does not show any records, should we fix the placeholder text?](https://www.notion.so/appsmith/Test-Party-datasource-previews-bcb0d3a39c2343a2a36a80e3f481cad6?p=24aa2ddff4994ad9a4aebf3517c579e0&pm=s)

### Steps To Reproduce

Follow each notion doc

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

Both

### PR DESCRIPTION
**Pull request by AmanAgarwal041**
## Description
This pr fixes:
- Let schema table accordions be closed on searching table
- Search placheholder changed to `Search for table`

#### PR fixes following issue(s)
Fixes #28750 
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
- [ ] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by sneha122 — APPROVED** [review]

**Comment by rohan-arthur** [comment]
tested this, LGTM

**Pull request merged**
