### PR TITLE
fix: tooltip for the orange deviation dot prevent overflow out of screen fixed

### LINKED ISSUE #17604: [Bug]: The tooltip for the orange deviation dot in property pane is moving out of the screen
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If the property name is a little long and the user has selected a value that is different from the theme, the deviated form theme orange dot appears. When hovering over it, the tooltip overflows from the screen.

image

### Steps To Reproduce

1. Open release.app.appsmith.com / create a fresh FE build from release.
2. DnD a text widget.
3. Change the text of the text widget to something lengthy like - 
> Lorem ipsum, in graphical and textual context, refers to filler text that is placed in a document or visual presentation. Lorem ipsum is derived from the Latin "dolorem ipsum" roughly translated as "pain itself".
4. Select **Overflow Text** in the property pane to **Truncate text**
5. Go to the style property pane and select any color in the "Truncate button color".
6. Hover over the orange dot and observe the tooltip overflowing.

https://user-images.githubusercontent.com/22471214/196107193-0fab95c9-9349-4d15-a131-0d44426adca4.mp4

### Public Sample App

_No response_

### Version

Appsmith Release - Appsmith v1.8.5-SNAPSHOT

### PR DESCRIPTION
**Pull request by iSatVeerSingh**
## Description

This PR fixes the tooltip overflows from the screen when hovering on it.
If the property name is a little long and the user has selected a value that is different from the theme, the deviated form theme orange dot appears. When hovering over it, the tooltip overflows from the screen.

Fixes #17604

Media
tooltip fix

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manual
- Jest

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by dhruvikn — DISMISSED** [review]

**Review by riodeuno — APPROVED** [review]
Looks good to me. Thanks for your contribution @iSatVeerSingh

**Comment by riodeuno** [comment]
@all-contributors please add @iSatVeerSingh to the list of contributors for code

**Comment by iSatVeerSingh** [comment]
> The following are new failures, please fix them before merging the PR:
> 
> 1. cypress/integration/Regression_TestSuite/Application/CommunityIssues_Spec.ts
> 2. cypress/integration/Regression_TestSuite/ServerSideTests/Params/PassingParams_Spec.ts
> 
> [Identified Flaky tests](https://app.appsmith.com/applications/613868bedd7786286ddd4a6a/pages/63ec710e8e503f763651791a)

@riodeuno What are these?

**Comment by riodeuno** [comment]
Hi @iSatVeerSingh these are test failures reported by the CI. I'm checking them out. 
At the moment, we have a merge freeze for our testing and release process, so we will need to wait a little for this PR to be merged.

I'll get back to you if we need any intervention from your end to successfully merge this PR and the other PR created by you.

**Comment by riodeuno** [comment]
Hi @iSatVeerSingh Could I ask you to pull the latest `release` branch into this branch and push again? I'll have to run the CI again once you've done so. Thanks.

**Review by riodeuno — APPROVED** [review]

**Comment by riodeuno** [comment]
@all-contributors please add @iSatVeerSingh for contributions in code.

**Comment by riodeuno** [comment]
@all-contributors please add @iSatVeerSingh for contributions in code.

**Pull request merged**
