### PR TITLE
chore: Release 19 june 23

### PR DESCRIPTION
**Pull request by rahulramesha**
Creating release PR for 1.9.24

### CODE REVIEW

**Comment by Aishwarya-U-R** [comment]
@rahulramesha - [Cypress is all passed in attempt1](https://cloud.cypress.io/projects/eyxvp8/runs/36477/overview), hence cancelling re-run.

**Comment by rahulramesha** [comment]
@Aishwarya-U-R The ci flow shows, one was not successful, https://github.com/appsmithorg/appsmith/actions/runs/5323424693

**Comment by Aishwarya-U-R** [comment]
@rahulramesha - Yes but that is a different step failure, which we are trying to fix, but nothing to concern with Cypress. Its always better to check Cypress dashboard once before re-running to avoid this case.

**Review by nidhi-nair — APPROVED** [review]

**Pull request merged**
