### PR TITLE
fix: Remove unwanted logs which may confuse the users

### LINKED ISSUE #15811: [Bug]: Triggering action fields causes console errors for undefined style and content configs of the widget
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When a widget's trigger field contains an action and this field is triggered then we see browser console errors for undefined style and content configs for that widget

### Steps To Reproduce

1. Add any widget, like Switch on the canvas
2. Add a showAlert action on its trigger field
3. Uncheck/check the switch widget and observe the browser console for errors as seen in the screenshot below

image

### Public Sample App

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by aswathkk**
## Description

Error messages related to widget configuration which are helpful only for Widget developers might cause confusion to our users.
So, removing them for a better UX.

Fixes #15811

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by yaldram — APPROVED** [review]
Can we do this - 
```js
const map = this.propertyPaneContentConfigsMap.get(type) || [];
return map
```
Or we can directly return whichever is more readable.

**Comment by ramsaptami** [comment]
Tested and verified on DP

**Comment by aswathkk** [comment]
@yaldram I will consider improving this in a better manner when we remove the feature flag of new property pane updates.

**Pull request merged**
