### PR TITLE
feat: Update directory structure for git-sync to mimic UI

### PR DESCRIPTION
**Pull request by abhvsn**
## Description

> Current file structure to save the resources in git repo is different than what we have in UI. This makes it difficult to grok the changes within the filesystem, which in turn results in difficulty for resolving the merge conflicts. This PR updates the directory structure to mimic UI. Proposed structure is shown in the attached issue

Fixes https://github.com/appsmithorg/appsmith/issues/11267

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

> Junit TCs
> Manual test

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by AnaghHegde — COMMENTED** [review]
LGTM, But is it possible to add a test which migrates changes from v1 to v2?

**Comment by abhvsn** [comment]
@AnaghHegde we already have the testcase to support import for v1 and v2. The current implementation takes care of exporting the files in v2. So considering the user have the filesystem from v1 we can successfully import this and export the v2 version.

**Review by AnaghHegde — APPROVED** [review]

**Pull request merged**
