### PR TITLE
fix: Post forking an application without the first page the application ends up having pages with page name as the page id

### LINKED ISSUE #17383: [Bug]: Post forking an application without the first page the application ends up having pages with page name as the page id
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://user-images.githubusercontent.com/67054171/194750905-94bd0186-39e0-4775-ae95-8af86b67e3c4.mov

page-id

If you fork a template by selecting pages to fork and if you don't select the first page. The application still ends having all the pages. Also the pages which were not selected seem to have the page name as the page id. We see the page not found error on the frontend when the invalid page(page which has the page name as the page id) ends up being the default page. Also it looks it is being set as the default page automatically post forking on the backend.

The response of GET `api/v1/applications/new` returns the unselected page(Dashboard) in the page list of the application. Also it is set as the default page and you can also see that the page id is the name of the page. Since it is set as the default page it tries to go to that page id on edit, but the page id is clearly invalid. The core issue seems to be the unselected page being added to the forked app.

### Steps To Reproduce

1. Create a new app and open the fork template modal. 
2. Fork the customer support dashboard by unselecting the first page.
3. You see the forked page. 
4. Go to home screen and edit the same app. It goes to a 404 page.

### Public Sample App

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by AnaghHegde**
## Description

When you fork a template by selecting pages to fork and if you don't select the first page. The application still ends up having all the pages. Also, the pages which were not selected seem to have the page name as the page id. We see the page not found error on the frontend when the invalid page(the page which has the page name as the page id) ends up being the default page. Also, it looks like it is being set as the default page automatically post forking on the backend.

The response of GET api/v1/applications/new returns the unselected page(Dashboard) in the page list of the application. Also, it is set as the default page and you can also see that the page id is the name of the page. Since it is set as the default page it tries to go to that page id on edit, but the page id is clearly invalid. The core issue is the reference inside the application.pages and application.publishedPages which was not updated based on the pageToImport parameter. Only the pageList in the JSON was updated after filtering. 

Fixes #17383 #17272 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Locally
- JUnit Tests

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by mohanarpit — APPROVED** [review]

**Comment by wengad82** [comment]
why  I can't fork the template into a existing app?  i run appsmith v1.9.6

**Pull request merged**
