### PR TITLE
fix: List widget inconsistent pageSize value with the number of item shown in the list.

### LINKED ISSUE #11299: [Bug]: List widget page size incorrect in certain situations
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The issue is shown in the attached video.

The list widget has incorrect page size for certain height settings.  This leads to weird behaviour when using server-side pagination. For eg. If there is a simple query pulling records from DB. In total there are 4 records. It only shows 3 records in the list. You expect the 4th record to show on the 2nd page, but it doesn't show. 

If you increase the list widget height, this appears to solve the issue.  

https://user-images.githubusercontent.com/32227135/154901474-992314ce-e01b-44dc-95bc-43e7073935e8.mp4

 

### Steps To Reproduce

See the attached video below

https://user-images.githubusercontent.com/32227135/154900467-329e4295-8b56-4fd2-ae14-82af91c09ef6.mov

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by ashit-rath**
## Description
When the height of the list widget is reduced, at a certain height range the `pageNumber` property and the items shown on the list do not match. This is due to incorrect calculation of the pageSize and when the pagination controls should show up

Fixes #11299 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
Jest test cases
Manual testing

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/11299-list-widget-pagesize 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 55.62 **(0.02)** | 36.82 **(0.02)** | 34.92 **(0)** | 55.93 **(0.02)**
 :red_circle: | app/client/src/utils/DynamicBindingUtils.ts | 83.89 **(-0.55)** | 70.54 **(-1.78)** | 75.86 **(0)** | 83.23 **(-0.62)**
 :green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.94 **(0.23)** | 41.67 **(0.84)** | 36.21 **(0)** | 56.99 **(0.25)**
 :green_circle: | app/client/src/widgets/ListWidget/widget/derived.js | 70.89 **(2.71)** | 52.17 **(14.67)** | 54.55 **(0)** | 69.33 **(3.2)**
 :green_circle: | app/client/src/widgets/ListWidget/widget/index.tsx | 65.33 **(1.99)** | 27.98 **(0.34)** | 58.49 **(0)** | 64.64 **(2.1)**</details>

### CODE REVIEW

**Review by jsartisan — DISMISSED** [review]

**Comment by somangshu** [comment]
@ashit-rath we have one review here, Can we move into QA with high priority, we should target this for the next release

**Review by SatishGandham — APPROVED** [review]
LGTM

**Comment by vivekverma2312** [comment]
@ashit-rath The list widget goes in bad state with few scenarios related to item space and resizing. I am not able to revert it once it breaks.
https://www.loom.com/share/54825a8d117e41a5b8670127ec0473b5

**Comment by ashit-rath** [comment]
@SatishGandham @jsartisan Can you guys check this commit and let me know if doing this won't break anything?

Basically, the code after this line was directly working on the children object or it's child object thus leading to mutations on the `this.props.children`

Just want to double-check if we are actually not relying on mutations of this.props.children as this change would break stuff.
https://github.com/appsmithorg/appsmith/pull/11355/commits/d54eae48caf8dc298cd2df532f28630cb6a1c8a9

**Comment by vivekverma2312** [comment]
@ashit-rath When we enter "-" in Item spacing the widget behaves improper depending upon server side pagination and without it.
https://www.loom.com/share/599e710f1aae4b8a90040d469514b72c

**Review by jsartisan — DISMISSED** [review]

**Comment by vivekverma2312** [comment]
@ashit-rath Now it's working fine.

**Review by jsartisan — APPROVED** [review]

**Pull request merged**
