### PR TITLE
fix: Add null check before updating the body in actions

### LINKED ISSUE #21742: [Bug]: Importing app from git shows uncommitted changes on opening git sync modal
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When an app which is connected to git which contains empty queries, is imported shows uncommitted changes on opening git sync modal. Refer: 

https://user-images.githubusercontent.com/80334441/227262020-d9a1af7d-9b53-4bad-97b6-f1a1a3c52661.mov

### Steps To Reproduce

1. Import an app from git which contain empty queries.
2. Open git sync modal and observe uncommitted changes are observed.

### Public Sample App

_No response_

### Environment

Release

### Issue video log

_No response_

### Version

Release

### PR DESCRIPTION
**Pull request by AnaghHegde**
## Description

> When an app which is connected to git which contains empty queries, is imported shows uncommitted changes on opening git sync modal. This PR fixes the issue. 

Fixes #21742 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual

### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by nayan-rafiq — APPROVED** [review]

**Comment by Parthvi12** [comment]
This issue is fixed and verified on DP.

**Review by Parthvi12 — APPROVED** [review]

**Pull request merged**
