### PR TITLE
Added wait for route

### PR DESCRIPTION
**Pull request by NandanAnantharamu**
Added suitable wait

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>
No changes to code coverage between the base branch and the head branch</details>

### CODE REVIEW

**Review by marks0351 — APPROVED** [review]

**Comment by arslanhaiderbuttar** [comment]
@NandanAnantharamu Not working fine for me on release.app. The response is not same as dsl. There is one extra field version in the response and we dont have that in dsl.

**Comment by NandanAnantharamu** [comment]
> @NandanAnantharamu Not working fine for me on release.app. The response is not same as dsl. There is one extra field version in the response and we dont have that in dsl.

The change is working if you check the CI dashboard fork application has passed , i have updated 
 the code for duplicate app https://dashboard.cypress.io/projects/eyxvp8/runs/6480/overview

**Review by marks0351 — APPROVED** [review]

**Review by marks0351 — APPROVED** [review]

**Pull request merged**
