### PR TITLE
Add required option to Rich Text Editor for validations when used with Form widget

### LINKED ISSUE #5161: [Feature] Add "required" option to Rich Text Editor when used in forms
## Summary

When using an RTE in a form it would be nice to be able to set it to "required" so the built in form validations can be used.

## Motivation

This solves the problem where a user can submit a form without filling in an RTE that should be required.

## Additional Context

The "required" option for the RTE should look and work the same as the ones in the other form fields.

### LINKED ISSUE #5376: [Bug] Deploy Preview - Rich Text Editor - The value at isRequired is invalid error occurs by dragging and dropping Rich Text Editor
## Description
Deploy Preview - https://deploy-preview-5330--appsmith-editor-ce.netlify.app/applications
It is observed that by dragging and dropping Rich Text Editor - the Value at isRequired is Invalid error occurs 

**Expected Result:**
Dragging and Dropping Rich Text editor should not throw any error

**Actual Result:**
The value at isRequired is invalid error occurs by dragging and dropping Rich Text Editor

### Steps to reproduce the behaviour:

1. Launch Appsmith app in the Deploy Preview - https://deploy-preview-5330--appsmith-editor-ce.netlify.app/applications
2. Drag and drop Rich Text editor and observe

VideoLink:
https://www.loom.com/share/d57ca42e8aa547f3895e935513ffec99

### Important Details

- Version: [14.1 (16611.1.21.161.3)]
- OS: [MacOS]
- Browser [Chrome, safari]
- Environment [deploy preview]

### LINKED ISSUE #5380: [Bug] Deploy Preview - Rich Text Editor - Submit button of form widget is enabled when RTE is required and there is no text in RTE
## Description
Deploy Preview :https://deploy-preview-5330--appsmith-editor-ce.netlify.app/applications
It is observed that the submit button can be enabled when there is no text in Rich Text editor and the rich text editor is enabled for required

**Expected Result:**
When the Rich text is enabled for required and when there is not text in rich text editor then the submit button of form should not be enabled

**Actual Result:**
The submit button of form widget can be enabled when there is no text in Rich Text editor and the rich text editor is enabled for required

### Steps to reproduce the behaviour:

1. Launch appmsith app in the Deploy Preview - https://deploy-preview-5330--appsmith-editor-ce.netlify.app/applications
2. Drag and drop form widget 
3. Place Rich Text editor inside form widget 
4. Enable 'Required' button of Rich Text editor 
5. Remove text inside rich text editor and observe the submit button of form is disabled
6. Open property pane of submit button and Disable the 'Disabled Invalid Forms' and observe

**VideoLink:**
https://www.loom.com/share/b45840429550468b836b3ad6ee0bd153

### Important Details

Version: [14.1 (16611.1.21.161.3)]
OS: [MacOS]
Browser [Chrome, safari]
Environment [deploy preview]

### PR DESCRIPTION
**Pull request by vicky-primathon**
## Description
Add required option to Rich Text Editor for validations when used with Form widget

Fixes #5161 
Fixes #5376 
Fixes #5380 

## Type of change
- New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>
No changes to code coverage between the base branch and the head branch</details>

### CODE REVIEW

**Review by somangshu — APPROVED** [review]

**Comment by YogeshJayaseelan** [comment]
@vicky-primathon Tested Rich Text Editor Required functionality inside form widget and came up with the below issues

#5376  and #5380

**Comment by riodeuno** [comment]
@YogeshJayaseelan The latest changes by @vicky-primathon should have also fixed #5380. Please verify. @vicky-primathon Please update the PR description to include `Fixes #5380`.

**Review by riodeuno — APPROVED** [review]
Approving for tests to run.

**Review by riodeuno — APPROVED** [review]

**Comment by YogeshJayaseelan** [comment]
@vicky-primathon We have tested the bug fixes, issue  #5376 is fixed and #5380 is still reproducible

**Comment by vicky-primathon** [comment]
@YogeshJayaseelan  this is working as intended

**Comment by somangshu** [comment]
@vicky-primathon #5376 the error should not occur when the widget is dropped. This needs to be fixed

@YogeshJayaseelan #5380 is not an issue and is functioning as intended

**Comment by vicky-primathon** [comment]
@somangshu  #5376 is fixed in current PR.

**Pull request merged**
