### PR TITLE
feat: Add Series Colour property for default charts

### LINKED ISSUE #15522: [Feature]-[780]:Add a series color property in default charts
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Add a new property for series color in default charts

### Why should this be worked on?

1. We want to reuse theme colors by default on the charts
2. People need to configure custom charts simply because they cannot change the color

### PR DESCRIPTION
**Pull request by souma-ghosh**
## Description
In default charts, only series title and series data could be provided by developer.
We have added the Series Color property as well in this PR to control the color of all the default charts (Except Pie Chart).

- Not applicable for custom charts
- Series Color will only work with hex code values as of now
- Series Color not applicable for Pie Chart and hence this feature is not available for Pie Chart

Fixes #15522

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Manual

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [x] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by jsartisan — APPROVED** [review]

**Comment by kamakshibhat-appsmith** [comment]
1. evaluated value not coming

**Review by jsartisan — DISMISSED** [review]

**Comment by chandannkumar** [comment]
Observation: @souma-ghosh cc: @dilippitchika 
- Color applied on charts is not same as actual color on adding less/more than 6 digit alphanumeric color code in Series Color property
https://bthrujcsw8.vmaker.com/record/7JzCerfGDvBVXMHJ

**Comment by souma-ghosh** [comment]
> Observation: @souma-ghosh cc: @dilippitchika
> 
> * Color applied on charts is not same as actual color on adding less/more than 6 digit alphanumeric color code in Series Color property
>   https://bthrujcsw8.vmaker.com/record/7JzCerfGDvBVXMHJ

This is happening because Fusion chart interprets hex colours differently when the hex is less than 6 digits. This is unpredictable as far as I tested. So we can expect this to work predictably when the series colour hex is 6 characters. Also fusion chart does not support text colours like "red", "green" etc. so the option has been limited to hex code.
We can put some validation to enforce the hex colours to be 6 characters only or think about switching to a different chart widget which can reliably interpret the colours provided. @dilippitchika Could you comment on whether we can move ahead with this?

**Comment by dilippitchika** [comment]
Ok this is a limitation, please create a new bug for it. Also @souma-ghosh can we support JS in the field?

**Comment by souma-ghosh** [comment]
@souma-ghosh ATM we can't. Since we have implemented the property controls for Chart Series in a bit hacky way. So we will need a refactor there before we can make the Series Color field JS convertible.

**Comment by dilippitchika** [comment]
Understood, can you please create a new issue for it?

**Comment by souma-ghosh** [comment]
Yes will do

**Comment by chandannkumar** [comment]
Test Plan for Series Colour property for Chart series
https://github.com/appsmithorg/TestSmith/issues/2115

**Pull request merged**
