### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Prachi0025**
I hope you will approve my Commit

### CODE REVIEW

**Comment by mohanarpit** [comment]
Unfortunately, this PR is not valid because this is a very low quality change that you're suggesting. I encourage you to look at some of the documentation issues that we have already created [here](https://github.com/appsmithorg/appsmith/issues?q=is%3Aissue+is%3Aopen+label%3ADocumentation)

For now, I'm closing this as invalid. Please let me know if I can help you in any other contributions that you'd like to make to our repository.

**Comment by Prachi0025** [comment]
Hello Sir
Sir sorry for my PR, but i believe that any change is not small and large.
So if you can accept then I'll be grateful to you.
As this is my starting and it will motivate me for large commits.

**Comment by mohanarpit** [comment]
@Prachi0025 I agree with you. I encourage you to contribute to open source responsibly. If you wish to make a difference and improve any open source project (Appsmith or otherwise), consider starting by contributing to the documentation in a meaningful way. I've already linked to some documentation issues in my previous comment. Consider picking them up as a starting point.

Thank you.

**Comment by Prachi0025** [comment]
Thank you

**Pull request closed without merging**
