### PR TITLE
fix: theme property pane reset on hover over the widget

### LINKED ISSUE #13639: [Bug]: App theming pane resets when hovering over a widget
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When i am on the theme selection page and my cursor hovers on a widget, the property pane changes from theme selection page to theme properties page -
[LOOM DEMO](https://www.loom.com/share/53a52476af1a4e70bf871447554a7f30)

### Steps To Reproduce

1. Open the theme selection page
2. Hover on a different widget
3. Observe how the property pane resets

### Public Sample App

_No response_

### Version

Release

### PR DESCRIPTION
**Pull request by keyurparalkar**
## Description

**Summary of changes**

* Added `SELECT_WIDGET_INIT` and `START_CANVAS_SELECTION` actions in the appThemingReducer.
* Set the `appStack` to `[]`.

**Motivation for the above changes**

* The issue was occurring due to `appStack` getting set to `[]` on `FOCUS_WIDGET` action
* The expected behaviour is the `appStack` should be blank whenever the user clicks on a widget or on the canvas.

Fixes #13639

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Manually tested

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/fix-theme-pane-reset-on-hover 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 56.61 **(0)** | 38.55 **(0.01)** | 35.9 **(0.01)** | 56.85 **(0)**
 :green_circle: | app/client/src/reducers/uiReducers/appThemingReducer.ts | 29.17 **(3.08)** | 100 **(0)** | 13.33 **(6.19)** | 29.17 **(3.08)**
 :green_circle: | app/client/src/selectors/propertyPaneSelectors.tsx | 88.89 **(2.78)** | 70.37 **(5.56)** | 91.67 **(0)** | 88.71 **(0)**</details>

### CODE REVIEW

**Review by jsartisan — APPROVED** [review]

**Comment by vivekverma2312** [comment]
@keyurparalkar Tested and the issue is fixed.

**Pull request merged**
