### PR TITLE
fix: blank screen in datasource view mode

### LINKED ISSUE #12045: [Bug]: Blank screen displayed after API save action
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

A blank screen is displayed after API save action and navigating to the API datasource from the entity explorer is not possible.

[LOOM DEMO](https://www.loom.com/share/4b995d7bffbc434e8c20ea8a287410d9)

### Steps To Reproduce

1. Create or modify an API datasource and click save
2. Observe the blank page displayed to user
3. Click on the datasource on the entity explorer and observe a blank screen appear as seen in the video above

### Public Sample App

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by danieldare**
## Description

- Upon updating an authenticated API data source it routes to a blank page

Fixes #12045

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
Manually

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/blank-screen-in-datasource 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 55.59 **(0)** | 36.79 **(0.01)** | 34.91 **(0)** | 55.9 **(0)**
 :red_circle: | app/client/src/pages/Editor/DataSourceEditor/DBForm.tsx | 49.23 **(-1.56)** | 17.14 **(-1.04)** | 9.09 **(0)** | 55.36 **(0)**
 :green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.94 **(0.23)** | 41.67 **(0.84)** | 36.21 **(0)** | 56.99 **(0.25)**</details>

### CODE REVIEW

**Review by Irongade — DISMISSED** [review]
LGTM

**Comment by rohan-arthur** [comment]
manual test: ok

**Review by AmanAgarwal041 — DISMISSED** [review]

**Review by Irongade — APPROVED** [review]

**Pull request merged**
