### PR TITLE
chore: use new ds version

### PR DESCRIPTION
**Pull request by tanvibhakta**
## Description

Uses new ds version which fixes an issue with divider color

#### PR fixes following issue(s)
Fixes # (issue number)
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
- [ ] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Comment by shadabbuchh** [comment]
As discussed, tested a few places where divider/menu divider is being used in the app. Please note that testing is only conducted at selected places excluding the Admin Settings pages.
The color is now reset to the correct value i.e. `#cdd5df`.
Screenshot 2023-09-06 at 11 47 07 AM
Screenshot 2023-09-06 at 11 47 25 AM
Screenshot 2023-09-06 at 11 47 46 AM
Screenshot 2023-09-06 at 11 48 03 AM
Screenshot 2023-09-06 at 11 48 17 AM
Screenshot 2023-09-06 at 11 49 22 AM
Screenshot 2023-09-06 at 11 49 42 AM
Screenshot 2023-09-06 at 11 51 07 AM
Screenshot 2023-09-06 at 11 51 33 AM
Screenshot 2023-09-06 at 12 02 18 PM

**Review by KelvinOm — APPROVED** [review]

**Pull request merged**
