### PR TITLE
fix: replace action execution cancellation toast errors with a better one

### LINKED ISSUE #16093: [Bug]: Empty error message is displayed to user on cancelling the run event
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When user clicks on RUN and then clicks on the CANCEL button in the response it is observed that empty error message is displayed to the user

### Steps To Reproduce

1) Paste the Rest API 
2) Click on the RUN option 
3) Click on the Cancel option
and observe the error message 
Screenshot 2022-08-17 at 1 31 54 PM

### Public Sample App

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by Irongade**
This PR gets rid of empty error toast messages which is displayed when a user cancels action execution.

Fixes #16093

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
Cypress tests

## Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Aishwarya-U-R — COMMENTED** [review]
Cypress changes looks fine!

**Review by AmanAgarwal041 — APPROVED** [review]

**Pull request merged**
