### PR TITLE
fix: Cannot delete current branch

### LINKED ISSUE #10333: Prune branch error - CannotDeleteCurrentBranchException when the checked out branch remote part is deleted

### PR DESCRIPTION
**Pull request by AnaghHegde**
## Description
For the sync/prune operation in git sync we are deleting the stale branches from local(if there is no remote tracking branch in git client). But suppose if the current checked out branch remote counter part is deleted from remote this operation will fail. This change set will fix this issue. We are excluding the current checked out branch from delete operation even though its remote counter part is deleted. 

Fixes #10333 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Locally
- JUnit tests

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by AnaghHegde** [comment]
@abhvsn Below scenarios are tested in this PR
1. When the default branch gets updated in remote git client
2. When the current checked out branch gets deleted at remote git client
3. When the appsmith default branch(application) gets deleted from remote
4. When the stale branch is present in local(with no remote counter part)

**Review by abhvsn — APPROVED** [review]
LGTM

Please update the commit message before squash merging to release

**Pull request merged**
