### PR TITLE
fix: Multiselection in table widget

### LINKED ISSUE #10669: [Bug]: Select all/deselect all do not work for the default row in table widget if it is changed
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[LOOM DEMO](https://www.loom.com/share/618c4e6e7b5c49a4bce8e5040daaa29e)

### Steps To Reproduce

1. Drag and drop a table widget
2. bind the widget with with query
3. Enable multi-row select 
4. Change the default row value
5. Now if we select/deselect all on table widget the default row do not get selected/deselected

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by Tooluloope**
## Description

> fix Select and deselect all in table widget when multiselection is enabled

Fixes #10669

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/select-and-deselect-in-table-widget 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 55.03 **(0)** | 36.37 **(0.01)** | 34.71 **(0)** | 55.41 **(0)**
 :green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.94 **(0.23)** | 41.67 **(0.84)** | 36.21 **(0)** | 56.99 **(0.25)**
 :red_circle: | app/client/src/widgets/TableWidget/widget/index.tsx | 29.74 **(0.1)** | 9.48 **(0)** | 28.85 **(-0.56)** | 29.4 **(0.11)**</details>

### CODE REVIEW

**Review by riodeuno — APPROVED** [review]

**Comment by riodeuno** [comment]
@Tooluloope The code looks good to me.

1. We will have to write a cypress test to avoid regressions in this scenario.
2. Can we verify by looking at the git blame of this file, to see whey we kept the default selected rows, selected, even when deselecting all? We might be able to find a relevant issue which was closed to figure out the rationale.

**Comment by chandannkumar** [comment]
Tested and working fine

**Comment by Tooluloope** [comment]
> @Tooluloope The code looks good to me.
> 
> 1. We will have to write a cypress test to avoid regressions in this scenario.
> 2. Can we verify by looking at the git blame of this file, to see whey we kept the default selected rows, selected, even when deselecting all? We might be able to find a relevant issue which was closed to figure out the rationale.

@riodeuno 
1. Added test cases already
2. https://github.com/appsmithorg/appsmith/pull/5074 it was just a feature request.

**Pull request merged**
