### PR TITLE
WIP : POST test and Multiple commands file added

### PR DESCRIPTION
**Pull request by NandanAnantharamu**
## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>
No changes to code coverage between the base branch and the head branch</details>

### CODE REVIEW

**Comment by mohanarpit** [comment]
@NandanAnantharamu Is this PR still valid? If yes, can you please merge the latest `release` branch and mark this as Ready for Review?

**Comment by NandanAnantharamu** [comment]
> @NandanAnantharamu Is this PR still valid? If yes, can you please merge the latest `release` branch and mark this as Ready for Review?

Noted will do that, i need some locators will update this PR

**Pull request closed without merging**
