### PR TITLE
fix: for SAAS plugins user configured values not separated

### LINKED ISSUE #21343: Handle query change count for queries with just the metadata file.
We're not showing the count for queries with just metadata files. This needs to be handled. Try it for Twilio queries.

### PR DESCRIPTION
**Pull request by AnaghHegde**
## Description

> 
1. We're not showing the count for queries with just metadata files. This needs to be handled. Try it for Twilio queries.
2. The user-configured values and system-generated metadata are not split into two files
This PR fixes these issues. 

Fixes #21343 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual

### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by nayan-rafiq — APPROVED** [review]

**Comment by AnaghHegde** [comment]
@Parthvi12 @infinitetrooper Please verify the changes done in this PR and let me know.

**Comment by Parthvi12** [comment]
@AnaghHegde  Verified the fix, and it looks good to me.

Uploading Screen Recording 2023-03-15 at 12.48.57 PM.mov…

**Pull request merged**
