### PR TITLE
fix: Feature/iframe dynamic visibility (2nd attempt)

### LINKED ISSUE #27991: [Feature]: Add support for isVisible property in the iframe widget
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Iframe widget cannot be hidden or shown dynamically, making it a blocker for cases like auto-height in containers. This feels like an inconsistency.

### Why should this be worked on?

This will help developers create a better experience for their flows where they want to show iframe dynamically

### PR DESCRIPTION
**Pull request by danceAndJive**
#### PR fixes following issue(s)
Fixes #27991 
>
>
#### Media

>
Firefox - My first application - Editor - Appsmith 2023-10-26 at 7 37 25 PM

>
- New feature (non-breaking change which adds functionality)
>
>
>
- [x] Manual
>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Comment by somangshu** [comment]
@riodeuno [you mentioned about some failing test](https://github.com/appsmithorg/appsmith/pull/28243#issuecomment-1774945040), is that fixed and merged

**Review by somangshu — APPROVED** [review]
LGTM

**Comment by riodeuno** [comment]
@somangshu Yes. The changes were merged https://github.com/appsmithorg/appsmith/pull/28243#discussion_r1368693522

**Comment by somangshu** [comment]
Deploy preview also LGTM

Waiting for another review to be able to close. 

@dilippitchika please check once on your end as well

**Comment by dilippitchika** [comment]
@somangshu @danceAndJive looks good to me, please merge

**Review by jsartisan — APPROVED** [review]

**Review by KelvinOm — APPROVED** [review]

**Pull request merged**
