### PR TITLE
fix: show the form setting in button widget

### PR DESCRIPTION
**Pull request by techbhavin**
## Description

> Buttons inside forms added in containers and modals don't show form settings

Fixes [#15939](https://github.com/appsmithorg/appsmith/issues/15939)

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by keyurparalkar — DISMISSED** [review]
LGTM!

**Comment by chandannkumar** [comment]
Buttons inside forms added in containers and modals don't show form settings - **Fixed**
- Tested button on form inside Container, Stat box, Tabs, Modal
- Tested with migration scenarios on existing buttons on form inside Container, Stat box, Tabs, Modal
- Tested with creating multi level modal and container type
- Tested Form Options functionality on every container type widgets
- Tested copy paste scenarios

This PR is tested and working as expected

**Comment by somangshu** [comment]
@sbalaji1192 does the code look good based on the latest changes requested?

**Review by sbalaji1192 — APPROVED** [review]

**Pull request merged**
