### PR TITLE
perf: optimize canvas resizing for fixed layout

### LINKED ISSUE #34741: [Bug]: Regression in Fluid Width Behaviour in View Mode
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have created an App in fluid width mode. When I change the resolution of the browser, or move it between monitors, the App should occupy the full space available in width. Whether its lesser space or more space.

With the current regression, the App occupies the same space when i change the resolutions. So from larger to small resolution, I see a scroll bar on the page
And from a smaller resolution to wider resolution, the App widgets do not occupy the full space.

I need to refresh the App for it to work correctly. This happens only in deployed mode

### Steps To Reproduce

1. Create an Application
2. Drag and Drop widgets onto it
3. Ensure that the App Canvas mode is using Fluid Width
4. Deploy the App
5. Reize the browser to a small width, or move the browser to a different sized screen

You will see that the App has not resized itself to occupy the width available in the browser

https://github.com/appsmithorg/appsmith/assets/5265702/f0a8d7cb-abcb-438f-964b-83ffc015c758

### Public Sample App

_No response_

### Environment

Production

### Severity

Low (Cosmetic UI issues)

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by alex-golovanov**
## Description
In this PR canvas resizing hook was refactored, many unnecessary effects were removed leaving the bare minimum.

Fixes #34741

## Automation

/ok-to-test tags="@tag.All"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/10155774784>
> Commit: 1900e8b429151d160e20712b6aca962f3a0e33ec
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=10155774784&attempt=2" target="_blank">Cypress dashboard</a>.
> Tags: `@tag.All`
> Spec:
> <hr>Tue, 30 Jul 2024 05:37:38 UTC

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [x] No

## Summary by CodeRabbit

- **New Features**
	- Introduced a new constant for resize debouncing to optimize UI performance.
	- Added a custom hook to automatically resize canvas elements based on container dimensions.

- **Enhancements**
	- Improved responsiveness of the app layout with better width management for canvas elements.
	- Enhanced structure and readability of components through destructuring props.

- **Bug Fixes**
	- Updated logic in the main canvas reducer to prevent unnecessary state updates after initialization.

- **Tests**
	- Updated tests to reflect changes in hooks focusing on canvas width auto-resizing.

### CODE REVIEW

**Comment by sagar-qa007** [comment]
@alex-golovanov Can we check coverage after unit test written as well? Please share report if any.

**Comment by alex-golovanov** [comment]
> @alex-golovanov Can we check coverage after unit test written as well? Please share report if any.

Could you rephrase please, I didn't really understand what you're asking. @sagar-qa007

**Comment by sagar-qa007** [comment]
@alex-golovanov I have seen you have written the unit tests in this PR. But I have no reports to measure that we do increase our coverage or at-least cover new logic with test cases from unit testing. If we can put that as well, we can be assured for logic testing before merging.

**Comment by alex-golovanov** [comment]
> @alex-golovanov I have seen you have written the unit tests in this PR. But I have no reports to measure that we do increase our coverage or at-least cover new logic with test cases from unit testing. If we can put that as well, we can be assured for logic testing before merging.

I think that test coverage should be collected automatically rather that in PR comments, only then you will have consistent way to collect, compare and gauge unit test dynamics. It looks like unit test commands are configured for client app, but if you require some help let's chat in QA slack.

With that said, this is a refactor, functionality has not changed, code base reduced and one additional unit test has been added. 

Here is the coverage you've asked for:
```json
    {
        "lines": {
            "total": 102538,
            "covered": 56164,
            "skipped": 0,
            "pct": 54.77
        },
        "statements": {
            "total": 110472,
            "covered": 61156,
            "skipped": 0,
            "pct": 55.35
        },
        "functions": {
            "total": 24245,
            "covered": 8232,
            "skipped": 0,
            "pct": 33.95
        },
        "branches": {
            "total": 58078,
            "covered": 16915,
            "skipped": 0,
            "pct": 29.12
        },
        "branchesTrue": {
            "total": 0,
            "covered": 0,
            "skipped": 0,
            "pct": 100
        }
    }
```

**Comment by sagar-qa007** [comment]
@alex-golovanov ignore my comment as I will check async for this.

**Review by hetunandu — APPROVED** [review]

**Pull request merged**
