### PR TITLE
fix: filePicker widget re-skinning 

### LINKED ISSUE #10997: [Enhancement]: Filepicker widget reskinning
https://www.notion.so/appsmith/Filepicker-b587b3cc2f7648c69c507e8808fa9f15

### PR DESCRIPTION
**Pull request by keyurparalkar**
## Description

This PR focuses on widget re-skinning of file picker widget. Please refer to the following [PRD](https://www.notion.so/appsmith/Filepicker-b587b3cc2f7648c69c507e8808fa9f15)

Please refer to the following [figma](https://www.figma.com/file/1aTQ6vksqqAMtgB243PtHm/UI-%7C-Widget-Style-Updates-0.1).

Fixes #10997 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

`FilePickerV2_Widget_Reskinning_spec.js` spec file is added to test styles. Please refer to the column `cypress tests covered or manual?` for tests that are automated and for the manual

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by somangshu** [comment]
@jsartisan please complete the review here, its taken longer than usual

**Comment by somangshu** [comment]
@keyurparalkar is this WIP, if that is the case please keep the PR in draft and dont request for a review. 

if the work is done, The PR desc dosent look apt, you should always think about each section well and fill up the details before requesting review

**Review by jsartisan — DISMISSED** [review]

**Comment by vivekverma2312** [comment]
@keyurparalkar LGTM

**Review by jsartisan — APPROVED** [review]

**Pull request merged**
