### PR TITLE
feat: 8761 added optionAlignment property

### LINKED ISSUE #8761: [Feature]: There should be alignment options for CheckboxGroup Widget
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

The default alignment for the Checkbox Group widget is `space-between`.  We should provide a way to choose different types of alignments.

### Why should this be worked on?

There are cases in which the users wanted to align this in different ways especially when the number of items in the checkbox is dynamic.

Here's one of my use cases:

https://user-images.githubusercontent.com/10436935/138659869-3ed857a1-fbba-42f0-b649-226c7b17c757.mov

See how the widget looks when there are only 2 items.

### PR DESCRIPTION
**Pull request by vibhandikyash**
## Description

> Added alignment option property for Checkbox group widget.

Fixes #8761 

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Tested locally.
- Added test cases.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/checkboxgroup-alignment-options 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 55.05 **(0)** | 36.49 **(0)** | 34.46 **(0.01)** | 55.59 **(0.02)**
 :green_circle: | app/client/src/utils/WorkerUtil.ts | 89.76 **(0.78)** | 72.55 **(1.96)** | 100 **(0)** | 93.33 **(0.95)**
 :red_circle: | app/client/src/widgets/CheckboxGroupWidget/component/index.tsx | 25 **(-0.71)** | 12.5 **(-0.83)** | 0 **(0)** | 33.33 **(0)**
 :green_circle: | app/client/src/widgets/CheckboxGroupWidget/widget/index.tsx | 58.73 **(0.67)** | 29.17 **(0)** | 44.44 **(0)** | 59.32 **(0.7)**</details>

### CODE REVIEW

**Review by aswathkk — DISMISSED** [review]
LGTM

**Comment by shwetha-ramesh** [comment]
@vibhandikyash Tested this PR. Working as expected in DP. 

Moving to Done.

**Review by aswathkk — APPROVED** [review]

**Pull request merged**
