### PR TITLE
Don't log debug level logs in prod

### PR DESCRIPTION
**Pull request by hetunandu**
## Description
The fallback for logging was set to debug which made all logs getting printed in prod

- Fallback set to ERROR
- set correct env in dev and build scripts
- introduce `logLevelOverride` to override loglevel

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Prod deployments should not see any debug logging
- setting `logLevelOverride` to either "DEBUG" or "ERROR" should override logging

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/loglevel 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 54.06 **(-0.01)** | 36.09 **(0)** | 32.57 **(0)** | 54.61 **(-0.01)**
 :green_circle: | app/client/src/components/editorComponents/GlobalSearch/parseDocumentationContent.ts | 79.12 **(0.23)** | 43.02 **(0)** | 92.31 **(0)** | 79.55 **(0.24)**
 :red_circle: | app/client/src/pages/Editor/Canvas.tsx | 80 **(-3.33)** | 100 **(0)** | 100 **(0)** | 80 **(-3.33)**
 :green_circle: | app/client/src/pages/common/CustomizedDropdown/dropdownHelpers.tsx | 41.38 **(2.09)** | 6.67 **(0)** | 33.33 **(0)** | 39.29 **(2.25)**
 :green_circle: | app/client/src/sagas/GlobalSearchSagas.ts | 52.5 **(1.22)** | 13.04 **(0)** | 50 **(0)** | 54.29 **(1.35)**
 :green_circle: | app/client/src/sagas/CommentSagas/index.ts | 51.15 **(0.38)** | 20.83 **(0)** | 58.82 **(0)** | 50 **(0.51)**
 :red_circle: | app/client/src/utils/storage.ts | 39.42 **(-2.77)** | 13.64 **(0)** | 20 **(0)** | 32 **(-3.16)**</details>

### CODE REVIEW

**Review by mohanarpit — COMMENTED** [review]
Why are we introducing a new variable logLevelOverride instead of using the existing variable logLevel?

**Comment by hetunandu** [comment]
> Why are we introducing a new variable logLevelOverride instead of using the existing variable logLevel?

It is confusing with `loglevel` (notice the small L in level) 
`loglevel` will be set by the library itself. 

Creating an "override" variable made sense

**Review by mohanarpit — APPROVED** [review]

**Comment by mohanarpit** [comment]
Does this mean that the variable `loglevel` in the browser's local storage will now be called `logLevelOverride` ?

**Comment by hetunandu** [comment]
> Does this mean that the variable `loglevel` in the browser's local storage will now be called `logLevelOverride` ? Or will we have 2 variables in local storage?

All users by default will have `loglevel` in their localstorage. To override they will use `logLevelOverride` and after that they will have two. Both will have the same value

**Pull request merged**
