### PR TITLE
feat: A/B test | flip primary and secondary CTAs in the datasource form

### LINKED ISSUE #30394: [Task]: A/B test | flip primary and secondary CTAs in the datasource form
### SubTasks

Scope: Postgres, MySQL, MongoDB

Control group: Primary CTA is `SAVE` and Secondary CTA is `TEST`
Experiment group: Secondary CTA should be `SAVE` and Primary CTA should be `TEST`

Hypothesis: For the experiment group, we will see an increase in successful first query run and decrease in time taken to run first successful query.

### PR DESCRIPTION
**Pull request by rohan-arthur**
## Description
Hypothesis: For the experiment group, we will see an increase in successful first query run and decrease in time taken to run first successful query.

Scope: Postgres, MySQL, MongoDB

Control group: Primary CTA is SAVE and Secondary CTA is TEST
Experiment group: Secondary CTA should be SAVE and Primary CTA should be TEST

https://www.notion.so/appsmith/Flip-CTA-primary-secondary-for-SAVE-and-TEST-datasource-9270ad0ca3ee4efebda63f0354a4bb4a

#### PR fixes following issue(s)
Fixes #30394 

#### Media
This is how it looks:

Screenshot 2024-01-25 at 13 24 16

#### Type of change

- Chore (housekeeping or task changes that don't impact user perception)
>
>
>
- [ ] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

## Summary by CodeRabbit

- **New Features**
	- Added a new feature flag check to modify button styles and behavior in the `DatasourceAuth` component.
	- Included a new feature flag `ab_flip_primary_secondary_ctas_dsform_enabled` in the `FeatureFlag.ts` file.

### CODE REVIEW

**Comment by rohan-arthur** [comment]
after discussing this with the team, we decided it doesn't make sense to apply conditional logic only for a few plugins(albeit top 5). 
This will be enabled for all plugins.

**Review by AmanAgarwal041 — APPROVED** [review]

**Pull request merged**
