### PR TITLE
fix: JSONForm select not working in nested fields - Array/Object

### LINKED ISSUE #12625: [Bug]: JSONForm select field does not open when used in an nested field (Array/Object)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The select field menu does not open when it is added to an Array Item/Array of Object/Object or any nested structure.

### Steps To Reproduce

1. Add a JSON Form
2. Add a new custom field
3. Change the type to Object
4. Add a new field under that object
5. Change the newly added field type to select
6. Try clicking the select field on the form, the menu won't open.

### Public Sample App

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by ashit-rath**
## Description
This PR fixes 2 things

1. Select field's menu does not open up when used in nested fields like Array or Object 
2. The multiselect dropdown menu width is less than the multiselect itself.

Fixes #12625 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Cypress
- Manual

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/12625-json-form-select 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 56.35 **(0)** | 37.79 **(-0.01)** | 35.96 **(0)** | 56.57 **(0)**
 :green_circle: | app/client/src/utils/WorkerUtil.ts | 89.76 **(0.78)** | 72.55 **(1.96)** | 100 **(0)** | 93.33 **(0.95)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.71 **(-0.23)** | 40.83 **(-0.84)** | 36.21 **(0)** | 56.74 **(-0.25)**
 :red_circle: | app/client/src/widgets/JSONFormWidget/fields/MultiSelectField.tsx | 28 **(-0.77)** | 4.65 **(-0.76)** | 0 **(0)** | 32.31 **(-1.02)**</details>

### CODE REVIEW

**Review by sbalaji1192 — APPROVED** [review]

**Comment by chandannkumar** [comment]
@ashit-rath 
- Unable to clear previous input from Currency Input type
https://www.loom.com/share/9613b9b49546452f9c56763f0a52c8db

**Comment by ashit-rath** [comment]
@chandannkumar Can you raise a separate issue for that?
Let's just stick with the select and multiselect issue for now.

**Comment by chandannkumar** [comment]
Tested this PR and working as expected
1. Select field's menu does not open up when used in nested fields like Array or Object - **Fixed**
2. The multiselect dropdown menu width is less than the multiselect itself - **Fixed**

**Pull request merged**
