### PR TITLE
fix: 12338 - postgres datasource default configure on reconnect modal

### LINKED ISSUE #12338: [Bug]: Reconnect Modal - Optional SSL should not be mandatory to Test Postgress DataSource
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://user-images.githubusercontent.com/91450662/160598179-625fb892-19b0-4b7e-96b3-af72f2c080a5.mov

### Steps To Reproduce

1. Create a new application with Postgres Ds & export the json
2. Create a new organisation & Import the same json from above step 
3. Observe Reconnect DS modal appear, fill in all details
4. Observe SSL is optional & do not select it
5. Try to test
6. **Observe - User is not allowed to Test successfully unless SSL is selected even though its optional**
7. **Expected - SSL option should be preselected similar to new create postgres page to allow user to seamlessly test the datasource via Reconnect Modal**
8. Try to Save without selecting SSL, DS is saved successfully & tables are accessible

### Public Sample App

_No response_

### Version

Cloud/Release v1.6.17

### PR DESCRIPTION
**Pull request by haojin111**
## Description
When importing application with only one postgres datasource, after selected unconfigured datasource, form value should be fullfilled default value such as ssl config as "Default"

> Updated logic of initializing datasource form on reconnect datasource modal
> Updated unconfigured datasoure list title and database type

Fixes #12338 , #12509, #12535

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Added cypress test with Application/ReconnectDatasource_spec.js

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>

    // Code coverage diff between base branch:release and head branch: fix/12338-postgre-datasource-default-configure-on-reconnect-modal 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | app/client/src/pages/Editor/DataSourceEditor/index.tsx | 30.53 **(0.32)** | 0 **(0)** | 18.18 **(0)** | 30.34 **(0)**
 :red_circle: | app/client/src/sagas/DatasourcesSagas.ts | 13.9 **(-0.08)** | 2 **(-0.03)** | 8.33 **(0)** | 16.36 **(-0.06)**
 :green_circle: | app/client/src/utils/WorkerUtil.ts | 89.76 **(0.78)** | 72.55 **(1.96)** | 100 **(0)** | 93.33 **(0.95)**</details>

### CODE REVIEW

**Comment by haojin111** [comment]
postgres_reconnect

**Comment by RakshaKShetty** [comment]
Tested with Json and git import in both the place default config is updated as in screenshoot
image

**Review by IAmAnubhavSaini — APPROVED** [review]

**Review by ankitakinger — APPROVED** [review]
LGTM

**Pull request merged**
