### PR TITLE
fix: Modal overlay crop issue

### PR DESCRIPTION
**Pull request by albinAppsmith**
## Description

When there are contents below initial scroll height, modal was taking only initial scroll height.

#### PR fixes following issue(s)
Fixes https://github.com/appsmithorg/appsmith/issues/31261

#### Media

https://github.com/appsmithorg/appsmith/assets/87797149/5e028c88-9576-49b4-8813-a273afff15d5

#### Type of change

- Bug fix (non-breaking change which fixes an issue)

- [ ] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

## Summary by CodeRabbit

- **New Features**
	- Introduced dynamic adjustment of the modal overlay layout based on sidebar state using a new custom hook.
	- Enhanced sidebar properties handling for a more responsive and user-friendly layout in the app viewer.
- **Refactor**
	- Simplified sidebar width calculation and improved logic for determining sidebar visibility.
	- Streamlined handling of layout and styling based on auto layout settings.
- **Style**
	- Minor styling fix with the addition of a missing semicolon in `AppPage.styled.tsx`.
- **Chores**
	- Cleaned up unused imports and selectors to improve code maintainability.

### CODE REVIEW

**Review by marks0351 — COMMENTED** [review]
@albinAppsmith can you pls add a test case for this so that this does not regress again?

**Comment by albinAppsmith** [comment]
> @albinAppsmith can you pls add a test case for this so that this does not regress again?

Created a task for this because of the time crunch we have right now. Will take it up once current set of tasks are done.
https://github.com/appsmithorg/appsmith/issues/31405

**Pull request merged**
