### PR TITLE
feat: [ Context Switching ] Maintain datasource edit mode

### LINKED ISSUE #17438: [Task]: Context switching - Datasources edit state
Datasource edit and view state need to be persisted.

### PR DESCRIPTION
**Pull request by akash-codemonk**
## Description

Maintains datasource edit mode

https://user-images.githubusercontent.com/67054171/204996511-f5fbdba0-94e1-419b-b543-260e9937b1d5.mov

Default is set to view mode. 
Datasources when created or edited(clicking on an edit datasource button from the integrations screen) needs to go to edit state. This happens outside the datasource route so set the state when in this route with an existing query param `viewMode`

Fixes #17438 

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Cypress

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by hetunandu — DISMISSED** [review]

**Review by hetunandu — APPROVED** [review]

**Comment by akash-codemonk** [comment]
@hetunandu Can we force merge this? All tests have passed. The perf test fails for all PR's.

**Review by hetunandu — APPROVED** [review]

**Pull request merged**
