### PR TITLE
fix: search input autofocus issue in entity explorer add query/js menu

### LINKED ISSUE #24088: [Bug]: Placeholder not aligned in editor pages
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Placeholder in big dynamic text field are not aligned with other type of input fields in the editor page eg MongoDB

### Steps To Reproduce

Screenshot 2023-06-06 at 10 43 36

### Public Sample App

_No response_

### Environment

Release

### Issue video log

_No response_

### Version

Cloud-latest

### PR DESCRIPTION
**Pull request by albinAppsmith**
## Description

This PR fixes,
1. Search component not getting focus on opening create new query or JS menu in entity explorer.
2. Deleted workflow for making design system pod members as reviewers.
3. Fixed text alignment in datasource page.

#### PR fixes following issue(s)
Fixes #24088, #23516

#### Media

https://github.com/appsmithorg/appsmith/assets/87797149/0c481e1d-3953-4dbd-8154-45a16518262b

https://github.com/appsmithorg/appsmith/assets/87797149/a913fdd2-f2c3-40d8-8a57-2fe9d8b1eac6

#### Type of change

- Bug fix (non-breaking change which fixes an issue)

- [ ] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by tanvibhakta — APPROVED** [review]

**Comment by tanvibhakta** [comment]
This PR also fixes this issue: https://github.com/appsmithorg/appsmith/issues/24338

**Comment by albinAppsmith** [comment]
> #24338

@tanvibhakta This PR won't fix this issue.

**Comment by tanvibhakta** [comment]
I just tested it on your PR, it does.

**Comment by tanvibhakta** [comment]
https://github.com/appsmithorg/appsmith/issues/24338 is happening because the padding set it the LazyLoadingEditor and the regular code editor is different. When you have removed the padding from the text area (https://github.com/appsmithorg/appsmith/pull/24387/commits/f85604f5b93a0a66e590b540c00e8a9f9210f421) it has reverted the padding in the text area to be the same as the padding in the lazy loaded text area. This fixes the issue.

**Comment by shadabbuchh** [comment]
Issue 1 - Fixed

https://github.com/appsmithorg/appsmith/assets/39921438/48bab37b-b8ec-4f92-abb4-4a5e8ba4ca69

Issue 2 - Fixed
Screenshot 2023-06-14 at 10 17 42 AM

Issue mentioned in https://github.com/appsmithorg/appsmith/issues/24338 is still reproducible for JS Objects:

https://github.com/appsmithorg/appsmith/assets/39921438/5217c2ae-b56e-451d-bcc5-9cde52e973c6

Cc: @tanvibhakta

**Comment by tanvibhakta** [comment]
@shadabbuchh can you confirm that https://github.com/appsmithorg/appsmith/issues/24338 doesn't occur for regular text area any more? Like in query pages?

**Comment by shadabbuchh** [comment]
> @shadabbuchh can you confirm that #24338 doesn't occur for regular text area any more? Like in query pages?

@tanvibhakta for other query pages it is fixed

https://github.com/appsmithorg/appsmith/assets/39921438/c0c4a5dd-acbd-4d80-8cec-e24ae63eb952

**Comment by tanvibhakta** [comment]
The text-shift in JSObjects is a vertical shift happening due to external padding being applied. Could you please raise a different issue, as it does not pertain to internal text area?

**Comment by shadabbuchh** [comment]
Have raised a separate bug for the vertical shift in JS Object query page: https://github.com/appsmithorg/appsmith/issues/24460

Rest looks good.

**Pull request merged**
