### PR TITLE
fix: fixes the google sheets update datasource name issue

### LINKED ISSUE #22576: GSheet Scope Drop Down Bug
Steps to reproduce:
1. Create a new google sheet data source 
2. Select Read/write all google sheets scope from drop-down menu
3. Now edit the data source name 
4. After changing the data source name click on whitespace anywhere.
5. Issue it will change the user selected scope to default one.

### PR DESCRIPTION
**Pull request by Irongade**
The google sheets datasource editor page re-renders whenever the name of the datasource is changed causing selected options to be cleared off. This PR fixes that issue.

> Add a TL;DR when description is extra long (helps content team)

Fixes #22576 

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

- Manual
- Jest
- Cypress

### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by sneha122 — APPROVED** [review]

**Comment by Aishwarya-U-R** [comment]
@Irongade - Please merge latest & trigger new oktotest. Cancelling re-attempt since its past 12 hrs.

**Comment by Aishwarya-U-R** [comment]
@Irongade - Please merge latest & trigger new oktotest. Cancelling re-attempt since its past 12 hrs since last run.

**Comment by Irongade** [comment]
@prapullac what is the update here?

**Pull request merged**
