### PR TITLE
feat: add missing fusion chart

### LINKED ISSUE #15958: [Feature]: Add missing fusion charts
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Add the missing Linear scale chart - https://www.fusioncharts.com/charts/gauges/gauge-linear-scale-with-colored-categories?framework=javascript

### Why should this be worked on?

Parity, we should support what fusion charts allows

### PR DESCRIPTION
**Pull request by iamrkcheers**
## Description

Add missing fusion chart of the type 'hlineargauge'

Fixes #15958

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Manual

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by sbalaji1192 — APPROVED** [review]

**Comment by chandannkumar** [comment]
Tested this PR and LGTM
- Sanity check on Chart widget

**Pull request merged**
