### PR TITLE
fix: allow localhost as a valid domain for image widget url

### LINKED ISSUE #22985: [Bug]: AirGappedinstance - Image widget throwing error on binding with camera imageblobUrl
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On binding camera widget with image widget using {{Camera1.imageBlobURL}}, it show show the picture clicked on camera instead throwing an error

Note: This issue happens only in localhost

### Steps To Reproduce

1. Drag & Drop Camera widget
2. Drag & Drop Image widget
3. Bind image widget with `{{Camera1.imageBlobURL}}`
4. Click a photo on camera and save it
5. Observe there is no image shown on Image widget and throws error

### Public Sample App

_No response_

### Environment

Production

### Issue video log

https://www.loom.com/share/34126bcf40794beebf0599f8257fc8ed

### Version

localhost

### PR DESCRIPTION
**Pull request by berzerkeer**
## Description
- If the image url in image widget points to localhost domain, it is treated as an invalid url. Updated regex to allow localhost as a valid domain.

#### PR fixes following issue(s)
Fixes #22985 

#### Type of change

- Bug fix (non-breaking change which fixes an issue)

- [x] Manual
- [x] Jest
- [ ] Cypress
>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by sbalaji1192 — APPROVED** [review]

**Comment by berzerkeer** [comment]
@chandannkumar can you test this dp [appsmith-fjcswfdrn-get-appsmith.vercel.app](https://appsmith-fjcswfdrn-get-appsmith.vercel.app/) and check if its allowing localhost now and approve. Thanks!

**Comment by berzerkeer** [comment]
> @chandannkumar can you test this dp [appsmith-fjcswfdrn-get-appsmith.vercel.app](https://appsmith-fjcswfdrn-get-appsmith.vercel.app/) and check if its allowing localhost now and approve. Thanks!

@chandannkumar is this done? If yes , can i get that label so that i can merge it. Thanks!

**Comment by chandannkumar** [comment]
@berzerkeer Tested this PR and LGTM

**Pull request merged**
