### PR TITLE
chore: Remove collaboration pointers from the Editor

### LINKED ISSUE #19659: [Task]: Remove unnecessary collaboration code
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- Collaboration features are only visible to users within Appsmith
- Removing this code will help cleanup the components and make them maintainable and give us a marginal performance improvement.

### PR DESCRIPTION
**Pull request by riodeuno**
## Description

This is an internal cleanup change, which removes the collaboration pointers from the Editor.

**_Background_**: We had a feature for collaboration which we had sunset. As a part of this feature, we could see the mouse pointers of the other users who were editing the same page in realtime. This feature is today visible only to internal Appsmith users. This part of the feature, also doesn't serve a purpose for our users. 

**_Why are we removing this?:_** This code has no impact on our users. This makes maintaining this code, as well as the additional computational load on the components unnecessary.

**_How do we put this back in?:_** The idea of this PR is to see the changes in one place and hence make it easy to revert when needed.

Fixes #19659 19659

Media
Here is what it looked like:
Screenshot 2023-01-10 at 2 04 42 PM

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manual
- Cypress: If all tests pass, these changes don't cause a regression

### Notes 
https://github.com/appsmithorg/appsmith/pull/19660#issuecomment-1379879800

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [NA] I have commented my code, particularly in hard-to-understand areas
- [NA] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [NA] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by hetunandu — DISMISSED** [review]

**Comment by riodeuno** [comment]
This is ready for QA. We will be keeping this PR open until we have a test plan and QA approval.

**Comment by riodeuno** [comment]
Note: Some design system components use react-dnd. However, we're removing the DndProvider. So, this might effect filepickers, although unlikely, as we've removed the DndProvider from the Editor and not from the Application.

**Review by hetunandu — APPROVED** [review]

**Comment by sharat87** [comment]
Resolved conflicts in `testUtils.tsx`.

**Comment by riodeuno** [comment]
@sharat87 Could you also approve this? We tried testing this, but we cannot consistently see the collaboration pointers today. So, I believe it is safe to merge, once the tests pass.

**Review by sharat87 — APPROVED** [review]

**Comment by riodeuno** [comment]
@Aishwarya-U-R I was wondering if we can test the `ci-merge-check` command on this PR?

**Comment by Aishwarya-U-R** [comment]
@riodeuno - Criteria for using that command is only when ci-test-result is not communicated back from Git runners after completion. Here I see cypress failure + Client build failure. In this case the comment wont work. But otherwise also we are making some improvements to it, so it's not fully usable yet. Its WIP. Will update asap.

**Pull request merged**
