### PR TITLE
fix: Cursor pagination in list widget

### LINKED ISSUE #13946: [Bug]: Firestore: Same Records Are Displayed on All Pages When Using Pagination in List Widget
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When using **Firestore** and implementing **Server-Side Pagination** for a **List**, it displays the _same records_ on all pages. 
The same implementation works correctly in a Table widget.
Ref: https://theappsmith.slack.com/archives/C0341RERY4R/p1652372710725879

### Steps To Reproduce

1. Add a **List** widget.
2. Create a **query** that fetches the data.
3. Implement **server-side pagination** and note that the same records are displayed on all pages.

### Public Sample App

https://app.appsmith.com/app/firestore/firestore-pagination-6283d136309fd93a9bf0fe7b

### Version

Cloud  v1.6.26-SNAPSHOT

### PR DESCRIPTION
**Pull request by Tooluloope**
## Description

Cursor Pagination Fix for list widget

Fixes #13946 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Visual Test

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/Firestore-Pagination-in-list-widget 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 56.71 **(-0.01)** | 38.66 **(-0.01)** | 36.22 **(0)** | 56.96 **(-0.01)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.71 **(-0.23)** | 40.83 **(-0.84)** | 36.21 **(0)** | 56.74 **(-0.25)**
 :red_circle: | app/client/src/widgets/ListWidget/widget/index.tsx | 66.56 **(-0.44)** | 28.72 **(-0.3)** | 62.26 **(0)** | 65.96 **(-0.47)**</details>

### CODE REVIEW

**Comment by chandannkumar** [comment]
@Tooluloope 
Getting error on page change when Server side pagination is enabled.
Since the records are correctly displayed on each page when server side pagination is disabled.
Refer video:
https://www.loom.com/share/08c404652442491ea128c674bdfeac07

**Comment by Tooluloope** [comment]
> @Tooluloope Getting error on page change when Server side pagination is enabled. Since the records are correctly displayed on each page when server side pagination is disabled. Refer video: https://www.loom.com/share/08c404652442491ea128c674bdfeac07

@chandannkumar Could you share the app with me, Most likely, this isn't related to this issue.

**Comment by chandannkumar** [comment]
Tested this PR and working fine. 
P.S: Need to cross check with the shared app which is added in issue to verify on Prod

**Comment by nidhi-nair** [comment]
Merging in since ui-test-result is not updating.

**Pull request merged**
