### PR TITLE
feat: Recorder widget

### LINKED ISSUE #3912: Audio recorder widget
Hello team,

Thank you for fantastic work with Appsmith.

I have been exploring the app and was wondering how one can add a voice recorder and an audio player to the app?
That would be a very helpful for the app feature we are trying to build in our team.

Thanks!

# RACI matrix
| Label | Value | 
| ------------- | ------------- |
| Responsible |  @jsartisan, @wmdev0808   |
| Accountable | @somangshu  |
| Consulted | @momcilo-appsmith  |
| Informed |  @Nikhil-Nandagopal |

# Objective

We need a voice recorder widget that allows users to record using there microphone, Listen to the playback and be able to export the data to a datasource.

# Success Metrics

| Goal  | Metric |
| ------------- | ------------- |
| New widget  | Increase use case coverage |
| Data type: Speech  | introduce a new data type; Ability to record voice etc. |

# Requirements

| Requirement   | User Story | Importance | Notes |
| ------------- | ------------- | ------------- | ------------- |
| Allow Playback | recording and playing the feedback should be part of the experience, this will depend on the developer config | High | - |
| Recording states | state will allow the user to pause / play or stop the recording. Once the recording is stopped the audio should be available for the playback if the dev has enable the option. | High  | - |
| Allow download | The dev will have an option to allow users to download the recorded playback. | Low  | - |
| `.value`  | And internal property should expose an API to access the file | High  | - |
| isVisible |  Dev can set this attributes to show/hide with toggle or even a JS expression (JS convertible)  | High  | - |
| isDisabled | Dev can set this attributes to disable the widget with toggle or even a JS expression (JS convertible) | High | - |
| Action - `OnRecordingStopped` | API to trigger an action on recording stopped | High  | - |
| `.multipart` | File data should also be available as multipart | High  | - |
| Recording state message | All states should be well handled with Recording state message: ex - recording in progress | Medium | - |
| Style | The widget can have style customisation | low | if required |
| Tooltip | An helper text on the recording button for the end user. This will only show up when when you  are on the initial state of the widget | Medium | - | 

# Questions:

| Question   | Answer |
| ------------- | ------------- |
|  |  |

# Developer Handoff Document in Figma:

https://www.figma.com/file/WUnCZ4TcUSOYLpSSGWIsPx/Audio-Recorder-Widget?node-id=5%3A493

### PR DESCRIPTION
**Pull request by wmdev0808**
## Description
- First MVP of the widget
Fixes #3912 

## Type of change

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

## How Has This Been Tested?

- Test A
- Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: feature/3912-voice-recorder-audio-player-widget 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 54.89 **(-0.29)** | 36.98 **(-0.12)** | 34.03 **(-0.12)** | 55.47 **(-0.27)**
 :sparkles: :new: | **app/client/src/components/designSystems/appsmith/AudioRecorderComponent.tsx** | **13.45** | **15.56** | **6.98** | **15.55**
 :red_circle: | app/client/src/components/designSystems/appsmith/ChartComponent.tsx | 49.41 **(0)** | 21.98 **(-0.13)** | 50 **(0)** | 47.47 **(0)**
 :green_circle: | app/client/src/icons/WidgetIcons.tsx | 95.45 **(0.14)** | 100 **(0)** | 90.63 **(0.31)** | 95.45 **(0.14)**
 :red_circle: | app/client/src/utils/WidgetRegistry.tsx | 79.49 **(-0.33)** | 100 **(0)** | 38.46 **(-1.01)** | 79.49 **(-0.33)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 50.47 **(-0.24)** | 37.72 **(-0.88)** | 36.21 **(0)** | 55.08 **(-0.27)**
 :sparkles: :new: | **app/client/src/widgets/AudioRecorderWidget.tsx** | **47.62** | **0** | **50** | **47.5**</details>

### CODE REVIEW

**Comment by jsartisan** [comment]
@wmdev0808 Looks awesome on the first attempt! :D

Just a few things to note:

1. The orange is not there in color dropdown control.
2. The icon size of the default state and recording states are different for the orange button. ( i think the sizes are the same but they look too big for pause and recording icon. 40% size looks good to me but that does not look good for the mic icon.
3. can you make the icons for stop and discard from 16 to 20?
4. Can you add expanding animation on the orange light border? ( sorry I missed in the developer handoff )
5. Also, can you remove the border from the orange icon? I see there is some border on the icon button.

Overall, its looking great in the first attempt already. Super work Paul!

**Review by jsartisan — APPROVED** [review]

**Comment by jsartisan** [comment]
@somangshu  @wmdev0808  LGTM!

**Comment by YogeshJayaseelan** [comment]
@wmdev0808 @jsartisan - Tested this feature and please find the observations below,

1. There is no file type extension related to audio file to download the saved file

Screenshot 2021-08-25 at 5 59 45 PM

2. If the browser permission is disabled for recording - Then the following message should be displayed as per figma - 'Permission not given' 
Suggestion - Instead of showing 'Permission not given' if the permission for recording is disabled can we enable the recording icon so that whenever user clicks on recording any alert message can be disabled to enable the permission - similar to location enable in maps

Screenshot 2021-08-25 at 6 07 47 PM

3. when the recorder widget is disabled and when the user clicks on the widget the property pane opens

https://www.loom.com/share/8a2c4ebd0b624b60845642d848f197bf

4. When an recorder widget which has recording saved and copy pasted the saved recording is not available in the copied widget 

Screenshot 2021-08-25 at 6 15 01 PM

**Review by somangshu — DISMISSED** [review]
LGTM

**Comment by YogeshJayaseelan** [comment]
@wmdev0808 Raised separate issue for point 1 - #6958 

**Issues Fixed:**
2

**Agreed on comments for issues 3 & 4**

New issues:
5.When an recorded audio is re-played and clicking on stop button resets the widget to original mode 

https://loom.com/share/45241f5305eb4361bc8f6e5f62879d5c

6. When recording is started and enabling the disable option - It is observed that the recording is still happening and the stop and discard button is accessible 

https://loom.com/share/ada82f37d6b44964ab0bf253b769d7f3

**Comment by wmdev0808** [comment]
> @wmdev0808 Raised separate issue for point 1 - #6958
> 
> **Issues Fixed:**
> 2
> 
> **Agreed on comments for issues 3 & 4**
> 
> New issues:
> 5.When an recorded audio is re-played and clicking on stop button resets the widget to original mode
> 
> https://loom.com/share/45241f5305eb4361bc8f6e5f62879d5c
> 
> 1. When recording is started and enabling the disable option - It is observed that the recording is still happening and the stop and discard button is accessible
> 
> https://loom.com/share/ada82f37d6b44964ab0bf253b769d7f3

@YogeshJayaseelan and @jsartisan, 
5: it is the normal action from the requirements, because we can go to the first step from saved state by clicking on the left recording button or clicking on stop button.
6: What's the appropriate action exactly for this scenario?

**Comment by somangshu** [comment]
@YogeshJayaseelan point 6 is invalid, the user does not have the choice to disable the widget from the property pane, Plus for an ongoing recording a disable state seems invalid, The state needs to be available before the action is taken.

@wmdev0808 I think point 5 valid. Seems like an inconsistency in the behaviour. For the first time the recording is stopped, But in the second time the widget is reset to the original state. The original state should only show up on click of the big check mark. Additionally we can remove the stop icon from this state. We only need pause and play actions. Let me know what you think

**Comment by wmdev0808** [comment]
> @YogeshJayaseelan point 6 is invalid, the user does not have the choice to disable the widget from the property pane, Plus for an ongoing recording a disable state seems invalid, The state needs to be available before the action is taken.
> 
> @wmdev0808 I think point 5 valid. Seems like an inconsistency in the behaviour. For the first time the recording is stopped, But in the second time the widget is reset to the original state. The original state should only show up on click of the big check mark. Additionally we can remove the stop icon from this state. We only need pause and play actions. Let me know what you think

@somangshu I agree with you. I will make changes

**Review by somangshu — DISMISSED** [review]
LGTM

**Comment by jsartisan** [comment]
@somangshu would need a way to expose the recorded audio in a format that is accepted by our APIs/Query. I'll be checking this. will get back to you.

**Comment by YogeshJayaseelan** [comment]
@wmdev0808 Verified the fix for 5th point and the issue still exists and please find the steps below

Record an audio and click on stop and click on tick mark icon to save the recordings and re-play the saved audio and click on pause the stop button will be displayed and click on stop button the widget resets to original mode.

https://loom.com/share/10e151ff321a4049b273f74ef17d48dc

**Comment by jsartisan** [comment]
@wmdev0808 can you add a derived property `url` on thewidget

```
url: `{{URL.createObjectURL(this.value)}}`,
```

**Review by somangshu — APPROVED** [review]
Name changes, Looks good to me

**Review by jsartisan — APPROVED** [review]

**Comment by YogeshJayaseelan** [comment]
@wmdev0808 @somangshu Issue 6 - The canvas breaks by default and unable to proceed testing audio widget

https://www.loom.com/share/455a3939aeab4743872f96651889b7a0

**Comment by somangshu** [comment]
@YogeshJayaseelan you might be having a widget in this app which does not exist in the DP, Please remove all the widgets from the sidebar and try again=

**Comment by YogeshJayaseelan** [comment]
@somangshu Initially i tried with existing app which has audio widget and that didn't work so again i tried creating new app in the DP and facing the same issue in new app which doesn't have any widgets

**Comment by somangshu** [comment]
@YogeshJayaseelan I saw a similar error, This was something to do with the derivedProperties and evaluations, Could be a merge required in the branch, However once I delete the widgets I dont see the error anymore. Regardless, @wmdev0808 there is a merge conflict, Can we resolve that and see if that fixes the above problem

**Review by somangshu — APPROVED** [review]

**Comment by YogeshJayaseelan** [comment]
@wmdev0808 Verified the fix for issue 5 & 6 and they are working as expected

**Pull request merged**
