### PR TITLE
fix: Make async evaluation as default

### PR DESCRIPTION
**Pull request by Rishabh-Rathod**
## Description

Current evaluation architecture has 2 natures of evaluation
- sync evaluation ( evaluation for data fields )
- async evaluation ( evaluation for trigger events )

For every evaluation, this nature needs to be set according to the field being evaluated. 
It was noticed that for async code evaluation where a code block executes only after the resolution of promise, for example,  

`fetch().then((res) => { showAlert("fetched") });`

Here, the `showAlert` only executes when the fetch is completed and before that, it could be possible that we have switched to sync evaluation in the worker. This would lead to a `showAlert` throwing error.

Hence, we resolve this issue by making `async evaluation` as the default nature of evaluation.  

Fixes https://github.com/appsmithorg/appsmith/issues/19733

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual
1. Validated Supabse app to check the error and JSPDF 
2. Validated sync data field with sync function and framework function  - verify that error for async function is displayed properly 
3. Validated older apps(Automation app/Silly string) to verify the Async error is not displayed 
4. .then and catch block in async function - 

- Jest
- Cypress

### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by Rishabh-Rathod — COMMENTED** [review]
LGTM

**Review by arunvjn — APPROVED** [review]
We need better names and remove IS_SYNC & ALLOW_SYNC keywords from global object, approving it for now.

**Review by Rishabh-Rathod — COMMENTED** [review]
Self review done.

**Pull request merged**
