### PR TITLE
fix: code hidden issue for JS Enabled fields

### LINKED ISSUE #13227: [Bug]: Property Pane - JS Enabled property value is visible only when clicked on the code editor.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In a property pane when a section is collapsed by default and a property under that section has the JS mode enabled, the value only shows up when the JS enabled input is clicked.

Note: This only happens if the Section is collapsed by default but not on the opened one as shown in the loom video.

### Steps To Reproduce

[LOOM DEMO](https://www.loom.com/share/f202f73819b749699962c416e95212a9)

### Public Sample App

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by ganganimaulik**
## Description

https://codemirror.net/doc/manual.html#addon_autorefresh
auto refresh was imported but not enabled, this will fix it.

Fixes #13227 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Tested manually by repeating steps provided in issue video

### CODE REVIEW

**Comment by ashit-rath** [comment]
Hello @ganganimaulik 👋 Thank you for contributing to Appsmith.

As this is a bug fix we would like you to add a cypress test to validate the fix.

**Comment by ganganimaulik** [comment]
> Hello @ganganimaulik 👋 Thank you for contributing to Appsmith.
> 
> As this is a bug fix we would like you to add a cypress test to validate the fix.

added test

**Review by ashit-rath — APPROVED** [review]

**Review by riodeuno — APPROVED** [review]

**Review by Nikhil-Nandagopal — APPROVED** [review]

**Comment by YogeshJayaseelan** [comment]
@ashit-rath Tested this and it is working as expected now

**Pull request merged**
