### PR TITLE
fix: Multiseries chart data does not load completely

### LINKED ISSUE #20212: [Bug]-[162]:Multi-series charts fail to load properly when a datapoint is set to 0
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When i have a multi-series line or column or any other default chart and any data point's y axis value is set to 0, the chart shows it as undefined. It works when we change it to "0" as a string but not as a number.

Screenshot 2023-01-30 at 3 53 30 PM

### Steps To Reproduce

1. Add a new chart widget and set it to line chart
2. Add data which contains y axis as 0, sample attached below
3. Add a new series
4. Observe the points where the data is 0 now show undefined

`[
  {
    "x": "Jul",
    "y": 3
  },
  {
    "x": "Aug",
    "y": 2
  },
  {
    "x": "Sep",
    "y": 2
  },
  {
    "x": "Oct",
    "y": 0
  },
  {
    "x": "Nov",
    "y": 2
  },
  {
    "x": "Dec",
    "y": 0
  },
  {
    "x": "Jan",
    "y": 1
  }
]`

### Public Sample App

_No response_

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by souma-ghosh**
## Description

When single series line chart data has 0 in one y axis value the chart renders fine but when we add a series to the chart the 0 values were being sent as null. This was because of an `if` condition which would send null if the value is 0.
This PR fixes it so that 0 values are passed down to chart properly.

Fixes #20212

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Jest

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [x] Test plan has been approved by relevant developers
- [x] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by jsartisan — APPROVED** [review]
LGTM!

**Comment by chandannkumar** [comment]
Tested this PR and LGTM
- Tested all default charts with single and multi series chart
- Tested the same on containers and modals type widgets

**Pull request merged**
