### PR TITLE
fix: 'are you sure' state reset

### LINKED ISSUE #31278: fixing UX bug related to "are you sure" state
The "are you sure" state isn't been reseted when we close the popup window in some parts of our app, over here we are fixing this to maintain parity with rest of our application.

### PR DESCRIPTION
**Pull request by vsvamsi1**
## Description
We have to reset the state of "are you sure" after closing the menu, currently it sticks around once the user clicks on the delete button.
#### PR fixes following issue(s)
Fixes #31278

#### Type of change
- Bug fix (non-breaking change which fixes an issue)
>
>
>
#### How Has This Been Tested?
- [x] Manual
- [ ] JUnit
- [ ] Jest
- [x] Cypress
>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

## Summary by CodeRabbit

- **New Features**
	- Enhanced state management for the `confirmDelete` action across various editor components, ensuring a more intuitive user experience when interacting with context menus.

### CODE REVIEW

**Comment by albinAppsmith** [comment]
@vsvamsi1 Can you add a video of the issue? I see it is working for me in local.

**Comment by vsvamsi1** [comment]
Hi @albinAppsmith here is the loom link for it
https://www.loom.com/share/84d0a3654c3145b0a6f1db7eb2e08c6e

**Review by marks0351 — APPROVED** [review]

**Review by albinAppsmith — APPROVED** [review]

**Pull request merged**
