### PR TITLE
chore: Updated direct string usages to static string variables

### PR DESCRIPTION
**Pull request by vishnu-gp**
## Description
This PR updates the usage of direct string names in the code.

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Locally

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by AnaghHegde — APPROVED** [review]

**Comment by vishnu-gp** [comment]
Closing this PR because this is now being handled from EE for the time being.

**Pull request closed without merging**
