### PR TITLE
test: Cypress - add method for deleting branch

### PR DESCRIPTION
**Pull request by Parthvi12**
## Description
Updates DeleteBranch test and adds common method for deleting branch

- [ ] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by Aishwarya-U-R — APPROVED** [review]

**Comment by Aishwarya-U-R** [comment]
Run it few more times just to be sure & revert limit test & PR can be merged.

**Comment by Aishwarya-U-R** [comment]
@Parthvi12 -Oh, whats the difference please, between then & now?

**Comment by Parthvi12** [comment]
Attaching the screenshot :
Screenshot 2023-09-04 at 11 29 24 AM
On release this test completes within 5 mins

**Comment by Aishwarya-U-R** [comment]
Is the change after moving to a method from Helper. That is weird. Last has taken 6 mins. Try this a couple of times if time is consistent around 6mins , we can merge it. Else move the method back to local scope.

**Comment by Parthvi12** [comment]
@Aishwarya-U-R Latest run also too 15mins, I think we should move it to local scope.

**Comment by Aishwarya-U-R** [comment]
Ok, let it stay as local scope. We can come back to this PR later.

**Pull request closed without merging**
