### PR TITLE
feat: dynamic checkbox widget standardisation

### LINKED ISSUE #13638: [Task]: Standardise Structure of Checkbox widget to enable Dynamic Height
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

_No response_

### PR DESCRIPTION
**Pull request by ankurrsinghal**
## Description

1. Passed the `contentRef` to `CheckboxComponent` from `CheckboxWidget`.
2. Wrapped the `CheckboxComponent` class component in the React.forwardRef and added an optional prop `innerRef` and the forwarded `ref` to `innerRef`.
3. Set the final `innerRef` to the ref of `CheckboxContainer` which is a styled `div`.

Fixes #13638 

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Manually

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by riodeuno — CHANGES_REQUESTED** [review]
Please resolve the extra diffs showing here. I've commented on the checkbox widget PR with what I assume is the case.

**Review by rahulramesha — APPROVED** [review]

**Comment by btsgh** [comment]
Tested on the Vercel link provided above and it seems to be working as expected. No issues seen.

**Pull request merged**
