### PR TITLE
fix: separating property pane out of widgets editor to avoid triggering unwanted events on widget canvas

### LINKED ISSUE #11079: [Bug]: Widget grouping mode is triggered after re-arranging table columns
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After dragging and re-arranging columns of table widget, moving cursor to canvas causes the widget grouping mode to be triggered.

https://user-images.githubusercontent.com/10436935/153403013-443d8b49-6952-4ad0-bc3d-afb7509a8bd9.mov

### Steps To Reproduce

1. Add a table widget or any other widget that has a draggable list items in the property pane
2. drag and re-arrange the list items in the property pane
3. move the cursor to the canvas to notice the issue.

### Environment

Release

### Version

Cloud

### LINKED ISSUE #11378: [Bug]: Selecting a widget from the list on the right side pane, does not open propertypane anymore
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There seems to be a regression, clicking on the widget button from the list of grouped widgets does not seem to open properties pane of that widget anymore.

https://user-images.githubusercontent.com/71900764/155273881-3e5b077a-e36d-451e-8c20-08e9545b5cf6.mp4

### Steps To Reproduce

1. Select multiple widget
2. on the right side pane, click on one of the buttons from the list
3. see that property pane of the widget clicked does not open

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by rahulramesha**
## Description

PropertyPane inside Widgets Editor causes events to be trigerred that is not meant for property pane. So, separating it out of Widgets Editor.

Fixes #11378
Fixes #11079

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

manual UI and cypress

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: widgetsEditorEventFix 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 55.73 **(0.01)** | 37.05 **(0.01)** | 35.79 **(0)** | 56.09 **(0.01)**
 :green_circle: | app/client/src/pages/Editor/MultiSelectPropertyPane/index.tsx | 85.71 **(0.71)** | 50 **(0)** | 66.67 **(0)** | 88.89 **(0.65)**
 :sparkles: :new: | **app/client/src/pages/Editor/WidgetsEditor/PropertyPaneContainer.tsx** | **86.67** | **100** | **33.33** | **84.62**
 :green_circle: | app/client/src/pages/Editor/WidgetsEditor/index.tsx | 93.75 **(1.97)** | 60 **(0)** | 100 **(25)** | 93.44 **(2.26)**
 :green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.94 **(0.23)** | 41.67 **(0.84)** | 36.21 **(0)** | 56.99 **(0.25)**</details>

### CODE REVIEW

**Review by arunvjn — APPROVED** [review]
LGTM!

**Comment by vivekverma2312** [comment]
@rahulramesha Tested and working fine.

**Review by arunvjn — APPROVED** [review]

**Review by jsartisan — APPROVED** [review]

**Comment by vivekverma2312** [comment]
@rahulramesha Tested the guided tour and working fine.

**Pull request merged**
