### PR TITLE
fix: numeric type input widget should accept zero after decimal point

### LINKED ISSUE #11449: [Bug]: Number type input widget clears an entry when there's a decimal followed by a zero
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Input widget clears an entry when there's a decimal followed by a zero. Typing consecutive periods and then hitting 0 clears all input from the widget.

### Steps To Reproduce

[LOOM DEMO](https://www.loom.com/share/49d05b2ea0b64b43a1b4113e22bb5fc6)

1. Change Input widget type to Number and try to enter `1.06` and observe the value revert to `1`
2. Try to type `1..0` and observe field values getting cleared

### Environment

Production

### Version

Cloud

### LINKED ISSUE #11839: [Bug]: null as defaultValue evaluates to 0 in Input widget number type
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When {{null}} is bound to defaultValue of Input widget Number type, it evaluates to 0.

### Steps To Reproduce

1. Add an input widget to the canvas
2. choose Number type
3. Set {{null}} as defaultValue in property pane
4. Input has 0 as value.

### Public Sample App

_No response_

### Version

clound

### PR DESCRIPTION
**Pull request by sbalaji1192**
## Description
Originally we solved this issue by converting the text property into a derived property. but that started causing issues when the Input widget was placed inside the List widget. https://github.com/appsmithorg/appsmith/issues/11833
Note: 
- Ideally, the text property of the input widget should be a derived property. 
  But derived properties of List widget children won't work. so having the text
  property of the Input widget as a derived property causes issues. hence changing
  it to a meta property.

Fixes #11449 
Fixes #11839 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/input-widget-decimal-value 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 55.59 **(0.02)** | 36.87 **(0.04)** | 34.87 **(0.01)** | 55.9 **(0.03)**
 :green_circle: | app/client/src/selectors/commentsSelectors.ts | 85.25 **(1.64)** | 64.71 **(2.95)** | 73.33 **(0)** | 90.59 **(2.35)**
 :green_circle: | app/client/src/widgets/BaseInputWidget/widget/index.tsx | 67.5 **(2.5)** | 7.14 **(0.89)** | 61.54 **(-5.13)** | 71.05 **(2.63)**
 :sparkles: :new: | **app/client/src/widgets/InputWidgetV2/widget/Utilities.ts** | **92.31** | **87.5** | **100** | **92.31**
 :green_circle: | app/client/src/widgets/InputWidgetV2/widget/index.tsx | 81.3 **(7.7)** | 68.18 **(7.31)** | 78.95 **(-2.3)** | 80.83 **(7.88)**
 :red_circle: | app/client/src/widgets/PhoneInputWidget/widget/index.tsx | 39.39 **(-1.24)** | 6.52 **(0)** | 40 **(-2.86)** | 39.18 **(-1.25)**</details>

### CODE REVIEW

**Review by jsartisan — DISMISSED** [review]

**Comment by vivekverma2312** [comment]
@sbalaji1192 Tested and LGTM

**Review by jsartisan — APPROVED** [review]

**Pull request merged**
