### PR TITLE
[Feature] Widget Grouping Phase - 3 (Cut Copy Paste)

### LINKED ISSUE #5014: Cut/Copy/Paste of selected widgets
- [x] Hot keys for cut(cmd/ctrl + x), copy(cmd/ctrl + c), paste(cmd/ctrl + v) for multiple widgets
- [x] UX for widget placement on paste
- [x] Implementing above UX(post discussion)

### LINKED ISSUE #5365: [Bug] Widget grouping UX issues
## Description
- [ ] Location of the bounding box does not follow the cursor closely

https://www.loom.com/share/f0ba4e3849ad4969b614e9ddb6ccbd2b

### PR DESCRIPTION
**Pull request by marks0351**
---
name: "Pull Request"
about: Create a pull request to submit new contributions to appsmith
title: "[FIX/FEATURE]"
labels:
assignees:
---

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Description

- [ ] Hot keys for cut(cmd/ctrl + x), copy(cmd/ctrl + c), paste(cmd/ctrl + v) for multiple widgets
- [ ] UX for widget placement on paste
- [ ] Implementing above UX(post discussion)

Fixes #5014 
Fixes #5365

> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: feature/widget-grouping-3 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 54.17 **(0.89)** | 36.15 **(0.88)** | 32.83 **(0.9)** | 54.66 **(0.86)**
 :red_circle: | app/client/src/actions/batchActions.ts | 71.43 **(-14.28)** | 100 **(0)** | 0 **(-50)** | 100 **(0)**
 :green_circle: | app/client/src/actions/controlActions.tsx | 76.92 **(7.69)** | 100 **(0)** | 25 **(25)** | 66.67 **(11.11)**
 :red_circle: | app/client/src/actions/metaActions.ts | 72.73 **(-9.09)** | 100 **(0)** | 0 **(-33.33)** | 62.5 **(-12.5)**
 :green_circle: | app/client/src/actions/widgetActions.tsx | 82 **(6)** | 0 **(0)** | 46.67 **(20)** | 76.47 **(8.82)**
 :red_circle: | app/client/src/actions/widgetSelectionActions.ts | 100 **(0)** | 50 **(-50)** | 100 **(0)** | 100 **(0)**
 :green_circle: | app/client/src/components/designSystems/appsmith/ContainerComponent.tsx | 93.33 **(0.47)** | 55 **(0)** | 100 **(0)** | 93.33 **(0.47)**
 :green_circle: | app/client/src/components/editorComponents/DropTargetComponent.tsx | 64.29 **(1.02)** | 39.73 **(1.37)** | 50 **(6.25)** | 59.77 **(1.15)**
 :green_circle: | app/client/src/components/editorComponents/CodeEditor/index.tsx | 76.21 **(2.42)** | 55.65 **(5.22)** | 59.38 **(3.13)** | 77.2 **(2.59)**
 :green_circle: | app/client/src/constants/messages.ts | 71.97 **(0.32)** | 100 **(0)** | 15.24 **(0.95)** | 76.03 **(0)**
 :green_circle: | app/client/src/pages/Editor/GlobalHotKeys.tsx | 71.25 **(18.24)** | 39.13 **(39.13)** | 60 **(24.52)** | 69.74 **(19.11)**
 :red_circle: | app/client/src/pages/Editor/Explorer/Pages/PageContextMenu.tsx | 71.43 **(-0.79)** | 60 **(0)** | 12.5 **(0)** | 73.53 **(-0.76)**
 :red_circle: | app/client/src/pages/common/CanvasSelectionArena.tsx | 90.38 **(-1.78)** | 57.58 **(0)** | 82.35 **(0)** | 90.1 **(-1.82)**
 :green_circle: | app/client/src/reducers/entityReducers/metaReducer.ts | 42.86 **(14.29)** | 0 **(0)** | 16.67 **(16.67)** | 42.86 **(14.29)**
 :green_circle: | app/client/src/reducers/uiReducers/dragResizeReducer.ts | 85 **(2.5)** | 61.54 **(3.85)** | 63.64 **(0)** | 87.18 **(2.56)**
 :green_circle: | app/client/src/sagas/ApplicationSagas.tsx | 19.9 **(1.05)** | 3.39 **(0)** | 9.09 **(0)** | 22.84 **(0.62)**
 :red_circle: | app/client/src/sagas/BatchSagas.tsx | 25.81 **(-16.13)** | 8.33 **(-16.67)** | 20 **(-20)** | 32 **(-20)**
 :red_circle: | app/client/src/sagas/EvaluationsSaga.ts | 17.5 **(0)** | 1.3 **(0)** | 3.85 **(-3.84)** | 20.35 **(0)**
 :green_circle: | app/client/src/sagas/RecentEntitiesSagas.ts | 44.83 **(0)** | 12.12 **(1.51)** | 50 **(0)** | 44.83 **(0)**
 :green_circle: | app/client/src/sagas/WidgetOperationSagas.tsx | 43.93 **(33.38)** | 30.28 **(29.03)** | 50.59 **(43.65)** | 44.3 **(32.92)**
 :red_circle: | app/client/src/sagas/WidgetOperationUtils.ts | 54.87 **(-8.09)** | 33.33 **(-13.34)** | 69.23 **(5.59)** | 55.45 **(-7.22)**
 :red_circle: | app/client/src/sagas/WidgetSelectionSagas.ts | 96.2 **(-2.28)** | 93.48 **(0.98)** | 100 **(0)** | 95.77 **(-2.54)**
 :green_circle: | app/client/src/utils/AppsmithUtils.tsx | 56.42 **(2.23)** | 29.07 **(5.81)** | 43.24 **(2.7)** | 52.26 **(2.58)**
 :green_circle: | app/client/src/utils/DynamicBindingUtils.ts | 90 **(1.54)** | 80.28 **(4.22)** | 76.19 **(4.76)** | 88.5 **(1.77)**
 :green_circle: | app/client/src/utils/helpers.tsx | 53.59 **(1.96)** | 26.76 **(4.22)** | 23.08 **(3.85)** | 47.5 **(2.5)**
 :green_circle: | app/client/src/utils/storage.ts | 43.48 **(8.7)** | 13.64 **(13.64)** | 22.22 **(18.52)** | 36.59 **(8.54)**
 :sparkles: :new: | **app/client/src/utils/hooks/useCanvasMinHeightUpdateHook.ts** | **100** | **85.71** | **100** | **100**
 :green_circle: | app/client/src/widgets/BaseWidget.tsx | 78.81 **(0)** | 44.19 **(2.33)** | 77.42 **(3.23)** | 77.88 **(0)**
 :red_circle: | app/client/src/widgets/MetaHOC.tsx | 75 **(-7.35)** | 47.37 **(-10.52)** | 92.31 **(0)** | 74.58 **(-8.47)**
 :green_circle: | app/client/src/widgets/Tabs/TabsWidget.tsx | 69.4 **(2.98)** | 46.24 **(9.68)** | 60.71 **(0)** | 68.5 **(3.15)**
 :sparkles: :new: | **app/client/test/testCommon.ts** | **100** | **50** | **100** | **100**
 :sparkles: :new: | **app/client/test/testMockedWidgets.tsx** | **100** | **100** | **100** | **100**
 :x: | ~~app/client/test/testCommon.tsx~~ | ~~100~~ | ~~50~~ | ~~100~~ | ~~100~~</details>

### CODE REVIEW

**Review by jsartisan — APPROVED** [review]

**Review by jsartisan — APPROVED** [review]

**Comment by vivekverma2312** [comment]
@marks0351 Feature has been tested on the deploy preview and looks good.

**Pull request merged**
