### PR TITLE
feat: added  isJSConvertible property in IconButton Widget

### LINKED ISSUE #11425: [Feature]: Icon Button Widget - the Icon and Button Color property should have JS option.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Screenshot 2022-02-24 at 6 42 07 PM
Users should be able to change the values of the Icon and Button Color property based on stat values.

### Why should this be worked on?

User request on the intercom - 
How can I change the icon in your stats box based on a certain value? For example, I will attach an image. I count the amount of bags yesterday and today, if the difference is a positive % I'd like a green icon with an upwards arrow. If it is a negative % I'd like a red icon like the one in the attachment
Screenshot 2022-02-24 at 6 46 55 PM
.

### PR DESCRIPTION
**Pull request by techbhavin**
## Description

>  Enabled Js Option in IconButton widget 

Fixes #11425 

## Type of change

- Bugfix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: feature/icon-button-widget-js-option 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 55.88 **(0)** | 37.22 **(-0.01)** | 35.24 **(0)** | 56.21 **(0)**
 :red_circle: | app/client/src/utils/WorkerUtil.ts | 89.76 **(0)** | 70.59 **(-1.96)** | 100 **(0)** | 93.33 **(0)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.71 **(-0.23)** | 40.83 **(-0.84)** | 36.21 **(0)** | 56.74 **(-0.25)**
 :green_circle: | app/client/src/widgets/IconButtonWidget/widget/index.tsx | 52.94 **(4.55)** | 0 **(0)** | 66.67 **(6.67)** | 53.13 **(4.85)**</details>

### CODE REVIEW

**Review by jsartisan — APPROVED** [review]

**Review by jsartisan — APPROVED** [review]

**Comment by YogeshJayaseelan** [comment]
@techbhavin Tested this feature and please find the status below,

Issue1 - The JS condition are displayed on the icon property field on disabling the JS option 

https://www.loom.com/share/7834848f4e7843bfb6a4a61fbed0382b

**Comment by YogeshJayaseelan** [comment]
@techbhavin Tested this PR and it is working as expected now

**Pull request merged**
