### PR TITLE
fix: Updated Template

### PR DESCRIPTION
**Pull request by keyurparalkar**
## Description

**Summary of changes**

- Replaced all the input widgets with the new Input widget for the CRUD app.

Fixes # (issue)

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

This is only tested on PostgreSQL page for updating the records in the table. 
Input widget needs to be tested on all the pages.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Rishabh-Rathod — CHANGES_REQUESTED** [review]
There are instances of INPUT_WIDGET still available in most of the pages, Inside insert modal also in other modal.

**Review by Rishabh-Rathod — APPROVED** [review]
Looks good to me.

This needs QA after it is merged to release.
@RakshaKShetty All CRUD template functionality needs to be checked once this PR is merged.

**Comment by RakshaKShetty** [comment]
@keyurparalkar following are the issues we are facing in CRUd pages:
1. The input widget name has been changed because of which the Insert fails
2. The update button deletes the data from the table
3.  When there is a build data and user tries to insert the data the data doesn't get inserted in table (might be same as 1st issue because of the name change in the input widget)

**Pull request merged**
