### PR TITLE
fix: icon button remove default green

### LINKED ISSUE #10309: [Bug]: Iconbutton widget when changed to 'no color' still remains green
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Iconbutton widget when changed to 'no color' still remains green.  Where as a button widget on canvas when changed to 'no color' appears transparent and on hover turns green.
image

https://loom.com/share/45ebfcc2b50349fd96d75377c276c3d5

### Steps To Reproduce

1. Drag and drop a IconButton widget
2. Change the Button color to 'no color' and observe

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by techbhavin**
## Description

>  Remove Default color from Icon Button Widget

Fixes #10309

## Type of change

- Bugfix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>

    // Code coverage diff between base branch:release and head branch: bug/icn-btn-handle-no-color 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.71 **(-0.23)** | 40.83 **(-0.84)** | 36.21 **(0)** | 56.74 **(-0.25)**
 :red_circle: | app/client/src/widgets/IconButtonWidget/widget/index.tsx | 48.39 **(-1.61)** | 0 **(0)** | 60 **(0)** | 48.28 **(-1.72)**</details>

### CODE REVIEW

**Review by somangshu — APPROVED** [review]
LGTM

**Comment by somangshu** [comment]
@techbhavin Tested the deploy preview, Everything looks good, Only one point:
- For the older buttons, Setting to noColor still has the hover color. This is not reproducible for the new buttons
Screenshot 2022-01-25 at 11 31 32 AM

**Comment by somangshu** [comment]
> * For the older buttons, Setting to noColor still has the hover color. This is not reproducible for the new buttons

@techbhavin I figured this happens when there is an onClick action configured, I am seeing the hover color even when the noColor is set

**Comment by YogeshJayaseelan** [comment]
@techbhavin Verified this and it is working as expected

**Pull request merged**
