### PR TITLE
Fix/fix chart layout

### LINKED ISSUE #26867: [Bug]: Fix fusion to echart UI consistency issues
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

There are multiple issues that will be listed down here to maintain the consistency between fusion charts and echarts.

1. Long labels should not overlap in any chart.
2. Undefined should not appear in legend if there is only one series. If there are multiple series, undefined can appear for any series which doesn't have series title.

### Steps To Reproduce

NA

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by rajatagrawal**
Fixes #26867

### CODE REVIEW

**Comment by laveena-en** [comment]
@rajatagrawal 
Bar chart: Labels on the x axis aren’t seen after a certain point. They don’t show up even when the widget is resized to a large extent 
image

Column Chart: When long labels are added, the ellipsis doesn’t go away to reveal the entire data even on resizing the widget considerably. [Loom](https://www.loom.com/share/Untitled-application-25-or-Editor-or-Appsmith-14-September-2023-8f43f57de2314f78a00ffdadd70add20?sid=0b736347-6730-4775-92f9-bc3b2a2ac800)

**Review by sbalaji1192 — APPROVED** [review]

**Comment by laveena-en** [comment]
@rajatagrawal As discussed, can we add in ellipsis to mitigate overlap on labels in the Y-axis.
image

The chart size is also changing once deployed: https://www.loom.com/share/Untitled-application-1-or-Editor-or-Appsmith-15-September-2023-231b47c6251248d8acfeede958ee1c25?sid=a24bd565-ce95-4428-ac44-2ddd94b6c5c8

Also, on removing a series data (not the object itself) and when only one series remains, we still see an undefined legend on the widget

**Comment by laveena-en** [comment]
Verified. Changes look good to me!

**Review by laveena-en — APPROVED** [review]
LGTM

**Pull request merged**
