### PR TITLE
feat: Migrates add template page modal to new ads component

### LINKED ISSUE #22762: [Task]: Deduplicate components & Grayscale/theming support in Add Page from Template
https://www.loom.com/share/9bf1e7edce9b4f16bdc5c98218c395e2

### PR DESCRIPTION
**Pull request by Irongade**
This PR migrates  the add template page modal to new ads component .

Fixes #22762 

-> Added title in modal
-> Back button is renamed from "back to templates" to "back"
-> Back button is aligned left to Template title.

Changes are done after discussion with design

Issue listed in notion are updated with comment
https://www.notion.so/appsmith/f353d8c6bd664f79ad858a42010cdfc8?v=f04cde23f6424aeb9d5a6e389cd172bd&p=b7cd3189a860465bb8ccab63a8c2c997&pm=s

### Media
https://www.loom.com/share/fc5fd7dc5585457ebd32aec6813a639e

- Manual
- Jest
- Cypress

### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by albinAppsmith — APPROVED** [review]

**Comment by shadabbuchh** [comment]
Tested this PR. All QA callouts in [this](https://www.notion.so/appsmith/f353d8c6bd664f79ad858a42010cdfc8?v=f04cde23f6424aeb9d5a6e389cd172bd&p=b7cd3189a860465bb8ccab63a8c2c997&pm=s) Notion doc are fixed & retested.

**Pull request merged**
