### PR TITLE
feat: add support for http2 protocol for REST API plugin and GraphQL plugin

### LINKED ISSUE #28226: [Feature]: Rest API plugin: enable HTTP 2.0
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

- Enable HTTP 2.0 protocol for web client based requests. 
- [ref](https://github.com/appsmithorg/appsmith/issues/27919)
- Update (25 Oct 2023):
  * My understanding so far had been that if multiple HTTP protocols are enabled then the webclient and the remote server can negotiate (e.g ALPN protocol) automatically on which protocol to use. 
  * An CI failure caught an [edge case](https://docs.arangodb.com/3.11/develop/http/general-request-handling/#switch-protocols) where the remote server was not able to automatically figure out which protocol to use between `HTTP` and `H2C` - thus causing the API request to fail.  
  * Based on the above two points my new understanding is that the preferred solution to this problem should be a selector configuration provided to the user on the action configuration page to select the preferred protocol
  * [previous attempt at fix](https://github.com/appsmithorg/appsmith/pull/28247) 

### Why should this be worked on?

- new feature

### PR DESCRIPTION
**Pull request by sumitsum**
## Description
- Currently, the REST API and GraphQL plugins cannot make HTTP calls to endpoints where the endpoint server only supports HTTP 2.0 . 
- This PR updates the REST API plugin and GraphQL plugin to use HTTP2 protocol as well, along with the default HTTP1.1 protocol that is uses right now. 
- As per my limited experimentation, it seems that when both HTTP2 and HTTP1.1 are configured for Spring webclient, it would by default choose HTTP1.1 first, and only choose HTTP2 if HTTP1.1. is rejected by the endpoint server. 

#### PR fixes following issue(s)
Fixes #28226 

#### Type of change
- New feature (non-breaking change which adds functionality)

#### How Has This Been Tested?
- [x] Manual
- Automation test case does not seem possible at the moment.

#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by trishaanand — APPROVED** [review]

**Comment by sumitsum** [comment]
Closing this because:
* My understanding so far had been that if multiple HTTP protocols are enabled then the webclient and the remote server can negotiate (e.g ALPN protocol) automatically on which protocol to use. 
* An CI failure caught an [edge case](https://docs.arangodb.com/3.11/develop/http/general-request-handling/#switch-protocols) where the remote server was not able to automatically figure out which protocol to use between `HTTP` and `H2C` - thus causing the API request to fail.  
* Based on the above two points my new understanding is that the preferred solution to this problem should be a selector configuration provided to the user on the action configuration page to select the preferred protocol.

**Pull request closed without merging**
