### PR TITLE
fix: OAuth Client Credential Token Refresh Timeout

### LINKED ISSUE #20538: [Bug]: OAuth with client credentials fail for UiPath OAuth service
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

OAuth with client credentials fail for UiPath OAuth service
Ref: https://theappsmith.slack.com/archives/C0385FH70E8/p1671153589146359

### Steps To Reproduce

Ref: https://theappsmith.slack.com/archives/C0385FH70E8/p1671153589146359

### Public Sample App

_No response_

### Issue video log

_No response_

### Version

self hosted, cloud

### PR DESCRIPTION
**Pull request by PiyushPushkar02**
## **Description**

- The PR adds a retry logic for OAuth token generation in case of any failures
- The number of retries is hardcoded to 1 for now

Fixes #20538 

### **Type of Change**

- Bug Fix(non-breaking change which adds functionality)

### **How Has This Been Tested?**
- Manual

### **Checklist**:

- [x]  My code follows the style guidelines of this project
- [x]  I have performed a self-review of my own code
- [ ]  I have commented my code, particularly in hard-to-understand areas
- [ ]  I have made corresponding changes to the documentation
- [ ]  My changes generate no new warnings
- [ ]  I have added tests that prove my fix is effective or that my feature works
- [x]  New and existing unit tests pass locally with my changes
- [ ]  PR is being merged under a feature flag

### **QA activity:**

- [ ]  Test plan has been approved by relevant developers
- [ ]  Test plan has been peer reviewed by QA
- [ ]  Cypress test cases have been added and approved by either SDET or manual QA
- [ ]  Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ]  Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Comment by sumitsum** [comment]
Marking it as draft for the moment as we are not able to reliably reproduce the issue.

**Comment by sumitsum** [comment]
Removing my name from the reviewer's list for now since it is showing up in my awaiting review list. Will take this up for review again when we are ready for this PR.

**Comment by PiyushPushkar02** [comment]
Closing this ticket as this PR is not valid anymore

**Pull request closed without merging**
