### PR TITLE
feat: debugger query pane navigation

### PR DESCRIPTION
**Pull request by akash-codemonk**
## Description
Navigates to the tab, and scrolls to the property field for the query pane. 

If the field isn't visible for e.g an error exists for a field which is not visible as requires some other option to be selected, then it would just switch to the tab. It won't modify the values for the field to be visible. 

We find out if the property exists in the settings config of the plugin if yes we switch to the settings tab, else we switch to the query tab. Query response errors do not have property path associated, so they just switch to the query tab.

#### PR fixes following issue(s)
Fixes https://github.com/appsmithorg/appsmith/issues/25466

#### Media

https://github.com/appsmithorg/appsmith/assets/67054171/4bbe1039-a18d-4177-ac68-24a0077a639b

#### Type of change

- New feature (non-breaking change which adds functionality)

#### How Has This Been Tested?

- [x] Manual
- [ ] Jest
- [x] Cypress
>
>
#### Test Plan
https://github.com/appsmithorg/TestSmith/issues/2466

#### Issues raised during DP testing
https://github.com/appsmithorg/appsmith/pull/25853#issuecomment-1658426581

>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [x] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [x] Test plan has been peer reviewed by project stakeholders and other QA members
- [x] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Comment by kavitasmoolya** [comment]
@akash-codemonk 

- [ ] Issue 1 : PostgreSQL query page : Ambiguity in navigation to "Use Prepared Statement" option as it is available in both query and setting page
https://www.loom.com/share/14297987c55c496fbdf2b20dd669587a?sid=b76ecd02-922a-45a3-b7fb-f6a868181df9

**Comment by akash-codemonk** [comment]
> * [ ]  Issue 1 : PostgreSQL query page : Ambiguity in navigation to "Use Prepared Statement" option as it is available in both query and setting page

Expected. It first searches for in the settings pane which is why it goes there. 

> * [ ]  Issue 2 : Firestore DS : Query pane elements are not showing up when we navigate to it from SMTP DS query page and same issue observed with refreshing the Firestore DS query page.

Expected. We can repro this in release as well while switching queries. This will be a bug in the query pane so out of scope of the PR

> * [ ]  Issue 3 : Airtable DS : Unable to navigate to sub option under Query panel

Expected. This is similar to cases in property pane and api pane where the field doesn't exist in the UI but the error continues to exist. Ideally the error shouldn't be there but that will out of scope of the PR. 

@kavitasmoolya

**Review by hetunandu — APPROVED** [review]

**Pull request merged**
