### PR TITLE
fix: added margin top to the onboarding flow if banner visible

### LINKED ISSUE #30953: [Bug]: The `Skip, I'll do it later` option isn't seen on the `Start with Data` default flow for few users
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The `Skip, I'll do it later` option isn't seen on the `Start with Data` default flow for few users. Unable to reproduce it with every sign-up.

image

### Steps To Reproduce

1. Sign up on https://nightly-saml-alb-https.appsmith.com
2. Notice that the `Skip, I'll do it later` option isn't seen on the `Start with Data` default flow f

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

Appsmith c136fdbe

### PR DESCRIPTION
**Pull request by AmanAgarwal041**
## Description
Earlier the since the license banner had fixed position which was making the skip section gets hidden. Hence as the page header is positioned 40px below the banner if it is visible. We are doing the same for the onboarding flow.
Screenshot 2024-03-05 at 11 33 47 PM

#### PR fixes following issue(s)
Fixes #30953

#### Media

https://github.com/appsmithorg/appsmith/assets/7565635/c090e06a-0cee-49a4-a48d-5b14dd79bf19

>
>
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
- [ ] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

## Summary by CodeRabbit

- **New Features**
	- Introduced a conditional banner visibility in the application creation interface, enhancing user experience by dynamically adjusting UI layout.

### CODE REVIEW

**Comment by AmanAgarwal041** [comment]
Find the deployed preview for testing on : https://github.com/appsmithorg/appsmith-ee/pull/3657

**Review by sneha122 — DISMISSED** [review]

**Comment by sneha122** [comment]
Tested both CE and EE DPs, everything looks good!!

**Review by sneha122 — APPROVED** [review]

**Pull request merged**
