### PR TITLE
fix: entity link in errors

### LINKED ISSUE #21816: [Task]: Update entity link to highlight the error
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Update entity link to highlight the error

### PR DESCRIPTION
**Pull request by ChandanBalajiBP**
## Description

> Fixes broken entity link to SAAS plugins

Fixes #21816 
#21289

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by ayushpahwa — APPROVED** [review]

**Review by ayushpahwa — APPROVED** [review]

**Comment by ChandanBalajiBP** [comment]
Prapulla has moved from moolya to appsmith today, and hence have required permission to add test approval comment and label. Hence adding it myself.

The QA has completed on this PR. Looks good from their side.

**Comment by ChandanBalajiBP** [comment]
We can only write cypress test case for gSheets after migrating to cy12. Hence not adding any new test cases here.

**Pull request merged**
