### PR TITLE
Modified error displayed to user on generic bad request

### LINKED ISSUE #2582: Unreadable error when trying to import empty curl command
Sentry Issue: [APPSMITH-B9](https://sentry.io/organizations/appsmith/issues/2055764872/?referrer=github_integration)

```
ServerWebInputException: 400 BAD_REQUEST "Request body is missing: public reactor.core.publisher.Mono<com.appsmith.server.dtos.ResponseDTO<com.appsmith.server.dtos.ActionDTO>> com.appsmith.server.controllers.RestApiImportController.create(java.lang.Object,com.appsmith.server.domains.RestApiImporterType,java.lang.String,java.lang.String,java.lang.String,java.lang.String)"
    at org.springframework.web.reactive.result.method.annotation.AbstractMessageReaderArgumentResolver.handleMissingBody(AbstractMessageReaderArgumentResolver.java:230)
    at org.springframework.web.reactive.result.method.annotation.AbstractMessageReaderArgumentResolver.lambda$readBody$8(AbstractMessageReaderArgumentResolver.java:215)
    at reactor.core.publisher.MonoErrorSupplied.subscribe(MonoErrorSupplied.java:70)
    at reactor.core.publisher.Mono.subscribe(Mono.java:4105)
    at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:75)
...
(14 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by nidhi-nair**
Fixes #2582 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
image
image

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by mohanarpit** [comment]
Is there a way to form a better error message? I understand that you've made changes to the `GlobalExceptionHandler` for this PR. But from a user's perspective, they still don't know what to do in order to fix the problem. Any way to make this message more empathetic?

**Comment by nidhi-nair** [comment]
> Is there a way to form a better error message? I understand that you've made changes to the `GlobalExceptionHandler` for this PR. But from a user's perspective, they still don't know what to do in order to fix the problem. Any way to make this message more empathetic?

@mohanarpit There are two ways to go about this. 
1. We can let the data flow through into the request and handle validation for each request separately. This way every time such exceptions are thrown we add more validations to our APIs.
2. A more generic method would be to check if the expected field is null or empty in the global handler, and send out a more vague error message saying "Please check the inputs to this form" / "Are you sure you haven't left a required field empty?".

**Comment by nidhi-nair** [comment]
@trishaanand Were you talking about option 1 from the suggestions above?

**Comment by trishaanand** [comment]
> @trishaanand Were you talking about option 1 from the suggestions above?

@nidhi-nair : Yes. If we go this route, we can have super helpful messages to guide the user on how to fix them.

**Comment by nidhi-nair** [comment]
@trishaanand updated handling for this specific case. I have left the code changes for generic prettification for all the uncaught cases we have not yet discovered.

**Review by trishaanand — APPROVED** [review]

**Pull request merged**
