### PR TITLE
fix: gsheet multiline broken formatting fixed

### LINKED ISSUE #14915: [Bug]: Newline character and multiline formatting breaks when using Bulk Insert/Update with Google Sheets
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I am adding/updating a single record into Google Sheet, with one of the params like "message" having multiline text, the formatting is maintained.
But if i use bulk insert/update, all the multiline characters ie "\n", looses the slash, and hence the formatting gets broken

### Steps To Reproduce

1. Connect Google sheets to Appsmith app
2. Try adding a single record which has a field with multi-line text, observe that the newline character "\n" is not broken and formatting is maintained.
3. Now try using bulk insert/update with records that have some multi-line text, and you shall see the newline character and formatting is broken

### Public Sample App

https://app.appsmith.com/app/googlesheets-bulk-insert-update-issue/page1-62bca65cee7723383d6513da

### Version

Cloud

### PR DESCRIPTION
**Pull request by sneha122**
## Description

When I am adding/updating a single record into Google Sheet, with one of the params like "message" having multiline text, the formatting is maintained.
But if i use bulk insert/update, all the multiline characters ie "\n", looses the slash, and hence the formatting gets broken

I still need to add Junit test for this, created a task for that https://github.com/appsmithorg/appsmith/issues/18553

> Add a TL;DR when description is extra long (helps content team)

Fixes #14915 
> if no issue exists, please create an issue and ask the maintainers about this first

Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Comment by sneha122** [comment]
@sumitsum Created the task https://github.com/appsmithorg/appsmith/issues/18553

**Review by sumitsum — DISMISSED** [review]

**Review by sumitsum — APPROVED** [review]

**Pull request merged**
