### PR TITLE
fix: fixed git config route protection using fetchGlobalGitConfigInit…

### LINKED ISSUE #34603: [Bug]: Git user config page can be accessed without user signed in
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we go to app.appsmith.com/profile, the pages can be accessed without the user logging in. 
Ideally it should be redirected to login page. 

### Steps To Reproduce

1. Open incognito window
2. Open app.appsmith.com/profile
3. Go to Git user config
4. After sometime it redirects to login page. 
5. Go back using browser control and it shows up the form for Git user config. In a throttled environment, page is accessible.

### Public Sample App

_No response_

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Issue video log

_No response_

### Version

Cloud - 1.29

### PR DESCRIPTION
**Pull request by Shivam-z**
## Description:
In this PR I have fixed the GitConfig route `dev.appsmtih.com/profile` with the help of `fetchGlobalGitConfigInit` method.
Now  If an unauthorized user try to access this URL , it will redirects to the login page.

## Issue video
[Screencast from 11-07-24 02:37:08 PM IST.webm](https://github.com/appsmithorg/appsmith/assets/127818049/1c851c90-c0d0-47d7-8b1e-8c5df74b6f28)

## Solution video
[Screencast from 11-07-24 02:36:02 PM IST.webm](https://github.com/appsmithorg/appsmith/assets/127818049/7f7840e7-d00c-4deb-93f0-ad7c3bc74bf5)

> [!TIP]  
> _Add a TL;DR when the description is longer than 500 words or extremely technical (helps the content, marketing, and DevRel team)._
>
> _Please also include relevant motivation and context. List any dependencies that are required for this change. Add links to Notion, Figma or any other documents that might be relevant to the PR._

Fixes #34603  
> [!WARNING]  
> _If no issue exists, please create an issue first, and check with the maintainers if the issue is valid._

## Automation

/ok-to-test tags=""

### :mag: Cypress test results

> [!CAUTION]  
> If you modify the content in this section, you are likely to disrupt the CI result for your PR.

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [x] No

## Summary by CodeRabbit

- **New Features**
  - Added automatic fetching of global Git configuration when visiting the UserProfile page.
  
- **Refactor**
  - Simplified imports and component logic in the UserProfile and GitConfig components for better maintainability.

- **Bug Fixes**
  - Improved initialization behavior of the GitConfig component by removing redundant fetch operations.

- **Tests**
  - Introduced unit tests for the UserProfile component to verify rendering behavior based on user authentication states.

### CODE REVIEW

**Comment by Shivam-z** [comment]
Hi @brayn003 , 
Thanks for your feedaback. In this commit I have fix the reundant API calls by removing fetchGlobalGitConfigInit logic from `UserProfile/General.tsx` and `UserProfile/GitConfig.tsx` and putting it in Parent component.

**Comment by brayn003** [comment]
Hi @Shivam-z, apologies for the late response. The logical changes look good to me. 
Appreciate if you could add some unit test cases for this. Once done, I can start running the CI suite and proceed with the ci/merging process

**Comment by Shivam-z** [comment]
@brayn003 added unit test case

**Comment by brayn003** [comment]
Let me trigger the tests

**Comment by brayn003** [comment]
Tests running at https://github.com/appsmithorg/appsmith-ee/pull/4758

**Comment by brayn003** [comment]
All the CI tests are passing. Will merge this PR shortly

**Review by brayn003 — APPROVED** [review]

**Pull request merged**
