### PR TITLE
Allow removing filter on Dropdown Widget

### LINKED ISSUE #3321: [Enhancement] [Dropdown Widget] Allow removing search input for filtering options
## Summary
Allow removing search input for filtering options

### PR DESCRIPTION
**Pull request by aswathkk**
## Description

Adds option to remove search input for filtering Dropdown options.

Fixes #3321 

## Type of change

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

## How Has This Been Tested?

All the existing test cases were passing.
I tested the feature manually, and it is working fine.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by aswathkk** [comment]
@Nikhil-Nandagopal

**Review by Nikhil-Nandagopal — APPROVED** [review]

**Review by somangshu — APPROVED** [review]

**Comment by SatishGandham** [comment]
Looks good to me.

**Review by SatishGandham — APPROVED** [review]

**Comment by somangshu** [comment]
Tested on deploy preview

**Review by somangshu — APPROVED** [review]

**Pull request merged**
