### PR TITLE
feat: statbox widget

### LINKED ISSUE #6118: [Feature] Stat box widgets
# Objective
Introduce a stat box widget to show numbers at a glance. This is new widget, which is made with the help of old widgets (composite widget)

Screen Shot 2021-07-25 at 2 40 36 AM

# Requirements

| Title | Description | Comment |
| ----- | ----- | ------ | 
| Container | Parent element is the container, Default to 14 rows and 12 columns | - |
| Text | headerText (para 2, #999999), bodyText (Heading 1, Bold, Black), captionText (para2, Theme success color) will be placed one below the other in the extreme left column | - | 
| IconButton / FAB | Default to solid, Success, Up arrow | The icon button will have a change here, When onClick action is not present the hover state and Click pointer should not occur |

> Preview
Screenshot 2021-08-04 at 5 58 54 PM

### PR DESCRIPTION
**Pull request by techbhavin**
## Description

>  Create StatBox Widget

Fixes #6118 

> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

- New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: feature/statbox-widget 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 55.01 **(0.01)** | 36.86 **(-0.01)** | 33.9 **(0.01)** | 55.56 **(0.01)**
 :red_circle: | app/client/src/components/designSystems/appsmith/IconButtonComponent.tsx | 48.78 **(-1.22)** | 7.84 **(-0.16)** | 22.22 **(0)** | 60.61 **(0)**
 :green_circle: | app/client/src/icons/WidgetIcons.tsx | 95.31 **(0.15)** | 100 **(0)** | 90.32 **(0.32)** | 95.31 **(0.15)**
 :red_circle: | app/client/src/utils/WidgetRegistry.tsx | 79.82 **(-0.36)** | 100 **(0)** | 39.47 **(-1.07)** | 79.82 **(-0.36)**
 :sparkles: :new: | **app/client/src/widgets/StatboxWidget.tsx** | **68.42** | **0** | **40** | **66.67**</details>

### CODE REVIEW

**Comment by techbhavin** [comment]
the document is updated under pr [appsmith-doc-185](https://github.com/appsmithorg/appsmith-docs/pull/185)
cc: @somangshu

**Review by jsartisan — DISMISSED** [review]

**Comment by jsartisan** [comment]
@techbhavin The PR looks good to me. Just a few things.

1. There are few merge conflicts. 
2. the icon for the stats widget in the sidebar is wrong. I think something went wrong while exporting it. Let me pass the correct icon to you.

**Comment by jsartisan** [comment]
@somangshu We will be taking care of typography sizes in text widget in a separate PR right? the current heading h1 is small.

**Comment by jsartisan** [comment]
@techbhavin Updated the icon and default config a little bit.

**Comment by somangshu** [comment]
@techbhavin please fix the merge conflicts soon

**Review by somangshu — APPROVED** [review]

**Review by jsartisan — APPROVED** [review]

**Comment by YogeshJayaseelan** [comment]
@techbhavin Tested this feature and please find the status below,

**Issues:**
1. When few more text widget is copied and pasted user is not able to scroll within stat box widget 
https://loom.com/share/f3d71fb008f542f4ac81a2e25df7ba97

2. Unable to reposition 3 of the text widgets and icon widgets inside stat box widget 
https://loom.com/share/cd2db603b8ff46229aae9e38bbb3a948

3. Unable to place any other widgets inside stat box widget 
https://loom.com/share/212de6304e1249058bbb7658890baefe

4. For icon - if no action is set OnClick then on mouse hovering on icon - The selection and mouse pointer are displayed
https://loom.com/share/d86a22adca3e405f9e9217b91538ee3f

**Review by somangshu — APPROVED** [review]
Approving for tests to run

**Comment by YogeshJayaseelan** [comment]
@techbhavin Tested the fix and please find the status below,

Issues fixed:
3,4

Issues re-opened:
1,4 - still exists

**Comment by jsartisan** [comment]
@techbhavin for the 1st, you will need the add this in the property config of stats widgets

```js
{
            propertyName: "shouldScrollContents",
            label: "Scroll Contents",
            controlType: "SWITCH",
            isBindProperty: false,
            isTriggerProperty: false,
          }
```

**Comment by jsartisan** [comment]
For the 4th point, don't change the background color of the icon on the hover if there is no click event handler. This change will be needed for the icon button widget.

**Comment by YogeshJayaseelan** [comment]
> For the 4th point, don't change the background color of the icon on the hover if there is no click event handler. This change will be needed for the icon button widget.

@somangshu @jsartisan - Now the background color of icon on hover is not happening when onClick is not performed. But still the mouse pointer is displayed on hover when onClick is not performed. Need you confirmation here

**Comment by somangshu** [comment]
> @somangshu @jsartisan - Now the background color of icon on hover is not happening when onClick is not performed. But still the mouse pointer is displayed on hover when onClick is not performed. Need your confirmation here

IMO the pointer is a default, And should be fine.

**Review by jsartisan — APPROVED** [review]

**Comment by jsartisan** [comment]
LGTM!  
There is one small merge conflict though.

**Review by somangshu — DISMISSED** [review]

**Comment by YogeshJayaseelan** [comment]
@techbhavin The deploy preview is failed and can you fix this and re-deploy

**Review by somangshu — APPROVED** [review]

**Comment by YogeshJayaseelan** [comment]
@techbhavin Verified the fixes for point 1,2,3,4 and they are working as expected

New issue:
5. The options in stat box property pane should follow the same order as container widget property pane 

Container widget property pane as the following order 

- General 
      -Background colour 
      -Visible JS
      -Scroll Contents 

Stat Box widget property pane as the following order 

 - General 
      - Scroll Contents 
      -Background colour 
      -Visible JS

**Comment by YogeshJayaseelan** [comment]
@techbhavin Verified the fix and it is working as expected and we can proceed further

**Review by jsartisan — DISMISSED** [review]

**Review by somangshu — DISMISSED** [review]

**Comment by somangshu** [comment]
@techbhavin there is a build error here, Please fix

**Review by somangshu — APPROVED** [review]
🆗

**Pull request merged**
