### PR TITLE
fix: show callback button in action selector cards for chainable actions by default

### LINKED ISSUE #22223: [Feature]: Unfurl callback to show success and failure actions with specific count
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

As a new user/user trying to configure a new action, the UI response in the revamped design is accurate.

But as an advanced user who has already configured actions on the property pane and wants to modify child action instead of parent, seeing only `callbacks` with total action count (again) on the first click of a parent action does not convey enough information. The user needs to click again to see success/failure blocks - which then opens up the entire success & failure blocks instead of incrementally increasing the information provided to the user.

**Current interaction:**
Initial view:
image

First click:
image

Second click:
image

### Why should this be worked on?

User flow should instead be augmented to:
1. First click on parent action: unfurl callback showing onSuccess/onFailure titles with total count under each action and make the title elements clickable
2. Second click on either success or failure child action: unfurl only the section selected by the user

### LINKED ISSUE #23857: [Enhancement]: Show the Callbacks header on action by default
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I view an action that contains no callbacks, I don't see an option to add new callbacks unless I click on the action. This is confusing for some users and poses a discovery risk for callbacks. 

**On widget click:**
Screenshot 2023-05-30 at 12 50 38 PM

**On action click:**
Screenshot 2023-05-30 at 12 54 02 PM

### Steps To Reproduce

1. Add an API action on button click
2. Exit action confugration
3. Click on the Button to view properties
4. Notice that the action does not show any options for configuring callbacks unless the action is explicltiy clicked on 

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by arunvjn**
## Description
show callback button in action selector cards for chain-able actions by default
- Removed touched state from ActionCard that tracks interaction on card.
- Added unit test to assert callback button render

#### Media
Screenshot 2023-06-06 at 13 13 27

#### Type of change
- Bug fix (non-breaking change which fixes an issue)
>
>
#### How Has This Been Tested?
- [x] Manual
- [x] Jest
- [ ] Cypress
>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by Rishabh-Rathod — APPROVED** [review]
LGTM

A minor nit for mocking redux store.

**Comment by tanvibhakta** [comment]
ADS review not needed

**Comment by arunvjn** [comment]
This PR is not related to #22223.  It contains changes only to show callback buttons by default to improve discoverability

**Comment by shwetha-ramesh** [comment]
@arunvjn QA Done.
This [DP](https://appsmith-2f0db6bmn-get-appsmith.vercel.app)https://appsmith-2f0db6bmn-get-appsmith.vercel.app/) by default i.e on click on the property pane only shows callback bar with total action count linked to it.

image

**Review by Aishwarya-U-R — COMMENTED** [review]
Cypress changes are ok!

**Review by Rishabh-Rathod — APPROVED** [review]

**Pull request merged**
