### PR TITLE
fix: redirect anonymous users to login page if they visit non public app

### LINKED ISSUE #9083: [Bug]: If Non public apps URL are opened then the user is not navigated to Login page and a error is displayed
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the apps are not public if we copy-paste the URL The error message is displayed 
image

### Steps To Reproduce

1. Copy the Application Url 
2. go to the incognito window or normal window any other browser
3. paste the application URL
4. The user is not navigated to the Login page and also appsmith server not available error is displayed

### Environment

Release

### Version

Cloud

### PR DESCRIPTION
**Pull request by pranavkanade**
## Description
Null check was missing,

Fixes #9083 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Cypress test

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/on-404-redirect-appviewer-to-login 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 54.59 **(0.01)** | 36.44 **(0)** | 33.22 **(0)** | 55.11 **(0)**
 :red_circle: | app/client/src/sagas/ApplicationSagas.tsx | 14.88 **(0)** | 1.15 **(-0.05)** | 4 **(0)** | 17.73 **(0)**
 :green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.26 **(0.22)** | 41.25 **(0.83)** | 34.48 **(0)** | 56.22 **(0.26)**</details>

### CODE REVIEW

**Review by arunvjn — APPROVED** [review]

**Comment by hetunandu** [comment]
@arunvjn does this mean that these apps will default to the old version of evaluation?

**Comment by arunvjn** [comment]
@hetunandu evaluationVersion will be set to whatever comes from the backend. When there is no such attribute( for old apps), we use the default value of 1. 

In case of anonymous user, fetchApplication call returns nothing and the lack of null check broke the code before it could hit the redirection logic. Correct me if I am wrong. @pranavkanade

**Comment by hetunandu** [comment]
@arunvjn @pranavkanade @trishaanand in that scenario, even for new apps built with the new version will get served as an old version to anonymous users. This can break public apps

**Comment by trishaanand** [comment]
@arunvjn : You should get the evaluationVersion even as anonymous user. Could we debug why this value was not delivered? That could be a bug.

**Pull request merged**
