### PR TITLE
chore: update app typography

### LINKED ISSUE #21426: Improve default app typography settings
1. Make `system default` our option for the default theme (`Modern`)
2. Put `Modern` at the top of the theme list
3. ~Rename `Modern` to `Default`~

All existing applications should continue to use whatever is in their theme (e.g. `Nunito`), all new applications should be built on `system default`.

### PR DESCRIPTION
**Pull request by jsartisan**
Fixes #21426

### CODE REVIEW

**Review by ichik — APPROVED** [review]

**Review by jsartisan — COMMENTED** [review]
try deprecated field

**Review by ichik — APPROVED** [review]

**Comment by jsartisan** [comment]
@nayan-rafiq Adding you as a reviewer as this PR involves backend changes. Let me know if I missed something.

**Review by nayan-rafiq — APPROVED** [review]
Backend changes looks good to me

**Review by KelvinOm — APPROVED** [review]

**Review by ichik — APPROVED** [review]

**Comment by laveena-en** [comment]
Tested and verified, changes look good to me!

**Pull request merged**
