### PR TITLE
fix: Hide logo upload behind a feature flag

### LINKED ISSUE #23493: [Task]: Hide logo upload behind a feature flag
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

With respect to some internal team conversations, we decided to hide the logo upload for app navigation behind a feature flag. If you're a team member, [follow this link to a Slack thread for details](https://theappsmith.slack.com/archives/C02JV8G1MP0/p1684387079809719).

### PR DESCRIPTION
**Pull request by dhruvikn**
## Description
With respect to some internal team conversations, we decided to hide the logo upload for app navigation behind a feature flag. If you're a team member, [follow this link to a Slack thread for details](https://theappsmith.slack.com/archives/C02JV8G1MP0/p1684387079809719).

This PR makes the feature available to users with appsmith.com and moolya.com emails.

#### PR fixes following issue(s)
Fixes #23493

#### Type of change
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

- [x] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [x] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [x] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by jsartisan — APPROVED** [review]

**Comment by chandannkumar** [comment]
Tested this PR and LGTM
- Tested with officials id of appsmith & moolya
- Tested with other email domains
- Tested functionality of not showing Logo upload feature to all
- Tested functionality of hiding Logo upload feature when existing logo is removed

**Pull request merged**
