### PR TITLE
fix: auto height regression fixes

### LINKED ISSUE #18393: [Bug]: The scroll is not working properly when container is set to Fixed height
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When container widget is set to Fixed height and widgets inside is set to Auto height, while the one widget gets taller the other widgets inside container are vanished from container instead of showing via scroll 

P.S: This is happening for all container type widgets like form, statbox & modal

### Steps To Reproduce

1. Drag & Drop container widget
2. Drag & Drop Text and JsonForm widget inside container
3. Make sure to add Text widget above of JSONForm widget
4. Make sure to set Height as 'Auto Height' for Text widget
5. Start typing input in Text widget until Text widget gets taller than container
6. Observe that JSONForm widget gets vanished from container entirely

### Public Sample App

_No response_

### Issue video log

https://www.loom.com/share/acf184349bc0431fa909a09ef847f6f9

### Version

Cloud / Release

### LINKED ISSUE #18399: [Bug]: Overlap issue with invisible widgets in specific case when switching between preview and edit mode
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Overlap issue with invisible widgets in specific case when switching between preview and edit mode

### Steps To Reproduce

1. dnd a form 
2. dnd another form but put it over the first one and do some reflow
3. make the form at first postion invisible
4. Switch between preview and edit mode

https://www.loom.com/share/601ccd69a54e4463abef64cfdaa0c944

### Public Sample App

_No response_

### Issue video log

_No response_

### Version

release

### LINKED ISSUE #18406: [Task] Remove Auto Height With Limits from Modal Widget
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- For a modal widget, there is a possibility of losing track of handles, as this doesn't exist in the context of the canvas and has a different stacking context.
- We need to remove the auto height with limits option for the Modal widget, so that users don't go into an irrecoverable state
- This fix may be reverted based on a better DX for handling limits for Modal widget

### LINKED ISSUE #18413: [Bug]: On increasing Border width of JSONForm, the below added widget flickers continuously
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On increasing the Border Width of JSONForm when height is set as 'Auto Height', the below added widgets flicker.
In edit mode entire screen flickers

### Steps To Reproduce

1. Drag & Drop JSONForm widget
2. Drag & Drop Text widget below JSONForm
3. Make sure to set Height of JSONForm as 'Auto Height'
4. Increase the Border Width of JSONForm widget: eg: 20
5. Observe the screen flicker in both Edit and View mode

### Public Sample App

_No response_

### Issue video log

https://bthrujcsw8.vmaker.com/record/pdsy3lvXEzVFSyuj

### Version

Cloud / Release

### LINKED ISSUE #18414: [Bug]: Background color is not applied as per set Border Radius in JSONForm when Auto Height with limit is set
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Background color in JSONForm must be calculated as per Border Radius set for all Height type

### Steps To Reproduce

1. Drag & Drop JSONForm widget
2. Set the Height property to 'Auto Height with limit'
3. Add any background color
4. Observe that Background color is applied irrespective of set Border Radius

### Public Sample App

_No response_

### Issue video log

https://bthrujcsw8.vmaker.com/record/on3UNocnbgTsZ6pF

### Version

Cloud / Release

### PR DESCRIPTION
**Pull request by ankurrsinghal**
## Description
- [ ] Default enabled Auto Height for all the widgets except JSON Form widget.
- [ ] Made changes as per @marks0351 review changes in the final auto height PR. (https://github.com/appsmithorg/appsmith/pull/18341)
- [ ] Disables auto height with limits in modal widget. Fixes #18406 
- [ ] Disables auto height on Container inside List Widget
- [ ] Fixes issue where fixed container doesn't scroll when content exceeds the scrollview
- [ ] Fixes issue where containers don't always collapse, no consistency
- [ ] Fixes issue where redo doesn't cause auto height computations
- [ ] Fixes issue where MainContainer has unnecessary scroll
- [ ] Fixes issue where Tabs Widget has unnecessary scroll
- [ ] Fixes issue where Tab switching in view mode did not adjust auto height
- [ ] Fixes List Widget pagination breaks
- [ ] Fixes Form Widget Flicker issues

Fixes #18414 
Fixes #18413 
Fixes #18399 
Fixes #18393 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manual
- Cypress Test pending

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [NA] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [PENDING] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [NA] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Comment by dilippitchika** [comment]
@ankurrsinghal what is the change here, i see the radio group functionality has changed fully - https://www.loom.com/share/a19fc7f104ff4658a09e7f7d8be6afe5

**Comment by ankurrsinghal** [comment]
> @ankurrsinghal what is the change here, i see the radio group functionality of inline has changed fully - https://www.loom.com/share/a19fc7f104ff4658a09e7f7d8be6afe5

@dilippitchika reverted the changes.

**Review by marks0351 — APPROVED** [review]

**Review by riodeuno — APPROVED** [review]

**Pull request merged**
