### PR TITLE
Fix Table Widget Filter issue

### LINKED ISSUE #3964: [Bug]Filtering ID and Order Amount = Empty is not working as expected
## Description
In table widget it is observed that by filtering ID = Empty and Order Amount = Empty the filter is not working as expected.

Expected Result:
If the ID and Order Amount has values and by filtering ID = Empty and Order Amount = Empty then the result should not be displayed in the table grid 

Actual Result:
It is observed that by filtering ID = Empty and Order Amount = Empty, the table grid displays results which has values in ID and Order Amount columns

### Steps to reproduce the behaviour:
1. Launch Appmsith in Release Environment 
2. Drag and Drop table widget 
3. Click on the Filter icon and Choose ID from the Attribute drop down 
4. Choose Empty from the Condition dropdown and observe 

**Video Link:**
https://www.loom.com/share/298e81f98266434d9702cb861f1f8ae5

### Important Details
 - Version: 14.0.3 (16610.4.3.1.7)
 - OS: [macOS Big Sur 11.2.3]
 - Browser [safari]

### LINKED ISSUE #4320: [Bug] Sorting table column with numbers is not working properly
## If any column have numbers then the sorting is not working properly

What happened -- Looks like it is sorting the numbers as string

### Steps to reproduce the behaviour:
1. Go to page and add table widget
2. Create a column with numerical values in it (eg, 10, 12, 21, 103 etc)
3. Click in sort icon for that column
4. Observe that sorting do not populate the correct result

Screenshot 2021-05-05 at 10 50 30 AM

### PR DESCRIPTION
**Pull request by riodeuno**
## Description
Fixes issue where non-string values like numbers were getting tagged as "empty" when filtering.
This resulted in the issue where filtering columns with numerical values by using the "empty" comparison, cleared the table.

Fixes #3964 Fixes #4320

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Unit Test

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by hetunandu — APPROVED** [review]

**Comment by somangshu** [comment]
Tests are failing here! Cannot see the cypress logs

**Comment by somangshu** [comment]
@riodeuno we probably need to merge the release here, The branch is too old

**Review by somangshu — APPROVED** [review]
Approving to run tests

**Pull request merged**
