### PR TITLE
fix: JSON form splits keys to multiple lines when it should not #32230

### LINKED ISSUE #32230: [Bug]: JSON form splits keys to multiple lines when it should not
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When having a JSON from with some keys, it splits it to to lines for no reason.  i.e. "For Sale" is split to two lines even though it is wide enough to fit "Manufacture".  There appears to be no way to control this.

Appsmith support requested I open this bug in Discord.

### Steps To Reproduce

1. Create a new test app
2. Add a JSON form widget
3. set the source data to `{{{Manufacture: false, "For Sale": true}}}`
4. Notice that for sales is split into two lines

### Public Sample App

_No response_

### Environment

Production

### Severity

Low (Inconsistent UI/UX)

### Issue video log

_No response_

### Version

Self Hosted - 1.13

### PR DESCRIPTION
**Pull request by akshat8605**
Fixes #32230

> [!WARNING]  
> _If no issue exists, please create an issue first, and check with the maintainers if the issue is valid._

## Automation

/ok-to-test tags="@tag.JSONForm"

### :mag: Cypress test results

> [!CAUTION]  
> If you modify the content in this section, you are likely to disrupt the CI result for your PR.

## Summary by CodeRabbit

- **Style**
	- Updated the JSON Form Widget to prevent text wrapping in field labels, ensuring labels are displayed in a single line.

### CODE REVIEW

**Comment by ashit-rath** [comment]
@akshat8605 Can you pull and merge the latest appsmith `release` branch to your branch? Since your changes are on top of last week's code and not the latest; there seems to be some sort of discrepancy in the [deploy preview](https://github.com/appsmithorg/appsmith/pull/32313#issuecomment-2044156103) that was generated.

I see that you have another [PR](https://github.com/appsmithorg/appsmith/pull/32497). Please go ahead and sync up that as well just to be on the safe side.

Let me know if you need any help.

**Comment by akshat8605** [comment]
Hi @ashit-rath, I just wanted to confirm that I made this pull request last week, and the other request was made yesterday after the latest pull from the release. So, do I need to make both requests again, or is just this one fine?

**Comment by akshat8605** [comment]
Hi @ashit-rath,

Sure, I am committing again with the latest release code.

Regarding the other PR, it was a mistake. I actually created a new branch and a new [pull request](https://github.com/appsmithorg/appsmith/pull/32497/commits) for that. However, I will fix that as well.

Thank you for your assistance!

**Pull request closed without merging**
