### PR TITLE
chore: Anvil cypress tests

### PR DESCRIPTION
**Pull request by marks0351**
> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.
>
## Description
In this pr we are writing tests to validate a few preliminary cases of the Anvil Editor.
the purpose of the task is to be able to run anvil tests along side the present suite of test cases.
Things to note for Anvil based test cases
- ANVIL_EDITOR_TEST tag is used for Anvil based tests to make sure relevant feature flags are set(using featureFlagIntercept) before creating pages so that Anvil pages are created.
- each test case in a Anvil spec file also use featureFlagIntercept to set the relevant flags since pages are reloded before running tests.
#### PR fixes following issue(s)
Fixes # (issue number)
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
- [ ] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

## Summary by CodeRabbit

- **New Features**
	- Enhanced Anvil editor with the ability to test app navigation, drag and drop functionality, and suggested widgets feature.
	- Improved accessibility and interaction capabilities within the Anvil canvas.
- **Tests**
	- Added comprehensive end-to-end tests for new Anvil editor features, including app navigation settings, widget drag and drop, and suggested widgets integration.
- **Refactor**
	- Introduced new constants and locators for better test structure and readability.
- **Style**
	- Updated components with new attributes for improved accessibility and testing.
- **Chores**
	- Added new tags for organizing tests related to the Anvil editor.

### CODE REVIEW

**Review by Aishwarya-U-R — COMMENTED** [review]
@marks0351 Cypress looks good, lets make sure to run the CI couple of times to make sure none of the new tests are flaky & then merge them 👍

**Comment by marks0351** [comment]
@Aishwarya-U-R rts-build runs are erratic, i keep rerunning for it to pass, is this something of concern?
test cases seem to be passing all the rime.

**Comment by Aishwarya-U-R** [comment]
> @Aishwarya-U-R rts-build runs are erratic, i keep rerunning for it to pass, is this something of concern? test cases seem to be passing all the rime.

I think it could be because of the runner issue we are seeing randomly in runs. So could be nothing specific to this PR & its changes.

**Comment by Aishwarya-U-R** [comment]
And @marks0351 - are these tests applicable for Airgap also?

**Comment by marks0351** [comment]
> And @marks0351 - are these tests applicable for Airgap also?

nope nothing Airgap specific. these are generic tests for Anvil which is under a feature flag.

**Comment by Aishwarya-U-R** [comment]
Means, they will run in Airgap runs also fine right?

**Comment by marks0351** [comment]
> Means, they will run in Airgap runs also fine right?

yes

**Review by Aishwarya-U-R — APPROVED** [review]
Approving Cypress changes.

**Pull request merged**
