### PR TITLE
fix: checkbox and button border radius

### PR DESCRIPTION
**Pull request by KelvinOm**
## Description
Fix checkbox and button border radius

https://github.com/appsmithorg/appsmith/assets/11555074/8b7cc892-eaa2-4b06-9745-40410cd1d92b

## Summary by CodeRabbit

- **New Features**
  - Updated the default font stack to include 'sans-serif' for better cross-platform consistency.

- **Style**
  - Adjusted button padding for improved visual alignment and spacing.
  - Enhanced checkbox design with responsive border-radius for a more modern look.

- **Documentation**
  - Updated theme settings to reflect the new "Pill" option value for border-radius, ensuring design consistency across components.

### CODE REVIEW

**Review by ichik — DISMISSED** [review]

**Review by ichik — DISMISSED** [review]

**Comment by ichik** [comment]
@KelvinOm we probably want to apply this fix also to text input, select etc.

**Comment by KelvinOm** [comment]
> @KelvinOm we probably want to apply this fix also to text input, select etc.

@ichik Now pill inputs looks like this. It seems that something needs to be done about textarea.

Снимок экрана 2023-12-09 в 13 53 09
Снимок экрана 2023-12-09 в 13 54 56

**Pull request merged**
