### PR TITLE
fix: Cursor turning to pointer upon onclick in deployed app

### LINKED ISSUE #7571: [Bug] Cursor not auto turning into hand pointer when onClick is true for Images
## Description

When I set the configuration of onClick to true for an Image, the cursor still remains the same, it is not turning into a hand pointer by default. 

### Steps to reproduce the behaviour:

1. Go to 'Entity page' and Click on '+' icon beside the widgets label
2. Click on 'Image' and Drag the widget into UI Building space
3. Click on 'Settings' and set an action for 'onClick' 
4. Now deploy and try hovering/clicking on the image, it still stays as a cursor

### Important Details

- Version: Cloud
- OS: Windows
- Browser: Chrome
- Environment: Production

### PR DESCRIPTION
**Pull request by nishihere19**
Signed-off-by: Nishi Agrawal <nishihere19@gmail.com>

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Description

> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change.

When the app is deployed with Image widget, even if the widget has onClick action associated with it, the cursor was set to default. This was happening due to the inherit property in CSS which I changed to pointer based on the onClick event associated. 

Fixes #7571

> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

NA

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

The result is when the onClick action is associated with the image widget, only then the cursor changes to pointer.
CursorDefault

CursorPointer

### CODE REVIEW

**Comment by areyabhishek** [comment]
@nishihere19 Thanks for the contribution! There needs to be a change here. The cursor needs to change to a pointer only if there is an on-click event for the image. The current implementation introduces a pointer for every image widget even if they don't have an on-click event. Could you modify your PR? 

I've shot a video to show you what I mean: https://www.loom.com/share/e5723f23663d4d2fa179b85c78abef0b  Please let me know if you need help! Thanks

**Comment by nishihere19** [comment]
Sure, thanks for the suggestions. Will apply the same!

**Comment by somangshu** [comment]
@nishihere19 please update the pull request description properly

**Comment by jsartisan** [comment]
@nishihere19 I can still see the cursor point in the view mode ( i had no on-click action on the image ). can you check it once in the view mode ( by view mode, i mean the app you see when you deploy your app )

**Comment by nishihere19** [comment]
Yeah, I am working on it. Will fix this.

**Comment by somangshu** [comment]
@nishihere19 as requested, Re-opening this PR, Kindly make the required changes in the next 2 days and update the PR with the latest release code from upstream

**Comment by nishihere19** [comment]
Sure, thank you!!

**Comment by somangshu** [comment]
@jsartisan @yatinappsmith need some help with the failing tests here

**Pull request merged**
