### PR TITLE
fix: Allowing multi form to json switching and eliminating json to form sw…

### LINKED ISSUE #15029: [Enhancement]: UQI query screen JS Toggle behavior should be consistent with the canvas area property pane
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In the Query pane of the Google Sheets UQI datasource, wherever the JS Toggle is present, the behavior should be consistent with the current JS toggle behavior on canvas property pane.

### Steps To Reproduce

The JS Toggle functionality has been modified on canvas recently as per this feature request - 
[Feature]-[9884]:Disable JS button if the field is not empty or if the default text is modified#10833

This feature should be consistent across the application. Google Sheets screens where-ever JS toggle appears, the same behavior should be seen.

Reference screen - 
GSheets_JSToggle

### Public Sample App

_No response_

### Version

Release

### LINKED ISSUE #16967: [Bug]: Gsheets where clause: take form configuration into JS mode
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

https://user-images.githubusercontent.com/94514895/191651771-de046182-8c23-44e5-8651-253e783cd971.mov

in ghseets query, when I add some where clause in the form mode. I switch to the JS mode, and it would be good to see the form mode configurations in the JS mode. 

### Why should this be worked on?

1. makes it easier for the user to make their entries
2. serves as an instructional guide to the user to make edits more confidently

### PR DESCRIPTION
**Pull request by Irongade**
This PR fixes the following issues:

- Makes the operation of the JS Toggles in the Query editor pages to be consistent with the ones in the property pane.
- Disables one way form to json switching. This allows users to convert from a form to json as many times as they want to.

Fixes #15029 
Fixes #16967 

- Bug fix (non-breaking change which fixes an issue)

- Manual Test

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by AmanAgarwal041 — APPROVED** [review]

**Review by AmanAgarwal041 — APPROVED** [review]

**Comment by prapullac** [comment]
Hi @Irongade @rohan-arthur 
1) We have deviated from the original functionality of JS component ie. User is unable to toggle back to Dropdown option upon entiring the correct value.
Expectation : @btsgh 
1) The data entered/ selected from the dropdown must be retained in JS mode and vice versa 
2) JS toggle must be disabled upon entering wrong value/ sheetname however the JS toggle must be kept open to switch back when the entry of data is correct 
Note : This is a set expectation of JS toggle in the canvas.

**Comment by Irongade** [comment]
> #15029

This was intended. Kindly follow this thread. https://theappsmith.slack.com/archives/CNQ9Q91C0/p1664795369902699 for more information on why this was done.

**Comment by prapullac** [comment]
Closing the issue based on the above conversation

**Pull request merged**
