### PR TITLE
Feat/meta rehydration (MANUAL TESTING)

### LINKED ISSUE #16926: [Feature]: Option to modify the order of preference for hydration of meta properties
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Summary

When a widget is mounted for the first time, the meta properties of the widgets are hydrated using the default values of the widget.

This feature aims to modify this default behaviour of looking only into the default values. Instead the widget can provide an order of preference to the evaluation to first look into the existing meta value (if present) and then the default values for hydration.

### Why should this be worked on?

The List widget v2 creates widgets on the fly while navigating to different pages. When a page is modified the previous page widgets are replaced with the new page widgets on the `unevalTree` but the meta properties of the removed widgets are still persisted. 
When the user navigates back to the previous page, the widgets are expected to be in the same state as they were before and the state primarily depends on the meta properties. 
In the current implementation of the evaluation, the new widgets for the previous page navigation are hydrated with the default values so the existing meta properties are lost in the process.

### PR DESCRIPTION
**Pull request by ohansFavour**
## Description 
This PR implements the rehydration of meta values when switching between pages of a List widget. In addition, changes to default values cause meta widget values to reset to default.

NB: THIS PR IS FOR MANUAL TESTING ONLY, LIST V2 ISN'T IN RELEASE YET.

Fixes #16926 (Adding this for zenhub to link this PR)

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

- Manual
- Jest
- Cypress

### Test Plan
https://github.com/appsmithorg/appsmith/pull/19681

### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [x] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Comment by ashit-rath** [comment]
Note for QA:
This PR includes couple of changes
1. It retains the interactions with the widgets in each items over page changes. For example if we have an input widget , then if we enter some value in the 2nd or 3rd item and move to the next page and edit some input there. When we come back the to the previous page, the values entered should be present instead of resetting to default.

2. If we do changes mentioned in point 1 and then we modify the default value then all the similar widgets (in our case the input widget) across all the pages should have the default value.

**Comment by kamakshibhat-appsmith** [comment]
Observations:
1. The values in the currency widget is not retaining fully (getting cropped) when we change the page . Not sure if it is a widget problem or related to meta
[LOOM](  https://www.loom.com/share/b3c00efe6b8f48ad84b942bee7073afa)
@ohansFavour @ashit-rath

**Comment by ashit-rath** [comment]
@kamakshibhat-appsmith Is this only with Currency or other input widgets like Phone number behaves the same?

**Comment by kamakshibhat-appsmith** [comment]
@ashit-rath Only currency widget

**Comment by kamakshibhat-appsmith** [comment]
Changed the status of all related PRs to InProgress for now. Pls triage and update it to relevant status accordingly

**Comment by ohansFavour** [comment]
The observation raised by @kamakshibhat-appsmith regarding the currency widget is a "widget" issue rather than a meta-property issue. This behaviour is also replicated in the List widget v2 PR (which doesn't yet have the meta changes).

cc: @ashit-rath

**Comment by ashit-rath** [comment]
@ohansFavour I verified this issue both in this DP and the List v2 and the problem doesn't seem to be there in the List v2 DP.
I have been testing this in both the DPs and I am unable to re-create this in the List v2 one.
Also it seems that the first dataTree after changing page also has the trimmed down value.
Can you double check this?

Hydration DP - https://appsmith-git-feat-meta-rehydration-get-appsmith.vercel.app/app/untitled-application-102/page4-63c007665ce71c57ed4b1ad1/edit#2bijpzaqyc

List v2 DP - https://appsmith-git-feat-list-widget-v2-get-appsmith.vercel.app/app/untitled-application-102/page4-63c007665ce71c57ed4b1ad1/edit#2bijpzaqyc

Let me know if I'm doing something wrong here.
cc: @kamakshibhat-appsmith

**Comment by ohansFavour** [comment]
Hey @ashit-rath , here is a [loom record ](https://www.loom.com/share/f4efb908ec0847b2a9892cbc32c1fb57)of me reproducing this in the listV2 DP

**Comment by ashit-rath** [comment]
@ohansFavour Can you share the app?

**Comment by ohansFavour** [comment]
> @ohansFavour Can you share the app?

I have shared the App with ashit@appsmith.com. Kindly let me know if this is your mail

**Comment by ohansFavour** [comment]
> @ohansFavour Can you share the url of the app?

https://appsmith-git-feat-list-widget-v2-get-appsmith.vercel.app/app/untitled-application-12/page1-63a0258b3acfb26450eccde1/edit#0a20lu51cx

**Comment by ashit-rath** [comment]
@ohansFavour Thanks!
@kamakshibhat-appsmith This is indeed a Currency widget issue and not a hydration bug. Please proceed with the verification excluding the Currency widget; we'll fix it separately.

**Comment by kamakshibhat-appsmith** [comment]
Rest of the things look good . @ohansFavour @ashit-rath

**Pull request closed without merging**
