### PR TITLE
feat: decouple redux and the view layer in CalloutV2

### PR DESCRIPTION
**Pull request by tanvibhakta**
## Description

Refactor `Group` component so it can pass the appropriate prop to CalloutV2. Fixes https://github.com/appsmithorg/appsmith/issues/16624

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Locally on ee, as well as on the DP

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by albinAppsmith — APPROVED** [review]

**Comment by shadabbuchh** [comment]
Errors while compiling this PR. Reopening this issue

**Comment by shadabbuchh** [comment]
This PR has been tested. No issues found.

**Review by albinAppsmith — APPROVED** [review]

**Pull request merged**
