### PR TITLE
fix: Objects that start with an underscore `_JSObject1` fail to be navigated from the debugger

### LINKED ISSUE #19115: [Bug]: Objects that start with an underscore `_JSObject1` fail to be navigated from the debugger
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Objects that start with an underscore `_JSObject1` fail to be navigated from the debugger. Click-through navigation works in other ways like Ctrl+ Click.

URL when navigating from the debugger changes from 
`/app/untitled-application-1/page1-637b854d3d59b3216e329ead/edit/jsObjects/63a338edbc0e8334c729741f?branch=master` to `/app/untitled-application-1/page1-637b854d3d59b3216e329ead/edit/jsObjects/_JSObject2.body?branch=master`

This works fine for queries.

### Steps To Reproduce

1. Create a JS object with an underscore at the start of it's name like `_JSObject2`
2. Create an errored code so it appears on the debugger as seen in the screenshot below
3. Now click on the object name on the debugger trying to navigate to the object and observe the error displayed stating it's an invalid page (seen in the screenshot attached)

image
image

### Public Sample App

_No response_

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by Druthi**
## Description
fix: Objects that start with an underscore `_JSObject1` fail to be navigated from the debugger

Fixes #19115

Media
image

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Cypress

### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by ApekshaBhosale — DISMISSED** [review]

**Comment by ramsaptami** [comment]
Gtg to release
CC: @Druthi

**Review by ApekshaBhosale — APPROVED** [review]

**Pull request merged**
