### PR TITLE
fix: Icon Widget button variant does not have JS option

### LINKED ISSUE #8382: [Bug]: Icon Widget button variant does not have JS option
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Icon Widget button variant does not have JS option

### Expected Behavior

Icon widget button variant
Screenshot 2021-10-11 at 10 44 53 AM
 should have JS option similar to Button widget, Menu button widget 

### Steps To Reproduce

```markdown
1.Launch Appmsith app in release/Production Environment 
2.Drag and drop Icon Widget 
3.Open property pane and check JS option for button variant
```

### Environment

```markdown
- Version: [11.3]
- OS: [MacOS]
- Browser [chrome, safari]
- Environment [production, release]
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by wmdev0808**
## Description

In Icon Button Widget, button variant does not have JS option

Fixes #8382 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Test A
- Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/8382-icon-button-variant-js-option 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 55.2 **(0)** | 36.98 **(0)** | 34.16 **(0)** | 55.72 **(0.01)**
 :green_circle: | app/client/src/selectors/commentsSelectors.ts | 85.25 **(1.64)** | 64.71 **(2.95)** | 73.33 **(0)** | 90.59 **(2.35)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.71 **(-0.23)** | 40.83 **(-0.84)** | 36.21 **(0)** | 56.74 **(-0.25)**</details>

### CODE REVIEW

**Comment by somangshu** [comment]
@jsartisan please let us know if the code looks good, if this needs QA kindly push to the relevant pipeline. I dont understand why have we been sitting on this for so long

@wmdev0808 kindly expedite such cases

**Comment by YogeshJayaseelan** [comment]
@jsartisan @somangshu Please find the list of area where JS is needed #8909

**Comment by YogeshJayaseelan** [comment]
@wmdev0808 Verified JS option is available for Icon Widget

**Comment by somangshu** [comment]
@wmdev0808 please merge this, Everything is passing

**Pull request merged**
