### PR TITLE
feat: adds `see more` to canvas starter templates

### LINKED ISSUE #29723: Add “See more page layouts” link on canvas
We want to show users more options  for building blocks when they `Start from scratch`.

[Notion card](https://www.notion.so/appsmith/Add-See-more-page-layouts-link-on-canvas-de6b6a83c737474582c045ee0b67bfd4?pvs=4)

### PR DESCRIPTION
**Pull request by rahulbarwal**
## Description
* This PR increases discovery of building blocks, allowing more building blocks to be shown in canvas.
* We also refactored the way `add a page from template` functions: now we have updated store structure to reflect from where the modal open was triggered.
* This pull request refactors the template styling and adds support for an optional modal layout. It also includes various updates and fixes to the styled components used in the templates feature.

#### PR fixes following issue(s)
Fixes #29723
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
#### Type of change

- New feature (non-breaking change which adds functionality)
- [x] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

## Summary by CodeRabbit

- **New Features**
	- Implemented a modal for template selection with the ability to hide it.
	- Added a "See More" text option for template page layouts.
	- Introduced layout switching capability within the templates modal.

- **Enhancements**
	- Updated template list and content components to support modal layout.
	- Added initial filter state management for template filtering.

- **Refactor**
	- Renamed selectors and actions for clarity and consistency.
	- Improved logic for determining template forking and filter component behavior.

- **Bug Fixes**
	- Adjusted styles to correctly apply margins in various layouts.

- **Documentation**
	- Updated messages and constants with more accurate terminology.

### CODE REVIEW

**Review by rahulbarwal — COMMENTED** [review]
/build-deploy-preview

**Review by AnaghHegde — APPROVED** [review]

**Pull request merged**
