### PR TITLE
fix: remove encoding of branch name with / in it

### LINKED ISSUE #12448: [Bug]: App breaks if user tries to visit a page from feature branch with `/`
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If the feature branch has a name like - `feature/xyz`, the deployed app breaks.

### Steps To Reproduce

1. Create a branch with name - `feat/xyz`
2. visit the deployed version

### Public Sample App

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by arunvjn**
## Description
Branch names that contain special character were not decoded properly in the utility method. 
Changes made to rely on branchName provide by react router in view mode.

Fixes #12448 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manual

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>

    // Code coverage diff between base branch:release and head branch: hotfix/decode-branch-name-request-header 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | app/client/src/sagas/InitSagas.ts | 41.18 **(0)** | 17.74 **(-0.29)** | 50 **(0)** | 45.16 **(0)**</details>

### CODE REVIEW

**Review by albinAppsmith — APPROVED** [review]

**Comment by Parthvi12** [comment]
Tested this on DP, its working as expected.

**Pull request merged**
