### PR TITLE
fix: Removed suggestions from design system tag input

### LINKED ISSUE #18594: [Task]: Remove suggestions from design system tag input
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Remove suggestions functionality from tag input component and keep it in EE since it's being used only in EE.

### PR DESCRIPTION
**Pull request by albinAppsmith**
## Description

As part of RBAC invite modal changes, Team managers had added suggestions functionality to design system tag input component. Since this is not being used anywhere else as of now, we are keeping this inside EE itself and not in design system.

Fixes #18594

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual
- Jest
- Cypress

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by ankitakinger — APPROVED** [review]

**Comment by shadabbuchh** [comment]
Tested this PR. `Tag Input` component is working fine in CE.

**Comment by albinAppsmith** [comment]
This change will go along with this PR - https://github.com/appsmithorg/appsmith/pull/18782

**Pull request closed without merging**
