### PR TITLE
chore: Update JS Object metrics

### PR DESCRIPTION
**Pull request by rishabhrathod01**
## Description

This PR removes the metrics that are overpopulating newRelic for the JS object update flow 

## Automation

/ok-to-test tags="@tag.Sanity"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/11463743078>
> Commit: 94bd14733c275b86873cbf1db1acb23bed016727
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=11463743078&attempt=2" target="_blank">Cypress dashboard</a>.
> Tags: `@tag.Sanity`
> Spec:
> <hr>Wed, 23 Oct 2024 07:48:23 UTC

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [ ] No

### CODE REVIEW

**Review by NilanshBansal — CHANGES_REQUESTED** [review]
@rishabhrathod01 can you please check the reason for the large number of indentation changes in this PR? It is difficult to review the actual changes.

**Comment by rishabhrathod01** [comment]
> @rishabhrathod01 can you please check the reason for the large number of indentation changes in this PR? It is difficult to review the actual changes.

@NilanshBansal  This was pushed after the spotless apply run, not sure why this indentation changes are showing up. There is no spotless config too in the pom.xml. I will revert the changes and check in some time.

**Comment by NilanshBansal** [comment]
> > @rishabhrathod01 can you please check the reason for the large number of indentation changes in this PR? It is difficult to review the actual changes.
> 
> @NilanshBansal This was pushed after the spotless apply run, not sure why this indentation changes are showing up. There is no spotless config change too recently in the pom.xml. I will revert the changes and check in some time.

@rishabhrathod01 no it's fine please don't revert.

**Review by NilanshBansal — APPROVED** [review]
Apart from the indentation changes, rest LGTM! If the indentation changes are only one time, let's proceed.

**Comment by NilanshBansal** [comment]
Closing this PR because changes are introduced in https://github.com/appsmithorg/appsmith/pull/37052

**Pull request closed without merging**
