### PR TITLE
fix: edit button on hover of suggested queries should appear on overall list item.

### LINKED ISSUE #32350: The hover behaviour triggers when hovering the text, not the list item
In the binding menu, when hovering over the text (query), the EDIT tertiary small button is displayed. However:
1. The hover behavior should apply to the list item, not just the text.
2. The button lacks a hover state, which is expected for a tertiary small button.

Video attached for reference.

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0lzQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a833b0f181498ba17f2f80e0e140d0f2622da5ad/edit%20query.mov)

### PR DESCRIPTION
**Pull request by AmanAgarwal041**
## Description
This PR fixes two issues:
- The hover behavior now applies to the overall list item and not just the text.
- The edit button is now using the design-system button which handles the hover effect as well.

Fixes #32350
_or_  
Fixes `Issue URL`
> [!WARNING]  
> _If no issue exists, please create an issue first, and check with the maintainers if the issue is valid._

## Automation

/ok-to-test tags="@tag.PropertyPane"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/8702168462>
> Commit: 79cab6fb3cb3fb116e35ce2ddb53826175b59318
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=8702168462&attempt=1" target="_blank">Click here!</a>

## Summary by CodeRabbit

- **New Features**
  - Enhanced the command editing interface in the Code Editor by replacing text elements with interactive buttons.

- **Style**
  - Updated and streamlined the styling of command suggestions within the Code Editor.

### CODE REVIEW

**Comment by sneha122** [comment]
@AmanAgarwal041 There is one more tag @tag.PropertyPane, can we also run these tests once? I remember there was one cypress that had occurred when we merged edit button changes last time

**Comment by sneha122** [comment]
@AmanAgarwal041 Tested the changes, looks good to me!

**Comment by AmanAgarwal041** [comment]
> @AmanAgarwal041 There is one more tag @tag.PropertyPane, can we also run these tests once? I remember there was one cypress that had occurred when we merged edit button changes last time

Test for JS ran successfully. Updated the test run for PropertyPane

**Pull request merged**
