### PR TITLE
Feature 2111 show hide table controls

### LINKED ISSUE #2111: Show/Hide Table Controls
## Summary

Provide the ability to selective hide table controls like:
1. Search box
2. Filters
3. Data download
4. Pagination controls

## Motivation

There are use cases where one would want to disable search/filtering/downloading of data or even hide the page next previous controls as one might be doing more complex pagination by themselves.

### PR DESCRIPTION
**Pull request by wmdev0808**
## Description

- Add the header options section for the visibility on the property pane
- Render conditionally the header part based on the setting

Fixes #2111 

## Type of change

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: FEATURE-2111-show-hide-table-controls 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 48.91 **(-0.02)** | 28.6 **(-0.04)** | 26.78 **(0)** | 49.29 **(-0.01)**
 :red_circle: | app/client/src/components/designSystems/appsmith/TableComponent/TableStyledWrappers.tsx | 35.37 **(0)** | 16.67 **(-0.14)** | 0 **(0)** | 35.37 **(0)**
 :red_circle: | app/client/src/widgets/TableWidget/index.tsx | 9.33 **(-0.16)** | 0 **(0)** | 10.64 **(0)** | 10.09 **(-0.18)**</details>

### CODE REVIEW

**Comment by wmdev0808** [comment]
> There is a UI problem, When all the table headers are hidden, There is always extra space under the table.
> 
> Screenshot 2021-05-11 at 5 14 33 PM

OK, let me check

**Review by somangshu — CHANGES_REQUESTED** [review]
The issue here is different now!
The proposed solution is to scale the table content and let the table boundaries remain intact on the grid space. i.e.

We can scale the height of the remaining table. As of now, our table height is
`Table Options Header (38px)` + `Table Header Row (32px)` + `Table Data Rows (40px * no of rows)`

We can change the `Table header row` height to 40px when we are hiding the `Table Options Header`. And change the no of visible rows.

Currently, on deploy preview, we can see that the table overlaps another widget when it's right below and we show/hide the `Table Options Header`


https://user-images.githubusercontent.com/11089579/118507741-23be3e80-b74c-11eb-855b-bd1e42cc409c.mov

**Comment by riodeuno** [comment]
If we've moved development to #4551, shall we close this PR?

**Pull request closed without merging**
