### PR TITLE
[FIX] Update Dropdown Widget default value placeholder

### PR DESCRIPTION
**Pull request by areyabhishek**
## Description
Updated the default value to something that doesn't fail.

Fixes # (issue)
#4596

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- no test required

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>
No changes to code coverage between the base branch and the head branch</details>

### CODE REVIEW

**Comment by somangshu** [comment]
@areyabhishek is this related to #4417, I cannot understand this PR, Kindly add some description if possible.

**Review by somangshu — APPROVED** [review]
Works as expected. Looks good to me!

**Comment by somangshu** [comment]
@vivekverma2312 could you find out if there is an issue related to this? If not, lets create one and link to this PR.

**Comment by vivekverma2312** [comment]
@somangshu Issue #4596 is linked to the PR. Also fix has been tested and looks fine.

Screenshot 2021-05-20 at 4 06 02 PM

**Review by jsartisan — APPROVED** [review]

**Comment by areyabhishek** [comment]
Why are tests failing for something so simple? :/

**Comment by somangshu** [comment]
@areyabhishek the test have been failing for sometime in other branches too. Many PR could not be merged because of the same issue in the last 2 week. We still haven’t  found any resolution to this 😞 . It's already reported to the QA automation team.

@NandanAnantharamu @arslanhaiderbuttar any update here?

**Pull request merged**
