### PR TITLE
fix: fix class cast exception seen on MySQL plugin when built on local setup

### LINKED ISSUE #11385: [Bug]-[288]:MySQL datasource failing on application import
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 75 |
| Effort (months)  | 0.25 |

### PR DESCRIPTION
**Pull request by sumitsum**
## Description
- Currently, when Appsmith API server is built on local setup on console or on IntelliJ and we try to create connection to a MySQL db via MySQL plugin then a `ClassCastException` is thrown as described [here](https://github.com/jcustenborder/kafka-connect-redis/issues/31).
- This PR attempts to resolve the issue by excluding the conflicting packages from MySQL r2dbc driver package as described in the link above. 

Fixes #11385

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- [Manuall on console and IntelliJ](https://theappsmith.slack.com/archives/CPQNLFHTN/p1653472196810239)

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by abhvsn — APPROVED** [review]

**Review by abhvsn — APPROVED** [review]

**Comment by subrata71** [comment]
I have found that the earlier change was 
```
<exclusion>
             <groupId>io.netty</groupId>
             <artifactId>*</artifactId>
</exclusion>
```
and the later change is 
```
<dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-all</artifactId>
            <scope>provided</scope>
</dependency>
```
@sumitsum Can you please state the reason behind this change?

**Comment by sumitsum** [comment]
Skipped the test plan approved label since it is a POM file change.

**Comment by sumitsum** [comment]
@subrata71 the core issue that was ocurring was a conflict between the `netty-all` package provided by the `r2dbc` package and the one that was provided by the API server. The first change removed the `netty-all` package that was being imported as part of the `r2dbc` package - this resolved the conflict. However, for some reason the GitHub CI was failing because if required the `netty-all` pagckage for mysql tests during the test run time - not sure why - this failure is not seen on my local set. Hence I added the `netty-all` package with the `provided` scope - which means that the mysql plugin would fetch the `netty-all` package from the overall dependency tree when required.

**Review by subrata71 — COMMENTED** [review]
> The core issue that was occurring was a conflict between the netty-all package provided by the r2dbc package and the one that was provided by the API server. The first change removed the netty-all package that was being imported as part of the r2dbc package - this resolved the conflict. However, for some reason the GitHub CI was failing because it required the netty-all package for mysql tests during the test run time - not sure why - this failure is not seen on my local setup. Hence I added the netty-all package with the provided scope - which means that the mysql plugin would fetch the netty-all package from the overall dependency tree when required.

The justification looks good to me.

**Pull request merged**
