### PR TITLE
fix: Add white-space CSS to span tag #9626

### LINKED ISSUE #9626: [Bug]: Space is not reflected in the text widget.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I expected the text widget to show the text I entered with the space.
However, as shown in the picture below, all spaces have disappeared.

If it's an intended function, I'd like to suggest adding a white space setting option.

image

image

### Steps To Reproduce

1. Create to Text widget.
2. Enter the text below into Text widget
```
Text
  Text
    Text
      Text
```

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by jerimo**
## Description

I fixed an issue where whitespace was not properly reflected in the text widget. I found that the CSS for `white-space` doesn't exist, and I added it.

Fixes #9626

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manually and also Jest unit tests.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by marks0351** [comment]
@jerimo spaces are recognised now but there seems to a mismatch in amount of space cud u check it out.
bug

**Comment by jerimo** [comment]
@marks0351  ok. I'll work on it.

**Review by marks0351 — CHANGES_REQUESTED** [review]
@jerimo pls let me know if you are stuck on something.

**Comment by jerimo** [comment]
@marks0351 Oh thank you, I didn't spend a lot of time on it these days. I'll try little more and contact you soon.

**Comment by jerimo** [comment]
sorry for the late response. In my opinion, the data displayed in the text widget has the correct number of spaces. Changing the `<span>` to `<pre>` doesn't seem to be a problem. I think it's because of the font, what do you think?

스크린샷 2021-12-27 오후 4 45 54
스크린샷 2021-12-27 오후 4 45 45

**Review by marks0351 — APPROVED** [review]
yea i see that the spaces are accurately shown but the pixels used for each space on the editor vs on the widget seem to different.

**Comment by marks0351** [comment]
@jerimo can u pls pull latest release?

**Comment by jerimo** [comment]
@marks0351  i'm done. cud u check it out?

**Comment by marks0351** [comment]
merging his PR because the failing cases are unrelated to the PR

**Pull request merged**
