### PR TITLE
Property pane for iFrame widget does not appear on clicking on widget

### LINKED ISSUE #6029: [Bug] Property pane for iFrame widget does not appear on clicking on widget
## Description
iFrame widget does not get selected (widget label in orange) on clicking the widget as is the case with other widgets, it's only "selected" when user clicks on the widget label. Hence property pane does not appear on click function. Also, pressing the delete key does not delete widget. 

### Steps to reproduce the behaviour:

1. Drag and drop iFrame widget from widgets toolbar
2. Try to click inside of the frame to select widget - remains in hover state unless user clicks on the widget label above widget

### Important Details

- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: production
https://www.loom.com/share/e15d5630885c45ca8766711105b71b99

### PR DESCRIPTION
**Pull request by wmdev0808**
## Description
- Add an overlaid div for iframe element

Fixes #6029 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Test A
- Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>

    // Code coverage diff between base branch:release and head branch: bug/6029-iframe-property-pane-not-appear 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 51.68 **(0)** | 33.61 **(0.01)** | 29.49 **(-0.01)** | 52.34 **(0)**
 :green_circle: | app/client/src/components/designSystems/blueprint/IframeComponent.tsx | 28.57 **(4.76)** | 19.05 **(4.76)** | 0 **(0)** | 30.77 **(4.45)**
 :green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 50.71 **(0.24)** | 38.6 **(0.88)** | 36.21 **(0)** | 55.35 **(0.27)**
 :red_circle: | app/client/src/widgets/IframeWidget.tsx | 51.35 **(-1.43)** | 0 **(0)** | 42.86 **(0)** | 51.43 **(-1.51)**</details>

### CODE REVIEW

**Review by somangshu — APPROVED** [review]
Approving to run tests

**Comment by somangshu** [comment]
Tested deploy preview, LGTM

**Comment by somangshu** [comment]
@wmdev0808 please resolve this conflict

**Review by somangshu — APPROVED** [review]
Approving for tests to run

**Review by SatishGandham — APPROVED** [review]

**Pull request merged**
