### PR TITLE
fix: Discard failing when there is a conflict with existing datasource

### LINKED ISSUE #25954: [Bug] Unable to discard and pull when there is an existing datasource with same name
The discard and pull does not work when there is a new datasource created with the same name. It provides the following exception:
```
Unable to import application in workspace 649143a571d24622c7775f1e. 
Error: Write operation error on server localhost:27017. 
Write error: WriteError{code=11000, message='E11000 duplicate key error collection: appsmith_ce.datasource index: workspace_datasource_deleted_compound_index dup key: { workspaceId: "649143a571d24622c7775f1e", name: "Plunk_API", deletedAt: null }', details={}}.
```
Here is the steps to reproduce this issue:
1. Create an app and connect it to Git
2. Add a new query and REST API datasource, save the datasource e.g. "ABC"
3. Commit and push the application
4. Delete the ABC datasource
5. Create a new query and REST API datasource with the name "ABC"
6. Try discard and pull

### PR DESCRIPTION
**Pull request by nayan-rafiq**
## Description
Fixed the git discard failure when there is a conflict between existing datasource name and datasource from pulled version. 

#### PR fixes following issue(s)
Fixes #25954

#### Type of change
- Bug fix (non-breaking change which fixes an issue)

#### How Has This Been Tested?
- [x] Manual
- [x] Jest
- [ ] Cypress

#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by AnaghHegde — APPROVED** [review]

**Comment by Parthvi12** [comment]
Verified the issue and its working fine

**Pull request merged**
