### PR TITLE
Fix-Extra grey space in published mode Table Widget when columns are hidden

### LINKED ISSUE #4832: [Bug] Grey spacing is displayed to user when a data/ Columns are hidden
Steps to reproduce:
1) Add a table widget
2) Navigate to Property Pane 
3) Hide the column 
and observe

Observation:
It is observed that the user is displayed with Grey space at the end of the table 

Expectation: 
Expected data must be displayed to the user appropriately the way it is displayed in Deploy mode

Screenshot 2021-06-01 at 1 55 02 PM

### PR DESCRIPTION
**Pull request by vicky-primathon**
## Description
Fixed extra grey space in published mode Table Widget when columns are hidden

Fixes #4832 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Added cypress test to validate column titles are occupying full table space

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/table-hidden-column-empty-space 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 53.37 **(0.02)** | 35.38 **(0.01)** | 32 **(0.02)** | 53.9 **(0.02)**
 :green_circle: | app/client/src/components/designSystems/appsmith/Dropdown.tsx | 33.33 **(1.51)** | 0 **(0)** | 0 **(0)** | 33.33 **(1.51)**
 :green_circle: | app/client/src/components/designSystems/blueprint/DropdownComponent.tsx | 32.89 **(0.79)** | 22.22 **(-0.42)** | 3.45 **(0.22)** | 33.33 **(1.28)**
 :green_circle: | app/client/src/widgets/DropdownWidget.tsx | 45.45 **(3.08)** | 0 **(0)** | 41.67 **(3.21)** | 47.06 **(3.42)**
 :green_circle: | app/client/src/widgets/TableWidget/index.tsx | 9.33 **(0.02)** | 0 **(0)** | 10.64 **(0)** | 10 **(0.03)**</details>

### CODE REVIEW

**Review by somangshu — APPROVED** [review]
Approving to run tests, Deploy preview looks good!

**Comment by YogeshJayaseelan** [comment]
Verified working as expected

**Comment by somangshu** [comment]
Rerunning flaky test fail

**Review by mohanarpit — APPROVED** [review]

**Pull request merged**
