### PR TITLE
Allow all utf-8 characters in page name fixes #5126

### LINKED ISSUE #5126: [Bug]The user is not allowed to add the special character in there page name and widget name
## Description

[What happened]The user is not allowed to add the special character in there page name and widget name

### Steps to reproduce the behaviour:

1. Go to Application
2. Click on Page name /Widget name
3. Try Entering Special Character /UTF 8 Character
4. Verify the display

Actual  Result: The user is not allowed to enter the Special Character

expected result: The user should be allowed to add Special Character as Page and Widget name 

- Version: [Cloud ]
- OS: Windows
- Browser Chrome
- Environment [production]

### PR DESCRIPTION
**Pull request by kaushik94**
## Description

This PR allows all utf-8 characters in page name

Fixes #5126 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>

    // Code coverage diff between base branch:release and head branch: bug/allow-all-utf-chars-page-name 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | app/client/src/utils/helpers.tsx | 52.05 **(0.35)** | 23.19 **(0)** | 20 **(0)** | 45.61 **(0.39)**</details>

### CODE REVIEW

**Review by rishabhsaxena — APPROVED** [review]
LGTM!
@hetunandu @riodeuno just confirming this looks safe?

**Comment by hetunandu** [comment]
We have already discussed this. This should not be allowed
https://github.com/appsmithorg/appsmith/pull/4741#pullrequestreview-680603535

**Comment by kaushik94** [comment]
@hetunandu please take a look at this: https://github.com/appsmithorg/appsmith/issues/5126

**Comment by mohanarpit** [comment]
Closing this PR as this is not required. Added an explanation here: https://github.com/appsmithorg/appsmith/issues/5126#issuecomment-863805815

**Pull request closed without merging**
