### PR TITLE
fix(client): fix default cursor autofocus (#610)

### LINKED ISSUE #610: [BUG]While hitting https://app.appsmith.com/user/login, cursor should be on Email by default
Browser Details: Chrome Version 85.0.4183.102 (Official Build) (64-bit)
Device Details: macOS 10.15.6 (MacBook Pro)
Note: Tried on cloud.

Steps to replicate:
1. Hit https://app.appsmith.com/user/login
2. Observe the input fields.

Expected Result: Cursor should be on 'Email' field by default. The user need not click on the field to enter input.

Example : Hit https://www.facebook.com/ and cursor is on Email field by default.

Attachment : https://drive.google.com/drive/folders/1jRDQGxGqsZ8HZV1KzRgp5PBv_YeYsGXu?usp=sharing

### PR DESCRIPTION
**Pull request by daniloff200**
closes #610

### CODE REVIEW

**Review by sawamoha20 — APPROVED** [review]

**Review by sawamoha20 — COMMENTED** [review]
good

**Comment by mohanarpit** [comment]
@daniloff200 Thank you for the PR ! 🎉 

I'm going to hold onto this PR because @akbansa was already working on this via #695 . I'm going to wait for him to correct his PR over the next 2 days. If he doesn't have time, then I'll accept this PR as the fix. Hope you understand.

**Comment by daniloff200** [comment]
@mohanarpit  Yes, sure thing.

**Comment by mohanarpit** [comment]
Closing as duplicate of #923

**Pull request closed without merging**
