### PR TITLE
fix: #11315 Added trimming in button variant name

### LINKED ISSUE #11315: [Bug]: Icon widget's appearance changes when added whitespace in Button variant
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After enabling JS for icon widget button variant, if we add a space after button variant options, the outer layer of the icon widget gets disappear. Observe in the video
[LOOM DEMO](https://www.loom.com/share/37ac2c819c614051a3826c7a14ad2eab)

### Steps To Reproduce

1. Add icon widget to canvas
2. Enable JS for button-variant from property pane
3. Type "PRIMARY  " and add space after text and observe the icon widget appearance

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by vibhandikyash**
## Description

> Added Trim function for Button Variant Name to avoid sizing issue.

Fixes #11315 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Tested locally.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/11315-trim-whitespace-icon-widget 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 55.82 **(0)** | 37.18 **(0.01)** | 35.2 **(0)** | 56.16 **(0)**
 :green_circle: | app/client/src/selectors/commentsSelectors.ts | 85.25 **(1.64)** | 64.71 **(2.95)** | 73.33 **(0)** | 90.59 **(2.35)**
 :red_circle: | app/client/src/utils/WorkerUtil.ts | 88.98 **(-0.78)** | 70.59 **(-1.96)** | 100 **(0)** | 92.38 **(-0.95)**</details>

### CODE REVIEW

**Review by Tooluloope — APPROVED** [review]

**Review by Tooluloope — COMMENTED** [review]
@vibhandikyash could you add cypress tests for this change

**Comment by shwetha-ramesh** [comment]
@vibhandikyash tested this PR. DP is working as expected.
image

**Pull request merged**
