### PR TITLE
fix: adding mode for graphql syntax with dynamic bindings

### LINKED ISSUE #16702: [Bug]: moustache+quotes formatting goes wrong in graphql body | autocomplete fail
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://www.loom.com/share/ccf9fccc89064ee7b4230aaf5bf3cc52 

1. pairing of moustache brackets and quotes "" causes a parse error (red highlight, no error)
2. after this error, autocomplete does not work anymore

### Steps To Reproduce

see video

### Public Sample App

_No response_

### Version

Release

### PR DESCRIPTION
**Pull request by AmanAgarwal041**
## Description

Adding mode for dynamic binding with quotes for graphql query syntax.

Fixes #16702 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Manually

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by AmanAgarwal041** [comment]
Adding `Test Plan Approved` label as the issue is moved to `Done` pipeline.

**Review by Irongade — APPROVED** [review]

**Pull request merged**
