### PR TITLE
feat: import changes for uneditable field

### LINKED ISSUE #16545: [Task]: Import changes for UneditableField
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Now that we've migrated UneditableField to the design system, we need to test it with the updated API on both ce and ee. If that works, we can take the same approach with other similarly structured components.

### PR DESCRIPTION
**Pull request by tanvibhakta**
## Description

Changes the API of UneditableField as part of the effort to decouple redux from ads components
Fixes #16545 

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Locally on ee on the `feat/import-changes-uneditable-field-eeTest` branch

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by albinAppsmith — DISMISSED** [review]

**Review by albinAppsmith — DISMISSED** [review]

**Comment by shadabbuchh** [comment]
The copy icon does not work for the uneditableField component.
https://www.loom.com/share/a3b0abeaf458463ab6f8c616eecfa806

**Comment by shadabbuchh** [comment]
@tanvibhakta getting a compiling error for this branch
Screenshot 2022-09-28 at 9 26 54 AM

**Comment by tanvibhakta** [comment]
@shadabbuchh were you getting a compile error for this branch or for the `eeTest` branch?

Can you try testing on the `feat/import-changes-uneditable-field-for-ee` branch pulled from ee now?

**Comment by shadabbuchh** [comment]
> @shadabbuchh were you getting a compile error for this branch or for the `eeTest` branch?

@tanvibhakta I was getting a compile error for the `eeTest` branch.

**Comment by shadabbuchh** [comment]
Tested this PR. The copy button is working fine now. However I see some tests failing, so will move it to `Done` once they pass.

**Review by albinAppsmith — APPROVED** [review]

**Review by albinAppsmith — APPROVED** [review]

**Pull request merged**
