### PR TITLE
fix: start with data UI issues fixed

### LINKED ISSUE #29254: [Bug]: Start with data onboarding initiative bugs - 2
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

- [too much white space in datasource form, can’t see CTAs](https://www.notion.so/appsmith/too-much-white-space-in-datasource-form-can-t-see-CTAs-fd05d99a4fc04a9da273226477d41426?pvs=4)
- [When there is a small space then the form is itself scrolling instead of the full screen.](https://www.notion.so/appsmith/When-there-is-a-small-space-then-the-form-is-itself-scrolling-instead-of-the-full-screen-76f4871977d34c3fb2dfc23ddcf57944?pvs=4)

### Steps To Reproduce

1. Sign up as a new user
2. Select start with data flow
3. Select a plugin
4. Observe the datasource form

### Public Sample App

_No response_

### Environment

Deploy Preview

### Issue video log

_No response_

### Version

Cloud/ Self-Hosted - 1.8.4

### PR DESCRIPTION
**Pull request by sneha122**
## Description

This PR fixes two of the UI issues in start with data flow:
[too much white space in datasource form, can’t see CTAs](https://www.notion.so/appsmith/too-much-white-space-in-datasource-form-can-t-see-CTAs-fd05d99a4fc04a9da273226477d41426?pvs=4)
[When there is a small space then the form is itself scrolling instead of the full screen.](https://www.notion.so/appsmith/When-there-is-a-small-space-then-the-form-is-itself-scrolling-instead-of-the-full-screen-76f4871977d34c3fb2dfc23ddcf57944?pvs=4)

#### PR fixes following issue(s)
Fixes #29254 
#### Type of change
- Bug fix (non-breaking change which fixes an issue)
>
>
>
- [x] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

## Summary by CodeRabbit

- **New Features**
  - Introduced an onboarding flow for the DataSource Editor, enhancing the user experience for new users.

- **Style**
  - Updated the DataSource Editor interface to dynamically adjust its layout during the onboarding process.

### CODE REVIEW

**Comment by AmanAgarwal041** [comment]
Tested the fixes. It is good to go. 
Just one observation, when we click on cancel button, it redirects me to the application instead of going back. Is this expected ? @sneha122

**Review by AmanAgarwal041 — APPROVED** [review]

**Comment by sneha122** [comment]
Thanks @AmanAgarwal041 On cancel it should ideally go back to plugins page, let me check that flow once

**Pull request merged**
