### PR TITLE
fix\Issues while performing actions on Home Page #749

### LINKED ISSUE #749: [BUG] Issues while performing actions on Home Page
Attachment : https://drive.google.com/drive/folders/1vFgWznBzwZEXRBxaFXYnUZ1AcBjux_DM?usp=sharing

Browser Details: Chrome
Device Details: macOS 10.15.6 (MacBook Pro)
Note: Tried on cloud.

Issue 1: Go to edit mode --> On the left side, click on Delete against Home Page.
Actual Result : Cannot Delete Home Page.
Expected Result:  No option to delete Homepage.

Issue 2: When there is just 1 page available (Home Page), try clicking on 'Move to Page'
Actual Result : Broken UI.
expected Result: Proper UI.

### PR DESCRIPTION
**Pull request by A-Scratchy**
Fixes #749 

## Description

> Issue 1: Go to edit mode --> On the left side, click on Delete against Home Page.
  Actual Result : Cannot Delete Home Page.
  Expected Result: No option to delete Homepage :heavy_check_mark: 

- Added a condition to ask if this page is the default page. If it is do not show the delete option in the `PageContextMenu`

#### menu on default page
Screenshot(11)

#### menu on non default page
Screenshot(13)

> Issue 2: When there is just 1 page available (Home Page), try clicking on 'Move to Page'
  Actual Result : Broken UI.
  expected Result: Proper UI. :heavy_check_mark: 

- Added a conditional to check if we have more than 1 page in the `menuPages` item. If we do then filter out our current page and display the rest. Otherwise show `No Pages`

#### menu when we have only 1 page
Screenshot(12)

#### menu when we have 2 pages
Screenshot(14)

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
Tested manually on local machine

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by satbir121** [comment]
@A-Scratchy There is a test failing. Please fix it. Use `yarn run cytest` to run the tests locally.

**Review by riodeuno — COMMENTED** [review]
@A-Scratchy The code looks good to me! Please look into the failing test.

**Comment by Nikhil-Nandagopal** [comment]
@A-Scratchy any update on this?

**Comment by A-Scratchy** [comment]
Hi, just trying to figure out what's going on...

**Comment by A-Scratchy** [comment]
Seems to be something to do with Postgres. Test tries to call datascources/structure but gets "status":500,"success":false,"error":{"code":5000,"message":"Plugin failed to get structure with error PluginExecution failed with error Error connecting to Postgres." I get this even on release branch locally. @Nikhil-Nandagopal Can we rerun tests for this PR??

**Comment by hetunandu** [comment]
@A-Scratchy since this is a fairly old PR can we rebase the latest release here and run the test suit again? 
The error you mentioned is expected if you have a bad datasource configured, but it should not cause any tests to fail or crash the app

**Comment by A-Scratchy** [comment]
Checks are saying PR is too old... `You are attempting to pass the --parallel flag to a run that was completed over 24 hours ago.` Shall we scrap this PR and I can make a fresh one?

**Comment by hetunandu** [comment]
Yea this merge was not right. If you are not able to fix it, a fresh PR is a normal way to go

**Pull request closed without merging**
