### PR TITLE
test: add test for git sync bug #10773 

### PR DESCRIPTION
**Pull request by Parthvi12**
## Description

- Added test for  Bug:10773 When user delete a resource form the child branch and merge it back to parent branch, still the deleted resource will show up in the newly created branch
- Fixed flaky tests

Fixes # (issue)

## How Has This Been Tested?

locally

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>

    // Code coverage diff between base branch:release and head branch: gitTests 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | app/client/src/utils/WorkerUtil.ts | 88.98 **(-0.78)** | 68.63 **(-3.92)** | 100 **(0)** | 92.38 **(-0.95)**</details>

### CODE REVIEW

**Comment by Parthvi12** [comment]
ok-to-test sha=f357576

**Review by Aishwarya-U-R — APPROVED** [review]

**Pull request merged**
