### PR TITLE
fix: Set isMetaPropDirty property on widgets

### LINKED ISSUE #20634: [Bug]: Appsmith returns undefined instead of empty string for widgets with no value.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

From new updates, appsmith returns `undefined`  instead of an empty string, breaking some of the things some users have worked on.  For example, something like `selectWidget.filterText` usually returns an empty string if there's no value, but from recent updates, it returns `undefined`, which is a breaking change for users that depends on the previous behavior

### Steps To Reproduce

1. Create a select widget and make sure there's no text in the filter
2. Create a query that uses `selectWidget.filterText`; this will evaluate to undefined 

### Public Sample App

_No response_

### Issue video log

_No response_

### Version

Cloud/ Self-hosted 1.9.7

### PR DESCRIPTION
**Pull request by ohansFavour**
## Description
Sets default values of meta fields to their defaultMetaProps value instead of undefined

Fixes #20634 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Cypress

### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by Rishabh-Rathod — DISMISSED** [review]
LGTM

**Comment by ramsaptami** [comment]
LGTM @ohansFavour

**Review by Rishabh-Rathod — APPROVED** [review]
LGTM

**Pull request merged**
