### PR TITLE
fix: Anvil zone widget default configurations

### PR DESCRIPTION
**Pull request by riodeuno**
## Description
- Zone widget needs the `flexVerticalAlignment` configurations to make the layout stretch to occupy all vertical space in a section
- Zone widget's layout configuration needs a `height:100%` to enable highlights in an empty zone.

## Automation

/ok-to-test tags="@tag.All"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/10221060293>
> Commit: 76b97f97b1ff6b487db00684584a97957094bcba
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=10221060293&attempt=1" target="_blank">Cypress dashboard</a>.
> Tags: `@tag.All`
> Spec:
> <hr>Fri, 02 Aug 2024 20:25:54 UTC

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [x] No

## Summary by CodeRabbit

- **New Features**
	- Introduced a new `layoutStyle` property for enhanced border and height control in layout components.
	- Added `flexVerticalAlignment` property to improve vertical alignment flexibility in widgets, allowing for responsive design enhancements.

These changes aim to provide users with greater customization options for layout and widget presentation.

### CODE REVIEW

**Comment by riodeuno** [comment]
@KelvinOm We need to visit the layouts architecture in Anvil. This follows what @marks0351 had mentioned regarding the fact that layouts being configurable is not necessary given that we only have a limited types of layouts and they're specific to widgets. I've created a task for this. https://github.com/appsmithorg/appsmith/issues/35300

Please let me know if this task is a duplicate. I couldn't find this task in the list of issues on our zenhub board.

**Comment by sagar-qa007** [comment]
@riodeuno Do we need unit test cases here ?

**Comment by riodeuno** [comment]
@sagar-qa007 If we add test unit test to the changes in this PR, we will be testing static configurations. I'm not sure if that warrants any tests.

**Review by KelvinOm — APPROVED** [review]

**Pull request merged**
