### PR TITLE
fix: Fix evaluated popup on all screens

### LINKED ISSUE #4458: [Bug]Evaluated value popup overlaps the DB query editor when the browser is minimized
## Description
Release Environment - PostgresSQL - It is observed that due to overlapping the cursor in the DB query editor is hidden due to which the user feels he/she cannot complete the action 

Expected Result:
Cursor should be visible clearly in the minimized mode and the evaluated value popup should be placed appropriately 

Actual Result:
Due to overlapping the cursor in the DB query editor is hidden due to which the user feels he/she cannot complete the action 

### Steps to reproduce the behaviour:
1. Launch Appmsith app in the Release Environment 
2. Expand DB
3. Create new Datasource with postgresSQL
4. Set up authentication 
5. Minimise the screen to 70-80% mode 
6. Check for the Evaluated value popup overlap and the DB query Cursor 

**VideoLink:**
[LOOM DEMO](https://www.loom.com/share/805ca00592614bdb8f4b02535927e760)

### Important Details
 - Version: [Chrome - 90.0.4430.212 ]**
 - OS: [MacOS Big Sur 11.3]
 - Browser [Chrome]

### PR DESCRIPTION
**Pull request by Irongade**
This PR fixes how the evaluated pop up overlaps the property pane when on smaller window screens.

Fixes #4458

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Visual Test.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by AmanAgarwal041 — DISMISSED** [review]

**Comment by prapullac** [comment]
Please find the screenshot here as I observe there is overlap of the evaluated value on the query body
Screenshot 2022-10-22 at 10 17 44 PM

**Comment by AmanAgarwal041** [comment]
@Irongade We discussed about the solution but it doesn't cater to all the scenarios. Hence, we would like to go back to the design phase to correct the ui as well. So moving the issue to `Design backlog` and marking this Pr as draft so that it doesn't reminds daily to review this PR for a while.

**Pull request closed without merging**
