### PR TITLE
feat: allow HTTP port customization in Helm chart

### LINKED ISSUE #36761: [Feature]: Allow customization of HTTP port in Helm chart
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Right now tcp/80 is hardcoded https://github.com/appsmithorg/appsmith/blob/8463d02740f9e300c8d306c7012edec39067d2ff/deploy/helm/templates/statefulset.yaml#L73

The feature is about adding a config in values.yaml to customize this port.

I've drafter an implem, a PR will follow.

### Why should this be worked on?

My K8S setup is based on the well-known and used community EKS terraform module. And I'm using Nginx ingress controller (community).

a) The terraform module doesn't allow node-to-node communication on privileged port (< 1025)
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/d2c671aca25165cc060e2459f5cafb49868a7be3/node_groups.tf#L134

b) Internally the Ingress configuration relies on Service, but Nginx ingress controller actually resolve the service endpoint and use directly the pod IP to fill-in its maintained nginx config file. If I remember correctly it's to allow for better load balancing than the Service loadbalancing abstraction offers.

So for Ingress to work, a nginx pod needs to contact directly (see b) appsmith's Caddy on tcp/80 pod IP, and because of a) it doesn't work.

I can fix by extending the node-to-node communication security group to privileged port but it's not advisable because

c) Opening a listening port on privileged port requires either root user or at least the CAP_NET_BIND_SERVICE capability. Both are security bad practice: secured environment must leverage SecurityContext to prevent root user and drop all capabilities (at least).

### PR DESCRIPTION
**Pull request by damienleger**
## Description
See https://github.com/appsmithorg/appsmith/issues/36761

I've been tested this with ee Helm chart. Imho tcp/8080 should be the default port but to avoid breaking change, tcp/80 remains the default port if the new variable is not specified.

Fixes #36761

## Automation

/ok-to-test tags=""

### :mag: Cypress test results

> [!CAUTION]  
> If you modify the content in this section, you are likely to disrupt the CI result for your PR.

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [X] No

## Summary by CodeRabbit

- **New Features**
	- Enhanced configurability of the HTTP container port through the introduction of a new variable (commented out).
	- Updated the Helm chart version from 2.1.0 to 2.2.0.

- **Bug Fixes**
	- Improved indentation and formatting for better readability.

- **Documentation**
	- Commented-out configuration for `HTTPContainerPort` included for future reference.

### CODE REVIEW

**Review by pratapaprasanna — DISMISSED** [review]

**Comment by pratapaprasanna** [comment]
@damienleger  Please bump the chart version and we can merge this

**Comment by damienleger** [comment]
> @damienleger Please bump the chart version and we can merge this

@pratapaprasanna Done!

**Comment by damienleger** [comment]
Hello, kind reminder to merge this PR please! 🙏

**Comment by damienleger** [comment]
Please merge 🙏

**Pull request merged**
