### PR TITLE
feat: Rename actions to events in property pane

### LINKED ISSUE #4495: [Feature] Rename Widgets "Actions" to "Events"
## Summary

This feature aims to rename 'Actions' to 'Events' in the property pane

## Motivation

Events communicate better the intent of that section in the property pane

https://user-images.githubusercontent.com/17744578/118364523-9d3c0e00-b54d-11eb-8f47-c5a629fbda48.mp4

### PR DESCRIPTION
**Pull request by cokoghenun**
## Description

This PR renames the 'Actions' section in the widget property pane to 'Events'. This better communicates the intent of the section i.e users can run actions when _events_ occur, thus the section should be named events.

I've also made an update to the relevant parts of the documentation to update actions to events. See this PR for more info https://github.com/appsmithorg/appsmith-docs/pull/281 

Fixes  #4495

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Test A: This has been tested locally on my computer
- Test B: All unit tests were run after this change and they all passed

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by cokoghenun** [comment]
Okay, I'll remove it

**Comment by cokoghenun** [comment]
Done

**Review by hetunandu — DISMISSED** [review]

**Comment by cokoghenun** [comment]
@hetunandu  Can this be merged?

**Review by hetunandu — APPROVED** [review]

**Pull request merged**
