### PR TITLE
fix: modal and App viewer header overlap

### LINKED ISSUE #14849: [Bug]: Modal overlaps with nav bar in smaller screens
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When i open a large modal in the view mode for small screens it overlaps with the nav bar.
image

When a modal is open it should take the highest priority

### Steps To Reproduce

1. Add a large modal
2. Deploy the app
3. Open the modal
4. Observe it is blocked by nav bar

### Public Sample App

_No response_

### Version

Cloud 1.7.5

### PR DESCRIPTION
**Pull request by rahulramesha**
## Description

This PR contains fix for modal and header overlap in View mode.
We are recalculating modal top and modal height in view mode based on header height

Fixes #14849

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
Manual UI

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by jsartisan** [comment]
@rahulramesha Can we connect for this? I have a better solution for this in mind.

**Review by jsartisan — APPROVED** [review]

**Comment by Sripriya93** [comment]
Have verified, Modal isn't overlapping with the header

**Pull request merged**
