### PR TITLE
fix: 9824 Google Sheet to filter empty condition

### LINKED ISSUE #9824: [Bug]: Unable to filter by empty conditions in Google sheets
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On trying to apply a where condition on Google sheets to search for an empty value, the plugin responds with an error.

### Steps To Reproduce

Create a `Fetch sheet rows` request with a condition like `"columnName" == [empty_value]`

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by leotom2000**
## Description
To get data from Google Sheet with empty where condition
We get empty array when the where condition is with no data in values field, 
ie when we want to search a user with no emailId, then we are getting a empty array [] although data exists

**Resolution :** 
Able to pull data when condition with empty value ( '' )is provided.
The current generated query is something like
--Select * from table where emailId=? (1, '') ; //This preparedstatement doesnt work
Modified code to generate like
--Select * from table where emailId IS NULL;   //This works

Fixes #9824

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Manual
Unit Test Added

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by nidhi-nair** [comment]
@leotom2000 Could you please provide information about what the bug that you were trying to fix was, what error was thrown initially, and why you have made the change that you have?

**Comment by leotom2000** [comment]
> @leotom2000 Could you please provide information about what the bug that you were trying to fix was, what error was thrown initially, and why you have made the change that you have?

Missed to add details in the description.
Added requirement/resolution details in the PR description now.

**Review by nidhi-nair — CHANGES_REQUESTED** [review]
Needs rework, addresses the incorrect scenario

**Comment by leotom2000** [comment]
Creating a new PR since a new branch was created. The new change/update is not a fix but  a new implementation so a new branch was created.
Closing this PR without any merges.

**Pull request closed without merging**
