### PR TITLE
fix: widget borders does not reflect widget height

### LINKED ISSUE #23690: [Bug]: In fixed mode, all auto height widgets are having incorrect min height .
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

there is a slight reduction in auto height than what it is supposed to be . All auto height widgets are having reduced height in bounding boxes but the references are correct

### Steps To Reproduce

https://www.loom.com/share/d15229490f6349eabb2a9c70e62a7f13

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

Release

### PR DESCRIPTION
**Pull request by riodeuno**
#### Reported issue
If a widget - not a container like widget - has a minimum height of 4 rows, and the auto height is enabled for the widget, the widget borders signify a much smaller height. Example - checkbox widget.

#### Results of RCA
This was happening because, we set `height: auto` for all widgets, when it should have been done only for container like widgets. The `height:auto` in the resizable library, allowed the library to show the widget borders completely hugging the contents of the widget, when it should have been restricted to a minimum of 4 rows (40px). This is because, in the platform, the minimum height any widget can have is 4 rows (40px) in Fixed mode (not auto layout mode)

#### Solution:
We exclude widgets which do not have `isCanvas` property set to `true` from setting the `autoHeight` flag. This allows the library to set the provided height instead of hugging contents.

#### PR fixes following issue(s)
Fixes #23690 

#### Type of change
- Bug fix (non-breaking change which fixes an issue)
#### How Has This Been Tested?
- [x] Manual
- [x] Cypress

#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Comment by tanvibhakta** [comment]
ads review not needed here 👍

**Review by marks0351 — DISMISSED** [review]

**Review by rahulramesha — DISMISSED** [review]

**Review by rahulramesha — APPROVED** [review]

**Pull request merged**
