### PR TITLE
fix: Adding deploy button on git deploy tab

### LINKED ISSUE #13642: [Bug]: Show a deploy button on Deploy tab [git]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I connect app to git repo, all of the files are getting written to remote repo in one commit. After connection, we take users to deploy tab. Since there are no changes to be committed, we disable commit functionality. And now there is no way for users to Deploy from the tab itself.

Either of one solution would suffice:

1. User should see a deploy button after initial commit. OR
2. We should not take user to Deploy tab after initial connection.

### Steps To Reproduce

1. Create a new app
2. Git connect it to a new remote repo
3. See that user ends up deploy tab, but there is nothing for user to do.

---

## what user sees after initial connection.

Screenshot 2022-05-06 at 1 41 35 PM

### Public Sample App

_No response_

### Version

Release

### LINKED ISSUE #14596: [Bug]: Commit message input becomes enabled for a short while after commit
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I commit changes, commit message input box becomes enabled for a short while.

I should not see enabled input box again.

### Steps To Reproduce

1. Make some changes in git backed app.
2. Commit changes
3. Notice that after successful commit, we see enabled input box for a while. (Around 00:24 below)

https://user-images.githubusercontent.com/1573771/174009273-000c1b58-dd30-4019-973c-4782e2f150d8.mov

### Public Sample App

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by IAmAnubhavSaini**
## Description

Fixes #13642 
Fixes #14596

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by IAmAnubhavSaini** [comment]
## Input box issue

### bug

https://user-images.githubusercontent.com/1573771/174009273-000c1b58-dd30-4019-973c-4782e2f150d8.mov

### fix

https://user-images.githubusercontent.com/1573771/174010567-fd614413-2081-42ab-ada7-671c3a5a1721.mov

## missing deploy info issue

### bug

https://user-images.githubusercontent.com/1573771/174010827-11834d70-c992-4971-b3d6-ab85423624d3.mov

### fix

https://user-images.githubusercontent.com/1573771/174010973-e9e3e2ed-8cfc-4092-b1bf-2d0a20414d11.mov

**Comment by IAmAnubhavSaini** [comment]
@RakshaKShetty please test the DP for fixes.

**Review by ankitakinger — APPROVED** [review]

**Comment by RakshaKShetty** [comment]
Both the issues are fixed, Found a new issue raising it separately on github

**Review by ankitakinger — APPROVED** [review]

**Comment by IAmAnubhavSaini** [comment]
Passing tests:

Screenshot 2022-06-27 at 12 35 34 PM

**Review by ankitakinger — APPROVED** [review]

**Comment by RakshaKShetty** [comment]
The issue is fixed here the  commit message input box will be displayed in disabled state when user click on the commit button

**Pull request merged**
