### PR TITLE
fix: select widgets label alignment when label is on left.

### LINKED ISSUE #18259: [Bug]:  select widgets label alignment when labelPosition is LEFT
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

- The labels of all inputs when label position is LEFT should be vertically centered as is the case for the input widget
- But for the select widgets the labels are top aligned when label position is LEFT.
- This bug should be resolved as it will be used for Dynamic Height.

image

### Steps To Reproduce

1. Drag and Drop an input widget and change label position to LEFT the label is center-aligned
2. Drag and Drop any select widget and change label position to LEFT, the label is top-aligned
3. The labels for select widgets when position is LEFT should be center aligned.

### Public Sample App

_No response_

### Issue video log

_No response_

### Version

Release

### PR DESCRIPTION
**Pull request by yaldram**
## Description
- Label for all select widgets are not center alignment when we choose LabelPosition = LEFT. This pull request fixes it, the label is now center aligned to the input.

Fixes #18259 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manual

### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Comment by Tooluloope** [comment]
@yaldram Could you tag the issue this is fixing

**Comment by yaldram** [comment]
@Tooluloope I have tagged the issue please check. Thanks

**Comment by Tooluloope** [comment]
@yaldram Could you add a fix for Checkbox Group as well

Screenshot 2022-11-18 at 09 59 15
 

@dilippitchika Are we leaving RichTextEditor as it is?

Screenshot 2022-11-18 at 09 59 40

**Comment by yaldram** [comment]
@Tooluloope I have added `checkbox group`.

**Comment by yaldram** [comment]
@Tooluloope all the `group` widgets follow the top label position, I would say we create a new issue with all the inconsistencies across the `group` widgets.

**Review by Tooluloope — DISMISSED** [review]

**Pull request closed without merging**
