### PR TITLE
chore: code split for EE PR 2169

### PR DESCRIPTION
**Pull request by ayushpahwa**
## Description
Code split for EE PR [#2169](https://github.com/appsmithorg/appsmith-ee/pull/2169)

#### PR fixes following issue(s)
Fixes [#2164 EE issue](https://github.com/appsmithorg/appsmith-ee/issues/2164)

### CODE REVIEW

**Review by ankitakinger — DISMISSED** [review]
I hope these changes have been tested. Code-wise, LGTM.

**Review by ApekshaBhosale — APPROVED** [review]

**Comment by ayushpahwa** [comment]
Adding skip label since this is a dev only change

**Review by ankitakinger — APPROVED** [review]

**Pull request merged**
