### PR TITLE
fix: geolocation.currentposition.coords.lat is giving error also on map geolocation is giving lint error

### LINKED ISSUE #25746: [Bug]: geolocation.currentposition.coords.lat is giving error also on map geololation is giving lint error
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Below code gives error - 
`func44:async()=>{
appsmith.geolocation.getcurrentposition()
let var1 =    appsmith.geolocation.currentPosition.coords.latitude
}`

image

Also  below data in map  is giving async/sync lint error

[
  {
    "lat": {{appsmith.geolocation.currentPosition.coords.latitude}},
    "long": 50.132,
    "title": "Location1"
  }
]

Recording:

https://github.com/appsmithorg/appsmith/assets/80756091/9471eccf-fb10-4983-b67c-e1d449c1d768

### Steps To Reproduce

Add above code and run 

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

cloud

### PR DESCRIPTION
**Pull request by Druthi**
## Description
Fix: geolocation.currentposition.coords.lat is giving error also on map geolocation is giving lint error

#### PR fixes following issue(s)
Fixes #25746

#### Type of change
- Bug fix (non-breaking change which fixes an issue)

>
>
>
- [x] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Comment by AnandiKulkarni** [comment]
@Druthi Verified appsmith.geolocation.currentlocation working fine

**Review by Rishabh-Rathod — APPROVED** [review]
LGTM

**Pull request merged**
