### PR TITLE
feat: Add USA to the Map Chart Widget

### LINKED ISSUE #16059: [Feature]: Add US map into the map chart widget
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Add US map into the map chart widget

### Why should this be worked on?

A user requested it here - https://app.intercom.com/a/inbox/y10e7138/inbox/shared/all/conversation/164629100159452#part_id=comment-164629100159452-16336696461

### PR DESCRIPTION
**Pull request by dhruvikn**
## Description

This PR adds the USA to the Map Chart Widget

CleanShot 2022-08-18 at 14 28 22@2x

Fixes #16059

## Type of change
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
- Manually tested
- Added a test case to the Cypress Spec

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by somangshu** [comment]
@keyurparalkar can you review this. Take any info from @dilippitchika from the product pov.

Also, from past, here the build size tends to increase a lot and we should be cognizant of the fact.

**Review by keyurparalkar — APPROVED** [review]
LGTM!

**Comment by chandannkumar** [comment]
USA map is added.
Tested this PR and working fine

**Comment by dhruvikn** [comment]
@somangshu can we merge please? TIA

**Comment by somangshu** [comment]
Please run the test once more with the latest release and let me know @dhruvikn

**Pull request merged**
