### PR TITLE
fix: allow camera & mic access for page in iframe

### LINKED ISSUE #12924: [Bug]: Can't call the camera in iframe
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Using the iframe widget, can't call the camera in iframe

### Steps To Reproduce

1.iframe URL : https://blog.minhazav.dev/research/html5-qrcode.html

### Public Sample App

_No response_

### Version

Self Host 1.6.6

### PR DESCRIPTION
**Pull request by ganganimaulik**
## Description

add `allow="camera; microphone"` so it will allow camera & mic access inside iframe

Fixes #12924 
 
## Type of change
 
- Bug fix (non-breaking change which fixes an issue)
 
## How Has This Been Tested?
- dragged iframe & set URL to https://blog.minhazav.dev/research/html5-qrcode.html
- make sure camera works

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by somangshu — APPROVED** [review]
Change LGTM

**Comment by somangshu** [comment]
Tested DP in comparison to release, And this is working as expected

**Comment by somangshu** [comment]
Build running [here](https://github.com/appsmithorg/appsmith/actions/runs/2237466628)

**Comment by ganganimaulik** [comment]
> @allcontributors add @ganganimaulik as a contributor for code

wow I am on appsmith github page! thanks ☺️

**Pull request merged**
