### PR TITLE
fix: use disabled cursor when icon disabled

### LINKED ISSUE #10624: [Bug]-[400]:"Disable icon" should be visible in Table widget's icon column is set to Disabled
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[LOOM DEMO](https://www.loom.com/share/787a5533764443d6a57697747b73f062)

### Steps To Reproduce

1. Drag and drop a Table widget
2. Change the action column type to Icon widget
3. Select a icon widget
4. Enable disable property
5. Observe that when we hover the cursor on disabled icons, cursor icon should be changed to disable icon same as other widgets

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by adarshlilha**
## Description

cursor for iconButton is not disabled, even when the iconButton is disabled from cursor control
This is fixed with this PR

- Fixes #10624 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual Tests employed.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by adarshlilha** [comment]
@somangshu please review

**Comment by somangshu** [comment]
Thanks for the contribution @adarshlilha

**Comment by somangshu** [comment]
@adarshlilha Can you merge the latest release version here, There has been a lot of changes in the last 18 days.

**Comment by adarshlilha** [comment]
@somangshu merged release branch, please review

**Review by aswathkk — CHANGES_REQUESTED** [review]
Hi @adarshlilha,
Thanks for your contribution.

`pointer-events: all` introduces a bug where we are unable to drag the disabled Icon button widget in the canvas.

For details, check out #8206

**Comment by somangshu** [comment]
@aswathkk the issue with the above solution on the DP seems intermittent to me.

@adarshlilha let us know if you are not able to reproduce the issue

**Comment by aswathkk** [comment]
@somangshu You will be able to consistently reproduce the issue if you click on the correct area.
Click on the button's surface. Not on the icon. attaching a video here to show that:

https://user-images.githubusercontent.com/10436935/156143517-88f68871-dc26-46be-af83-00f887c6748b.mov

You will also consistently reproduce this if you select an empty icon.
Glad that Cypress test is written for covering this case.

**Comment by techbhavin** [comment]
@somangshu  @aswathkk  closing this PR. this issue is we cover in new PR

**Pull request closed without merging**
