### PR TITLE
fix: Fix shareapp case due to load issue

### PR DESCRIPTION
**Pull request by sagar-qa007**
## Description
Fixes #`36626`  

Issue: Script was clicking on share button without full page load.
Solution: Waited for page load with api.

EE PR: https://github.com/appsmithorg/appsmith-ee/pull/5285

## Automation

/ok-to-test tags="@tag.Sanity"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/11174778224>
> Commit: 80be7e10eac4227b33702435f679e21173f12ef8
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=11174778224&attempt=2" target="_blank">Cypress dashboard</a>.
> Tags: `@tag.Sanity`
> Spec:
> <hr>Fri, 04 Oct 2024 07:01:59 UTC

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [x] No

## Summary by CodeRabbit

- **New Features**
	- Enhanced test coverage for workspace sharing and public access functionalities.
	- Added assertions to validate visibility of the Git sync bottom bar during application editing.
  
- **Bug Fixes**
	- Updated specification for limited tests to point to the correct test file, ensuring accurate execution of tests.

### CODE REVIEW

**Comment by brayn003** [comment]
Don't think it is a good idea to use a git element in a test that is not related to git. Probably use other indicators like canvas element appearing or consolidated-api returning 200

**Comment by sagar-qa007** [comment]
@brayn003 Please check and approve now. Have updated.

**Review by brayn003 — APPROVED** [review]
lgtm

**Pull request merged**
