### PR TITLE
fix: showScrollbarOnlyOnHover not working correctly for ScrollIndicator

### LINKED ISSUE #16283: [Task]: Update design-system version from 1.0.15 to 1.0.16
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

_No response_

### PR DESCRIPTION
**Pull request by souma-ghosh**
## Description

ScrollIndicator component improvements
Adds showScrollbarOnlyOnHover functionality to ScrollIndicator

Fixes #16283 

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Manually tested

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by albinAppsmith — APPROVED** [review]

**Comment by souma-ghosh** [comment]
Release has already been updated with the latest version of design-system (1.0.18). Hence merging this PR is not necessary anymore.

**Pull request closed without merging**
