### PR TITLE
feat: 5xx error message with links

### LINKED ISSUE #21524: [Feature]: Add instructions on the 5xx error pages on how to get the logs.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Currently, Appsmith only shows a plain empty page for 5xx errors.
We want to include basic instructions on how to obtain the logs and share them with the support team in the error pages, on top of the existing info on the 5xx pages.

### The 5xx page should contain the information below.

Click <a href="/supervisor/logtail/backend"> here </a>to have a quick look at the Server logs on Supervisor.

Please share the full logs in the `stacks/logs/backend` directory with  <a href="mailto: support@appsmith.com?subject=Appsmith 503 Server Error"> Appsmith Support </a> .

You can find more instructions on how to access logs on other platforms in the Appsmith [How to guide](https://docs.appsmith.com/learning-and-resources/how-to-guides/how-to-get-container-logs).

### Why should this be worked on?

This will improve the user experience when they encounter 5xx error when the user's are not sure how to fetch the logs.
This would also make the troubleshooting process quicker for support.

### PR DESCRIPTION
**Pull request by eco-monk**
## Description

Updated error messages with link for 503 error page
https://www.figma.com/file/nVvIoLuCmTjvivejSnCML8/5XX-Error-states?node-id=2-179&t=Z6nt7OQB00EjeWt5-0

Fixes #21524

## Media

CE cloud hosted:
- Link opens a email to support@appsmith.com
https://www.loom.com/share/9f904f0b97844961b9be3235780095d5

CE self hosted:
- first link opens [documentation](https://docs.appsmith.com/learning-and-resources/how-to-guides/how-to-get-container-logs)
- second link opens relative path `/supervisor/logtail/backend`
https://www.loom.com/share/d39070575ca943fda1e6b49368cde1d5

EE: (same as CE self hosted, but without appsmith label)
Addressed here: https://github.com/appsmithorg/appsmith-ee/pull/1245
https://www.loom.com/share/65568d09b76044309de2e42aac3cc0fe

## Type of change
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Manual

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by hetunandu — CHANGES_REQUESTED** [review]

**Review by hetunandu — APPROVED** [review]

**Comment by Richarex** [comment]
- [ ] **Built on appsmith** hyperlink is missing for the Non-cloud version app (ce instance) which is there in the design doc. Please refer the attached SS:-

**Comment by eco-monk** [comment]
For the built in appsmith badge, it’s gonna take some file splitting to handle EE and CE cases. 
In favour of time, Will create a separate bug for this.

**Comment by Richarex** [comment]
Testing is completed for 5xx error messages for **cloud**, **non-cloud** & **business edition** versions. This PR looks good to me.

**Pull request merged**
