### PR TITLE
fix: JSobject and Api pane title

### LINKED ISSUE #11008: [Bug]: Make JS Object page consistent with Query and Api pages.
Description

- The name/ title component of the JSObject is different from that of Apis and Queries.

Screenshot 2022-02-08 at 11 26 12 PM

Screenshot 2022-02-08 at 11 26 06 PM

- The JS Object UI doesn't seem the same as our queries. It is moving positions like in the video below

https://user-images.githubusercontent.com/46670083/166943948-d324f444-eebb-49e2-b9b2-2121727df4f9.mov

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

See Description

### Steps To Reproduce

1. Create a JSObject. See the UI. 
2. Create an API. See the UI.
3. Create a Query. See the UI

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by devnamrits**
## Description

The JSObject and API pane title were different. The edit icon was missing from JSObject. Changes are made to fix the JSObject title pane.

Fixes #11008 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by devnamrits** [comment]
@AmanAgarwal041 Can you please review this PR? It would be great you give a go-ahead.

**Comment by devnamrits** [comment]
@AmanAgarwal041 Any update??

**Comment by AmanAgarwal041** [comment]
@devnamrits  Can you use the ads component for API Editor but change the UI for JS Editor to look same as API Editor today ?

**Comment by devnamrits** [comment]
Okay @AmanAgarwal041  Will try to do so. If faced any sort of difficulty, I'll ping you!

**Comment by devnamrits** [comment]
Hi @AmanAgarwal041, as stated by you, I've tried to implement that.

Screenshot 2022-03-21 at 11 07 01 PM

Screenshot 2022-03-21 at 11 07 10 PM

Will this work??

Also, the cloud icon which present in the API pane is stored in AWS s3 and is being picked from respective plugins within the ads component. The plugin details are stored in the backend.
As of now, I've used an example JS icon picked from internet in JSObjectPane. Can you please provide me the image link? Also, any other changes that I need to do??

**Comment by devnamrits** [comment]
@AmanAgarwal041 Sorry, my bad.
Screenshot 2022-03-21 at 11 28 59 PM
I think this will work fine. Also, this won't require any image uploads in AWS s3. I've imported this from ExplorerIcons.
Should I push it? Any other proposed changes??

**Comment by AmanAgarwal041** [comment]
@devnamrits Just push your changes. I will update in this thread if there are any other changes required.

**Comment by devnamrits** [comment]
@AmanAgarwal041  Pushed the changes. Please review and let me know if it can be merged or not!

**Comment by devnamrits** [comment]
@AmanAgarwal041 Any update??

**Comment by rimildeyjsr** [comment]
@devnamrits - Hello! Thanks for your contribution to appsmith!

I was reviewing your changes and everything looks good, just one minor request - Could you align the logo and text properly? Both should be aligned centrally!

After you make this change, I will approve and push the PR forward to the next stage!

**Comment by AmanAgarwal041** [comment]
Hey @devnamrits , Sorry for the late reply. Here's a screenshot attached which specifies the difference between the JS Editor Page and API Editor Page 
Screenshot 2022-04-15 at 3 56 11 PM
Screenshot 2022-04-15 at 3 55 55 PM

Please update the difference.

**Comment by ohansFavour** [comment]
Hey @devnamrits, any update on this?

**Comment by ohansFavour** [comment]
@devnamrits thanks for your contribution to this. I will now merge to the `js-editor-name-inconsistencies` branch.

**Pull request merged**
