### PR TITLE
fix: ads-v2 fixes

### PR DESCRIPTION
**Pull request by tanvibhakta**
## Description

Notion Issues: 

1. Issues with link component: https://www.notion.so/appsmith/f353d8c6bd664f79ad858a42010cdfc8?v=f04cde23f6424aeb9d5a6e389cd172bd&p=4121a76714cb49f2ba76d20fbeab9766&pm=s
2. GraphQL code editor heading color: https://www.notion.so/appsmith/f353d8c6bd664f79ad858a42010cdfc8?v=f04cde23f6424aeb9d5a6e389cd172bd&p=82bbeaa2749642268eada28fcf5ec6a6&pm=s
3. tooltip on long JS Object names: https://www.notion.so/appsmith/f353d8c6bd664f79ad858a42010cdfc8?v=f04cde23f6424aeb9d5a6e389cd172bd&p=353552b086de45329390bd4dfae98ee4&pm=s
4. Multiple scroll bars on response tab: https://www.notion.so/appsmith/f353d8c6bd664f79ad858a42010cdfc8?v=f04cde23f6424aeb9d5a6e389cd172bd&p=111515d90ec5447687b1b573d64bd6eb&pm=s
5. Save and delete buttons: https://www.notion.so/appsmith/f353d8c6bd664f79ad858a42010cdfc8?v=f04cde23f6424aeb9d5a6e389cd172bd&p=1ac1fed293994b51b4c31bc44dd2d736&pm=s
6. Js Objects always on tooltip: https://www.notion.so/appsmith/f353d8c6bd664f79ad858a42010cdfc8?v=f04cde23f6424aeb9d5a6e389cd172bd&p=59f3e5b452d24ab9aa05e9fdd169113f&pm=s
7. Error message alignment: https://www.notion.so/appsmith/f353d8c6bd664f79ad858a42010cdfc8?v=f04cde23f6424aeb9d5a6e389cd172bd&p=a6f2cc4e79994b77894c0293d50be3b9&pm=s
8. Max width of field on Admin settings page: https://www.notion.so/appsmith/Text-boxes-too-small-in-Auth-Pages-ef2d0fb97f8247848113f9a419e3da09?pvs=4

Other issues:
1. Added data testid for branch create spinner.
7. Fix: branch name button have a fixed width even if text length is small.

#### Type of change
- Bug fix (non-breaking change which fixes an issue)

- [ ] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Comment by shadabbuchh** [comment]
1. Is partially verified on CE. Will need a EE PR to completely test it out.
2. Is fixed
3. Although we are now able to see a tooltip for longer function names, however the tooltips do not disappear when we move the cursor to select a different function:
https://www.loom.com/share/2d6832f323884189b213403de92a40f8

4. I am still able to see more than 1 scroll bar:
(this is in GSheets)
Screenshot 2023-05-23 at 2 11 55 PM

5. 

- Although the buttons are now visible, we see an additional divider at the bottom which does not let us view the options in Advanced settings without scrolling. This is a deviation from Prod.

- The Delete button is now renamed to Cancel. And on clicking it nothing happens.

https://www.loom.com/share/3ec29a0c2b0447f09de1f1b1675bbee3

**Comment by tanvibhakta** [comment]
5 is occuring due to @ayushpahwa 's change - could you please push a fix here?

**Comment by ayushpahwa** [comment]
This is as per the new design of multiple env. @parth-appsmith can add context here

**Review by ankitakinger — DISMISSED** [review]

**Comment by tanvibhakta** [comment]
1 - https://github.com/appsmithorg/appsmith-ee/pull/1508#issuecomment-1560479890 dp is available
3 - tooltip has been placed to the right to prevent overlap.
Screenshot 2023-05-24 at 11 49 16 AM
4 - scrollbar issue has been fixed

**Comment by shadabbuchh** [comment]
All issues apart from the below are fixed:
The `Cancel` button in Authenticated API &. GraphlQl is not working. Nothing happens when we click on it.
Screenshot 2023-05-24 at 2 37 04 PM

**Comment by ayushpahwa** [comment]
@shadabbuchh I can only replicate this when the datasource is in temp mode. Once saved and opened for editing, the cancel button works as expected. Previously the delete button was disabled in this state but the cancel behaviour needs to be different. This is not yet documented, I'll update you on the final decision with @parth-appsmith 
In the meantime, can you confirm if cancel is working normally on non-temp datasources? Thanks!

**Comment by shadabbuchh** [comment]
@ayushpahwa if by Non-Temp you mean checking the `Cancel` button in edit mode, then yes it is working.

**Comment by rohitagarwal88** [comment]
@ayushpahwa / @tanvibhakta : Callout should have spacing at the top
Screenshot 2023-05-25 at 7 48 46 PM

**Comment by shadabbuchh** [comment]
This PR has been tested below issues are reopened:
1. https://www.notion.so/appsmith/f353d8c6bd664f79ad858a42010cdfc8?v=f04cde23f6424aeb9d5a6e389cd172bd&p=981d15cae6af4b1d8530cf497090c3dc&pm=s
2. https://www.notion.so/appsmith/f353d8c6bd664f79ad858a42010cdfc8?v=f04cde23f6424aeb9d5a6e389cd172bd&p=0cdc147a619a430cbcfd113879a5f712&pm=s
3. https://www.notion.so/appsmith/f353d8c6bd664f79ad858a42010cdfc8?v=f04cde23f6424aeb9d5a6e389cd172bd&p=f52e3023ab544ac49e9ac2ebb28e71c3&pm=s

**Review by ankitakinger — APPROVED** [review]

**Pull request merged**
