### PR TITLE
test: replace routes with intercepts

### PR DESCRIPTION
**Pull request by NandanAnantharamu**
## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: test/interceptUpdate 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 55.69 **(0)** | 37.08 **(0)** | 35.25 **(0)** | 55.95 **(0.01)**
 :green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.94 **(0.23)** | 41.67 **(0.84)** | 36.21 **(0)** | 56.99 **(0.25)**</details>

### CODE REVIEW

**Review by yatinappsmith — APPROVED** [review]

**Review by yatinappsmith — APPROVED** [review]

**Review by yatinappsmith — APPROVED** [review]

**Review by yatinappsmith — DISMISSED** [review]

**Comment by NandanAnantharamu** [comment]
Old PR not relevant anymore

**Pull request closed without merging**
