### PR TITLE
chore: external merge request from Contributor

### PR DESCRIPTION
**Pull request by rahulbarwal**
## Description
Fixes #35734
> [!WARNING]
> _If no issue exists, please create an issue first, and check with the maintainers if the issue is valid._

## Automation

/ok-to-test tags="@tag.All"

### :mag: Cypress test results

> [!CAUTION]
> If you modify the content in this section, you are likely to disrupt the CI result for your PR.

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [x] No

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/10663820810>
> Commit: 442b11199614322b071652f1e47933f18c3afa78
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=10663820810&attempt=2" target="_blank">Cypress dashboard</a>.
> Tags: `@tag.All`
> Spec:
> <hr>Mon, 02 Sep 2024 10:12:29 UTC

### CODE REVIEW

**Review by znamenskii-ilia — APPROVED** [review]

**Comment by ALOK9442** [comment]
hey @rahulbarwal, i did the same changes and you also committed the same change, is it going to make any difference? just curios if yes then I would love to know about it

**Comment by rahulbarwal** [comment]
closing as no longer needed

**Comment by rahulbarwal** [comment]
Hey @ALOK9442 , 
This PR is just for running all the CI that does not run with your(external) PRs. Rest assured, once we have everything passing, we merge yours and close this one.

**Pull request closed without merging**
