### PR TITLE
fix: stopping list widget from copying onto another list widget

### LINKED ISSUE #13609: [Bug]: App crash on List widget when try copy/paste
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

[LOOM DEMO](https://www.loom.com/share/eda77e0771234aa992198df3c73406ed)

### Steps To Reproduce

1. Drag and drop a List widget
2. Copy list widget (CMD +C)
3. Move the cursor on the container
4. Pate it (CMZ+V)
5. Observe the app crash

### Public Sample App

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by rahulramesha**
## Description

This is a fix to stop list widget from becoming a parent or grand parent of any other list widget

Fixes #13609 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Manual, jest and cypress

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: copyPasteListWidgetFix 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 56.58 **(0.02)** | 38.36 **(0.03)** | 35.84 **(0)** | 56.82 **(0.01)**
 :red_circle: | app/client/src/sagas/WidgetOperationSagas.tsx | 61.9 **(0)** | 51.07 **(-0.18)** | 61.54 **(0)** | 63.75 **(0)**
 :green_circle: | app/client/src/sagas/WidgetOperationUtils.ts | 71.4 **(2.32)** | 51.1 **(4.43)** | 68.06 **(0.45)** | 71.18 **(2.41)**
 :red_circle: | app/client/src/utils/WorkerUtil.ts | 89.76 **(0)** | 70.59 **(-1.96)** | 100 **(0)** | 93.33 **(0)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.71 **(-0.23)** | 40.83 **(-0.84)** | 36.21 **(0)** | 56.74 **(-0.25)**</details>

### CODE REVIEW

**Review by sbalaji1192 — DISMISSED** [review]

**Comment by vivekverma2312** [comment]
@rahulramesha Can you please fix the merge conflict in the PR.

**Comment by rahulramesha** [comment]
@vivekverma2312, resolved the conflict. Please proceed with testing.

**Comment by vivekverma2312** [comment]
@rahulramesha Tested and it's working fine now.

**Review by sbalaji1192 — APPROVED** [review]

**Pull request merged**
