### PR TITLE
fix: adjust spacing for filter/sort/pagination form controls

### LINKED ISSUE #37198: [AR] Incorrect pagination & sorting gaps

### PR DESCRIPTION
**Pull request by alex-golovanov**
## Description
Adjusted spacing to match design values for filter/sort/pagination form controls.

Fixes #37198

## Automation

/ok-to-test tags="@tag.IDE"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/11699699613>
> Commit: cb18e1e71d992a6f77eee1a133eb4df6fab86da0
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=11699699613&attempt=1" target="_blank">Cypress dashboard</a>.
> Tags: `@tag.IDE`
> Spec:
> <hr>Wed, 06 Nov 2024 08:54:32 UTC

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [x] No

## Release Notes

- **New Features**
	- Enhanced layout responsiveness for the `Zone`, `Pagination`, `Sorting`, and `Where Clause` components.
	- Improved clarity and usability of pagination feature in the Google Sheets plugin.

- **Bug Fixes**
	- Corrected a typo in the `WhereClauseControl` component function name.

- **Style**
	- Updated CSS for various components to use CSS variables for consistent spacing.
	- Removed hardcoded widths for improved flexibility in form controls.
	- Added border-radius and adjusted padding for the `SecondaryBox` component.
	- Streamlined rendering logic for form configuration elements.

- **Refactor**
	- Minor refactoring of function names and properties for better clarity and maintainability.

### CODE REVIEW

**Comment by ankitakinger** [comment]
Hey @alex-golovanov,
Can you make these 2 minor changes as well? This will make sure to remove the empty space above pagination field in google sheets:
Screenshot 2024-11-05 at 11 25 52 PM

**Comment by alex-golovanov** [comment]
> Hey @alex-golovanov, Can you make these 2 minor changes as well? This will make sure to remove the empty space above pagination field in google sheets: Screenshot 2024-11-05 at 11 25 52 PM

Yep, sure thing

**Review by ankitakinger — APPROVED** [review]
LGTM

**Pull request merged**
