### PR TITLE
fix: Bindings on API and Query panes are not tracked via ENTITY_BINDING_SUCCESS

### LINKED ISSUE #22125: [Bug]: Bindings on API and Query panes are not tracked via ENTITY_BINDING_SUCCESS
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I add a binding on an API or Query, I don't see it being tracked as a part of the ENTITY_BINDING_SUCCESS event

### Steps To Reproduce

Add any binding using {{ }} on an API or Query. Notice that the action is not being tracked.  

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by Druthi**
## Description
Bindings on API and Query panes are not tracked via ENTITY_BINDING_SUCCESS

Fixes #22125 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manual

### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [x] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by ApekshaBhosale — APPROVED** [review]

**Comment by ramsaptami** [comment]
Skipping QA since changes since this is event changes
cc: @Druthi

**Pull request merged**
