### PR TITLE
feat: file structure v2 for actions

### PR DESCRIPTION
**Pull request by AnaghHegde**
## Description

> Ignore the body field while committing the JS Object related actions to git repo.

Fixes https://github.com/appsmithorg/appsmith/issues/20550
https://github.com/appsmithorg/appsmith/issues/19546

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Manual
- JUnit

### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by nayan-rafiq — APPROVED** [review]

**Review by nayan-rafiq — DISMISSED** [review]

**Comment by Parthvi12** [comment]
@AnaghHegde On importing application with actions, for queries and api, the older json files are not getting deleted on committing, could you please check?
Screenshot 2023-02-27 at 4 04 03 PM

**Comment by Parthvi12** [comment]
Tested and verified the changes, looks good to me.

**Pull request merged**
