### PR TITLE
Fix: Do not allow for spaces inside create applications form.

### PR DESCRIPTION
**Pull request by jyash97**
### Current Behavior: 

We can submit an empty application in the Create application form, though BE gives an error it is better to do a client validation instead of waiting for API response to give an error.

### New Behavior:

https://www.loom.com/share/11db2d803aa94158a39e3ae23d3eb559

### CODE REVIEW

**Comment by satbir121** [comment]
@jyash97 Can you please link the issue this fixes?

**Comment by jyash97** [comment]
Hey @satbir121 I could not find an existing issue for these. There is one issue for adding validation in editing the name which is already assigned so I havent added that. Link for the issue: #817

**Comment by hetunandu** [comment]
Hey @jyash97 we had an issue with our CI runs which did not run the tests properly. Can you rebase/merge the latest release branch into your branch to fix this?

**Comment by jyash97** [comment]
Hey @hetunandu 

Sure thing will update the branch in sometime. 👍🏼

**Comment by jyash97** [comment]
@hetunandu updated the PR

**Review by Nikhil-Nandagopal — APPROVED** [review]

**Pull request merged**
