### PR TITLE
chore: move settings pane to the left

### PR DESCRIPTION
**Pull request by akash-codemonk**
## Description

Show settings pane on the left in place of explorer. This will be later in a sidepane. 

Fixes https://github.com/appsmithorg/appsmith/issues/27955

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
- [ ] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Comment by kavitasmoolya** [comment]
@akash-codemonk 
With feature flag = off, performed sanity test around below areas on [DP](https://ce-28002.dp.appsmith.com/)

- Setting pane opens on right as same behavior on prod
- Setting pane access when side bar or entity expands and collapses
- Setting pane access on git connected app (master and child branch)
- Setting pane access on different apps in different workspaces
- Explorer behavior that it is visible appropriately as same on prod

Looks good to me

**Review by hetunandu — APPROVED** [review]

**Pull request merged**
