### PR TITLE
fix: Icon-dropdown overlap in button properties

### LINKED ISSUE #7575: [Bug] Icon dropdown of Button widget is overlapped by button radius on the property pane
## Description
Border radius property of the Button widget overlaps Icon dropdown 

### Steps to reproduce the behaviour:
1. Drag and drop a button widget on the canvas and go to the property pane.
2. Click on the icon dropdown and observe the overlap

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Release

image

### PR DESCRIPTION
**Pull request by nishihere19**
## Description

The border radius property of the Button widget overlaps the Icon dropdown. A small change in the padding in CSS of the input bar in the icon dropdown can be used to fix it.

Fixes #7575

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

NA

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

Final result.
icondropdown

### CODE REVIEW

**Comment by nishihere19** [comment]
Do let me know if any other changes are to be done. The suggestions were of great help and documentation in the project is really good which helped me in setting up the project smoothly.

**Comment by ohansFavour** [comment]
Hi @nishihere19, thanks for contributing :star_struck: . The Semantic Pull Request check is failing, this check ensures that PR titles are semantic and consistent. You have to add one of the prefixes listed [here](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json)  (without the square brackets). 
Kindly rename this PR, thank you.

**Comment by nishihere19** [comment]
Sure, will do.

**Comment by areyabhishek** [comment]
Thanks @nishihere19! I've tested the DP and it looks good to me. @ohansFavour Please review the code and let's merge this if things look good.

**Comment by jsartisan** [comment]
@nishihere19 The padding bottom I suggested is creating issues in other controls. Can you find a way to fix this?

image
image

**Comment by nishihere19** [comment]
Sure, I didn't notice this. Will find an alternative and fix this properly.

**Comment by jsartisan** [comment]
Closing this as there is no activity.

**Comment by nishihere19** [comment]
Hi @jsartisan, I tried a lot to find a way to detect if the menu is for icon controls and apply CSS accordingly but couldn't find one. Could you guide me a little and tell me if there is any way to pass on the props in the IconSelectContainerStyles such that it checks for icon-controls and applies the padding?

**Comment by jsartisan** [comment]
Looks great. For some reason, the icon alignment is distorted. Can you check?

**Comment by jsartisan** [comment]
this looks good to me.

@somangshu can we merge this in as well?

**Review by jsartisan — APPROVED** [review]

**Comment by nishihere19** [comment]
Hi, I wanted to know if this PR will be considered for hacktoberfest.

**Comment by mohanarpit** [comment]
Test result: https://github.com/appsmithorg/appsmith/runs/4152661366

**Comment by mohanarpit** [comment]
> Hi, I wanted to know if this PR will be considered for hacktoberfest.

Yes. This will be considered as part of Hacktoberfest as well.

**Comment by somangshu** [comment]
@jsartisan just a reminder that you need to take this PR ahead!

**Comment by jsartisan** [comment]
Closing as it will get fixed in #9714

**Pull request closed without merging**
