### PR TITLE
feat: Make Action Selector keyboard accessible

### LINKED ISSUE #9920: [Task]: Make action selector keyboard accessible
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

_No response_

### PR DESCRIPTION
**Pull request by aswathkk**
## Description

`Tab` to focus the dropdown.
`Enter` `Space` key to open the dropdown
`ArrowUp` `ArrowDown` keys to navigate
`Enter` or `Space` to select option
`Enter` or `Space` or `ArrowRight` to open sub menu
`ArrowLeft` to close sub menu

Fixes #9920

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Manually tested and jest test is available

## Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: feat/keyboard-accessible-action-selector 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 55.24 **(0.15)** | 37.16 **(0.28)** | 35.22 **(0.21)** | 55.73 **(0.16)**
 :green_circle: | app/client/src/components/ads/TreeDropdown.tsx | 95.57 **(36.31)** | 77.31 **(18.49)** | 97.37 **(60.53)** | 96.79 **(39.1)**
 :green_circle: | app/client/src/selectors/commentsSelectors.ts | 85.25 **(1.64)** | 64.71 **(2.95)** | 73.33 **(0)** | 90.59 **(2.35)**</details>

### CODE REVIEW

**Review by SatishGandham — CHANGES_REQUESTED** [review]
- Please add the double brackets for the if conditions, though your style in concise, it easy for someone working on the code later to introduce bugs.
- Is the menu item re rendering taken care?

**Review by SatishGandham — APPROVED** [review]

**Comment by vivekverma2312** [comment]
@aswathkk 
1. When we open the action selector using up/down arrow key and try to selection options it jumps and not move in sequence.
https://www.loom.com/share/3f807ced70f04aa0be74b3330e206d13

2. This is bit confusing for me. As the sub menu option open on the left of the menu I always try to go back by using the right arrow key but actually left arrow key works here.
https://www.loom.com/share/20a1ff2115e44caaa2f880177eaaabc9

3. Scrolling using up/down arrow key the drop-down options flicker
https://www.loom.com/share/d83f26eab33d4f0c89fca8b69f903019

**Comment by vivekverma2312** [comment]
@aswathkk Tested and looks good.

**Pull request merged**
