### PR TITLE
fix: changed download flow for image control

### LINKED ISSUE #10753: [Bug]: Unable to download file from Image widget when file uploaded from local device
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The image uploaded via local device is not getting downloaded but redirecting the link to new tab and nothing happens there

[LOOM DEMO](https://www.loom.com/share/d0dc87174f814407ba36a1a39c1e30fb)

### Steps To Reproduce

1. Add Image widget to canvas
2. Add File picker widget to canvas and bind it with image widget {{FilePicker1.files[0].data}}
3. Upload any files from your device using File Picker widget
4. Enable download option from property pane of Image Widget
5. Try to download the image you have uploaded

### Environment

Release

### Version

Cloud

### LINKED ISSUE #10931: [Bug]: Unable to download file from image widget
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Adding a url to image widget is displaying the image but downloading the same file is not working on release

image

[LOOM DEMO](https://www.loom.com/share/0b425dd8c9bf43458e0d5cfa3b0fe443)

### Steps To Reproduce

1. Add image widget
2. Add image url to the widget to dispaly the same image
3. Enable download option
4. Try downloading the image

### Environment

Release

### Version

Cloud

### PR DESCRIPTION
**Pull request by techbhavin**
## Description

> In Image widget download option improve  image download feature to add download props in `a`  elements

Fixes #10753
Fixes #10931

## Type of change

- Bugfix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: bug/image-handle-local-download 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 55.76 **(0.04)** | 37.05 **(0.01)** | 35.8 **(0.01)** | 56.12 **(0.04)**
 :green_circle: | app/client/src/selectors/commentsSelectors.ts | 85.25 **(1.64)** | 64.71 **(2.95)** | 73.33 **(0)** | 90.59 **(2.35)**
 :green_circle: | app/client/src/utils/WorkerUtil.ts | 89.76 **(0.78)** | 70.59 **(0)** | 100 **(0)** | 93.33 **(0.95)**
 :green_circle: | app/client/src/widgets/ImageWidget/component/index.tsx | 19.35 **(4.72)** | 14.81 **(0.69)** | 9.52 **(1.19)** | 21.79 **(5.6)**</details>

### CODE REVIEW

**Review by Tooluloope — APPROVED** [review]
LGTM
@techbhavin could you add cypress Tests for this change

**Comment by chandannkumar** [comment]
Tested this PR and working as expected

**Review by Tooluloope — APPROVED** [review]

**Pull request merged**
