### PR TITLE
feat: Updating invite modal & app settings for SSO embedding to introduce private app embedding

### PR DESCRIPTION
**Pull request by ankitakinger**
## Description

Updating invite modal and app settings for SSO embedding to introduce upgrade content for private apps. This is being done to introduce private embedding SSO in invite modal and app settings for Business Edition.

Fixes [#20578](https://github.com/appsmithorg/appsmith/issues/20578)

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
- Manual
- Cypress

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by berzerkeer — APPROVED** [review]

**Review by berzerkeer — APPROVED** [review]

**Review by dipyamanbiswas07 — DISMISSED** [review]

**Review by berzerkeer — APPROVED** [review]
Left a few comments , nit picks.

**Pull request merged**
