### PR TITLE
fix: empty query response on page load issue fixed

### LINKED ISSUE #28287: [Bug]: Query response not shown even when we can see the data in widget
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we bind a query returning data successfully to a widget, on page load, we can see the data in widget, but when we go to query editor, response tab is empty

For more information - [thread](https://theappsmith.slack.com/archives/C040LHZN03V/p1697720357230469)

### Steps To Reproduce

1. Create a datasource and a query on it
2. Execute the query
3. Bind query to a list or table widget
4. Reload the page
5. Observe that data is there in the widget
6. But on query page, response tab is empty

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

Cloud/ Self-Hosted - 1.9.42

### PR DESCRIPTION
**Pull request by sneha122**
## Description

When we bind a successfully running query to a widget, the query gets executed on page load, so in such a case, we were able to see the query in the widget, but when visiting query editor, response tab is empty. This PR fixes that issue.

Screenshot 2023-10-23 at 3 35 50 PM

**Root Cause:**
In order to see the response in the response tab, we need to have action config, execute API response and responseDisplayFormat to be present. responseDisplayFormat denotes whether to show response in Table, Json or Raw format.
This responseDisplayFormat gets set in `setDefaultActionDisplayFormat` method. This property is set on action config object itself. This method is called from execute `executePluginActionSaga` and `executePluginActionSaga` is called from `executePageLoadAction`, so the flow of actions looks as below:

- `executePageLoadAction`
      - `executePluginActionSaga`
              - `setDefaultActionDisplayFormat`

Once the responseDisplayFormat was set, `executePageLoadAction` was again resetting the action config object in the redux store, thus removing this responseDisplayFormat property and hence empty response tab.

**Note: This bug is not a regression, it has existed from a long time.**

#### PR fixes following issue(s)
Fixes #28287 
#### Type of change
- Bug fix (non-breaking change which fixes an issue)
>
>
>
- [x] Manual
- [ ] JUnit
- [ ] Jest
- [x] Cypress
>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by AmanAgarwal041 — APPROVED** [review]

**Comment by chandannkumar** [comment]
Tested this PR and LGTM

**Pull request merged**
