### PR TITLE
fix: Update datasource deletion message for clarity

### LINKED ISSUE #34604: [Bug]: datasource deletion refers to "action(s)", which is meaningless to the user
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Try deleting a datasource that has some queries on top of it. The error says: `Cannot delete datasource since it has 1 action(s) using it`

The word "action" is internal to the codebase, and means nothing to the user. Ideally, the error should be `Cannot delete datasource since it has 1 query using it`

There are two problems with the error message:
1. `action` should change to `query`
2. the error should be intelligent to know between `query`(in case there is only 1) and `queries` (in case > 1)

### Steps To Reproduce

1. create any datasource
2. create a query on top of it
3. go back and try to delete the datasource
4. see the error toast

### Public Sample App

_No response_

### Environment

Production

### Severity

Low (Cosmetic UI issues)

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by AnnaHariprasad5123**
Fixes #34604 

Hi @nidhi-nair , 

**Screenshots :**
**Earlier :**
image
**After update the error message :**
image
image

## Summary by CodeRabbit

- **Bug Fixes**
  - Updated error messages during datasource deletion to improve clarity: "Cannot delete datasource since it has 1 query using it."

- **Tests**
  - Adjusted test cases to reflect updated error messages and ensure accurate verification.

- **Documentation**
  - Improved error message documentation for better user understanding during datasource deletions.

### CODE REVIEW

**Comment by NilanshBansal** [comment]
@AnnaHariprasad5123 thanks for your contribution! 
There is one server unit test [(deleteDatasourceWithActions)](https://github.com/appsmithorg/appsmith/pull/34863#issuecomment-2222273679) failing in this PR, can you please check. 

We might need to add the second parameter "query" also in the error message [here](https://github.com/appsmithorg/appsmith/blob/b8f161c0e7691fcf357682a28107e8bd7f27d6ff/app/server/appsmith-server/src/test/java/com/appsmith/server/services/DatasourceServiceTest.java#L944)

**Comment by NilanshBansal** [comment]
Other than this [failing test](https://github.com/appsmithorg/appsmith/pull/34822#issuecomment-2222306900), rest changes LGTM.

**Comment by AnnaHariprasad5123** [comment]
Hi @NilanshBansal , Could you check once.

**Comment by NilanshBansal** [comment]
@AnnaHariprasad5123 there are a large number of cypress test case failures due to this assertion. 
https://github.com/appsmithorg/appsmith/blob/c48aaaccd45d8cb4822325d1473e98cb8133a9e4/app/client/cypress/support/Pages/DataSources.ts#L887

Can you change this assertion to "Cannot delete datasource"

**Comment by AnnaHariprasad5123** [comment]
> @AnnaHariprasad5123 there are a large number of cypress test case failures due to this assertion.
> 
> https://github.com/appsmithorg/appsmith/blob/c48aaaccd45d8cb4822325d1473e98cb8133a9e4/app/client/cypress/support/Pages/DataSources.ts#L887
> 
> Can you change this assertion to "Cannot delete datasource" cc: @sneha122 @AmanAgarwal041

Done

**Comment by NilanshBansal** [comment]
The testing on the following has been done. The PR is ready to be merged! 
- [x] Code Review
- [x] DP Testing
- [x] Test Suite 

Thanks @AnnaHariprasad5123 for your contribution! Looking forward to more such PRs from you!

**Review by NilanshBansal — APPROVED** [review]

**Pull request merged**
