### PR TITLE
chore: Miscellaneous one click binding updates

### PR DESCRIPTION
**Pull request by sbalaji1192**
## Description
- Remove the primary column from the insert and update queries.
- Save/Discard button isSaveDisabled and isDiscardDisabled properties should be in js mode.
- Don't create insert and update query if datasource is read only

#### PR fixes following issue(s)
Fixes https://github.com/appsmithorg/appsmith/issues/24858

#### Type of change

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
>
>
>
- [x] Manual
- [ ] Jest
- [x] Cypress
>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by ayushpahwa — APPROVED** [review]

**Comment by kamakshibhat-appsmith** [comment]
The first time you connect datasource via one-click binding , the insert/update queries are not created even though the database is read/write https://www.loom.com/share/757a421f559e4839bc4fc91b39652bb3 @sbalaji1192

**Comment by sbalaji1192** [comment]
@kamakshibhat-appsmith Fixed the above issue and triggered a new DP. please check

**Comment by kamakshibhat-appsmith** [comment]
On toggling the JS mode in Query Data field, the page load property of the query switches from On to off
https://www.loom.com/share/ac6ca87b12d24ff08a62c9fd1080e7f8
@sbalaji1192

**Review by berzerkeer — APPROVED** [review]

**Review by berzerkeer — APPROVED** [review]

**Pull request merged**
