### PR TITLE
fix: Re-selecting dropdown value triggers evaluation cycle

### LINKED ISSUE #15625: [Bug]: Reselecting values from dropdown control in Property pane should not update the property
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Reselecting the selected value from the dropdown control in the property pane results in an unnecessary update Property call which leads to the app getting saved and a subsequent evaluations cycle.
We should not call update property in such cases.

### Steps To Reproduce

1. D&D a widget with a dropdown control in the property pane
2. click on the selected option from the dropdown control.
3. notice that the application gets saved. (it should also trigger an evaluation cycle).

### Public Sample App

_No response_

### Version

cloud

### PR DESCRIPTION
**Pull request by aswathkk**
## Description

Reselecting the selected value from the dropdown control in the property pane results in an unnecessary update Property call which leads to the app getting saved and a subsequent evaluations cycle

Fixes #15625

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by yaldram — DISMISSED** [review]

**Comment by Sripriya93** [comment]
List of dropdown properties for several widgets which are still showing the evaluation trigger are shared with @aswathkk. Moving to In progress.

**Review by yaldram — APPROVED** [review]

**Comment by Sripriya93** [comment]
Still could find few widgets showing the evaluation trigger shared it with @aswathkk , moving to In progress.

**Review by yaldram — APPROVED** [review]

**Comment by Sripriya93** [comment]
Working fine, moving to done. Have checked all the widgets with dropdown property.

**Review by riodeuno — APPROVED** [review]

**Review by yaldram — APPROVED** [review]

**Pull request merged**
