### PR TITLE
fix: date picker uniformity when only Month or year is changed

### LINKED ISSUE #11057: [Bug]:  Date picker should not update till a user selects a date
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

**Feature Requirement Proposal**
For the Datepicker Widget, we have one action "onDateSelected".
We may need "onMonthSelected" and "onYearSelected" as there are issues in certain scenarios

This requirement is based on a issue faced by a Discord user
https://discordapp.com/channels/725602949748752515/940981446338809886

**Feature Requirement Summary :**
---Not Finalised --

 

### Why should this be worked on?

The need happens when we want to display the selected date in another place.

**Part A**
(1) User Displays the selected date in a label/textfield using the 'onDateSelected" action script.
(2) User navigates to the next month and selects somewhere outside, the month gets changed in the datePicker.
(2.1) The date in the label/textfield remains unchanged, so a mismatch is occurring
(3) Similarly when Year is changed the mismatch between the datepicker date and the display date in a label/textfield occurs.

Considering the above scenario we need the implementation.

Alternatively
**Part B**
(1) To make mandatory to select the modal calendar, else the calendar may not disappear.
(2) Do not change the Month or Year in the datepicker unless a date is selected.

TODO :
To decide which option are feasible and we could go ahead (Part A or Part B or a combination). 
To write down the conclusion in the "Feature Requirement Summary" above.

### PR DESCRIPTION
**Pull request by Tooluloope**
## Description

Date picker values get changed when month and year and changed without selecting a date but `Datepicker.selectedDate` keeps the previous value since no date was selected

Fixes #11057

## Type of change

> Please delete options that are not relevant.

- Bugfix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Cypress test

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/datepicker-selected-value-not-uniform 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 55.77 **(-0.01)** | 37.09 **(-0.01)** | 35.82 **(0)** | 56.13 **(0)**
 :red_circle: | app/client/src/components/ads/Dropdown.tsx | 80.93 **(-1.28)** | 61.09 **(-0.76)** | 69.44 **(0)** | 79.66 **(-1.37)**
 :green_circle: | app/client/src/utils/WorkerUtil.ts | 89.76 **(0.78)** | 72.55 **(1.96)** | 100 **(0)** | 93.33 **(0.95)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.71 **(-0.23)** | 40.83 **(-0.84)** | 36.21 **(0)** | 56.74 **(-0.25)**</details>

### CODE REVIEW

**Comment by ashit-rath** [comment]
@Tooluloope Could you improve the PR title? Right now it might cause misunderstanding while creating release notes.

**Review by ashit-rath — APPROVED** [review]

**Comment by YogeshJayaseelan** [comment]
@Tooluloope Tested this PR and now irrespective of selecting month and year the selection will reflect on the text/input widget only on selecting any of the days. Working as expected now and we can proceed further

**Comment by somangshu** [comment]
@Tooluloope please focus on better PR descriptions. You need to fill out the checklist by the end, and also fill out the rest of the details properly. 

@ashit-rath you should also keep that in mind for the future.

**Pull request merged**
