### PR TITLE
feat: migrate SearchSnippet

### LINKED ISSUE #16884: Migrate SnippetButton

### PR DESCRIPTION
**Pull request by tanvibhakta**
## Description

This PR migrates the SearchSnippet component into the ads, and leaves the redux responsibilities with the parent. Closes #16884 

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Tested locally 

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by shadabbuchh** [comment]
This PR has been tested and no issues have been found.

**Review by albinAppsmith — APPROVED** [review]

**Pull request merged**
