### PR TITLE
fix: Bugfix for curl import in the child branch when application is connected to git

### LINKED ISSUE #10637: [Bug]: Curl import fails for the sub-branch application
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When user connects the app to git and tries to import the curl this works fine for default branched application but fails when tries to import the same curl in sub-branch app.

### Steps To Reproduce

1. Connect app to git
2. You will get the default branched application
3. Import the curl works as expected
4. Create a new branch from the base/default branch
5. Try to import the curl

### Environment

Release

### Version

Cloud

### PR DESCRIPTION
**Pull request by abhvsn**
## Description

> When the application is connected to git and user tries to import a curl it's working fine for default branched application but fails if user creates a sub-branch from the default branch and then tries to import the curl.

Fixes #10637

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Junit TC
> Manual test

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by AnaghHegde** [comment]
@abhvsn Can you please elaborate on why we are removing the `id` and just using the page name?

**Review by AnaghHegde — APPROVED** [review]

**Comment by abhvsn** [comment]
> @abhvsn Can you please elaborate on why we are removing the `id` and just using the page name?

We are not removing the `pageId` but setting this after we have the branched page id from where the request has been made

**Comment by AnaghHegde** [comment]
So the page details are stored underCollection which is what is used depending on the view mode. Is that correct assumption ?

**Pull request merged**
