### PR TITLE
fix: Remove not found error in get snapshot API

### LINKED ISSUE #24786: [Bug]: Snapshot not found error in the log always
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we open an application, we see a not found error in the log. This is logged for all the applications when there is no snapshot created. As most of the applications do not have a snapshot, this error is there for almost all applications.

### Steps To Reproduce

1. Open an application which does not have a snapshot
2. Check the server log

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

cloud

### PR DESCRIPTION
**Pull request by nayan-rafiq**
## Description
This PR stops writing 404 error on log when snapshot is not found in the get snapshot API.

#### PR fixes following issue(s)
Fixes #24786

#### Type of change
- Bug fix (non-breaking change which fixes an issue)

#### How Has This Been Tested?
- [x] Manual
- [x] Jest
- [ ] Cypress

#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by NilanshBansal — CHANGES_REQUESTED** [review]
@nayan-rafiq Can we write any tests to assert that 404 error is not coming now?

**Comment by nayan-rafiq** [comment]
@NilanshBansal I've added test. Would you please review once again?

**Review by NilanshBansal — APPROVED** [review]
LGTM

**Pull request merged**
