### PR TITLE
fix: widget field validation

### LINKED ISSUE #14895: [Bug]-[28000]:Binding shows successful even for invalid JS
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Writing invalid code shows a successful state all across the editor

### Steps To Reproduce

1. Drag a table widget
2. Drag a Select widget
3. Bind {{Table1.test}} in the options field
4. See that it shows success
5. Add a JSObject and add the same invalid code in a function and notice it does not show an error

### Public Sample App

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by arunvjn**
## Description
Show validation error, when a field that accepts values of type'x' has bindings, but not the ones that evaluate to a value of type 'x'.

Fixes #14895 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- **Test plan**
- [ ]  https://github.com/appsmithorg/TestSmith/issues/1997

- Cypress

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by ohansFavour — DISMISSED** [review]

**Comment by ramsaptami** [comment]
Invalid bindings like: `Table1.test` does not show any error

**Comment by ramsaptami** [comment]
- [ ] Incorrect error handling even though datatype of Table.searchText is string on any string type widget fields
image

- [ ] No error displayed when there's no function present in an action field
image

**Pull request closed without merging**
