### PR TITLE
chore: Page name validation closer to file name validation

### PR DESCRIPTION
**Pull request by sharat87**
1. Introducing a custom validation annotation, `@FileName` to be used on fields that are used as file/folder names as part of the product.

2. Updated the validation logic to only accept valid file names on Linux, macOS as well as on Windows.

/ok-to-test tags="@tag.Settings, @tag.IDE"

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/8784587443>
> Commit: a13f700d490845a9d3c53d0da9c1a763fde6be9b
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=8784587443&attempt=1" target="_blank">Click here!</a>

## Summary by CodeRabbit

- **New Features**
	- Enhanced page name validation to include more special characters and reserved names, ensuring compatibility and preventing errors.

- **Bug Fixes**
	- Updated regular expression for replacing disallowed characters in page names to improve system stability and user experience.

- **Tests**
	- Expanded testing for invalid page names to cover a broader range of scenarios, enhancing reliability.

### CODE REVIEW

**Review by mohanarpit — APPROVED** [review]

**Review by hetunandu — COMMENTED** [review]
I changed the test tags and some are failing. Can you verify if they are related to your change?

**Comment by sharat87** [comment]
This is very wierd. One test passes locally, and the other `Pages_spec.js` fails locally, but I've no idea why. It fails to find the page name element, but... it's right there. The selector is working fine when I run it in the browser, yet Cypress can't find it. 😞

**Comment by hetunandu** [comment]
In the `Page_Load_Spec.js`, I see this error when trying to hide the name. This seems like a problem which causes the test to fail. If it passes locally, can you confirm if the CI and local are running against the same server code?

Screenshot 2024-04-22 at 7 44 38 AM

**Comment by sharat87** [comment]
Yep, looks like hiding/unhiding works in the DP as well. That's what's been confusing me. 🤔

**Review by hetunandu — APPROVED** [review]

**Pull request merged**
