### PR TITLE
feat: design updates as per figma for checkbox and radio button widget

### LINKED ISSUE #8310: [Bug] Widget design audit: checkbox / checkbox group / radio group Widget
## Description

This is to make cosmetic changes to the checkbox / checkbox group / radio group widget based on the changes after the design audit. Here we are covering:

- [ ] Text size and colors changed (for selected and not selected)
- [ ] Added hover state
- [ ] Checkbox shape changed
- [ ] Added new icon
- [ ] Increasing the height of the input box (36px).
- [ ] The whole input should take 4 rows in height.
- [ ] Dropped width to be changed to 20.

## Developer handoff file:
https://www.figma.com/file/w9CaXHF5iYcrLtiEbAHcFu/Original-Theme-Widgets-Library?node-id=574%3A5217

### PR DESCRIPTION
**Pull request by techbhavin**
## Description

> change design checkbox, checkbox group, radio group widget

Fixes #8310 

## Type of change

- design change (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: bug/design-audit-check-checkgrp-radiogrp 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 54.78 **(0.02)** | 36.64 **(0.02)** | 33.5 **(0.03)** | 55.31 **(0.01)**
 :green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.26 **(0.22)** | 41.25 **(0.83)** | 34.48 **(0)** | 56.22 **(0.26)**
 :green_circle: | app/client/src/widgets/CheckboxGroupWidget/component/index.tsx | 46.67 **(3.81)** | 13.33 **(0)** | 0 **(0)** | 53.85 **(3.85)**
 :green_circle: | app/client/src/widgets/CheckboxWidget/component/index.tsx | 96.55 **(2.11)** | 64 **(-9.33)** | 90 **(10)** | 95.83 **(2.5)**
 :green_circle: | app/client/src/widgets/RadioGroupWidget/component/index.tsx | 68.42 **(1.75)** | 30.77 **(0)** | 25 **(0)** | 75 **(1.67)**</details>

### CODE REVIEW

**Comment by techbhavin** [comment]
Issue 1: When the checkbox is invalid the error CSS overrides hover states.

point 1: This was not the scope of current PR. I have followed design audit points only
point 2: Checkbox new icon taken from Figma, radio icon is same
point 3: it means setting the height of the input type checkbox or radio as 36px

@shwetha-ramesh

**Comment by somangshu** [comment]
@techbhavin merge latest release and update run the test suite

**Comment by techbhavin** [comment]
https://github.com/appsmithorg/appsmith/actions/runs/1410895701

**Comment by techbhavin** [comment]
https://github.com/appsmithorg/appsmith/actions/runs/1439079632

**Comment by techbhavin** [comment]
https://github.com/appsmithorg/appsmith/actions/runs/1442824817

**Comment by sbalaji1192** [comment]
https://github.com/appsmithorg/appsmith/actions/runs/1449744109

**Pull request merged**
