### PR TITLE
feat: Add a read only mode to rating widget

### LINKED ISSUE #17141: [Feature]: Add a read only mode to rating
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Add a new read only mode to ratings. 

Pptions:
1. Add a switch called read only and migrate all the disabled values to read only instead. Doing this means we have to handle the case where when both read only and disabled are set to ON we default to disabled.
2. Add a state button group which has editable, read only and disabled as options, but this will create a new version.

### Why should this be worked on?

This is frustrating for our users because there is now a changed behavior on all rating widgets where it was working as read only did previously but now it's disabled.

### PR DESCRIPTION
**Pull request by jsartisan**
Add readonly property to rating widget

Fixes #17141 

> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change
- New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by dhruvikn — DISMISSED** [review]

**Comment by laveena-en** [comment]
@jsartisan Can we please add a tooltip on hover when `read only` is enabled? 
image

**Comment by laveena-en** [comment]
Tested and verified for:
- migration with older apps/widgets
- functionality of `read only` mode
- associated JS toggle
- behaviour in edit and view mode

**Review by dhruvikn — DISMISSED** [review]

**Review by dhruvikn — APPROVED** [review]

**Pull request merged**
