### PR TITLE
fix: Application name does not show up sometimes

### LINKED ISSUE #25457: [Bug]: The application name tends to disappear on page reload.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The application name tends to disappear on multiple page reloads. No specific pattern . Just keep on refreshing edit mode couple of time and the issue appears

### Steps To Reproduce

1. Do a page refresh in edit mode multiple times

https://www.loom.com/share/7ad77c6335614eaabe8a06106065ffe2

### Public Sample App

_No response_

### Environment

Release

### Issue video log

_No response_

### Version

Cloud/Release

### PR DESCRIPTION
**Pull request by hetunandu**
## Description
We noticed that empty applications sometimes do not show the application name. This was caused by a style issue where the height of the component was defaulted to 1px even if the name actually exists in the component. To fix this, we are forcing the styles to always be set to the header height. 
Also refactored the Editor header component a bit.

#### PR fixes following issue(s)
Fixes #25457

#### Type of change

- Bug fix (non-breaking change which fixes an issue)

- [ ] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by akash-codemonk — APPROVED** [review]

**Comment by Aishwarya-U-R** [comment]
@hetunandu - When will this PR be merged? We see 2 specs - `OtherUIFeatures/ApplicationURL_spec.js `& `Git/ExistingApps/v1.9.24/DSCrudAndBindings_Spec.ts` being so flaky in CI due to this.

**Comment by kamakshibhat-appsmith** [comment]
@hetunandu  The hamburger icon for collapsing the side bar is broken https://www.loom.com/share/51227b52f6c34f9b903225f53dd2e71a

**Comment by hetunandu** [comment]
@kamakshibhat-appsmith this looks like a signposting / onboarding issue. Once you complete signposting, you will start seeing the hamburger menu cc @akash-codemonk

**Comment by akash-codemonk** [comment]
> https://www.loom.com/share/51227b52f6c34f9b903225f53dd2e71a

@hetunandu @kamakshibhat-appsmith Are you talking about the hamburger menu not being visible when signposting is on? That is expected behaviour. It will be visible once signposting is completed. This has been implemented as part of the issue https://github.com/appsmithorg/appsmith/issues/24345.

**Comment by kamakshibhat-appsmith** [comment]
Looks good !

**Pull request merged**
