### PR TITLE
fix: make table button transparent when no color is selected

### LINKED ISSUE #10276: [Bug]: Button color in table widget when changed to no color moves back to green color
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Button color in table widget when changed to 'no color' moves back to green color. Whereas the default behavior of Button widget on a canvas when the color is changed to _no color_, it becomes transparent and on hover it appears green. Consistency can be maintained when a button is placed irrespective on a canvas, form, container or a table.

Currently button on canvas, container and on form behaves same it is indifferent on table widget.

https://loom.com/share/32decd910a744a5aa95934e1597e5888

### Steps To Reproduce

1. Drag and drop a table widget
2. Click on settings icon for _action_ column
3. Change the Button Color to no color.

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by Tooluloope**
## Description
Make table button transparent when no color is selected

Fixes #10276

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Cypress test

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>

    // Code coverage diff between base branch:release and head branch: fix/button-color-does-not-change-to-transparent 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | app/client/src/utils/WorkerUtil.ts | 88.98 **(-0.78)** | 68.63 **(-3.92)** | 100 **(0)** | 92.38 **(-0.95)**
 :green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.94 **(0.23)** | 41.67 **(0.84)** | 36.21 **(0)** | 56.99 **(0.25)**</details>

### CODE REVIEW

**Review by sbalaji1192 — APPROVED** [review]

**Comment by YogeshJayaseelan** [comment]
@Tooluloope Tested this PR and please find the status below,

Issue 1 - Choosing button colour to 'No colour' in the table widget on mouse hovering the button is not visible. 

https://www.loom.com/share/79e0809993534c2bbf1a13aa37be8bc2

**Comment by Tooluloope** [comment]
> @Tooluloope Tested this PR and please find the status below,
> 
> Issue 1 - Choosing button colour to 'No colour' in the table widget on mouse hovering the button is not visible.
> 
> [LOOM DEMO](https://www.loom.com/share/79e0809993534c2bbf1a13aa37be8bc2)

@YogeshJayaseelan this would be supported in this PR https://github.com/appsmithorg/appsmith/pull/9164

This issue is just for the background color

**Pull request merged**
