### PR TITLE
chore: Update environment switch toast text

### LINKED ISSUE #25924: [Bug]: Update environment switch toast text
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Update toast messages upon switching environment from 
`...Switching your environment to ${environment}, and running all associated pageload actions` to 
`Switching your environment to ${environment}, and running all associated pageload actions`

### Steps To Reproduce

Switch environment 

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by ChandanBalajiBP**
#### PR fixes following issue(s)
Fixes #25924 

#### Type of change
- Chore (housekeeping or task changes that don't impact user perception)
>
>
>
#### How Has This Been Tested?
- [x] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Comment by ChandanBalajiBP** [comment]
This updates the text in toast and i have verified it by myself. We are not adding automation test cases here because we are expecting this CTA to change in near future and this is just a workaround design. Hence adding skip test plan label myself.

**Review by sondermanish — APPROVED** [review]
LGTM

**Pull request merged**
