### PR TITLE
fix: Radio button triggering on change twice

### LINKED ISSUE #18026: [Bug]: JS Objects settings change event handlers are called twice
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I toggle the JS Objects settings toggles, the event handler is called twice. It should be called only once.

https://user-images.githubusercontent.com/13567359/199208381-d16395b8-2568-4b5d-9095-69f4badef057.mp4

### Steps To Reproduce

1. Go to JS Objects.
2. Select Settings.
3. Toggle one of the settings.

### Public Sample App

_No response_

### Version

Cloud - 1.8.6

### PR DESCRIPTION
**Pull request by albinAppsmith**
## Description

This PR contains the fix for th design system radio component triggering on change function twice.

Fixes #18026

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Comment by ravikp7** [comment]
Fixes https://github.com/appsmithorg/appsmith/issues/18026

**Review by tanvibhakta — DISMISSED** [review]

**Comment by shadabbuchh** [comment]
The fix looks good. Event handlers are called only once now.
https://www.loom.com/share/0ac1667648e5483ca5eb1e8e61ba5610

**Review by tanvibhakta — APPROVED** [review]

**Pull request merged**
