### PR TITLE
chore: Release promotion v1.9.4

### PR DESCRIPTION
**Pull request by Rishabh-Rathod**
## Description

Release promotion: v1.9.4

## Type of change

chore

### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by sharat87 — APPROVED** [review]

**Comment by filipesmedeiros** [comment]
I'm getting a bunch of 503s after updating/refreshing Appsmith. Wonder if it's related to this merge?

**Comment by nidhi-nair** [comment]
Hey @filipesmedeiros ! Could you please help us with the Appsmith version you're running? Please also share your log files so we can take a look at the cause. :)

**Pull request merged**
