### PR TITLE
fix: sentry issues

### LINKED ISSUE #9451: [Bug] TypeError: Cannot read properties of undefined (reading 'forEach')
Sentry Issue: [APPSMITH-1B2](https://sentry.io/organizations/appsmith/issues/2778247815/?referrer=github_integration)

```
TypeError: Cannot read properties of undefined (reading 'forEach')
  at call (sagas/EvaluationsSaga.ts:135:8)
  at apply (utils/WorkerUtil.ts:176:10)
  at Worker.a (../../src/helpers.ts:87:17)
...
(37 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by eco-monk**
## Description
- added polyfill for `String.replaceAll`
- add null check for `logs`

Fixes #9451, #9453

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/sentry-issues 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 55.08 **(0)** | 37.13 **(-0.01)** | 33.87 **(0)** | 55.58 **(0)**
 :red_circle: | app/client/src/sagas/EvaluationsSaga.ts | 24.88 **(0)** | 5.49 **(-0.26)** | 12.5 **(0)** | 27.75 **(0)**</details>

### CODE REVIEW

**Review by hetunandu — APPROVED** [review]

**Comment by eco-monk** [comment]
image
`Table_Filter_spec.js` is underwork by automation team

**Comment by eco-monk** [comment]
image

image

**Pull request merged**
