### PR TITLE
fix: Adds analytics event to log search input.

### LINKED ISSUE #27449: [Task]: Add event to track data entered in Templates search box
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

We need to get information about what our users are entering in the templates search box to understand what kind of templates our users want.

Screenshot 2023-09-19 at 17 13 23

### PR DESCRIPTION
**Pull request by rahulbarwal**
## Description
Adds analytics event to log search input.
* Adds debounce to search as well.
#### PR fixes following issue(s)
Fixes #27449

#### Type of change
- Chore (housekeeping or task changes that don't impact user perception)
- [x] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by akash-codemonk — DISMISSED** [review]

**Comment by rahulbarwal** [comment]
@shwetha-ramesh 
Only visible change that comes with this PR is that search input in the `/templates` page is now debounced, i.e. you won't immediately receive the results but after 500ms.
DP: https://ce-27477.dp.appsmith.com/templates

**Review by akash-codemonk — APPROVED** [review]

**Comment by shwetha-ramesh** [comment]
@rahulbarwal QA done.

**Pull request merged**
