### PR TITLE
fix: Queries are missing from git after renaming a page

### LINKED ISSUE #27508: [Bug]: Renaming page which contains queries and committing those changes make queries disappear
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we have multiple branches say master and develop, on renaming the page on develop and merging it back to master , casues queries to lose

### Steps To Reproduce

https://github.com/appsmithorg/appsmith/assets/80334441/3f06de5c-c528-4f0c-952d-36fed3025d26

1. Connect an app to git, create Page1 and add query1 to it, commit changes
2. Create new branch develop and update the Page1 to Page1-updated, commit and merge changes to master
3. Switch to master and observe query1 is missing

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by nayan-rafiq**
## Description
In git connected applications, if user renames a page, their queries are not pushed to git for that page.

#### PR fixes following issue(s)
Fixes #27508

#### Type of change
- Bug fix (non-breaking change which fixes an issue)

#### How Has This Been Tested?
- [x] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by AnaghHegde — COMMENTED** [review]
Looks good. Can we add a junit test case to ensure that this won't happen again

**Comment by nayan-rafiq** [comment]
> Looks good. Can we add a junit test case to ensure that this won't happen again

@AnaghHegde Yeah, I'll try. Didn't add with this because wanted to release the fix ASAP.

**Review by AnaghHegde — APPROVED** [review]

**Pull request merged**
