### PR TITLE
fix: Compact property not functional for menu type in table widget v2

### LINKED ISSUE #15261: [Bug]: Compact property is not functional for Menu Button type on Table widget
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The font size of the Menu options are getting smaller but overall size of the dropdown is still same as in non-compact mode.

P.S: Compact property is working fine on Menu button widget

https://www.loom.com/share/42d0a274f1f24d77bd0d4223f3168268

### Steps To Reproduce

1. D&D Table widget
2. Observe there is default data displayed in Table widget
3. Click on Action column setting icon
4. Change the Column Type to Menu Button
5. Add multiple menu options
6. Now Click on Menu Button on Table widget and observe the height of the dropdown list
7. Now enable **Compact** option
8. Observe there is no change in height of the dropdown list

### Public Sample App

_No response_

### Version

Cloud/Release

### PR DESCRIPTION
**Pull request by souma-ghosh**
## Description

Fixes issue where Compact property not functional for menu type in table widget v2.
This issue has been fixed for table widget v1. This PR makes the same fix for table widget v2.

Fixes #15261 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manually tested

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by jsartisan — APPROVED** [review]

**Comment by vivekverma2312** [comment]
@souma-ghosh Tested and working fine.

**Comment by somangshu** [comment]
@Aishwarya-U-R can you check why are the test failing here? The server build keeps failing

**Comment by Aishwarya-U-R** [comment]
@somangshu - Failing test is known flaky. Please proceed.

**Pull request merged**
