### PR TITLE
fix: Datasource edit icon is different from platform

### LINKED ISSUE #8057: [Bug]-[10000]:Edit icon consistency across application for design system
## Description
Raising this issue to list down different areas where we have **edit** option but there's inconsistency on design/icon. Need some clarity on this.

imageIcon on **Datasources** page
image

- [ ] Icon on **API query page** - not present on other datasources
image

- [ ] **Profile dropdown** - icon different from others
image

- [ ] **Entity pane, query** - no icon
image

- [ ] **Entity pane, datasources** - no icon
image

- [ ] **Entity pane, datasources** - no icon
image

- [ ] **Entity pane, page** - no icon
image

- [ ] **Query name** - icon change?
image

- [ ] **Application header** - edit mode icon
image

- [ ] **Header**, app name - no icon
image

- [ ] **Home page** - App name edit icon
image

- [ ] **Home page**, app card - icon
image

- [ ] API query
image

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Deploy preview 7304

### PR DESCRIPTION
**Pull request by albinAppsmith**
## Description

Edit icon was different in edit datasource button, this PR fixes that issue. Also, changed to sentense case in authentication tab.

#### PR fixes following issue(s)
Fixes #8057 

#### Media
Screenshot 2023-06-19 at 11 55 04 AM

#### Type of change

- Bug fix (non-breaking change which fixes an issue)

## Testing

- [ ] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by rohitagarwal88 — APPROVED** [review]

**Comment by shadabbuchh** [comment]
Tested this PR. Looks good.

- New icon for `Edit Datasource` button.
- Sentence case applied in auth page.

Screenshot 2023-06-21 at 10 02 23 AM

**Pull request merged**
