### PR TITLE
Sentry fix for TypeError: t.entities.canvasWidgets[e.widgetId] is undefined

### LINKED ISSUE #6177: [Bug] TypeError: t.entities.canvasWidgets[e.widgetId] is undefined
Sentry Issue: [APPSMITH-ZT](https://sentry.io/organizations/appsmith/issues/2537206160/?referrer=github_integration)

```
TypeError: t.entities.canvasWidgets[e.widgetId] is undefined
  at selector (components/editorComponents/DropTargetComponent.tsx:92:26)
  at DropTargetComponent (components/editorComponents/DropTargetComponent.tsx:91:24)
  at r (../../src/helpers.ts:87:17)
...
(15 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by rahulramesha**
## Description

Added checks for typeError

Fixes #6177 

## Type of change

Sentry Issue

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/6177_typeError_sentry 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 51.51 **(0)** | 33.53 **(0.01)** | 29.3 **(0)** | 52.13 **(0)**
 :green_circle: | app/client/src/components/editorComponents/DropTargetComponent.tsx | 65 **(0)** | 36.62 **(2.29)** | 52.94 **(0)** | 60.67 **(0)**</details>

### CODE REVIEW

**Review by somangshu — APPROVED** [review]
LGTM

**Review by riodeuno — APPROVED** [review]

**Review by somangshu — APPROVED** [review]
Approving to run tests

**Pull request merged**
