### PR TITLE
fix: reset the filepicker widget when the user goes to a different link 

### PR DESCRIPTION
**Pull request by techbhavin**
## Description

>  Resetting the fileficker widget when the user goes to a different link or uses in any different widget like form or tabs. 

Fixes [#11660](https://github.com/appsmithorg/appsmith/issues/11660)

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by keyurparalkar — COMMENTED** [review]
@techbhavin Can you add the cypress test for this?

**Comment by chandannkumar** [comment]
Tested this PR and it is working as expected.
- Tested for resetting file picker widget when user goes to different link, new page, query page
- Tested for resetting file picker widget when tabs switched on Tab widget 
- Tested for resetting file picker widget when used inside form, container type widgets

**Review by keyurparalkar — CHANGES_REQUESTED** [review]
@techbhavin can you add cypress test for this?

**Review by keyurparalkar — APPROVED** [review]
LGTM!

**Pull request merged**
