### PR TITLE
Fix-Catch invalid google recaptcha v3 key error

### LINKED ISSUE #5734: Error: SyntaxError: Document.querySelector: 'script[src="https://www.google.com/recaptcha/api.js?render=...
Sentry Issue: [APPSMITH-Y5](https://sentry.io/organizations/appsmith/issues/2500798984/?referrer=github_integration)

```
Error: SyntaxError: Document.querySelector: 'script[src="https://www.google.com/recaptcha/api.js?render=""test"]' is not a valid selector

SyntaxError: Document.querySelector: 'script[src="https://www.google.com/recaptcha/api.js?render=""test"]' is not a valid selector
```

### PR DESCRIPTION
**Pull request by vicky-primathon**
## Description
Catch invalid google recaptcha v3 key error

Fixes #5734 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/google-recaptcha-v2 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 51.91 **(0.01)** | 33.51 **(0)** | 30 **(0)** | 52.57 **(0)**
 :green_circle: | app/client/src/components/designSystems/blueprint/ButtonComponent.tsx | 49.48 **(1.48)** | 42.67 **(0)** | 56 **(0)** | 52.87 **(1.76)**</details>

### CODE REVIEW

**Review by somangshu — DISMISSED** [review]
LGTM

@vivekverma2312 lets have a set of test cases set for this in our sheet as well.

**Comment by vivekverma2312** [comment]
@vicky-primathon I am getting error the moment I enter `""` in the reCaptcha field.
https://www.loom.com/share/53d6700226c94915b797b430e4425dca

**Comment by vicky-primathon** [comment]
> @vicky-primathon I am getting error the moment I enter `""` in the reCaptcha field.
> https://www.loom.com/share/53d6700226c94915b797b430e4425dca

@vivekverma2312 fixed this issue.

**Review by somangshu — DISMISSED** [review]
LGTM

**Review by somangshu — APPROVED** [review]

**Comment by vivekverma2312** [comment]
@vicky-primathon Deploy preview is tested and working fine now.

**Review by somangshu — APPROVED** [review]

**Pull request merged**
