### PR TITLE
fix: JSONForm missing theming accent color property and few JS enabled controls not access sourceData/formData properties

### LINKED ISSUE #13816: [Bug]: JSONForm Add missing accent colors and enable missing properties access to JS convertible fields
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

1. Few fields have missing accent color
2. Some properties' JS enabled text input does not have access to `sourceData`/`formData`/`fieldState`

### Steps To Reproduce

FIelds that should have accent colors
```
CHECKBOX
CURRENCY INPUT
DATEPICKER
EMAIL INPUT
MULTILINE TEXT INPUT
MULTISELECT
NUMBER INPUT
PASSWORD INPUT
PHONE NUMBER INPUT
PHONE NUMBER INPUT
RADIO GROUP
SELECT
SWITCH
TEXT INPUT
```

Properties that have missing access to `sourceData`/`formData`/`fieldState` when JS mode enabled
Theme controls - borderRadius, boxShadow

Steps
1. Drop JSONForm
2. Go to field configuration of any field
3. Enable js mode for borderRadius
4. Type `{{sourceData}}`, it would not get evaluated.

### Public Sample App

_No response_

### Version

Release

### PR DESCRIPTION
**Pull request by ashit-rath**
## Description

1. Few fields have missing accent color.
2. Some properties' JS enabled text input does not have access to sourceData/formData/fieldState

Fixes #13816 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
Jest test has been added to check if a property config is enabled for JS conversion then the customControl should be defined and the value should be `JSON_FORM_COMPUTE_VALUE`. Except for Action selectors whose JS mode control should always be `INPUT_TEXT`

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/13816-jsonform-missing-properties 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 56.61 **(0)** | 38.55 **(0)** | 35.9 **(0)** | 56.86 **(0.01)**
 :green_circle: | app/client/src/widgets/JSONFormWidget/widget/propertyConfig/properties/checkbox.ts | 45.45 **(6.99)** | 100 **(0)** | 0 **(0)** | 45.45 **(6.99)**
 :green_circle: | app/client/src/widgets/JSONFormWidget/widget/propertyConfig/properties/common.ts | 24.07 **(0.54)** | 0 **(0)** | 7.14 **(-0.55)** | 24.53 **(0.53)**
 :green_circle: | app/client/src/widgets/JSONFormWidget/widget/propertyConfig/properties/radioGroup.ts | 45 **(4.09)** | 0 **(0)** | 0 **(0)** | 45 **(4.09)**
 :green_circle: | app/client/src/widgets/JSONFormWidget/widget/propertyConfig/properties/switch.ts | 45.45 **(6.99)** | 100 **(0)** | 0 **(0)** | 45.45 **(6.99)**</details>

### CODE REVIEW

**Review by jsartisan — DISMISSED** [review]

**Comment by ashit-rath** [comment]
Reduced scope https://github.com/appsmithorg/appsmith/issues/13816#issuecomment-1125886951

**Review by jsartisan — DISMISSED** [review]

**Comment by chandannkumar** [comment]
Observation:
Removing the accent color with null, what should be the default color we display? @ashit-rath
I suggest to keep the Theming color 
https://www.loom.com/share/d4e736e7b649438f9bddd08801d38305

**Comment by ashit-rath** [comment]
> Observation: Removing the accent color with null, what should be the default color we display? @ashit-rath I suggest to keep the Theming color [LOOM DEMO](https://www.loom.com/share/d4e736e7b649438f9bddd08801d38305)

That's a good question, right now the fallback is the original color i.e the green one and if I'm not wrong all the other widgets behave similarly. It's a technical limitation right now but ideally we should address this later.
cc: @dilippitchika @jsartisan @somangshu

**Comment by chandannkumar** [comment]
Accent color for datepicker's calendar is not working when datepicker falls inside Array/Object field
https://www.loom.com/share/0d44d6d2dd1d431bab35b778af8258c7

**Comment by chandannkumar** [comment]
Tested this PR and working as expected
- Tested Accent color with JS option must be present for all the field types except Array & Object
- Tested JS enabled(accentColor, boxShadow and borderRadius) text input must have access to sourceData/formData/fieldState
- Tested JS option for accentColor, boxShadow and borderRadius

**Review by jsartisan — APPROVED** [review]

**Pull request merged**
