### PR TITLE
fix: Fix backward compatibility related to v1 git file format

### PR DESCRIPTION
**Pull request by abhvsn**
## Description

Recently we have modified the git file ops to optimize the performance, but we missed a bit to clean up the file for v1 of the file format. 

### v1 file fomrmat
Screenshot 2022-06-23 at 4 55 39 PM

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Manual testing

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by Athayde3586** [comment]
Manuela check me

**Comment by Athayde3586** [comment]
🤣

**Review by vishnu-gp — APPROVED** [review]

**Pull request merged**
