### PR TITLE
fix: Refactoring to replace all usages of isEqual method from lodash with equal method from fast-deep-equal/es6

### LINKED ISSUE #16421: [Task]: Replace loadash isEqual with fast deep equal
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

[FastDeepEqual](https://www.npmjs.com/package/fast-deep-equal) is significantly faster than lodash's isEqual, replace all instances of isEqual with fastDeepEqual.

Should we write a wrapper around it so that it would be a change at one place if we find something faster?

Screen Shot 2022-08-31 at 10 10 53 AM
Screen Shot 2022-08-31 at 10 01 39 AM

### PR DESCRIPTION
**Pull request by smrutiparida**
## Description

The change is a refactoring work. All usages of isEqual method from lodash has been replaced with equal method from fast-deep-qual/es6. This shall optimise the speed of execution as already analysed by the task creator.

Fixes #16421 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

This has not been tested other than reviewing the code changes.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have not added tests that prove my fix is effective or that my feature works
- [ ] existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by somangshu** [comment]
Thanks a lot for the contribution on this @smrutiparida, we will review this and take it forward from here. Please do keep a lookout for any change requests, If would like to get this merged ASAP if all looks good 😄 Let us know if you have any question meanwhile!

cc @SatishGandham

**Review by SatishGandham — APPROVED** [review]
Looks good. Thank you @smrutiparida :)

**Comment by somangshu** [comment]
@SatishGandham do we need some manual QA around this? Can you shed light on that?

**Pull request merged**
