### PR TITLE
fix: ButtonGroupWidget button variant validation updated

### LINKED ISSUE #9149: [Bug]: ButtonGroup widget's buttonVariant should be similar to that of ButtonWidget
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

ButtonGroup Widget:
Screenshot 2021-11-13 at 11 29 49 PM

Button Widget:
Screenshot 2021-11-13 at 11 31 28 PM

### Steps To Reproduce

1. Add button and buttonGroup widgets
2. Observe both's example and expected type of buttonVariant option

### Environment

Release

### Version

Self-Hosted

### PR DESCRIPTION
**Pull request by techbhavin**
## Description

> update variant in a button group Widget

Fixes #9149 

## Type of change

- Bugfix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>

    // Code coverage diff between base branch:release and head branch: bug/button-group-buttonvariant 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.71 **(-0.23)** | 40.83 **(-0.84)** | 36.21 **(0)** | 56.74 **(-0.25)**</details>

### CODE REVIEW

**Review by jsartisan — APPROVED** [review]

**Comment by shwetha-ramesh** [comment]
@techbhavin tested this PR, the 'Evaluated value' for buttongroup widget still shows _undefined_
image

**Comment by shwetha-ramesh** [comment]
@techbhavin working as expected.
Moving to DONE.

**Review by jsartisan — APPROVED** [review]

**Pull request merged**
