### PR TITLE
fix: order of plugins in most popular section fixed

### LINKED ISSUE #28931: [Bug]: The order of plugins in most popular datasources section is incorrect
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Screenshot 2023-11-17 at 3 01 45 PM
 
The order of plugins in most popular section is like as shown in image, it's incorrect, the order should be GSheets, REST API, POSTGRESQL, MYSQL, MONGODB

Refer [thread](https://theappsmith.slack.com/archives/C05P3ME9MBR/p1700149869598579?thread_ts=1700116820.577679&cid=C05P3ME9MBR)

### Steps To Reproduce

1. Create new application
2. Go to create new datasource page
3. Observe most popular datasource section, order is incorrect

### Public Sample App

_No response_

### Environment

Release

### Issue video log

_No response_

### Version

Cloud/ Self-Hosted - 1.8.12

### PR DESCRIPTION
**Pull request by sneha122**
## Description

This PR fixes the order of plugins in most popular datasource section in create new datasource page, The correct order should be Gsheets, REST, Postgres, MySQL, MongoDB

#### PR fixes following issue(s)
Fixes #28931 
- Bug fix (non-breaking change which fixes an issue)
>
>
>
- [x] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by AmanAgarwal041 — DISMISSED** [review]

**Comment by AmanAgarwal041** [comment]
Tested this on onboarding flow. Its works fine!

**Comment by AmanAgarwal041** [comment]
Divider seems missing. Screenshot 2023-11-21 at 2 46 36 PM

Tested well on onboarding as well as datasource pane.

**Comment by sneha122** [comment]
@AmanAgarwal041 As discussed with @carinanfonseca I have added the dividers wherever missing, Please check

**Pull request merged**
