### PR TITLE
fix: starter building blocks on canvas removes existing queries and JS objects

### LINKED ISSUE #32573: [Bug]: Canvas starter building blocks cause existing queries and Js in apps to be deleted
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I open a new app, add some queries and JS object, then click any of the canvas starter building blocks, the block get implemented, but all existing queries and JS objects before clicking on the block gets deleted.

### Steps To Reproduce

1. Create new application
2. Add 1 query
3. Add 1 JS object
4. Click to add any canvas starter building block
5. Check that already exiting queries and JS gets deleted

### Public Sample App

_No response_

### Environment

Production

### Severity

Critical (Broken Production apps)

### Issue video log

https://theappsmith.slack.com/files/U0386RC9C4R/F06TPG23L4S/2024-04-10_10.53.24.gif

### Version

1.21.0

### PR DESCRIPTION
**Pull request by rahulbarwal**
## Description
<ins>Root cause: </ins>
The original intention of the building blocks on canvas was to serve a new user on their very first app. 
Looking at (good) usage of this feature, we turned it on for all pages on all apps. 
Now, an experienced user don't always start with UI and thats when we hit this issue.

Additionally, this was a tech debt we had to repay and this PR takes that opportunity to get rid of hack of using `add a page from template` for this feature and uses proper PIE based API to support his.

Fixes #32573
_or_  
Fixes `Issue URL`
> [!WARNING]  
> _If no issue exists, please create an issue first, and check with the maintainers if the issue is valid._

## Automation

/ok-to-test tags="@tag.Templates"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/8797225643>
> Commit: 5f7f0fd094284faf67338412a57ef4757eb70af8
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=8797225643&attempt=1" target="_blank">Click here!</a>

## Summary by CodeRabbit

- **New Features**
	- Introduced functionality for importing starter building blocks into applications, including layout positioning and action triggers upon successful import.
	- Added new actions and selectors in Redux for managing current forking building block names.

- **Refactor**
	- Updated the handling of template names and constants for better consistency and use within the app.
	- Simplified event handling and variable naming in several components for improved code clarity and performance.

- **Bug Fixes**
	- Adjusted analytics and event data handling to ensure accurate tracking and functionality.

- **Tests**
	- Updated Cypress E2E tests to reflect changes in functionality and removed outdated test cases.

### CODE REVIEW

**Review by rahulbarwal — COMMENTED** [review]
/build-deploy-preview skip-tests=true

**Review by jacquesikot — APPROVED** [review]

**Review by jacquesikot — APPROVED** [review]

**Review by jacquesikot — APPROVED** [review]

**Pull request merged**
