### PR TITLE
chore: Fix signposting issue where application erroring out if there is nested binding

### PR DESCRIPTION
**Pull request by sbalaji1192**
Fixes: #7730

> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/nested-path-biding-signposting-issue 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 54.8 **(0.04)** | 36.57 **(0.05)** | 33.88 **(0.08)** | 55.41 **(0.04)**
 :green_circle: | app/client/src/components/editorComponents/Debugger/helpers.tsx | 79.69 **(1.56)** | 79.17 **(4.17)** | 37.5 **(0)** | 79.63 **(0)**
 :green_circle: | app/client/src/pages/Editor/utils.ts | 53.04 **(12.13)** | 50.62 **(11.95)** | 55 **(38.33)** | 53.77 **(11.61)**</details>

### CODE REVIEW

**Comment by ramsaptami** [comment]
Tested ok on deploy preview. Can be pushed to release

**Review by rishabhsaxena — DISMISSED** [review]
LGTM

**Comment by rishabhsaxena** [comment]
Think a jest test case or a comment would be useful here too

**Comment by trishaanand** [comment]
@sbalaji1192 : Is it possible to add a test case for this scenario so that this doesnt repeat in the future?

**Comment by sbalaji1192** [comment]
> @sbalaji1192 : Is it possible to add a test case for this scenario so that this doesnt repeat in the future?

Yeah. Adding a unit test case.

**Review by rishabhsaxena — APPROVED** [review]

**Pull request merged**
