### PR TITLE
fix: Expand Query/JS section in the explorer for new applications.

### LINKED ISSUE #11937: [Bug]-[1500]:Upon adding a new JSObj/Query/Blank API's - EntityExplorer should show the new item in the expanded tree
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

.png: 
Screenshot 2022-03-17 at 1 53 36 PM

### Steps To Reproduce

1. Create a new application
2. Add a new JSObject/Query/Blank API
3. User should be able to see the item added in the left side tree - as a confirmation that new item being created is added [as visible before]
4. Once user expands/collapses the Queries/JS or DataSources sections - then that state should be preserved upon different navigations/page refreshes etc.,
5. For older apps - the state can be preserved as decided by user
6. This bug addresses only the experience during a new application creation

### Public Sample App

_No response_

### Version

Cloud Release v1.6.15

### PR DESCRIPTION
**Pull request by arunvjn**
## Description
For a new application, keep the Query/JS section on the explorer open by default. This ensures that the user gets feedback when they create their first query.

Fixes #11937 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manual
- Cypress

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/keep-query-section-open-new-application 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 56.71 **(0)** | 38.66 **(0.01)** | 36.23 **(0.01)** | 56.96 **(0)**
 :green_circle: | app/client/src/pages/Editor/Explorer/common.tsx | 100 **(9.09)** | 100 **(0)** | 100 **(100)** | 100 **(9.09)**
 :red_circle: | app/client/src/pages/Editor/Explorer/helpers.tsx | 83.33 **(-0.73)** | 58.51 **(0)** | 100 **(0)** | 83.33 **(-0.88)**
 :green_circle: | app/client/src/pages/Editor/Explorer/Files/index.tsx | 77.78 **(2.22)** | 38.89 **(5.56)** | 57.14 **(14.28)** | 82.05 **(2.56)**
 :green_circle: | app/client/src/pages/Editor/Explorer/Widgets/WidgetGroup.tsx | 96.88 **(2.76)** | 74.65 **(0)** | 100 **(0)** | 96.77 **(2.83)**
 :green_circle: | app/client/src/utils/WorkerUtil.ts | 89.76 **(0.78)** | 72.55 **(1.96)** | 100 **(0)** | 93.33 **(0.95)**</details>

### CODE REVIEW

**Review by albinAppsmith — APPROVED** [review]

**Comment by arunvjn** [comment]
Closing this stale PR

**Pull request closed without merging**
