### PR TITLE
feat: Grouping & reorganisation of Property Pane

### LINKED ISSUE #15296: Remove feature flag for Grouping & reorganisation of Property pane
- [ ] Cleanup unwanted configurations for all widgets
- [ ] Remove code related to feature flag from client & server
- [x] Fix all Cypress tests

### PR DESCRIPTION
**Pull request by aswathkk**
## Description

Removes feature flag for Property pane grouping and reorganisation 

Fixes #15296

## Type of change

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

## TODO
- [ ] Fix Cypress tests
- [ ] Remove feature-flag related code from Server
- [ ] Address #15811
- [ ] Visual changes of property pane

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by yaldram — APPROVED** [review]
There are 2 places where I see the code is behind a false condition (will not be executing), I hope we will tackle it afterwards, I see some TODOS there,

**Comment by aswathkk** [comment]
Yes @yaldram. Those will be removed when we add the search input to the property pane.

**Pull request merged**
