### PR TITLE
chore: Update analytics to pass the correct source information in identify user call

### PR DESCRIPTION
**Pull request by ankitakinger**
## Description

Updating analytics to pass the correct source information

Fixes [#32266](https://github.com/appsmithorg/appsmith/issues/32266)

## Automation

/ok-to-test tags="@tag.Sanity"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/8750877755>
> Commit: 6fedefebd3867aee79877b7ed105c90888005cfd
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=8750877755&attempt=1" target="_blank">Click here!</a>

### CODE REVIEW

**Review by marks0351 — DISMISSED** [review]

**Review by brayn003 — APPROVED** [review]
lgtm, most changes are import renaming

**Pull request merged**
