### PR TITLE
fix: CENTER as default value for vertical alignment in Table Widget

### LINKED ISSUE #14885: [Bug]: JS toggle is not working for vertical alignment property
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://www.loom.com/share/fd17c1002a7148eeae4d78cd70b2dee9

### Steps To Reproduce

1. Drag and drop a table widget
2. Click on any column from property pane
3. Click on JS toggle for vertical alignment property
4. Observe that by default LEFT populates and clearing the data does noting

### Public Sample App

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by aswathkk**
## Description

Set "CENTER" as default value for Vertical Alignment property instead of invalid value "LEFT"

Fixes #14885

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by somangshu — APPROVED** [review]
LGTM

**Comment by somangshu** [comment]
@aswathkk do we need to merge this in

**Comment by aswathkk** [comment]
@somangshu Yes. Tests were passed. But, the ui-test-result status is not getting reported.

**Pull request merged**
