### PR TITLE
feat: Make icon selector keyboard accessible

### LINKED ISSUE #10060: Make Icon Selector keyboard accessible
Screenshot 2021-12-29 at 11 51 05 PM

### PR DESCRIPTION
**Pull request by aswathkk**
## Description

- Virtualized icon rendering result in less DOM nodes and improved performance / smooth loading of icons
- Made Icon selector keyboard accessible
  - `Tab` to focus
  - `ArrowDown`|`ArrowUp`|`Space`|`Enter` to open
  - `Esc` to close
  - `ArrowDown` to Change focus from search bar to icons
  - `Shift`+`ArrowUp` or `ArrowUp` when the focus is on first row to Change focus from Icons to search bar
  - `ArrowUp`|`ArrowDown`|`ArrowLeft`|`ArrowRight` to navigate through icons
  - `Space`|`Enter` to select an icon

Fixes #10060 

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Manual and Jest tests

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: feat/icon-select-control 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 55.83 **(0.11)** | 37.17 **(0.17)** | 35.34 **(0.33)** | 56.17 **(0.11)**
 :red_circle: | app/client/src/actions/pluginActions.ts | 65 **(-0.22)** | 100 **(0)** | 0 **(0)** | 58.33 **(-3.21)**
 :green_circle: | app/client/src/api/PluginApi.ts | 85.71 **(3.1)** | 100 **(0)** | 50 **(7.14)** | 85 **(3.18)**
 :green_circle: | app/client/src/ce/constants/messages.ts | 76.97 **(0.35)** | 100 **(0)** | 31.7 **(1.06)** | 81.75 **(-0.17)**
 :red_circle: | app/client/src/components/ads/Icon.tsx | 99.4 **(0)** | 84.21 **(0)** | 100 **(0)** | 99.39 **(-0.01)**
 :red_circle: | app/client/src/components/ads/Text.tsx | 92.59 **(-0.63)** | 74.19 **(0)** | 100 **(0)** | 92.45 **(-0.65)**
 :green_circle: | app/client/src/components/propertyControls/BaseControl.tsx | 83.33 **(16.66)** | 25 **(25)** | 66.67 **(33.34)** | 81.82 **(18.18)**
 :green_circle: | app/client/src/components/propertyControls/IconSelectControl.tsx | 91.78 **(48.92)** | 72.9 **(50.68)** | 96.15 **(76.15)** | 91.67 **(45.24)**
 :red_circle: | app/client/src/constants/routes.ts | 64.96 **(-0.47)** | 24.05 **(0.3)** | 22.22 **(0.79)** | 61.27 **(-0.82)**
 :green_circle: | app/client/src/reducers/entityReducers/pluginsReducer.ts | 41.67 **(5.96)** | 100 **(0)** | 0 **(0)** | 41.67 **(5.96)**
 :green_circle: | app/client/src/reducers/uiReducers/applicationsReducer.tsx | 10.42 **(0.11)** | 30 **(0)** | 8.33 **(0.17)** | 10.75 **(0.11)**
 :red_circle: | app/client/src/sagas/ApplicationSagas.tsx | 17.74 **(-0.33)** | 6.06 **(0)** | 8 **(0)** | 20.87 **(0)**
 :green_circle: | app/client/src/sagas/PluginSagas.ts | 14.58 **(0.99)** | 2.94 **(0.16)** | 10 **(0.91)** | 17.5 **(1.03)**
 :red_circle: | app/client/src/sagas/index.tsx | 92.86 **(-0.12)** | 60 **(0)** | 100 **(0)** | 94.44 **(-0.11)**
 :green_circle: | app/client/src/selectors/applicationSelectors.tsx | 68.67 **(0.85)** | 33.33 **(2.08)** | 46.15 **(3.29)** | 61.54 **(0.67)**
 :green_circle: | app/client/src/selectors/entitiesSelector.ts | 46.62 **(-0.18)** | 7.8 **(0)** | 25.52 **(0.52)** | 43.23 **(0.06)**
 :green_circle: | app/client/src/utils/storage.ts | 34.48 **(0.44)** | 11.11 **(0)** | 7.69 **(0.55)** | 27.56 **(0.55)**
 :green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.94 **(0.23)** | 41.67 **(0.84)** | 36.21 **(0)** | 56.99 **(0.25)**
 :red_circle: | app/client/src/workers/evaluationUtils.ts | 58.73 **(-0.29)** | 57.07 **(-0.44)** | 65.08 **(0)** | 58.13 **(-0.34)**
 :x: | ~~app/client/src/actions/templateActions.ts~~ | ~~68.18~~ | ~~100~~ | ~~0~~ | ~~88.89~~
 :x: | ~~app/client/src/api/TemplatesApi.ts~~ | ~~71.43~~ | ~~100~~ | ~~20~~ | ~~69.23~~
 :x: | ~~app/client/src/reducers/uiReducers/templateReducer.ts~~ | ~~38.46~~ | ~~100~~ | ~~0~~ | ~~38.46~~
 :x: | ~~app/client/src/sagas/TemplatesSagas.ts~~ | ~~28.95~~ | ~~10~~ | ~~16.67~~ | ~~34.38~~</details>

### CODE REVIEW

**Comment by vivekverma2312** [comment]
@aswathkk Icon pop-up do not close if we select the icon with space button. One if user has used the space button to select then enter button also start behaving same.
https://www.loom.com/share/e0ec9b1e10bc4144a5f18a4f1431c9e7

**Review by SatishGandham — APPROVED** [review]

**Comment by vivekverma2312** [comment]
@aswathkk I am not able to focus on cancel icon on search icon field using keyboard
Screenshot 2022-02-16 at 12 49 36 PM

**Comment by aswathkk** [comment]
@vivekverma2312 
As a decent keyboard user myself, here’s my take on this one: 
I prefer `Cmd` + `A` to select all text and press `Delete` to clear the selection.

  The challenges on making clear-all button also keyboard accessible:
- We need to decide on a keyboard shortcut
- It might complicate the UX
- We need a way to communicate this to the user

@ramsaptami @somangshu @vuiets 
I would like to know your thoughts here

**Comment by somangshu** [comment]
> I prefer `Cmd` + `A` to select all text and press `Delete` to clear the selection.

@aswathkk @vivekverma2312 I agree to ☝️ , Intuitively thats the first thought to achieve the use case

**Comment by vivekverma2312** [comment]
@aswathkk It is working fine the only thing observed is that cross icon on search is not able to focus using keyboard.

**Comment by aswathkk** [comment]
Thanks, @vivekverma2312 
We will be raising a separate PR if we decide to have a focus state for cross icon.

**Pull request merged**
