### PR TITLE
fix: allowing custom username is git url validation

### LINKED ISSUE #19881: [Feature]: Add support for the custom ssh URL that does not begin with git@
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Why should this be worked on?

A self hosted or a private github organization can have ssh urls that does not begin with the keyword `git`. Hence such urls are not supported with Appsmith. We should support such use cases. 

Link to conversation - https://theappsmith.slack.com/archives/C0341RERY4R/p1674049012093039?thread_ts=1673636062.767679&cid=C0341RERY4R

Front logo [Front conversations](https://app.frontapp.com/open/top_6vccs)

### PR DESCRIPTION
**Pull request by brayn003**
## Description
Fixes the validation issue with custom usernames in Git origin URL

#### PR fixes following issue(s)
Fixes #19881

#### Media
image

#### Type of change
- Bug fix (non-breaking change which fixes an issue)

- [x] Manual
- [ ] JUnit
- [x] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

## Summary by CodeRabbit

- **Refactor**
	- Enhanced support for a wider range of git remote URL formats in the Git synchronization feature.

### CODE REVIEW

**Comment by brayn003** [comment]
Seems like validation is present in backend too

**Review by AnaghHegde — CHANGES_REQUESTED** [review]
Looks good. Can you also update the server unit test to include the new url type that is supported?

**Review by AnaghHegde — APPROVED** [review]

**Pull request merged**
