### PR TITLE
fix: App nav upload logo thumbnail false

### LINKED ISSUE #22293: [Task]: App Nav Logo Upload - Is Thumbnail False
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Upload logo API resizes the uploaded image to THUMBNAIL_PHOTO_DIMENSION of 128*128.

### PR DESCRIPTION
**Pull request by NilanshBansal**
## Description

> This PR fixes the logo upload which was by default getting set to a thumbnail type size.

Fixes #22293 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

- Manual
- Jest
- Cypress

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Comment by dhruvikn** [comment]
Is there a way to test this from postman but not setting up a local server?

**Review by nayan-rafiq — APPROVED** [review]
LGTM

**Pull request merged**
