### PR TITLE
feat: deprecate duplicate button

### LINKED ISSUE #13169: [Type]-[400]:Deprecate duplicate application as we can fork the application within the same organization as well
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Using the fork application user can create a copy of the application within the same organization along with the other organizations of which the user is part. From the user's perspective, this creates some confusion as we are doing the same thing in 2 different places. 
For more details please check slack thread: https://theappsmith.slack.com/archives/C0341RERY4R/p1650518456216239

### PR DESCRIPTION
**Pull request by rahulbarwal**
## Description
We have `Fork` and `Duplicate` options which essentially do the same thing, the former one provides us more flexibility, hence we are removing the `Duplicate` option completely from our app.

#### PR fixes following issue(s)
Fixes #13169
#### Type of change
- Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### How Has This Been Tested?
- [x] Cypress
- [x] Manual

#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [x] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [x] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [x] Cypress test cases have been added and approved by SDET/manual QA
- [x] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by Aishwarya-U-R — COMMENTED** [review]
Cypress changes looks OK.

**Review by akash-codemonk — DISMISSED** [review]

**Comment by ramsaptami** [comment]
lgtm
cc: @rahulbarwal

**Review by akash-codemonk — APPROVED** [review]

**Pull request merged**
