### PR TITLE
Fixed the pull request template issue partially 

### PR DESCRIPTION
**Pull request by OmkarPh**
I strongly recommend to merge this with our default branch i.e. **release**, because it won't take effect until then.
Fixed issue #826

### CODE REVIEW

**Comment by OmkarPh** [comment]
Hi @hetunandu 
This is the PR, checkout and tell me if anything else is required.

**Review by mohanarpit — APPROVED** [review]

**Comment by mohanarpit** [comment]
@OmkarPh Thanks for raising this PR. If we are moving the file `pull_request_template.md` to `.github` folder, can you also please delete that folder? This is because the folder is now empty and we don't want to have empty folders like this in the repo.

**Comment by OmkarPh** [comment]
Hi @mohanarpit 
Since GitHub doesn't track Empty folders, the folder is not visible in my branch now as you can see:

**Comment by hetunandu** [comment]
@OmkarPh Please clone this branch, delete the folder and push the commit back so that the folder is deleted. This is needed for maintaining clean code. Post this we will merge this in

**Comment by OmkarPh** [comment]
Ok, I'll do it soon

**Comment by OmkarPh** [comment]
Hi @hetunandu 
I deleted my local repo and cloned my remote repo again, when I open the .GitHub folder I don't see old PR folder anymore.
Maybe you're seeing it coz of some merge conflict...

**Review by hetunandu — APPROVED** [review]

**Comment by hetunandu** [comment]
This worked well @OmkarPh! Thanks a lot for this critical contribution to Appsmith 🙌 Hope to keep seeing your amazing contributions here 😄

**Comment by OmkarPh** [comment]
I look forward to continue contribution here !
Great community ✌️

**Pull request merged**
