### PR TITLE
fix: fixed broken file downloads for urls containing "(" or ")"

### LINKED ISSUE #13915: [Bug]: Downloaded Image Broken When It Includes Brackets () in Its Filename
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When using the `download()` method to download an image that contains **brackets** `()` in its filename, e.g., `logo_(1)`, the downloaded image is broken. 

Here is a [sample app](https://app.appsmith.com/app/image/image-download-62820d3b2c1e3f03d32a2fad) that reproduces the issue.

### Steps To Reproduce

1. Add an **Image** widget to the canvas and use an URL of an image that contains **brackets** in its name.
2. In the **onClick** event of the **image**, add the **`download()`** method for it to download.
3. Click on the image to test the download and note that the downloaded file is broken.

Note: This works fine if the image does not contain brackets in the filename(e.g., `logo_1`).

### Public Sample App

https://app.appsmith.com/app/image/image-download-62820d3b2c1e3f03d32a2fad

### Version

Cloud  v1.6.26-SNAPSHOT

### PR DESCRIPTION
**Pull request by arunvjn**
## Description
- fixed broken file downloads for urls containing "(" or ")"
- Modified regex that checks to see if a string is a URL.
- Added unit tests for isURL utility method.

Fixes #13915 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manual
- Jest

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [x] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [x] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Comment by ohansFavour** [comment]
@arunvjn will this fix the AForce file download issues?

**Comment by arunvjn** [comment]
> @arunvjn will this fix the AForce file download issues?

I am not sure. Could you please share the ticket here if there is one ?

**Comment by ohansFavour** [comment]
See the following ;

1. https://theappsmith.slack.com/archives/C0341RERY4R/p1678954237147369
2. https://theappsmith.slack.com/archives/C0341RERY4R/p1679502382461859

**Review by ohansFavour — DISMISSED** [review]
Check out the failing test

**Review by ohansFavour — APPROVED** [review]

**Comment by ramsaptami** [comment]
LGTM cc: @arunvjn

**Pull request merged**
