### PR TITLE
Add chart type: "Custom FusionChart"

### LINKED ISSUE #2647: [Feature] FusionCharts manual chart config to be able to plot anything FusionCharts supports
## Summary

Currently only a few chart options are supported (e.g. line/bar chart). The underlying library, FusionCharts, supports many more  chart types and options. This feature request is to add a chart type "Manual" (in the "Chart type" dropdown) where the user supplied data is not expected to be in the format `Array<x:string, y:number>` but in the format `Object`, representing the full config for a FusionChart chart (maybe except for the `renderAt` property which AppSmith can fill in). 

## Motivation

The current charting options are useful but don't allow for configuring chart options beyond the explicit ones in the interface (e.g. x-axis label). If a user would like more complex charting options the user should be able to manually specify the config even though this takes more effort on the user side.

## Additional Context

image
So, in this dropdown another option could be added: "Manual"

Additionally, a link somewhere to the FusionCharts documentation (https://www.fusioncharts.com/fusioncharts) would be useful when the "Manual" option is selected.

### PR DESCRIPTION
**Pull request by zegerhoogeboom**
## Description

This change implements an additional chart type: "Custom FusionChart". This is useful as the FusionChart library has many options which are currently not configurable using the Appsmith interface.

The PR includes a dependency on `@fusioncharts/powercharts` which I intended to support "Power charts" (https://www.fusioncharts.com/charts#powercharts) though maybe we can opt for leaving out this dependency.

Some notes about the changes:

- I have not yet added any documentation, I guess I should right?
- Currently the whole chart will re-render on an update which especially on charts with relatively large amounts of data is not so great. It's implemented like this because you can of course update the chart configuration part and not only the data part so only updating the data is not enough on update. Maybe it can be a bit smarter in that we check if the update only changed something in `.dataSource.data` then we only update the data.
- I didn't fully understand how the error messages from the validators work, I did my best trying to make it as similar as possible to the existing validators, just so you know.
- For the chart name there is a preference for the chart name text field over the `.dataSource.chart.caption` field. If the chart name text field is not filled but the `.dataSource.chart.caption` value is it will use that one though.

Fixes #2647

## Type of change

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

## How Has This Been Tested?

This change can be tested by creating a new chart, select the "Custom FusionChart" option and paste the following configuration. 
This should create a chart that would not be possible to configure without this chart type. Additionally other chart types can be tested from the FusionChart documentation (https://www.fusioncharts.com/dev/chart-attributes).
```
{{{
  type: "column3d",
  dataSource: {
    chart: {
      caption: "Countries With Most Oil Reserves [2017-18]",
      subCaption: "In MMbbl = One Million barrels",
      xAxisName: "Country",
      yAxisName: "Reserves (MMbbl)",
      numberSuffix: "K",
    },
    data: [
      {
        label: "Venezuela",
        value: "290"
      },
      {
        label: "Saudi",
        value: "260"
      },
      {
        label: "Canada",
        value: "180"
      },
      {
        label: "Iran",
        value: "140"
      },
      {
        label: "Russia",
        value: "115"
      },
      {
        label: "UAE",
        value: "100"
      },
      {
        label: "US",
        value: "30"
      },
      {
        label: "China",
        value: "30"
      }
    ]
  }
}}}
```
This should create the following chart:

image

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by riodeuno — APPROVED** [review]
Looks good to me. There are differences in the design from what we have in release. I'll deal with these in the `feature/property-pane-enhancements` branch.

**Comment by riodeuno** [comment]
@all-contributors please add @zegerhoogeboom for code

**Comment by riodeuno** [comment]
Hi @zegerhoogeboom These fixes have been release. 

This, unfortunately, took a long time to be released as there were many changes introduced over time in the property pane enhancements which needed to be fixed, evaluated and tested. So, we had to keep going back to the branch before it was ready to be released.

We really appreciate your contribution, it has made a high impact on Appsmith and hope to see more contributions from you in the future.

**Comment by zegerhoogeboom** [comment]
Hi @riodeuno that's awesome! 

I'm happy it's released and no worries about the time it took, I've been using the custom fusion charts with pleasure on my own instance for a while now so hope it will be useful to other people wanting to do more advanced charting like me.

We're actually also using 3D charts through Plotly.js within Appsmith which we migrated from a custom made internal tool specifically for that and it's a lot nicer now in Appsmith. I'm happy to contribute it in a PR if you're open for more plotting options but I think I would need some suggestions on how to best do it, currently it's simply loading the Plotly dependency in the index.html meaning it's loaded on any Appsmith page even if Plotly is not used (which will be the case for the majority of users). It would be better to dynamically load the dependency only when it's needed but I'm not sure how to do that. 

Sorry for the detour about Plotly, I think I'll reach out on the Discord server once I have a merge-able version for feedback :-)!

**Comment by zegerhoogeboom** [comment]
Let me get back to you on that I think next week @areyabhishek because at the moment neither is easy (the Appsmith instance is behind a company SSO reverse proxy so not directly reachable). I think I can make screenshots work, just not immediately. I'll get in touch :v:

**Pull request merged**
