### PR TITLE
fix: Unable to drag disabled button

### LINKED ISSUE #7826: [Bug] Dragging a disabled form button or a select all widget is annoying, it won't let you grab anywhere but in the corner
## Description
Dragging a disabled form button or a select all widget is annoying, it won't let you grab anywhere but in the corner

### Steps to reproduce the behaviour:
1. Drag a button to the canvas, and try to change it's position
2. Disable the button from the property pane and try to change the position again
3. At times it doesn't work as expected 

https://user-images.githubusercontent.com/1944800/134770271-eda2e8f6-2694-48b7-8f7a-bfa6096c9fd6.mov

### PR DESCRIPTION
**Pull request by aswathkk**
## Description

Widgets like ButtonWidget, IconButtonWidget and MenuButtonWidget are facing issues with dragging while on disabled mode. The root cause for this is that we were passing `disabled` prop to the blueprint component which internally sets `disabled` property to <button> tag. Button tags with disabled prop will prevent all other mouse events. The solution is to add `pointer-events: none` to the button so that the parent DOM nodes will handle the mouse event.

Fixes #7826 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Tested manually by setting the disabled state for the widgets and dragging and arranging it.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/disabled-button-drag 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 54.63 **(0)** | 36.33 **(-0.01)** | 33.09 **(0)** | 55.15 **(0)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.04 **(-0.22)** | 40.42 **(-0.83)** | 34.48 **(0)** | 55.96 **(-0.26)**
 :green_circle: | app/client/src/widgets/ButtonWidget/component/index.tsx | 50.53 **(1.07)** | 30 **(0.41)** | 45.45 **(2.59)** | 49.4 **(0.62)**
 :red_circle: | app/client/src/widgets/IconButtonWidget/component/index.tsx | 29.41 **(-1.84)** | 7.14 **(-0.27)** | 0 **(0)** | 41.67 **(-1.81)**
 :red_circle: | app/client/src/widgets/MenuButtonWidget/component/index.tsx | 25.93 **(-0.99)** | 14.71 **(-0.44)** | 0 **(0)** | 30.43 **(-0.68)**</details>

### CODE REVIEW

**Comment by aswathkk** [comment]
@somangshu Conflicts are resolved.

**Review by somangshu — DISMISSED** [review]

**Comment by aswathkk** [comment]
I couldn't find a good way to test drag and drop feature in Cypress or Jest. After the discussion with @NandanAnantharamu, he told that he is going to take a look at that.

**Comment by NandanAnantharamu** [comment]
> I couldn't find a good way to test drag and drop feature in Cypress or Jest. After the discussion with @NandanAnantharamu, he told that he is going to take a look at that.

@aswathkk i have added a test based on our discussion, please check and merge

**Review by marks0351 — APPROVED** [review]

**Comment by aswathkk** [comment]
@NandanAnantharamu This test pass even after I revert my changes

**Comment by NandanAnantharamu** [comment]
> @NandanAnantharamu This test pass even after I revert my changes

oh.. i must add a proper assertion for this . let me check that aspect

**Comment by marks0351** [comment]
@aswathkk there are jest examples in https://github.com/appsmithorg/appsmith/blob/release/app/client/src/pages/Editor/MainContainer.test.tsx#L890
 to assert dragging functionality.

**Comment by aswathkk** [comment]
@marks0351 Followed the jest test as you told and set it up for the button widget.
But same as like Cypress test, the jest test also passes even if I revert the change.

**Comment by marks0351** [comment]
> @marks0351 Followed the jest test as you told and set it up for the button widget. But same as like Cypress test, the jest test also passes even if I revert the change.

i think the problem is when simulating a drag from jest or cypress we are trying to drag using the t-draggable-widget div which will work, but the edge case here is to try to drag it via the button it-selves(which is wrapped inside the draggable layer)

**Comment by marks0351** [comment]
@aswathkk also the issue says this is reproducible intermittently.

**Comment by aswathkk** [comment]
@marks0351 Yes. As you said, the issue can only be reproduced if we drag exactly the button. Not button text or anything else. This is an issue with the `<button>` tag.
I tried various methods to simulate this interaction via Cypress and Jest. Both were able to drag a disabled button on release.

**Comment by aswathkk** [comment]
@marks0351 @NandanAnantharamu I was able to write the tests using [cypress-real-events](https://github.com/dmtrKovalenko/cypress-real-events#cyrealhover) library.
Can you review the tests?

**Review by marks0351 — DISMISSED** [review]

**Review by marks0351 — APPROVED** [review]

**Comment by YogeshJayaseelan** [comment]
@aswathkk Tested this PR and now able to drag disabled button type widgets. But the problem still exists for MultiTreeSelect and Mu.itSelect widget on disabling and dragging by clicking on the options area - Refer attached video for reference

https://loom.com/share/1a67b90ad0734e9182186b2e155025ff

**Comment by aswathkk** [comment]
@YogeshJayaseelan The scope of this PR is only about widgets for which we use buttons as an underlying component.
You can raise a separate issue for MultiTreeSelect and Select widgets.

**Pull request merged**
