### PR TITLE
fix:skipping jest-tests in client workflow

### PR DESCRIPTION
**Pull request by pratapaprasanna**
Fixes: [22072](https://github.com/appsmithorg/appsmith/issues/22072)
Running as part of individual builds:

https://github.com/appsmithorg/appsmith/actions/runs/4605026111/jobs/8136569091

### CODE REVIEW

**Review by mohanarpit — DISMISSED** [review]

**Comment by sharat87** [comment]
@pratapaprasanna, is this PR ready to be reviewed/merged? I recall you were still testing this in a separate isolated repo to confirm?

**Review by sharat87 — APPROVED** [review]

**Pull request merged**
