### PR TITLE
feat: migrate pages at once

### LINKED ISSUE #14411: [Bug]-[1644]:Handle client side migration for git discard functionality to avoid seeing uncommitted changes
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When user's application has client-side migration since last commit, and if user triggers the discard and pull flow user ends up seeing uncommitted changes as client-side migrations run after the successful response from server. This gives the false impression that discard failed for some unknown error though UI does not show any error state. To resolve this issue we will be doing a autocommit when we detect the client-side migrations in get status flow:

- [x] #19209
- [ ] Chain get status API with migrations so as to avoid the race condition i.e. run all the migrations and then trigger get status API @IAmAnubhavSaini 
- [x] #14412

### Steps To Reproduce

1. Connect application to git
2. Reduce the page DSL version from DB by 1 (manual update)
3. Commit changes without refreshing the page
4. Hard refresh from browser to trigger client side migrations along with get status call
5. Try pull and discard flow
6. Even if discard is successful we will see migrations changes to be committed

### Public Sample App

_No response_

### Version

Cloud: v1.7.1

### PR DESCRIPTION
**Pull request by IAmAnubhavSaini**
## Description

This PR takes care of migrating pages at once, so that git-status can report all of the changes to be committed.

Fixes #14411

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by IAmAnubhavSaini** [comment]
Example of migration of all pages at once, in DP.


Uploading Screen Recording 2022-06-28 at 9.47.22 AM.mov…

Running git sync after pages are migrated is pending.

**Comment by IAmAnubhavSaini** [comment]
@RakshaKShetty Please test DP for all pages migration. Pick an old git-connected app with multiple pages. And notice that all of the pages are migrated on app load.

**Comment by RakshaKShetty** [comment]
@IAmAnubhavSaini following are the issues 
1. After discard change only the current page gets migrated
2. The Status Api is failing each time and throwing an internal server error

**Comment by IAmAnubhavSaini** [comment]
This is challenging my understanding of how Appsmith works at every step. It might take a while.

**Comment by IAmAnubhavSaini** [comment]
Only 347 tests failing

Screenshot 2022-07-12 at 11 45 03 AM
Screenshot 2022-07-12 at 11 44 45 AM

**Comment by IAmAnubhavSaini** [comment]
Not working on it ATM

**Pull request closed without merging**
