### PR TITLE
Fix comment card click on the same thread after closing the inline thread

### LINKED ISSUE #5993: [Bug] Comment is not refocused on closing the comment thread and clicking on it again
## Description

- Add a comment at a position such that we need to scroll
- Click on the comment card link from the sidebar
- Close the comment thread, scroll away and click on the same card again
- The comment card is not refocused

### PR DESCRIPTION
**Pull request by rishabhsaxena**
## Description
Fixes #5993

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- manually

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix-comment-card-click 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 51.51 **(0.01)** | 33.52 **(0.01)** | 29.3 **(0)** | 52.13 **(0)**
 :green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 50.83 **(0.24)** | 40.25 **(0.84)** | 36.21 **(0)** | 55.04 **(0.27)**</details>

### CODE REVIEW

**Review by Rishabh-Rathod — APPROVED** [review]
LGTM

**Comment by rishabhsaxena** [comment]
Merging this as an exception: the failing test is unrelated to this PR and we need to push this to release on a priority.
Test run details: https://dashboard.cypress.io/projects/eyxvp8/runs/8381/test-results/c05eaa62-b525-496e-b0a6-4c13275abf3b

**Pull request merged**
