### PR TITLE
chore: Fix Security vulnerabilities

### PR DESCRIPTION
**Pull request by Irongade**
This PR fixes a security vulnerability.

For more context: https://github.com/appsmithorg/appsmith-ee/issues/2011

- Bug fix (non-breaking change which fixes an issue)
- Chore (housekeeping or task changes that don't impact user perception)

- [x] Manual
- [x] Jest
- [x] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by AmanAgarwal041 — DISMISSED** [review]
LGTM

**Review by KelvinOm — APPROVED** [review]

**Review by sharat87 — APPROVED** [review]

**Review by sharat87 — APPROVED** [review]

**Comment by Irongade** [comment]
Adding test plan approved label as per this comment [here](https://theappsmith.slack.com/archives/C040LHZN03V/p1692016211288019?thread_ts=1691230202.018089&cid=C040LHZN03V)

**Pull request merged**
