### PR TITLE
fix: Text getting clipped for Italic font in Table Widget V1

### LINKED ISSUE #14489: [Bug]: Text is getting clipped when Italic Font style is used
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Screenshot 2022-06-13 at 3 07 10 PM

### Steps To Reproduce

1. Drag and drop a Table widget
2. Change the Text size
3. Select Italic Font style

### Public Sample App

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by souma-ghosh**
## Description

For Italic and L sized font text is getting clipped towards the end in Table Widget V1.
This issue does not exist in Table Widget V2
After trying out a few solutions concluded that adding padding to the right fixes this issue without breaking any other existing code. Thus went ahead with this approach.

Fixes #14489 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manually tested

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by souma-ghosh** [comment]
Could you please review this one? @sbalaji1192

**Review by sbalaji1192 — DISMISSED** [review]

**Comment by souma-ghosh** [comment]
@dilippitchika This fix is for table widget v1. Will QA be able to test this out since we have table widget v2 already deployed?

**Comment by laveena-en** [comment]
Tested and verified.

**Review by sbalaji1192 — APPROVED** [review]

**Pull request merged**
