### PR TITLE
fix: deduct bottom bar height from sidebar's height in preview mode

### LINKED ISSUE #25949: [Bug]: In preview mode with SIDE NAV enabled, we get to see the bottom of the content (in the side bar) cut off
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In preview mode with SIDE NAV enabled, we get to see the bottom of the content (in the side bar) cut off.

This might be because we tend to disappear the footer in preview mode but with ME , since we show the env dropdown, the contents are overflowing(Though not completely sure)

### Steps To Reproduce

Screenshot 2023-08-02 at 6 29 39 PM

You can switch to SIDE NAV thru , app settings-->Navigation-->side

**_### Please re-assign to the correct team if not relevant to ME team_**

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

Cloud/Prod

### PR DESCRIPTION
**Pull request by dhruvikn**
## Description
Adjusts the sidebar height and fixes its overflowing after multiple environments started showing the bottom bar in preview mode.

Before - 
before

After - 
after

#### PR fixes following issue(s)
Fixes #25949

#### Type of change
- Bug fix (non-breaking change which fixes an issue)

- [x] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [x] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Comment by laveena-en** [comment]
Verified, PR looks good to me!

**Review by jsartisan — APPROVED** [review]

**Pull request merged**
