### PR TITLE
fix: negative spacing in list widget

### LINKED ISSUE #9084: [Bug]: Negative spacing in item spacing in list widget does not work anymore
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I pass negative spacing in item spacing of list widget, nothing happens. List widget ignores negative space altogether now.

### Steps To Reproduce

1. Drop a list widget
2. Pass `-5px` in item spacing.
3. Notice there is no change in spacing in list widget.

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by Tooluloope**
## Description

Allow minimum of -8px for item spacing in list widget
Fixes #9084 

## Type of change

- Bugfix (non-breaking change which fixes an issue)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/negative-spacing-in-list-widget 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 55.13 **(0.01)** | 37.08 **(0.03)** | 34 **(0)** | 55.64 **(0.01)**
 :green_circle: | app/client/src/selectors/commentsSelectors.ts | 85.25 **(1.64)** | 64.71 **(2.95)** | 73.33 **(0)** | 90.59 **(2.35)**
 :green_circle: | app/client/src/utils/validation/common.ts | 59.02 **(3.28)** | 57.5 **(4.37)** | 33.33 **(0)** | 58.33 **(3.33)**
 :green_circle: | app/client/src/widgets/ListWidget/widget/index.tsx | 61.95 **(0.26)** | 25.89 **(-0.26)** | 56.86 **(0.86)** | 60.79 **(0.28)**</details>

### CODE REVIEW

**Review by jsartisan — APPROVED** [review]

**Comment by YogeshJayaseelan** [comment]
@Tooluloope Verified this PR and observed the below issue 

Issue 1 : If the user enters values beyond -8 (for example -15, -25, -200) - The validation message shows 'Minimum allowed value is -8' but still the widget changes its spacing to -8 when the user passes -15, -20, -200.

https://www.loom.com/share/9192a8ee1acf40c8be6d973eb50d4e30

Expected result:
If the user passes values beyond -8 then just showing validation message would be enough and the widget should retain the original item spacing value

**Comment by YogeshJayaseelan** [comment]
@Tooluloope Verified the fix and they are working as expected. We can proceed further

**Review by jsartisan — APPROVED** [review]

**Pull request merged**
