### PR TITLE
fix: Known issues with Context Switching

### LINKED ISSUE #18191: [Bug]: Unable to delete the checkbox group items inside the list widget
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://user-images.githubusercontent.com/10436935/202157515-7c98082f-9e38-49aa-8336-29dc868875ba.mov

Unable to delete the checkbox group item when the checkbox group widget is inside a list widget.

#### Edit
This also is being observed in Dynamic Height DP where we are unable to open the dropdown on the first click

https://user-images.githubusercontent.com/10436935/202455642-c3369d3d-8a8e-4139-89ad-45be07719f2a.mov

### Steps To Reproduce

1. DnD a list widget
2. Place a checkbox group widget inside the list widget
3. Try to delete checkbox group items

### Public Sample App

_No response_

### Issue video log

_No response_

### Version

v1.8.7-SNAPSHOT

### LINKED ISSUE #18376: [Bug]: `navigateTo` function broken. Fails to set queryParams if the app is connected to Git
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

queryParams are not being set by `navigateTo` if the app is connected to Git

### Steps To Reproduce

1. Create a button with `navigateTo` and add some params
2. Connect your app to git
3. Click on the button, see there is no `queryParam` after navigation

### Public Sample App

_No response_

### Issue video log

https://www.loom.com/share/4cea3ab835e345df87e6eb4bf2a801ef

### Version

Cloud - v1.8.10

Front logo [Front conversations](https://app.frontapp.com/open/top_5zjf0)

### PR DESCRIPTION
**Pull request by rahulramesha**
## Description

This PR contains fixes for known issues with existing context switching,
- [ ] Retain url query parameters while focusing on the widget on Page load
- [ ] Fix scrolling issues on selection of widgets which cause unnecessary scrolling on dragging/resizing widgets
- [ ] Unable to delete the checkbox group items inside the list widget

Fixes #18376 
Fixes #18191

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Cypress

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by hetunandu — APPROVED** [review]

**Comment by Richarex** [comment]
- [X] #18376 :- This is fixed, verified it on release

- [X] #18191:- This is also fixed verified it on release

**Pull request merged**
