### PR TITLE
revert: "fix: dataTree mutation (#15952)"

### LINKED ISSUE #16378: [Bug]: Improve performance of function run on the editor
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Currently running a function on the editor on release takes slightly more time than it does on prod. This needs to be improved. Console implementation also causes a slow execution on it's DP and has the potential to further slow down the editor

https://www.loom.com/share/31f39247e2cb495ba39dffad08b3a689

### Steps To Reproduce

1. Execute function3 on [app on release](https://release.app.appsmith.com/app/automation-test-cases/page-1-62c6b8c60721a64d32ce5e09/edit/jsObjects/630cb8c7d982454fd2dafcbb?editName=false) and [app on prod](https://app.appsmith.com/app/whatsapp-messenger/page1-6304ddb4b189ad45f609d796/edit/jsObjects/630c9b1b8faf1771c76bc102)

### Public Sample App

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by Rishabh-Rathod**
## Description

This reverts commit dbcc643ccfb2af276698c89f922916ea0ad3ef8f.

Fixes #16378

## Type of change

- Revert changes which impacted performance

## How Has This Been Tested?

Manual performance verification 

@ramsaptami 

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by ohansFavour — DISMISSED** [review]

**Review by ohansFavour — APPROVED** [review]

**Review by ohansFavour — APPROVED** [review]

**Review by ramsaptami — COMMENTED** [review]
QA'd on DP

**Pull request merged**
