### PR TITLE
feat: Change Map Pin Color on Map Widget

### LINKED ISSUE #7620: [Feature] Change Map Pin Colour on Map Widget
## Summary

Change Map Pin Colour in Map widget.

## Motivation

It is important to distinguish different locations (pins) of the maps with a different colour? Would be be nice to have a property in the Default Makers property.

## Additional Context

This is the about the Map widget.

### PR DESCRIPTION
**Pull request by wmdev0808**
## Description
Change Map Pin Color in Map widget.
Fixes #7620 

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Test A
- Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>

    // Code coverage diff between base branch:release and head branch: feat/7620-map-pin-color 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.94 **(0.23)** | 41.67 **(0.84)** | 36.21 **(0)** | 56.99 **(0.25)**
 :red_circle: | app/client/src/widgets/MapWidget/component/index.tsx | 29.55 **(0)** | 21.62 **(-1.24)** | 0 **(0)** | 30.95 **(0)**</details>

### CODE REVIEW

**Comment by momcilo-appsmith** [comment]
Let's try #E0DEDE for default color.

**Comment by somangshu** [comment]
Hey @wmdev0808 we now have the [icon](https://www.figma.com/file/i80YbQLLs5mXthjIHclPpX/Appsmith-Design-System?node-id=4239%3A14011), We should implement this with the following changes:
- This will be the default icon
- If the color property does not exist we will show the default color, otherwise we show the given color.

**Review by somangshu — DISMISSED** [review]
LGTM

**Comment by somangshu** [comment]
@wmdev0808 merge the latest release, Run the action again, Move it to QA post that

**Comment by wmdev0808** [comment]
https://github.com/appsmithorg/appsmith/actions/runs/1415633985

**Comment by shwetha-ramesh** [comment]
@wmdev0808 @somangshu After going through the comments if I have got it right 
1. The icon will be as below.
image
2. The color property will not exist in _Default markers_ and the default color will be #ea4335; same as the initial marker when the widget is placed ? And this same color is maintained for multiple marked locations?

**Comment by somangshu** [comment]
@shwetha-ramesh that is correct

**Comment by shwetha-ramesh** [comment]
@wmdev0808 tested this PR. Noticed one issue when 'Create new marker' is enabled and when you click on the map the marker does not appear at the place where you click but it appears below the cursor (as seen in this video)
https://loom.com/share/4f0e0a818e8e4b26a59f817d87b59597

**Comment by wmdev0808** [comment]
> @wmdev0808 tested this PR. Noticed one issue when 'Create new marker' is enabled and when you click on the map the marker does not appear at the place where you click but it appears below the cursor (as seen in this video) https://loom.com/share/4f0e0a818e8e4b26a59f817d87b59597

@shwetha-ramesh , I think it is not related to this issue.

**Comment by wmdev0808** [comment]
https://github.com/appsmithorg/appsmith/actions/runs/1452576085

**Review by somangshu — APPROVED** [review]
LGTM

@shwetha-ramesh please verify the fix

**Comment by shwetha-ramesh** [comment]
@wmdev0808 retested the issue. Working as expected.

**Moving it to Done**

**Pull request merged**
