### PR TITLE
feat: added key pair auth for snowflake behind feature flag

### LINKED ISSUE #34375: UI for key pair auth
https://www.notion.so/UI-for-key-pair-auth-ee41bf8f3b6c4fc4a71caf77aa4c4552

### PR DESCRIPTION
**Pull request by AmanAgarwal041**
## Description
This PR adds snowflake datasource form config for key pair authentication
- Dropdown `Authentication type` that has options `USERNAME_PASSWORD` (default) and `KEY_PAIR` -> stores in `datasourceConfiguration.authentication.authType`
- Username text input field (mandatory) -> stores in `datasourceConfiguration.authentication.username` (was already existing)
- Private key file picker to accept file for private key (mandatory) -> stores in `datasourceConfiguration.authentication.privateKey`
- Private key passphrase as text input (optional) -> stores in `datasourceConfiguration.authentication.passphrase`

This feature is behind feature flag `release_snowflake_key_pair_auth_enabled` which shows this updated form only when its `true` else the form appears as it is today.

This PR also introduces a new auth type in `DBAuth` which extends `AuthenticationDTO` which is `KEY_PAIR` since there already existed `USERNAME_PASSWORD` so changed `basic` to `USERNAME_PASSWORD`.

Fixes #34375 
_or_  
Fixes `Issue URL`
> [!WARNING]  
> _If no issue exists, please create an issue first, and check with the maintainers if the issue is valid._

## Automation

/ok-to-test tags="@tag.Datasource, @tag.ImportExport"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9652220918>
> Commit: 2ecab82ae5047815cf8d5a0aef801b498009f677
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9652220918&attempt=1" target="_blank">Cypress dashboard</a>.
> Tags: `@tag.Datasource, @tag.ImportExport`

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [ ] No

## Summary by CodeRabbit

- **New Features**
  - Added support for new authentication types ("Basic" and "Key Pair") in the Snowflake plugin, enhancing flexibility for user authentication.
  - Introduced dynamic visibility of authentication fields based on selected authentication type and feature flags.

- **Improvements**
  - Enhanced the `DataSourceEditor` component to support feature flags, paving the way for future feature enhancements and customizations.

### CODE REVIEW

**Comment by sneha122** [comment]
@AmanAgarwal041 Changes look good to me, should we add unit test cases for this?

**Comment by sneha122** [comment]
@AmanAgarwal041 Tested the DP, Observed few things:
1. Key value pair should be default value in dropdown
2. When using valid credentials, test datasource is failing

**Comment by AmanAgarwal041** [comment]
> @AmanAgarwal041 Changes look good to me, should we add unit test cases for this?

Added a notion issue : https://www.notion.so/appsmith/42ab11bf621a42fb9670196b065d792e?v=2100cc622ba140d0b4dca0bd881a391a&p=c074b8bb44784390b84a441adc89e78f&pm=s

**Comment by AmanAgarwal041** [comment]
> @AmanAgarwal041 Tested the DP, Observed few things:
> 
> 1. Key value pair should be default value in dropdown
> 2. When using valid credentials, test datasource is failing

1. `USERNAME_PASSWORD` should be the default value as there might be existing snowflake db users who might encounter unwanted scenarios like key pair getting selected by default (while editing the existing datasource) when they were using `USERNAME_PASSWORD` by default
2. Fixed

**Comment by sneha122** [comment]
> > @AmanAgarwal041 Tested the DP, Observed few things:
> > 
> > 1. Key value pair should be default value in dropdown
> > 2. When using valid credentials, test datasource is failing
> 
> 1. `USERNAME_PASSWORD` should be the default value as there might be existing snowflake db users who might encounter unwanted scenarios like key pair getting selected by default (while editing the existing datasource) when they were using `USERNAME_PASSWORD` by default
> 2. Fixed

@AmanAgarwal041 First scenario would not occur because we would be doing migration for the existing users DBs so that they have authenticationType set as username password, this way, every time they edit the datasource, they would be seeing username password selected by default. The reason for setting key pair by default was since key pair is the most widely used method and anybody who is serious about their snowflake DB would go for key pair auth, we had decided that key pair would be default, let me know what you think

**Review by sneha122 — APPROVED** [review]

**Pull request merged**
