### PR TITLE
fix: git remote SSH url for Azure | BE

### LINKED ISSUE #12891: [Bug]: User is unable to add Azure DevOps git repo URL
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Screenshot 2022-04-13 at 1 15 02 PM

### Steps To Reproduce

1. click on `connect git` 
2. paste this URL - `git@ssh.dev.azure.com:v3/hubglobalnz/HubGlobal/AppSmith`

### Public Sample App

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by vishnu-gp**
## Description

Users were not able to add Git SSH URLs from some providers. This fixes the BE aspects of this issue.

image

Fixes #12891

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Tested using JUnit test cases
- Manual testing from UI

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by AnaghHegde — APPROVED** [review]

**Review by abhvsn — CHANGES_REQUESTED** [review]
Can we please add the testcase for different repo urls where the earlier implementation was failing

**Comment by AnaghHegde** [comment]
@abhvsn The failing case is already covered here - https://github.com/appsmithorg/appsmith/blob/08aab73cba60e24f1dc44787742982b1a6616c55/app/server/appsmith-server/src/test/java/com/appsmith/server/helpers/GitUtilsTest.java#L61

**Comment by abhvsn** [comment]
> @abhvsn The failing case is already covered here -
> 
> https://github.com/appsmithorg/appsmith/blob/08aab73cba60e24f1dc44787742982b1a6616c55/app/server/appsmith-server/src/test/java/com/appsmith/server/helpers/GitUtilsTest.java#L61

Shouldn't we do the same for isRepoPrivate method?

**Comment by AnaghHegde** [comment]
> #12891

The failing case is `git@ssh.dev.azure.com:v3/hubglobalnz/HubGlobal/AppSmith`. This is covered in the test that was added.

**Comment by AnaghHegde** [comment]
> > @abhvsn The failing case is already covered here -
> > https://github.com/appsmithorg/appsmith/blob/08aab73cba60e24f1dc44787742982b1a6616c55/app/server/appsmith-server/src/test/java/com/appsmith/server/helpers/GitUtilsTest.java#L61
> 
> Shouldn't we consider the updated regex for other methods in utils class?

The failing case is git@ssh.dev.azure.com:v3/hubglobalnz/HubGlobal/AppSmith. This is covered in the test that was added.

**Review by abhvsn — APPROVED** [review]

**Pull request merged**
