### PR TITLE
feat: Make table resizable in response view

### LINKED ISSUE #24465: [Feature]: make column widths adjustable in the query response
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

context: https://theappsmith.slack.com/archives/C040LHZN03V/p1686734826608749

currently the column widths are fixed, and cannot be dragged to resize. 

### Why should this be worked on?

I can't see the contents of fields beyond a certain length in the query response. Fixing this will help the user experience

### PR DESCRIPTION
**Pull request by Irongade**
For Action Response Viewer, In the table tab, the column widths of each table are fixed, and cannot be dragged to resize. This PR makes it possible to resize the columns.

Fixes #24465 
Fixes #24657

#### Type of change
- New feature (non-breaking change which adds functionality)
>
>
>
- [ ] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Comment by Aishwarya-U-R** [comment]
@Irongade - Merge latest release & trigger new oktotest. Cancelling the re-run since its past 12 hours from initial attempt.

**Comment by Aishwarya-U-R** [comment]
@Irongade - [All cypress passed here](https://cloud.cypress.io/projects/eyxvp8/runs/36522/overview?runStatus=PASSED&runStatus=FAILED&runStatus=RUNNING&runStatus=CANCELLED&runStatus=ERRORED&runStatus=OVERLIMIT&runStatus=NOTESTS&runStatus=TIMEDOUT&roarHideRunsWithDiffGroupsAndTags=1)

**Review by AmanAgarwal041 — APPROVED** [review]

**Pull request merged**
