### PR TITLE
fix: table button migration issues

### LINKED ISSUE #7796: [Bug]The delete button functionality is not working in Generate page
## Description

[What happened]The delete button functionality is not working in Generate page

### Steps to reproduce the behaviour:

[LOOM DEMO](https://www.loom.com/share/62ab59f19943479484b69e447d31e795)

### Important Details

- Version: [Cloud ]
- OS: MacOS
- Browser chrome
- Environment release

### PR DESCRIPTION
**Pull request by aswathkk**
## Description

Fixes the migration issues arrived from #7166 and #7310 

Fixes #7796 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Tested by using generate page as shown in the issue #7796 

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/table-button-migration 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 54.89 **(0)** | 37.03 **(0.01)** | 33.88 **(0)** | 55.5 **(0)**
 :green_circle: | app/client/src/selectors/commentsSelectors.ts | 79.84 **(1.61)** | 57.35 **(2.94)** | 70 **(0)** | 86.36 **(2.27)**
 :red_circle: | app/client/src/utils/DSLMigrations.ts | 74.17 **(-0.23)** | 65.44 **(-0.17)** | 69.66 **(-0.79)** | 73.98 **(-0.24)**
 :green_circle: | app/client/src/utils/migrations/TableWidget.ts | 83.74 **(0.16)** | 75.28 **(0.28)** | 92 **(0)** | 85.88 **(0.17)**</details>

### CODE REVIEW

**Review by somangshu — APPROVED** [review]
Deploy preview looks good, Issue related to button UI and onClick actions fixed.

Need to check the action onClick migration properly. @riodeuno please take a look

Approving to run the tests meanwhile

**Review by riodeuno — APPROVED** [review]

**Comment by aswathkk** [comment]
@somangshu Can we merge this now?

**Comment by somangshu** [comment]
@aswathkk I have only confirmed the positive test cases, Can you confirm if it all fine. We can merge it post that. @vivekverma2312 kindly help us out.

**Comment by RakshaKShetty** [comment]
@somangshu when i create a new crud page the delete functionality seems to be working, but in the old crud application, i still see the issue.

**Comment by RakshaKShetty** [comment]
@aswathkk As per the discussion the old apps wont be affected we can go ahead and merge it to release

**Pull request merged**
