### PR TITLE
fix: updated default content-type and default body format type

### LINKED ISSUE #11822: [Bug]: Set default content type to application/json instead of raw when creating API
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

- Currently when we create an API, the default content type which is set to be raw while we want it to be set to json 
- The body tab has group of tabs which by default should selected as json instead of raw.

Screenshot 2022-03-10 at 1 38 15 PM

### Steps To Reproduce

1. Go to datasource page and Create an API
2. When you go to API creation Page, you will see the default content type to be raw instead of json in the body tab, which should be fixed.

### Public Sample App

_No response_

### Version

Cloud and Self Hosted

### PR DESCRIPTION
**Pull request by AmanAgarwal041**
## Description

- No change in the headers when new API is created. HTTP Methods now have default Form Body Types. i.e `application/json` when `POST`, `PUT`, `PATCH` with `content-type` as  `application/json` header and `None` if `GET` and `RAW` if `DELETE`.
- Updated the body format type according to the header `content-type` present, if not then default is `RAW`
- Updated the setting of `content-type` header whenever the body format is changed to previousContentType when the format selected is `None` else whichever format is select like `Raw` -> `text/plain`, `Form Url Encoded` -> `application/x-www-form-urlencoded`, `JSON` -> `application/json` and `Multipart` -> `multipart/form-data`.

Fixes #11822 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Manually

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/api-default-content-type 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 56.33 **(-0.01)** | 37.74 **(0)** | 35.94 **(-0.01)** | 56.55 **(-0.01)**
 :red_circle: | app/client/src/sagas/ApiPaneSagas.ts | 16.59 **(-1.03)** | 1.24 **(0.05)** | 8.7 **(-0.39)** | 18.23 **(-1.18)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.71 **(-0.23)** | 40.83 **(-0.84)** | 36.21 **(0)** | 56.74 **(-0.25)**</details>

### CODE REVIEW

**Comment by cokoghenun** [comment]
Hey @AmanAgarwal041, small suggestion: Can we set the content-type only on methods that support a body i.e GET requests shouldn't have a content-type and we may also want to disable the body tab in this case. But on the other hand for methods that support a body be can have JSON be the default

Thanks so much for working on this, really appreciate 🙏

**Comment by AmanAgarwal041** [comment]
> Hey @AmanAgarwal041, small suggestion: Can we set the content-type only on methods that support a body i.e GET requests shouldn't have a content-type and we may also want to disable the body tab in this case. But on the other hand for methods that support a body be can have JSON be the default
> 
> Thanks so much for working on this, really appreciate 🙏

@cokoghenun Hey, I have updated the description and the code. Please have a look at it and let me know if there is a change.

**Comment by cokoghenun** [comment]
Hey @AmanAgarwal041 , this looks good!

Thanks for working on it 🙏

**Review by Irongade — APPROVED** [review]

**Pull request merged**
