### PR TITLE
fix: update Select All Checkbox on selection of all widgets

### PR DESCRIPTION
**Pull request by SaiCharanChetpelly31**
Fixes [#29386](https://github.com/appsmithorg/appsmith/issues/29386)
Added **updateSelectAllChecked** in **toggleNode** fn.

Added a recursive function that calculates the total count of all available widgets (including nested widgets).
image
Added jest test for Select All Checkbox.

## Summary by CodeRabbit

- **New Features**
  - Enhanced widget selection in the export modal with a "Select All" functionality.
  
- **Tests**
  - Added new test cases to verify the behavior of the "Select All" checkbox in the widget export component.

### CODE REVIEW

**Comment by SaiCharanChetpelly31** [comment]
Hi @rahulbarwal  I’m curious and excited to hear your thoughts on my pull request raised a while ago. Looking forward to your review!
Thank you.

**Comment by SaiCharanChetpelly31** [comment]
Hi @jacquesikot  I’m curious and excited to hear your thoughts on my pull request raised a while ago. Looking forward to your review!
Thank you.

**Comment by jacquesikot** [comment]
@SaiCharanChetpelly31 Sorry for the delay, we have this on our list and will get to it. I am currently addressing some other external PRs of higher priority. I should be able to get to this by next week. Thanks

**Comment by SaiCharanChetpelly31** [comment]
@jacquesikot @rahulbarwal I’m curious and excited to hear your thoughts on my pull request raised a while ago. Looking forward to your review!
Thank you.

**Pull request closed without merging**
