### PR TITLE
chore: Run NGINX with readonly root FS support

### PR DESCRIPTION
**Pull request by sharat87**
Part of supporting readonly root filesystem, gets NGINX to start without doing any writes to the filesystem, except for in `/tmp`.

### CODE REVIEW

**Comment by pratapaprasanna** [comment]
DP is failing to start here. because RTS is not running

**Review by pratapaprasanna — COMMENTED** [review]
RTS fails to start in dp

**Review by pratapaprasanna — COMMENTED** [review]
```
│ editor stderr | + popd                                                                                                                                                                                           │
│ editor stderr |                                                                                                                                                                                                  │
│ editor stdout | /opt/appsmith                                                                                                                                                                                    │
│ editor stdout |                                                                                                                                                                                                  │
│ editor stderr | + exec nginx -g 'daemon off;error_log stderr info;'                                                                                                                                              │
│ editor stderr |                                                                                                                                                                                                  │
│ editor stderr | 2023/09/22 08:15:05 [notice] 1502#1502: using the "epoll" event method                                                                                                                           │
│ editor stderr |                                                                                                                                                                                                  │
│ editor stderr | 2023/09/22 08:15:05 [notice] 1502#1502: nginx/1.18.0 (Ubuntu)                                                                                                                                    │
│ editor stderr | 2023/09/22 08:15:05 [notice] 1502#1502: OS: Linux 5.10.186-179.751.amzn2.x86_64                                                                                                                  │
│ editor stderr | 2023/09/22 08:15:05 [notice] 1502#1502: getrlimit(RLIMIT_NOFILE): 1048576:1048576                                                                                                                │
│ editor stderr |                                                                                                                                                                                                  │
│ editor stderr | 2023/09/22 08:15:05 [notice] 1502#1502: start worker processes                                                                                                                                   │
│ editor stderr |                                                                                                                                                                                                  │
│ editor stderr | 2023/09/22 08:15:05 [notice] 1502#1502: start worker process 1531                                                                                                                                │
│ editor stderr |                                                                                                                                                                                                  │
│ editor stderr | 2023/09/22 08:15:05 [notice] 1502#1502: start worker process 1532                                                                                                                                │
│ editor stderr |                                                                                                                                                                                                  │
│ editor stderr | 2023/09/22 08:15:05 [notice] 1502#1502: start worker process 1533                                                                                                                                │
│ editor stderr |                                                                                                                                                                                                  │
│ editor stderr | 2023/09/22 08:15:05 [notice] 1502#1502: start worker process 1534                                                                                                                                │
│ editor stderr |                                                                                                                                                                                                  │
│ editor stderr | 2023/09/22 08:15:05 [notice] 1502#1502: start worker process 1535                                                                                                                                │
│ editor stderr |                                                                                                                                                                                                  │
│ editor stderr | 2023/09/22 08:15:05 [notice] 1502#1502: start worker process 1536                                                                                                                                │
│ editor stderr |                                                                                                                                                                                                  │
│ editor stderr | 2023/09/22 08:15:05 [notice] 1502#1502: start worker process 1537                                                                                                                                │
│ editor stderr |                                                                                                                                                                                                  │
│ editor stderr | 2023/09/22 08:15:05 [notice] 1502#1502: start worker process 1538                                                                                                                                │
│ editor stderr |                                                                                                                                                                                                  │
│ backend stdout | Waiting for RTS to start ...
```

**Comment by sharat87** [comment]
@pratapaprasanna, can you share full logs please? I don't see anything wrong the logs snippet above? Can you elaborate on what I'm missing please? 🤔

**Comment by sharat87** [comment]
Building DP failed with this:

```
Deploy appsmith helm chart
Flag --recreate-pods has been deprecated, functionality will no longer be updated. Consult the documentation for other methods to recreate pods
Error: UPGRADE FAILED: cannot patch "ce27453-appsmith" with kind Service: Service "ce27453-appsmith" is invalid: spec.ports[1].name: Duplicate value: "appsmith"
Error: Process completed with exit code 1.
```

**Review by pratapaprasanna — DISMISSED** [review]

**Pull request merged**
