### PR TITLE
[FIX] modify regex to accept cyrillic characters in page name

### LINKED ISSUE #2210: [Feature] Allow Cyrillic characters in page name
## Summary

Allow all utf8 characters in page name.

## Motivation

A Russian user wants to use cyrillic characters in their page name.

## Additional Context

russian

### PR DESCRIPTION
**Pull request by kaushik94**
## Description
This will allow the usage of utf characters in page name. Today for example we are unable to add Cyrillic characters to page name. This PR will fix that.

Fixes #2210

## Type of change
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- ~~Added cypress test to edit page name and use Cyrillic characters inside the name~~

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>
No changes to code coverage between the base branch and the head branch</details>

### CODE REVIEW

**Comment by kaushik94** [comment]
@pranavkanade and @rishabhsaxena can you please review this at your convenience. I will have to add tests and I will do that today in some time.

**Comment by kaushik94** [comment]
@mohanarpit I am somehow unable to change the Fixes # to link it to [this issue](https://app.zenhub.com/workspaces/appsmith-platform-pod-5fbaa4ecb2915c001e8db27c/issues/appsmithorg/appsmith/2210) The issue numbered 2210 doesn't show up for me in suggestions. Can you please go ahead and change it. Maybe it works for you.

**Review by pranavkanade — DISMISSED** [review]
LGTM!

**Review by hetunandu — CHANGES_REQUESTED** [review]
Reintroduces this bug #765

**Comment by kaushik94** [comment]
@hetunandu nice catch. I completely missed this case. I have updated the PR to handle special characters. I have copy pasted this regex from [here](https://www.regextester.com/3319). Please let me know if I need to make any changes. Thanks.

**Review by hetunandu — APPROVED** [review]

**Review by NandanAnantharamu — APPROVED** [review]
Approved for test run

**Pull request merged**
