### PR TITLE
feat: Migrated callout component to design system

### LINKED ISSUE #17288: [Task]: Migrate callout component to design system
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- Migrate the callout component to design system package.
- Delete callout from main repository.
- Replace the usage in main repo.

### PR DESCRIPTION
**Pull request by albinAppsmith**
## Description

Migrated callout component to design system package.

Fixes #17288

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Tested in local

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by tanvibhakta — APPROVED** [review]

**Comment by shadabbuchh** [comment]
This PR has been tested. No issues found.

**Review by ankitakinger — APPROVED** [review]

**Pull request merged**
