### PR TITLE
Fixed comment missing issue when user role is changed

### LINKED ISSUE #5859: 8.f the user changes the role of the users in the application than the old comments won't be retained

### PR DESCRIPTION
**Pull request by nayan-rafiq**
## Description
This PR fixes the issue: Comments are missing when an user's role is changed in an organization.

Fixes #5859 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Tested on local machine

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by trishaanand** [comment]
@nayan-rafiq : Hey Nayan! You are missing the same code changes in the function `removeUserRoleFromOrganizationGivenUserObject` which handles removing the user from the organization. In case a user's role is changed, we first remove the user and then add the user with the new role.

**Comment by nayan-rafiq** [comment]
@trishaanand I think it's there also in the `removeUserRoleFromOrganizationGivenUserObject` function. It's in the line numbers 254, 270, 277

**Comment by trishaanand** [comment]
> @trishaanand I think it's there also in the `removeUserRoleFromOrganizationGivenUserObject` function. It's in the line numbers 254, 270, 277

Aah I can see that! Thanks!

Could you also add a test case for the failing scenario which this PR fixes?

**Comment by nayan-rafiq** [comment]
@trishaanand ok, I'll do this ASAP

**Review by sharat87 — APPROVED** [review]
Looks good to be merged. Please squash merge once the CI is finished. Thanks!

**Comment by nayan-rafiq** [comment]
@trishaanand I've added tests to make sure comment thread policy is updated when a new user is added, removed or role changed. Would you please take sometime to review this?

**Review by trishaanand — APPROVED** [review]

**Pull request merged**
