### PR TITLE
Redirecting to view mode of datasource after authorization

### LINKED ISSUE #5759: [Bug] For google sheet datasource, on successful connection user gets redirected back to same page
## Description
User get redirected back to same editor page for google sheet datasource on successful connection

### Steps to reproduce the behaviour:
1. Create New Google sheet datasource
2. Click Continue
3. Follow all steps

### Important Details
- Version: [Cloud]
- OS: [MacOSX]
- Browser [chrome, safari]
- Environment [release]

### PR DESCRIPTION
**Pull request by nidhi-nair**
## Description
1. Changing the redirection URL to redirect user to view mode, on google sheet datasource successful connection.
2. Remove the `New Query` btn from G Sheet datasource edit mode

Fixes #5759 

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/view-mode-true 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 53.84 **(0.01)** | 35.81 **(0.01)** | 32.44 **(0.01)** | 54.42 **(0.01)**
 :green_circle: | app/client/src/pages/Editor/SaaSEditor/DatasourceForm.tsx | 36.26 **(1.61)** | 17.39 **(0.25)** | 6.25 **(0.37)** | 38.55 **(1.99)**</details>

### CODE REVIEW

**Review by pranavkanade — DISMISSED** [review]

**Review by rishabhsaxena — APPROVED** [review]

**Comment by rishabhsaxena** [comment]
Hey QQ should we keep the `success=true` param as well to show the success toast?

**Comment by pranavkanade** [comment]
> Hey QQ should we keep the `success=true` param as well to show the success toast?

The view mode already shows `Datasource Connected` with green check. Which is static, we should fix that and make it dynamic depending on actual connection status.

**Comment by pranavkanade** [comment]
@nidhi-nair this fix for redirection did not work. I tested it on release, and the redirection URL does not have `viewMode=true` query param.

**Pull request merged**
