### PR TITLE
fix: undefined evaluted value text widget

### LINKED ISSUE #8442: [Bug]: Text Widget -The Cell background and Text size field evaluated values are undefined after enabling JS
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It is observed that by enabling JS on the Cell background colour and the Text Size field on the text widget, the evaluvated value is 'undefined'

https://github.com/appsmithorg/appsmith/issues/8439

### Steps To Reproduce

```markdown
1.Launch appmsith app in release/Prod environment
2.Drag and drop text widget
3.Open property pane 
4.Choose cell background colour an enable JS and click on the cell background colour field and observe the evaluated value 
5.Similarly check for the text size field and observe
```

### Environment

Release

### Version

Cloud

### PR DESCRIPTION
**Pull request by keyurparalkar**
> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Description
This PR includes the following changes:

- Enabled `isBindProperty` for `text size` and `cell background`
- Added `regex` and `expected` validation params to the `cell background` property.
- Added `allowedValues` params in the validation of `text size` property.
- Addition of cypress test case to check for validation of text size and cell background changes.

Fixes #8442 

> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Created a cypress spec file: `TextWidget_BgColor_TextSize_spec.js`. This test validates the following things:

- Changing the cell background without JS mode.
- Changing the cell background with JS mode.
    - Validates if the HTML color value given in the Cell background matches with evaluated value in panel and the actual text widget.
    - Validates if the HEX color value given in the Cell background matches with evaluated value in panel and the actual text widget.
    - Validates if blank value changes the color to transparent both in evaluated values panel and actual text widget bg color.
- Changing the text size via dropdown.
- Changing the text size with JS mode:
    - Validates if the value given in text size matches with evaluated value in panel and the text size in text widget.
    - Validates if the blank value given in text size matches with evaluated value in panel and default text size in text widget.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/fix-undefined_evaluted_value_text_widget 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 55.13 **(0)** | 37.16 **(-0.01)** | 33.97 **(0)** | 55.64 **(0)**
 :red_circle: | app/client/src/selectors/commentsSelectors.ts | 83.61 **(-1.64)** | 61.76 **(-2.95)** | 73.33 **(0)** | 88.24 **(-2.35)**</details>

### CODE REVIEW

**Review by jsartisan — APPROVED** [review]

**Comment by shwetha-ramesh** [comment]
@keyurparalkar Working as expected. Moving to Done.

**Pull request merged**
