### PR TITLE
fix: Show connect your data prompt correctly

### LINKED ISSUE #29680: Bug: Connect with your data walkthrough appearing after using a template when a user already connected with a datasource before
[Notion card](https://www.notion.so/appsmith/Connect-with-your-data-walkthrough-appearing-after-using-a-template-when-a-user-already-connected-wi-1e547dee4ec446dcb0026297c44e5e22?pvs=4)

Expected: Do not show the `Connect with your data` walkthrough for: 
new user + any datasource in the workspace that is not a sample one (since an active datasource is something already in use in that app, we cannot use that definition). 
([slack ref](https://theappsmith.slack.com/archives/C05P3ME9MBR/p1702577444125589?thread_ts=1702531292.214919&cid=C05P3ME9MBR))

### PR DESCRIPTION
**Pull request by rahulbarwal**
## Description

**Problem** 
We noticed that some users go through "start with data" option and then "forks a starter building block from canvas", this condition prevents showing the popup if datasource is already connected.

With this PR we add a check, to ensure that if user already has some datasources then it prevents showing the popup if datasource is already connected.

#### PR fixes following issue(s)
Fixes #29680

- Bug fix (non-breaking change which fixes an issue)
>
>
>
- [x] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

## Summary by CodeRabbit

- **Refactor**
  - Improved the logic for displaying the datasource prompt in the editor to enhance user experience.
  - Optimized data retrieval for app-wide datasources.

### CODE REVIEW

**Review by rahulbarwal — COMMENTED** [review]
/ok-to-test

**Review by rahulbarwal — COMMENTED** [review]
/build-deploy-preview

**Review by jacquesikot — APPROVED** [review]

**Pull request merged**
