### PR TITLE
fix: show error when Required is true and default selected value is e…

### LINKED ISSUE #15391: [Bug]: No error thrown if widget is set as Required and no option is selected
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The Select widget family does not throw any error if the `Required` property is enabled and no option(s) is selected.

https://www.loom.com/share/04fc54ec17b543b386e78937d4378ea7

### Steps To Reproduce

1. D&D any widget from the Select Family.
2. Enable the `Required` property.
3. No delete the text in the `Default Value` property.

**Expected:** An error should be thrown.

### Public Sample App

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by SaiCharanChetpelly31**
Fixes #15391 
Showing error message similar to input widget.

Wrapped errortooltip around Dropdowncontainer.
Added two props showError and errorMessage.
Added jest unit tests since this is a functionality.

## Summary by CodeRabbit

- **New Features**
  - Introduced error handling for the SelectWidget, displaying error messages when conditions are met.
  - Added a new ErrorTooltip component for visual feedback on errors.
  
- **Bug Fixes**
  - Enhanced validation logic to ensure proper error handling for required fields and default selections.
  
- **Tests**
  - Implemented comprehensive unit tests for the SelectWidget to verify validation and error handling functionalities.

### CODE REVIEW

**Comment by SaiCharanChetpelly31** [comment]
hI @shadabbuchh @somangshu Could you please take this PR forward for review and add a reviewer?

Thanks in advance.

**Comment by SaiCharanChetpelly31** [comment]
Hi @ramsaptami can you please add a reviewer and take this pr forward for review?
Thanks in advance.

**Comment by SaiCharanChetpelly31** [comment]
Hi @riodeuno @jsartisan can you please review pr?

**Comment by jsartisan** [comment]
@SaiCharanChetpelly31 Can you share a video on how the solution works? I couldn't see any tooltop when is required was true and there is no value. 
Also, the original issue talks about the all teh select widget family ( tree select, multi tree select, multiselect and single select ), and the files you changed are only of select widget.

**Comment by SaiCharanChetpelly31** [comment]
> @SaiCharanChetpelly31 Can you share a video on how the solution works? I couldn't see any tooltop when is required was true and there is no value. Also, the original issue talks about all the select widget family ( tree select, multi tree select, multiselect, and single select ), and the files you changed are only of select widget.

Here is the video

https://github.com/user-attachments/assets/ac2ddd42-e011-4894-9b50-987f85d8387d

Forgot to fix for all select widgets, i will add it now.

**Comment by jsartisan** [comment]
@SaiCharanChetpelly31 The ` this.props.defaultOptionValue === ""` is not needed IMO. If I am marking `isRequired` as true and I just unselected the selected options, shouldn't get the tooltip? With that check, we are not. 

What you have done is, you are checking if the `defaultOptionValue` is also empty which is not right.  The main idea was to show a tooltip if there is no selected value and the widget value is marked as required.

This is the exact reason I was not able to trigger the tooltip before
>   I couldn't see any tooltop when is required was true and there is no value.

**Comment by SaiCharanChetpelly31** [comment]
@jsartisan Thanks for your reply. Understood. I will remove logic related to defaultValue in all select family widgets.

**Comment by SaiCharanChetpelly31** [comment]
@jsartisan Please review this PR

**Comment by jsartisan** [comment]
@SaiCharanChetpelly31 Hey give me a day. I'll check this in the evening.

**Comment by jsartisan** [comment]
@SaiCharanChetpelly31 Really sorry for the delay. Got busy with tasks. 

I tried the latest commit and it does not work properly. I saw the tooltip for one in edit mode but can't see it at all in deploy mode.


https://github.com/user-attachments/assets/4a10d8e2-7dc7-4ded-a157-4b635e9afcfe

I can see the red border but no tooltip.

**Review by jsartisan — COMMENTED** [review]
The solution not working properly.

**Comment by SaiCharanChetpelly31** [comment]
> The solution not working properly.

I will recheck and get back to ypu. Thanks for reviewing.

**Pull request closed without merging**
