### PR TITLE
fix: updated height for page view

### LINKED ISSUE #9858: [Bug]: Vertical scroll in embed mode
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There's a scroll that's appearing on pages in embed mode even when there aren't a lot of widgets in the page.
The default page height seems to be fixed and doesn't resize even when the page is empty.

### Steps To Reproduce

1. Add one widget
2. Try to embed it
3. See a scroll appear even when there are no widgets that warrants a scroll

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by techbhavin**
## Description

> CanvasWidget Height change to `100%`

Fixes #9858 

## Type of change

- Bugfix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/vertical-page-scroll 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 55.7 **(0)** | 37.06 **(0.01)** | 35.75 **(0)** | 56.05 **(0)**
 :green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.94 **(0.23)** | 41.67 **(0.84)** | 36.21 **(0)** | 56.99 **(0.25)**
 :red_circle: | app/client/src/widgets/CanvasWidget.tsx | 95.45 **(-0.47)** | 66.67 **(0)** | 100 **(0)** | 97.56 **(-0.27)**</details>

### CODE REVIEW

**Review by Tooluloope — APPROVED** [review]

**Comment by chandannkumar** [comment]
Tested this PR and working as expected

**Pull request merged**
