### PR TITLE
fix:  Not able to see all the options of Font property as it is not scrollable +  Canvas scroll to top when I drop Tab widget on the canvas

### LINKED ISSUE #13582: [Bug]: Canvas scroll to top when I drop Tab widget on the canvas
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Observed this issue on Tab change as well.

[LOOM DEMO](https://www.loom.com/share/0b4fff84ba0144dd8d51d2da1e57f459)

### Steps To Reproduce

1. Drop few widgets on top of the canvas so that visible screen have widgets now
2. Scroll the canvas and the drop Tab widget
3. Observe that the canvas scroll back to top

### Public Sample App

_No response_

### Version

Cloud/Release

### LINKED ISSUE #13591: [Bug]-[4788]:Next/Previous icon on Tab widget is not functional with single click but only working when we click and hold
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

[LOOM DEMO](https://www.loom.com/share/b717c6db52eb47b7bbb3ceee88ca15b3)

### Steps To Reproduce

The issue is if we click it once it does not work. You have to click and hold it to be functional. Currently on prod we have click behaviour and not click + hold.

### Public Sample App

_No response_

### Version

Cloud/ Release

### LINKED ISSUE #13598: [Bug]: Not able to see all the options of Font property as it is not scrollable
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

[LOOM DEMO](https://www.loom.com/share/600c44f882f94d249994b2d5145ba4c6)

### Steps To Reproduce

1. Drag and drop a Text widget
2. Click on Font Family property
3. Observed that the options are getting clipped and we do not have scroll

### Public Sample App

_No response_

### Version

Cloud

### LINKED ISSUE #13641: [Bug]: Older versions of widgets don't support app theming but show properties which correspond to theming
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Older versions of input/select/multiselect widgets have theme properties like box shadow and border radius, but they don't work when the user tries to update the widget's properties. 

### Steps To Reproduce

1. Go to an app which has older input widget
2. Theme the app's border radius to be different
3. Go to the older input widget
4. Try changing the border radius or resetting the value
5. Observe that it doesn't change

### Public Sample App

_No response_

### Version

Release

### PR DESCRIPTION
**Pull request by jsartisan**
Fixes #13582
Fixes #13598
Fixes #13591
Fixes #13641

## Type of change

> Please delete options that are not relevant.

- Bugfix

## How Has This Been Tested?
- Manually tested

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>

    // Code coverage diff between base branch:release and head branch: fix/theming-bugs 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | app/client/src/selectors/commentsSelectors.ts | 85.25 **(1.64)** | 64.71 **(2.95)** | 73.33 **(0)** | 90.59 **(2.35)**
 :green_circle: | app/client/src/widgets/TabsWidget/component/PageTabs.tsx | 97.87 **(-0.05)** | 85 **(1.67)** | 100 **(0)** | 97.73 **(-0.05)**
 :green_circle: | app/client/src/widgets/TabsWidget/component/index.tsx | 90.32 **(5.61)** | 61.11 **(0.58)** | 78.57 **(15.41)** | 88 **(7.7)**</details>

### CODE REVIEW

**Review by keyurparalkar — DISMISSED** [review]
LGTM!

**Comment by vivekverma2312** [comment]
@jsartisan Tab issue is tested and working fine. I have tested Font Family issue on [13105](https://github.com/appsmithorg/appsmith/pull/13105)

**Review by sbalaji1192 — APPROVED** [review]

**Pull request merged**
