### PR TITLE
fix: table color picker issue

### LINKED ISSUE #9526: [Bug]: Color picker in TableWidget sets a value even after clearing
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After clearing an existing value inside color picker, default value of green color is automatically getting populated into the color picker.

https://user-images.githubusercontent.com/10436935/144408747-8ab3cb84-99eb-4607-9c61-d146c54f9bde.mov

### Steps To Reproduce

1. Add Table widget
2. Open the property pane for Button type column
3. Select a new button background color
4. Clear the button color property
5. Once it is empty wait for some time and notice that the field is getting filled with hex code for green color.

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by aswathkk**
## Description

Removed `defaultColor` property to avoid re-populating the cleared color.

Fixes #9526 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Manually tested. Cypress test is also added to verify

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/table-color-issue 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 55.12 **(0)** | 37.05 **(0.01)** | 34.02 **(0)** | 55.64 **(0)**
 :green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.94 **(0.23)** | 41.67 **(0.84)** | 36.21 **(0)** | 56.99 **(0.25)**
 :red_circle: | app/client/src/widgets/TableWidget/index.ts | 43.75 **(-6.25)** | 100 **(0)** | 0 **(0)** | 43.75 **(-6.25)**
 :red_circle: | app/client/src/widgets/TableWidget/widget/propertyConfig.ts | 95.92 **(-0.08)** | 100 **(0)** | 93.55 **(0)** | 95.92 **(-0.08)**
 :green_circle: | app/client/src/widgets/TableWidget/widget/propertyUtils.ts | 24.44 **(0.01)** | 8 **(0)** | 20 **(0)** | 23.02 **(0.07)**</details>

### CODE REVIEW

**Review by Tooluloope — APPROVED** [review]

**Comment by vivekverma2312** [comment]
@aswathkk Deploy preview is tested and working fine.

**Pull request merged**
