### PR TITLE
feat: Hide shadows of hiddens objects during page loading in deploy view

### LINKED ISSUE #11203: [Feature]:Hide shadows of hiddens  objects during page loading in deploy view
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Hi, 
when i set visible = false in every objects it is not beautiful to see in deployed version during page loading
 the shadow of this object... 

### Why should this be worked on?

The end user , if the page spend some time to load ,  might get disoriented to see shadows of objects that not exixst. 
It is rigth only in designe time.

### PR DESCRIPTION
**Pull request by wmdev0808**
## Description
when i set visible = false in every objects it is not beautiful to see in deployed version during page loading
the shadow of this object...

Fixes #11203 

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Test A
- Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: feat/11203-hide-invisible-widget-in-view-mode 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 55.68 **(-0.01)** | 37.08 **(0)** | 35.25 **(0)** | 55.94 **(-0.01)**
 :red_circle: | app/client/src/utils/WorkerUtil.ts | 89.76 **(0)** | 70.59 **(-1.96)** | 100 **(0)** | 93.33 **(0)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.71 **(-0.23)** | 40.83 **(-0.84)** | 36.21 **(0)** | 56.74 **(-0.25)**
 :red_circle: | app/client/src/widgets/CanvasWidget.tsx | 94.12 **(-1.8)** | 62.5 **(-4.17)** | 100 **(0)** | 95.83 **(-2)**</details>

### CODE REVIEW

**Review by somangshu — COMMENTED** [review]
Tested all changes on the deploy preview and it works fine. Will need QA though

Not sure about the code change though @riodeuno please check for any implication you can think of

**Review by riodeuno — APPROVED** [review]

**Comment by vivekverma2312** [comment]
@wmdev0808 Tested and working fine.

**Pull request merged**
