### PR TITLE
fix: #8530 Added Config for Menu JS Convertible

### LINKED ISSUE #8530: [Bug]: Table menu colour does not have JS option
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It is observed that table menu column type does not have JS options for the Menu colour
Screenshot 2021-10-14 at 1 23 16 PM

### Steps To Reproduce

```markdown
1.Launch appmsith app in release/Prod Environment 
2.Drag and drop table widget 
3.Change any of the column type to Menu button and check for the JS options on Menu colour and observe
```

### Environment

Release

### Version

Cloud

### PR DESCRIPTION
**Pull request by vibhandikyash**
Fixes #8530 

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Tested locally.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/8530-table-menu-color-jsconvertible 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 55.04 **(0)** | 36.93 **(-0.01)** | 33.78 **(0)** | 55.52 **(0)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.04 **(-0.22)** | 40.42 **(-0.83)** | 34.48 **(0)** | 55.96 **(-0.26)**
 :green_circle: | app/client/src/widgets/TableWidget/widget/index.tsx | 29.88 **(0)** | 9.8 **(0.06)** | 30 **(0)** | 29.54 **(0)**</details>

### CODE REVIEW

**Review by somangshu — DISMISSED** [review]

**Comment by somangshu** [comment]
https://github.com/appsmithorg/appsmith/actions/runs/1408383291

**Comment by vibhandikyash** [comment]
https://github.com/appsmithorg/appsmith/actions/runs/1448298789

**Review by techbhavin — APPROVED** [review]

**Comment by shwetha-ramesh** [comment]
@vibhandikyash Tested this on release I see below 2 issues and hence reopening this issue.
1. _Evaluated value_ shows 'undefined'
2. When JS is enabled the default value shows blank and later when the option is changed the value appears (Refer video)

https://loom.com/share/0fb85812c9e34c1fa754cbac92b0aa3d

**Pull request merged**
