### PR TITLE
fix: refresh profile image on the header when a new image is uploaded

### PR DESCRIPTION
**Pull request by caspero-62**
## Description

I have been able to fix the issue of profile image change on the header after the user changes the profile picture or removes it. When the user changes the profile page, I have been able to update the `state.ui.users.currentUser.photoId` to the updated photo id and change it to an empty string (clearing the photo id state) as soon as the user removes the profile image.

Fixes # (issue)
#7305 

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
The bug was tried to be reproduced over again on my end and couldn't be reproduced

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by caspero-62** [comment]
Okay then, would get to it right now

**Review by rishabhsaxena — DISMISSED** [review]
Looks good! Thanks @caspero-62!

**Comment by caspero-62** [comment]
Hello, is there anything I need to add before this PR is merged?

**Comment by rishabhsaxena** [comment]
Actually it looks good, there seemed to be a test case failing, have re-run it since it didn't seem related to the changes in the PR

**Comment by caspero-62** [comment]
Okay, I understand. Thanks

**Comment by caspero-62** [comment]
Hello @pranavkanade, Please this pr has been stale for a while. Is there anything holding it up from being merged?

**Comment by pranavkanade** [comment]
@caspero-62 Hey! there seems to be multiple failures in the CI for this PR. I'll look into it

**Comment by caspero-62** [comment]
> @caspero-62 Hey! there seems to be multiple failures in the CI for this PR. I'll look into it

Alright then!
Thanks

**Comment by pranavkanade** [comment]
@caspero-62 can you please merge the latest release to your branch?
ps: couldn't do it myself, ran into permission issues

**Comment by caspero-62** [comment]
> @caspero-62 can you please merge the latest release to your branch?
> ps: couldn't do it myself, ran into permission issues

Alright, I'll do that. Thanks

**Comment by caspero-62** [comment]
I guess all checks are passing now :)

**Review by rishabhsaxena — APPROVED** [review]

**Comment by pranavkanade** [comment]
@caspero-62 We really appreciate your efforts for this PR!! As promised, your swag is on its way :)
Please let us know, how your experience was? and what we could've done better? Our Discord - https://discord.gg/gG6unH8n

**Comment by caspero-62** [comment]
> @caspero-62 We really appreciate your efforts for this PR!! As promised, your swag is on its way :)
> Please let us know, how your experience was? and what we could've done better? Our Discord - https://discord.gg/gG6unH8n

>@pranavkanade it's my pleasure contributing to this. Thanks for your help in the PR and also for the swag 

As for my experience, it was awesome actually. I got to learn stuff and contribute to a meaningful project. 
I'm already on the discord channel :)

**Pull request merged**
