### PR TITLE
fix: REST API multimedia file upload issue fixed

### LINKED ISSUE #32378: [Feature]: Rest API Plugin: provide option to upload binary data (multimedia files)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Currently REST API plugin does not seem to have any option that allows users to directly transmit binary data / file content . 
e.g. Postman provides a `binary` tab: 
https://theappsmith.slack.com/files/U035SFJHW3A/F06S5N2BUTX/image.png

### Why should this be worked on?

This should take away a lot of confusion related with file uploads using REST API query.

Front logo [Front conversations](https://app.frontapp.com/open/top_6w64b0)

### PR DESCRIPTION
**Pull request by sneha122**
## Description
If we use REST API action and file picker widget to upload any multimedia files (image, audio, video, pdf, xlsx), The file upload would be successful but file would get corrupted upon uploading. This was happening because file picker widget encodes this file to base64 format, and we were uploading this same base64 string using REST API url. Instead we should have decoded this base64 and then uploaded the file to retain the original contents of the file. 

This PR fixes that issue by adding a new tab in body of the REST API action called `binary`, once we select this tab, we get autogenerated header for `Content-Type: application/octet-stream`, in this binary input field we can then provide base64 encoded file contents, the server then decodes the contents before triggering the respective REST API and uploading the file.

### Steps to test the issue
1. Add a file picker widget on canvas
2. Select data format as `Base64`
3. Upload any of pdf, image, audio, video, xlsx in file picker
4. Create a REST API action using [Dropbox upload API](https://www.dropbox.com/developers/documentation/http/documentation#files-upload)
5. Configure the API headers as mentioned in the documentation, also configure file name in the header correctly
6. Go to body tab, select binary and file contents in input box using binding like {{Filepicker1.files[0].data}}
7. Execute this API
8. Now go to your dropbox account and check the uploaded file, you should be able to successfully preview it

Fixes #32378  
_or_  
Fixes `Issue URL`
> [!WARNING]  
> _If no issue exists, please create an issue first, and check with the maintainers if the issue is valid._

## Automation

/ok-to-test tags="@tag.Datasource"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/8844375718>
> Commit: 3316290a4d7d77ae3f9d8969245c5f470ef1ab5c
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=8844375718&attempt=1" target="_blank">Click here!</a>

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [x] No

## Summary by CodeRabbit

- **New Features**
	- Added support for binary file uploads in API requests, including handling of base64-encoded files.
	- Expanded content type options to include a new "BINARY" type for API requests.

- **Tests**
	- Implemented new tests to verify the functionality of binary file uploads with dynamic data binding.

- **Bug Fixes**
	- Ensured correct handling and auto-generation of headers for binary file types and form urlencoded data formats.

### CODE REVIEW

**Review by AmanAgarwal041 — APPROVED** [review]

**Review by NilanshBansal — APPROVED** [review]
LGTM

**Comment by NilanshBansal** [comment]
@sneha122 this change needs a documentation update as `Binary` tab needs to be selected to upload files. 
https://docs.appsmith.com/build-apps/how-to-guides/Send-Filepicker-Data-with-API-Requests

Can you please inform the documentation team about the same.

**Comment by sneha122** [comment]
> @sneha122 this change needs a documentation update as `Binary` tab needs to be selected to upload files. https://docs.appsmith.com/build-apps/how-to-guides/Send-Filepicker-Data-with-API-Requests
> 
> Can you please inform the documentation team about the same.

@NilanshBansal Yes I will be informing them about this change

**Comment by PrasannaPtools** [comment]
Thanks!

I just need to update to the latest then?

**Comment by sneha122** [comment]
@PrasannaPtools Hi are you using self hosted version of appsmith? If yes you will have to wait for next update, post that you can update your version. I can inform you once that upgrade happens.

**Comment by NilanshBansal** [comment]
@sneha122 this issue still persists, can you please help in debugging this further? Did we have a regression? I tried reproducing the exact same replication steps as mentioned in the issue description but the uploaded file is still corrupted.

Please check the attached video below.
https://github.com/user-attachments/assets/4e31aa3a-7532-4d37-98e5-743b3a8352c5

cc: @appsmithorg/query-widgets-pod @vivek-appsmith

**Comment by sneha122** [comment]
> @sneha122 this issue still persists, can you please help in debugging this further? Did we have a regression? I tried reproducing the exact same replication steps as mentioned in the issue description but the uploaded file is still corrupted.
> 
> Please check the attached video below. https://github.com/user-attachments/assets/4e31aa3a-7532-4d37-98e5-743b3a8352c5
> 
> cc: @appsmithorg/query-widgets-pod

@NilanshBansal As mentioned in the steps above, the data format for file picker should be base64, what you have in your video is binary and hence it is not working. There's no regression here

**Comment by NilanshBansal** [comment]
Yes @sneha122, please ignore my comment above. This works fine. Apologies for the inconvenience.
Here is the final working version acc to the testing above!
cc: @appsmithorg/query-widgets-pod 

https://github.com/user-attachments/assets/1a6a5379-4114-45e7-bc55-3a1cb6ed1406

**Pull request merged**
