### PR TITLE
fix: Modal widget close after rename

### LINKED ISSUE #23475: [Bug]: Modal does not close after rename
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Modal does not close after rename

https://www.loom.com/share/093d1e58c8414ac3aca0cf6d3475cd7c

### Steps To Reproduce

1. Drag and drop Modal widget
2. Rename the widget and click on close button or icon button (x) to close it. 

Expected : The Modal should close on clicking on close button even after rename

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by iSatVeerSingh**
## Description
Added code to create "dynamicTriggetPathList" property on child IconButton and Button widget when Blueprint Operation MODIFY_PROPS add 'onClick' property to child widgets.

The issue is happening because when Modal Widget is created, the child widgets have onClick: closeModal reference of Modal widget but do not have dynamicTriggetPath: [{key: onClick}] property. This PR fixes this issue.
#### PR fixes following issue(s)
Fixes #23475

#### Media
[Screencast from 2023-06-25 18-32-26.webm](https://github.com/appsmithorg/appsmith/assets/85070570/18f418be-c26e-4d4e-ab97-ef3db23a6832)

#### Type of change
- Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### How Has This Been Tested?
- [x] Manual

#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Comment by sbalaji1192** [comment]
@iSatVeerSingh Thanks for showing interest in fixing this issue. 
The fix provided doesn't seem related to the actual cause of the issue. I have attached a video.

https://github.com/appsmithorg/appsmith/assets/5328605/99db6c53-566e-4755-858d-51c762422cbd

CC @somangshu

**Comment by iSatVeerSingh** [comment]
@sbalaji1192 Let me explain. So I have setup frontend and backend with java locally on my computer. I have setup backend for development. 

Talking about my fix, so when I connect frontend development server with backend development server, both running locally on my laptop. This fix is working. But When I connect frontend development server to the release backend (https://release.app.appsmith.com), this fix is not working. So maybe this issue is happening on both frontend and backend, but on backend this seems fixed in the repository, I mean in development but still occurring on release server.

So I suggest, Connect the frontend with the backend which is running in development on your local system.

### Explanation, thought process behind this fix:-
So after doing deep debugging, observing network calls, deep function calls and stack. and also after some frustration, I tried adding a simple Button widget to empty canvas. So when we add an onClick event on button widget, It also adding another property `dynamicTriggerPathList: {key: "onClick"}`. So on rename it is renaming and everything is working fine with button widget.

When I add a Modal widget to canvas, four other widgets are also created as childern inside Modal widget. An onClick event is also added on some of them (IconButton widget and Button2 widget for close) during Modal widget creation. So when I tried to change name of Modal widget, I observed network calls and refactor request is going to the backend with oldname and new name. I thought problem is on backend server. So after doing some debugging on backend I found that refactor request is changing the name of modal widget (where type == "MODAL_WIDGET") but it is not chaning the onClick: closeModal reference on child widgets(IconButton and Button for close), because it didn't found `dynamicTriggerPathList: {key: onClick}` on child widgets. 

Which means, `dynamicTriggerPathList: {key: onClick}` property is not added on children during Modal widget creation. Which means, BlueprintOperations.MODIFY_PROPS adding `onClick: closeModal(Modal1)` to children but not adding `dynamicTriggerPathList: {key: onClick}`.
So in this fix, I have added code to add `dynamicTriggerPathList` during BlueprintOperations.MODIFY_PROPS execution.

One More time, This fix works with development backend with release branch, not with (https://release.app.appsmith.com)

**Comment by sbalaji1192** [comment]
@iSatVeerSingh Thanks for the detailed explanation. 
I'm not sure why this is not working with release env. release.app.appsmith.com gets built with the release branch. So we should not see any difference. Having said that. I still feel that `MODIFY_PROPS` is not an appropriate place to update the dynamicTriggerPathList. The correct place would be that place where we go through the blueprint and create child widget.
Can we sync on google meet to discuss the problem?

**Comment by iSatVeerSingh** [comment]
@sbalaji1192 sure.

**Comment by iSatVeerSingh** [comment]
@sbalaji1192 So BlueprintOperations.Modify_Props is the last main operation(in a general sense last main work) that is happening during the child widget creation process. I mean child widgets are already created before blueprintOperations.Modify_props execution. So if it is modifying something in already created widgets and if it modifying some property that is dynamically referenced, We should make sure that everything in every widget is updated after this.

I mean if it is adding, removing, or changing something, and if it is dynamically referenced, so we should make sure that dynamic paths are also up to date. So think this is the right place for this.

And not just for dynamicTriggerPaths, we should check for dynamicBindingPaths.

What are your thoughts on this? Please let me know.

**Comment by sbalaji1192** [comment]
@iSatVeerSingh BlueprintOperations.Modify_Props is a life cycle method to perform any modification from the widget side to the widget object during creation. The saga function `executeWidgetBlueprintOperations` is only used to execute the blueprint operation methods. we should not be making any modifications to the widget object during there.
There is a method called `generateChildWidgets` which is responsible for creating the child based on the blueprint view, ideally, that method should be responsible for making changes to the widget in the add widget flow.
Let's discuss further on the call.

**Comment by iSatVeerSingh** [comment]
@sbalaji1192 Should I close this PR?

**Comment by sbalaji1192** [comment]
@iSatVeerSingh yeah. please close this PR. We need to refactor the getPropertiesToUpdate function to address the actual issue as we discussed on the call.

**Pull request closed without merging**
