### PR TITLE
test: Updating Mongo DB name to match Mongo TED database name

### PR DESCRIPTION
**Pull request by Aishwarya-U-R**
## Description

> Fixes CI Mongo spec failures

## Type of change

- New DB name (non-breaking change which adds functionality)

## How Has This Been Tested?

> Release CI

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Rishabh-Rathod — DISMISSED** [review]
- We are changing `runMode` to `1` as `2` didn’t much help before for us. 
cc: @Aishwarya-U-R  

- We are changing DB name to match appsmith TED https://github.com/appsmithorg/TestEventDriver#datasources-credentials-to-be-used-

**Review by yatinappsmith — DISMISSED** [review]

**Review by yatinappsmith — APPROVED** [review]

**Pull request merged**
