### PR TITLE
fix: Select widget if set to required on initial state has red border

### LINKED ISSUE #9346: [Bug]: Select widget if set to required on initial state has red border
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When accessing the page where "Select" widget is configured to be required it's highlighted with the red border. The widget should be highlighted with the red border after using it, not on its initial state.

### Steps To Reproduce

1. Drop "Select" widget on canvas
2. Set it to be required
3. Deploy it
4. Access the page where widget was added and see that it's highlighted with red border

### Environment

Production

### Version

Self-Hosted

### PR DESCRIPTION
**Pull request by jsartisan**
## Description
When accessing the page where "Select" widget is configured to be required it's highlighted with the red border. The widget should be highlighted with the red border after using it, not on its initial state.

Fixes #9346 

## Type of change

- Bug fix

## How Has This Been Tested?
- manually tested

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>

    // Code coverage diff between base branch:release and head branch: fix/select-initial-state-issue 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | app/client/src/widgets/DropdownWidget/widget/index.tsx | 71.19 **(-2.02)** | 36.84 **(-2.55)** | 64.29 **(0)** | 70.37 **(-2.18)**</details>

### CODE REVIEW

**Comment by jsartisan** [comment]
@tmdoit hey, can you check if this DP if it is having the desired UX? https://deploy-preview-9378--appsmith-editor-ce.netlify.app/applications

**Comment by tmdoit** [comment]
How to access the app?

**Comment by jsartisan** [comment]
@tmdoit this is the preview link - https://deploy-preview-9378--appsmith-editor-ce.netlify.app/
you will need to create a new account on it as it uses a different database.

**Comment by tmdoit** [comment]
@jsartisan 
- height of select and input component is different
- when input and select widget are required, select widget has red border on initial state. opposite to input widget

**Review by aswathkk — APPROVED** [review]

**Comment by YogeshJayaseelan** [comment]
@jsartisan verified this PR and working as expected

**Review by riodeuno — APPROVED** [review]

**Comment by jsartisan** [comment]
Closing this PR as we are going to fix the validation itself.

**Pull request merged**
