### PR TITLE
Fixing Flaky tests 

### PR DESCRIPTION
**Pull request by NandanAnantharamu**
Flaky test fixes include
1.CreateOrg
2.LeaveOrg
3.Logspec

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>
No changes to code coverage between the base branch and the head branch</details>

### CODE REVIEW

**Review by yatinappsmith — APPROVED** [review]

**Review by yatinappsmith — COMMENTED** [review]
any reason you are using force:true for click

**Comment by NandanAnantharamu** [comment]
> any reason you are using force:true for click

some times click fails even though we click an element, force click works during those usecases

**Review by arslanhaiderbuttar — APPROVED** [review]

**Review by yatinappsmith — APPROVED** [review]

**Review by yatinappsmith — APPROVED** [review]

**Pull request merged**
