### PR TITLE
fix: Return default page id instead of id in restore snapshot API

### LINKED ISSUE #22956: [Coversion Alogorithm] In git connect apps, After snapshot restore , we are being thrown to invalid PageID resulting in error
https://www.loom.com/share/8c00528bccac4398b73dbb2a8c6607d4

### PR DESCRIPTION
**Pull request by nayan-rafiq**
## Description
The restore snapshot API returns the Application object that was restored. In current implementation, it returns pages with `_id` as the `id`. This creates problem when the Application is Git connected because no page will be found with the _id and branch name. This PR fixes this problem by replacing the `id` with the `defaultPageId`.

#### PR fixes following issue(s)
Fixes #22956
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
- [ ] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by NilanshBansal — CHANGES_REQUESTED** [review]
@nayan-rafiq can you add any tests to cover this?

**Comment by nayan-rafiq** [comment]
> @nayan-rafiq can you add any tests to cover this?

Thanks for the review. I've added tests for the case.

**Review by NilanshBansal — APPROVED** [review]
LGTM

**Comment by Aishwarya-U-R** [comment]
@nayan-rafiq -Merge latest release & trigger new oktotest. Cancelling the re-run since its past 12 hours from initial attempt.

**Pull request merged**
