### PR TITLE
removed gitlab-ci

### PR DESCRIPTION
**Pull request by ari-hacks**
#573

### CODE REVIEW

**Comment by mohanarpit** [comment]
@ari-hacks Please read the [contribution guide](https://github.com/appsmithorg/appsmith/blob/master/contributions/CodeContributionsGuidelines.md#-git-workflow). Can you please fork your branch from `release` instead of `master` ? Typically, we use `master` only for stable, well-tested code.

Also, raise your PR against the `release` branch instead of `master` in the Appsmith repository.

**Comment by ari-hacks** [comment]
@mohanarpit, will do. Sorry about that!

**Comment by mohanarpit** [comment]
Also, @ari-hacks can you also remove the `gitlab-ci.yml` file from `app/server` folder as well?

**Comment by hetunandu** [comment]
Closed in favour of #865

**Pull request closed without merging**
