### PR TITLE
chore: update spacing between elements in git sync modal

### PR DESCRIPTION
**Pull request by akash-codemonk**
## Description

Update spacing between elements to make the button visible. 

Fixes https://github.com/appsmithorg/appsmith/issues/19869

## Media

https://user-images.githubusercontent.com/67054171/225610707-c64d431d-5ed3-4b9e-90fd-30b36c7242c7.mov

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual
- Cypress

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Comment by Parthvi12** [comment]
Verified the fix and it looks good to me.

**Review by eco-monk — APPROVED** [review]

**Review by hetunandu — APPROVED** [review]

**Pull request merged**
