### PR TITLE
fix: Evaluation issue with Button in table Widget

### LINKED ISSUE #9310: [Bug]: Button name of default column changes when On click property for action column is deleted
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[LOOM DEMO](https://www.loom.com/share/f7b0cfdc245b46008c1008fe863e532d)

[LOOM DEMO](https://www.loom.com/share/46f95892ac6e4e938a58440f426a562d)

### Steps To Reproduce

1. Drag and drop a Table widget
2. In property pane go to action column
3. Click on JS for on click property 
4. Remove the default query and observe that the button title changes

### Environment

Release

### Version

Cloud

### PR DESCRIPTION
**Pull request by Tooluloope**
## Description
Button and Menu Button Column type Fix on table widget

Fixes #9310 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>
No changes to code coverage between the base branch and the head branch</details>

### CODE REVIEW

**Review by jsartisan — APPROVED** [review]

**Review by vibhandikyash — APPROVED** [review]

**Comment by YogeshJayaseelan** [comment]
@jsartisan Verified fix for issue 9310 and it is working as expected now

**Review by marks0351 — APPROVED** [review]

**Pull request merged**
