### PR TITLE
fix: moved the logic of highlight walkthrough to widget boundary

### LINKED ISSUE #25941: [Bug]: List Widget onItemClick actions fails to execute when we click on empty space inside the List Item container
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

List Widget onItemClick actions fails to execute when we click on empty space inside the List Item container

### Steps To Reproduce

https://www.loom.com/share/110d875cdff44e75b7068c51e908aca9

### Public Sample App

_No response_

### Environment

Release

### Issue video log

_No response_

### Version

Cloud/Release

### PR DESCRIPTION
**Pull request by keyurparalkar**
## Description
This PR moves the logic of closing the highlight walkthrough to the widget boundary component. This allows us to retain the closure of walkthrough as well as retain the onItemClick event functionality of list widget.

#### PR fixes following issue(s)
Fixes #25941

#### Type of change
- Bug fix (non-breaking change which fixes an issue)

>
>
>
- [ ] Manual
    - should test that `onItemClick` event works when clicked on the blank space of the list item
    - should test that highlight walkthrough get closed when clicked on the widget.
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Comment by kamakshibhat-appsmith** [comment]
checked the fix on List. Looks good @keyurparalkar

**Review by AmanAgarwal041 — DISMISSED** [review]

**Review by ashit-rath — COMMENTED** [review]
@keyurparalkar Please verify if there were any existing cypress test for this and why those didn't throw error. If the relevant tests were not there then please do add them.

**Review by ashit-rath — APPROVED** [review]

**Comment by AmanAgarwal041** [comment]
[RCA-for-List-Widget-onItemClick-actions-fails](https://www.notion.so/appsmith/RCA-for-List-Widget-onItemClick-actions-fails-9f0b9052f8144fd1b5640eaf01f36f82)

**Pull request merged**
