### PR TITLE
fix: google sheet datasource is incorrectly marked as unauthorised by reconnect modal logic. 

### LINKED ISSUE #23861: [Bug]: The Save and Test config button are not visible in the Reconnect data source modal
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The Save and Test config button are not visible in the Reconnect data source modal
image

### Steps To Reproduce

1. Go to https://ee-1544.dp.appsmith.com/
2. Pick any one App
3. Click on app setting and then on import
4. now import a new app with has db connection
5. in the reconnect datasource modal the save and test configuration button are hidden

### Public Sample App

_No response_

### Environment

Release

### Issue video log

_No response_

### Version

v1.9.20.5

### LINKED ISSUE #23881: [Bug]: GSheet datasources are not getting authorised in reconnect modal while importing app
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When there are two Gsheets, if we authorise first one then authorise second one, first one's authorisation go away, refer video: 

https://github.com/appsmithorg/appsmith/assets/80334441/5d57dd81-9898-48a4-8ca8-c53aad45a16a

### Steps To Reproduce

1. Import an app with more than one gsheet
2. In reconnect modal, authorise gsheets
3. Observe the previously authorised Gsheet's authorisation goes away.

### Public Sample App

_No response_

### Environment

Release

### Issue video log

_No response_

### Version

https://ee-1544.dp.appsmith.com

### PR DESCRIPTION
**Pull request by AmanAgarwal041**
## Description
This PR constitues
- The "reconnect" modal logic was modified to use the "isDatasourceAuthorizedForQueryCreation" function in the "editorContextUtils.ts" file to verify the authorization state of the Google Sheets plugin.
- Added a functionality to determine whether or not the plugin is Google Sheets.

#### PR fixes following issue(s)
Fixes #23881
Fixes #23861
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
- [ ] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by sneha122 — APPROVED** [review]

**Comment by Parthvi12** [comment]
After authorisation, redirection to app is not happening: 
Screenshot 2023-05-31 at 10 44 34 AM

**Comment by Aishwarya-U-R** [comment]
@AmanAgarwal041 - Merge latest release & trigger new oktotest. Cancelling the re-run since its past 12 hours from initial attempt.

**Comment by Parthvi12** [comment]
Another issue, importing app in new workspace doesn't wait for me to authorise datasource and directly goes to app: 

https://github.com/appsmithorg/appsmith/assets/80334441/312be2a4-d598-487c-909c-94b0c3e9dce8

**Comment by Parthvi12** [comment]
Both the issues are resolved and verified on DP

**Review by sumitsum — APPROVED** [review]

**Review by tanvibhakta — APPROVED** [review]

**Pull request merged**
