### PR TITLE
refactor: Code splitting of some files for invite modal on EE

### PR DESCRIPTION
**Pull request by ankitakinger**
## Description

> Refactoring the code to code split some files for invite modal on EE

Fixes [#16741](https://github.com/appsmithorg/appsmith/issues/16741)

## Type of change

- refactor

## How Has This Been Tested?

> Tested locally if nothing breaks

- Manual

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by Rhitottam** [comment]
Hi @ankitakinger i am testing a feature of perf-infra tests. Its results can be ignored.

**Review by albinAppsmith — APPROVED** [review]

**Pull request merged**
