### PR TITLE
fix: show clear input icon on allow clear value

### LINKED ISSUE #15132: [Bug]-[25]:Clear all selection property doesn't work in Tree select widget
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Clear all selection property doesn't work in Tree select widget
https://www.loom.com/share/cef34c23cc0943f5b81f0f4a3e6a529d

### Steps To Reproduce

1. Go to canvas
2. drag and drop the Tree select widget
3. In the property pane
4. enable the clear all section property
5. now in tree select widget click on Close icon the selection is not reset the 

### Public Sample App

https://release.app.appsmith.com/app/11th-july-regression/treeselect-62cbab4a4eb23b5ac7c64844/edit?branch=raksha_widgets%2F1

### Version

release

### PR DESCRIPTION
**Pull request by yaldram**
## Description
- Show clear icon on toggling allow clear value option for `treeSelect widget`. 
- Remove the clear icon when the toggle is off.

Fixes #15132

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Tested manually on the canvas.
- Added cypress test cases for the same

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Tooluloope — DISMISSED** [review]

**Comment by btsgh** [comment]
The Allow Clearing Value functionality seems to be working fine, however, one observation here is :
 If the Light Blue option is selected from dropdown, and the column width is increased to say 10, the "x" symbol overlaps with the text of the selected option.
Expected behavior - The text should not overlap, but hide behind the "x" just like it functions for the dropdown symbol "v". 
Discussed and showed this to @yaldram

**Comment by yaldram** [comment]
@btsgh I have fixed the truncation issue when the widget input has smaller width please check. Thanks

**Comment by btsgh** [comment]
Tested on the new dp - works fine now. Also tested MultiTreeSelect for which an issue has been fixed - the clear all selections icon was not appearing as soon as the toggle was enabled. It was only appearing if the dropdown was clicked. That issue also has been fixed on this dp. Now the icon appears as soon as toggle is enabled.

**Review by Tooluloope — APPROVED** [review]

**Pull request merged**
