### PR TITLE
fix: changed cap default to fix ux issue on js toggle

### LINKED ISSUE #10197: [Bug]: Turning on JS on cap field and clearing placeholder of Divider widget causes unexpected behaviour
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Turning on JS on cap field of Divider widget causes unexpected behaviour where cap appears on the divider without any selection

[LOOM DEMO](https://www.loom.com/share/d393fdc07467426d9530491be8f0a4b1)

### Steps To Reproduce

1. Turn on JS for cap field of the divider widget
2. Clear the placeholder and observe cap options show up below the field and on the widget
3. Toggle JS off and observe the cap still present on the divider widget with `no selection`

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by techbhavin**
## Description

> In Divider Widget change default Cap.

Fixes #10197

## Type of change

- Bugfix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: bug/divider-js-toggle-cap-issue 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 55.09 **(0)** | 36.88 **(0.01)** | 35.01 **(0)** | 55.57 **(0.01)**
 :green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.94 **(0.23)** | 41.67 **(0.84)** | 36.21 **(0)** | 56.99 **(0.25)**
 :green_circle: | app/client/src/widgets/DividerWidget/widget/index.tsx | 100 **(6.67)** | 100 **(0)** | 100 **(20)** | 100 **(7.14)**</details>

### CODE REVIEW

**Review by aswathkk — APPROVED** [review]

**Comment by YogeshJayaseelan** [comment]
@techbhavin Tested this PR and please find the status below,

The original issue on the Widget is fixed now - Enabling JS on CAP and removing the value on CAP field does not react on the widget now

Additionally found the below issues 

Issue 1 - Enabling JS on CAP and removing the value still shows the options below on the CAP property 

https://loom.com/share/379beda8843e4684a324a149147cf0e3

**Comment by vivekverma2312** [comment]
@techbhavin Left/Centre/Right alignment of cap is not showing when JS condition is used
Screenshot 2022-01-19 at 11 21 13 AM

**Review by aswathkk — APPROVED** [review]

**Comment by YogeshJayaseelan** [comment]
@techbhavin Tested this PR and please find the status below,

Both the issue are reopen 

Issue 1 - Enabling JS on CAP and removing the value still shows the options below on the CAP property
Issue 2 - Left/Centre/Right alignment of cap is not showing when JS condition is used

https://loom.com/share/a6a6959e2c8942cc84868139085b4ca1

**Comment by techbhavin** [comment]
@somangshu  @dilippitchika  @vivekverma2312  

1. can we add the name label  `Cap Alignment` in the alignment property in Property Panel. 

2.  when we have cap type is `nc` then we hide cap alignment property and for rest, it is visible instead we can remove this condition and show cap alignment for all-cap types.

**Comment by dilippitchika** [comment]
Agreed with you for both points @techbhavin. 

Call the label "Cap Position" and the tooltip to say "Changes the position of the cap if a valid cap is selected." Not worth over-engineering.

**Comment by YogeshJayaseelan** [comment]
@techbhavin Tested the bug fixes and please find the status below

Issue 1 - **Fixed**
Issue 2 - **Fixed** 

New issue :

Issue 3  - Cap selection dot or arrow is not applied to the default widget state 

https://www.loom.com/share/aed06bbdeba3406f95fcacb5f272997f

**Comment by somangshu** [comment]
@YogeshJayaseelan you are not seeing the UI properly, Maybe it was not visible to you, But I can see it in the video attached.

Also, I know I sound like a broken record here, But could we something here to make the information grok-able? I literally went through the point more than thrice and still did not understand, Would love to help you in this regard if required

**Comment by somangshu** [comment]
@techbhavin please push this back in case you think my above statement is correct

**Comment by YogeshJayaseelan** [comment]
@techbhavin Thats my bad i was not able notice arrow or dot at the first time. This is working fine and we can proceed further 

@somangshu Yes i understand and going forward i will make it clear

**Pull request merged**
