### PR TITLE
feat: App Positioning Feature Backend Implementation

### LINKED ISSUE #19348: [Task]: App Level settings for Auto Layout (App Positioning)
- Create an App level Property(appPositioningType) to capture widget positioning Mode of the applications.
- Add a new property to existing app level settings
- Allow two values "FIXED" and "AUTO"
- Provide an api to update the setting/property.
- published and unpublished versions for the property should exist.
- the setting's value should be send back as part of the application api.
- backfill existing applications with "FIXED"
- newly created apps should have "FIXED" by default
- Make sure git sync works along side this.

**Feature Description**
- App Positioning property added to the App Settings so that the user can set the **FIXED** or **AUTO** positioning of the App

FIXED
fixed

AUTO
auto

### PR DESCRIPTION
**Pull request by NilanshBansal**
## Description

Implements backend functionality for App Positioning (Auto Layout) Feature

Fixes #19348 

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- JUnit 
- Manual

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Comment by nidhi-nair** [comment]
Hey Nilansh, I'm going to call this out again, we seem to be adding yet another set of unpublished and published fields in the base type in this PR. Do you think it is worth investing in consolidating this into one type, we're going to end up increasing the burden of migrations in the future at this rate. :)

**Comment by NilanshBansal** [comment]
Hey @nidhi-nair, I completely agree to what you are pointing towards and this has been a conscious decision to ignore the cleanup as part of this PR. 
The aggregation of published and unpublished fields is our next top-most priority and will be picked up very soon. Issue reference here: [https://github.com/appsmithorg/appsmith/issues/19280](https://github.com/appsmithorg/appsmith/issues/19280)

Rest assured, this would probably be the last set of published and unpublished fields going in the base type.
Can you please review this PR, ignoring the cleanup and optimisation for published/unpublished fields at this point?

I will connect with you separately for #19280

**Pull request merged**
