### PR TITLE
fix: JSONForm multiselect field with invalid option crash

### LINKED ISSUE #20791: [Bug]: Multiselect widget; TypeError: this.props.defaultOptionValue.some is not a function
Sentry Issue: [APPSMITH-5J8](https://appsmith.sentry.io/issues/3802741307/?referrer=github_integration)

```
TypeError: this.props.defaultOptionValue.some is not a function
  at <object>.value (widgets/MultiSelectWidgetV2/widget/index.tsx:642:37)
  at next (RouteParamsMiddleware.ts:126:10)
...
(45 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by ashit-rath**
## Description

When invalid `Options` is passed to a multiselect field in a JSONForm, the widget crashes.
Example of invalid `Options`
```js
{{ [ { label: "asd", value: "zxc"}, null ] }}
```
The second option is `null` which makes the whole `Options` property as invalid.

Fixes #20791

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manual
- Cypress

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [x] Test plan has been approved by relevant developers
- [x] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by Tooluloope — APPROVED** [review]

**Comment by chandannkumar** [comment]
Observations: @ashit-rath 
- There is no detailed error message on debugger
- On deploying the app with null value, the JSONForm buttons seems grey and does not follow theme color

https://www.loom.com/share/27ace33d9fca4e7781b4ed757cdf915d

**Comment by chandannkumar** [comment]
Tested this PR and LGTM
- No app breakage on passing invalid options

**Pull request merged**
