### PR TITLE
fix: radio group widget crash when one of options becomes null

### LINKED ISSUE #9289: [Bug] TypeError: Cannot read properties of null (reading 'label')
Sentry Issue: [APPSMITH-1CX](https://sentry.io/organizations/appsmith/issues/2808172301/?referrer=github_integration)

```
TypeError: Cannot read properties of null (reading 'label')
  at None (widgets/RadioGroupWidget/component/index.tsx:75:31)
  at Array.map (<anonymous>)
  at render (widgets/RadioGroupWidget/component/index.tsx:70:31)
  at HTMLDocument.a (../../src/helpers.ts:87:17)
...
(12 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by aswathkk**
## Description

Fixes #9289 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Refer [this comment](https://github.com/appsmithorg/appsmith/issues/9289#issuecomment-976417079) to reproduce the issue

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>
No changes to code coverage between the base branch and the head branch</details>

### CODE REVIEW

**Review by jsartisan — APPROVED** [review]

**Comment by YogeshJayaseelan** [comment]
@aswathkk Tested this PR and now passing {{moment()}} to options doesnt throw properties of null error

**Pull request merged**
