### PR TITLE
fix: Layout Conversion bugs for auto Layout

### LINKED ISSUE #21967: [Bug][Conversion Algorithm] when conversion API fails, but snapshot is a success, then on using snapshot we are seeing a mismatch in the layout mode for widgets and canvas
In the video below, notice after using snapshot , the widgets are in fixed layout and canvas in auto layout creating a conflict

https://user-images.githubusercontent.com/113327629/229110207-731159a1-859a-4adc-97b2-c6977b95ded4.mov

### LINKED ISSUE #21969: [Bug][Conversion Algorithm] conversion failing for a specific template with error in the API being "Incorrect Dynamic Bindings"
Import Applicant Tracker-test template

Image

On further checking, seems like this is happening because of NULL bindings in widget, remove all NULL bindings in the app, and the conversion worked

Image

### LINKED ISSUE #22094: [Bug][Conversion Algorithm] Is there a way to dynamically update the data in the Modal which gives the Latest snapshot timestamp
https://www.loom.com/share/13d6c3f77a9644579bed3c67d1e801f1

Not the highest priority, might require product decision

### LINKED ISSUE #22187: [Bug][Widget responsiveness] Issue with dimensions of Widgets inside modal when switched to mobile viewport
https://www.loom.com/share/edad0eaa6edd4a33a04560f82f69012e

### LINKED ISSUE #22244: [Bug]:[Auto layout][Widget responsiveness] Buttons is Modal widgets are overlapping in Mobile viewport
Issue 1: Buttons in the Modal widget are overlapping when resized to mobile viewport, we are able to see another widget placed near the buttons are also overlapped

Issue 2: When Tab widget is placed inside Modal widget, and Tab1 have less widgets Tab2 have a larger widget. In Mobile viewport we are able to see the Tab1 in Tabs widget is enlarged to the size of the Tab2 but gets collapsed to the original size only after we switch between tabs.

https://user-images.githubusercontent.com/104895602/230966418-8ae5c139-68a9-4ecc-87b6-53159affc6e9.mp4

### LINKED ISSUE #22697: [Bug]: [Conversion Algorithm] Conversion is failing when we have widgets style property bind to another widget
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When widgets stlyle property is bind with other widgets, we are seeing "Conversion failed" error message

image (18)

Response of status 400:
{"responseMeta":{"status":400,"success":false,"error":{"code":"AE-APP-4022","title":"Invalid dynamic binding reference","message":"{  \"widgetType\" : \"MULTI_SELECT_TREE_WIDGET\",  \"bindingPath\" : \"labelTextSize\",  \"currentKey\" : \"labelTextSize\",  \"message\" : \"Binding path in the widget not found. Please reach out to Appsmith customer support to resolve this.\",  \"widgetName\" : \"MultiTreeSelect1\",  \"widgetId\" : \"crsgv7sxej\",  \"pageId\" : \"6446732696116d0af9d3f8a7\",  \"layoutId\" : \"6446732696116d0af9d3f8a5\",  \"errorDetail\" : \"Binding path has no mustache bindings\",  \"dynamicBinding\" : \"0.875rem\"}","errorType":"BAD_REQUEST"}},"errorDisplay":"AE-APP-4022: {  \"widgetType\" : \"MULTI_SELECT_TREE_WIDGET\",  \"bindingPath\" : \"labelTextSize\",  \"currentKey\" : \"labelTextSize\",  \"message\" : \"Binding path in the widget not found. Please reach out to Appsmith customer support to resolve this.\",  \"widgetName\" : \"MultiTreeSelect1\",  \"widgetId\" : \"crsgv7sxej\",  \"pageId\" : \"6446732696116d0af9d3f8a7\",  \"layoutId\" : \"6446732696116d0af9d3f8a5\",  \"errorDetail\" : \"Binding path has no mustache bindings\",  \"dynamicBinding\" : \"0.875rem\"}"}

https://user-images.githubusercontent.com/104895602/234209472-fefd577b-bf2c-4a59-b825-cc17b6061ce1.mp4

### Steps To Reproduce

1. D&D few widgets and bind them with radio group widget for the style property
2. Click on Covert to Auto layout
3. Observe the below error

image

### Public Sample App

_No response_

### Environment

Release

### Issue video log

_No response_

### Version

Release

### PR DESCRIPTION
**Pull request by rahulramesha**
## Description
The Changes in this PR includes, 
- separated the logic for getting Readable snapshot details and are derived on component render rather than on change of 
   state to have upto date value on the conversion modal
- Separated the DayJs Utils for the same.
- Upon restoring Snapshot, change the layout type based on the response from API rather than the opposite of current 
   layout type
- Updated the width of modal widget for calculating the positions of children in PositionUtils
- Updated Conversion algorithm to remove the dynamic binding path from list for property paths with default autolayout values

Fixes #21967
Fixes #21969 
Fixes #22244
Fixes #22094 
Fixes #22187 
Fixes #22697 

# Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested? Manual
- Manual

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by prsidhu — APPROVED** [review]
Looks good.

**Comment by kamakshibhat-appsmith** [comment]
LGTM @rahulramesha

**Pull request merged**
