### PR TITLE
feat: Add manual and auto update fields within application object to distinguish between the migration related changes

### LINKED ISSUE #12065: [Task]: Add auto-update and manual-update as a seperate fields to distinguish if the migration took place in between the commits
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

_No response_

### PR DESCRIPTION
**Pull request by abhvsn**
## Description

> When we run the DB migration and then try to commit the application, we are not providing any context as to why some changes are getting reflected even if the user hasn't updated any resource attached to the application. This leads to confusion if the commit is safe. This PR introduces the `isManualUpdate` and `isAutoUpdate` fields within the application object to detect if the changes are due to migration that occurred between the commits. This way client can consume this information to let users know about the changes that the user is seeing for status API.

Fixes #12065

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

> JUnit TC
> Manual testing

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>

    // Code coverage diff between base branch:release and head branch: add-migration-check 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.71 **(-0.23)** | 40.83 **(-0.84)** | 36.21 **(0)** | 56.74 **(-0.25)**</details>

### CODE REVIEW

**Review by AnaghHegde — DISMISSED** [review]

**Review by Aishwarya-U-R — APPROVED** [review]
Approving Cypress changes

**Pull request merged**
