### PR TITLE
fix: disallow drag to select for drop disabled canvas.

### LINKED ISSUE #9737: [Bug] TypeError: Cannot read properties of undefined (reading 'parentId')
Sentry Issue: [APPSMITH-15G](https://sentry.io/organizations/appsmith/issues/2656272414/?referrer=github_integration)

```
TypeError: Cannot read properties of undefined (reading 'parentId')
  at None (sagas/SelectionCanvasSagas.ts:109:38)
  at Array.filter (<anonymous>)
  at call (sagas/SelectionCanvasSagas.ts:108:64)
  at apply (pages/common/CanvasSelectionArena.tsx:332:11)
  at HTMLCanvasElement.a (../../src/helpers.ts:87:17)
...
(32 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by marks0351**
> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Description

> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change.

Fixes #9737

> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>

    // Code coverage diff between base branch:release and head branch: fix/9737 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | app/client/src/pages/common/CanvasSelectionArena.tsx | 91.58 **(0.05)** | 71.67 **(0.16)** | 89.29 **(0)** | 91.3 **(0.04)**
 :red_circle: | app/client/src/utils/WorkerUtil.ts | 88.98 **(-0.78)** | 70.59 **(-1.96)** | 100 **(0)** | 92.38 **(-0.95)**</details>

### CODE REVIEW

**Review by SatishGandham — COMMENTED** [review]
@marks0351 Is there an issue for this?

**Comment by marks0351** [comment]
> @marks0351 Is there an issue for this?

yep #9737 have added this to the description.

**Review by SatishGandham — APPROVED** [review]

**Pull request merged**
