### PR TITLE
Add datasource connected page

### LINKED ISSUE #928: [Task] Create a flow to add query after data source is saved
- On Save we will call test whether it's a valid datasource
- if It's valid then we show the new screen
- if it's not valid then we stay on the same screen and give an error
- There will be a +new query option which will create a query on the current page and take the user to that query

[Designs](https://www.figma.com/embed?embed_host=notion&url=https%3A%2F%2Fwww.figma.com%2Ffile%2FRdWmO9Ny6SfkMZAFIhLKSU%2FAppsmtih-Workspace_Aakash%3Fnode-id%3D37%253A1297)

### PR DESCRIPTION
**Pull request by akash-codemonk**
Fixes #928, https://github.com/appsmithorg/appsmith/projects/14#card-46975264 and https://github.com/appsmithorg/appsmith/projects/14#card-46975397

### CODE REVIEW

**Comment by hetunandu** [comment]
Issues
- Creating new datasource is directly showing the connected screen
- Invalid datasources is showing as connected

**Review by hetunandu — CHANGES_REQUESTED** [review]
Some changes needed with when is the connected state shown

**Comment by hetunandu** [comment]
@akash-codemonk Can you verify tests locally? The CI is not running the cypress tests for this for some reason

**Comment by akash-codemonk** [comment]
There were some tests failing fixed it in https://github.com/appsmithorg/appsmith/pull/1020/commits/1ee255091e673b3a6fb635cb7133f29466f9cdcb. 
The tests are passing now.

**Comment by hetunandu** [comment]
Still seeing some crashes failures when opening/saving datasources with headers(rest api) 
Seeing crashes when creating new query with an invalid datasource
It says `+ New Query` for a REST datasource

This is very unstable right now. Needs more work

**Comment by akash-codemonk** [comment]
Fixes https://github.com/appsmithorg/appsmith/projects/14#card-46975264 and https://github.com/appsmithorg/appsmith/projects/14#card-46975397.

**Pull request closed without merging**
