### PR TITLE
chore: Show Tabs on recent access order

### LINKED ISSUE #30365: [Task]: Optimise Recent Entities Calculations
Refactor recent entity calculations based on new requirements
- Show and order tabs as they access the entity
- Limit open tabs to 5
- Only update the order if a tab is not visible, is accessed

### PR DESCRIPTION
**Pull request by hetunandu**
## Description

Update IDE tabs order and limits

- Show only recently accessed tabs
- If recent tab is was already on screen, do not update order
- Limit to just 5 active tabs

#### PR fixes following issue(s)
Fixes #30365

#### Media

https://github.com/appsmithorg/appsmith/assets/12022471/a53a93cd-1b5e-4341-ba4f-289c6bd82b6d

>
#### Type of change
- Chore (housekeeping or task changes that don't impact user perception)

- [ ] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

## Summary by CodeRabbit

- **New Features**
	- Introduced new actions to manage JavaScript and query tabs within the IDE.
	- Enhanced IDE to update tabs based on route changes.

- **Enhancements**
	- Improved tab management for JavaScript and queries in the IDE.

- **Bug Fixes**
	- Ensured consistent IDE tab states during navigation.

### CODE REVIEW

**Comment by mohanarpit** [comment]
@hetunandu How will this feature behave on page load? In the future, will the order of the tabs persist across multiple sessions of me opening the app?

**Comment by albinAppsmith** [comment]
@hetunandu I found an issue in this algorithm. So when a user is selected the last tab, and he want to goto any new tab which is not there in the tabs list. So now what will happen is the last tab will get pushed out of the list and the new one get added in the first place(like FIFO manner). But as a user, I want to see the recent tab I was in(I guess this is the understanding here). CHeckout the video attached here.

https://github.com/appsmithorg/appsmith/assets/87797149/0685a0e0-9eb9-4f8f-b793-1cd76f5eac0f

**Comment by hetunandu** [comment]
> @hetunandu How will this feature behave on page load? In the future, will the order of the tabs persist across multiple sessions of me opening the app?

Eventually we will have this information stored on the server and pull it at the start so that it can last across sessions and clients.
Soon, I will make a change to make it persist locally
Right now it is not persisted so that testing becomes easy

**Comment by hetunandu** [comment]
> @hetunandu I found an issue in this algorithm. So when a user is selected the last tab, and he want to goto any new tab which is not there in the tabs list. So now what will happen is the last tab will get pushed out of the list and the new one get added in the first place(like FIFO manner). But as a user, I want to see the recent tab I was in(I guess this is the understanding here). CHeckout the video attached here.
> 
>  Screen.Recording.2024-01-19.at.12.25.17.PM.mov

This is the expected behaviour. The Recent order is not changed throughout the session. Only additions are accounted for as they will be added at the beginning of the list. More details are added in the solution doc: https://www.notion.so/appsmith/IDE-Solution-behaviour-8607a3b4df254970a77bd077290d3690?pvs=4#3d7f04820e174389b377037bc2c29906

**Review by albinAppsmith — APPROVED** [review]

**Pull request merged**
