### PR TITLE
feat: Need color agnostic hover states for buttons and table cells

### LINKED ISSUE #4354: [Feature] Need color agnostic hover states for buttons and table cells
## Summary
Every button should have a hover and active state irrespective of the color of the button.

## Motivation
Users are used to seeing buttons that react to their mouse and it's a natural part of every web product.

## Additional Context
Different kinds of hover states:
[LOOM DEMO](https://www.loom.com/share/85f805dc874a4a40b1e7b4ca5a9f5c4b)

Related to #4149 #4353

### PR DESCRIPTION
**Pull request by wmdev0808**
## Description

> Motivation:
  Users are used to seeing buttons that react to their mouse and it's a natural part of every web product.

- Every button should have a hover and active state irrespective of the color of the button.
- Calculate and apply the hover color of a button based on base color and variant.
- Influenced widgets: Button, Button Group, Icon Button, Menu Button

Fixes #4354 

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Test A
- Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: feat/4354-color-agnostic-hover-states 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 55.86 **(0.03)** | 37.32 **(0.09)** | 35.23 **(0.02)** | 56.17 **(0.03)**
 :sparkles: :new: | **app/client/src/components/ads/GradientHoverOverlay.tsx** | **100** | **100** | **100** | **100**
 :green_circle: | app/client/src/widgets/MetaHOC.tsx | 85.94 **(1.56)** | 57.69 **(3.84)** | 92.31 **(0)** | 84.75 **(1.7)**
 :green_circle: | app/client/src/widgets/WidgetUtils.ts | 84.95 **(5.58)** | 64.91 **(14.91)** | 60 **(6.15)** | 82.28 **(7.77)**
 :green_circle: | app/client/src/widgets/ButtonGroupWidget/component/index.tsx | 23.96 **(0)** | 11.57 **(0.37)** | 4.17 **(0)** | 25.58 **(0)**
 :green_circle: | app/client/src/widgets/ButtonWidget/component/index.tsx | 52.08 **(0.5)** | 30.23 **(0.23)** | 45.45 **(0)** | 51.76 **(0.57)**
 :green_circle: | app/client/src/widgets/ButtonWidget/component/utils.tsx | 100 **(0)** | 85.71 **(35.71)** | 100 **(0)** | 100 **(0)**
 :green_circle: | app/client/src/widgets/ButtonWidget/widget/index.tsx | 72.34 **(1.61)** | 43.75 **(0.89)** | 64.29 **(5.96)** | 71.74 **(1.74)**
 :green_circle: | app/client/src/widgets/IconButtonWidget/component/index.tsx | 28.21 **(4.4)** | 7.84 **(1.96)** | 0 **(0)** | 36.67 **(-0.37)**
 :green_circle: | app/client/src/widgets/MenuButtonWidget/component/index.tsx | 26.67 **(1.25)** | 13.79 **(2.03)** | 0 **(0)** | 32 **(1.39)**</details>

### CODE REVIEW

**Review by aswathkk — COMMENTED** [review]
LGTM
Some utility functions need to be covered using Jest.
@wmdev0808 What about the buttons inside the Table widget? They still don't have a hover or active state.

**Comment by wmdev0808** [comment]
> LGTM Some utility functions need to be covered using Jest. @wmdev0808 What about the buttons inside the Table widget? They still don't have a hover or active state.

It is not covered in this PR, it is out of scope for this PR. this PR is only dealing with buttons and table widget case will be dealt in separate issue.

**Review by aswathkk — APPROVED** [review]

**Comment by jsartisan** [comment]
Closing this PR now as it will conflict with theming. WIll reopen after theming gets merged.

**Pull request closed without merging**
