### PR TITLE
fix: Add escaping special characters before JSON.parse

### PR DESCRIPTION
**Pull request by Rishabh-Rathod**
## Description

Fixes ( #8802 ) 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manually ( #8802 steps to reproduce were tried and no issue found )
- Jest test.

## Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/escape-spl-chars 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 55.05 **(0.01)** | 36.94 **(0)** | 33.79 **(0.01)** | 55.53 **(0.01)**
 :green_circle: | app/client/src/selectors/commentsSelectors.ts | 85.25 **(1.64)** | 64.71 **(2.95)** | 73.33 **(0)** | 90.59 **(2.35)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.04 **(-0.22)** | 40.42 **(-0.83)** | 34.48 **(0)** | 55.96 **(-0.26)**
 :green_circle: | app/client/src/widgets/WidgetUtils.ts | 84.31 **(0.98)** | 59.38 **(0)** | 54.55 **(4.55)** | 80.49 **(1)**
 :red_circle: | app/client/src/widgets/ListWidget/widget/index.tsx | 61.69 **(-0.3)** | 26.15 **(0)** | 56 **(0)** | 60.51 **(-0.3)**</details>

### CODE REVIEW

**Comment by Rishabh-Rathod** [comment]
https://github.com/appsmithorg/appsmith/issues/9280

**Comment by Rishabh-Rathod** [comment]
ok-to-test sha=090a31b

**Review by jsartisan — APPROVED** [review]

**Pull request merged**
