### PR TITLE
fix: remove allowed filetype restriction in filepickerwidget

### LINKED ISSUE #9907: [Bug]: [File picker widget] Remove allowed filetype restriction in filepicker widget
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

There should be no restriction in allowed filetypes in filepicker widget. filetypes like ".csv", ".tsv" should be allowed.

### Why should this be worked on?

We need to allow App developers to have fine control over files types they want to allow in the file picker widget. Some of the App developers would want to allow only `.csv`, but currently, App developers need to allow `text/*` to do that. which would allow other file types as well.

### PR DESCRIPTION
**Pull request by sbalaji1192**
Fixes #9907

> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>

    // Code coverage diff between base branch:release and head branch: fix/filepicker-allowed-files 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | app/client/src/components/editorComponents/CodeEditor/index.tsx | 67.13 **(0)** | 40.36 **(0.12)** | 51.28 **(0)** | 67.05 **(0)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.71 **(-0.23)** | 40.83 **(-0.84)** | 36.21 **(0)** | 56.74 **(-0.25)**</details>

### CODE REVIEW

**Review by jsartisan — APPROVED** [review]

**Comment by YogeshJayaseelan** [comment]
@sbalaji1192 Im not seeing deploy preview for this PR. Can you help me with the DP for testing

**Comment by sbalaji1192** [comment]
@YogeshJayaseelan Here is DP link - https://appsmith-gw7a47uao-get-appsmith.vercel.app/user/login

**Comment by YogeshJayaseelan** [comment]
@sbalaji1192 started testing this PR and please find the status below,

Note: Testing is in-progress

Issue 1 - Currently when the image option is checked and the user is able to attach both Jpeg and Png image formats. But when the user chooses images and Jpeg formats in the allowed file types - still the user is able to attach png files. 
Either we can remove jpeg and png options and keeping images option alone or we can remove images option and keep jepg and png options 

https://www.loom.com/share/badc0d3177914564bd5150eaafb97979

**Comment by YogeshJayaseelan** [comment]
> @sbalaji1192 started testing this PR and please find the status below,
> 
> Note: Testing is in-progress
> 
> Issue 1 - Currently when the image option is checked and the user is able to attach both Jpeg and Png image formats. But when the user chooses images and Jpeg formats in the allowed file types - still the user is able to attach png files. Either we can remove jpeg and png options and keeping images option alone or we can remove images option and keep jepg and png options
> 
> [LOOM DEMO](https://www.loom.com/share/badc0d3177914564bd5150eaafb97979)

Will create an separate enhancement for this

**Pull request merged**
