### PR TITLE
feat: [Feature]-[116] Map Widget - Add MapTypeControl (Satellite/Roadmap)

### LINKED ISSUE #11815: [Feature]-[116]:Map Widget - Add MapTypeControl (Satellite/Roadmap)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Add an option to enable/disable MapTypeControl (For switching between roadmap and satellite.)
[https://developers.google.com/maps/documentation/javascript/controls](https://developers.google.com/maps/documentation/javascript/controls)

MapTypeControl

### Why should this be worked on?

Some projects require a satellite map instead of a roadmap. 
Currently there’s no way to switch between map types.

### PR DESCRIPTION
**Pull request by janbre**
#### PR fixes following issue(s)
Fixes #11815

## Description
Added an option to enable/disable MapTypeControl on the Map widget.

- The BOTTOM_CENTER position was chosen so it would not interfere with any of the other elements that can currently be added to the map. 
- It specifically uses the DEFAULT control style to serve as a hint that work can be done to allow the user to set this option. 
- It specifies only ROADMAP and SATELLITE, which disables the terrain map option because the dropdown that allows the user to select the terrain map overflows the map boundary when using BOTTOM_CENTER position

#### Media
output

#### Type of change
- New feature (non-breaking change which adds functionality)

#### How Has This Been Tested?
- [X] Manual

Manually tested that 
- the map type controls can be added to the map widget
- that toggling the switch adds/removes the controls from the map
- that the controls don't interfere with any other elements on the map screens of different sizes (desktop, tablet, mobile)

#### Dev activity
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Review by jsartisan — APPROVED** [review]
LGTM

**Comment by somangshu** [comment]
@jsartisan did you test the DP, is this is a mergeable state?

**Comment by jsartisan** [comment]
@somangshu I couldn't test the DP as there was no google maps key configured for it. I only checked the code.

**Comment by janbre** [comment]
@somangshu I can update the PR to move the new prop to the end like so 
Screenshot from 2023-10-27 11-06-54

Writing tests for it would take me considerably more time, as I'm unfamiliar with the Cypress test framework and my computer runs out of memory trying to run the existing tests for the Map Widget :neutral_face:

**Comment by dilippitchika** [comment]
@somangshu i agree the property should be at the end of the general settings, @janbre please move it as you showed. @somangshu since it's a new field we will need to add documentation

**Comment by somangshu** [comment]
@jnikhila since this is an external contribution, can you please help with the documentation requirement?

**Comment by jnikhila** [comment]
@somangshu - I believe the implementation adds new properties to the map widget. Are these properties, reference properties or available in properties pane while configuring the map widget? Is there a DP available for testing.

**Comment by janbre** [comment]
@jnikhila There is one new property added to the widget, and it's available in the properties pane while configuring the widget. 

**Enable map types**: `boolean` 
When enabled, this setting allows the user to switch between map view and satellite view. Default is map view.

**Comment by somangshu** [comment]
@jsartisan please re-approve. Lets try and merge this PR, got missed in the last week

**Review by somangshu — APPROVED** [review]

**Review by jsartisan — APPROVED** [review]

**Comment by janbre** [comment]
Any progress on this?

**Comment by jsartisan** [comment]
@janbre there is one unit test failing. 
CleanShot 2023-11-23 at 14 54 41

**Comment by jsartisan** [comment]
@janbre can you add helpText for the new property you added?

```
{
  propertyName: "enableMapTypeControl",
  label: "Enable map types",
  controlType: "SWITCH",
  helpText: "Allows users to change the map type", // <--- add this line
  isJSConvertible: false,
  isBindProperty: false,
  isTriggerProperty: false,
},
```

**Comment by jsartisan** [comment]
@somangshu @KelvinOm can we merge this PR? all tests passing

**Pull request merged**
