### PR TITLE
FIX #5254 : dropdown height fixed and made scrollable

### LINKED ISSUE #5254: [Bug] On lengthy Dropdowns in the table filter is not scrollable
Steps to reproduce:
1) Add a Query with many columns
2) Bind the Query to the Table
3) Now click on the Filter option 
and observe

Observation:
It is observed that the List is not scrollable and make it difficult to  select the topmost or bottom most criteria

Expectation:
It is expected that making the filter scrollable
Screenshot 2021-06-18 at 3 24 17 PM

### PR DESCRIPTION
**Pull request by vibhandikyash**
## Description

> Made filter scrollable

Fixes #5254

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Tested locally.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: FIX/5254-dropdown-length-fix-for-table-filterpane 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 53.34 **(-0.01)** | 34.76 **(-0.01)** | 31.46 **(-0.01)** | 53.89 **(0)**
 :red_circle: | app/client/src/utils/helpers.tsx | 54.88 **(-1.83)** | 28.77 **(-4.11)** | 25 **(-3.57)** | 48.84 **(-1.55)**</details>

### CODE REVIEW

**Review by marks0351 — APPROVED** [review]

**Comment by YogeshJayaseelan** [comment]
@vibhandikyash Verified this fix now the table filter has scroll option in the dropdown working as expected

**Review by somangshu — APPROVED** [review]
Approving to run all failing tests

**Comment by somangshu** [comment]
@vibhandikyash need the latest release merged here, Failing test fixes are available

**Review by somangshu — APPROVED** [review]

**Pull request merged**
