### PR TITLE
fix: typo in new query dropdown in datasource preview

### LINKED ISSUE #30433: [Bug]: typo in new query dropdown in datasource preview
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

This should read “Create API in”. Similarly for query.. it should read ’Create query in”.
Screenshot 2024-01-18 at 15 59 19

### Steps To Reproduce

1. ensure the app has multiple pages
2. create a valid datasource (gsheets, postgres or mongo)
3. click the button group `+ New query`

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by rohan-arthur**
Screenshot 2024-01-18 at 15 59 19

>
> File changed: `app/client/src/pages/Editor/DataSourceEditor/NewActionButton.tsx`
> Changed the following line:
`<Text className="pl-2" kind="heading-xs">{`Create a ${`
To:
`<Text className="pl-2" kind="heading-xs">{`Create ${`

Screenshots after making the changes:
Screenshot 2024-01-18 at 16 45 16
Screenshot 2024-01-18 at 16 45 25

#### PR fixes following issue(s)
Fixes #30433

- Bug fix (non-breaking change which fixes an issue)
- [x] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

## Summary by CodeRabbit

- **Refactor**
	- Improved the implementation of the New Action Button for enhanced user experience.

### CODE REVIEW

**Comment by abhishek20111** [comment]
hey [Rohan Arthur](https://github.com/rohan-arthur) can you help me .
i need to step up, locally in window , i am getting issue , can you guide me.

**Review by hetunandu — APPROVED** [review]

**Pull request merged**
