### PR TITLE
fix: added dataFormat into file data

### LINKED ISSUE #11279: [Feature]-[300]: Include data format (Base64/Binary) information in Filepicker widget's files
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

We need a way to identify the data format of the `data` property in the entries of the `files` property in the filepicker widget.

### Why should this be worked on?

On many occasions, we find ourselves having access to only the `files` property, which doesn't have the information necessary to correctly parse or convert the data. So, having the explicit mention of the data format in the file object will help.

### PR DESCRIPTION
**Pull request by techbhavin**
## Description

Added data format in filepicker widget

Fixes #11279 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>
No changes to code coverage between the base branch and the head branch</details>

### CODE REVIEW

**Review by jsartisan — APPROVED** [review]

**Comment by YogeshJayaseelan** [comment]
@techbhavin Tested this PR and please find the status below,

1. Trying to bind the file data format the auto-suggestions don't show options "dataFormat" and it just shows data
Steps:
A) Add a file picker and upload a file
B)Add a text widget and bind the text widget with filepicker - {{Filepicker1.files[0].}} and check for the auto suggestions 

https://www.loom.com/share/78e513341d44400ca94c664f2f3548c0


2. Dynamic update on the fileData type is not reflecting on the binded widget and every-time user needs to refresh the page and add a file again
Steps:
A) Add a file picker and upload a file and set the data type as Binary 
B)Add a text widget and bind the text widget as {{Filepciker1.files[0].dataFormat}} 
C)change the data type in the file picker widget to Text and observe the text widget is not updated dynamically 

https://loom.com/share/86b4cc9135d54f1f99030a030b3b07f4


3. The evaluated value on the image widget is not appropriate when the file picker is binded with the image widget and keeping the file data type as binary or Text. Is this expected behaviour?

https://www.loom.com/share/7d4274d3a37a4533908986ef81483b25

**Comment by techbhavin** [comment]
@YogeshJayaseelan  plz refer this comment and let me know your new observation 

**comment 1:** I'll update autosuggestion
**comment 2:** dataType is bind with the uploaded file. once you upload the file in base64 and then you update dataType from the property pane and expect that reflection to the uploaded file that's wrong (not relevant issue)
**comment 3:** image widget only accept URL / Base64 formats, not text format (not relevant issue)

**Review by jsartisan — APPROVED** [review]

**Comment by YogeshJayaseelan** [comment]
@techbhavin Tested this PR and it is working as expected

**Pull request merged**
