### PR TITLE
fix: Autocomplete needs to show async await keywords instead of showi…

### LINKED ISSUE #10115: [Bug]: Autocomplete needs to show async await keywords instead of showing 'no suggestions'
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently, `async`, `await` keywords etc... are displayed as no suggestions by autocomplete and these needs to be added into autocomplete suggestions

### Steps To Reproduce

1. Try using promises keywords in JS editor or on action fields of the property pane and observe autocomplete show `no suggestions` instead

### Environment

Release

### Version

Cloud

### PR DESCRIPTION
**Pull request by Druthi**
## Description
fix: Autocomplete needs to show async await keywords instead of showing 'no suggestions

image

Fixes #10115

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Cypress

### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by ohansFavour — COMMENTED** [review]
We should also add completion for "async function". Check `keywordCompletion.ts `.

Add a new autocompletion hint with name "async function", this should autocomplete with text 
```
async ()=>{

}
```

**Review by ohansFavour — APPROVED** [review]
PR looks good

**Comment by ramsaptami** [comment]
gtg to release
CC: @Druthi

**Pull request merged**
