### PR TITLE
fix: remove 'display: block' from span inside text widget

### LINKED ISSUE #19285: [Bug]: Adding span html element causes the text widget to break into multiple lines
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When i add 
`this is a <span style=color:#ff0000 ; > span </span> thing`
into text widget, it breaks line. Span class should never break line.

### Steps To Reproduce

1. Add a new text widget
2. Add the text as `this is a <span style=color:#ff0000 ; > span </span> thing`
3. Observe that the text splits into multiple lines

### Public Sample App

_No response_

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by dhruvikn**
## Description

This PR prevents `span` HTML tags inside the text widget from breaking lines.

More context here - https://theappsmith.slack.com/archives/C02JV8G1MP0/p1672230336770849

Fixes #19285

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manual
- 

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Comment by chandannkumar** [comment]
Tested this PR and working as expected
- Fixed `span` HTML tags inside the text widget from breaking lines

**Comment by dhruvikn** [comment]
@chandannkumar can we also test the auto height behavior of the text widget once?

cc: @dilippitchika @ankurrsinghal

**Comment by chandannkumar** [comment]
> @chandannkumar can we also test the auto height behavior of the text widget once?

@dhruvikn Tested auto height behavior too

**Comment by dhruvikn** [comment]
Great, thanks a lot @chandannkumar! 🥳

**Review by jsartisan — APPROVED** [review]

**Pull request merged**
