### PR TITLE
fix: Table widget pagesize in short row height mode

### LINKED ISSUE #15984: [Bug]: When table default row height is set to short, the page size calculation is wrong
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When i add a table with a short row height, the page size calculation is wrong and there is always a scroll on the table.

### Steps To Reproduce

1. Add a new table
2. Add data
3. Set the table default row height to short
4. Observe the table page size increases more than it should and table has a scroll

### Public Sample App

_No response_

### Version

Production

### PR DESCRIPTION
**Pull request by sbalaji1192**
Fixes #15984 

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by jsartisan — DISMISSED** [review]

**Comment by laveena-en** [comment]
Tested and verified.

**Review by jsartisan — APPROVED** [review]

**Pull request merged**
