### PR TITLE
fix: use newer editableText component

### PR DESCRIPTION
**Pull request by tanvibhakta**
## Description

1. Removes red background on error (fixes https://github.com/appsmithorg/appsmith/issues/24098)
2. Changes saving state icon to use new standard `loader` icon (fixes https://github.com/appsmithorg/appsmith/issues/24112)

#### Media

https://github.com/appsmithorg/appsmith/assets/13763558/d5fc8b4d-f3cd-4b9d-a0d7-54c9aa9921c6

>
#### Type of change

- Bug fix (non-breaking change which fixes an issue)
>
>
- [ ] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by albinAppsmith — APPROVED** [review]

**Comment by shadabbuchh** [comment]
- **Issue 1 -** Fixed

Screenshot 2023-06-12 at 11 14 56 AM
Screenshot 2023-06-12 at 11 17 17 AM

- **Issue 2 -** We are now able to see the new Loader. However the loader does not seem to rotate like it does in other places. Also we are not able to see the loader after changing the Workspace name.

https://github.com/appsmithorg/appsmith/assets/39921438/06e0faf7-d3e6-42c6-ba40-67ea7fd5b21c

**Comment by tanvibhakta** [comment]
> However the loader does not seem to rotate like it does in other places.

To do so we would have to update the design-system-old spinner, which is not useful as we are building a new component for this in a few weeks time. I have changed the icon so that the difference is not glaring when seen for a split second.

**Comment by albinAppsmith** [comment]
@tanvibhakta I see we are using old gray in edit field. Approving the rest of the changes.

**Review by albinAppsmith — APPROVED** [review]

**Pull request merged**
