### PR TITLE
fix: Update date ISO string validations

### LINKED ISSUE #11381: [Bug]: Invalid date in Date Picker widget when using moment object
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Steps To Reproduce

1. Drag and drop a date picker widget
2. Use `{{moment()}}` in default date property
3. Refresh the page
4. Observe the invalid date in widget

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by sbalaji1192**
## Description

In the worker thread, we were using lodash's cloneDeep function to clone the data tree, we recently started using a new library to clone to improve performance ([PR](https://github.com/appsmithorg/appsmith/pull/11001/files)).
Due to this change, Datepicker defaultValue is no longer evaluating to string, it gets evaluated to moment object, which results in the above error.

Fixes #11381 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/datepicker-validations 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 55.77 **(0)** | 37.1 **(-0.03)** | 35.82 **(0)** | 56.12 **(-0.01)**
 :red_circle: | app/client/src/utils/WorkerUtil.ts | 88.98 **(-0.78)** | 70.59 **(-1.96)** | 100 **(0)** | 92.38 **(-0.95)**
 :green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.94 **(0.23)** | 41.67 **(0.84)** | 36.21 **(0)** | 56.99 **(0.25)**
 :red_circle: | app/client/src/workers/validations.ts | 81.32 **(-0.63)** | 70.57 **(-0.66)** | 76.67 **(0)** | 82.39 **(-1)**</details>

### CODE REVIEW

**Comment by riodeuno** [comment]
@sbalaji1192 Seems like we've changed how the validations work. The jest tests related to the data iso string validations are failing. Can we update the PR description to describe the rationale behind, changing the way we validate a data iso string? Alternatively, can we fix the validation so that the jest tests pass? (preferable)

Changing how validations respond to validation configurations, can result in cascading changes in other parts of the application. Possibly, the Table Widget.

**Comment by sbalaji1192** [comment]
@riodeuno I have fixed the test case. it was actually because of an extra key in the expected value. 

We are making changes to only `DATE_ISO_STRING` validations. And this validation is only being used by the Datepicker widget. There was an issue with the `DATE_ISO_STRING` validation, as the name suggests, should return an ISO date string. But in a case where we use the Date object or moment object as the binding, it returns the object. This was not a problem before because of the way we use to clone data tree (Moment and date object got converted to date string by the clone function).

**Review by riodeuno — APPROVED** [review]
Looks good to me.

**Comment by vivekverma2312** [comment]
@sbalaji1192 After I use {{moment()}} in default field the date populates in widget only after I refresh the screen in edit mode. Is this expected?

**Comment by sbalaji1192** [comment]
@vivekverma2312 Not sure whether it's related to changes I did. Since this issue got merged to prod. Could you create a new issue? will investigate and provide a fix there.

**Pull request merged**
