### PR TITLE
fix: column order of frozen columns when query changes

### LINKED ISSUE #21154: [Bug]-[1600]:the frozen custom columns are not retaining its position when we change to a different query
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

 ISSUE 1 : the Save/discard button is not retaining its position when we change to a different query
https://www.loom.com/share/ee06eeba09c74985bb891b425b2e1810

ISSUE 2: when we have a custom column along with editable field, and then we change to a different query , UI breaks
https://www.loom.com/share/fc9cc430988941459c6a06cf3f933ac8

### Steps To Reproduce

ISSUE 1

1. DnD a table widget
2. make any column editable 
3. delete dummy data and add a fresh query 
you will see the wrong positioning of Save / discard

ISSUE 2: 
1. DnD a table widget
2. make any column editable and add one custom column
3. delete dummy data and add a fresh query 
you will see the wrong positioning of Save / discard

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by keyurparalkar**
## Description

This PR focuses on reordering the frozen columns when the query changes. With this PR, we intend to retain the position of the frozen columns. 

Fixes #21154

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual
    - Order of the unfrozen common columns should appear as expected. 
    - Column order of common columns should work as expected as before
- Cypress
    - Frozen custom columns should retain the position on query change
    - Custom common columns should retain the position on query change
    - Frozen column should remain frozen and unfrozen column should come first when query changes
    - The order of the frozen columns should remain the same.
    - When 2 common columns, one is frozen to left, other is unfrozen, then post query change, unfrozen comes after frozen 
    

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [x] Test plan has been approved by relevant developers
- [x] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by sbalaji1192 — APPROVED** [review]

**Review by sbalaji1192 — APPROVED** [review]

**Comment by chandannkumar** [comment]
Observed that on migration Save/Discard button is not retaining to it's correct position. It remains as it was before migration.
https://www.loom.com/share/0661df09b7d443e8b56169aead5d1081

**Comment by chandannkumar** [comment]
Observed that on migration Save/Discard button is not retaining to it's correct position. It remains as it was before migration.
https://www.loom.com/share/0661df09b7d443e8b56169aead5d1081

**Comment by keyurparalkar** [comment]
> Observed that on migration Save/Discard button is not retaining to it's correct position. It remains as it was before migration. https://www.loom.com/share/0661df09b7d443e8b56169aead5d1081

@chandannkumar please ignore the above callout since the user can directly unfreeze and freeze the column at the correct position.

CC: @dilippitchika

**Comment by chandannkumar** [comment]
Tested this PR and LGTM

**Pull request merged**
