### PR TITLE
feat: Add addMessageHandler as global function (handle window.postMessage from host)

### LINKED ISSUE #15538: [Feature]: Appsmith app should be able to listen to messages sent from the parent webpage
When appsmith is embedded as an iframe, listen to messages from parent window.

JS equivalent -> `window.addEventListener('message', (ev) => {})`.

## Method signature

- Subscriptions to be unsubscribed:
  - On page change, because the callback can have references to entities from that page
  - On app switch/exit, because we want to restrict listening to app's only.

- `subscribeParentMessages`
```
subscribeParentMessages(
	"https://eco-monk.github.io", 
	(message) => { showAlert(message) }
)
```

- `unsubscribeParentMessages`
```
unsubscribeParentMessages("https://eco-monk.github.io")
```

---

Todo:
 - [x] decide on UI (Discussed: this will be handled purely in code for now) @kocharrahul7 @RoopKrrish9696 
 - [x] investigate and handle security concerns (we're good with adding domain checks)
 - [x] handle page switch unsubscribe
 - [x] unsubscribe and subscribe -> params remain the same
 - [x] No action creator -> since it's not a widely used method

### PR DESCRIPTION
**Pull request by kienmatu**
## Description
This PR create new global function named **addMessageHandler**. This allows us to add a listener to the event window.postMessage() when we embed an appsmith page as an iframe.

appsmith-addmessagehandler drawio

Fixes #15538

### Related PR: 
PR #14925 just contains postMessage that send data from appsmith iframe to other, but in our PR, we will handler message received from host page.

### Usage:
Add a function and make it run every time our page loads:
Screenshot from 2022-10-07 14-47-38

## Type of change

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by kien-manabie** [comment]
@keyurparalkar could you please help me to review it. thanks!

**Comment by thanhloc1993** [comment]
> @keyurparalkar could you please help me to review it. thanks!

please help us. We realy need this feature.

**Comment by eco-monk** [comment]
@kienmatu, Thank you so much for this effort.!

There's and issue for this already #15538.
We initially started out with something similar [here](https://github.com/appsmithorg/appsmith/pull/15539).
And are currently in evaluation/design phase.

Because, We realised that this has a larger scope.
- We need a way to unsubscribe
- Unsubscription should happen on page change (otherwise we'd end up with unwanted errors)
- Not to allow multiple subscriptions for the same domain (which is debatable)
- When we can specify domains allowed for embedding, we need a way to prompt the user when they subscribe to a non-allowed domain
- Need to be vigilant of any security concerns

We are also exploring ways to enable this from JsObject settings (like the on page load switch).

---

Please hold on while we flush out the details. This is only to make sure we do this right.

**Review by eco-monk — COMMENTED** [review]
Already posted my comments above.
This is tracked at #15538.

**Comment by WichardRiezebos** [comment]
Is there any chance this can be sped up?

**Comment by robtimmer** [comment]
+1 for this feature

**Pull request closed without merging**
