### PR TITLE
test: Added test for Download feature

### PR DESCRIPTION
**Pull request by NandanAnantharamu**
Table Download feature
Download csv
Download xlsx

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>
No changes to code coverage between the base branch and the head branch</details>

### CODE REVIEW

**Review by yatinappsmith — APPROVED** [review]

**Review by yatinappsmith — APPROVED** [review]

**Comment by NandanAnantharamu** [comment]
duplicate

**Pull request closed without merging**
