### PR TITLE
fix: Avoid HikariCP creating idle connection on Postgres DB

### LINKED ISSUE #14117: [Bug]: Postgresql connections are left idle.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After running a query postgres connections are left idel

### Steps To Reproduce

1. Create Postgress data source.
2. Create multiple onload select queries.
3. Create multiple pages.
4. traverse multiple all the pages few times.
5. Check idle connections

### Public Sample App

https://release.app.appsmith.com/app/habitasaurus/page1-628f4177dfdca56c4283eb2a/edit/queries/628f4182dfdca56c4283eb2c

### Version

cloud

## Update:
- A large part of the issue is supposed to be resolved by this [fix](https://github.com/appsmithorg/appsmith/pull/14348). 
- Unsolved part is described [here](https://www.notion.so/appsmith/Postgres-multiple-idle-connections-issue-72cc080691c64385ab3efab5d573c630).

Front logo [Front conversations](https://app.frontapp.com/open/top_5sozw)

### PR DESCRIPTION
**Pull request by nidhi-nair**
## Description

A few users noticed that Appsmith was creating surplus connections in their database even when connected through a single datasource. Ideally, this number should start from 5 and not exceed beyond total concurrent requests in the app/workspace. However, it seems like HikariCP tends to send the following query outside of the connection pool size for every query that we try to run.
```
SET application_name = 'PostreSQL JDBC Driver'
```

This PR has introduced a custom set application name to all connections to avoid sending this set query along with every execution request, according to this [post](https://seethawenner.medium.com/improve-the-performance-of-your-aws-rds-postgres-database-by-avoiding-session-pinning-a4f010109bed).

Unfortunately, while this solution has lowered the number of such set queries, they have not disappeared entirely. There is another alternative [here](https://github.com/appsmithorg/appsmith/pull/21780) that requires us to let users know about minimum version support for PG so we will not be opting for that solution at this time.

Fixes #14117

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manual
- JUnit

### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by subrata71 — APPROVED** [review]

**Comment by btsgh** [comment]
@nidhi-nair  - hey - the DP suddenly stopped working with the error - 
503 Service Temporarily Unavailable
nginx

Any ideas why?

**Comment by subrata71** [comment]
> @nidhi-nair - hey - the DP suddenly stopped working with the error - 503 Service Temporarily Unavailable nginx
> 
> Any ideas why?

@btsgh [This](https://theappsmith.slack.com/archives/CGBPVEJ5C/p1680245144918199) could be the reason.

**Comment by btsgh** [comment]
Here are a few observations on the Prod environment [Jacques' app] - @nidhi-nair 
1. Have had the app open and running the queries at some regular intervals for the whole of today. I have not been able to hit 200 connections so far. Max I have hit is around 54 connections and the number of set application_name was 13 in this case.
On the DP generated for this issue:
1. Followed the above steps as suggested by Rohan to create the DS connected to supabase. Tried re-running the queries for the same duration as above and probably even more. Here the number of max connections that were reached were about 7, with the number of set application_name being 2 out of them.

**Comment by nidhi-nair** [comment]
Thanks for documenting your observations here @btsgh .. Considering that this is a non-interfering change, we have decided to merge it in so that we're able to assess whether the lower number of `SET application_name` calls truly does fix the issue. 

This PR would still need to be followed up by more optimizations to reduce this numbers to 0, and to avoid creating a pool in every pod as stated in the PR description.

**Comment by btsgh** [comment]
@nidhi-nair - Please go ahead and merge.

**Pull request merged**
