### PR TITLE
fix: library installation failure in public apps

### LINKED ISSUE #20207: [Bug]: Installed JS libraries fail to load on public apps for anon users
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Installed JS libraries fail to load on public apps for anon users

### Steps To Reproduce

1. Add a custom library and use it in a binding/function so it can run on a deployed app
2. Deploy the app and make it public
3. Open the app link as an anon user and observe the library does not load

[Slack thread](https://theappsmith.slack.com/archives/CGBPVEJ5C/p1674729997721399)

### Public Sample App

_No response_

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by arunvjn**
## Description
- Feature flag API returns an empty response for public applications. The API to fetch installed libraries was behind the custom JS library feature flag and thus wasn't invoked. This PR removes all the references to CUSTOM_JS_LIB feature flag in the code base.
- Add change to make Custom JS Lib view endpoint accessible without login. 
- Add JUnit TC to test for js lib presence in view mode. 

Fixes #20207

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manual
- Cypress

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [x] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by trishaanand — COMMENTED** [review]
Server side changes LGTM

**Review by ApekshaBhosale — DISMISSED** [review]

**Comment by ramsaptami** [comment]
gtg to release
CC: @arunvjn

**Review by Rishabh-Rathod — APPROVED** [review]
Frontend changes LGTM

**Pull request merged**
