### PR TITLE
fix: Tweak how we show errors for required and not required inputs

### LINKED ISSUE #6857: [Bug] isValid errors on the input widget
## Description

- When the input type is set to number, The isValid for a required field return null / undefined on pageLoad and hence the form buttons by default is enabled for an invalid form. 
- When a field is not required and empty, it should not show an error, given valid and regex properties are also empty
- The input widget shows an error briefly when the value is first changed from empty (this happens only on first keypress in an empty input)

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Release

### PR DESCRIPTION
**Pull request by SatishGandham**
## Description
Tweak how input fields validations for require, not required fields are handled when they are empty.

Fixes #6857

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue) 

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/inconsistent-validations-input-widget 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 54.89 **(0)** | 37.04 **(-0.01)** | 33.88 **(0)** | 55.5 **(0)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 50.47 **(-0.24)** | 38.26 **(-0.87)** | 36.21 **(0)** | 55.08 **(-0.27)**</details>

### CODE REVIEW

**Comment by somangshu** [comment]
The 3rd issue which shows the field as invalid for a second before turning valid when required is enabled  still exists, Also there are multiple conditions for required here, @riodeuno please check the code.

**Comment by SatishGandham** [comment]
@somangshu  Will take up the third as a separate issue. Can not find the source yet.
Since it is marked as high priority pushed fixes for the two.

**Review by jsartisan — DISMISSED** [review]

**Comment by somangshu** [comment]
> @somangshu Will take up the third as a separate issue. Can not find the source yet.
> Since it is marked as high priority pushed fixes for the two.

@ramsaptami can you separate the issue please

**Comment by riodeuno** [comment]
@SatishGandham If I leave the field empty, while the `isRequired` is `false`, the validation still fails
Screenshot 2021-09-24 at 3 28 11 PM
Screenshot 2021-09-24 at 3 29 43 PM

.

**Comment by ramsaptami** [comment]
@somangshu raised #7810 
Haven't updated the description yet since I'm not clear on the cause - will update it once I have more information

**Review by riodeuno — APPROVED** [review]

**Pull request merged**
