### PR TITLE
fix: edit and launch button fail on keeping mouse over while reload

### LINKED ISSUE #36804: [Bug]: Edit and Launch buttons fail to appear if mouse pointer is hovering over the Application box while loading webpage
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

While loading the page https://app.appsmith.com/applications, if the mouse pointer is hovering over an area where an application box is supposed to load, the `Edit` and `Launch` buttons fail to appear. The mouse pointer needs to be removed away from the application box, for these two buttons to appear normally when the mouse pointer is again returned to the same place.

### Steps To Reproduce

1. Go to https://app.appsmith.com/applications or the same location on your self-hosted setup.
2. Refresh the page. While the site is loading, keep your mouse pointer on one of the application boxes.
3. When all the components of the page have loaded, the `Edit` and `Launch` buttons do not appear, even if the mouse pointer is moved or clicked all over the application box.
4. When the mouse pointer is moved outside the application box and returned, both the buttons appear normally.

https://github.com/user-attachments/assets/794805bd-d28c-470c-a9f7-24ac6e196bbd

 

### Public Sample App

_No response_

### Environment

Production

### Severity

Low (Cosmetic UI issues)

### Issue video log

_No response_

### Version

Cloud : v1.45.0-SNAPSHOT / Self-hosted : v1.44.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by ALOK9442**
## Description

> Fixes edit and launch buttons fail to appear if mouse pointer is hovering over the Application box while loading webpage
> Tested it thoroughly.

https://github.com/user-attachments/assets/797df6c8-04b7-48af-ae87-51a89ad25e62

Fixes #36804  

## Automation

/ok-to-test tags=""

### :mag: Cypress test results

> [!CAUTION]  
> If you modify the content in this section, you are likely to disrupt the CI result for your PR.

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [ ] No

## Summary by CodeRabbit

- **Bug Fixes**
	- Updated mouse event handling in the Card component for improved overlay display behavior.

- **Refactor**
	- Adjusted event triggering from `onMouseEnter` to `onMouseOver` without altering overall functionality.

### CODE REVIEW

**Comment by ankitakinger** [comment]
@ALOK9442 Could you rearrange the props `onMouseOver` and `onMouseLeave` alphabetically? It causing lint failure.

**Comment by ALOK9442** [comment]
> @ALOK9442 Could you rearrange the props `onMouseOver` and `onMouseLeave` alphabetically? It causing lint failure.

@ankitakinger  sure, also can you tell me like what should be the commit message? should it be same as previous or the changes I did now like the reordering it alphabetically

**Comment by ALOK9442** [comment]
hey @ankitakinger , now I am getting an error 
✖ eslint --fix --cache:
Oops! Something went wrong! :(
ESLint: 9.12.0
ESLint couldn't find an eslint.config.(js|mjs|cjs) file.

after I am commiting the changes

image

**Comment by ALOK9442** [comment]
hey @ankitakinger , could you check this error as I searched this error and it is saying to rename the file .eslintrc.js file, to eslint.config.js
which I got after commiting the changes
Screenshot 2024-10-17 215805

**Comment by ankitakinger** [comment]
@ALOK9442 can you try by going in to the client folder first on your terminal and then do the commit?
```
cd app/client
git commit -m "fix: linting error reorder props alphabetically"
```

**Comment by ALOK9442** [comment]
@ankitakinger , I tried and still getting the same error and also a new error of gitleaks 
image

**Comment by ankitakinger** [comment]
@ALOK9442 Seems like you have a higher version of `eslint` installed. Can you commit with the `--no-verify` flag here?

**Comment by ALOK9442** [comment]
> --no-verify

I have commit the changes, please check

**Comment by ALOK9442** [comment]
> @ALOK9442 you haven't pushed the changes it seems

Sorry, it got delayed because of internet issue, it's done now

**Review by ankitakinger — APPROVED** [review]

**Comment by ankitakinger** [comment]
@ALOK9442 Thank you for your contribution.

**Comment by ALOK9442** [comment]
> @ALOK9442 Thank you for your contribution.

@ankitakinger I'm glad I could help

**Pull request merged**
