### PR TITLE
chore: Refactor RapidMode and add optimization if a test uses DSL

### LINKED ISSUE #23264: [Task]: Refactor Rapid Mode configuration for skipping reload if a test uses dsl for testing
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

1. Move rapid mode configuration from index.ts file to local cypress.env.json file. This file is gitignored and users will not have to set rapid mode to false everytime.
2. It skips multiple visits to app page if a test uses DSL. This will help reduce 10 seconds on each test re-run locally.

Notion Doc for updated configuration: https://www.notion.so/appsmith/Run-Cypress-locally-23033565651344f78ea2c8be768004bf?pvs=4#f9dd7872d97e49efbc87261819de8ab1

Github documentation at : https://github.com/appsmithorg/appsmith/blob/chore/release/contributions/docs/TestAutomation.md

### PR DESCRIPTION
**Pull request by rajatagrawal**
Fixes #23264

### CODE REVIEW

**Review by Aishwarya-U-R — APPROVED** [review]

**Review by Rishabh-Rathod — APPROVED** [review]
LGTM. Thanks for working on this.

**Pull request merged**
