### PR TITLE
feat: font update - PT root UI medium

### LINKED ISSUE #32720: [Task] - Update system font to PT root UI

### PR DESCRIPTION
**Pull request by albinAppsmith**
## Description

This PR update default font to PT Root UI.

Fixes #32720 

## Automation

/ok-to-test tags="@tag.Sanity"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9001227602>
> Commit: 491aaf0d92f123482c88c6ec13999e0356dbea53
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9001227602&attempt=1" target="_blank">Click here!</a>

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [x] No

## Summary by CodeRabbit

- **Style**
	- Removed font smoothing properties from the body styling to enhance text clarity and appearance across web browsers.

### CODE REVIEW

**Comment by albinAppsmith** [comment]
./build-deploy-preview skip-test=true

**Review by KelvinOm — DISMISSED** [review]

**Review by hetunandu — APPROVED** [review]

**Pull request merged**
