### PR TITLE
feat: Updates table widgets to v2

### LINKED ISSUE #18250: [Feature]: Update table to table v2 in CRUD generation
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Only update the table widget to table v2 for now in crud page

### Why should this be worked on?

People starting from crud pages are running into bugs which we are not fixing because of older versions of tables.

Front logo [Front conversations](https://app.frontapp.com/open/top_5w824)

### PR DESCRIPTION
**Pull request by souma-ghosh**
## Description

This PR updates all the table widgets in CRUD App Templates from v1 to v2

Fixes #18250
> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

- New feature (non-breaking change which adds functionality)

- Manual
- Jest
- Cypress

### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by keyurparalkar — APPROVED** [review]

**Comment by laveena-en** [comment]
@souma-ghosh Looks like the branch hasn’t been deployed. Can we please check?

**Comment by souma-ghosh** [comment]
DP is up @laveena-en

**Comment by kamakshibhat-appsmith** [comment]
@souma-ghosh The custom columns ordering is different than what we had in old tables.
in v1, it used to be at the end.
in v2, it is coming at the first position. 
Please check .

**Comment by souma-ghosh** [comment]
> @souma-ghosh The custom columns ordering is different than what we had in old tables. in v1, it used to be at the end. in v2, it is coming at the first position. Please check .

The change we made to address is that we have frozen the delete columns to the right in all the table widgets. Created a separate issue for this [here](https://github.com/appsmithorg/appsmith/issues/21128).
We can move ahead with the QA here @kamakshibhat-appsmith

**Comment by kamakshibhat-appsmith** [comment]
There are some critical issues coming with CRUD apps that is because of column freeze feature. I would suggest to fix the column freeze bugs before proceeding with this PR

**Comment by kamakshibhat-appsmith** [comment]
There are some critical issues coming with CRUD apps that is because of column freeze feature. I would suggest to fix the column freeze bugs before proceeding with this PR

**Comment by kamakshibhat-appsmith** [comment]
There are some critical issues coming with CRUD apps that is because of column freeze feature. I would suggest to fix the column freeze bugs before proceeding with this PR

1. The delete column (Custom column )is coming at the very first position
2. the delete column (custom column) is getting frozen (Custom columns should not be frozen by default)
3. The custom columns ,are getting right frozen by default (which is also wrong ref point 2) but on the UI it is coming at the left most position.

**Comment by dilippitchika** [comment]
@souma-ghosh why was this not checked when you integrated the column freeze part. Why did this go to @kamakshibhat-appsmith when it's clearly not working?

**Comment by somangshu** [comment]
@keyurparalkar @kamakshibhat-appsmith @dilippitchika I am closing this for now, We should pick this up once Keyur is back, we should also re-figure the priority at this point in time

**Review by sbalaji1192 — DISMISSED** [review]

**Comment by keyurparalkar** [comment]
@kamakshibhat-appsmith @chandannkumar Can you please test this PR once again so that it works as expected?

**Comment by nidhi-nair** [comment]
Hey @keyurparalkar , sorry I see that your PR was close to being merged. Could you please rebase the PR back to your own last commit? I'll pick up my changes after yours is done.

**Comment by kamakshibhat-appsmith** [comment]
Callouts 
1. the page is getting unresponsive for movies DB when you select any row
2. since scroll content is off by default in the CRUD templates' Modals, we are having issues with auto layout where we are unable to scroll the overflowed content as under the hood scroll contents is OFF and we have removed the properties from property pane
@keyurparalkar

**Pull request closed without merging**
