### PR TITLE
fix: Update designs for select widgets according to Figma

### LINKED ISSUE #8308: [Bug] Widget design audit: select / multi-select / multi treeselect / treeselect Widget
## Description

This is to make cosmetic changes to the select / multi-select / multi treeselect / treeselect widget based on the changes after the design audit. Here we are covering:

- [ ] Removed the radio button from all the single selection  dropdowns 
- [ ] Standardised the icon for the dropdown (new icon)
- [ ] Selected and hover states defined

## Developer handoff file:
https://www.figma.com/file/w9CaXHF5iYcrLtiEbAHcFu/Original-Theme-Widgets-Library?node-id=469%3A5738

### LINKED ISSUE #8611: [Feature]: Label for select and multi-select
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

A user should be able to set label for the select / multi-select widgets from the property pane. This will be in consistency to the tree select widgets.

Screenshot 2021-10-19 at 12 10 39 PM

### Why should this be worked on?

Better consistency / polish

### PR DESCRIPTION
**Pull request by techbhavin**
## Description

> update in design select / multi-select / multi treeselect / treeselect Widget

Fixes #8308
Fixes #8611 

## Type of change

- Bugfix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: bug/design-audit-select-multi-tree 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 54.58 **(0)** | 36.33 **(-0.11)** | 33.11 **(-0.11)** | 55.09 **(-0.02)**
 :green_circle: | app/client/src/components/ads/Icon.tsx | 50.79 **(0.39)** | 33.54 **(0.42)** | 100 **(0)** | 50.66 **(0.4)**
 :sparkles: :new: | **app/client/src/widgets/DropdownWidget/component/index.styled.tsx** | **50** | **11.76** | **0** | **50**
 :red_circle: | app/client/src/widgets/DropdownWidget/component/index.tsx | 81.16 **(-0.32)** | 50.77 **(-9.7)** | 68.42 **(-7.77)** | 80.6 **(-0.17)**
 :green_circle: | app/client/src/widgets/DropdownWidget/widget/index.tsx | 71.74 **(0.63)** | 23.53 **(0)** | 63.64 **(0)** | 70.73 **(0.73)**
 :red_circle: | app/client/src/widgets/MultiSelectTreeWidget/component/index.styled.tsx | 50 **(-4.84)** | 25 **(-0.93)** | 0 **(0)** | 51.52 **(-4.04)**
 :green_circle: | app/client/src/widgets/MultiSelectTreeWidget/component/index.tsx | 23.91 **(3.46)** | 0 **(0)** | 0 **(0)** | 26.19 **(3.11)**
 :red_circle: | app/client/src/widgets/MultiSelectWidget/component/index.styled.tsx | 51.72 **(-40.59)** | 24.14 **(-75.86)** | 0 **(0)** | 51.85 **(-48.15)**
 :green_circle: | app/client/src/widgets/MultiSelectWidget/component/index.tsx | 18.33 **(1.02)** | 0 **(0)** | 0 **(0)** | 19.64 **(0.89)**
 :green_circle: | app/client/src/widgets/MultiSelectWidget/widget/index.tsx | 50 **(1.02)** | 0 **(0)** | 50 **(0)** | 51.06 **(1.06)**
 :red_circle: | app/client/src/widgets/SingleSelectTreeWidget/component/index.styled.tsx | 52.78 **(-5.84)** | 25.81 **(-1.11)** | 0 **(0)** | 53.13 **(-4.56)**
 :green_circle: | app/client/src/widgets/SingleSelectTreeWidget/component/index.tsx | 24.44 **(3.51)** | 0 **(0)** | 0 **(0)** | 26.83 **(3.15)**</details>

### CODE REVIEW

**Comment by somangshu** [comment]
Suggest we take label as a new requirement. Ill create a requirement and re-assign

**Review by Tooluloope — DISMISSED** [review]

**Review by Tooluloope — APPROVED** [review]

**Comment by techbhavin** [comment]
- comment 1 
    1. issue with height
        - we have given min height 36 px to all inputs as per design audit issue
        - When user change label text size widget size changes but widget can not resize the container, so widget container needs to be resized manually.
    2. Default Label Text Size will show as “Paragraph” now instead of “No Selection”
- comment 2
    1. To solve : “https://github.com/appsmithorg/appsmith/pull/8594#issuecomment-946405114” when user drag drops select widget first list item gets focused, which enables arrow key to work for selection. This focus applies css for highlight.
    2. This changes are same as figma design
    3. Error shown are errors in widget PropertyPane and not widget itself. Widget will not be aware of OR effected by any errors in configuration inside property pan.
    4. fixed
    5. updated help text - “Sets a Label Text”
    6. fixed
    7. This is not scope of current issue, which only addresses design changes.
    8. its default functionality of rc-tree-select third-party library being used under the hood for this widget
    9. select input is already searchable
        1. required new issue if we want search in dropdown

@shwetha-ramesh

**Comment by shwetha-ramesh** [comment]
@techbhavin The dp doesnt seem to be ready to verify the issues you've fixed. Here are few more things that has been observed for #8308

1. As per document for Multiselect widget - Active + Hover over 4th item (refer image) over hover an unselected item the font appears bold. The same is not noticed here in dp (Refer video)
image
https://loom.com/share/d0ca2d54dc394b818b1ee5ec16a83b12

2. As per document for Multiselect widget/Multitreeselect/ Tree select widget - Error state the widget border is highlighted in Red (refer image). The same is not noticed here in dp. 
image
image

3. Disabled - need clarity multiselect/multitreeselect/treeselect, whether 'x' marks need to appear.

4. As per document for Multitreeselect widget / Multiselect / Treeselect widget - Placeholder must be Select options, 's' is small here in DP.
image

5. As per document for Multitreeselect widget - Active + Hover over 4th item (refer image) over hover an unselected item the font appears bold. The same is not noticed here in dp (Refer video)
image
https://loom.com/share/1ecabd0d938342a59172560b91969263

**Moving this issue to In Progress.**

**Comment by shwetha-ramesh** [comment]
> @somangshu Are covering this here as well, i.e. adding a different input for searching Screenshot 2021-10-26 at 03 37 07

@somangshu clarity on this would be appreciated. A separate search tray currently is not present, should this be implemented ?

**Comment by somangshu** [comment]
@shwetha-ramesh @techbhavin please note if the package supports this, its possible right away, Otherwise I suggest looking at this from the design POV again, Is this really required, If so, We should create a new issue around this and deal with it separately.

@techbhavin please verify the implementation in the current package

cc: @momcilo-appsmith

**Comment by momcilo-appsmith** [comment]
If it is noot possible right away, do not include it, do it the way it is done today.

**Comment by shwetha-ramesh** [comment]
@techbhavin issue 2 for #8611 still persists. Moving to _In Progress_

**Comment by techbhavin** [comment]
1. updated
2. Error shown are errors in widget PropertyPane, not widget errors, so first we have to detect that there is an error in property pane or not, then we can highlight widget border in red as per Figma
3. when Multitreeselect / Multiselect disabled, ‘x’ removed by third party library “rc-tree-select”
4. updated
5. updated

@shwetha-ramesh  Here Point 2 and 3 are repeated from your end. why we can’t cover this point in this PR that i  try to explain in my previous comment

**Comment by techbhavin** [comment]
https://github.com/appsmithorg/appsmith/actions/runs/1439369355

**Comment by shwetha-ramesh** [comment]
@techbhavin Tested this PR for #8303 wrt your comments. 

1.  If the feature is to show the first list item focused which enables arrow key to work for selection - from the below video you can see for Select widget by default the first item gets focused however with mouse hover the third item is also getting focused which I think is bad UX. Also for multitree select and tree select the first item is not focused for arrow key selection. There is no consistency is the 4 widgets. 
https://loom.com/share/58b991d92a9044e2991be55093d959fc

2. Sorted.

3. As I can notice from the Figma document the widget appears Red when there is an error. @momcilo-appsmith @somangshu any input on this will be helpful
image

4. Not in scope - Creating separate issue

5. Not in scope - Creating separate issue

6. Not fixed. 

7. Not in scope

8. Not fixed - @somangshu: any input on this will be helpful. Issue is when the widgets multi select & multitree select  is disabled the selections made appear without 'x' mark for all the options. Where as figma doc shows otherwise 
image

9. Package not supported for separate search tray. Dropping this.

Test for 2nd comment. 
1. Fixed 
2 & 3 - Duplicate of 3,8 from above.
4. Fixed
5. Fixed.

**Comment by techbhavin** [comment]
https://github.com/appsmithorg/appsmith/actions/runs/1443778583

**Comment by shwetha-ramesh** [comment]
@techbhavin Tested PR for #8611.
Issue1: Not fixed
Issue2: FIXED.

**Comment by techbhavin** [comment]
https://github.com/appsmithorg/appsmith/actions/runs/1448288267

**Comment by shwetha-ramesh** [comment]
@techbhavin Retested this PR for #8308: as discussed when ’required’ is enabled and there is no selection made the widget tile appears red. 

**_Moving this issue to DONE._**

**Review by Tooluloope — DISMISSED** [review]
Code wise, LGTM

**Comment by somangshu** [comment]
@techbhavin what is the update here, Please move it to the right pipeline, And let me know how can we close this?

**Review by Tooluloope — DISMISSED** [review]

**Review by Tooluloope — APPROVED** [review]

**Pull request merged**
