### PR TITLE
fix: [Bug]Audio option hidden on edit mode

### LINKED ISSUE #7868: [Bug]Audio option hidden on edit mode
## Description

**Audio option hidden on edit mode has been going under the main navigation pane** 
the option working fine on View mode though
Capture

### PR DESCRIPTION
**Pull request by AR10X**
## Description

Fixes #7868

## Type of change

Hidden the audio options as per https://github.com/appsmithorg/appsmith/issues/7868#issuecomment-932018289

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by AR10X** [comment]
Does it open a download and playback window after you click the three dots?

**Comment by AR10X** [comment]
> @AR10X It does. But not in an obvious position. That's why we decided to completely remove it. Kindly check the issue for more context.

Ok I will try a different solution.

**Review by aswathkk — CHANGES_REQUESTED** [review]
@AR10X Linting issues are not yet resolved. I could see that build is failing due to that.
Check [here](https://app.netlify.com/sites/appsmith-editor-ce/deploys/617e6d9c7e06010008b0b32a) to see the full logs and linting issues.

I would recommend you to install VSCode Extensions like Prettier which will auto-fix the linting issues for you.

**Review by aswathkk — APPROVED** [review]
LGTM

**Pull request merged**
