### PR TITLE
fix: Icon alignment changes automatically every time the icon is changed in Menu button widget

### LINKED ISSUE #11482: [Bug]: Icon Alignment changes automatically every time when icon is changed in Menu Widget
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Every we click on icon and change the existing icon, the alignment of the icon changes automatically to default one

[LOOM DEMO](https://www.loom.com/share/7cab0f5d9c02429c9eb1ede268fea69b)

### Steps To Reproduce

1. Add Menu widget to the canvas
2. Select a icon from property pane
3. Set icon alignment to Right view so that icon will display the right of menu widget
4. Change the icon and observe that icon alignment gets changed to other selection

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by wmdev0808**
## Description
Every time we click on an icon and change the existing icon, the alignment of the icon changes automatically to default one

Fixes #11482 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Test A
- Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>
No changes to code coverage between the base branch and the head branch</details>

### CODE REVIEW

**Review by Tooluloope — APPROVED** [review]
LGTM
@wmdev0808 Could you add cypress test for this fix

**Review by Tooluloope — APPROVED** [review]

**Comment by shwetha-ramesh** [comment]
@wmdev0808 tested this PR. DP is working fine.
Moving to Done.

**Pull request merged**
