### PR TITLE
fix: Filter columns which has a column accessor

### LINKED ISSUE #6968: [Bug] Error: A column ID (or string accessor) is required!
Sentry Issue: [APPSMITH-11W](https://sentry.io/organizations/appsmith/issues/2582221574/?referrer=github_integration)

```
Error: A column ID (or string accessor) is required!
  at assignColumnAccessor (../../src/utils.js:56:11)
  at None (../../src/utils.js:22:5)
  at Array.map (<anonymous>)
  at linkColumnStructure (../../src/utils.js:15:18)
  at a (../../src/hooks/useTable.js:151:7)
...
(45 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by vicky-primathon**
## Description
Filter columns which does not have an accessor property

Fixes #6968 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/table-crash-column 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 55.01 **(-0.01)** | 36.91 **(-0.01)** | 33.91 **(0.01)** | 55.56 **(-0.01)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 50.47 **(-0.24)** | 37.72 **(-0.88)** | 36.21 **(0)** | 55.08 **(-0.27)**
 :green_circle: | app/client/src/widgets/TableWidget/derived.js | 54.5 **(0.24)** | 53.57 **(0)** | 39.47 **(1.63)** | 54.07 **(0)**</details>

### CODE REVIEW

**Review by marks0351 — APPROVED** [review]

**Comment by riodeuno** [comment]
@vicky-primathon There is a test failing in this PR. Please confirm that this isn't related to changes in this PR.

**Comment by vicky-primathon** [comment]
> @vicky-primathon There is a test failing in this PR. Please confirm that this isn't related to changes in this PR.

Failing test is from FormWidget. No changes has been made related to that.

**Comment by vivekverma2312** [comment]
@vicky-primathon Did a round of sanity around table widget as the steps to repro was not able to for the issue.

**Comment by somangshu** [comment]
After running the tests twice `Entity_Explorer_Multiple_Widgets_spec.js` started failing now

cc @yatinappsmith

**Comment by somangshu** [comment]
@vicky-primathon @riodeuno all tests have passed now. Please merge this if  the bug is resolved

**Pull request merged**
