### PR TITLE
feat: disable parsing link

### LINKED ISSUE #5377: [Bug] Label text widget gets converted into link automatically without option to Disable the link
## Description

Label text widget, when entered with something that resembles a link or an email gets converted into a link. With no option to disable it.

### Steps to reproduce the behaviour:

Add steps to reproduce this behaviour, include console / network logs & screenshots

1. Go to the Editor page
2. Drag Label Text Widget to the canvas
3. Add text as "Employee.Id" or "Ph.No"
4. The text gets converted to a link without an option to disable it.

image

### Important Details

- Version: [Cloud]
- Browser [chrome]
- Environment [production]

### PR DESCRIPTION
**Pull request by Tooluloope**
## Description

Add option to disable parsing as link

Fixes #5377  (issue)

## Type of change
- New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: feat/disable-parsing-link 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 54.78 **(-0.01)** | 36.5 **(0.01)** | 33.98 **(0)** | 55.33 **(-0.01)**
 :red_circle: | app/client/src/selectors/commentsSelectors.ts | 78.23 **(-1.61)** | 54.41 **(-2.94)** | 70 **(0)** | 84.09 **(-2.27)**
 :green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 50.71 **(0.24)** | 39.13 **(0.87)** | 36.21 **(0)** | 55.35 **(0.27)**
 :red_circle: | app/client/src/widgets/TextWidget/component/index.tsx | 100 **(0)** | 71.67 **(-0.74)** | 100 **(0)** | 100 **(0)**
 :green_circle: | app/client/src/widgets/TextWidget/widget/index.tsx | 100 **(0)** | 75 **(25)** | 100 **(0)** | 100 **(0)**</details>

### CODE REVIEW

**Review by somangshu — DISMISSED** [review]
Code LGTM. Approving to run test.

In the deploy preview the functionality does not work for email, which was the case before. 

@Tooluloope also check for any failing test before pushing it again to review

**Review by SatishGandham — APPROVED** [review]

**Review by somangshu — DISMISSED** [review]
LGTM, Approving to run the tests

**Review by somangshu — DISMISSED** [review]
Approving to run tests

**Review by aswathkk — DISMISSED** [review]
Approving to run tests

**Review by aswathkk — APPROVED** [review]
Approving to run the tests

**Comment by YogeshJayaseelan** [comment]
@Tooluloope Verified the fix now user will able to disable link using the toggle. Works as expected

**Pull request merged**
