### PR TITLE
 chore: improvements added in gsheet form config for feature flag

### LINKED ISSUE #20925: [Task]: Improvement for feature flag info in form config
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

In this https://github.com/appsmithorg/appsmith/pull/20395, we have added feature flag in datasource form config json, to show appropriate config based on feature flag. One thing we could improve is currently we are passing just the flag condition and hidden flag value as true or false, we could also pass in information like which feature flag to check the conditions against. 
`"hidden": {
        "comparison": "FEATURE_FLAG",
        "value": true
      },`
Currently config looks like this, we could add one more property indicating which flag to compare these values against.

### PR DESCRIPTION
**Pull request by sneha122**
## Description

This PR adds code review improvements for feature flag in gsheets form config as per https://github.com/appsmithorg/appsmith/pull/20395

> Add a TL;DR when description is extra long (helps content team)

Fixes #20925 
> if no issue exists, please create an issue and ask the maintainers about this first

Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video

## Type of change

> Please delete options that are not relevant.

- Chore (housekeeping or task changes that don't impact user perception)

## How Has This Been Tested?

- Manual

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by sumitsum — APPROVED** [review]

**Comment by sumitsum** [comment]
Server side change LGTM.

**Review by Irongade — APPROVED** [review]

**Pull request merged**
