### PR TITLE
chore: remove defaultSelectedFiles

### PR DESCRIPTION
**Pull request by Rishabh-Rathod**
## Description

- `defaultSelectedFiles` field is not being used anywhere and hence can be removed.

## Type of change

- chore

## How Has This Been Tested?

current cypress tests

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>
No changes to code coverage between the base branch and the head branch</details>

### CODE REVIEW

**Review by SatishGandham — APPROVED** [review]

**Review by riodeuno — APPROVED** [review]

**Comment by somangshu** [comment]
@Rishabh-Rathod Pawn is not available right now, just FYI

**Comment by Rishabh-Rathod** [comment]
> @Rishabh-Rathod Pawn is not available right now, just FYI


No worries 2 reviews are good for this to be merged. This PR was blocked by the failing test.

**Pull request merged**
