### PR TITLE
fix: JSObject AST parsing logic

### LINKED ISSUE #15009: [Task]: Add check to match `jsObject` node for AST parsing logic
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

As we set the `jsObjectVariableName` in the jsCode which we parse for AST for JSObject.

we could only focus on particular variable name instead of all variableDeclarator.
Hence adding `node.id.name === jsObjectVariableName`.

It worked without it as jsObject was the last node to be called in variableDeclarator when parsing AST.

### PR DESCRIPTION
**Pull request by Rishabh-Rathod**
## Description

As we set the jsObjectVariableName in the jsCode which we parse for AST, 
- we could only focus on particular variable name instead of all variableDeclarator.
 
Hence adding `node.id.name === jsObjectVariableName`. 

It worked without it as jsObject was the last node to be called in variableDeclarator when parsing AST. 

Fixes #15009

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by ohansFavour — CHANGES_REQUESTED** [review]
- Attach issue to this PR
- Add jest test prevent this from happening in the future

**Review by ohansFavour — APPROVED** [review]

**Comment by Rishabh-Rathod** [comment]
Testing for this PR is skipped as this changes doesn’t change any functionality and just add a logical check in code.

**Pull request merged**
