### PR TITLE
[Enhancement] Double click to open Property pane.

### LINKED ISSUE #5424: [Enhancement] Open Property pane only on clicking on widget name
## Summary

- Open property pane only via the widget toggle(widget name) instead of opening it up on clicking on the widget/ resizing/ dragging.
- Open property pane when a new widget is dropped into canvas.

## Motivation

Property pane often comes in the way when the user wants to just move around widgets or resize them or interact with them which ends up into a bad UX. 

## Additional Context

When a new widget is added property pane is shown.

### PR DESCRIPTION
**Pull request by marks0351**
> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Description

Open property pane only via the widget toggle(widget name) and double-clicking on the widget instead of opening it up on clicking on the widget/ resizing/ dragging.

Fixes #5424 

> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/prop-pane-double-click 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 53.92 **(0.02)** | 36.03 **(0.03)** | 32.6 **(0)** | 54.5 **(0.03)**
 :green_circle: | app/client/src/components/editorComponents/DraggableComponent.tsx | 85.71 **(2.66)** | 68.57 **(7.03)** | 73.33 **(0)** | 86 **(2.98)**
 :red_circle: | app/client/src/components/editorComponents/DropTargetComponent.tsx | 63.64 **(-0.65)** | 39.73 **(0)** | 50 **(0)** | 59.09 **(-0.68)**
 :green_circle: | app/client/src/components/editorComponents/ResizableComponent.tsx | 59.55 **(0.21)** | 23.73 **(0.78)** | 63.64 **(0)** | 58.62 **(0.19)**
 :red_circle: | app/client/src/selectors/propertyPaneSelectors.tsx | 92.31 **(-3.84)** | 94.12 **(0)** | 83.33 **(-16.67)** | 92 **(-4)**
 :green_circle: | app/client/src/utils/hooks/useClick.tsx | 95 **(15)** | 78.57 **(14.28)** | 100 **(0)** | 95 **(15)**
 :sparkles: :new: | **app/client/src/utils/hooks/useDoubleClickOpenPropPane.tsx** | **86.36** | **48.94** | **100** | **85.48**
 :x: | ~~app/client/src/utils/hooks/useClickOpenPropPane.tsx~~ | ~~81.13~~ | ~~52.63~~ | ~~100~~ | ~~80~~</details>

### CODE REVIEW

**Review by SatishGandham — APPROVED** [review]

**Review by SatishGandham — APPROVED** [review]

**Comment by vivekverma2312** [comment]
@marks0351 Observations:
1. If we set click action on button widget then double click do not open the property pane
2. Select/unselect checkbox and radio widget with single click also open property pane
https://www.loom.com/share/81dc19eab07d45e380d44006aed0596c
3. Double tap on touch bar works but not with double-click (This is related to mac touchpad)
4. Double tap is not smooth for list widget - Need more that 2 tap for property open if tapping on individual container
https://www.loom.com/share/fd77f6fba06746d18c0ef708f871e83e
5. There is space between widget and property pane
Screenshot 2021-07-08 at 10 09 35 AM

Testing is still in progress, I will post here if we find some more new issues.

**Comment by riodeuno** [comment]
@marks0351 Closing this for now, let's keep track of the branch name and we'll get to this again, if we decide to do so.

**Pull request closed without merging**
