### PR TITLE
chore: Sunset Omnibar Documentation and Snippets

### LINKED ISSUE #24278: [Feature]: Sunset Documentation in the omnibar
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Omnibar Documentation: The purpose of this feature was to help users with in-app documentation that they could use to solve their problems. Over time, the maintenance of this feature has been a major challenge and it's led to poor experiences while using the product. In the future, we will simply open our docs in a new tab.

### Why should this be worked on?

Documentation in the omnibar has been an ongoing problem for us. Maintenance, as well as a lack of user response. We find that users are struggling with this, and usually don't find helpful documentation links

### SubTasks

- [ ] [Change existing links from the errors tab to docs.appsmith.com](https://github.com/appsmithorg/appsmith/issues/24279) 
- [ ] Disable the hotkey and the omnibar section for documentation (possibly move behind FF)
- [ ] Remove the documentation in the omnibar altogether
- [ ] Disable the middle layer we currently use to translate info from the docs to the omnibar format

### LINKED ISSUE #24279: [Task]: The `Open documentation` button in the error messages tab should lead to the docs.appsmith.com
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [ ] Change existing links from the errors tab to this link: https://docs.appsmith.com/help-and-support/troubleshooting-guide 
- [ ] Verify with the TM pod if we need to take this into account for the airgapped project/version

### LINKED ISSUE #24280: [Feature]: Remove snippets
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Snippets are turning out to be difficult to maintain, as well as a very low success rate. It was intended to show users example code, however, we have not seen a great response from users. They usually ignore it, and the few who do end up using it rarely find success

### Why should this be worked on?

Snippets: The purpose of this feature was to help users with example code they could use to achieve their bindings. The feature adoption has been around 12% of the overall user base and only about 1.8% of users ever see success with it. Less than 3% of users have ever used it more than 2 times. On top of that, we have never maintained or updated the snippets here so it warrants us killing it.

### SubTasks
- [ ] Take a dump of all existing snippets, Share the snippets with the docs team to see if they find value in adding them to the documentation page
- [ ] Remove all front end access to the snippets (via omnibar, CTAs and hotkeys)
- [ ] Move the feature behind a featureflag
- [ ] Remove it altogether

### PR DESCRIPTION
**Pull request by hetunandu**
## Description

We are removing the documentation and snippets that used to be shown in the omnibar. These features are not being maintained and usage is pretty low.

#### PR fixes following issue(s)
Fixes #24278
Fixes #24279
Fixes #24280

#### Type of change

- Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### How Has This Been Tested?

- [x] Manual
- [x] Cypress

#### Test Plan
https://github.com/appsmithorg/appsmith/pull/24787#issuecomment-1611180354

#### Issues raised during DP testing
https://github.com/appsmithorg/appsmith/pull/24787#issuecomment-1611475323

#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [x] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [x] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [x] Test plan has been peer reviewed by project stakeholders and other QA members
- [x] Manually tested functionality on DP
- [x] We had an implementation alignment call with stakeholders post QA Round 2
- [x] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by akash-codemonk — DISMISSED** [review]

**Comment by kavitasmoolya** [comment]
Performed testing on [DP](https://ce-24787.dp.appsmith.com/) and covered below scenarios 

- [ ] Navigation to omnibar via keyboard shortcut (ctrl+k) 
- [ ] Navigation to omnibar via UI option
- [ ] Remove snippet from omnibar
- [ ] keyboard shortcut' should not work for snippet and documentation
- [ ] Keyboard shortcut for navigation and create a query link should work as same as prod
- [ ] Remove all front end access to the snippets (via omnibar, CTAs and hotkeys)
- [ ] Disable the hotkey and the omnibar section for documentation.
- [ ] Remove the documentation in the omnibar altogether
- [ ] Respective documentation link opens up in https://docs.appsmith.com/ not dp url
- [ ] Check above scenarios for git connected app as well
- [ ] The Open documentation button in the error messages tab should lead to the docs.appsmith.com

@ramsaptami Please review it and let me know if anything more to be added in the list.

**Comment by kavitasmoolya** [comment]
@hetunandu Please have a look into below issues 

- [ ] Tooltip `"Open doc in omnibar" ` displays even though we have removed documentation from omnibar.
image

- [ ] "Get Appsmith Support" link does not display in error tab on DP and Release both but it displays on prod. 
image

**Review by akash-codemonk — APPROVED** [review]

**Pull request merged**
