### PR TITLE
feat: move `Use this template` to top of iframe

### LINKED ISSUE #15946: [Task]: Updates to Template Page in Platform (Move 'Fork this template' button, add query param to open forking modal)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

In the Templates tab of the platform, update the individual template page at:
https://app.appsmith.com/templates/APP_ID

- [ ] Move the **Fork this template** button above the iframe so it is visible without having to scroll down. The template title and forking button should both be in the same div, similar to the [website](https://www.appsmith.com/template/discord-bot-for-github-updates)
- [x] Add query parameter that opens the forking modal i.e. `?modal=true` or similar. Adding this to url should trigger the forking modal to open on page load. This will be used when directing a user from the website to the platform.

### PR DESCRIPTION
**Pull request by rahulbarwal**
## Description
* Moved `Use this template` from description to header. 
* Restructured template `Header` to its separate component.
#### PR fixes following issue(s)
Fixes #15946
#### Media
Screenshot 2023-06-12 at 2 54 42 PM

#### Type of change
- New feature (non-breaking change which adds functionality)
#### How Has This Been Tested?
- [x] Cypress
>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by akash-codemonk — DISMISSED** [review]

**Review by tanvibhakta — APPROVED** [review]
approved for ads usage

**Comment by shwetha-ramesh** [comment]
@rahulbarwal QA Done
image

**Pull request merged**
