### PR TITLE
fix: Binding appsmith.user to text label by default

### LINKED ISSUE #22336: [Enhancement]: Change the default value on the Text widget's Text property
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

The current default value on a Text widget's Text property is `Label` and it hardly serves any purpose. 

Change the default value of the Text widget's Text property to `Hello {{appsmith.user.name}}` and make it easier for users to discover bindings

### Why should this be worked on?

New users usually skip the onboarding and later find it hard to discover bindings on the property pane. The Text widget is the first widget that users drag and drop on the canvas and serves as an ideal point to help users discover bindings.

### PR DESCRIPTION
**Pull request by arunvjn**
## Description
Binds text widget default text to `appsmith.user.name` or  `appsmith.user.email`. 
Motivation is to let new users know about bindings
>
> Links to Notion, Figma or any other documents that might be relevant to the PR
>
>
#### PR fixes following issue(s)
Fixes #22336 
>
>
#### Type of change
- Bug fix (non-breaking change which fixes an issue)
>
>
>
#### How Has This Been Tested?
- [x] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by Rishabh-Rathod — APPROVED** [review]
LGTM

**Comment by arunvjn** [comment]
Closing this PR since we cannot support this for Form widget just yet

**Pull request closed without merging**
