### PR TITLE
fix: Input, Phone and Currency input widgets valid property validations

### LINKED ISSUE #10893: [Bug]: Currency Input stops accepting valid input after removing condition in valid property
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If you add a condition in the valid property and then remove it later , the Currency Input widget flags all valid data as Invalid Input

### Steps To Reproduce

1. Drag and drop a Currency Input widget.
2. Add a condition in the valid property. The widget works fine even if you modify this condition
3. Now remove the condition in the valid property.
3. The widget stops accepting any valid input thereafter.

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by sbalaji1192**
Fixes #10893

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/input-widget-validation-property 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 55.06 **(0)** | 36.39 **(0.01)** | 34.7 **(0)** | 55.43 **(0)**
 :green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.94 **(0.23)** | 41.67 **(0.84)** | 36.21 **(0)** | 56.99 **(0.25)**</details>

### CODE REVIEW

**Review by ashit-rath — APPROVED** [review]

**Comment by YogeshJayaseelan** [comment]
@sbalaji1192 Tested this PR and it is working as expected

**Pull request merged**
