### PR TITLE
Refactor: remove `true` from boolean attribute

### PR DESCRIPTION
**Pull request by withshubh**
### Description
Hi :wave: I ran the [DeepSource](https://deepsource.io) static analyzer on the forked copy of this repo and found some [interesting code quality issues](https://deepsource.io/gh/withshubh/appsmith/issues/). This PR fixes a few of them.

### Summary of changes
- Removed `true` from boolean attribute 
- added .deepsource.toml file

### CODE REVIEW

**Review by riodeuno — APPROVED** [review]
@withshubh Thanks for your contribution in running deepsource and bringing these issues to light.

**Comment by withshubh** [comment]
@riodeuno I would like to share the steps to activate the [DeepSource](https://deepsource.io/) analysis on the repo. Activating analysis will help you to continuously analyze repo for code quality issues and fix commonly occurring issues using the auto-fix feature. You can also use it to track test coverage and detect problems in Dockerfile.

#### Using DeepSource to continuously analyze your repository:
- Install DeepSource on your repository [here](https://deepsource.io/signup).
- create `.deepsource.toml` configuration which you can use to configure your analysis settings.
- Activate analysis [here](https://deepsource.io/gh/appsmithorg/appsmith/).

Note: This PR merged the `.deepsource.toml` file so you need not create the configuration file but if you want you can modify it any time either manually or update it from the dashboard as per your requirement.

**Comment by withshubh** [comment]
Hi @riodeuno :wave: Just want to follow up! :sparkles:

**Comment by withshubh** [comment]
Hi @riodeuno @mohanarpit :wave: 

Did you activate and try out DeepSource? Would love to know your feedback :)

**Pull request merged**
