### PR TITLE
test: Added Support for MySQL

### LINKED ISSUE #6794: [Bug] Cypress Doesnot support MySQL
## Description

Cypress Doesnot support MySQL

### Steps to reproduce the behaviour:

Add steps to reproduce this behaviour, include console / network logs & screenshots

Cypress Doesnot support MySQL

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment [production, release, deploy preview]

### PR DESCRIPTION
**Pull request by yatinappsmith**
## Description

Add support MySQL

Fixes #6794

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Tested locally

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: test/MySQLSupport 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 54.62 **(0.01)** | 36.68 **(0.01)** | 33.04 **(0)** | 55.22 **(0)**
 :green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 50.71 **(0.24)** | 38.6 **(0.88)** | 36.21 **(0)** | 55.35 **(0.27)**</details>

### CODE REVIEW

**Review by NandanAnantharamu — APPROVED** [review]
LGTM

**Review by NandanAnantharamu — DISMISSED** [review]
LGTM

**Review by NandanAnantharamu — APPROVED** [review]
LGTM

**Comment by yatinappsmith** [comment]
Added tests for MySQL

**Pull request merged**
