### PR TITLE
fix: fetch actions and plugins before choosing which GQL editor tab to focus

### LINKED ISSUE #33695: [Bug]: GraphQL query editor: Headers tab is the default one after a reload
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The GraphQL query editor differs from other editors as its default tab is the "Body" tab, instead of the "Headers" tab.
After reloading the page while in the GraphQL editor, the "Headers" tab is selected instead of the "Body" tab.

### Steps To Reproduce

In an existing application:
1. Create a new GraphQL query
2. Reload the page

https://github.com/appsmithorg/appsmith/assets/1488378/c731efa6-2d7d-4605-97df-9cf249bfc7f9

### Public Sample App

_No response_

### Environment

Production

### Severity

Low (Cosmetic UI issues)

### Issue video log

_No response_

### Version

Cloud - Appsmith v1.27.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by danguilherme**
## Description
[`FocusRetentionSaga`](https://github.com/appsmithorg/appsmith/blob/d71e050fa6ad1da1aed222d756fb2c523c75d322/app/client/src/sagas/FocusRetentionSaga.ts) is not respecting the GraphQL API editor [subtype](https://github.com/appsmithorg/appsmith/blob/release/app/client/src/ce/navigation/FocusElements/AppIDE.ts#L162-L164) when the page is being loaded because it's running its focus management logic before knowing that the action being edited is in fact a GraphQL plugin action.

So now I am waiting for the app's actions and plugins to be loaded before the [focus retention logic](https://github.com/appsmithorg/appsmith/blob/d71e050fa6ad1da1aed222d756fb2c523c75d322/app/client/src/sagas/FocusRetentionSaga.ts#L183-L210) is run.

<table>
<tr>
 <td><strong>Before
 <td><strong>After
<tr>
 <td>

https://github.com/appsmithorg/appsmith/assets/1488378/22350e6e-c8e8-42d9-82da-aa2034279808

 <td>

https://github.com/appsmithorg/appsmith/assets/1488378/9c126a01-76de-4c4f-9c05-fbd566399e22

</table>

Fixes #33695

## Automation

/ok-to-test tags="@tag.All"

### :mag: Cypress test results

> [!CAUTION]  
> If you modify the content in this section, you are likely to disrupt the CI result for your PR.

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by danguilherme** [comment]
Hey @jsartisan, I'm tagging you as you were the person that reviewed my last PR. Could you please take a look at this one?

**Review by hetunandu — APPROVED** [review]

**Comment by hetunandu** [comment]
@danguilherme can you also add this scenario to the test case [here](https://github.com/appsmithorg/appsmith/blob/release/app/client/src/ce/navigation/FocusStrategy/AppIDEFocusStrategy.test.ts#L231)

**Comment by danguilherme** [comment]
@hetunandu done!

**Comment by danguilherme** [comment]
Hey there @hetunandu, any updates here? Commenting so it's not closed.

**Review by hetunandu — APPROVED** [review]

**Comment by hetunandu** [comment]
All tests passed in the [mirror PR](https://github.com/appsmithorg/appsmith/pull/33976). Merging this in

**Pull request merged**
