### PR TITLE
Fix page name special character bug

### LINKED ISSUE #765: [BUG] Special Character is not accepted in the page name but results into empty space (1st character).
Attachment - https://drive.google.com/drive/folders/1dK1x9FR-RfkgD0WQoUZhiHINkFoS-A7G?usp=sharing

Browser Details: Chrome
Device Details: macOS 10.15.6 (MacBook Pro)
Note: Tried on cloud.

Steps to replicate:
1. Go to 'Edit App'
2. Go to page name --> Edit Name
3. Now type a special character or . (full stop) or , (comma)

Expected Result: If it's not accepted, cursor shouldn't move.
Actual Result: Since, characters mentioned in step 3 are not accepted, they result into empty spaces.
Note: Only results into an empty space while typing the 1st character, works fine 2nd character onwards.

### PR DESCRIPTION
**Pull request by nuwan94**
## Description
In page name edit, when the user entered a special character cursor shouldn't move with space. Previously defined `resolveAsSpaceChar` function was replace with `resolveAsEmptyChar` function.

Fixes #765 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by riodeuno** [comment]
Hi @nuwan94 Thanks for the fix.
One of the reasons the previous function worked the way it did, was that, we would like the ability to use a space character between words in the page entity names.
So, while `my$page` would not be valid, `my page` and `my_page` are valid page entity names.

Could you update the function to allow for spaces? The implementation in the PR works well for special characters other than spaces.

One more detail: There should ideally be only one `space` character between any two words, and consecutive `space` characters between two words may not be allowed.

**Comment by nuwan94** [comment]
@riodeuno Sure I will modify the code accordingly.

**Comment by satbir121** [comment]
@nuwan94 @riodeuno What is happening with this issue?

**Comment by nuwan94** [comment]
@riodeuno I changed back to `resolveAsSpaceChar` and modify it to allow space characters.
Could you please review the changes? 😃

**Review by riodeuno — APPROVED** [review]

**Comment by riodeuno** [comment]
LGTM!

**Pull request merged**
