### PR TITLE
fix: removes error count form widget name component

### LINKED ISSUE #22892: [Bug]: Remove error number from the widget name component
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Currently , errors in the the widget show up in the name of the widget.  We need to remove the error number altogether as red color is indicative enough

### Steps To Reproduce

Screenshot 2023-05-02 at 11 20 00 AM

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

Production

### PR DESCRIPTION
**Pull request by aswathkk**
## Description
Removes the error count form the widget name

#### PR fixes following issue(s)
Fixes #22892
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
#### Media
before:

after:
Screenshot 2023-06-20 at 10 50 58 AM

#### Type of change
- Bug fix (non-breaking change which fixes an issue)

- [x] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by marks0351 — APPROVED** [review]

**Comment by kamakshibhat-appsmith** [comment]
Can we merge latest release and also point to latest cloud service?

**Comment by kamakshibhat-appsmith** [comment]
LGTM ! We can merge

**Pull request merged**
