### PR TITLE
chore: store value perf

### LINKED ISSUE #14760: [Task]: Performance - storeValue each action increases worker - main thread communication
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

| Number of StoreValue action |  Screenshot of performance profile |
|---|---|
| 1 | SCR-20220623-hj3 |
| 3 | SCR-20220623-hgt |
| 9 | SCR-20220623-hkg |

### Problem 
As we could notice in above screenshots. 
With the increase in the `storeValue` action number, main thread is doing more work. 

If evaluation could batch the storeValue result and only communicate once, that would be ideal. 

###  Initial task
We will need to measure the impact
- performance gain vs the effort

### Possible approach to solve
-  We could execute the `storeValue` action inside the worker and at the end of the action trigger execution push the change to the main thread.
or 
- We could consider using IndexedDB for persistent `appsmith.store` and remove the need for main-thread communication for store value update. This could be big change as
     - After the update, we also need to make such unEvalTree diff detects this change.
     - Maybe also fetch values from localStorage to support previous persistence values and prefer IndexedDB values over localStorage.

### PR DESCRIPTION
**Pull request by arunvjn**
## Description
Batch store ops (storeValue, removeValue and clearStore) requests for performance.
Existing implementation of these store functions make a request to the main thread per invocation.
All occurrences of store functions are now batched and sent together.

#### Code changes.
- Removed store fns from the current implementation of "Promisified" action.
- All store function now resolves immediately to keep it backward compatible.
- Introduced TriggerCollector(could be renamed in the subsequent PRs) class which batches all store operations and sends one request once the call stack is empty.
- Remove transient and persistent store from appsmith store. All store updates will now be under one key.

Fixes #14760

## Type of change
- Perf optimisation

## How Has This Been Tested?
- Jest
- Manual
  - [ ]  https://github.com/appsmithorg/TestSmith/issues/2142
  - [ ] https://github.com/appsmithorg/TestSmith/issues/2083
  - [ ] https://github.com/appsmithorg/TestSmith/issues/2074
  - [ ] https://github.com/appsmithorg/TestSmith/issues/1960

### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Comment by arunvjn** [comment]
Perf improvements-
Code snippet used in profiles
`for(let i=0; i< x; i++) {
	storeValue(i, i*2);
}`

Iterations | Release | DP
---|---|---
1000 | 4.5s | 180ms
100 | 750ms | 140ms
10 | 350ms | 120ms

**Comment by arunvjn** [comment]
### 1000 iterations
#### Before
Screenshot 2023-01-02 at 20 36 39

----

#### After 
Screenshot 2023-01-02 at 20 34 28

**Review by ApekshaBhosale — APPROVED** [review]

**Review by ApekshaBhosale — APPROVED** [review]

**Pull request merged**
