### PR TITLE
fix: child widget not updating state  in List widget

### LINKED ISSUE #21515: [Bug]: The checkbox/switch (and groups') state is not updating consistently when used inside List widget
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The checkbox/switch(and groups) is having inconsistencies when used inside List widget. 

### Steps To Reproduce

1. DnD a checkbox inside a List
2. Try click on the checkbox to change its state in each List Item
3. Observe that sometimes the State doesn't update and kind of hangs

https://www.loom.com/share/d662269507dd4d4caf049c261d8b59a2

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by Tooluloope**
## Description
The checkbox/switch(and groups) are not updating state when used inside the List widget.
This is due to the positioning set on the List widget Containers.

Fixes #21515

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Cypress

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by prsidhu — APPROVED** [review]

**Comment by chandannkumar** [comment]
@Tooluloope 
- Observed Inconsistent behavior on updating Switch group in List child widget
https://bthrujcsw8.vmaker.com/record/ZAHBaXLoYhAAInki

**Comment by Tooluloope** [comment]
@chandannkumar This is also happening in Production.

Could you open a new issue for that and assign it to me?
This PR doesn't cover that.

**Comment by chandannkumar** [comment]
> @chandannkumar This is also happening in Production.
> 
> Could you open a new issue for that and assign it to me? This PR doesn't cover that.

Here is the issue:
https://github.com/appsmithorg/appsmith/issues/21745

**Comment by chandannkumar** [comment]
Tested this PR and LGTM

**Pull request merged**
