### PR TITLE
fix: calculate fluid tokens based on provider width

### LINKED ISSUE #29177: Сalculate fluid tokens based on provider width

### PR DESCRIPTION
**Pull request by KelvinOm**
## Description
- calculate fluid tokens based on the provider's width
- slightly improve performance for tokens calculation

#### PR fixes following issue(s)
Fixes #29177 

#### Media

https://github.com/appsmithorg/appsmith/assets/11555074/2d8eb354-2269-4282-84ce-33d58f6eee88

- Bug fix (non-breaking change which fixes an issue)

- [x] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress

#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### CODE REVIEW

**Comment by ichik** [comment]
@KelvinOm tooltip positioning in broken (see Chromatic).

**Comment by KelvinOm** [comment]
> @KelvinOm tooltip positioning in broken (see Chromatic).

Thanks for highlighting this.

**Review by ichik — APPROVED** [review]

**Pull request closed without merging**
