### PR TITLE
FIX #4875 : update modal onclick reference for same modal while pasting modal

### LINKED ISSUE #4875: [Bug] Copying a modal retains the close icon reference
## Description

When a modal is copied into a new widget, the close button of the new widget seems to retain the reference to the old modal. As a result, the new modal remains open.

### Steps to reproduce the behaviour:

1. Create a new modal
2. Copy this modal (cmd + c)
3. Click on the canvas to close first modal
4. Paste a new modal (cmd + v)
5. Open the new modal and try to use the close button on it.
6. The modal remains open.

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment [production, release, deploy preview]

### PR DESCRIPTION
**Pull request by vibhandikyash**
Fixes #4875 

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Tested Locally.
> Added new Test cases

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: FIX/4875-model-close-icon-reference-update 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 51.6 **(0.02)** | 32.74 **(0.02)** | 29.73 **(0.03)** | 52.1 **(0.02)**
 :green_circle: | app/client/src/sagas/WidgetOperationUtils.ts | 76.19 **(3.97)** | 65.63 **(4.09)** | 70 **(12.86)** | 74.58 **(4.58)**</details>

### CODE REVIEW

**Review by jsartisan — APPROVED** [review]

**Comment by somangshu** [comment]
Tests failing, Re-ran!

**Comment by vivekverma2312** [comment]
@vibhandikyash **Issue**: In deploy preview I am not able to open the 2nd Modal.
Steps:
1. Create a new modal
2. Copy this modal (cmd + c)
3. Click on the canvas to close first modal
4. Paste a new modal (cmd + v)
5. Not able to open second modal

https://www.loom.com/share/af3e99891cc94a878407eef391474e1b

**Comment by somangshu** [comment]
@vivekverma2312 my bad, I didn't realize that you were still testing this out on the deploy preview. Can we check this on release and create a Bug for this if required. You can assign it back to me. Ill take care of it!

**Pull request merged**
