### PR TITLE
fix: Design system package conflict with babel-plugin-styled-components

### PR DESCRIPTION
**Pull request by albinAppsmith**
## Description

This PR will resolve the `.withConfig is not a function` error in local development. This issue was only affecting the local development when user tries to click on design system components.

List of components got changed
- Callout
- Color Picker
- Color Selector
- Date Picker
- Dialogue component
- Icon
- LabelWithTooltip
- Menu
- Menu Item
- MultiSwitch
- NotificationBanner
- Rectangular Switch
- Search Input
- Showcase Carousal
- Step Component
- Table Dropdown
- Tabs
- Toggle

Fixes [#16685](https://github.com/appsmithorg/appsmith/issues/16685)

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Tested in local

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by shadabbuchh** [comment]
Tested all the above components in this PR. No issues found.

**Review by aswathkk — APPROVED** [review]

**Pull request merged**
