### PR TITLE
fix: Reset on submit for Number type in Input widget

### LINKED ISSUE #8437: [Bug]: Number Input Don't Get Reset On Form Submit
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using a resettable form, the number input widget doesn't reset. I've added a video here to show this

> It's also noteworthy to mention that force resetting the input widget with the `resetWidget` function still doesn't work

https://user-images.githubusercontent.com/17744578/136925939-44dcc380-1a2d-47d4-a525-6636703aacf2.mp4

### Steps To Reproduce

```markdown
I've illustrated the steps to reproduce this in the attached video
```

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by sbalaji1192**
## Description

Fixes #8437 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/input-reset-on-submit 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 55.29 **(0.09)** | 37.13 **(0.16)** | 34.34 **(0.18)** | 55.81 **(0.1)**
 :green_circle: | app/client/src/components/ads/Button.tsx | 90.85 **(0)** | 75.65 **(1.74)** | 95.56 **(0)** | 91.43 **(0)**
 :green_circle: | app/client/src/components/ads/TextInput.tsx | 75.41 **(0)** | 48.6 **(0.94)** | 84.21 **(0)** | 74.55 **(0)**
 :green_circle: | app/client/src/components/ads/Toggle.tsx | 86.36 **(59.09)** | 53.57 **(46.43)** | 80 **(80)** | 85 **(55)**
 :sparkles: :new: | **app/client/src/components/ads/formFields/FieldError.tsx** | **100** | **75** | **100** | **100**
 :sparkles: :new: | **app/client/src/components/ads/formFields/TextField.tsx** | **100** | **66.67** | **100** | **100**
 :green_circle: | app/client/src/pages/Settings/Main/Link.tsx | 100 **(0)** | 85 **(5)** | 100 **(0)** | 100 **(0)**
 :sparkles: :new: | **app/client/src/pages/Settings/Main/TextInput.tsx** | **100** | **75** | **100** | **100**
 :sparkles: :new: | **app/client/src/pages/Settings/Main/Toggle.tsx** | **80.95** | **62.5** | **57.14** | **80**
 :sparkles: :new: | **app/client/src/pages/Settings/Main/group.tsx** | **97.06** | **71.88** | **100** | **96.77**
 :green_circle: | app/client/src/widgets/InputWidget/widget/index.tsx | 62.86 **(0.72)** | 43.24 **(1.57)** | 69.57 **(0)** | 65 **(0.71)**</details>

### CODE REVIEW

**Review by jsartisan — DISMISSED** [review]

**Comment by shwetha-ramesh** [comment]
@sbalaji1192 tested this PR. DP looks good. Input widget of data type _number_ resets on Form submit in both edit & view mode.

**Review by jsartisan — APPROVED** [review]

**Pull request merged**
