### PR TITLE
feat: #4141 added truncate support into text widget

### LINKED ISSUE #4141: [Feature] Setting to truncate text in the text widgets
## Summary
Today the text widget truncates long text by showing only the center lines and hides the rest of it. See screenshot.
Screen Shot 2021-04-26 at 4 04 41 AM

Some solutions to improve this
1. To show the entire text without truncating it. This would overflow onto other widgets, but it would serve the purpose of displaying the entire text
2. Give the user the option of truncating the text in the property pane. I saw a good way inside Glide apps to do this.
[LOOM DEMO](https://www.loom.com/share/437277aeaec840b186f83468700a35e5)

## Figma Design Link

https://www.figma.com/file/5Gmo3788ASY2CJcHMJsU7u/Text-Style?node-id=2%3A262

### PR DESCRIPTION
**Pull request by vibhandikyash**
## Description

> Add support for truncate functionality in Text Widget.

Fixes #4141 

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Tested locally.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: FEATURE/4141-setting-truncate-text 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 55.06 **(0.01)** | 36.5 **(0.01)** | 34.47 **(0.01)** | 55.58 **(0)**
 :sparkles: :new: | **app/client/src/components/designSystems/appsmith/ModalComponent.tsx** | **56.67** | **30.77** | **26.67** | **58.62**
 :red_circle: | app/client/src/utils/WorkerUtil.ts | 89.76 **(0)** | 70.59 **(-1.96)** | 100 **(0)** | 93.33 **(0)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.71 **(-0.23)** | 40.83 **(-0.84)** | 36.21 **(0)** | 56.74 **(-0.25)**
 :red_circle: | app/client/src/widgets/TextWidget/component/index.tsx | 80.28 **(-19.72)** | 67.33 **(-11)** | 78.95 **(-21.05)** | 79.71 **(-20.29)**</details>

### CODE REVIEW

**Review by Tooluloope — APPROVED** [review]
LGTM
Would just require cypress tests.

@somangshu Would it be required to move the text styles like(Font color, Font size, Cell background into the modal?

**Comment by somangshu** [comment]
@Tooluloope great point.

@Tooluloope @vibhandikyash for now we should keep it to a default which is extensible as a config later.

**Comment by shwetha-ramesh** [comment]
@vibhandikyash Tested this PR, below are the few observations I have made

1. When Text widget is placed inside Form widget and ```Truncate Text``` is set to true, the ```ellipsis ...``` has a grey background which appears distinct from the widget in edit & view mode
image

2. Any styles added to the widget is not replicated in the Modal.
https://www.loom.com/share/5d08d46ae4f745a08b1f2ddf3e295717

**Comment by techbhavin** [comment]
@shwetha-ramesh  
point 1: Fixed 
point 2: Not relevant point 

@somangshu  can you please help us with point 2. did we want that feature?

**Comment by somangshu** [comment]
@shwetha-ramesh if issue 2 also exist in the release, we should create a separate issue to deal with it.

@techbhavin @shwetha-ramesh we need to confirm the ui with @momcilo-appsmith @UXFalcon after a design audit.

cc @areyabhishek

**Comment by shwetha-ramesh** [comment]
> @shwetha-ramesh if issue 2 also exist in the release, we should create a separate issue to deal with it.
> 
> @techbhavin @shwetha-ramesh we need to confirm the ui with @momcilo-appsmith @UXFalcon after a design audit.
> 
> cc @areyabhishek

@somangshu I just cross verified issue 2 ; ```truncate``` is a new feature and does not exist on release.

**Comment by somangshu** [comment]
@shwetha-ramesh I was talking about the other styles, Do they persist in the modal

**Comment by shwetha-ramesh** [comment]
@vibhandikyash As discussed wrt UI on display of text on the widget, when large data is present the context seems to cut off and not appear legible. A consistency can be maintained before and after truncate to always show the first line of the text.
image

https://loom.com/share/ff04cc3be77f43e19ffd0214cf54cbbb

Also need confirmation on the discussion we had regarding moving the ```ellipsis...``` next to the text. @somangshu @momcilo-appsmith

**Comment by somangshu** [comment]
> A consistency can be maintained before and after truncate to always show the first line of the text.

@shwetha-ramesh this is not going to be possible because the first line is shown when scroll is enabled, I.E. the user is requesting to get the content on scroll, When it is not enabled we need to keep the text center aligned, Since the content is big in your example, its overflowing, But remaining centered, Now what if the widget dimensions were huge, The content would be expected to remain centered. Am I right?

WRT the discussion, With the bug resolved on the PR, we are currently awaiting a feedback from @areyabhishek & @momcilo-appsmith, We will proceed accordingly

**Pull request merged**
