### PR TITLE
MS SQL Plugin implementation

### PR DESCRIPTION
**Pull request by sharat87**

### CODE REVIEW

**Comment by sharat87** [comment]
@Nikhil-Nandagopal FYI, this plugin refers to MsSQL logo at `https://s3.us-east-2.amazonaws.com/assets.appsmith.com/MsSQL.jpg` and documentation to be at `https://docs.appsmith.com/core-concepts/connecting-to-databases/querying-mssql` (both of which are missing currently but I've used these URLs so they can be setup separately).

**Review by mohanarpit — APPROVED** [review]

**Comment by mohanarpit** [comment]
@sharat87 Can you please reference the issue in the commit message & PR so that the issue will automatically get updated once this is merged in?

**Comment by sharat87** [comment]
I deliberately don't mention the issue number in the commit message because it will get closed before it is available on release/prod. The idea is that we close them after they get on release/prod.

But, of course, I'd start doing this from next PR onwards (since this is the second time someone's asking for this) :)

**Comment by sharat87** [comment]
Implementation for #1155.

**Pull request merged**
