### PR TITLE
chore: Switch from OTLP HTTP/protobuf (New Relic) to HTTP/JSON (Grafana)

### PR DESCRIPTION
**Pull request by subhrashisdas**
Fixes #`Issue Number`  
_or_  
Fixes `Issue URL`
> [!WARNING]  
> _If no issue exists, please create an issue first, and check with the maintainers if the issue is valid._

## Automation

/ok-to-test tags="@tag.All"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/11885638023>
> Commit: 9878a3e760992ade7bce76565385d7f482eb6df1
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=11885638023&attempt=2" target="_blank">Cypress dashboard</a>.
> Tags: `@tag.All`
> Spec:
> <hr>Mon, 18 Nov 2024 05:59:27 UTC

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [x] No

## Summary by CodeRabbit

- **New Features**
	- Introduced new monitoring paths for telemetry data exports: `/monitoring/traces` and `/monitoring/metrics`.
	- Added a function to streamline URL management for telemetry exports.

- **Bug Fixes**
	- Updated telemetry export protocols to enhance reliability and performance.

- **Chores**
	- Updated multiple OpenTelemetry dependencies to their latest versions for improved functionality and security.
	- Removed outdated OpenTelemetry dependencies to optimize performance.

### CODE REVIEW

**Review by rajatagrawal — DISMISSED** [review]

**Review by nidhi-nair — APPROVED** [review]

**Comment by KelvinOm** [comment]
What do you think about updating the [RTS dependencies](https://github.com/appsmithorg/appsmith-ee/pull/5530#pullrequestreview-2437796574) too?

**Comment by subhrashisdas** [comment]
Hi @KelvinOm, 
- The changes have been made in the CE repo; the first task is done.  
- The dependencies in the RTS package have been updated as specified.  
- All dependencies used in the RTS package are now explicitly listed and correctly defined.

**Comment by KelvinOm** [comment]
> Hi @KelvinOm,
> 
> * The changes have been made in the CE repo; the first task is done.
> * The dependencies in the RTS package have been updated as specified.
> * All dependencies used in the RTS package are now explicitly listed and correctly defined.

Thank you for your efforts!

**Review by KelvinOm — APPROVED** [review]

**Pull request merged**
