### PR TITLE
fix: Table crashes when column width is greater than component width

### LINKED ISSUE #25166: Table crashes when componentWidget is negative TypeError: Cannot read properties of undefined (reading 'width')
Sentry Issue: [APPSMITH-6N0](https://appsmith.sentry.io/issues/4250755458/?referrer=github_integration)

```
TypeError: Cannot read properties of undefined (reading 'width')
  at getColumnsPureFn (widgets/TableWidgetV2/widget/reactTableUtils/getColumnsPureFn.tsx:112:51)
  at _this.getTableColumns (widgets/TableWidgetV2/widget/index.tsx:402:12)
  at <object>.value (widgets/TableWidgetV2/widget/index.tsx:949:31)
  at <object>.value (widgets/BaseWidget.tsx:747:17)
  at _this.getWidgetComponent (widgets/BaseWidget.tsx:621:16)
...
(20 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by berzerkeer**
## Description
- When the table's column width is greater than the component width the table widget crashes.

> Links to Notion, Figma or any other documents that might be relevant to the PR
>
>
#### PR fixes following issue(s)
Fixes #25166 

#### Media
https://vdqm24wed6.vmaker.com/record/q4yZXh8n0uv7sVrl
>
#### Type of change

- Bug fix (non-breaking change which fixes an issue)

## Testing

- [x] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [x] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by sbalaji1192 — APPROVED** [review]

**Comment by laveena-en** [comment]
Verified, PR looks good to me!

**Pull request merged**
