### PR TITLE
feat: Add option to delete empty organization

### LINKED ISSUE #924: [Enhancement] Add the option to delete an organization from the user's home page
## SubTasks

- The backend needs to add an API `DELETE /api/v1/organizations/{id}` that recursively deletes all the applications, pages, actions & datasources for a given organization ID. Once all the sub-entities have been deleted, the API will then delete the organization entity as well.
- The frontend needs to integrate with the API 
- The frontend needs to refresh it's local list of organizations so that this change can be reflected in the UI.

### PR DESCRIPTION
**Pull request by arunvjn**
## Description
Added option to delete organization to users with manage org permissions when there are no apps left in the organization.

Fixes #924 

## Type of change
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
-Manual
-Cypress
-Junit tests

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: feature/add-option-to-delete-org 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 55.22 **(-0.01)** | 37.08 **(0)** | 34.06 **(-0.02)** | 55.73 **(-0.01)**
 :red_circle: | app/client/src/actions/orgActions.ts | 67.86 **(-0.14)** | 100 **(0)** | 0 **(0)** | 52.63 **(-0.31)**
 :red_circle: | app/client/src/api/OrgApi.ts | 55.88 **(-0.37)** | 0 **(0)** | 7.69 **(-0.64)** | 54.55 **(-0.29)**
 :red_circle: | app/client/src/constants/messages.ts | 74.09 **(-0.01)** | 100 **(0)** | 23.3 **(-0.05)** | 79.57 **(0.03)**
 :red_circle: | app/client/src/reducers/uiReducers/applicationsReducer.tsx | 9.47 **(-0.21)** | 30 **(0)** | 6.38 **(-0.29)** | 9.78 **(-0.22)**
 :red_circle: | app/client/src/sagas/OrgSagas.ts | 18.06 **(0.01)** | 2.56 **(-0.14)** | 6.67 **(-0.47)** | 22.61 **(-0.03)**</details>

### CODE REVIEW

**Review by albinAppsmith — APPROVED** [review]

**Review by albinAppsmith — APPROVED** [review]

**Review by albinAppsmith — APPROVED** [review]

**Review by albinAppsmith — APPROVED** [review]

**Review by albinAppsmith — APPROVED** [review]

**Comment by areyabhishek** [comment]
Can we merge this in?

**Comment by nayan-rafiq** [comment]
@areyabhishek I'm working on the resolving the conflicts due to code split. Hopefully we can merge this by today.

**Review by albinAppsmith — APPROVED** [review]

**Review by albinAppsmith — APPROVED** [review]

**Pull request merged**
