### PR TITLE
feat: added scrollbar to repo limit error modal

### LINKED ISSUE #11780: [Task]: Add scrolling to Repository Limit Reached modal
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

As of right now, if user converts a lot of connected public repo to private, there is no way to scroll all the connected private repos.

Screenshot 2022-03-10 at 11 55 03 PM

### PR DESCRIPTION
**Pull request by haojin111**
## Description

> added scrollbar to repo limited error modal

Fixes #11780 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Please check linked issue

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>

    // Code coverage diff between base branch:release and head branch: feat/11780-add-scrolling-repo-limit-modal 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.94 **(0.23)** | 41.67 **(0.84)** | 36.21 **(0)** | 56.99 **(0.25)**</details>

### CODE REVIEW

**Comment by haojin111** [comment]
repo_limit

**Review by IAmAnubhavSaini — APPROVED** [review]

**Comment by haojin111** [comment]
repo_limit_modal_scrolling
repo_limit_modal_scrolled

**Review by IAmAnubhavSaini — APPROVED** [review]

**Pull request merged**
