### PR TITLE
test: Unit test for datatype evaluation logic

### LINKED ISSUE #15759: [Task]: Write jest test case to evaluate the logic for finding a given value's datatype
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

1. Research on how to write cypress test cases on API request payload/ function.
2. Write test cases for all the changes.

### PR DESCRIPTION
**Pull request by ChandanBalajiBP**
## Description

>Includes the jest cases to evaluate the logic for finding a given value's datatype

Fixes #15759 

## Type of change

- New feature(test case) (non-breaking change which adds functionality)

## How Has This Been Tested?
- unit testing (Jest)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ x I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by sneha122 — APPROVED** [review]
Looks Good!!

**Comment by ChandanBalajiBP** [comment]
This PR has only jest test case for the datatype handling Client side changes. Thus, will be skipping the QA process and add the `testplanapproved` label myself.

**Pull request merged**
