### PR TITLE
fix: Issue with git UI after ADS v2 release

### PR DESCRIPTION
**Pull request by albinAppsmith**
## Description

This PR fixes below mentioned issues,
1. Git error callout is not being visible until user scroll down.
2. Git branch name button have fixed width even if the branch name is short.
3. Added data-testid for create branch spinner.

#### PR fixes following issue(s)
Fixes #
https://github.com/appsmithorg/appsmith/issues/23617

#### Media

https://github.com/appsmithorg/appsmith/assets/87797149/34d5c576-a610-4565-901a-05d33d640214

#### Type of change

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

## Testing

- [ ] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by akash-codemonk — APPROVED** [review]

**Comment by shadabbuchh** [comment]
This PR has been tested for Issue 1 & 2.
1. We are now able to see the error callout without scrolling
2. When the branch has a small name, the button width adjusts to the width of the text.

https://github.com/appsmithorg/appsmith/assets/39921438/ba15f66f-dbb7-4224-a0ab-f4c39e0cf46d

**Review by Parthvi12 — APPROVED** [review]

**Pull request merged**
