### PR TITLE
fix: Select component arrow, table component font issues

### LINKED ISSUE #26313: [Bug]: [Design System] UI issues after @appsmithorg/design-system@2.1.18
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Some of the UI layouts and font sizes are changed after 2.1.17. 

1. The arrow in the select component is different from release
Screenshot 2023-08-14 at 11 22 21 AM

2. There is a change in size of the tag component when compared with release/prod. Maybe because of introducing a border
Screenshot 2023-08-14 at 11 22 52 AM

3. There seems to be a horizontal shift in the layout for some pages e.g. Members page
4. Font size in Members page is different from prod.
5. Bottom divider under the member details is missing
Screenshot 2023-08-14 at 11 23 44 AM

### Steps To Reproduce

1. Goto https://ce-26293.dp.appsmith.com/applications
2. check the Ui shifts in above mentioned places

### Public Sample App

_No response_

### Environment

Deploy Preview

### Issue video log

_No response_

### Version

@appsmithorg/design-system-2.1.18

### PR DESCRIPTION
**Pull request by albinAppsmith**
## Description

1. The arrow in the select component fixed.
2. There seems to be a horizontal shift in the layout for some pages e.g. Members page
3. Font size in Members page is different from prod.
4. Bottom divider under the member details is missing.

#### PR fixes following issue(s)
Fixes #26313

#### Type of change

- Bug fix (non-breaking change which fixes an issue)

- [x] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [x] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [x] Test plan has been peer reviewed by project stakeholders and other QA members
- [x] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by KelvinOm — APPROVED** [review]

**Comment by shadabbuchh** [comment]
Tested in this PR:

1. Table component - Text size & divider - _Pass_
Screenshot 2023-08-17 at 2 59 30 PM

2. Select component - Arrow - _Pass_
Screenshot 2023-08-17 at 3 00 20 PM
Screenshot 2023-08-17 at 3 00 29 PM
Screenshot 2023-08-17 at 3 09 12 PM

**Comment by albinAppsmith** [comment]
Closing this PR since it was raised to test the functionality.

**Pull request closed without merging**
