### PR TITLE
fix: patches blueprint's popover

### LINKED ISSUE #6194: [Bug] Information text that's highlighted using **Tab** function does not exit when using a combination of mouse clicks and key presses
## Description
Information text that's displayed on hover or 'Tab' key does not exit after either clicking away or using Tab key once text is shown using the Tab key.

### Steps to reproduce the behaviour:
1. Drag and drop menu widget (can be replicated on any widget that contains information text on hover function)
2. Use **Tab** key to move control to any information text
3. Click away using the cursor - expected behaviour is for the information text exit from hover mode but it stays open

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: RC and Production

https://www.loom.com/share/6657abc0bd704c658510c354e649db42

### PR DESCRIPTION
**Pull request by aswathkk**
## Description

Patches Blueprintjs's popover based on https://github.com/palantir/blueprint/pull/5080

Fixes #6194

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manually

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>
No changes to code coverage between the base branch and the head branch</details>

### CODE REVIEW

**Review by riodeuno — APPROVED** [review]

**Comment by vivekverma2312** [comment]
@aswathkk Tested and it's working fine.

**Pull request merged**
