### PR TITLE
fix: Marker is not showing title tooltip when passed to marker

### LINKED ISSUE #21149: [Bug]: Marker is not showing title tooltip when passed to marker
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I am passing title in marker, marker is not showing the title as tooltip

### Steps To Reproduce

1. Drop map widget
2. Hover on the default maker, it does not show the title as a tooltip

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

1.9.9

### PR DESCRIPTION
**Pull request by jsartisan**
While migrating the map widget underlying library, we missed adding title in the set of options that we are passing to marker. This PR adds the title back

Fixes #21149 

## Type of change

- Bug fix

## How Has This Been Tested?
- Manual

### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [x] Test plan has been approved by relevant developers
- https://github.com/appsmithorg/TestSmith/issues/2205
- [x] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [x] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by dhruvikn — DISMISSED** [review]

**Comment by kamakshibhat-appsmith** [comment]
No DP has been generated, @jsartisan Can you re-trigger?

**Comment by kamakshibhat-appsmith** [comment]
Sending it to dev in progress till the time DP is generated @jsartisan

**Comment by jsartisan** [comment]
@kamakshibhat-appsmith here is the dp link - https://appsmith-of8hcakfv-get-appsmith.vercel.app/

**Comment by laveena-en** [comment]
Hey @jsartisan Publish API is failing for this DP. Internal server error is being thrown on trying to deploy. Can you please check?

image

**Comment by laveena-en** [comment]
@jsartisan The tooltip isn’t getting dismissed on moving the cursor away. Please do check https://www.loom.com/share/fe2a894c90c8448cb763b6d5f755e007

**Comment by jsartisan** [comment]
>The tooltip isn’t getting dismissed on moving the cursor away. Please do check
@laveena-en We can't really do anything about it as it's a browser tool that comes when we use title attribute on HTML component.

**Comment by laveena-en** [comment]
Tested and verified the PR for the fix. LGTM.

**Pull request merged**
