### PR TITLE
fix: Tab title text cut issue

### PR DESCRIPTION
**Pull request by priyanka-mahour**
## Description

Fixed this issue: https://github.com/appsmithorg/appsmith/issues/21606#issuecomment-1510693391

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

- Manual

### Dev activity
- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [x] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Comment by somangshu** [comment]
@priyanka-mahour please update you PR description properly!

**Comment by priyanka-mahour** [comment]
> @priyanka-mahour please update you PR description properly!

@somangshu updated PR description, let me know if I need to do anything else
I checked for adding labels, looks like I don't have access to add labels

**Review by jsartisan — APPROVED** [review]

**Comment by somangshu** [comment]
After checking the DP, looks like the bug is fixed

**Comment by somangshu** [comment]
cc @chandannkumar @dilippitchika please verify once

**Comment by chandannkumar** [comment]
Tested this PR and LGTM
- Tab title text cut issue is fixed
- Tested on all canvas size

**Comment by somangshu** [comment]
@prsidhu @marks0351 HugWidgetValidationSpec.js is failing here, Can you folks please check and give us a signoff, this is a UI change, hence I am concerned.

**Comment by marks0351** [comment]
@priyanka-mahour could you pull the latest release so that we can run the tests again on the branch.

**Comment by priyanka-mahour** [comment]
> @priyanka-mahour could you pull the latest release so that we can run the tests again on the branch.

I have merged the latest release into my branch @marks0351 
Please let me know if I need to do anything else

**Pull request merged**
