### PR TITLE
fix: show scroll bar in git connection modal.

### PR DESCRIPTION
**Pull request by marks0351**
Fixes: #19869

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Description

as of now scroll bar in git connect modal shows up only when the user performs a scroll operation which is not very obvious to discover. so making scroll bar visible on hover.

Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update

- Manual
- Jest
- Cypress

### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Comment by Parthvi12** [comment]
@marks0351  Server build is failing causing deploy preview also to fail , can you please check?

**Review by riodeuno — APPROVED** [review]

**Comment by riodeuno** [comment]
@marks0351 Please update the PR description.

**Comment by Sripriya93** [comment]
Scroll is seen when we hover, Working as expected. QA done. @marks0351

**Review by riodeuno — APPROVED** [review]

**Review by riodeuno — APPROVED** [review]

**Comment by AnaghHegde** [comment]
@marks0351 Why are showing the scroll bar in the generate key tab as well?
image

**Comment by riodeuno** [comment]
😓 @marks0351 @AnaghHegde @ginilpg We need to go back to the drawing board on this one, and look at all the scenarios. 

@ginilpg could you help with having a team member from the design team audit these? Someone who's working with the design system would be best, as they would have context on what is coming in from the design system.

**Comment by riodeuno** [comment]
This is a papercut issue which has been brought up frequently, if we can successfully merge a fix for this, preferably in this PR, it would really help with the product polish.

**Comment by ginilpg** [comment]
> generate key tab



> This is a papercut issue which has been brought up frequently, if we can successfully merge a fix for this, preferably in this PR, it would really help with the product polish.



> 😓 @marks0351 @AnaghHegde @ginilpg We need to go back to the drawing board on this one, and look at all the scenarios.
> 
> @ginilpg could you help with having a team member from the design team audit these? Someone who's working with the design system would be best, as they would have context on what is coming in from the design system.

@riodeuno Sorry I didn't get this. When there isn't enough content to scroll, we must avoid using the scroll bar. Do we really need a designer's opinion on this? Also in this case, I believe the modal is from the design system but not the scrollable content within it.

**Comment by riodeuno** [comment]
@ginilpg The issue we're trying to fix is to show scroll bar in the modal when there is more content below the scroll view of the modal. We tried to fix this but there seems to be different scenarios as @AnaghHegde demonstrated. To deal with this we need an audit from a team member from the design team. This way we can know what is the appropriate way to handle all scenarios.

I'm afraid that if there is no input from the design team, a patchwork could reduce the polish of the UI instead of increasing it. Fixing the papercut was the objective of this PR. Now that we see there are more scenarios than we considered we need design input.

**Pull request closed without merging**
