### PR TITLE
chore: Update api current env function

### LINKED ISSUE #25626: [Bug]: Test pass Environment toast message is shown on release even though environments are not seen
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I login to release using any email id other than an appsmith email id, create a new DS and test configuration, it gives the toast message related to environments - this should not happen ... this toast message is only specific to environments

### Steps To Reproduce

1. Signup and login to release with any email id other than appsmith email. 
2. Create a new DS and test configuration. [note that this user cannot see environments and changes related to that]
3. It gives the toast message related to environments.
4. This should come only for users who can see environments and access changes related to that

toast

### Public Sample App

_No response_

### Environment

Release

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by ChandanBalajiBP**
#### PR fixes following issue(s)
Fixes #25626 
>
#### Type of change
- Chore (housekeeping or task changes that don't impact user perception)
>
>
>
- [x] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by sneha122 — APPROVED** [review]

**Comment by btsgh** [comment]
The Error log and the Toast are both working correctly - no reference to Production or any environment is seen in the messages

**Pull request merged**
