### PR TITLE
chore: import common variables from design system

### PR DESCRIPTION
**Pull request by tanvibhakta**
## Description

Import variables that are commonly used both in the design system and in the core repository from the design-system in order to prevent duplication of code and maintain a single source of truth. 
Closes https://github.com/appsmithorg/appsmith/issues/17599

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Builds pass locally. Regression across app on DP. 

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by albinAppsmith — APPROVED** [review]

**Review by albinAppsmith — APPROVED** [review]

**Comment by shadabbuchh** [comment]
This PR has been tested. No issues found.

**Pull request merged**
