### PR TITLE
fix: JS toggle default value is wrong for vertical alignment table widget

### LINKED ISSUE #14953: [Bug]-[36]:In a table widget, JS toggle retains the CENTER text on vertical alignment property of column
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On clearing JS toggle of vertical alignment property of a column in a table widget, and clicking anywhere outside the text area, the CENTER text comes back up again.

### Steps To Reproduce

Drag and drop a table widget
Click on any column from property pane (say Task column)
Click on JS toggle for vertical alignment property
Observe that by default CENTER populates. 
Delete the CENTER text and click outside of the text area. 

The text CENTER gets auto-populated again.

### Public Sample App

_No response_

### Version

Release

### PR DESCRIPTION
**Pull request by souma-ghosh**
## Description

- Fixes wrong default value for Vertical Alignment in column settings of table widget
- Fixes issue where JS toggle for vertical alignment cannot be turned off after turning it on once

Fixes #14953

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manually tested

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by sbalaji1192 — DISMISSED** [review]

**Review by aswathkk — APPROVED** [review]

**Comment by laveena-en** [comment]
@souma-ghosh On changing the alignment and turning off the JS toggle, the respective option isn’t seen to be selected. Can you please check this? https://www.loom.com/share/74bc98b245ac46beaf4de094f24f0266

**Comment by souma-ghosh** [comment]
> @souma-ghosh On changing the alignment and turning off the JS toggle, the respective option isn’t seen to be selected. Can you please check this? https://www.loom.com/share/74bc98b245ac46beaf4de094f24f0266

@laveena-en We can create a separate issue for this. Confirmed with @aswathkk that this is a bug we need to fix. For this PR we can go ahead if:

- Default value is correct for vertical alignment
- Able to turn off JS toggle for Vertical Alignment after its turned on

**Comment by laveena-en** [comment]
Yes, will raise a separate issue for the same @souma-ghosh 
PR works as expected.

**Review by sbalaji1192 — APPROVED** [review]

**Review by aswathkk — DISMISSED** [review]

**Review by sbalaji1192 — APPROVED** [review]

**Review by sbalaji1192 — APPROVED** [review]

**Pull request merged**
