### PR TITLE
feat: Update order of action file operations

### LINKED ISSUE #22618: [Feature]: Reorganise the create action popup
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

More often than not, users are creating queries from the create action popup. However, there are 4 items above the first query type. Therefore this should be the new layout:
 
- By default show New API, New JS Object & New Datasource
- If a user connects a datasource show that on top

User in a new workspace sees:
-New API
-New JS
-New Datasource

Once a datasource is created, the user sees
- Connected User sees
- New <created datasource type> Query
- New API
- New JS
- New Datasource

Datasources should be listed in the order of most recently used/created/edited (same as the one in the datasource list in the entity explorer)

### Why should this be worked on?

In our user interviews, we noticed a sense of confusion for users. We feel like these changes would clear up a lot of that confusion, and reduce the number of options for users, making it easier and better for users to create their Queries, APIs and JSObjects

### PR DESCRIPTION
**Pull request by hetunandu**
## Description

In order to improve new user experience, we want to update the order of items listed in the new action list. This will show app datasources higher in the order and generic creation action lower in the order. Create JS objects is still listed on the top.
This also will update the list sorting on the omni bar.

Screenshot 2023-04-26 at 3 49 31 PM

Screenshot 2023-04-26 at 3 53 39 PM

> Improve the order of action create list

Fixes #22618

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Extracted the function and adding some jest cases for the functionality 

- Manual
- Jest
- Cypress

### Test Plan
TBA

### Issues raised during DP testing
https://github.com/appsmithorg/appsmith/pull/22754#issuecomment-1527503666

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [x] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [x] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by akash-codemonk — DISMISSED** [review]

**Comment by ramsaptami** [comment]
lgtm
cc: @hetunandu

**Pull request merged**
