### PR TITLE
Added test for table data sorting

### PR DESCRIPTION
**Pull request by NandanAnantharamu**
Added tests for 
Binding Input widget with table
Check table sorting functionality

### CODE REVIEW

**Comment by hetunandu** [comment]
This PR has been open for quite long @NandanAnantharamu. Can we close this for now if the fix is not being worked on?

**Comment by NandanAnantharamu** [comment]
> This PR has been open for quite long @NandanAnantharamu. Can we close this for now if the fix is not being worked on?

@hetunandu let me check if the issue is fixed now, if the issue is fixed I will merge.

**Comment by NandanAnantharamu** [comment]
@hetunandu this issue stil exists so we cant merge this .

**Comment by NandanAnantharamu** [comment]
@hetunandu as discussed commenting the test for the time being

**Pull request merged**
