### PR TITLE
fix: removed global style from design system dropdown component

### LINKED ISSUE #17452: [Bug]: Dropdown changes in design system affected performance of modal
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Recent changes in design system dropdown component affected the re-rendering time of modal widget. This is due to the use of createGlobalStyle functionality of styled component

### Steps To Reproduce

1. Goto performance dashboard
2. Check the PR details tab with [16718](https://github.com/appsmithorg/appsmith/pull/16718)
3. Notice the re-rendering time diff in MODAL_OPEN

### Public Sample App

_No response_

### Version

@appsmithorg/design-system-1.0.25

### PR DESCRIPTION
**Pull request by albinAppsmith**
## Description

Fixed rendering performance issue caused by design system dropdown.

Fixes #17452

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by shadabbuchh** [comment]
There appears to be a padding at the bottom of the widget (Currency & Phone Input) dropdowns.

**Review by tanvibhakta — DISMISSED** [review]

**Comment by shadabbuchh** [comment]
The padding issue on the `CurrencyInput` & `PhoneInput` widgets is resolved. However, additional issues have creeped in:

1. The grey padding appears on the following drop-downs:

- Homepage - User invite Modal
- Git sync Modal - Merge Tab
- Template Pages - Fork template 
- Members Page - Add Member Dropdown

2. There appears to be a strange padding for almost all the impact areas that hides the underlying components/objects when the dropdown is clicked upon.

**Review by tanvibhakta — DISMISSED** [review]

**Comment by shadabbuchh** [comment]
Bugs have been retested. Good to go.

**Review by tanvibhakta — APPROVED** [review]

**Pull request merged**
