### PR TITLE
fix: fixed back button to redirect to applications page

### PR DESCRIPTION
**Pull request by saicharan-zemoso**
added the changes to redirect to application pages instead of going back in the history.

issue: [#34431](https://github.com/appsmithorg/appsmith/issues/34431)

fixed the navigation to not go back in history
The navigation of the back button used to go back in history. Now it will be redirected to the expected page.

added the test for profile page:
image

added the tests for settings page:
image

video:

https://github.com/user-attachments/assets/35a805ec-a579-4571-b4c6-e415f0f5c5f3

## Automation

/ok-to-test tags="@tag.All"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/10659602683>
> Commit: 23f22850060df9eae1c2d033c529ea471eb596b7
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=10659602683&attempt=3" target="_blank">Cypress dashboard</a>.
> Tags: `@tag.All`
> Spec:
> <hr>Mon, 02 Sep 2024 04:52:56 UTC

## Summary by CodeRabbit

- **New Features**
	- Enhanced navigation for the BackButton in both UserProfile and Settings components, directing users to the applications page and specific workspace pages, respectively.

- **Bug Fixes**
	- Improved test coverage for BackButton interactions in both UserProfile and Settings components, ensuring correct navigation behavior is verified.

- **Tests**
	- Expanded test suite for UserProfile and Settings components, incorporating better routing and interaction simulations.

### CODE REVIEW

**Comment by ankitakinger** [comment]
@saicharan-zemoso Could you please check and fix the checks that are failing? You will be able to see the errors when you click "Details" for the specific check.

**Comment by saicharan-zemoso** [comment]
Ok I will check why they are failing

**Comment by ankitakinger** [comment]
@saicharan-zemoso There are still some failures in prettier and lint checks.

**Comment by ankitakinger** [comment]
@saicharan-zemoso It's actually not a dot but a single space. If you are using VSCode as your editor, you can install "ESLint" and "Prettier - Code formatter" extensions and that will take care of fixing these errors.
image
image

If you're using any other editor, I'm sure there would be a way to get this done automatically on save, you'll just have to search for the same.

**Review by ankitakinger — APPROVED** [review]
LGTM

**Pull request merged**
