### PR TITLE
perf: Optimising DSL fetch api

### LINKED ISSUE #23637: [Task]: DSL call slower than other API calls.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

In load testing it was found that the DSL call is slower than other API calls, when it just have to get a single record from the DB.

Identify the reason for the slowness and fix it.

### PR DESCRIPTION
**Pull request by NilanshBansal**
#### PR fixes following issue(s)
Fixes #23637 

- Chore (housekeeping or task changes that don't impact user perception)

#### How Has This Been Tested?

- [x] Manual
- [x] Jest
- [ ] Cypress

#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Comment by SatishGandham** [comment]
@NilanshBansal , Please share some numbers on performance improvement.

**Review by nayan-rafiq — APPROVED** [review]
LGTM

**Comment by NilanshBansal** [comment]
@SatishGandham here are the numbers from my local testing, it's clearly showing a big difference in old vs new.
https://www.notion.so/appsmith/Performance-Testing-DSL-API-aee3772d6e0d41368e1965673d7ccc90?pvs=4

I will still merge this PR and later share the results from the server on the release branch.
cc: @somangshu

**Pull request merged**
