### PR TITLE
ci: added to pull workflow 

### PR DESCRIPTION
**Pull request by yatinappsmith**
## Description

added to pull workflow
Fixes # (issue)

## Type of change
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

code review
## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by Rhitottam** [comment]
/perf-test ref=rhito/feat/compare-with-lt-standard-deviation-for-regression

**Comment by Rhitottam** [comment]
/perf-test ref=rhito/feat/compare-with-lt-standard-deviation-for-regression

**Review by NandanAnantharamu — APPROVED** [review]
LGTM

**Comment by Rhitottam** [comment]
/perf-test ref=rhito/feat/compare-with-lt-standard-deviation-for-regression

**Pull request merged**
