### PR TITLE
test: Cypress CI run Group name update

### PR DESCRIPTION
**Pull request by Aishwarya-U-R**
## Description

- This PR includes the script updates for connecting to TED Git instead of actual Github for running tests

## Type of change

- New script changes to connect to TED Git

## How Has This Been Tested?
- Cypress CI runs

### QA activity:
- [X] Test plan has been approved by relevant developers
- [X] Test plan has been peer reviewed by QA
- [X] Cypress test cases have been added and approved by either SDET or manual QA
- [X] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [X] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Comment by Yoyobentmomo** [comment]
///activity &action,!!has&been.stop$**%¥¥¥¥¥<last><chance>{{{{wastoday}}}€#8(allof/you)#####%onebyone[[]][[{{iwill}}fu&100%€€ck??@wait-call^^^^me~~~before❤️!!you<<<carry~~~£€€€big:-)case-£***###~~ok<<8bit>>>ch&1cow###+newyear:(***happy~~~~~~~💕💕💕💕💕

**Review by sharat87 — APPROVED** [review]

**Pull request merged**
