### PR TITLE
fix: [Bug]: Inconsistency in the field title of the property pane #8439

### LINKED ISSUE #8439: [Bug]-[97]:Inconsistency in the field title of the property pane
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

For few of the Widgets the text title is displayed as **colour** in some places and **color** in some places.

Current status:

1.Container widget - Background **colour**, Border **colour**  and Shadow **color**
2.Audio Recorder - Icon **color** , Background **color**
3.Button Widget - Button **color**, Shadow **color**
4.Divider Widget - Divider **color**
5.Form Widget - Background **colour**, Border **colour**  and Shadow **color**
6.Icon Widget - Button **color**, Shadow **color**
7.Iframe Widget - Border **color**
8.List Widget - Background , Item Background - **text colour is not displayed** 
9.Menu Widget - Icon **color**, Text **color**, Background **color** , Menu **color**, Shadow **color**
10.MultiTeeSelect - Label text **color**
12.Rate Widget - Active **color**, Inactive **color**
13.Stat Box Widget - Background **color**
14.Table Widget - Cell Background -**text colour is not displayed for Cell Background**  , Text **color**
15.Text Widget -  Cell Background -**text colour is not displayed for Cell Background** , Text **color** , Border **Colour**
16.TreeSelect - Label text **color**

### Steps To Reproduce

```markdown
1.Launch appsmith app in release or Prod environment 
2.Drag and drop most of the widgets , open property pane and check the field title of colour
```

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by AR10X**
## Description

I have made the following changes:
Changing colour to color for following widget, rest of the widget already having color hasn't been changed.

1.Container widget - Background colour, Border colour and Shadow color ✔️

5.Form Widget - Background colour, Border colour and Shadow color ❗
(couldn't find any files in form widget having the above properties)

8.List Widget - Background , Item Background - text colour is not displayed ✔️

14.Table Widget - Cell Background -text colour is not displayed for Cell Background , Text color ❗
(couldn't find any files in table widget having the above properties)

15.Text Widget - Cell Background -text colour is not displayed for Cell Background , Text color , Border Colour ✔️

Fixes #8439

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by AR10X** [comment]
Pls review the PR 😄

**Comment by jsartisan** [comment]
@somangshu this PR Looks good to me. can we merge this in?

**Comment by somangshu** [comment]
https://github.com/appsmithorg/appsmith/actions/runs/1415531984

**Review by somangshu — APPROVED** [review]

**Comment by somangshu** [comment]
@jsartisan since none of the actions ran, I did that, Shall merge this in a while

**Comment by somangshu** [comment]
@jsartisan we need to test this out, Sending to the QA pipeline

@jsartisan @AR10X I see some tests failing which on a glance look like they are related to the changes made here, Its not wise to close this PR directly. Kindly rectify

**Comment by YogeshJayaseelan** [comment]
@AR10X @jsartisan Verified this PR and looks good

**Comment by somangshu** [comment]
@NandanAnantharamu @yatinappsmith could you help is get the cypress tests fixed here?

**Review by jsartisan — APPROVED** [review]

**Comment by somangshu** [comment]
@keyurparalkar could you take the responsibility of merging this PR, i think we have the QA signoff and the review here

**Comment by keyurparalkar** [comment]
@somangshu This PR's changes are merged to the release branch via PR: #10181 
Therefore, closing this PR.

**Pull request closed without merging**
