### PR TITLE
fix: multiselect crashing

### LINKED ISSUE #18578: [Bug]: MultiSelect Widget crash
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When option is undefined or when a query for options fail

### Steps To Reproduce

Make a Query for options and let it fail.
No DefaultValue and MultiSelect seem to crash

https://app.intercom.com/a/inbox/y10e7138/inbox/shared/all/conversation/164629100185652?view=List

Link to app on release
https://release.app.appsmith.com/app/arce-bost-mobile-agents/mym-050wa-638726e06f683550e8f14add/edit

QA: Do let me know if you'll need access to the app

### Public Sample App

_No response_

### Issue video log

_No response_

### Version

cloud

### PR DESCRIPTION
**Pull request by Tooluloope**
## Description

HotFix for multiselect crashing
Handle undefined state of selectedOptionValues

Fixes #18578

## Type of change
- Bug fix (non-breaking change which fixes an issue)

- Manual
- Jest
- Cypress

### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by keyurparalkar — CHANGES_REQUESTED** [review]
Can we add a test case for this scenario where selectedOptionLabels or selectedOptionValue are undefined?

**Comment by Tooluloope** [comment]
> Can we add a test case for this scenario where selectedOptionLabels or selectedOptionValue are undefined?

@keyurparalkar, most of the tests for MultiSelect have selectedOptionLabels and selectedOptionValues as undefined.

You can check the `multiSelectDsl.json`. They are not part of the Multiselect dsl

@Rishabh-Rathod is currently investigating the root cause.

**Review by keyurparalkar — APPROVED** [review]

**Comment by laveena-en** [comment]
Tested and verified the DP for:
- when the query associated with the multi-select widget fails
- regression on the multi-select widget
- all functionalities across edit and deployed state

**Comment by Rishabh-Rathod** [comment]
Notes for future RCA: 
It was noticed that the multi-select widget's, `selectedOption` was evaluated as an empty string instead of an empty array for the user's application. 

This was not reproducible on production env when we tried to create a similar application.

**Pull request merged**
