### PR TITLE
fix: Update widget isLoading property when API/Query is executed

### LINKED ISSUE #26935: [Bug]: `isLoading` received in the widget props should be true until all the bindings have been evaluated
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

A widget should receive isLoading true until all the query bindings have been evaluated. At the moment, isLoading gets set to false even when the queries haven't loaded yet.

This is needed because widgets starts receiving evaluation errors for null data while the query bindings are getting evaluated. This hampers the user experience because a widget may choose to display evaluation errors in its UI. This UI causes a flicker during the widget load and reduces the user experience.

### Steps To Reproduce

1. Dnd a chart widget
2. For chart series data, use a query binding
3. Deploy the app
4. Notice that the users see an error in the chart widget for half a seconds that describes that there was an error in evaluating chart series data because of undefined query binding data.

Expected behavior: The widget should receive isLoading to true until the query bindings have evaluated so that the widgets knows how to distinguish between actual user errors and appsmith processing states.

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by ohansFavour**
## Description

This PR ensures that there is a sync between the isLoading property of API/Queries and that of dependent entities.

#### PR fixes following issue(s)
Fixes #26935

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
- [ ] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Test Plan
1. Verified table,list select treeselect chart loading 
2. Did sanity on binding above widget with API/Query/Lable
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Comment by arunvjn** [comment]
@ohansFavour Can we close this PR ?

**Comment by ohansFavour** [comment]
This has been handled in https://github.com/appsmithorg/appsmith/pull/27406

**Pull request closed without merging**
