### PR TITLE
fix: remove appsmith from widget entity dropdown

### LINKED ISSUE #15120: [Bug]: Connection on the property pane shows "Appsmith" as incoming connection
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On placing the widget and property pane displays incoming connection as "appsmith" 

### Steps To Reproduce

1) Add a widget 
2) ensure property pane opens 
3) observe the incoming entity 
observer 1 incoming connections name "Appsmith" is disaplyed 

### Public Sample App

release

### Version

cloud

### PR DESCRIPTION
**Pull request by yaldram**
## Description
- Remove `appsmith` as an entity (incoming / outgoing entity) from the entity dropdown, widget property pane.

Fixes #15120

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Tested Manually on the canvas.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by akash-codemonk — APPROVED** [review]

**Comment by Sripriya93** [comment]
Have checked all the widgets, in a new workspace, dragging and dropping each of them, it shows "No entity". Working fine moving to done.

**Pull request merged**
