### PR TITLE
perf: Anvil widget name component rendering

### LINKED ISSUE #33330: [Bug]: Performance degradation post widget selection changes
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

DnD experience has degraded a bit after widget selection changes
- app performance becomes significantly worse with slight complexity (~60 widgets including 2 tables and modal, tables are connected to dummy data that does not fetch >30 records)
- modal is slow
- moving apps using scroll is glitchy

related issue: zone space redistribution does a glitchy adjustment when an adjacent zone is deleted

### Steps To Reproduce

https://www.loom.com/share/db67c4212c6d4a08993c28fc61fe0fa4?sid=f122697e-612f-4865-b58b-6c114ac97e33
https://www.loom.com/share/34d0d056b44f41979f5536f1ef2363a3?sid=9e762e98-cfe7-4824-96ef-2462abe6c5ce

### Public Sample App

_No response_

### Environment

Deploy Preview

### Severity

High (Blocker to building or releasing)

### Version

cloud

### LINKED ISSUE #33386: [Bug]: Incorrect transient widget name state
while scrolling widget name shows different states like selected state even if it is not selected. 
https://www.loom.com/share/44efa67b6c664f5a9584c1638b7af149?sid=8b635fd0-c63a-413d-8eb0-29935f183a66

- [ ] selected and hover states of a widget are easily visible while scrolling through the canvas
https://www.loom.com/share/44efa67b6c664f5a9584c1638b7af149?sid=e59d2e7a-338a-4c40-90c6-0be5975de6e9

### PR DESCRIPTION
**Pull request by riodeuno**
## Description
- Fixes some of the performance issues in the widget name component for Anvil. Particularly, the following
   - All widget name components for all widgets used to be added to the DOM tree, even if they're not visible
   - All widget name components had the floating-ui listeners added to them at all times, leading to a sharp rise in the number of JS listeners and increasing RAM usage.
   - Widget name component positions used to recompute sporadically, leading to perceived jitter when users scrolled too quickly.

The above issues have been fixed by the following changes
- Widget name component gets added to the DOM only when `nameComponentState !== "none"`
- Widget name component only has listeners added by floating-ui when the name component needs to be visible
- Floating-ui is configured to recompute in all `requestAnimationFrame` cycles

Fixes #33386
Fixes #33330 

## Automation

/ok-to-test tags="@tag.All"

### :mag: Cypress test results

> [!CAUTION]
> 🔴 🔴 🔴 Some tests have failed.
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9205700153>
> Commit: db2487d78aa705d4588ca8242de61a2a9fdfbcc5
> Cypress dashboard: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9205700153&attempt=1&selectiontype=test&testsstatus=failed&specsstatus=fail" target="_blank"> Click here!</a>
> The following are new failures, please fix them before merging the PR: <ol>
> <li>cypress/e2e/Regression/ClientSide/BugTests/GitBugs_Spec.ts </ol>
> To know the list of identified flaky tests - <a href="https://internal.appsmith.com/app/cypress-dashboard/identified-flaky-tests-65890b3c81d7400d08fa9ee3?branch=master" target="_blank">Refer here</a>

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [x] No

### CODE REVIEW

**Review by KelvinOm — COMMENTED** [review]
LGTM. Just one question. Why are we changing the id? 

https://github.com/appsmithorg/appsmith/assets/11555074/cb7bb7c2-5a08-4741-9c79-7c727fe31cb4

**Comment by riodeuno** [comment]
@KelvinOm Nice observation. Not sure what is happening. Floating-ui is creating these and I believe this is because `floating-ui` is getting different references so, creating different DOM nodes.

**Review by KelvinOm — APPROVED** [review]

**Review by marks0351 — APPROVED** [review]

**Pull request merged**
