### PR TITLE
fix: callouts changed from warning to info for db datasources

### LINKED ISSUE #26737: [Bug]: Change the warning callouts to info callouts for datasources
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

image

### Steps To Reproduce

1. Go to creation page for psql datasource
2. Observe the callout

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

Both

### PR DESCRIPTION
**Pull request by AmanAgarwal041**
## Description
Changed callouts type from `warning` to `info` for the message asking user to whitelist couple of IPs on their datasource instance.
Earlier :
image

Now :
Screenshot 2023-08-29 at 7 02 23 PM

#### PR fixes following issue(s)
Fixes #26737

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
- [ ] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by vinay-appsmith — APPROVED** [review]
The change to info variant of the callout component is proper.

**Comment by AmanAgarwal041** [comment]
Adding skip test plan label as the changes are approved by design team and there is nothing to be tested as such as it is a small visual change.

**Pull request merged**
