### PR TITLE
fix: The page order doesn't work as expected in page setting page

### LINKED ISSUE #9991: [Bug]-[48000]:The other page name changes by default when users change any one page name
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The other  page name changes by default when users change any one-page name 
[LOOM DEMO](https://www.loom.com/share/af3e4e7d840e498385bac2ba8459e3d4)

### Steps To Reproduce

1. Go to page properties tab
2. Add 10 pages
3. Drag and drop the 10th page to the 3rd place
4. Now change the name of the 3rd page 
5. The name of the 4th page changes automatically

### Environment

Release

### Version

Cloud

### LINKED ISSUE #12758: [Bug]-[2640]:Renaming page after reorder is not proper on page setting page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

[LOOM DEMO](https://www.loom.com/share/ccbb6c4bc3f241ceb3c9f51fa28b8dae)

### Steps To Reproduce

1. Navigate to Page setting page
2. Add few new pages
3. Rename one of the page
4. Reorder that page
5. Now try to reorder another page
6. Observe that previous page is getting renamed.

### Public Sample App

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by rahulramesha**
## Description

This bug is caused because of using  index as react keys while generating similiar siblings.

Fixes #12758
Fixes #9991 

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- 
## How Has This Been Tested?
Manual UI testing

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: PageReorderFix 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 56.59 **(0)** | 38.39 **(-0.01)** | 35.84 **(0)** | 56.83 **(-0.01)**
 :red_circle: | app/client/src/components/ads/DraggableList.tsx | 35.87 **(0)** | 15.71 **(-0.47)** | 26.67 **(0)** | 38.75 **(0)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.71 **(-0.23)** | 40.83 **(-0.84)** | 36.21 **(0)** | 56.74 **(-0.25)**</details>

### CODE REVIEW

**Comment by jsartisan** [comment]
@rahulramesha Can you check if this is working fine in the widgets property pane where we use draggable list.

**Comment by rahulramesha** [comment]
@jsartisan, yes those seemed to be working fine. Wanted to change those as well, but did not find a reliable ID that I can use as key. When I change the key to `item[i].id` table's column draggable list was not working as expected so I just let them be for now.

**Review by jsartisan — APPROVED** [review]

**Review by jsartisan — APPROVED** [review]

**Pull request merged**
