### PR TITLE
fix: DisplayText in table url column should be processed properly for…

### LINKED ISSUE #13299: [Bug]: Table widget: Column type URL: Display text not working appropriately
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The table widget column type URL display text is buggy, if the value is none, it throws a unknown character in the table column

Screenshot 2022-04-26 at 10 39 36 AM

### Steps To Reproduce

1. Use table widget column type URL
2. set display text on a condition to throw null values sometime
3. Observe for null text, the table add an additional unknown character. 

### Public Sample App

https://release.app.appsmith.com/app/untitled-application-2/page1-6180db4c730a92228e7a3341

### Version

Cloud

### PR DESCRIPTION
**Pull request by sbalaji1192**
… empty values

## Description
When DisplayText is empty for a given cell, we should properly process the given value

Fixes #13299

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/display-text-url-column-type-table 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 56.47 **(0.01)** | 37.95 **(0.06)** | 36.13 **(0.01)** | 56.7 **(0.02)**
 :red_circle: | app/client/src/utils/WorkerUtil.ts | 88.98 **(-0.78)** | 70.59 **(0)** | 100 **(0)** | 92.38 **(-0.95)**
 :green_circle: | app/client/src/widgets/TableWidget/widget/getTableColumns.tsx | 68 **(37.57)** | 66.67 **(66.67)** | 33.33 **(33.33)** | 63.64 **(43.64)**</details>

### CODE REVIEW

**Review by Tooluloope — APPROVED** [review]

**Comment by chandannkumar** [comment]
Tested this PR and working as expected for empty values in Table widget's URL column

**Pull request merged**
