### PR TITLE
chore: Extend the list of widgets that cannot be used inside the List…

### PR DESCRIPTION
**Pull request by sbalaji1192**
… widget

## Description

Only widgets that don't have derived or meta properties work well inside the current version of the List widget. Widgets like Input, Select maintain the state on meta properties which won't be available in List.selectedItem object. Hence we're restricting them from being placed inside the List widget.

Related #10683 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: task/list-widget-allowed-children 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 54.99 **(0)** | 36.31 **(-0.01)** | 34.68 **(0)** | 55.37 **(0)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.71 **(-0.23)** | 40.83 **(-0.84)** | 36.21 **(0)** | 56.74 **(-0.25)**</details>

### CODE REVIEW

**Review by jsartisan — APPROVED** [review]

**Review by riodeuno — APPROVED** [review]
Looks good to me!
@YogeshJayaseelan Needs a regression test for existing widget which is now disallowed. Can we play around with that state, moving the widget outside and then inside the List Widget, and check the experience.

**Comment by YogeshJayaseelan** [comment]
@sbalaji1192 Tested this PR and now the below widgets are allowed inside list widget 

"AUDIO_WIDGET",
"BUTTON_GROUP_WIDGET",
"BUTTON_WIDGET",
"CHART_WIDGET",
"CHECKBOX_WIDGET",
"CHECKBOX_GROUP_WIDGET",
"CIRCULAR_PROGRESS_WIDGET",
"DIVIDER_WIDGET",
"ICON_BUTTON_WIDGET",
"IFRAME_WIDGET",
"IMAGE_WIDGET",
"INPUT_WIDGET_V2",
"MAP_CHART_WIDGET",
"MAP_WIDGET",
"MENU_BUTTON_WIDGET",
"PROGRESSBAR_WIDGET",
"STATBOX_WIDGET",
"SWITCH_WIDGET",
"SWITCH_GROUP_WIDGET",
"TEXT_WIDGET",
"VIDEO_WIDGET",

Also, when trying to place non allowed widgets - Valid toast message appears and the list widget doesn't break

**Comment by sbalaji1192** [comment]
@YogeshJayaseelan The above callout is not related to the list widget. It's a know issue and being tracked here - https://github.com/appsmithorg/appsmith/issues/10659

**Comment by YogeshJayaseelan** [comment]
@sbalaji1192 Apart from the list widget inside another list widget issue rest of everything works fine

**Pull request merged**
