### PR TITLE
fix: prevents console log from getting mutated

### LINKED ISSUE #17746: [Bug]: Console logs get mutated when the logged object is changed later in the function
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Logs get updated when the data passed to it is mutated later on in the code.
https://app.frontapp.com/open/cnv_s1ue8y4

### Steps To Reproduce

1. Setup a JS Object with the function `() => { var a = [] console.log('aStart', a) for (var i = 0; i < 3; i++) { a.push(i) } console.log('aEnd', a) return a }`;
2. Run the function and observe the logs.

Current behaviour:
aStart [1, 2, 3]
aEnd [1, 2, 3]

Expected behaviour:
aStart []
aEnd [1, 2, 3]

### Public Sample App

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by arunvjn**
## Description
All logs are stored in an array and processed at once. If a data is logged twice in a function while being manipulated in the steps between them, then logs get updated as well. This PR clones the object that should be logged to prevent mutation to it.

Fixes #17746

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manual
- Cypress

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by Rhitottam** [comment]
/perf-test ref=rhito/feat-create-run-meta-before-test-starts-compare-lt-st-for-prev-runs

**Comment by Rhitottam** [comment]
/perf-test ref=rhito/feat-create-run-meta-before-test-starts-compare-lt-st-for-prev-runs

**Review by ayushpahwa — APPROVED** [review]

**Review by ayushpahwa — APPROVED** [review]

**Pull request merged**
