### PR TITLE
feat: Add Jest Test for propertyPaneConfiguration validation

### LINKED ISSUE #7678: [Task] Add Jest tests to validate property config
Jest tests are needed for validating widget's property config

Today, we have a runtime logic for validating a small part of the property validation configurations which is done in the WidgetFactory during the `registerWidgets` phase.

A similar logic can be applied in a Jest test which will statically (by importing the configurations of each widget) test to confirm if the validations are correct.

We need to write a function which checks for certain structures in the validation configuration. This function should return true or false based on the validity of the validation structure.

Jest test can expect the results of this function to be true or false based on the input.

### PR DESCRIPTION
**Pull request by aswathkk**
## Description

Adds Jest test to validate propertyPaneConfiguration with certain conditions.

Fixes #7678 

The Following widget configs are changed:

- DividerWidget
    - Divider Color
    - Cap
- ProgressBarWidget
    - Fill Color
- ButtonGroupWidget
    - Buttons > Button Type
- FormButtonWIdget
    - Disable Invalid Forms
- TableWidget
    - Columns
        - Visible
        - Button
            - Disabled
            - Button Color
            - Label Color
        - Icon Button
            - Border Radius
            - Box Shadow
            - Shadow Color
        - MenuButton
            - Compact
            - Menu Color
        - Date
            - Original date format
            - Display Date Format
            - Text Align
            - Text Size
            - Font Style
            - Vertical alignment
            - Text Color
            - Cell Background

## Type of change

- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested?

Manually tested

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## TODO
- [x] Work on `validateValidationStructure`
- [x] Confirm and fix all the issues spotted by this test

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: feat/jest-test-for-propertypane 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 55.07 **(-0.03)** | 36.59 **(0)** | 34.54 **(0)** | 55.57 **(-0.04)**</details>

### CODE REVIEW

**Review by hetunandu — DISMISSED** [review]

**Review by riodeuno — APPROVED** [review]

**Review by riodeuno — APPROVED** [review]
LGTM! Please make sure that we haven't missed any existing widgets in the latest release, not sure if these will show up as merge conflicts.

**Comment by riodeuno** [comment]
@aswathkk The new tests seem to be failing. https://github.com/appsmithorg/appsmith/issues/2410

**Comment by aswathkk** [comment]
@riodeuno I reverted the fixed validations because I'm waiting for ValidationTypes.TABLE_PROPERTY to be available in release. That's why tests are failing now.
I will fix validation for the failing cases and update the PR. As you told, new widget will show up as a merge conflict.

**Comment by somangshu** [comment]
@aswathkk what is happening here, Are we stuck on any decisions, Can we take a call on this soon

**Comment by aswathkk** [comment]
@somangshu I was waiting for some other dependent PRs to get merged. I will prioritise them and will merge this soon.

**Comment by riodeuno** [comment]
@aswathkk @vivekverma2312 As this effects the widgets' property pane configurations, we need a regression test here. Especially, a check to make sure that existing applications won't change any values. If we start showing validation errors, that is fine, however, it shouldn't result in different values for properties, otherwise, we'll see the view mode for such applications work differently.

**Comment by shwetha-ramesh** [comment]
@aswathkk tested this PR on DP. Looks good on both old and new apps.

**Pull request merged**
