### PR TITLE
feat: improve signposting discoverability

### PR DESCRIPTION
**Pull request by akash-codemonk**
## Description
Update to signposting flow with visual indicators. This will behind feature flag. The feature makes use of the walkthrough component. 

#### PR fixes following issue(s)
Fixes https://github.com/appsmithorg/appsmith/issues/26003

#### Media

https://github.com/appsmithorg/appsmith/assets/67054171/7007e4fa-95e2-4199-b042-ea7a71632993

#### Type of change
- New feature (non-breaking change which adds functionality)

#### How Has This Been Tested?

- [x] Manual
- [ ] Jest
- [x] Cypress

#### Test Plan
https://github.com/appsmithorg/TestSmith/issues/2501
>
>
#### Issues raised during DP testing
https://github.com/appsmithorg/appsmith/pull/26551#issuecomment-1689542043

>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [x] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [x] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Comment by kavitasmoolya** [comment]
@akash-codemonk 

- [ ] Issue 1 : Close link on GIF does not highlight on hovering on it
image

- [ ] Issue 2 : GIF pop up does not disappear on accessing omnibar using keyboard short cut key
Steps : 1. Add a data source > add a query > drag and drop a table widget > Using keyboard key (ctrl+k) open omnibar > Click navigate on omnibar and navigate to query page

**Comment by akash-codemonk** [comment]
> * [ ]  Issue 1 : Close link on GIF does not highlight on hovering on it
> * [ ]  Issue 5 : GIF pop up title is not in bold, looks like normal text.

We will need to update it at the component level for all. No fix for now.

> * [ ]  Issue 2 a. : GIF pop up does not disappear on accessing omnibar using keyboard short cut key
>   Steps : 1. Add a data source > add a query > drag and drop a table widget > Using keyboard key (ctrl+k) open omnibar > 

Fixed. Omnibar shortcut is disabled.

 Most app shortcuts are disabled when walkthrough is going on. Not all keyboard shortcuts are disabled. Not a blocker for now.

> * [ ]  Issue 3 : Gif pop up gets located misaligned on the canvas and visible partially

Fixed. The popup was for the table widget card in the widget pane, which was showing up even when the widget pane was not selected.

> * [ ]  Issue 4 : Step-5 Hyphen is overlapping with documentation icon

Unable to repro. No changes made for popup design. 

> * [ ]  Issue 6 : `Go back to the canvas` gif pop up does not show up after user adds a query successfully or sometimes takes time to show up and `switch to widget section` pop up shows up first.

Not an issue. This is expected. Not required to show up in order

> * [ ]  Issue 7 :  `Go back to canvas` pop up shows up on Data source page as well if user being on query page click (ctrl+k) and navigate to data source page.

Fixed. Omnibar won't open now when walkthrough is enabled

> * [ ]  Issue 8 : No GIF clip available for deploy step only the content (title & short summary) shows up.

Expected

> * [ ]  Issue 9 : GIF pop up displays on Preview mode when user switches from edit mode to preview mode using keyboard shortcut key (p) and basically check with other short cut keys as well

Fixed. Preview mode shortcut is disabled now when walkthrough is enabled

> * [ ]  Issue 10 : GIF pop up/modal keeps on displaying when user navigates from current step to previous step using browser back button.
> * [ ]  Issue 11 : Minimize the window to smaller screen and observe (shift+down arrow key) will scroll the canvas but not the gif pop up modal. Should we include scroll bar to the gif modal for smaller screen

No fix for now. This exists for all existing popups on prod as well. Not a blocker. Will fix it later if it causing issues.

> * [ ]  Issue 12 :`connect data`modal is also partially visible if widget is dropped at the end of the screen and on scrolling the canvas misalignment occurs in pop up and blinking orange icon
>   steps : Complete step 1 and 2 then drag the widget and drop it at the bottom of the screen in such a way that table widget must display partial and then observe connect data modal is also partially visible at the end of the screen and now scroll the canvas and observe the misalignment

No fix for now. Similar to above not a blocker for now. Unlikely case, will be fixed later if it causes any issues.

**Review by hetunandu — APPROVED** [review]

**Review by AmanAgarwal041 — APPROVED** [review]

**Pull request merged**
