### PR TITLE
feat: deduplicate toast

### PR DESCRIPTION
**Pull request by tanvibhakta**
## Description

Visual Changes for toast - we're no longer living in dark mode land on toast. 
Some API changes - developers will now have to pass in a button on the toast differently.

Change of behavior in one instance of toast being triggered - when a toast is triggered after the the first time deleting a widget, there is no button label, just the text in the toast. This is because on production right now, clicking on the label does nothing.

Video of incorrect behavior: 
https://user-images.githubusercontent.com/13763558/222145003-99c4ee05-67c3-4c87-ad94-b04c30189394.mov

Fixes # (issue)

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- the component has been tested on storybook
- dev has done a sanity test
- Jest
- Cypress
- Manual

### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by albinAppsmith — APPROVED** [review]

**Review by albinAppsmith — APPROVED** [review]

**Comment by tanvibhakta** [comment]
This branch has been merged into https://github.com/appsmithorg/appsmith/pull/22030

**Pull request closed without merging**
