### PR TITLE
fix: List widget highlights not visible

### LINKED ISSUE #23815: [Bug][List]Unable to place widgets and see drop targets when widget is dragged to a blank area (increase the height of list item and try dragging and releasing widget in the blank space )in List item container
[www.loom.com/share/0c41037da9ab4a1885bae9f3bb8adefd](http://www.loom.com/share/0c41037da9ab4a1885bae9f3bb8adefd)

### PR DESCRIPTION
**Pull request by aswathkk**
## Description
For List widget in auto-layout mode, the highlights were not getting properly shown since the height of the DropTarget is not fitting within the list item container. Height of dropTarget in the case of List Widget set to "100%" while dragging resolved this issue.

#### PR fixes following issue(s)
Fixes #23815

#### Media
before:

https://github.com/appsmithorg/appsmith/assets/10436935/680fc9ec-2314-4743-a9a9-774f5e5d7b4f

after:

https://github.com/appsmithorg/appsmith/assets/10436935/553b2a2b-715c-460d-a3c8-e0d16b27ba12

#### Type of change
- Bug fix (non-breaking change which fixes an issue)
>
>
>
#### How Has This Been Tested?
- [x] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by rahulramesha — APPROVED** [review]

**Comment by Sripriya93** [comment]
We are still able to observe the issue when the container inside the List widget gets bigger. Moving back to In progress. 
@rahulramesha @rohitagarwal88 

https://github.com/appsmithorg/appsmith/assets/104895602/c78b9072-5e48-4500-93f8-7a8f788381ec

**Comment by rahulramesha** [comment]
@Sripriya93 This seems to be a unrelated issue and seems to be happening on all container type widgets in release as well. Please raise a separate issue for the same and verify around the bug on this PR.

**Comment by rahulramesha** [comment]
@Sripriya93 , could you please provide an update on the above comment

**Comment by Sripriya93** [comment]
As per discussion, we can close this issue. @rahulramesha . Apologies for the delay.

**Pull request merged**
