### PR TITLE
fix: undefined selected theme

### LINKED ISSUE #16412: TypeError: Cannot read properties of undefined (reading 'properties')
Sentry Issue: [APPSMITH-36T](https://sentry.io/organizations/appsmith/issues/3429226262/?referrer=github_integration)

```
TypeError: Cannot read properties of undefined (reading 'properties')
  at c (pages/Editor/WidgetsEditor/CanvasContainer.tsx:70:50)
  at next (RouteParamsMiddleware.ts:125:10)
...
(45 additional frame(s) were not displayed)
```

Discord user query: https://discord.com/channels/725602949748752515/1013630823410434070/1013950513018048644

### PR DESCRIPTION
**Pull request by keyurparalkar**
## Description

This PR adds front-end validation for the scenario where the `selectedTheme` that is fetch from backend is undefined. We default it to "Modern" system theme. 

Here is the scenario:
1. Whenever the `selectedTheme` is undefined, we fetch all the system themes using the API endpoint: `/themes/applications/${applicationId}`
2. Next, we update the selected theme at the backend using the API endpoint: `/applications/${applicationId}/themes/${theme.id}` and update the `selectedTheme` in the redux store.

Fixes #16412

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Tested this manually.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by jsartisan — APPROVED** [review]

**Review by jsartisan — DISMISSED** [review]

**Review by jsartisan — APPROVED** [review]

**Comment by keyurparalkar** [comment]
@laveena-en @chandannkumar I have added the toast message as per the QA callout. PFB screenshot:

Screenshot 2022-09-22 at 11 15 35 AM

**Comment by laveena-en** [comment]
@keyurparalkar As discussed, here are our findings:

1. In a git connected app - the themes that are updated and deployed once the current theme was deleted, are all reverting back to the default theme.
https://www.loom.com/share/7a3ad8f0aca443bb80e9baa76a7f20e4
3. Can we also change the toast to be a warning type instead of a success message?
cc: @chandannkumar

**Comment by keyurparalkar** [comment]
> @keyurparalkar As discussed, here are our findings:
> 
> 1. In a git connected app - the themes that are updated and deployed once the current theme was deleted, are all reverting back to the default theme.
>    https://www.loom.com/share/7a3ad8f0aca443bb80e9baa76a7f20e4
> 2. Can we also change the toast to be a warning type instead of a success message?
>    cc: @chandannkumar

@laveena-en for the issue 1: We will be creating a separate issue for this. This is happening due to `selectedTheme` API returns undefined response.

For issue 2: As per the callout changed the toast to a warning type.
Screenshot 2022-09-26 at 1 04 39 PM

**Comment by keyurparalkar** [comment]
@laveena-en Here is the [github issue](https://github.com/appsmithorg/appsmith/issues/17048) for the first callout

**Review by jsartisan — APPROVED** [review]

**Comment by laveena-en** [comment]
Tested and verified for the following test-cases:
1. When current theme cannot be fetched - revert to the default theme (Modern)
2. (In continuation to the above) Notifying the user that the theme couldn’t be fetched hence the default theme has been set via a toast message 
3. Checked if custom themes are being set after the app has reverted to the default theme (An issue was seen and a separate [issue](https://github.com/appsmithorg/appsmith/issues/17048) has been raised for it.

Tested the above scenarios for:
1. Both git connected and non-connected apps.
2. With custom themes as well as system themes.
3. Edit and view modes.

cc: @chandannkumar

**Pull request merged**
