### PR TITLE
chore: Add git discard documentation url in status API response

### PR DESCRIPTION
**Pull request by abhvsn**
## Description

> PR to add discard and pull doc link for `getStatus` API response. This will be consumed by the client to navigate user to Appsmith documentation on a separate tab. 

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

> JUnit TC

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by abhvsn** [comment]
@IAmAnubhavSaini sample response:
```
{
    "responseMeta": {
        "status": 200,
        "success": true
    },
    "data": {
        "modified": [
            "queries/InsertQuery_Page1.json",
            "pages/Page1/queries/UpdateQuery.json",
            "pages/Page1.json",
            "metadata.json",
            "pages/Page2/queries/Query1.json",
            "queries/DeleteQuery_Page1.json",
            "pages/Page1/canvas.json",
            "queries/UpdateQuery_Page1.json",
            "pages/Page2.json",
            "pages/Page1/queries/DeleteQuery.json",
            "queries/Query1_Page2.json",
            "queries/SelectQuery_Page1.json",
            "pages/Page1/queries/InsertQuery.json",
            "pages/Page1/queries/SelectQuery.json",
            "pages/Page2/canvas.json"
        ],
        "added": [],
        "removed": [],
        "conflicting": [],
        "isClean": false,
        "modifiedPages": 9,
        "modifiedQueries": 5,
        "modifiedJSObjects": 0,
        "modifiedDatasources": 0,
        "aheadCount": 0,
        "behindCount": 0,
        "remoteBranch": "refs/remotes/origin/master",
        "discardDocUrl": "https://docs.appsmith.com/core-concepts/git-sync#discard-and-pull-changes"
    }
}
```

**Review by AnaghHegde — APPROVED** [review]

**Pull request merged**
