### PR TITLE
chore: Add errorId to DEBUGGER_NEW_ERROR_MESSAGE telemetry

### LINKED ISSUE #22558: [Bug]: Add errorId to DEBUGGER_NEW_ERROR_MESSAGE event
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Add errorId to `DEBUGGER_NEW_ERROR_MESSAGE` telemetry event. And also make errorId uniquer for each of the `DEBUGGER_NEW_ERROR_MESSAGE` and `DEBUGGER_RESOLVED_ERROR_MESSAGE`

### Steps To Reproduce

This event is fired on new error in the log.

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by ChandanBalajiBP**
## Description

> Add errorId to `DEBUGGER_NEW_ERROR_MESSAGE` event
> Add timestamp to errorId to have 1:1 mapping of resolved and new error mapping.

> Add a TL;DR when description is extra long (helps content team)

Fixes #22558 

## Type of change

> Please delete options that are not relevant.

- Chore (housekeeping or task changes that don't impact user perception)

## How Has This Been Tested?

- Manual

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### CODE REVIEW

**Comment by ChandanBalajiBP** [comment]
Adding test plan approved label as this PR adds errorId to telemetry and no need of testing. I have manually verified the event in the logs.

**Review by sneha122 — APPROVED** [review]

**Pull request merged**
