### PR TITLE
fix: Active color of primary buttons broken after ADS 2.0 migration

### LINKED ISSUE #25446: [Bug]: Admin settings - Branding - Color theme - While we "Click" on a button we are able to see a different color or the default color theme in the application
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When admin have changed the settings of color theme in the application, we are able to see a default color when we click on a button.

https://github.com/appsmithorg/appsmith/assets/104895602/2b2c5bf7-047e-4e05-b5ac-8d103da91055

### Steps To Reproduce

1. Go to Admin setting and change the color theme to a different color
2. Click on any button in the application
3. Observe while clicking on the button we are able to see a change of color 

### Public Sample App

_No response_

### Environment

Deploy Preview

### Issue video log

_No response_

### Version

Appsmith Business v1.9.28-SNAPSHOT

### LINKED ISSUE #27501: [Bug]: The primary buttons across the instance disappear on mouse hover.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Buttons on the welcome screen disappear on mouse hover.

### Steps To Reproduce

**Steps to reproduce:**
1. Take a latest pull from the release
2. ENter the details on first welcome/onboarding screen
3. Mouse hover on "Continue" button

Observe that the button disappears. 
A similar observation is made on the next two screens as well. 

Please find the video below.

https://github.com/appsmithorg/appsmith/assets/132880870/21303d6d-157e-42b2-a893-4dd7d672c91f

### Public Sample App

_No response_

### Environment

Release

### Issue video log

_No response_

### Version

Appsmith Business v1.9.39-SNAPSHOT

### PR DESCRIPTION
**Pull request by albinAppsmith**
## Description

When admin has configured the branding color, on click of primary button, still appsmith orange color was being rendered. This PR fixes that issue and also added a fallback to handle the old customers who already have a branding color. This fallback is required since the new fix work only for people who choose brand color after this PR is merged.

Corresponding EE PR: https://github.com/appsmithorg/appsmith-ee/pull/2182

#### PR fixes following issue(s)
Fixes #25446 
Fixes #27501

#### Type of change

- Bug fix (non-breaking change which fixes an issue)

- [x] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [x] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by jsartisan — APPROVED** [review]

**Review by jsartisan — APPROVED** [review]

**Comment by laveena-en** [comment]
@albinAppsmith There's an extra `Active` state seen for Branding. Please have a look:
image

**Review by jsartisan — APPROVED** [review]

**Comment by albinAppsmith** [comment]
@laveena-en Please re test this PR

**Review by jsartisan — DISMISSED** [review]

**Comment by laveena-en** [comment]
@albinAppsmith Can you please check if this was intended: https://www.loom.com/share/78aaf677437b44f5a5688713c2a6dfee?sid=eca3a72e-e11d-43d5-a771-946c8245788c

**Comment by albinAppsmith** [comment]
@laveena-en this is intentional, the new Appsmith orange color is #E15615.

**Comment by laveena-en** [comment]
Tested and verified on EE and CE. We can go ahead with these changes.

**Review by jsartisan — APPROVED** [review]

**Pull request merged**
