### PR TITLE
feat: added keyboard interaction for datepicker

### LINKED ISSUE #10095: [Task]: Make the datepicker in property pane keyboard accessible
Insert a date picker widget and look at the property pane to see the date picker.

Screenshot 2021-12-31 at 8 27 40 PM

Reference: [HTML input type "datetime-local"](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_type_datetime-local)

### PR DESCRIPTION
**Pull request by ankurrsinghal**
## Description

Made the DatePicker control in the property pane keyboard accessible.
- On pressing the tab, highlight the text, do not open the picker.
- When we are on the field, if we press Enter, open the picker.
- If the picker is open and we press the tab, focus the picker and cycle through all the controls inside the picker, on subsequent tabs.
- On pressing Esc close the picker and defocus from the field.
- If any of the picker controls are focused they will take control of the Enter/Space to select the value.
- On clicking the field open the picker.

Fixes #10095

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Manually

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: feature/pp-datepicker 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 56.36 **(-0.06)** | 37.74 **(-0.07)** | 35.98 **(-0.04)** | 56.57 **(-0.07)**
 :red_circle: | app/client/src/components/ads/DatePickerComponent.tsx | 10.23 **(-39.77)** | 3.39 **(-96.61)** | 0 **(0)** | 10.59 **(-39.41)**</details>

### CODE REVIEW

**Review by jsartisan — DISMISSED** [review]

**Review by aswathkk — DISMISSED** [review]

**Comment by vivekverma2312** [comment]
@ankurrsinghal 
Date picker issue
1. Pressing tab moves focus from previous icon to next icon and not from left to right
2. Enter is not working when focus is on month and year
3. When click clear using short cut it clears the default date from widget but not from the default property field
4. Now if again I set the default date and press tab the date in property gets clear

https://www.loom.com/share/458040f8b55241dabe68e97628033cd1

**Comment by ankurrsinghal** [comment]
@vivekverma2312 Thanks for the Q/A review, regarding 1,2, and 5th points, it's the way how Blueprint Datepicker behaves and it will be a lot of mess to change that behavior. I will see the 3rd and 4th points.

**Comment by aswathkk** [comment]
@ankurrsinghal Can you resolve the issues and close this PR soon?

**Comment by ankurrsinghal** [comment]
I will work on this today @aswathkk .

**Comment by ankurrsinghal** [comment]
@vivekverma2312 Hi Vivek, can you please QA it again, something regarding the datepicker cannot be changed as we have discussed. I am adding a link to the component from Blueprint which we use for your reference. (https://blueprintjs.com/docs/#datetime/dateinput)

**Comment by vivekverma2312** [comment]
@ankurrsinghal After I select a date in the date pop up it do not close. This is different from existing behaviour in prod. Can you please confirm if this is intentional?
https://www.loom.com/share/9566b7271da1493db676a71e4525aa80

**Comment by ankurrsinghal** [comment]
Yes @vivekverma2312 it is intentional couldn't find a way to hook up to those events. So that's why it's a limitation.

**Review by aswathkk — APPROVED** [review]

**Comment by vivekverma2312** [comment]
@ankurrsinghal Tested and it looks good.

**Pull request merged**
