### PR TITLE
FIX #4376 : update default config response to render proper data for …

### LINKED ISSUE #4376: [Bug] Table row is not rendering the example data properly when table widget is dropped on the canvas the first time.
## Description
Screenshot 2021-05-07 at 10 49 58 PM

### PR DESCRIPTION
**Pull request by vibhandikyash**
## Description
Table row is not rendering the example data properly when table widget is dropped on the canvas the first time

Fixes #4376 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: FIX/4376-table-row-not-rendering-drop-on-canvas 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 54.14 **(-0.01)** | 36.18 **(0)** | 32.8 **(-0.01)** | 54.63 **(-0.01)**
 :red_circle: | app/client/src/mockResponses/WidgetConfigResponse.tsx | 11.34 **(-0.75)** | 0 **(0)** | 0 **(0)** | 11.7 **(-0.8)**</details>

### CODE REVIEW

**Review by riodeuno — DISMISSED** [review]

**Comment by somangshu** [comment]
Rerunning jobs for failing tests

**Comment by vivekverma2312** [comment]
@vibhandikyash Drag 2 table widgets with default data, this time query api for another table (Table2). Observe that the table1 data reset.

https://www.loom.com/share/ad1f6ddb23b24bf4be145267e5ce5eee

**Comment by vibhandikyash** [comment]
@vivekverma2312 It seems to work fine on my local machine. Can't reproduce as you mentioned in the video.

**Comment by vivekverma2312** [comment]
@vibhandikyash Can you please check if you are able to repro in the deploy preview.

**Review by somangshu — DISMISSED** [review]

**Review by riodeuno — APPROVED** [review]

**Comment by vibhandikyash** [comment]
> @vibhandikyash Can you please check if you are able to repro in the deploy preview.
@vivekverma2312 The issue that your mentioned has been fixed. Kindly retest.

**Comment by somangshu** [comment]
@vibhandikyash latest merge required here to fix failing tests

**Comment by vivekverma2312** [comment]
@vibhandikyash The fix has been tested and working fine.

**Review by somangshu — APPROVED** [review]

**Comment by somangshu** [comment]
@vibhandikyash the latest test failing has been fixed and merged into release, we will have to update it here again!

**Review by somangshu — APPROVED** [review]

**Pull request merged**
