### PR TITLE
feat: support window object access.

### PR DESCRIPTION
**Pull request by arunvjn**
## Description
- Intercepts access to window variable in code using proxy (windowProxy.ts)
- Registered a new route to trap window intercept requests.
- Added reference maps to make subsequent request maintain the context.

Fixes # (issue)
> if no issue exists, please create an issue and ask the maintainers about this first

Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update

- Manual
- Jest
- Cypress

### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Comment by japrogramer** [comment]
I cannot access the window object from the jsObjects code editor after trying out this pull request.

**Comment by japrogramer** [comment]
> > @arunvjn I cannot access the window object from the jsObjects code editor after trying out this pull request.
> 
> @japrogramer Could you please confirm if [serviceworker](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorker) is active? DevTools -> Applications -> Service workers

The Service worker is working properly are there anymore steps to debug this?

```
pageService.js
Received 8/15/2023, 5:23:12 PM
#3309 activated and is running
```

**Comment by japrogramer** [comment]
I ended up using postWindowMessage to solve my problem. thank you

**Comment by arunvjn** [comment]
Closing this PR since it is not relevant at the moment

**Pull request closed without merging**
