### PR TITLE
fix: ADS select styles getting overridden by WDS components

### LINKED ISSUE #24459: [Bug]: Old ADS colors showing up in property pane
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

We are seeing old ADS gray color show up in drop downs scrollbars & search components for widgets such as:

1. Currency Input 
2. Phone input widget 
3. Input widget
4. Multi Select Tree Widget
5. Multi Select Widget
6. Table Widget (scroll, search, header)

### Steps To Reproduce

1. D&D a MultiSelect widget.
2. Click on the `Height` property.

**Expected:** We should see the new grays in the dropdown.
**Actual:** Older grays are appearing.

### Public Sample App

_No response_

### Environment

Production

### Issue video log

https://www.loom.com/share/436d0775566940c9b9ff4c12e9a30c47

### Version

Cloud

### PR DESCRIPTION
**Pull request by albinAppsmith**
## Description
This issue fixes, 
Select component option styles was getting overridden by WDS tree select component.

#### PR fixes following issue(s)
Fixes #24459

#### Media
**Before**
Screenshot 2023-06-15 at 11 14 43 PM
**After**
Screenshot 2023-06-15 at 11 16 18 PM

#### Type of change

- Bug fix (non-breaking change which fixes an issue)

- [ ] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by KelvinOm — APPROVED** [review]

**Comment by shadabbuchh** [comment]
Reopening this issue as no DP is available for this.

**Comment by shadabbuchh** [comment]
Tested this PR. Looks good.


https://github.com/appsmithorg/appsmith/assets/39921438/8c31953e-5aed-4a25-89a9-66793749a412

**Review by KelvinOm — APPROVED** [review]

**Pull request merged**
