### PR TITLE
fix: #11112 updated list widget property config

### LINKED ISSUE #11112: [Bug]: Widget styling options on List widget is not categorized under Styles
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

List widget styling options is not under Styles as is the case with other widgets

### Steps To Reproduce

image
image
image

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by vibhandikyash**
## Description

> Categorising widget styling options for List Widget.

Fixes #11112 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Tested locally.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>

    // Code coverage diff between base branch:release and head branch: fix/11112-update-property-config-list-widget 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.94 **(0.23)** | 41.67 **(0.84)** | 36.21 **(0)** | 56.99 **(0.25)**</details>

### CODE REVIEW

**Review by jsartisan — APPROVED** [review]

**Comment by shwetha-ramesh** [comment]
@vibhandikyash tested this PR. DP looks good. Styling option now appear under Styles.
image

**Pull request merged**
