### PR TITLE
fix: Inconsistency propertypane

### LINKED ISSUE #8439: [Bug]-[97]:Inconsistency in the field title of the property pane
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

For few of the Widgets the text title is displayed as **colour** in some places and **color** in some places.

Current status:

1.Container widget - Background **colour**, Border **colour**  and Shadow **color**
2.Audio Recorder - Icon **color** , Background **color**
3.Button Widget - Button **color**, Shadow **color**
4.Divider Widget - Divider **color**
5.Form Widget - Background **colour**, Border **colour**  and Shadow **color**
6.Icon Widget - Button **color**, Shadow **color**
7.Iframe Widget - Border **color**
8.List Widget - Background , Item Background - **text colour is not displayed** 
9.Menu Widget - Icon **color**, Text **color**, Background **color** , Menu **color**, Shadow **color**
10.MultiTeeSelect - Label text **color**
12.Rate Widget - Active **color**, Inactive **color**
13.Stat Box Widget - Background **color**
14.Table Widget - Cell Background -**text colour is not displayed for Cell Background**  , Text **color**
15.Text Widget -  Cell Background -**text colour is not displayed for Cell Background** , Text **color** , Border **Colour**
16.TreeSelect - Label text **color**

### Steps To Reproduce

```markdown
1.Launch appsmith app in release or Prod environment 
2.Drag and drop most of the widgets , open property pane and check the field title of colour
```

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by keyurparalkar**
## Description

I have made the following changes:
Changing colour to color for following widget, rest of the widget already having color hasn't been changed.

1.Container widget - Background colour, Border colour and Shadow color ✔️

5.Form Widget - Background colour, Border colour and Shadow color ❗
(couldn't find any files in form widget having the above properties)

8.List Widget - Background , Item Background - text colour is not displayed ✔️

14.Table Widget - Cell Background -text colour is not displayed for Cell Background , Text color ❗
(couldn't find any files in table widget having the above properties)

15.Text Widget - Cell Background -text colour is not displayed for Cell Background , Text color , Border Colour ✔️

Fixes #8439

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Failing test cases are fixed.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: inconsistency-propertypane 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 55.06 **(-0.01)** | 36.56 **(-0.01)** | 34.5 **(0)** | 55.58 **(0)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.71 **(-0.23)** | 40.83 **(-0.84)** | 36.21 **(0)** | 56.74 **(-0.25)**</details>

### CODE REVIEW

**Comment by keyurparalkar** [comment]
This PR is an extension to the existing PR: #8599

**Review by jsartisan — APPROVED** [review]

**Pull request merged**
