### PR TITLE
fix: peeking on undefined properties

### LINKED ISSUE #23817: [Bug]: Peek overlay shouldn't work on undefined variables
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://www.loom.com/share/8a21626d889d408da4742844dbfe0bbf

### Steps To Reproduce

Type some random variable in JsObject and hover on it.

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

Appsmith v1.9.20.4

### PR DESCRIPTION
**Pull request by eco-monk**
## Description
Don't show peek overlay on undefined variables.
Also filter internal property `pageList`.

#### PR fixes following issue(s)
Fixes #23817

#### Media
https://www.loom.com/share/751ce60facdb446d9c1bb4208dc697c4

#### Type of change
- Bug fix (non-breaking change which fixes an issue)
#### How Has This Been Tested?
- [x] Manual
- [ ] Jest
- [x] Cypress
>
>
#### Test Plan
Tested random variables and strings for negative check
>
>
#### Issues raised during DP testing
none
>
>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [x] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [x] Cypress test cases have been added and approved by SDET/manual QA
- [x] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by hetunandu — APPROVED** [review]

**Comment by tanvibhakta** [comment]
No ads review necessary

**Pull request merged**
