### PR TITLE
chore: update alpha release

### PR DESCRIPTION
**Pull request by tanvibhakta**
## Description

Updates this release: https://github.com/appsmithorg/design-system/pull/420

Depends on https://github.com/appsmithorg/design-system/pull/420 as well.

## Type of change

- Chore (housekeeping or task changes that don't impact user perception)

## How Has This Been Tested?

- Manual
- Jest
- Cypress

### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by albinAppsmith — APPROVED** [review]

**Comment by shadabbuchh** [comment]
Completed a sanity on this PR. No issues around the icon component found.

**Review by albinAppsmith — APPROVED** [review]

**Pull request merged**
