### PR TITLE
Add Table button in Rich Text Editor's Toolbar

### LINKED ISSUE #3442: [Feature] Inserting table in Rich Text Editor widget
The rich text editor widget indicates that the table plugin has been installed. This can be verified by clicking on the `?` icon in the editor's toolbar, and seeing that the table plugin is listed under `Installed Plugins` header.

However, there's no button in the toolbar of the rich text editor to insert a table. This makes it impossible to add a table for users in the editor.

Please add a button in the toolbar, or some other way to insert a table in the editor content.

### PR DESCRIPTION
**Pull request by aswathkk**
## Description
Added Table button into the Rich Text Editor's toolbar.

Fixes #3442 

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

All the existing tests passed. I manually tested the newly added button

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by aswathkk** [comment]
@Nikhil-Nandagopal All the tests are passing. But the Client Build Workflow is showing the following error:
```
Error: HttpError: Resource not accessible by integration
```
Do I need to have any permissions to make it pass?

**Comment by Nikhil-Nandagopal** [comment]
@jsartisan can you help with this?

**Comment by jsartisan** [comment]
@Nikhil-Nandagopal @aswathkk Just checked the PR on my local. It's working fine.

**Review by jsartisan — APPROVED** [review]

**Comment by jsartisan** [comment]
@Nikhil-Nandagopal I think this is okay to merge this PR.

**Comment by mohanarpit** [comment]
Closing in favor of #3799. For some reason, Github Actions was throwing an error on this PR. 

Thank you @aswathkk for your contribution towards making Appsmith a better project! 🎉

**Pull request closed without merging**
