### PR TITLE
fix: remove data identifier error when there's no List data

### LINKED ISSUE #21767: [Bug]: This data identifier evaluates to an empty array Error When List Widget Is Empty
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

A user has a List widget that is populated by the result returned by a query. Sometimes the query might return no results; in this case, we have an empty array. If this happens, the user gets this error in the editor: `This data identifier evaluates to an empty array. Please use an identifier that evaluates to a valid value.` 
image
If turning off the visibility of the list if the source data is empty, then the error disappears.

[Forum post](https://community.appsmith.com/t/list-widget-that-uses-an-array-that-sometimes-could-be-empty/2157)
[Front thread](https://app.frontapp.com/open/msg_1oth99u4?key=ikV3nGA8_GdgK1oTIi9ziqihbD59hJYs)

### Steps To Reproduce

Add a List widget to the canvas and bind it to the result of a query that returns no results.

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

Appsmith v1.9.12-SNAPSHOT

Front logo [Front conversations](https://app.frontapp.com/open/top_8bw5o)

### LINKED ISSUE #22504: [Bug]: currentItem is not defined error on empty list that are not visible
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

1. When a List widget items is an empty array, you get an error. 
`This data identifier evaluates to an empty array. Please use an identifier that evaluates to a valid value.`
3. To avoid the error I was advised to add a condition to make take list visible only if the items array length is greater than 0.
4. But then the elements within that (invisible) list widget reports the error:
`currentItem is not defined`

### Steps To Reproduce

1. create a list widget
2. set an empty array is its itesm
3. set list widget visible to false
4. elements within the list widget shows error
`currentItem is not defined`

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

Self hosted / v1.9.15

### PR DESCRIPTION
**Pull request by Tooluloope**
## Description
When the List widget has empty data, we want to avoid showing the Data identifier error.

Fixes #21767
Fixes #22504

Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Jest

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by ashit-rath — COMMENTED** [review]
When I add `{{null}}` to the `Items`, the list widget crashes. I think we might need to update the property config validation of this field by adding a default value to it so that it does not pass the `null` value to the list widget.

**Review by ashit-rath — APPROVED** [review]

**Comment by chandannkumar** [comment]
Tested this PR and LGTM
- Observed no error message on data identifier when List data is empty

**Pull request merged**
