### PR TITLE
fix: Add back canvas resize

### PR DESCRIPTION
**Pull request by albinAppsmith**
## Description

Added back canvas resizing while switching to side by side.

#### PR fixes following issue(s)
Fixes https://github.com/appsmithorg/appsmith/issues/31057

#### Type of change
- Bug fix (non-breaking change which fixes an issue)

## Testing

- [ ] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

## Summary by CodeRabbit

- **Refactor**
	- Enhanced the `useDynamicAppLayout` hook for improved layout calculations and control flow, removing dependencies on specific editor states and modes.

### CODE REVIEW

**Comment by riodeuno** [comment]
@albinAppsmith Could you share a before and after recording. I have very little idea about what broke and what we've fixed. Also, how does the changes effect the fix?

**Comment by albinAppsmith** [comment]
> @albinAppsmith Could you share a before and after recording. I have very little idea about what broke and what we've fixed. Also, how does the changes effect the fix?

Hi @riodeuno ,
I'm not able to make a video of this in my screen. I can try to explain this change to you.

So when IDE pod added side by side layout, the canvas was getting resized when switch from and to UI mode. So in order to prevent this re-render, what I had done is if split screen mode is enabled, I had stopped recalculating the canvas based on CANVAS_VIEWPORT width. This then will show the canvas with horizontal scroll. 
What this PR does is removing this particular logic to previously how it was. Reason being. We are conducting a search party next week and to see how much of performance issue is this canvas resizing causing.

**Comment by riodeuno** [comment]
@albinAppsmith 

Thanks for the details.

Could you DM me on this with some elaboration
> We are conducting a search party next week

**Review by hetunandu — APPROVED** [review]

**Pull request merged**
