### PR TITLE
fix: switch group added check for inline width

### LINKED ISSUE #14185: [Bug]: Switch group widget - Inline property not working
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I drop a switch group widget on the canvas, it is seen that the inline property of the widget does not work, though the Inline property is enabled by default. The switch group options remain one below the other with the inline enabled, even though they are supposed to be next to each other.

### Steps To Reproduce

1. Drop the switch group widget on to the canvas
2. Note that the Inline property is enabled by default, but still the options are one below the other. 

This is broken in release. Works fine in Production.

Also tested an older application which had a Switch Group Widget, and found that the older application also was impacted by this bug. 
swgrpinline2
swgrpinline1

### Public Sample App

_No response_

### Version

Release

### PR DESCRIPTION
**Pull request by techbhavin**
## Description

> In the SwitchGroup widget inline property is not working 

Fixes #14185

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>

    // Code coverage diff between base branch:release and head branch: bug/switch-group-inline 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 56.71 **(0)** | 38.66 **(-0.01)** | 36.23 **(0.01)** | 56.96 **(0)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.71 **(-0.23)** | 40.83 **(-0.84)** | 36.21 **(0)** | 56.74 **(-0.25)**
 :green_circle: | app/client/src/widgets/SwitchWidget/component/index.tsx | 97.56 **(0.12)** | 70.59 **(-1.29)** | 87.5 **(1.79)** | 96.88 **(0.11)**</details>

### CODE REVIEW

**Review by jsartisan — APPROVED** [review]

**Comment by shadabbuchh** [comment]
This issue is fixed now. Tested it in DP.
The `Switch Group` abides by the `Inline` property. Also when initially dropped onto the canvas, the options appear next to each other.

https://images.zenhubusercontent.com/275993885/97fa631f-0eca-4863-84e9-cb2467df668e/screen_recording_2022_05_31_at_11_23_52_am.mov

Moving it to `Done`.

**Comment by somangshu** [comment]
Screenshot 2022-05-31 at 11 33 37 AM

It still does not seem resolved to me @jsartisan @techbhavin

**Review by rahulramesha — APPROVED** [review]

**Pull request merged**
