### PR TITLE
fix: cell wrapper

### LINKED ISSUE #6673: [Bug] Deploy Preview - The columns and the operators are not selectable in the table filter pane
## Description
Deploy Preview - https://deploy-preview-6662--appsmith-editor-ce.netlify.app/applications
It is observed that in the table filter pane the columns and operators are not selectable 

**Expected Result:**
User should be able to select columns and operators in the table filter pane

### Steps to reproduce the behaviour:
1. Launch appsmith app in the deploy preview https://deploy-preview-6662--appsmith-editor-ce.netlify.app/applications
2. Drag and drop table widget 
3. open filter pane 
4. Try to select columns and operators in the filter pane and observe

**videolink:**
https://loom.com/share/b9a9f71192c644d5b9ed83a044b883f1

### Important Details

- Version: [11.3]
- OS: [MacOS]
- Browser [chrome, safari]
- Environment [deploy preview]

### LINKED ISSUE #6699: [Bug] Unable to see query results in query editor pane
Screenshot 2021-08-18 at 7 17 27 PM
Screenshot 2021-08-18 at 7 21 43 PM

### PR DESCRIPTION
**Pull request by Tooluloope**
## Description
Cell wrapper visibility

> Bug Fix

Fixes #6673  
Fixes #6699 

> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

- Bugfix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/cell-wrapper 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 54.91 **(-0.01)** | 36.81 **(-0.01)** | 33.57 **(-0.02)** | 55.46 **(0)**
 :red_circle: | app/client/src/utils/helpers.tsx | 66.11 **(-1.67)** | 37.89 **(-3.16)** | 45.16 **(-3.23)** | 63.19 **(-1.39)**
 :green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 50.71 **(0.24)** | 38.6 **(0.88)** | 36.21 **(0)** | 55.35 **(0.27)**</details>

### CODE REVIEW

**Review by somangshu — APPROVED** [review]
LGTM

**Comment by somangshu** [comment]
@vivekverma2312 we need a through regression here, Please consider this on priority and hot-fix

**Comment by vivekverma2312** [comment]
@Tooluloope Observed error in console after running query.
Error: `TypeError: Cannot read property 'source' of undefined`

Screenshot 2021-08-30 at 12 08 12 PM

**Comment by Tooluloope** [comment]
> @Tooluloope Observed error in console after running query.
> Error: `TypeError: Cannot read property 'source' of undefined`
> 
> Screenshot 2021-08-30 at 12 08 12 PM

Could you confirm this isn't on release?
for the changes, i made won't cause any errors @vivekverma2312

**Comment by vivekverma2312** [comment]
> > @Tooluloope Observed error in console after running query.
> > Error: `TypeError: Cannot read property 'source' of undefined`
> > Screenshot 2021-08-30 at 12 08 12 PM
> 
> Could you confirm this isn't on release?
> for the changes, i made won't cause any errors @vivekverma2312
@Tooluloope  No error in console on release.

Screenshot 2021-08-30 at 12 43 49 PM

**Review by somangshu — APPROVED** [review]

**Comment by Tooluloope** [comment]
@vivekverma2312 could you check again, I guess the console error was from a previous release.
just merged release with this branch and it looks fixed

**Comment by vivekverma2312** [comment]
@Tooluloope Tested and it's working fine.

**Pull request merged**
