### PR TITLE
chore: Split the import code to smaller parts

### LINKED ISSUE #25662: Refactor import application code to make it granular

### PR DESCRIPTION
**Pull request by nayan-rafiq**
## Description
This PR refactors the import application code so that the global variables are no more there. It also breaks down the code into small functions.

#### PR fixes following issue(s)
Fixes #25662

#### Type of change
- Chore (housekeeping or task changes that don't impact user perception)

#### How Has This Been Tested?
- [x] Manual
- [x] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by AnaghHegde — APPROVED** [review]

**Review by AnaghHegde — APPROVED** [review]

**Comment by Parthvi12** [comment]
@nayan-rafiq  Can you please check if it's a bug or something to do with DP, importing app in existing app fails on gsheet authorisation?

https://github.com/appsmithorg/appsmith/assets/80334441/aceaaf0c-6d0e-459c-ae20-ab2ee8e2b57c

**Review by Parthvi12 — DISMISSED** [review]

**Review by AnaghHegde — DISMISSED** [review]

**Review by AnaghHegde — APPROVED** [review]

**Pull request merged**
