### PR TITLE
Fix: show property pane only when respective widget is present on the DOM

### LINKED ISSUE #6675: [Bug] Property pane shows up before modal widget causing an unwanted scroll
## Description
Property pane of modal widget shows up before the widget causing an additional scroll to be added on the screen and also docks itself to the bottom of the screen causing an unnecessary block on the page while scrolling.

[LOOM DEMO](https://www.loom.com/share/84ca0d8441b04f63b9161a50f4b37c19)

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Production

### PR DESCRIPTION
**Pull request by marks0351**
… dom.

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Description

Drag and Drop Modal to see property pane showing below modal.

Fixes #6675 

> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/prop-pane 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 54.62 **(0.01)** | 36.69 **(0.02)** | 33.04 **(0)** | 55.23 **(0.01)**
 :green_circle: | app/client/src/selectors/propertyPaneSelectors.tsx | 81.16 **(0.56)** | 68 **(0.65)** | 100 **(0)** | 86.44 **(0.48)**
 :green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 50.71 **(0.24)** | 38.6 **(0.88)** | 36.21 **(0)** | 55.35 **(0.27)**</details>

### CODE REVIEW

**Review by SatishGandham — APPROVED** [review]

**Review by SatishGandham — APPROVED** [review]

**Review by jsartisan — APPROVED** [review]

**Comment by jsartisan** [comment]
@techbhavin for the 1st, you will need the add this in the property config of stats widgets

```

**Comment by jsartisan** [comment]
@marks0351 sorry closed the PR by mistake :P

**Comment by marks0351** [comment]
@YogeshJayaseelan has verified this. so merging this PR.

**Comment by YogeshJayaseelan** [comment]
@marks0351 Verified this PR and now it is working as expected. Property pane are displayed next to widgets and displayed after when widgets are loaded

**Comment by ramsaptami** [comment]
tested ok on deploy preview

**Pull request merged**
