### PR TITLE
test: Fix super user signup form cypress test

### LINKED ISSUE #9180: [Task]: Fix and uncomment super user signup form cypress tests
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

_No response_

### PR DESCRIPTION
**Pull request by sbalaji1192**
Fixes #9180 

> if no issue exists, please create an issue and ask the maintainers about this first

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: task/comment-super-user-cypress-test-fix 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 54.67 **(-0.01)** | 36.59 **(-0.01)** | 33.33 **(0)** | 55.19 **(-0.01)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.04 **(-0.22)** | 40.42 **(-0.83)** | 34.48 **(0)** | 55.96 **(-0.26)**</details>

### CODE REVIEW

**Comment by sbalaji1192** [comment]
https://github.com/appsmithorg/appsmith/actions/runs/1444785472

**Comment by sbalaji1192** [comment]
https://github.com/appsmithorg/appsmith/actions/runs/1445674130

**Comment by sbalaji1192** [comment]
https://github.com/appsmithorg/appsmith/actions/runs/1447444082

**Comment by sbalaji1192** [comment]
https://github.com/appsmithorg/appsmith/actions/runs/1447549310

**Comment by sbalaji1192** [comment]
https://github.com/appsmithorg/appsmith/actions/runs/1447683754

**Review by NandanAnantharamu — APPROVED** [review]
LGTM

**Pull request merged**
