### PR TITLE
fix: added width cap, updated props to handle size

### LINKED ISSUE #10787: [Bug]: Long menu item has ellipsis in MenuButton but not in ButtonGroup widget.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

For _MenuButton_ widget when a long Menu item is added an ellipsis is added at the end and on hover the whole item name is displayed there by maintaining the drop down to the width of the widget which looks neat. Whereas in _ButtonGroup_ widget when the button type are of Menu, the items with long name do not have a ellipsis and overflows from the widget which doesn't look crisp. Suggest same can be followed as MenuButton widget

image

image

### Steps To Reproduce

1. Drag & drop Menubutton widget > Add a menu item with long name 
2. Drag & drop ButtonGroup widget > For _More_ button dad a menu item with long name 
3. Click on the drop down and verify both

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by techbhavin**
## Description

> fixed design issue Long menu item has ellipsis in MenuButton

Fixes #10787 

- Bugfix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: bug/btn-grp-handle-long-menu-items 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 55.76 **(-0.02)** | 37.09 **(-0.01)** | 35.82 **(0)** | 56.11 **(-0.02)**
 :red_circle: | app/client/src/sagas/JSActionSagas.ts | 16.67 **(-0.72)** | 1.96 **(-0.17)** | 6.67 **(0)** | 19.71 **(-0.9)**
 :red_circle: | app/client/src/widgets/ButtonGroupWidget/component/index.tsx | 23.33 **(-1.97)** | 10.69 **(-0.33)** | 4.76 **(-0.24)** | 25 **(-2.78)**
 :red_circle: | app/client/src/widgets/ButtonGroupWidget/widget/index.tsx | 56.67 **(-2.59)** | 0 **(0)** | 33.33 **(0)** | 57.14 **(-2.86)**</details>

### CODE REVIEW

**Review by jsartisan — APPROVED** [review]

**Comment by chandannkumar** [comment]
Tested this PR and working as expected

**Comment by shwetha-ramesh** [comment]
@techbhavin tested this PR. The  mentioned issue still exists on DP

https://loom.com/share/96593e0983e5417fba6ae6ca53d42383

**Pull request merged**
