### PR TITLE
fix: Cell background colour not applied to new columns in table widget

### LINKED ISSUE #11734: [Bug]-[298]:Cell background color not applied for new columns in table widget
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Cell background color not applied for new columns in table widget
image
https://loom.com/share/3130ad9143284ed1944d6f7d9ddd861d

### Steps To Reproduce

1. Drag and drop table widget
2. In property pane add Cell background color
3. Create new column > Make column type as Button

### Public Sample App

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by souma-ghosh**
## Description

- On investigating this issue we found that apart from cellBackground other properties (textColour, textSize, fontStyle, verticalAlignment and horizontalAlignment) are also not being applied by default to newly added columns
- We were already applying these properties to new columns but this was not working since the properties were not present in the dependency list for Columns in table property
- This fix applies cellBackground, textColour, textSize, fontStyle, verticalAlignment and horizontalAlignment to new columns by default

Fixes #11734 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manually tested

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by sbalaji1192 — APPROVED** [review]

**Comment by laveena-en** [comment]
Tested and verified.

**Comment by souma-ghosh** [comment]
@somangshu The cypress tests that are failing here are for Aforce app
Also added Albin to review this as one check says someone from Design System pod required to review it (not sure why as this is just a small fix where newly added columns will have the default table styles (like cell background, font size etc.) applied to it.

**Comment by somangshu** [comment]
@souma-ghosh i didn't understand the failing test problem you mentioned. Can you get help from the automation team.

The other part happens when the we make any change in a component which is now part of the design system.

**Pull request merged**
