### PR TITLE
fix: table sorting with null values

### LINKED ISSUE #7598: [Bug] Sorting Numeric Fields doesn't work
## Description

Sorting doesn't appear to function on decimal types.

### Steps to reproduce the behavior:

1. Set a number type column - pull from a database table.
2. Set the type to number
3. Sort
4. Note: The images show "$" signs, etc. These are done post. If you remove any formating by Intl.Number, the issue still persists.

image
image

### Important Details

- Version: Self-Hosted - Release v1.5.21 
- OS: Windows 10
- Browser: MS Edge - Version 93.0.961.52 (Official build) (64-bit)
- Environment: Development/Production

### PR DESCRIPTION
**Pull request by sbalaji1192**
## Description
Push null values to bottom of the table while sorting

Fixes #7598 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/table-sorting-with-null 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 54.63 **(0)** | 36.37 **(0.03)** | 33.1 **(0.01)** | 55.16 **(0.01)**
 :green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.26 **(0.22)** | 41.25 **(0.83)** | 34.48 **(0)** | 56.22 **(0.26)**
 :green_circle: | app/client/src/widgets/TableWidget/widget/derived.js | 58.65 **(0.81)** | 59.76 **(2.17)** | 45.24 **(1.34)** | 58.64 **(0.89)**</details>

### CODE REVIEW

**Comment by sbalaji1192** [comment]
@vivekverma2312 Could you please test this on DP?

**Comment by vivekverma2312** [comment]
@sbalaji1192 Data is not reflected on the Table widget after binding.I can only see the column name is reflecting. I am blocked with testing the fix on the deploy preview.
Screenshot 2021-11-11 at 12 06 04 PM

**Comment by sbalaji1192** [comment]
@vivekverma2312 Fixed the issue. Could you please take a look again ?

**Comment by shwetha-ramesh** [comment]
@sbalaji1192 tested this on DP. Below are the observed issues.
* Sorting does not appear right for ascending and descending when column type is set to Plain text. (Refer video)
image
image

* When column type is set to Numbers null values and zero are mixed up and are not sorted. (Refer video)
image
https://loom.com/share/f768fcdb7c714fd19539b968f07ba033

**Comment by sbalaji1192** [comment]
@shwetha-ramesh 
I have the fixed issue with sorting a column and empty values appear to be jumbled. Now all the empty values will come to the bottom.
Wrt, Issue with sorting string type columns, String sorting is little different than number sorting. For example, 200 < 1000 but "200" > "1000". since "2" is greater than "1". please test again on DP.

**Comment by shwetha-ramesh** [comment]
Re-tested this PR
The above listed issues are fixed.
When the column type is set to Plain text columns with just numericals and string+numericals (such as $,£) will sort appropriately with the selection made (asc, desc) and null values are pushed at the end of the column irrespective of type of sorting.

But when the column type is set to Numbers and if the column contains String (such as $200) this will be considered as a string and sorting is not applied in accordance with numbers, however null values are pushed at the end of the column.

_Moving this to DONE._

**Review by jsartisan — APPROVED** [review]

**Pull request merged**
