### PR TITLE
fix: widget field array validation

### LINKED ISSUE #14895: [Bug]-[28000]:Binding shows successful even for invalid JS
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Writing invalid code shows a successful state all across the editor

### Steps To Reproduce

1. Drag a table widget
2. Drag a Select widget
3. Bind {{Table1.test}} in the options field
4. See that it shows success
5. Add a JSObject and add the same invalid code in a function and notice it does not show an error

### Public Sample App

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by arunvjn**
## Description
Show validation error, when a field that accepts values of type array has bindings, but not the ones that evaluate to an array.

Fixes #14895 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manual

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by ohansFavour — DISMISSED** [review]
LGTM 
Few points though,
1. The `validate` function has 5 parameters, can we consider using an object?
2. @Aishwarya-U-R had talked about all new test cases adhering to typescript, could we consider that?

**Review by ohansFavour — APPROVED** [review]

**Comment by arunvjn** [comment]
Closing this PR since vercel deployment fails on every attempt. Will be recreating this PR.

**Pull request closed without merging**
