### PR TITLE
fix: Migration to convert old defaultOptionValue expression to new on…

### LINKED ISSUE #16829: [Bug]: Select widgets with bindings added before v1.8 have addtional {{ }} in default values
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When i open a select or multi select widget and it had bindings for default values `{{ }}` then we are observing additional `{{ }}` for them.

### Steps To Reproduce

1. Open any older app which has a select or multi select widget with a binding
2. Observe how it shows the default value now
image

### Public Sample App

_No response_

### Version

Production

### PR DESCRIPTION
**Pull request by sbalaji1192**
…e in Select & multi select widget
Fixes #16829

> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by ashit-rath — APPROVED** [review]

**Review by Tooluloope — DISMISSED** [review]

**Comment by laveena-en** [comment]
Tested and verified on both an old and new app for:
- Bindings in default options (Select, multis-select, tree and multi-treeselect widgets)
- General sanity 
The PR is working as expected.

**Review by Tooluloope — APPROVED** [review]

**Comment by laveena-en** [comment]
Test scenarios pertaining to this issue:

Exported old apps that consisted of select widgets that had bindings added.
An example app that was used to test: https://release.app.appsmith.com/app/multi-select

Tested the behaviour of the widgets in accordance to their bindings:

- Data displayed when bound to a text widget

- Data displayed in the widget itself

Tested other functionalities as a general sanity check to inspect if the fix impacted any other aspect of the widgets like search, validations etc.
(The above were tested for the entire select widget family)

cc: @somangshu

**Comment by somangshu** [comment]
This is great Laveena 
We should also do this on both the view & edit mode. The cases look good otherwise

**Comment by laveena-en** [comment]
Noted Somangshu.

**Pull request merged**
