### PR TITLE
fix: missing reference to installed libraries when an application is deployed

### LINKED ISSUE #20245: [Bug]: Reference to an installed library is lost in edit mode when an application is deployed
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

We reset libraries inside `setEvaluationVersion` function which called every time we fetch details of an application
When an application is deployed, we make a call to fetch app details to get the last deployed info and this ends up resetting the libraries on edit mode, thereby losing access to all the installed libraries.

### Steps To Reproduce

1. Create a new application.
2. Create a new JS Object.
3. Install uuidjs library.
4. Inside the async function of the JSObject simply `return UUID();`
5. Set ^ function to run on page load.
6. Deploy the app and observe that there are no errors.
7. Switch back to the edit mode tab and run the function manually.
8. Errors out saying UUID is not a function

### Public Sample App

_No response_

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by arunvjn**
## Description
Fixes a bug where application in edit mode loses references to installed libraries immediately after it is deployed.

Fixes #20245 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manual
- Cypress

### Test Plan
Add a test case to the existing [test plan](https://github.com/appsmithorg/TestSmith/issues/2125) on custom libraries

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [x] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [x] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by ApekshaBhosale — APPROVED** [review]

**Comment by ramsaptami** [comment]
LGTM
cc: @arunvjn

**Pull request merged**
