### PR TITLE
fix: Refactor dataTree diff translation

### LINKED ISSUE #20428: [Bug]: Multiselect widget's selected options getting reset when page is switched in List v2
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Multiselect widget's selected options getting reset when the page is switched in List v2

https://www.loom.com/share/d4fd134eb3ec45249edb3d4c009eb18e

### Steps To Reproduce

1. Drag List v2 widget
2. Drag Multiselect widget into it.
3. Delete one of the selected options
4. Switch to next page
5. Observe that selected option is empty in new page

### Public Sample App

_No response_

### Issue video log

_No response_

### Version

DP (https://appsmith-git-feat-list-widget-v2-get-appsmith.vercel.app/)

### PR DESCRIPTION
**Pull request by ohansFavour**
### Cause of issue
During the translation of dataTree diff, a change from an `Array` to `undefined`, was interpreted as a **delete event**. This causes the path to be deleted from the dependencyMap, hence doesn't ever show up in the evaluation order.

### Solution
A change from an Array or Object to undefined is translated to 

1. Deletion of all Array accessor paths 
2. Edit of propertyPath

### Example

Multiselect1.selectedOptions changes from ["Red", "Green"] to **undefined**. This translates to

1. Delete event for Multiselect1.selectedOptions[0] &  Multiselect1.selectedOptions[1] 
2. Edit event for Multiselect1.selectedOptions

Fixes #20428 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual
- Jest
- Cypress

### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Comment by ashit-rath** [comment]
@ohansFavour Any expected timeline on when this will get merged into release?
cc: @somangshu

**Comment by ohansFavour** [comment]
> @ohansFavour Any expected timeline on when this will get merged into release? cc: @somangshu

By next week Friday, 10th of February.

**Comment by somangshu** [comment]
@ohansFavour why such a long delay in merging this? What is pending, I had an understand that its only waiting to get merged while all sign-off were given on it. Please help us understand better 
cc @satbir121 @kamakshibhat-appsmith @ashit-rath

**Comment by ohansFavour** [comment]
@somangshu the priority for this has been bumped up, it will get merged by Wednesday.

Sign-off was given to the meta-rehydration fix, this issue is related directly to Evaluations.

**Review by ApekshaBhosale — APPROVED** [review]

**Comment by ohansFavour** [comment]
Add the "Test Approve label" as the fix has been tested [here](https://github.com/appsmithorg/appsmith/pull/20181) and endorsed [here](https://github.com/appsmithorg/appsmith/pull/20181#issuecomment-1408125578)

**Pull request merged**
