### PR TITLE
fix: Issue 34961 GraphQL Logo seems to be incorrect 

### LINKED ISSUE #34961: [Bug]: GraphQL Logo seems to be incorrect
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The GRAPHQL plugin logo is shown same as RestAPI plugin. 

### Steps To Reproduce

Screenshot 2024-07-16 at 1 13 33 PM

### Public Sample App

_No response_

### Environment

Production

### Severity

Low (Cosmetic UI issues)

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by shubham88fru**
## Description

Issue: The GRAPHQL plugin logo is shown same as RestAPI plugin.
Fix: Imported the right logo for graphql and used the right image in the img tag

Fixes #34961  

## Automation

/ok-to-test tags="@tag.Sanity @tag.IDE"

### :mag: Cypress test results

> [!CAUTION]  
> If you modify the content in this section, you are likely to disrupt the CI result for your PR.

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [x] No

## Summary by CodeRabbit

- **New Features**
  - Updated the New API screen to display the GraphQL logo instead of the Plus logo.

### CODE REVIEW

**Comment by shubham88fru** [comment]
Hi @ayushpahwa . Please review.

**Comment by shubham88fru** [comment]
Hi @ayushpahwa , please review this PR.

**Review by ayushpahwa — APPROVED** [review]
LGTM. Thanks for your contribution!

**Comment by NilanshBansal** [comment]
@ayushpahwa do we need any tests for this?

**Comment by ayushpahwa** [comment]
@NilanshBansal for UI changes like this, snapshot tests might be relevant but they are not really maintainable. I have done manual test on the DP generated however. Lemme know if there's any other suggestions/reservations.

**Comment by ayushpahwa** [comment]
All automation tests passed, okay to merge.

**Pull request merged**
