### PR TITLE
task: [Design System V2] Git features

### PR DESCRIPTION
**Pull request by hetunandu**
https://www.loom.com/share/3fe048ef056446fca7ce9c6cdf3f976b
fixes [#19409](https://github.com/appsmithorg/appsmith/issues/19409)

## Description

> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change
> Links to Notion, Figma or any other documents that might be relevant to the PR

> Add a TL;DR when description is extra long (helps content team)

Fixes # (issue)
> if no issue exists, please create an issue and ask the maintainers about this first

Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update

- Manual
- Jest
- Cypress

### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Comment by rohitagarwal88** [comment]
1. Local branches/Remote branches & separator` text color `to use ADS2.0 token
2. Border radius token is not used in selected & hover state for branch name
Screenshot 2023-04-14 at 12 20 55 PM
3. Dropdown menu is not using the `menu component`, if not possible use the menu component. Then, please use ADS2.0 color tokens
Screenshot 2023-04-14 at 12 12 56 PM

4. Can we get rid of the error box around the input, Also, the `error callout `is not from ADS 2.0. Callout goes out of the modal content boundary. @vasanth-appsmith 
Screenshot 2023-04-14 at 12 17 43 PM

5. @vasanth-appsmith : Do we need full-width merge button? Also, @albinAppsmith the select dropdown is hidden coz of zindex issue.
Screenshot 2023-04-14 at 12 10 40 PM

6. @albinAppsmith : Please update the progress bar component color with ADS 2.0 tokens.
Screenshot 2023-04-14 at 12 12 02 PM
7. ` Latest deploy preview` & text under it does not consume ADS 2.0 tokens.
Screenshot 2023-04-14 at 12 09 22 PM
8. Swap button positions.
Screenshot 2023-04-14 at 12 11 58 PM

**Comment by vasanth-appsmith** [comment]
Here are the issues I find on the DP!
[image](https://user-images.githubusercontent.com/92305123/233335725-65760f25-551c-4f8e-b978-bb1f0213438b.png)
image
image
image

**Comment by rohitagarwal88** [comment]
@hetu: The functionality is missing in your dedup git for RSA keys. check loom for details
https://www.loom.com/share/b3b999930fe648e6b01686029d3a2c65

**Comment by vasanth-appsmith** [comment]
Here are the list of issues I found
https://www.notion.so/appsmith/Git-Issues-cae9472e7c264ce78a06ebf3cfe22ddd?pvs=4

**Pull request merged**
