### PR TITLE
fix: upgrade page for audit logs with correct data

### PR DESCRIPTION
**Pull request by IAmAnubhavSaini**
## Description

This PR fixes:
- content that was repeated
- has new images
- removes comments
- brings text to messages file

## Compare

| OLD | NEW |
| - | - |
| security-and-compliance | security-and-compliance |
| debugging | debugging |
| incident-management | incident-management |

### CODE REVIEW

**Review by ankitakinger — APPROVED** [review]
LGTM

**Comment by vuiets** [comment]
@vasanth-appsmith the images are still not up to date. Could you please share the latest images here?

**Comment by vasanth-appsmith** [comment]
Here are the updated Upgrade Hooks for the Audit Logs
1. Content is changed to match with PR - Notion Doc. 
2. Changed the image for each of the carousels.


[Figma](https://www.figma.com/file/F0YqVElXWiuvP9MXHULHWk/Upgrade-hooks?node-id=612%3A12387)

@IAmAnubhavSaini  The graphics are attached here. 
[Updated.zip](https://github.com/appsmithorg/appsmith/files/9818099/Updated.zip)

**Review by ankitsrivas14 — DISMISSED** [review]
looks good

**Review by ankitakinger — DISMISSED** [review]

**Review by vuiets — APPROVED** [review]

**Comment by Rhitottam** [comment]
/perf-test ref=rhito/feat-create-run-meta-before-test-starts-compare-lt-st-for-prev-runs

**Pull request merged**
