### PR TITLE
fix: JSONForm input field REGEX validation

### LINKED ISSUE #14109: [Bug]-[12]:RegEx Validation Not Working in Input Field of JSON Form
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In a **JSON Form**, when using **Regex** on an **Input** field, the field shows as _invalid_, even if the value entered is correct.

image

### Steps To Reproduce

1. Add a **JSON Form** to the canvas and enter some **Source Data**. E.g.:
```
{
  "name": "John",
  "date_of_birth": "20/02/1990",
  "employee_id": 1001,
  "phone": "1234567890"
}
```
2. In the **Regex** property of the _Phone_ input field, enter `^\d+$` to allow only digits.
3. Type some digits in the _Phone_ input field.

**Expected behavior**: The field should be valid, as only digits have been entered.
**Actual behavior**: The field is shown as _invalid_.

### Public Sample App

https://app.appsmith.com/app/json-form/json-form-regex-validation-628e95f77901344ba8d2b2b1

### Version

Cloud  v1.6.26-SNAPSHOT

### PR DESCRIPTION
**Pull request by ashit-rath**
## Description

When a Regex property is entered a value like `^\d+$`. Under the hood, the value for the JSONForm is stored in this format
```{{sourceData, formData, fieldState) => (`^\d+$`))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}```

As this is a binding, it is evaluated and due to evaluation the `\d` is treated as an escape sequence and the `\` is removed.

So the solution is to not use the default binding template of the JSONForm when the value that is being entered in the property pane is not a dynamic value. In this way the regex will be treated as a plain text and won't get evaluated

If a user wants to use a regex in a binding the `\` has to be escaped i.e `{{^\\d+$}}`

Fixes #14109 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

1 cypress test is added to an existing spec

Test steps:
1. A new JSONForm is added 
2. The source data is updated to
```json
{ "name": "John" }
```
3. The property pane is opened and the `Regex` property is updated to `^\d+$` (accepts only numeric values).
4. The `name` field is entered an alphabetic value "abcd" and it is observed that the error popup shows up with message `Invalid input`
5. The `name` field is cleared and entered a numeric value "1234" and it is observed for no error pop ups.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by sbalaji1192 — DISMISSED** [review]

**Comment by chandannkumar** [comment]
This PR has broken DP link
@ashit-rath

**Comment by ashit-rath** [comment]
@chandannkumar Ahh yes there is some memory outage issue going on with vercel. Let me check with the team to re-deploy this.

**Comment by ashit-rath** [comment]
@chandannkumar The DP is now available.

**Comment by chandannkumar** [comment]
The Regex validation is working fine on this DP but **not working on Migration**. 
@ashit-rath cc: @dilippitchika

**Comment by dilippitchika** [comment]
Hey @chandannkumar it's a limitation for now. We will have to let people know once this is live that they have reconfigure their regex values.

**Comment by chandannkumar** [comment]
Tested this PR and it is working as expected.
- Tested regex validation with bindings
- Tested regex validation without bindings
- Tested with complex regex combinations

**Review by sbalaji1192 — APPROVED** [review]

**Pull request merged**
