### PR TITLE
fix for ui crashing when the gmaps api key is incorrect

### LINKED ISSUE #2378: [Bug] CE : On placing the Map Widget the page crashes
Steps to reproduce:
1) Add a Map widget 
and observe the map does not load 
2) Add any widget 
and observe the page crashes 

Expectation:
The page should not break 

Video:
https://www.loom.com/share/50c638c17182497aae0a6000e9aa5212

### PR DESCRIPTION
**Pull request by rishabhsaxena**
## Description
When the api key is incorrect/restricted by domain, gmaps mutates the DOM which results in an errored state. 
If we have a good way to measure the performance impact, we can take a call for this. Open to other suggestions as well.

fixes #2378 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- manually

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by ofpiyush — DISMISSED** [review]

**Comment by ofpiyush** [comment]
@hetunandu @riodeuno If you can find a better solve for this, please help out. 

Otherwise, this seems to add 2 checks on every node removal from DOM. (Not sure how to measure the perf hit of that.)

**Comment by hetunandu** [comment]
> @hetunandu @riodeuno If you can find a better solve for this, please help out.
> 
> Otherwise, this seems to add 2 checks on every node removal from DOM. (Not sure how to measure the perf hit of that.)

This fix does not sit well with me. Can we do something more targeted for the maps widget itself?

**Review by hetunandu — CHANGES_REQUESTED** [review]
Needs a more targeted approach for google maps component only

**Comment by ofpiyush** [comment]
I'm assuming that the objection more design neatness.

Things to figure:
- Can we add the problem component after verifying that we have a legitimate key? Would that prevent/solve the issue?
    - Eg: Would this also happen when the maps widget goes into loading?
- How important is the problem to solve?
    - How many users are facing this?
    - Should we spend time trying to dig deeper with the lib/sdk etc.
- Under what circumstances would we would accept a global solution like this?

**Comment by rishabhsaxena** [comment]
Closing this for now, since this seems like an edge case with using an incorrect gmaps API key. Also these errors are displayed on the console.

**Pull request closed without merging**
