### PR TITLE
feat: Add type inference for redux's useSelector hook

### PR DESCRIPTION
**Pull request by ravikp7**
Right now, in our codebase we're using two `useSelector` one from `react-redux` (without any type inference) and another is our custom one which provides type inference. The changes in this PR will bring consistency and better type support.

- Used module augmentation of TS to override the default root state interface
- Replaced custom hook with redux's useSelector
- It brings consistency as at a lot of places in the codebase we're using only the redux's useSelector without any type support.

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manual
- Jest

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by riodeuno — DISMISSED** [review]

**Comment by AnandiKulkarni** [comment]
@ravikp7 As per discussion below scenarios are verified
1. Validated older apps created, Apps created out of templates
2. Create multiple widgets and verified the functioning
3. Validated API calls and query calls 
4. Verified the action selector part

**Review by arunvjn — DISMISSED** [review]

**Review by arunvjn — APPROVED** [review]

**Pull request merged**
