### PR TITLE
Add few ternjs defs for moment

### PR DESCRIPTION
**Pull request by akash-codemonk**

### CODE REVIEW

**Review by hetunandu — APPROVED** [review]

**Comment by areyabhishek** [comment]
@akash-codemonk Good to see that this has been committed to release. Have you tested the feature? When can we push this to Master?

**Comment by akash-codemonk** [comment]
Yeah can be pushed to master.

**Comment by areyabhishek** [comment]
I just noticed the word 'few' in this PR and had a few questions. Why are we doing only few?(Will we end up dealing with this bug again?) Will the user not miss the rest? How have you chosen the few?

**Comment by akash-codemonk** [comment]
It doesn't contain all the definitions only a few commonly used ones are present. These definitions were added manually there are probably 20-30 more methods in moment which need to be added. Adding all of them would mean it has to be auto-generated somehow which has to be figured out.

**Pull request merged**
