### PR TITLE
feat: changed icon widget to icon btn for modal widget

### LINKED ISSUE #10758: [Enhancement]: Modal should use the icon button widget for close icon
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Use the icon widget for modal close button instead of hardcoding widget. 

### Why should this be worked on?

Makes it easy for users to customise

### PR DESCRIPTION
**Pull request by techbhavin**
## Description

> In Model Widget replace icon widget to Icon Button Widget

Fixes #10758 

## Type of change

- Bugfix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: enhancement/modal-use-icon-btn 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 55.89 **(0)** | 37.26 **(0.02)** | 35.29 **(0.01)** | 56.22 **(0)**
 :green_circle: | app/client/src/utils/DSLMigrations.ts | 73.38 **(0.11)** | 69.27 **(-0.06)** | 71.13 **(0)** | 73.19 **(0.11)**
 :red_circle: | app/client/src/utils/migrations/ModalWidget.ts | 78.38 **(-7.98)** | 84 **(-2.67)** | 100 **(0)** | 77.14 **(-8.57)**
 :green_circle: | app/client/src/widgets/ModalWidget/index.ts | 52.94 **(6.27)** | 0 **(0)** | 0 **(0)** | 52.94 **(6.27)**</details>

### CODE REVIEW

**Review by jsartisan — APPROVED** [review]

**Comment by jsartisan** [comment]
@techbhavin preview build is failing. can you check it once? not able to see any dp for this pr.

**Comment by YogeshJayaseelan** [comment]
@techbhavin Tested this PR and please find the status below,

Issue 1 - By default the button variant for the icon button is secondary - This should be tertiary by default as we are showing a transparent X icon 

https://www.loom.com/share/371a5ff4c36a4555bbd6529f538c7022

Issue 2 - The default hover colour is blue on the icon button 

https://www.loom.com/share/ee21f49d137947b99a13d3eb87accb11

Issue 3 - Migration - For the older apps the X icon still remains the same and it is not changing into Icon widget 

https://www.loom.com/share/526f5d344f414a689f43430a48c132bc

**Review by jsartisan — APPROVED** [review]

**Comment by jsartisan** [comment]
LGTM!

**Comment by YogeshJayaseelan** [comment]
@techbhavin Tested the fixes and they are working as expected.

**Pull request merged**
