### PR TITLE
Show error callout in api pane when there is an error

### LINKED ISSUE #4742: [Bug] Non 2xx Errors in API should always show the debug CTA

### PR DESCRIPTION
**Pull request by akash-codemonk**
## Description
Show error callout in api pane when there is an error. Previously the user had the option to close the Callout and once closed it would not appear again as the state was stored in localStorage. 

Fixes #4742 

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
Manually

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/show-debug-api-pane 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 51.77 **(0)** | 33.07 **(0.01)** | 29.7 **(0)** | 52.25 **(0)**
 :green_circle: | app/client/src/components/editorComponents/ApiResponseView.tsx | 52.86 **(2.86)** | 35.48 **(2.69)** | 0 **(0)** | 54.41 **(1.55)**</details>

### CODE REVIEW

**Review by rishabhsaxena — COMMENTED** [review]
@akash-codemonk 
Just to confirm, the issue says about the debug  CTA, it's not related to the debug cta on the error notification ?

**Review by rishabhsaxena — DISMISSED** [review]

**Comment by akash-codemonk** [comment]
> @akash-codemonk
> Just to confirm, the issue says about the debug CTA, it's not related to the debug cta on the error notification ?

No it is about the CTA in the response body. Previously the user had the option to close the Callout and once closed it would not appear again as the state was stored in localStorage. With this PR it will show-up when there is an error while running.

**Review by rishabhsaxena — APPROVED** [review]

**Pull request merged**
