### PR TITLE
fix: Fix dropdown bug issue

### LINKED ISSUE #22576: GSheet Scope Drop Down Bug
Steps to reproduce:
1. Create a new google sheet data source 
2. Select Read/write all google sheets scope from drop-down menu
3. Now edit the data source name 
4. After changing the data source name click on whitespace anywhere.
5. Issue it will change the user selected scope to default one.

### PR DESCRIPTION
**Pull request by Irongade**
The saas datasource editor page re-renders whenever the name of the datasource is changed causing selected options to be cleared off. This PR fixes that issue.

#### PR fixes following issue(s)
Fixes #22576

- Bug fix (non-breaking change which fixes an issue)

- [x] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Test Plan
1)  Navigate to create new DS 
2) Rename the DS and click on white space 
3) Select scope to authorize the datasource and then change the name of the datasource and click on white space 
4) Rename the DS and click on white space  and check if the scope of other datasource gets changed 
5) Rename the DS and click on the white space click on the back button to ensure the pop-up is displayed to the user
6) rename the DS from entity explore and observe the scope of the same DS and other DS 
7) Ensure user is able to create new API 
8) Ensure user is able to edit the DS  (Scope , authorise to different Gmail Account)

#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [x] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [x] Test plan has been peer reviewed by project stakeholders and other QA members
- [x] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Comment by tanvibhakta** [comment]
No ads review necessary

**Review by AmanAgarwal041 — APPROVED** [review]

**Pull request merged**
