### PR TITLE
fix: Disable console logs for internal operation

### PR DESCRIPTION
**Pull request by Rishabh-Rathod**
## Description

To determine if a JSObject function is sync or async, we run a `functionDeterminer.isFunctionAsync` check that actually runs the raw user function, this way we find out if a trigger was present or not. When running the raw user function internally, we should disable console logs to make sure users don't see those logs. 

TL;DR:- Changes in this PR disable the console log for the internal run of JSObject functions.

Fixes https://github.com/appsmithorg/appsmith/issues/19533

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual
- Jest
- Cypress

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by Rishabh-Rathod — COMMENTED** [review]
LGTM. ( Self-review )

**Review by rimildeyjsr — APPROVED** [review]

**Pull request merged**
