### PR TITLE
feat: Add widget responsiveness and conversion algorithm

### PR DESCRIPTION
**Pull request by prsidhu**
## Description

QA branch for mobile responsiveness

### CODE REVIEW

**Comment by aswathkk** [comment]
@prsidhu Preview is available at https://appsmith-goutham-appsmithcom-get-appsmith.vercel.app/

You need to check the 7th step in vercel-local-build to see the URL

**Comment by aswathkk** [comment]
DP Link: https://appsmith-ojudnw5pt-get-appsmith.vercel.app/user/login

**Review by marks0351 — APPROVED** [review]

**Pull request merged**
