### PR TITLE
fix: resetWidget doesn't reset child widgets inside a list

### LINKED ISSUE #30116: [Bug]: Reset widget method is failing and inconsistent across widgets
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Resetting widget method is failing and inconsistent across widgets

### Steps To Reproduce

Example 1:

1. D&D a button widget and set its onClick function to reset a List widget. Let `reset children` be set to `true`
2. Drop an input widget within the list widget and add some value to it
3. Notice that onClick of the button, the child widget doesnt get reset

Example 2:

1. D&D a button widget and set its onClick function to reset a container widget. Let `reset children` be set to `false`
2. Drop an input widget within the container widget and add some value to it
3. Notice that onClick of the button, the child widget also gets reset despite it being set to false

### Public Sample App

_No response_

### Environment

Production

### Issue video log

https://www.loom.com/share/bfed4a19fed9413a92f0b637f881454c?sid=8311772d-ebb9-4992-ae1b-a20e712181fb

### Version

v1.9.58

### PR DESCRIPTION
**Pull request by arunvjn**
These bug was introduced in #29151, where we moved the resetWidget logic to the worker thread, to support restoration of default values in meta fields (post setter methods invocation).
>
>
#### PR fixes following issue(s)
Fixes #30116 

#### Type of change
- Bug fix (non-breaking change which fixes an issue)
>
#### How Has This Been Tested?
- [x] Manual
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

## Summary by CodeRabbit

- **Refactor**
  - Streamlined evaluation logic for better performance and maintainability.
- **New Features**
  - Enhanced widget reset functionality with improved cache handling.
  - Upgraded library installation process for JavaScript libraries within the app, ensuring more reliable and consistent performance.

### CODE REVIEW

**Comment by laveena-en** [comment]
Tested and verified! Changes look good to me.

**Review by rishabhrathod01 — DISMISSED** [review]
LGTM

**Review by rishabhrathod01 — APPROVED** [review]
LGTM

**Pull request merged**
