### PR TITLE
feat: building block canvas dragging

### LINKED ISSUE #31315: [Feature]: Improve Partial Import Export (PIE) API to allow adding building blocks to apps.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

The primary aim of this feature is to empower users by enabling them to seamlessly integrate building blocks along with their associated components (queries, JavaScript, datasources, and widgets) into their existing applications through drag-and-drop functionality.

**Proposal**
To achieve this objective, the proposed approach involves enhancing the PIE API to facilitate backend operations. This enhancement will allow the backend to efficiently add queries, JavaScript functions, and datasources to existing applications. Subsequently, the updated application's widget structure will be transmitted back to the client for rendering, ensuring a smooth and cohesive user experience.

### Why should this be worked on?

This process is critical for the successful implementation of building blocks in the explorer and the client side cannot effectively manage the operations of queries, JS and datasources within an App. These processes are better handled on the backend.

### PR DESCRIPTION
**Pull request by AnaghHegde**
## Description
The primary aim of this feature is to empower users by enabling them to seamlessly integrate building blocks along with their associated components (queries, JavaScript, datasources, and widgets) into their existing applications through drag-and-drop functionality.
This PR adds change to create a Partial IE engine to download the json file from CS, then add all DS, JS, Queries and Custom JS Libs. Also handle the name refactoring in js, queries and dsl and then return modified widget dsl to frontend.

#### PR fixes following issue(s)
Fixes #31315 

#### Type of change
- New feature (non-breaking change which adds functionality)

#### How Has This Been Tested?
- [ ] Manual
- [ ] JUnit

#### Test Plan
https://www.notion.so/appsmith/Test-planning-Drag-and-drop-building-blocks-030b0a5e944a478c9598ad65ba5096e2?pm=c

#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

## Summary by CodeRabbit

- **New Features**
	- Added `BuildingBlockDTO` import.
	- Added `ApplicationTemplateService` and `WidgetRefactorUtil` services.
	- Added `importBuildingBlock` method.
	- Introduced partial import functionality for building blocks.
	- Added capability to refactor widget and action names during import to avoid name clashes.

- **Enhancements**
	- Improved logic for importing resources within a page.
	- Enhanced name refactoring in DSL bindings to ensure consistency across the application.

- **Refactor**
	- Updated methods to handle new import structures and services more efficiently.

- **Tests**
	- Added new tests to verify partial imports and name refactoring functionalities.

### CODE REVIEW

**Review by NilanshBansal — APPROVED** [review]
Backend Code LGTM

**Comment by NilanshBansal** [comment]
@AnaghHegde can you share steps on how to test this on dp?

**Comment by AnaghHegde** [comment]
@NilanshBansal This can be tested via postman, since this is a new API. The FE work is still pending. Since this a new API, this will be tested in the same DP where we have the FE code is present.

**Pull request merged**
