### PR TITLE
fix: Input widget as number type 0 as default value

### LINKED ISSUE #7246: [Bug] Input Widget does not show default value if it is 0 for number type
Input Widget does not show default value if it is 0 for number type

### Steps to reproduce the behavior:

1. Drop an input widget on the canvas
2. Set the input type to number and set the default value to 0
3. Notice the input widget does not show 0 even on refresh.

### PR DESCRIPTION
**Pull request by ashit-rath**
## Description

Fixes #7246 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
Manual

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/7246-input-widget-default-value-0 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 54.87 **(0.01)** | 36.69 **(0.06)** | 34.26 **(0.03)** | 55.41 **(0.02)**
 :green_circle: | app/client/src/constants/messages.ts | 75.04 **(0.13)** | 100 **(0)** | 25.59 **(0.4)** | 81.23 **(-0.06)**
 :green_circle: | app/client/src/widgets/InputWidget/widget/index.tsx | 61.76 **(8.22)** | 41.43 **(18.57)** | 68.18 **(4.54)** | 63.92 **(8.6)**</details>

### CODE REVIEW

**Review by jsartisan — APPROVED** [review]

**Review by somangshu — APPROVED** [review]

**Comment by ashit-rath** [comment]
@somangshu Can you verify [this](https://github.com/appsmithorg/appsmith/issues/7246#issuecomment-917910210)?

**Review by jsartisan — APPROVED** [review]

**Review by jsartisan — DISMISSED** [review]

**Comment by vivekverma2312** [comment]
@ashit-rath After I remove the default text as “0” still the value is coming on input widget.
https://www.loom.com/share/4798e845d7b64f17a227a313eef5a539

**Review by vicky-primathon — APPROVED** [review]
Looks good to me

**Comment by ashit-rath** [comment]
@vivekverma2312 The issue has been addressed, can you do a round of testing and approve?

> @ashit-rath After I remove the default text as “0” still the value is coming on input widget.
> [LOOM DEMO](https://www.loom.com/share/4798e845d7b64f17a227a313eef5a539)

**Pull request merged**
