### PR TITLE
fix: checkbox column misalignment on table widget

### LINKED ISSUE #21790: [Bug]-[50]:Checkbox type column on a table widget does not center icon even when alignment is centered
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

We see the checkbox icon right aligned when column type is a checkbox and alignment is centered. Applicable for other columns types like icon, image etc...

### Steps To Reproduce

image
image

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by SaiCharanChetpelly31**
Fixes #21790
_or_  
Fixes [Issue URL](https://github.com/appsmithorg/appsmith/issues/21790)

 Introduced a new prop called isFullWidth for the CheckboxComponent and pass this prop to this styled component CheckboxContainer. The isFullWidth is an optional boolean property whole default value would be true.
 
Added screenshot for reference.
image

## Summary by CodeRabbit

- **New Features**
  - Introduced a full-width option for checkboxes to enable better styling flexibility.
  
- **Tests**
  - Added new test cases to verify checkbox styling properties in tables.

### CODE REVIEW

**Comment by riodeuno** [comment]
@SaiCharanChetpelly31 In the previous PR, I see that you've added an update to the cypress test. However, in this PR, those changes are not available. May I know the reason behind this?

**Comment by SaiCharanChetpelly31** [comment]
> @SaiCharanChetpelly31 In the previous PR, I see that you've added an update to the cypress test. However, in this PR, those changes are not available. May I know the reason behind this?

@riodeuno I missed adding cypress test. I will add it and push it now.

**Comment by SaiCharanChetpelly31** [comment]
> > @SaiCharanChetpelly31 In the previous PR, I see that you've added an update to the cypress test. However, in this PR, those changes are not available. May I know the reason behind this?
> 
> @riodeuno I missed adding cypress test. I will add it and push it now.

@riodeuno I added cypress test. Im getting an error while commiting the changes. Do you know the reason?
image

**Comment by somangshu** [comment]
I am building the deploy preview for this again. 
@ramsaptami have you checked this out. Do you think this fix is right?
I dont understand why we are introducing a new prop to solve a bug. I am very hesitant to promote this PR.

**Comment by ramsaptami** [comment]
build action keeps failing for some reason @somangshu

**Review by riodeuno — APPROVED** [review]

**Review by ramsaptami — APPROVED** [review]

**Comment by somangshu** [comment]
@riodeuno the tests have [passed internally](https://github.com/appsmithorg/appsmith/pull/34231). Shall we merge this in?

cc @ramsaptami

**Comment by SaiCharanChetpelly31** [comment]
@somangshu @ramsaptami Could you merge this pr if every thing is okay?

**Comment by somangshu** [comment]
Things looks good here. I am merging this in.

**Pull request merged**
