### PR TITLE
feat: sniping mode functionality moved to widget level

### LINKED ISSUE #8667: [Feature]: Add sniping mode support for newer widgets
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

1. Add support for newer widgets including chart widget
2. Add automated test cases.

### Why should this be worked on?

Currently it only supports a few widgets

### PR DESCRIPTION
**Pull request by pranavkanade**
## Description
Moved the sniping mode functionality support at widget level, and updated the test cases

Fixes #8667

## Type of change
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
- Automated cypress tests

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/sniping-mode-refactor 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 55.63 **(0.09)** | 37 **(-0.01)** | 35.77 **(0.01)** | 55.98 **(0.1)**
 :red_circle: | app/client/src/actions/propertyPaneActions.ts | 81.25 **(-3.37)** | 100 **(0)** | 40 **(-10)** | 75 **(3.57)**
 :green_circle: | app/client/src/ce/constants/messages.ts | 77.09 **(0.08)** | 100 **(0)** | 32.06 **(0.21)** | 81.99 **(0.09)**
 :red_circle: | app/client/src/components/editorComponents/WidgetNameComponent/index.tsx | 96.88 **(-0.09)** | 83.64 **(0)** | 100 **(0)** | 96.77 **(-0.11)**
 :green_circle: | app/client/src/sagas/SnipingModeSagas.ts | 38.46 **(18.46)** | 2.08 **(-1.05)** | 28.57 **(-11.43)** | 40.68 **(19.89)**
 :green_circle: | app/client/src/selectors/commentsSelectors.ts | 85.25 **(1.64)** | 64.71 **(2.95)** | 73.33 **(0)** | 90.59 **(2.35)**
 :red_circle: | app/client/src/utils/WidgetFactory.tsx | 71 **(-2.91)** | 66.67 **(-3.92)** | 61.11 **(-3.6)** | 71 **(-2.91)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.71 **(-0.23)** | 40.83 **(-0.84)** | 36.21 **(0)** | 56.74 **(-0.25)**
 :green_circle: | app/client/src/widgets/BaseWidget.tsx | 79.69 **(0.83)** | 46.81 **(2.37)** | 75.76 **(0.76)** | 78.86 **(0.89)**
 :green_circle: | app/client/src/widgets/CanvasWidget.tsx | 96 **(0.08)** | 66.67 **(0)** | 100 **(0)** | 97.87 **(0.04)**
 :green_circle: | app/client/src/widgets/ListWidget/index.ts | 11.39 **(2.3)** | 0 **(0)** | 0 **(0)** | 12.5 **(2.5)**
 :green_circle: | app/client/src/widgets/ModalWidget/index.ts | 50 **(3.33)** | 0 **(0)** | 0 **(0)** | 50 **(3.33)**
 :green_circle: | app/client/src/widgets/TableWidget/index.ts | 47.06 **(3.31)** | 100 **(0)** | 0 **(0)** | 47.06 **(3.31)**
 :green_circle: | app/client/src/widgets/TabsWidget/index.ts | 35.29 **(4.04)** | 0 **(0)** | 0 **(0)** | 35.29 **(4.04)**</details>

### CODE REVIEW

**Review by rishabhsaxena — DISMISSED** [review]
This has already been reviewed, approval for a minor commit added

**Comment by mohanarpit** [comment]
Test result: https://github.com/appsmithorg/appsmith/runs/4064269697

**Review by riodeuno — APPROVED** [review]

**Review by rishabhsaxena — DISMISSED** [review]

**Comment by hiteshjoshi** [comment]
@pranavkanade was this PR not merged? is #8667 still open?

**Pull request closed without merging**
