### PR TITLE
fix: Map pin does not center when location is changed and centering option is turned on

### LINKED ISSUE #9844: [Bug]: Map pin does not center when location is changed and centering option is turned on
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Pinned location should move when location changes on the map when `Map & marker centering` is turned on. Currently, the pin moves as location changes but manual intervention is needed to center or even bring the pin into view since it does not auto-adjust.

[LOOM DEMO](https://www.loom.com/share/034a71830c514ca4919330cb6d925a8d)

### Steps To Reproduce

1. Open up map widget with map & marker centering turned on and bind location using `watchPosition()` on a button trigger as seen in the video
2. Change user location using sensor
3. Observe the pin position move but map view remain the same - this needs to dynamically change as per setting

### Environment

Release

### Version

Cloud

### PR DESCRIPTION
**Pull request by wmdev0808**
## Description

- Pinned location should move when location changes on the map when Map & marker centering is turned on. Currently, the pin moves as location changes but manual intervention is needed to center or even bring the pin into view since it does not auto-adjust.
- Update center meta property accordingly when defaultMarkers or mapCenter properties were changed

Fixes #9844 

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Test A
- Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/9844-map-pin-center 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 55.06 **(-0.01)** | 36.56 **(-0.01)** | 34.49 **(0)** | 55.57 **(-0.01)**
 :red_circle: | app/client/src/selectors/commentsSelectors.ts | 83.61 **(-1.64)** | 61.76 **(-2.95)** | 73.33 **(0)** | 88.24 **(-2.35)**
 :red_circle: | app/client/src/widgets/MapWidget/widget/index.tsx | 44.78 **(-3.61)** | 6.9 **(-2.19)** | 33.33 **(0)** | 44.62 **(-3.71)**</details>

### CODE REVIEW

**Comment by somangshu** [comment]
@YogeshJayaseelan @shwetha-ramesh please take feedback from @ramsaptami to understand how to test this properly

**Review by Tooluloope — APPROVED** [review]
LGTM code wise

**Comment by chandannkumar** [comment]
Map is not loading on Deploy preview


@wmdev0808 can u please help!

**Comment by wmdev0808** [comment]
> Map is not loading on Deploy preview
> 
>  @wmdev0808 can u please help!

I've run the PR on my local and I could not reproduce the issue.
It seems to be deploy problem.

**Comment by ramsaptami** [comment]
It's something to do with the Google Maps API, it's not allowing maps to appear on deploy preview. Happened on Netlify too apparently. So can this be pushed to release and I'll test it there?

**Pull request merged**
