### PR TITLE
Moving all toast messages to messages.ts file

### LINKED ISSUE #2797: Improve client-side error messages across the board

### PR DESCRIPTION
**Pull request by mohanarpit**
Added a function called `createMessage` to format the messages correctly. This way we will have a central way to review & update all messages being displayed to a user.

## Description

Fixes #2797

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by hetunandu** [comment]
We can use Template literals instead of JS string formatting.. Making that change

**Comment by mohanarpit** [comment]
> We can use Template literals instead of JS string formatting.. Making that change

I did check out template literals but I couldn’t figure out how to use it in the generic function

**Comment by hetunandu** [comment]
Also just realising that util module is only available in node and not in all browsers.

**Comment by mohanarpit** [comment]
> Also just realising that util module is only available in node and not in all browsers.

I tested these changes on Firefox, Chrome & Safari. Do you know of any particular browser versions where this library won't work? I was under the impression that this library is meant to introduce functions that aren't available in the browser's environment by default.

**Comment by ofpiyush** [comment]
Is something like https://www.npmjs.com/package/util worth adding or should we go with a more javascript-ey solution that looks like:

```
export const ERROR_ACTION_EXECUTE_FAIL = (actionName) => (`${actionName} action returned an error response`);

function createMessage(formatFn, ...args) {
  return formatFn(...args);
}

// Example usage:
createMessage(ERROR_ACTION_EXECUTE_FAIL, "Api1"); // Api1 action returned an error response

// Example 2:
ERROR_ACTION_EXECUTE_FAIL("Api1"); // Api1 action returned an error response
```

Even though `Example 2` works, I prefer `createMessage` kind of solution because that makes it easier for us to add translation or letting dev user override the message text.

**Comment by ofpiyush** [comment]
One use case I've come across is nested message.

In Oauth2 auth code error, we can have different error codes and the message can change based on the code.

```py
REST_API_AUTHORIZATION_FAILED = {
    "appsmith_error" : "Appsmith encountered some error, please try again later.",
    "access_denied": "Check credentials.",
    "__fallback__": "Some generic fallback unknown error message.",
}
```

**Comment by hetunandu** [comment]
The issue seemed to be around importing the messages.ts file in the worker (validation.ts) file. This has issues with functions cause of the way CRA adds workers in dev mode. This problem can only be solved when we eject out of CRA. Till then, I have refactored to keep the message in the validation file itself

**Review by hetunandu — APPROVED** [review]

**Pull request merged**
