### PR TITLE
fix: Select widget Value

### LINKED ISSUE #9102: [Bug]: Select Widget highlighted value selection doesn’t reflect in the binding
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

For the particular scenario where the select widget's default option is bound with the Table widget's selected row,
noticed this bug of Selection not working when selecting already highlighted value. 

[LOOM DEMO](https://www.loom.com/share/ab12f7171ad14b8dbe637c083a6d0178)

### Steps To Reproduce

1. Add Form on canvas and inside that Add Select Widget
2. Add TableWidget and TextWidget on canvas 
3. Select Widget, Set Default option as `{{Table1.selectedRow.step}}` & `options` as 
```
[
  {
    "label": "#1",
    "value": "#1"
  },
 {
    "label": "#2",
    "value": "#2"
  }
]
```
4. Make `Text` of Text Widget as `{{Select1.selectedOptionValue}}`
5. Now Select 3rd Row, then select highlighted option in the Select widget and see the Text widget value.
6. If you don't see an error select 1st or 2nd row of the Table and then select 3rd row again and repeat Step 5.   

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by Tooluloope**
## Description

 Fix selected option value when defaultValue changes
Fixes #9102 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/selectedOptionValue-from-Select-widget 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 55.06 **(0.01)** | 36.93 **(0.02)** | 33.92 **(0.01)** | 55.57 **(0)**
 :green_circle: | app/client/src/widgets/DropdownWidget/widget/index.tsx | 73.33 **(0.41)** | 43.24 **(19.71)** | 64.29 **(0.65)** | 72.73 **(0.64)**</details>

### CODE REVIEW

**Review by jsartisan — APPROVED** [review]

**Comment by YogeshJayaseelan** [comment]
@Tooluloope Verified this PR and it is working as expected

**Pull request merged**
