### PR TITLE
fix: Add a charts layout builder to progressively hide chart elements

### LINKED ISSUE #26189: [Bug]: Fix layout issues for Chart Widget when the chart widget size is small
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

1. Users should have the option to choose to show/hide label on series data.
2. The allow scroll property shouldn't overlap with chart data when chart widget size is small.
3. The legend shouldn't overlap with chart widget when chart widget size is small.
4. Long names should work fine for small chart widget size.
5. Title, legend, XAxis Bar, YAxisBar, allow scroll bar should hide gradually as the chart size decreases.
6. If chart title isn't present, its space should be used up by rest of the chart

### Steps To Reproduce

1. Dnd a chart widget on canvas.
2. Reduce the size of the chart widget to very small.
3. Notice that the legend, allow scroll and data point labels shouldn't overlap

Relevant Slack Thread : https://theappsmith.slack.com/archives/C0341RERY4R/p1691488244791999

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by rajatagrawal**
Fixes #26189

### CODE REVIEW

**Review by sbalaji1192 — DISMISSED** [review]

**Comment by chandannkumar** [comment]
Observations:
1. No option to scroll the graph when chart widget is smaller in size.
https://www.loom.com/share/933f68b7b54c4e67bf63b9f76f37c123?sid=25204fbd-c2bd-497b-9d3f-4904c502c4bf 

2. Tooltip size is quite bigger to fit in smaller chart widgets. Since the tooltip is not visible when widget is smaller
https://www.loom.com/share/fef4b014373b491492071f52ccbc712e?sid=24986ee5-cce8-419b-ba4a-b57b8965d5a6

3. The y-axis and it's label name takes too much space in smaller chart widget. At some point, half of the widget shows the graph and other half focus to show only y-axis details
https://www.loom.com/share/06bdecde876c4ec881f4c542c20fa04e?sid=252f42e9-da2d-4903-a088-ea0c2eecb372

cc: @rajatagrawal @dilippitchika

**Comment by rajatagrawal** [comment]
> Observations:
> 
> 1. No option to scroll the graph when chart widget is smaller in size.
>    https://www.loom.com/share/933f68b7b54c4e67bf63b9f76f37c123?sid=25204fbd-c2bd-497b-9d3f-4904c502c4bf
> 2. Tooltip size is quite bigger to fit in smaller chart widgets. Since the tooltip is not visible when widget is smaller
>    https://www.loom.com/share/fef4b014373b491492071f52ccbc712e?sid=24986ee5-cce8-419b-ba4a-b57b8965d5a6
> 3. The y-axis and it's label name takes too much space in smaller chart widget. At some point, half of the widget shows the graph and other half focus to show only y-axis details
>    https://www.loom.com/share/06bdecde876c4ec881f4c542c20fa04e?sid=252f42e9-da2d-4903-a088-ea0c2eecb372
> 
> cc: @rajatagrawal @dilippitchika

The observation are non critical with respect to the bug fixes. I can address them in another bug fix.

**Pull request merged**
