### PR TITLE
chore: Update config label in Rest API datasource config page

### LINKED ISSUE #11106: [Bug]: Update config label in Rest API datasource config page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Update  label`Send client credentials with` to `Send client credentials with (on refresh token):` under the `Advanced settings` tab that appears for `Oauth` + `Authorization Code` setting.

### Steps To Reproduce

1. Create new Rest API datsaource. 
2. Set authentication typo to OAuth. 
3. Select Authorization code from dropdown. 
4. Unfurl Advanced settings dropdown. See the config names. 

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by RishiKumarRay**
## Description

Update the Label of the `refreshTokenClientCredentialsLocation` dropdown

Fixes #11106

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by danieldare — APPROVED** [review]

**Comment by RishiKumarRay** [comment]
@danieldare looks like the test are not performed yet

**Comment by RishiKumarRay** [comment]
@danieldare do i need to make anymore changes as it looks like there are some more failed tests?

**Comment by danieldare** [comment]
> @danieldare do I need to make any more changes as it looks like there are some more failed tests?

Your changes look good to me. I'm looking into the checks.

**Comment by RishiKumarRay** [comment]
@sumitsum there are some checks which haven't started , i was wondering when will this be merged :)

**Pull request merged**
