### PR TITLE
fix: set button color and remove button style for button, IconButton, Menubutton

### LINKED ISSUE #7046: [Bug] Button widget: Changes in the enhancements
## Description

- `Button styles` should be called as `Button colours`
- The button style changes are linked to the API pane button, is this linked, we should change this if so. (HIGH)
- Form buttons are also seeing these changes probably because of the changes in the core component (HIGH)

### Design Changes:
- Button style > secondary colour palette needs to change
- In button prop pane, The border radius and box shadow attribute need to consume lesser space

## Important Details

- Version: [Cloud]
- OS: [MacOSX]
- Browser [chrome]
- Environment [release]

### LINKED ISSUE #7260: [Bug] Form widget buttons don't respond to styling options
## Description
The form buttons retain only primary styling and don't respond to button styling options. The new button styling options haven't been applied to them.
Old form buttons were updated to primary button style automatically.

Reported by a user on intercom.

### LINKED ISSUE #7283: [Bug] TypeError: Cannot read properties of undefined (reading 'outline')
Sentry Issue: [APPSMITH-134](https://sentry.io/organizations/appsmith/issues/2636050771/?referrer=github_integration)

```
TypeError: Cannot read properties of undefined (reading 'outline')
  at getCustomHoverColor (components/designSystems/blueprint/ButtonComponent.tsx:76:53)
  at id (components/designSystems/blueprint/ButtonComponent.tsx:228:13)
  at he (../../src/models/Keyframes.js:20:51)
  at isCompositeComponent (../../src/utils/isStaticRules.js:6:54)
  at isCompositeComponent (../../src/models/StyledComponent.js:194:9)
...
(45 additional frame(s) were not displayed)
```

### LINKED ISSUE #7367: [Bug] TypeError: Cannot read properties of undefined (reading 'solid')
Sentry Issue: [APPSMITH-131](https://sentry.io/organizations/appsmith/issues/2634183603/?referrer=github_integration)

```
TypeError: Cannot read properties of undefined (reading 'solid')
  at getCustomBackgroundColor (components/designSystems/blueprint/ButtonComponent.tsx:116:11)
  at id (components/designSystems/blueprint/ButtonComponent.tsx:206:13)
  at he (../../src/models/Keyframes.js:20:51)
  at isCompositeComponent (../../src/utils/isStaticRules.js:6:54)
  at isCompositeComponent (../../src/models/StyledComponent.js:194:9)
...
(45 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by Tooluloope**
## Description

set button color and remove button style for button, IconButton, Menubutton
Fixes #7046, 
Fixes #7260,
Fixes #7367,
Fixes #7283,
Fixes #7260 

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/button-widget-enhancements 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 54.89 **(0.04)** | 37.05 **(0.32)** | 33.89 **(0.04)** | 55.5 **(0.04)**
 :red_circle: | app/client/src/utils/DSLMigrations.ts | 74.4 **(-3.2)** | 65.61 **(-1.92)** | 70.45 **(0.68)** | 74.22 **(-3.06)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 50.47 **(-0.24)** | 38.26 **(-0.87)** | 36.21 **(0)** | 55.08 **(-0.27)**
 :green_circle: | app/client/src/widgets/ButtonWidget/component/index.tsx | 55.26 **(10.21)** | 36.97 **(15.58)** | 52 **(16)** | 53.54 **(10.68)**
 :green_circle: | app/client/src/widgets/ButtonWidget/widget/index.tsx | 70.73 **(5.42)** | 42.86 **(5.36)** | 58.33 **(-1.67)** | 70 **(5.42)**
 :green_circle: | app/client/src/widgets/FilePickerWidgetV2/component/index.tsx | 54.55 **(2.17)** | 0 **(0)** | 20 **(0)** | 52.38 **(2.38)**
 :green_circle: | app/client/src/widgets/FilepickerWidget/component/index.tsx | 54.55 **(2.17)** | 0 **(0)** | 20 **(0)** | 52.38 **(2.38)**
 :red_circle: | app/client/src/widgets/FormButtonWidget/widget/index.tsx | 64.71 **(-6.02)** | 19.05 **(-12.95)** | 62.5 **(-10.23)** | 63.64 **(-6.36)**
 :green_circle: | app/client/src/widgets/IconButtonWidget/component/index.tsx | 31.25 **(0)** | 7.41 **(3.33)** | 0 **(0)** | 43.48 **(0)**
 :green_circle: | app/client/src/widgets/IconButtonWidget/widget/index.tsx | 50 **(1.61)** | 0 **(0)** | 60 **(0)** | 50 **(1.72)**
 :green_circle: | app/client/src/widgets/MenuButtonWidget/component/index.tsx | 28 **(3.36)** | 15.63 **(9.01)** | 0 **(0)** | 31.82 **(3.95)**
 :green_circle: | app/client/src/widgets/MenuButtonWidget/widget/index.tsx | 60 **(12.63)** | 0 **(0)** | 42.86 **(6.5)** | 60.87 **(13.65)**
 :green_circle: | app/client/src/widgets/TableWidget/widget/index.tsx | 26.87 **(0.19)** | 5.86 **(-0.04)** | 26.92 **(0)** | 26.63 **(0.2)**
 :red_circle: | app/client/src/widgets/TableWidget/widget/propertyConfig.ts | 38.3 **(-0.43)** | 10.2 **(0)** | 64.52 **(-1.11)** | 39.71 **(-0.44)**</details>

### CODE REVIEW

**Comment by somangshu** [comment]
@jsartisan @Tooluloope we need the final conclusion here

**Comment by jsartisan** [comment]
@Tooluloope the default menu widget state's background color is wrong on the DP.

**Review by jsartisan — APPROVED** [review]
LGTM!

**Comment by Tooluloope** [comment]
@somangshu should this still not be merged?

**Comment by somangshu** [comment]
@Tooluloope what is the migration about here

**Comment by Tooluloope** [comment]
> @Tooluloope what is the migration about here

Moving colors selected in `buttonStyle` to `buttonColor`

**Comment by aswathkk** [comment]
@Tooluloope I will take care of this PR from here onward.

**Review by somangshu — APPROVED** [review]
Approving to run tests

**Review by aswathkk — APPROVED** [review]
Approving to run tests

**Comment by somangshu** [comment]
@aswathkk please request for the QA on this soon. We need to ship this in time. Also do link any critical issues missing from here

**Comment by aswathkk** [comment]
@somangshu I was unable to connect this with #7260 I have moved it to needs QA

**Comment by somangshu** [comment]
> @somangshu I was unable to connect this with #7260 I have moved it to needs QA

@aswathkk For future reference once you add it in the description it works.

**Review by jsartisan — DISMISSED** [review]

**Comment by vivekverma2312** [comment]
1. JS Option should be available for button colour 
2. Migration issues: Multiple button appears to be invisible 
    1. Buttons: Danger, warning, secondary, Info
    2. Menu Button: Primary, secondary
    3. Icon button: Reset to default colour (Green)
    4. No default colour is showing for button and menu widget
Release:
Screenshot 2021-09-21 at 12 33 03 PM

Deploy Preview:
Screenshot 2021-09-21 at 12 33 12 PM

**Review by aswathkk — APPROVED** [review]
Approving to run tests

**Comment by aswathkk** [comment]
@vivekverma2312 I couldn't see JS editable option anywhere else for background color. Are you sure about it?

**Comment by vivekverma2312** [comment]
> @vivekverma2312 I couldn't see JS editable option anywhere else for background color. Are you sure about it?

I will raise a separate Enhancement for Button color and Background color.

**Comment by vivekverma2312** [comment]
@aswathkk Deploy preview is tested and working fine.

**Review by jsartisan — COMMENTED** [review]
LGTM!

**Review by somangshu — APPROVED** [review]
Approving to re-run the workflow

**Review by aswathkk — APPROVED** [review]
Approving to run tests

**Review by aswathkk — APPROVED** [review]
Approving to run tests

**Review by aswathkk — APPROVED** [review]
Approving to run tests

**Review by somangshu — APPROVED** [review]
Approving to run tests

**Review by aswathkk — APPROVED** [review]
Approving to run tests

**Pull request merged**
