### PR TITLE
fix/tabs widget corners

### LINKED ISSUE #990: [Bug]: Tab widget needs to follow same style as container widget
## Summary
The tab widget should have the same rounded corners that the container widget does

### PR DESCRIPTION
**Pull request by sumanthyedoti**
Fixes #990 

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by Nikhil-Nandagopal** [comment]
@sumanthyedoti I see 2 problems
The tab has a weird red outline and no shadow
Screenshot 2020-11-03 at 11 25 10 AM

**Review by Nikhil-Nandagopal — CHANGES_REQUESTED** [review]
I see some fixes needed in the UI

**Comment by sumanthyedoti** [comment]
@Nikhil-Nandagopal  So sorry about that. Missed to remove the test border. Pushing without that. 

**About 'no shadow':** 
- I was thinking to ask about that and open a new issue if it does not exist already.
- There is some weirdness in Tab 1. This is from **release** branch.
- Shadow comes in Tab 2 and works fine. 
- *And the major issue is, could not add other elements into Tab 1*

**Comment by hetunandu** [comment]
Also need to look into the case where tabs are not shown. In such a scenario it should look exactly like a container

**Comment by Nikhil-Nandagopal** [comment]
> @Nikhil-Nandagopal So sorry about that. Missed to remove the test border. Pushing without that.
> 
> **About 'no shadow':**
> 
> * I was thinking to ask about that and open a new issue if it does not exist already.
> * There is some weirdness in Tab 1. This is from **release** branch.
> * Shadow comes in Tab 2 and works fine.
> * _And the major issue is, could not add other elements into Tab 1_

@sumanthyedoti we're fixing the issue with not being able to add elements.
You're right about the tab1 / tab2 not matching issue, this was missed.

**Comment by Nikhil-Nandagopal** [comment]
@sumanthyedoti 
There is still something wrong with the overall style of the tab widget. I can see a sharp edge protruding from the right of the widget

**Comment by sumanthyedoti** [comment]
@Nikhil-Nandagopal Will check why happening

@hetunandu Does that mean deleting all the Tabs? Could not delete the only existing Tab i.e; the last Tab to delete

**Comment by hetunandu** [comment]
> @hetunandu Does that mean deleting all the Tabs? Could not delete the only existing Tab i.e; the last Tab to delete
Tabs Widget has a setting to disable "tabs" and control the switching between tabs via code (default tab) This looks visually different and should be handled as well

Screenshot 2020-11-03 at 2 42 30 PM

**Comment by sumanthyedoti** [comment]
@hetunandu 
Seems like for additional Tabs which are added by user, the prop is [`containerStyle: "none"`](https://github.com/appsmithorg/appsmith/blob/dcc30b31d28937182e04157680058d1ab0549406/app/client/src/widgets/TabsWidget.tsx#L109)

For default tabs (Tab 1 and Tab 2), I guess it is taking `containerStyle: "card"`. 
[`const containerStyle = props.containerStyle || "card"`](https://github.com/appsmithorg/appsmith/blob/dcc30b31d28937182e04157680058d1ab0549406/app/client/src/components/designSystems/appsmith/ContainerComponent.tsx#L41)

I am having a hard time figuring out where the default Tabs are sourced from. Can you help with that, please?

**Comment by hetunandu** [comment]
Not sure about the container styles. Can you help in this @riodeuno ?

Default values are used to control widgets with other state in the app. So for tabs, you can switch tabs with another input like dropdown values. Check this video of how it works
https://www.loom.com/share/aa89279cf1ac42518d5fc51ba8b6adb8
As you can imagine, you can put any js logic in the default tab field to switch between tabs.

**Comment by sumanthyedoti** [comment]
@riodeuno  @hetunandu 
Thanks. It was a nice demo.
To reproduce what I am referring to:
- Add the third tab
- Switch between default Tab(1 or 2) and Tab 3
- Observe the container of tab content

For Tab 1 & 2 the container has rounded corners and shadow (`containerStyle: "card"`). For Tab 3, its `containerStyle: "none"`

**Comment by riodeuno** [comment]
@sumanthyedoti Thanks for noticing this issue. I can confirm that this issue exists. Canvas Widgets should not have rounded corners or shadows. I have a fix available in #1564 which once merged will remove the default rounded corners in Tab1 and Tab2 which you noticed.

The styles (rounded corners and borders) need to be applied to the Tabs Widget, just as it does for Container Widget and Form Widget. Individual tabs will not implement this as they are Canvas Widgets under the hood.

Let me know if you need more information regarding the approach.

**Comment by Nikhil-Nandagopal** [comment]
@sumanthyedoti I just wanted to call out that this was a great PR. The tabs look really good now. Thank you so much for your contribution 🥇

**Review by Nikhil-Nandagopal — APPROVED** [review]

**Pull request merged**
