### PR TITLE
Enable total number of rows and page size for server side pagination in table widget

### LINKED ISSUE #1578: [Feature] Enable num rows for server side pagination
## Summary

Tables with serverside pagination can be navigated infinitely. Having an option to specify the number of rows will allow us to determine the number of pages

### LINKED ISSUE #2230: [Feature] Allow users to configure a page size for server side pagination
## Motivation

This will allow us to disable the next page button if the page size is lower than the expected page size. Read more about the conversation here #2107 & #1578

### PR DESCRIPTION
**Pull request by vicky-primathon**
## Description
Enable number of rows and default page size for server side pagination in table widget

Fixes #1578
Fixes #2230 

## Type of change
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
- Cypress test that validates table data with api bindings, default page size and total records count

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: configure-table-data-rows-count 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 53.33 **(-0.03)** | 35.29 **(-0.04)** | 31.95 **(0)** | 53.85 **(-0.03)**
 :red_circle: | app/client/src/widgets/TableWidget/index.tsx | 9 **(-0.31)** | 0 **(0)** | 10.64 **(0)** | 9.6 **(-0.37)**</details>

### CODE REVIEW

**Review by somangshu — DISMISSED** [review]
Approving to run tests

**Review by somangshu — APPROVED** [review]
Approving to run tests

**Comment by somangshu** [comment]
@riodeuno need you approval here

**Review by somangshu — APPROVED** [review]

**Review by somangshu — APPROVED** [review]

**Review by mohanarpit — APPROVED** [review]

**Comment by somangshu** [comment]
@vicky-primathon `execution_param.spec.js` was fixed, can you merge once more.

@NandanAnantharamu kindly correct me if I am wrong

**Comment by NandanAnantharamu** [comment]
> @vicky-primathon `execution_param.spec.js` was fixed, can you merge once more.
> 
> @NandanAnantharamu kindly correct me if I am wrong

yes we have fixed this issue @somangshu

**Review by somangshu — APPROVED** [review]

**Pull request merged**
