### PR TITLE
feat: add progressbar widget

### LINKED ISSUE #3356: [Feature] Progress Bar widget
## Summary

Users need a widget to display the progress of a long-running task

## Figma Design Links:
[Icon Design](https://www.figma.com/file/ATfTB5F9Q7ZiI0yYckuXW7/Deprecated-Design-System?node-id=172%3A5437)
[Widget Design](https://www.figma.com/file/mxIUUL3LM363xWInQnhjDW/New-Widgets-Exploration?node-id=44%3A3054)

### PR DESCRIPTION
**Pull request by techbhavin**
## Description

> Create a ProgressBar Widget

Fixes #3356 

## Type of change

- New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: feature/progress-bar-widget 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 55.04 **(0.02)** | 36.46 **(0)** | 34.45 **(0.02)** | 55.57 **(0.02)**
 :red_circle: | app/client/src/icons/WidgetIcons.tsx | 61.73 **(-0.3)** | 100 **(0)** | 18.42 **(-0.5)** | 61.73 **(-0.3)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.71 **(-0.23)** | 40.83 **(-0.84)** | 36.21 **(0)** | 56.74 **(-0.25)**
 :sparkles: :new: | **app/client/src/widgets/ProgressBarWidget/constants.ts** | **100** | **100** | **100** | **100**
 :sparkles: :new: | **app/client/src/widgets/ProgressBarWidget/index.ts** | **100** | **100** | **100** | **100**
 :sparkles: :new: | **app/client/src/widgets/ProgressBarWidget/component/index.tsx** | **38.71** | **41.67** | **0** | **41.38**
 :sparkles: :new: | **app/client/src/widgets/ProgressBarWidget/widget/index.tsx** | **91.3** | **100** | **75** | **90.91**</details>

### CODE REVIEW

**Comment by vivekverma2312** [comment]
@techbhavin Few observations for progress bar widget
1. Default state of widget after drag and drop is not proper. Looks very similar to divider widget. It would be great if we set some default progress value.
2. Type and number of steps property is not available on property widget mentioned in figma design
3. Not able to resize the widget horizontally 
https://www.loom.com/share/77ab5682883d4e8bbf22ac65404c889b

**Comment by vivekverma2312** [comment]
@techbhavin Thanks for fixing the above issues. Observed few more issues after the fix.
1. Not sure why we are not showing `Show Result `property for `Indeterminate` type. I would suggest it's good to show result in both the types.
2. No limit is set for Number of steps. It does not show properly when we enter 0, 1 or 1000 as `Number of steps`. We should set a limit and show error message.
3. Progress did not work when I enter 10 in `Progress` property and 4 in `Number of steps`
4. When Set type as `Indeterminate` `Progress` as 65 and `Number of steps` as 4, progress bar show it as 70% highlighted. The last step should not be completely highlighted.
5. Page become unresponsive beyond certain number of value in Number of steps
https://www.loom.com/share/693d61b5092a431db3870c9bac31c289


Loom Video for issue 1-4: https://www.loom.com/share/11511ca530f1404c9948f01c54aaaf30

**Comment by shwetha-ramesh** [comment]
@techbhavin tested this PR wrt to the issues commented by @vivekverma2312. All looks good. However below I have mentioned two observations of mine.
1. When user enters decimal value in '''Number of steps''' widget breaks. Ideally an error message must be displayed
image

2. Also in [figma ](https://www.figma.com/file/mxIUUL3LM363xWInQnhjDW/New-Widgets-Exploration?node-id=44%3A3054) doc labels are seen next to the progress bar which is missing in DP.
image

**Comment by techbhavin** [comment]
@shwetha-ramesh   In your observation 
point 1: can you please give me the error message string so we can display it. 

point 2: here we are providing options for Fill Colour styles. so in that case we do not provide `PRIMARY`, `WARNING`, and `DANGER`.

**Comment by somangshu** [comment]
@shwetha-ramesh the labels you are seeing are to represent the color scheme for the developer. This is not an issue

cc @momcilo-appsmith @UXFalcon

**Comment by momcilo-appsmith** [comment]
Screenshot 2021-12-27 at 08 56 50

The text here is way too small. Can you guys try 14 px?

**Comment by vivekverma2312** [comment]
@techbhavin Above issues are tested and working fine.

**Review by sbalaji1192 — APPROVED** [review]
LGTM. Great work!

**Review by sbalaji1192 — APPROVED** [review]

**Pull request merged**
