### PR TITLE
chore: added extra params for AUTO_COMPLETE events

### LINKED ISSUE #23838: [Task]: Measure Autocomplete Effectiveness
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

| Event | Additional properties to track | Existing properties to modify |
|--------|--------|--------|
| AUTO_COMPLETE_SELECT | `query`, `selectedResultIndex`, `selectedResultType`, `isBestMatch` | rename `searchString` -> `selectedResult`
| AUTO_COMPLETE_SHOW | `query`, `numberOfResults` |  --  |

Definitions: 
1. `query`: Search query typed by the user that triggered the autocomplete popup to show up
2. `selectedResultIndex`: Index of the autocomplete result that was selected 
3. `selectedResultType`: Type of the autocomplete result that was selected (eg: Function, Array, Object, etc..)
4. `isBestMatch`: Boolean value to indicate if the selected autocomplete result was a part of Best Match suggestions
5. `numberOfResults`: Number of results shown in the autocomplete popup

### PR DESCRIPTION
**Pull request by Druthi**
## Description
 Chore: added extra params for AUTO_COMPLETE events

#### PR fixes following issue(s)
Fixes #23838 

#### Type of change
- Chore (housekeeping or task changes that don't impact user perception)

#### How Has This Been Tested?
- [ ] Manual

#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by ohansFavour — APPROVED** [review]

**Comment by ramsaptami** [comment]
Skipping QA since the PR targets event tracking
cc: @Druthi

**Review by ohansFavour — APPROVED** [review]

**Pull request merged**
