### PR TITLE
fix: Throw error on trying to access non-existent unpublished action

### LINKED ISSUE #11751: [Bug] NullPointerException
Sentry Issue: [APPSMITH-1RJ](https://sentry.io/organizations/appsmith/issues/2999648897/?referrer=github_integration)

```
NullPointerException: None
    at com.appsmith.server.services.ce.NewActionServiceCEImpl.generateAndSetActionPolicies(NewActionServiceCEImpl.java:237)
```

### PR DESCRIPTION
**Pull request by nidhi-nair**
Fixes #11751 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by sumitsum** [comment]
Few things we might want to think about: 
- Should we add similar check in other action related flows as well - update, rename, copy, move etc. 
- Should we add a JUnit TC for this ? If it is difficult due to the nature of code flow, we may as well skip it for now.

**Review by AnaghHegde — COMMENTED** [review]
Do we have test case to check the scenario? Rest all looks good to me.

**Review by AnaghHegde — APPROVED** [review]

**Comment by nidhi-nair** [comment]
Merging since all tests have passed and test result is not updating.

**Pull request merged**
