### PR TITLE
fix: revert for super users and update ui for profiling ques for non super users

### LINKED ISSUE #27915: [Task]: Profiling question change UI for non-admin users
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Previous issue : https://github.com/appsmithorg/appsmith/issues/27135
Previous PR : https://github.com/appsmithorg/appsmith/pull/27228

The above Pr changed the flow for admin users as well, which collided with the 1 click upgrade project. So we need to revert it for admin users and change the ui for non-admin users

### PR DESCRIPTION
**Pull request by AmanAgarwal041**
## Description
This PR contains the changes :
- Reverting the PR changes for the super user introduced by the pr https://github.com/appsmithorg/appsmith/pull/27228
- Updating the UI for the profiling questions for non-super users
- Enabled the profiling questions for cloud as well as self hosted instances
- Added two events :
  - `PAGE_VIEW` -> `{ pageType: "profilingQuestions", }`
  - `GET_STARTED_CLICKED` -> `{ proficiency, goal: useCase }` (to keep the use case event data common from backend, added use case in goal field)
- FYI - The above UI changes for profiling questions are only for users non-super users & non-invited users on both cloud and self-hosted instances

#### PR fixes following issue(s)
Fixes #27915
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
- [ ] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Comment by chandannkumar** [comment]
Tested and Verified this PR and LGTM
- Tested for older question UI for Super users
- Tested for Newer UI for non-super user
- Tested on Cloud and Local env(by Aparna)

**Review by NilanshBansal — APPROVED** [review]
Backend changed LGTM

**Comment by sneha122** [comment]
Frontend changes LGTM

**Review by sneha122 — APPROVED** [review]

**Pull request merged**
