### PR TITLE
fix: curl import error

### LINKED ISSUE #15175: [Bug]: Creating new cURL import query from entity explorer crashes the app
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we create new cURL import from entity explorer, it gives the error "Resource not found" and on refresh app crashes

https://user-images.githubusercontent.com/80334441/178717222-c4d20cd8-a9fc-4c5a-9689-75495c6d7661.mov

### Steps To Reproduce

1. Go to entity explorer 
2. Create new cURL import and observe

### Public Sample App

_No response_

### Version

Release

### PR DESCRIPTION
**Pull request by eco-monk**
## Description
Send only pageId for redirect call.

Fixes #15175

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
Manually

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by arunvjn** [comment]
Approving for now but we'll need to fix types in a separate PR.

**Review by arunvjn — DISMISSED** [review]

**Review by arunvjn — APPROVED** [review]

**Comment by Parthvi12** [comment]
@eco-monk Tested the dp and it fixes the issue.

**Pull request merged**
