### PR TITLE
fix: Improve ssh url checking for git import

### LINKED ISSUE #15432: [Bug]: Connect to git modal does not allow valid ssh urls
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Open the app and click on connect to git. Add the ssh url - `git@gitlab-abcd.test.org:org__org/repoName.git`.

### Steps To Reproduce

Open the app and click on connect to git. 
Add the ssh url - `git@gitlab-abcd.test.org:org__org/repoName.git`
Notice the FE throws an error saying invalid ssh url.
image

### Public Sample App

Any app

### Version

Latest

### PR DESCRIPTION
**Pull request by IAmAnubhavSaini**
## Description

Fixes issue by allowing `-` in subdomain/domain.

Fixes #15432 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by AnaghHegde** [comment]
@IAmAnubhavSaini Can we update the place holder values as well? We can go with as @vuiets suggested here - 
https://github.com/appsmithorg/appsmith/issues/15432#issuecomment-1195414955

**Comment by IAmAnubhavSaini** [comment]
@AnaghHegde @vuiets I am not inclined to touch strings for git right now. It can be updated anyway without engineering efforts. Please create a merge request with appropriate changes to messages.ts and messages.test.ts.

**Review by ankitakinger — APPROVED** [review]

**Comment by IAmAnubhavSaini** [comment]
Screenshot 2022-08-01 at 10 48 16 AM

**Pull request merged**
