### PR TITLE
fix: update def on widget property name update

### LINKED ISSUE #14100: [Bug]-[400]:Names given to custom columns do not reflect while referencing unless the page is refreshed.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When a user changes the `property name` of a custom column e.g. from `customColumn1` to `Distance`. The new name i.e. `Distance` does not reflect in the app (autocomplete) while binding table.selectedRow.

[LOOM DEMO](https://www.loom.com/share/80ef0d193dcc47f9a62043ee6dd60c6f)

### Steps To Reproduce

1. D&D a table & a text widget
2. In the property pane of the table click on `Add a new column`.
3. Change the `Property name` of the custom column from `customColumn1` to `Distance`.
4. Try to bind the Text widget with the table widget using: `{{Table1.selectedRow.Distance}}`.

**Expected:** The binding should take place successfully.
**Actual:** In the autocomplete options user still sees the original name i.e. `customColumn1` instead of `Distance`.

### Public Sample App

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by Rishabh-Rathod**
## Description

Fixes #14100

## Type of change

- Bug fix (non-breaking change which fixes an issue)

#### Cypress test 
- [x] Edit table column property name and then check in binding if autocompletion shows the new column name

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by arunvjn — APPROVED** [review]

**Comment by ramsaptami** [comment]
Tested and verified on DP for custom columns on table widget

**Review by Aishwarya-U-R — COMMENTED** [review]
Cypress looks fine!

**Comment by ramsaptami** [comment]
@Aishwarya-U-R you can add the Test plan approved label once you're done with your checks

**Pull request merged**
