### PR TITLE
Added email verification while creating user and sending email

### LINKED ISSUE #627: [BUG] No server side validation for email and password length + wrong email regex for email notifications
I can do whatever I want with email, no need for any EMAIL format to be sent for a user to be created.

1. **Check this function responsible for sign up:**
https://github.com/appsmithorg/appsmith/blob/04368d675e891700998ed3d6d4f1b9f69f1819f0/app/server/appsmith-server/src/main/java/com/appsmith/server/services/UserServiceImpl.java#L483

Also, while sending emails from the server your EMAIL REGEX is not valid for many domains like `.website`, `.analytics`, `.education`

2. **Check the variable defined in the notification service:**
https://github.com/appsmithorg/appsmith/blob/04368d675e891700998ed3d6d4f1b9f69f1819f0/app/server/appsmith-server/src/main/java/com/appsmith/server/notifications/EmailSender.java#L38

Here are the options for (2):
[Option 1](https://regex101.com/r/BCZIA4/2)
[Option 2](https://www.regular-expressions.info/email.html)

Once you decide on the regex, you can create a helper function to use for an invite, signup, login, etc.

### PR DESCRIPTION
**Pull request by pc9795**
## Description
Added email verification during `User `creation by adding Java validation API `@Email` annotation on the `email `field of the `User `object. Updated the email verification logic in the `EmailSender `using Apache commons validator's `EmailValidator`

Fixes #627 

## Type of change
- Bugfix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Locally using Postman

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by pc9795** [comment]
Right now we will get a generic message `"Bad Request: Validation failure"` while creating User from the API but after merging https://github.com/appsmithorg/appsmith/pull/1084 we will get a nicely formatted message specifically telling what is failed.

**Comment by pc9795** [comment]
FYI: @Nikhil-Nandagopal

**Comment by mohanarpit** [comment]
@pc9795 Thanks for this PR. Is it possible to write a test to assert the email validation is happening properly? Will ensure that in the future, if any other developer changes the validation, the tests can ensure that the change is valid.

**Review by mohanarpit — APPROVED** [review]

**Comment by mohanarpit** [comment]
@pc9795 Thank you so much for this change! 👏

**Pull request merged**
