### PR TITLE
fix: break branch creation text, fix text casing

### LINKED ISSUE #15014: [Task]: Add space in the text in the create a new branch option (Version Control with Git)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

The text that shows up while creating a new branch has a formatting issue. There is no space between the text. 
For example, I'm currently on master, opened the branch list, and typed a branch name that does not exist yet, say `test`. The create new branch option comes with the following text - "`Create Branch: testfrom 'master'`"
Screenshot 2022-07-05 at 2 05 55 PM

### PR DESCRIPTION
**Pull request by IAmAnubhavSaini**
## Description

During branch creation, a bit of text was clinging to each other. Put them as per the design.

Fixes #15014 

### Issue:

image

### design:

Screenshot 2022-07-16 at 12 40 39 AM

### fix:

https://user-images.githubusercontent.com/1573771/179295053-d5940ba7-2a9f-41a9-965d-596bff69ac71.mov

Screenshot 2022-07-16 at 12 36 52 AM

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by IAmAnubhavSaini** [comment]
Failing test, this modal one makes you think, how was it merged?

Screenshot 2022-07-16 at 2 22 28 PM

**Comment by IAmAnubhavSaini** [comment]
Green CI

Screenshot 2022-07-17 at 12 37 47 AM

**Comment by IAmAnubhavSaini** [comment]
@RakshaKShetty  please test DP for the fix.

**Review by berzerkeer — APPROVED** [review]

**Comment by RakshaKShetty** [comment]
@IAmAnubhavSaini The fix looks good
image

**Pull request merged**
