### PR TITLE
perf: Optimize list widget renders by memoizing part of renderChildren

### LINKED ISSUE #7669: [Perf] Optimize list widget performance
Due to the way list widget children are generated, entire list widget is re rendered when something changes on the canvas.
Fix by memoizing the render children call.

### PR DESCRIPTION
**Pull request by SatishGandham**
Even after the optimizations we did to the widgets editor as a part of improving the editing experience, children of list widget still re-render whenever you edit the canvas, this PR fixes it.

Fixes #7669

## Type of change
- Performance improvement

## How Has This Been Tested?

- Profiled before and after

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: perf/list-widget 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 54.89 **(0)** | 37.03 **(-0.02)** | 33.9 **(0.01)** | 55.5 **(0)**
 :sparkles: :new: | **app/client/src/pages/Editor/DataSourceEditor/BackButton.tsx** | **60** | **50** | **0** | **60**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 50.47 **(-0.24)** | 38.26 **(-0.87)** | 36.21 **(0)** | 55.08 **(-0.27)**
 :green_circle: | app/client/src/widgets/ListWidget/widget/index.tsx | 61.99 **(0.02)** | 26.15 **(-1.83)** | 56 **(1.83)** | 60.81 **(0.43)**</details>

### CODE REVIEW

**Comment by SatishGandham** [comment]
@vivekverma2312 , this needs QA. All list widget functionality should work like before.

**Review by jsartisan — APPROVED** [review]

**Review by jsartisan — DISMISSED** [review]

**Review by jsartisan — APPROVED** [review]

**Review by somangshu — APPROVED** [review]

**Review by somangshu — APPROVED** [review]

**Review by jsartisan — APPROVED** [review]

**Comment by vivekverma2312** [comment]
@SatishGandham Repositioning any widget inside list widget is not working properly
https://www.loom.com/share/fedb90533122411e8d699b91daab7fcb

**Comment by vivekverma2312** [comment]
2. Resizing list container is not proper
https://www.loom.com/share/fc316a348fc545daa7bc8eb2844c3a23
https://www.loom.com/share/ba6e827cf67b44a6ac1071f838f273a5

**Review by jsartisan — APPROVED** [review]

**Review by rahulramesha — APPROVED** [review]
Approving for tests

**Comment by vivekverma2312** [comment]
@SatishGandham Above issues are fix but now again flicker is observed when placing any widget in list widget.
https://www.loom.com/share/c6d657cbe59b47399b98d95c39dc7fb9

**Comment by SatishGandham** [comment]
@vivekverma2312 Flicker happens in the current version as well. Will address that when we rewrite listWidget.

**Review by jsartisan — DISMISSED** [review]

**Review by rahulramesha — DISMISSED** [review]
Approving for tests

**Review by jsartisan — APPROVED** [review]

**Pull request merged**
