### PR TITLE
chore: use helper method for evicting all pg user related cache

### PR DESCRIPTION
**Pull request by nsarupr**
## Description

> The following code introduces a wrapper around the `evictPermissionGroupForUser` cache which can then be extended  for further similar use cases with changes if required.

Fixes https://github.com/appsmithorg/appsmith/issues/20567

Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video

## Type of change

- Chore (housekeeping or task changes that don't impact user perception)

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Comment by nsarupr** [comment]
Flaky Tests:
- GitSyncedApps_spec
- Basic_spec
- Button_onClickAction_spec
- inline_editing_validations_spec

**Comment by nsarupr** [comment]
UI test: https://github.com/appsmithorg/appsmith/actions/runs/4165308562

Non-flaky tests:
- cypress/integration/Regression_TestSuite/ClientSideTests/VisualTests/DatasourcePageLayout_spec.js
- cypress/integration/Regression_TestSuite/ClientSideTests/Widgets/Filepicker/FilePicker2_spec.js
- cypress/integration/Regression_TestSuite/ClientSideTests/Widgets/Form/Form_With_CheckBox_spec.js

**Review by trishaanand — APPROVED** [review]

**Pull request merged**
