### PR TITLE
chore: add import sorting

### LINKED ISSUE #35732: [Task]: Add automatic import sorting in FE client
### SubTasks

**Purpose**
Import sorting improves code organization, readability and maintainability.

**Approach**
Import sorting is purely an esthetic/formatting task in terms of code safety/validity, so there is not necessity to enforce it by a ESLint rule. Therefore this can be done entirely by a formatter, prettier in our case. Additionally, formatting approach is more efficient when compared to linting.

**The tool**
I propose we use **@trivago/prettier-plugin-sort-imports**, in my experience it has been flawless.

**Order & grouping**
Certainly a field for debate, my initial config is as follows: 
```
"importOrder": [
  // react and react-dom are, generally, declared on top of the file, later this will help us remove these imports (react@18)
  "^react$",
  "^react-dom$",
  // our packages
  "^@appsmith/.*$",
  // these are, unfortunately, both: third party modules and our imports that are resolved through loaders 
  "<THIRD_PARTY_MODULES>",
  // all local imports to identify local components
  "^[./]"
],
```

### PR DESCRIPTION
**Pull request by alex-golovanov**
## Description
Automatic import sorting for FE client app.

Fixes #35732

## Automation

/ok-to-test tags="@tag.Sanity"

### :mag: Cypress test results

> [!CAUTION]
> 🔴 🔴 🔴 Some tests have failed.
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/10507939409>
> Commit: 808c190b4874ff6256c82ccee423fc6590bbec0c
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=10507939409&attempt=1&selectiontype=test&testsstatus=failed&specsstatus=fail" target="_blank">Cypress dashboard</a>.
> Tags: @tag.Sanity
> Spec: 
> The following are new failures, please fix them before merging the PR: <ol>
> <li>cypress/e2e/Sanity/Datasources/ArangoDataSourceStub_spec.js
> <li>cypress/e2e/Sanity/Datasources/Arango_Basic_Spec.ts
> <li>cypress/e2e/Sanity/Datasources/AuthenticatedApiDatasource_spec.js
> <li>cypress/e2e/Sanity/Datasources/AuthenticatedApiWithOAuth_spec.ts
> <li>cypress/e2e/Sanity/Datasources/DSAutosaveImprovements_spec.ts
> <li>cypress/e2e/Sanity/Datasources/DatasourceForm_spec.js
> <li>cypress/e2e/Sanity/Datasources/ElasticSearchDatasource_spec.js
> <li>cypress/e2e/Sanity/Datasources/GraphQL_spec.ts
> <li>cypress/e2e/Sanity/Datasources/MongoDatasourceURI_spec.ts
> <li>cypress/e2e/Sanity/Datasources/MsSQLDataSourceStub_spec.js
> <li>cypress/e2e/Sanity/Datasources/MySQLDataSourceStub_spec.js
> <li>cypress/e2e/Sanity/Datasources/MySQLNoiseTest_spec.js
> <li>cypress/e2e/Sanity/Datasources/MySQL_spec.js
> <li>cypress/e2e/Sanity/Datasources/Port_Number_Placeholder_Spec.ts
> <li>cypress/e2e/Sanity/Datasources/PostgresDatasource_spec.js
> <li>cypress/e2e/Sanity/Datasources/RedshiftDataSourceStub_spec.js
> <li>cypress/e2e/Sanity/Datasources/RestApiDatasource_spec.js
> <li>cypress/e2e/Sanity/Datasources/RestApiOAuth2Validation_spec.ts
> <li>cypress/e2e/Sanity/Datasources/SMTPDatasource_spec.js
> <li>cypress/e2e/Sanity/Datasources/Styles_spec.js
> <li>cypress/e2e/Smoke/Apps/ReconnectDatasource_spec.js</ol>
> <a href="https://internal.appsmith.com/app/cypress-dashboard/identified-flaky-tests-65890b3c81d7400d08fa9ee3?branch=master" target="_blank">List of identified flaky tests</a>.
> <hr>Thu, 22 Aug 2024 12:41:38 UTC

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [x] No

## Summary by CodeRabbit

- **New Features**
	- Introduced a new Prettier plugin for automatic sorting of import statements to enhance code organization.
  
- **Improvements**
	- Enhanced formatting rules for import statements to promote readability and maintainability in the codebase.
	- Structured order for imports now prioritizes specific modules for better organization.

### CODE REVIEW

**Review by KelvinOm — COMMENTED** [review]
@alex-golovanov Before merging, there is necessary to run the prettier with new settings so that the new changes are reflected in the code.

**Comment by alex-golovanov** [comment]
> @alex-golovanov Before merging, there is necessary to run the prettier with new settings so that the new changes are reflected in the code.

I'm not so sure about this, this will modify almost all `src` files, I'd rather do a gradual transfer through `lint-staged`.

**Comment by KelvinOm** [comment]
> > @alex-golovanov Before merging, there is necessary to run the prettier with new settings so that the new changes are reflected in the code.
> 
> I'm not so sure about this, this will modify almost all `src` files, I'd rather do a gradual transfer through `lint-staged`.

Yes, it will be so. But that's okay. It seems there is nothing terrible to do it in 1 time.

Also, if this is not done, then you will need to make changes to these pipelines. 
Снимок экрана 2024-08-19 в 14 16 53

**Comment by alex-golovanov** [comment]
> > > @alex-golovanov Before merging, there is necessary to run the prettier with new settings so that the new changes are reflected in the code.
> > 
> > 
> > I'm not so sure about this, this will modify almost all `src` files, I'd rather do a gradual transfer through `lint-staged`.
> 
> Yes, it will be so. But that's okay. It seems there is nothing terrible to do it in 1 time.
> 
> Also, if this is not done, then you will need to make changes to these pipelines. Снимок экрана 2024-08-19 в 14 16 53

Ok, no worries, formatted everything.

**Comment by alex-golovanov** [comment]
> > > > @alex-golovanov Before merging, there is necessary to run the prettier with new settings so that the new changes are reflected in the code.
> > > 
> > > 
> > > I'm not so sure about this, this will modify almost all `src` files, I'd rather do a gradual transfer through `lint-staged`.
> > 
> > 
> > Yes, it will be so. But that's okay. It seems there is nothing terrible to do it in 1 time.
> > Also, if this is not done, then you will need to make changes to these pipelines. Снимок экрана 2024-08-19 в 14 16 53
> 
> Ok, no worries, formatted everything.

Spoke to soon, there is a problem with EE.

```
Pre push hook called
URL is git@github.com:appsmithorg/appsmith.git
remote is origin
remote sha is 
pushing from 88c0241f39a298f3457b77b955fc17d16fd14ca4 to 24816450c2f1e5f9f73fec1bcba9994b31f78c4a
local ref is  refs/heads/chore/35732-prettier-import-sort
remote ref is  refs/heads/chore/35732-prettier-import-sort
to_commit in function is 24816450c2f1e5f9f73fec1bcba9994b31f78c4a
from_commit is 88c0241f39a298f3457b77b955fc17d16fd14ca4
File 'app/client/src/ee/AppRouter.tsx' matches the string 'app/client/src/ee'
Found EE changes in the commits

Hook process exited.
```

How do you solve things like these? @KelvinOm

**Comment by KelvinOm** [comment]
> > > > > @alex-golovanov Before merging, there is necessary to run the prettier with new settings so that the new changes are reflected in the code.
> > > > 
> > > > 
> > > > I'm not so sure about this, this will modify almost all `src` files, I'd rather do a gradual transfer through `lint-staged`.
> > > 
> > > 
> > > Yes, it will be so. But that's okay. It seems there is nothing terrible to do it in 1 time.
> > > Also, if this is not done, then you will need to make changes to these pipelines. Снимок экрана 2024-08-19 в 14 16 53
> > 
> > 
> > Ok, no worries, formatted everything.
> 
> Spoke to soon, there is a problem with EE.
> 
> ```
> Pre push hook called
> URL is git@github.com:appsmithorg/appsmith.git
> remote is origin
> remote sha is 
> pushing from 88c0241f39a298f3457b77b955fc17d16fd14ca4 to 24816450c2f1e5f9f73fec1bcba9994b31f78c4a
> local ref is  refs/heads/chore/35732-prettier-import-sort
> remote ref is  refs/heads/chore/35732-prettier-import-sort
> to_commit in function is 24816450c2f1e5f9f73fec1bcba9994b31f78c4a
> from_commit is 88c0241f39a298f3457b77b955fc17d16fd14ca4
> File 'app/client/src/ee/AppRouter.tsx' matches the string 'app/client/src/ee'
> Found EE changes in the commits
> 
> Hook process exited.
> ```
> 
> How do you solve things like these? @KelvinOm

Make changes to EE repo and then use the `yarn sync-ee-to-ce` script to create a commit in CE repo. Read more about this [here](https://www.notion.so/appsmith/Extract-CE-changes-from-EE-Repo-1d06403171d645d4a92328fa7b89be3f).  

Remember that the script only moves changes from the `src` folder, so something will need to be moved manually.

**Comment by alex-golovanov** [comment]
> Make changes to EE repo and then use the `yarn sync-ee-to-ce` script to create a commit in CE repo. Read more about this [here](https://www.notion.so/appsmith/Extract-CE-changes-from-EE-Repo-1d06403171d645d4a92328fa7b89be3f).
> 
> Remember that the script only moves changes from the `src` folder, so something will need to be moved manually.

It seems that this script is not geared towards something as drastic as this, so my proposal is to avoid formatting all files and go with gradual `lint-staged` adoption.  This can be easily force merged without any consequences for EE or CE.

**Pull request closed without merging**
