### PR TITLE
chore: External contri/external contri/issue #24726/feat wrong mssql configuration

### LINKED ISSUE #24726: [Feature]: show a better error for wrong mssql configuration
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

When the MSSQL datasource configuration is wrong, three things happen:
1. upon testing the datasource, the busy indicator spins for a long time and gives up without an error 
2. the schema in the entity explorer shows a timeout error
3. if you try to run a simple query `select * from dbo.users`, there is a timeout error

Use the following config:
host: [SQL5106.site4now.net](http://sql5106.site4now.net/)
db: db_a9b34d_rohansdb
user: db_a9b34d_rohansdb_admin
pw: Password@123

First, keep the port number blank or enter `1433` to ensure that the correct config works. Test connection, see the schema, run a query.

Next deliberately enter a wrong port number. You can see the three symptoms mentioned above.

Ideal scenario:
1. On test of the datasource, I should see an error message saying that the port number is wrong
2. Same in the schema
3. Same when I try to run a query

### Why should this be worked on?

this will help users create good quality mssql datasources, and therefore be more likely to successfully execute their query

### PR DESCRIPTION
**Pull request by rohan-arthur**
## Description
shadow PR for #34472

Fixes #24726   

## Automation

/ok-to-test tags="@tag.Datasource"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9962367370>
> Commit: a6cbef76610e9ec548d2dde9f59c848941d5d0c7
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9962367370&attempt=1" target="_blank">Cypress dashboard</a>.
> Tags: `@tag.Datasource`
> Spec:
> <hr>Tue, 16 Jul 2024 19:16:22 UTC

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [x] No

## Summary by CodeRabbit

- **New Features**
  - Improved validation for connection mode, endpoints, and authentication in MSSQL plugin.
  - Enhanced error messages for missing hostnames and database names.

- **Tests**
  - Added tests for validating various datasource configurations, including null credentials, endpoints, hosts, and authentication details.

### CODE REVIEW

**Comment by rishabhrathod01** [comment]
To pull new changes from https://github.com/appsmithorg/appsmith/pull/34472 PR, we need to follow below steps
1. Checkout to the current PR branch where new changes need to fetch `git checkout external-contri/external-contri/Issue-#24726/feat-wrong-mssql-configuration`
2. `git remote add saiprabhu https://github.com/saiprabhu-dandanayak/appsmith.git`  
3. `git fetch saiprabhu`   ( This will pull all the branches in the mentioned repo locally )
4. `git merge external-contri/Issue-#24726/feat-wrong-mssql-configuration`  
5. Push changes

**Comment by saiprabhu-dandanayak** [comment]
> 1. branch where new changes need to fe

ok @rishabhrathod01 , will do that now.

**Comment by saiprabhu-dandanayak** [comment]
> To pull new changes from #34472 PR, we need to follow below steps
> 
> 1. Checkout to the current PR branch where new changes need to fetch `git checkout external-contri/external-contri/Issue-#24726/feat-wrong-mssql-configuration`
> 2. `git remote add saiprabhu https://github.com/saiprabhu-dandanayak/appsmith.git`
> 3. `git fetch saiprabhu`   ( This will pull all the branches in the mentioned repo locally )
> 4. `git merge external-contri/Issue-#24726/feat-wrong-mssql-configuration`
> 5. Push changes

Hi @rishabhrathod01 , actually the above mentioned  `git checkout external-contri/external-contri/Issue-#24726/feat-wrong-mssql-configuration` branch is not present in my forked repository so i am unable to switch to the same branch should take the latest pull from 

> To pull new changes from #34472 PR, we need to follow below steps
> 
> 1. Checkout to the current PR branch where new changes need to fetch `git checkout external-contri/external-contri/Issue-#24726/feat-wrong-mssql-configuration`
> 2. `git remote add saiprabhu https://github.com/saiprabhu-dandanayak/appsmith.git`
> 3. `git fetch saiprabhu`   ( This will pull all the branches in the mentioned repo locally )
> 4. `git merge external-contri/Issue-#24726/feat-wrong-mssql-configuration`
> 5. Push changes

Hi @rishabhrathod01 , since i dont have `git checkout external-contri/external-contri/Issue-#24726/feat-wrong-mssql-configuration` branch is not present in my forked repo , should i create one and push or else can i take the leatest changes from release and push it to `https://github.com/appsmithorg/appsmith/pull/34472`

**Comment by rishabhrathod01** [comment]
@saiprabhu-dandanayak those steps mentioned above were for the internal team to reference later on. You don't need to do anything here. Thanks.

**Pull request closed without merging**
