### PR TITLE
fix: Added timestamp in where clause types, modified logic for calculating date time types

### LINKED ISSUE #9557: [Bug]: DATE parsing in GoogleSheet broke existing apps with DATETIME values stored in a column
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The last release introduced parsing of DATETIME values stored as strings in Google Sheets as DATE objects. This breaks all existing apps which have previously stored date values with the time component.

Example of such breakdown reported by an user https://discord.com/channels/725602949748752515/760761686549463060/916260512277356554

### Steps To Reproduce

1. Store DATETIME values in a Google Sheet column
2. Do a where clause fetch on this sheet
3. Notice the SQL insert message in the Response pane

image

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by nidhi-nair**
Fixes #9557

### CODE REVIEW

**Review by sumitsum — DISMISSED** [review]

**Comment by sumitsum** [comment]
@nidhi-nair this PR is still in draft mode - just informing you in case this PR is in draft mode by mistake.

**Comment by nidhi-nair** [comment]
Yeah I forgot I haven't added a test case for the actual failure so created it as a draft. I'll add the test case and update the PR status 😀

**Review by sumitsum — DISMISSED** [review]

**Review by sharat87 — APPROVED** [review]

**Pull request merged**
