### PR TITLE
fix: Revert - Implemented responsive table header controls #10971

### PR DESCRIPTION
**Pull request by techbhavin**
Reverts appsmithorg/appsmith#10971

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: revert-10971-6518-responsive-table-header-controls 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 56.28 **(-0.01)** | 37.7 **(0)** | 35.92 **(-0.02)** | 56.51 **(0)**
 :green_circle: | app/client/src/utils/WorkerUtil.ts | 89.76 **(0)** | 72.55 **(1.96)** | 100 **(0)** | 93.33 **(0)**
 :green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.94 **(0.23)** | 41.67 **(0.84)** | 36.21 **(0)** | 56.99 **(0.25)**
 :red_circle: | app/client/src/widgets/TableWidget/component/Constants.ts | 85.48 **(-0.88)** | 73.53 **(-1.47)** | 91.3 **(-0.37)** | 85.48 **(-0.88)**
 :red_circle: | app/client/src/widgets/TableWidget/component/Table.tsx | 61.63 **(-0.44)** | 38.89 **(0)** | 38.89 **(0)** | 60.98 **(-0.47)**
 :green_circle: | app/client/src/widgets/TableWidget/component/TableDataDownload.tsx | 35.82 **(0)** | 13.89 **(0.73)** | 9.09 **(0)** | 34.92 **(0)**
 :green_circle: | app/client/src/widgets/TableWidget/component/TableFilters.tsx | 80 **(2.22)** | 23.81 **(3.81)** | 66.67 **(0)** | 78.79 **(2.32)**
 :red_circle: | app/client/src/widgets/TableWidget/component/TableHeader.tsx | 50 **(-3.49)** | 53.06 **(-4.83)** | 30 **(-6.36)** | 47.37 **(-3.85)**
 :red_circle: | app/client/src/widgets/TableWidget/component/TableStyledWrappers.tsx | 87.5 **(-0.28)** | 56.2 **(0.08)** | 80.7 **(-0.66)** | 87.5 **(-0.28)**</details>

### CODE REVIEW

**Review by sbalaji1192 — APPROVED** [review]

**Review by somangshu — APPROVED** [review]

**Comment by somangshu** [comment]
Constantly seeing a failure here, @techbhavin is this related by any chance

@Aishwarya-U-R can you please help

**Comment by techbhavin** [comment]
@somangshu  there is not any related test-case is failing. 

The below test case is falling
 `Smoke_TestSuite/ClientSideTests/FormWidgets/Widget_Popup_spec.js`

**Comment by Aishwarya-U-R** [comment]
@somangshu - Its always better to trigger a ok-to-test after latest release merge. That failing cases has passed now.

**Pull request merged**
