### PR TITLE
feat: Added tests for renaming entities through the entity explorer

### PR DESCRIPTION
**Pull request by Irongade**
Added cypress tests for recent changes made to the entity explorer.

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: feat/entity-explorer-cypress-tests 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 55.2 **(-0.09)** | 36.97 **(-0.16)** | 34.16 **(-0.18)** | 55.71 **(-0.1)**
 :red_circle: | app/client/src/components/ads/Button.tsx | 90.85 **(0)** | 73.91 **(-1.74)** | 95.56 **(0)** | 91.43 **(0)**
 :red_circle: | app/client/src/components/ads/TextInput.tsx | 75.41 **(0)** | 47.66 **(-0.94)** | 84.21 **(0)** | 74.55 **(0)**
 :red_circle: | app/client/src/components/ads/Toggle.tsx | 27.27 **(-59.09)** | 7.14 **(-46.43)** | 0 **(-80)** | 30 **(-55)**
 :red_circle: | app/client/src/pages/Settings/Main/Link.tsx | 100 **(0)** | 80 **(-5)** | 100 **(0)** | 100 **(0)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.71 **(-0.23)** | 40.83 **(-0.84)** | 36.21 **(0)** | 56.74 **(-0.25)**
 :red_circle: | app/client/src/widgets/InputWidget/widget/index.tsx | 62.14 **(-0.72)** | 41.67 **(-1.57)** | 69.57 **(0)** | 64.29 **(-0.71)**
 :x: | ~~app/client/src/components/ads/formFields/FieldError.tsx~~ | ~~100~~ | ~~75~~ | ~~100~~ | ~~100~~
 :x: | ~~app/client/src/components/ads/formFields/TextField.tsx~~ | ~~100~~ | ~~66.67~~ | ~~100~~ | ~~100~~
 :x: | ~~app/client/src/pages/Settings/Main/TextInput.tsx~~ | ~~100~~ | ~~75~~ | ~~100~~ | ~~100~~
 :x: | ~~app/client/src/pages/Settings/Main/Toggle.tsx~~ | ~~80.95~~ | ~~62.5~~ | ~~57.14~~ | ~~80~~
 :x: | ~~app/client/src/pages/Settings/Main/group.tsx~~ | ~~97.06~~ | ~~71.88~~ | ~~100~~ | ~~96.77~~</details>

### CODE REVIEW

**Review by Aishwarya-U-R — COMMENTED** [review]
cy.DeletepageFromSideBar("Page2");
-- this method does not take any paramater as of now. Is this method also updated at your end? if yes - that file also should go in as this PR right?

**Review by AmanAgarwal041 — DISMISSED** [review]

**Review by AmanAgarwal041 — APPROVED** [review]

**Review by Aishwarya-U-R — COMMENTED** [review]
Approving!

**Pull request merged**
