### PR TITLE
fix: update tooltip record count prop table

### LINKED ISSUE #9090: [Docs]: Update tooltip for Total Records Count property of the table widget
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

_No response_

### Describe the problem

The text on the tooltip of Total Records Count is confusing and does not deliver the meaning of the property.

### Describe the improvement

Replace the tooltip text with the following:

"It stores the total no. of rows in the table. Helps in calculating the no. of pages that further allows to enable or disable the next/previous control in pagination."

### PR DESCRIPTION
**Pull request by keyurparalkar**
> Pull Request Template
> 
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Description
Replaced the tooltip text with the following :

"It stores the total no. of rows in the table. Helps in calculating the no. of pages that further allows to enable or disable the next/previous control in pagination." 

Fixes #9090

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
Manually tested - Jest test case written. 
> Please also list any relevant details for your test configuration.
- File name: `src/widgets/TableWidget/widget/propertyConfig.test.ts`

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/fix-update_tooltip_record_count_prop_table 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 55.05 **(0.01)** | 36.93 **(0)** | 33.8 **(0.01)** | 55.53 **(0.01)**
 :green_circle: | app/client/src/constants/messages.ts | 74.03 **(0.05)** | 100 **(0)** | 23.14 **(0.15)** | 79.72 **(0.06)**
 :green_circle: | app/client/src/widgets/TableWidget/widget/propertyConfig.ts | 95.74 **(0.09)** | 100 **(0)** | 93.33 **(0)** | 95.74 **(0.09)**</details>

### CODE REVIEW

**Comment by keyurparalkar** [comment]
@jsartisan Updated the code as per the suggestion:

- Defined a constant in the `constants/message.ts`.
- used `createMessage` function.

**Review by jsartisan — APPROVED** [review]

**Pull request merged**
