### PR TITLE
fix: Add email validation for 4 letter email domain extension names

### LINKED ISSUE #23576: [Bug]: Email input doesn't support some domains
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When using an email input, i expect all domains to be supported by default. However, .tech and .info domains failed to work.

### Steps To Reproduce

1. Add a new input widget
2. Make it email type
3. Add an email like "dilippitchika@appsmith.info"
4. Observe the widget throws an invalid email error

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by rajatagrawal**
Fixes #23576

Steps to repro:

QA Steps:
1. Use an email with four letter extension : .info, .tech
2. Check case insensitive extension validations. Both .info and .INFO should be valid email addresses

### CODE REVIEW

**Review by sbalaji1192 — APPROVED** [review]

**Comment by laveena-en** [comment]
Tested email input with various 4 letter email extensions. Changes LGTM!

**Pull request merged**
