### PR TITLE
fix: Auto layout List widget related issues

### LINKED ISSUE #21870: [Bug[Widget Responsiveness] When resized to mobile viewport(using resize handles and actual viewport), some of the widgets in List widget are not responding correctly from second item container onwards
1. Mobile viewport using handles
https://www.loom.com/share/0d2db381fb3441d2a151efa01bfa44e2

2. Actual mobile viewport

Screenshot 2023-03-29 at 5 06 57 PM

### LINKED ISSUE #22086: [Bug][Widget Responsiveness] the child widgets of list widget are not visible in actual mobile viewport
Image

### LINKED ISSUE #22539: [Bug][Widget responsiveness]Issue List widget in mobile viewport
When we Dnd list widget in Auto layout and change canvas to mobile viewport, we are able to see 1st option is different from the other options below

### PR DESCRIPTION
**Pull request by aswathkk**
## Description

In the case of widgets that are managed by List widget (Meta widgets), we store it in `entitites.metaWidgets`.
For auto layout calculations, we were making use of `entities.canvasWidgets` and not `entites.metaWidgets` caused the widgets inside List widget not to function properly.

In this PR, we started making use of both canvasWidgets & metaWidgets to resolve some of the issues with ListWidget in Auto layout mode.

Fixes #21870
Fixes #22086
Fixes #22539

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manual

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by prsidhu — APPROVED** [review]
Tested locally. Looks good.

**Review by prsidhu — APPROVED** [review]

**Comment by prsidhu** [comment]
are we not targeting the manual resize of list item container in this PR?

**Comment by aswathkk** [comment]
@prsidhu Yes. We are allowing to manually resize list item container

**Pull request merged**
