### PR TITLE
fix: Js object - set async tag after all objects are parsed

### LINKED ISSUE #12243: [Bug]: Async tag of a particular function keeps turning off when app is loaded and only recognizes it as async after an edit
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

A JS function keeps loosing it's async tag when app is loaded and on editing the object, the async tag reappears. 

### Steps To Reproduce

1. Go to JS object at [this](https://release.app.appsmith.com/applications/623d6239e0a3cd4540af5979/pages/623d6239e0a3cd4540af597f/edit/jsObjects/623d6239e0a3cd4540af59ca) location
2. Observe the state of the function - if in async - clear cache and reload the app
3. Observe the async tag no longer present on the function
[LOOM DEMO](https://www.loom.com/share/e7fc47ecce8449d59dd9c8f1fcfec972)

4. If the function does not have an async tag, edit to reparse the function and observe the async tag reappear
[LOOM DEMO](https://www.loom.com/share/587722d8bfad4b2ab6f6cd3a99956ce0)

### Public Sample App

_No response_

### Version

Cloud

### LINKED ISSUE #12502: [Bug]: JS object+function pair is not identified when being called by another function
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When one JS function calls another JS function, then the nested function comes up as an error stating 'nestedJSObj.myFun is not a function at parentJSObj'  causing app flow to break

Not sure of exact repro steps to reach this state but sample app with this behaviour is attached below

### Steps To Reproduce

1. Go to app at [this link](https://release.app.appsmith.com/earworm-performance-lag-issue-11284/music-app-issue-11284-6241687ee5732918f59b7d7d/edit/jsObjects/6241687fe5732918f59b7def)
2. Edit `pageLoadActions.authorizeSpotifyUsage` by adding a comment if you can't see the async tag (another issue being tracked under #12243 )
3. Observe console displaying an error ``` SpotifyAuthOperation.authTPP is not a function at authorizeSpotifyUsage ```
4. Navigate on JS objects and observe this function exsits

[LOOM DEMO](https://www.loom.com/share/67949cfb39b5464fbf97f599f2253f3d)

### Public Sample App

https://release.app.appsmith.com/earworm-performance-lag-issue-11284/music-app-issue-11284-6241687ee5732918f59b7d7d/edit/jsObjects/6241687fe5732918f59b7def

### Version

Cloud

### PR DESCRIPTION
**Pull request by eco-monk**
Fixes #12243
Fixes #12502

For cases where a Js object uses an async function from another Js object. 
The order in which js objects were parsed resulted in some functions not getting the async tag.

This change will ensure `isAsync` tag is set only after all objects are parsed.

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
Sample app [export](https://drive.google.com/file/d/18m5N_B3heLxGXlZlBj6HDSQydB_M38rZ/view?usp=sharing)

To consistently reproduce error (on release), add this snippet at the beginning of `parseJSactions` method in `DataTreeEvaluator`.
This will change the order in which Js objects are parsed based on their name.
```
   let jsUpdates = {};
    if (!!differences && !!oldUnEvalTree) {
      differences.sort((a, b) =>
        a.payload.propertyPath[0] > b.payload.propertyPath[0] ? 1 : -1,
      );
      console.log("jsUpdates", differences);
```

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/async-tag 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 56.34 **(0)** | 37.73 **(-0.01)** | 35.94 **(0)** | 56.56 **(0)**
 :red_circle: | app/client/src/utils/WorkerUtil.ts | 88.98 **(-0.78)** | 68.63 **(-3.92)** | 100 **(0)** | 92.38 **(-0.95)**
 :red_circle: | app/client/src/workers/DataTreeEvaluator/DataTreeEvaluator.ts | 76.31 **(-0.32)** | 58.36 **(-0.37)** | 74.16 **(-0.84)** | 76.15 **(-0.21)**</details>

### CODE REVIEW

**Review by ApekshaBhosale — COMMENTED** [review]
What happens in case one js object fails to parse? is it taken care by this as well?

**Comment by eco-monk** [comment]
So, in case of any parsing errors, the function doesn't make it to the state where we check for async flag.

**Comment by eco-monk** [comment]
We should consider adding a third state for async flag. ( say `undetermined`)

Because, right now a function is either async or sync.
But actually, in case of errors, it really is undetermined.

**Comment by ApekshaBhosale** [comment]
@eco-monk what do we want to achieve by adding a third state? if it's not undermined then let's assume the default one ie sync. when the error gets cleared anyways it corrects itself. I think by adding third state are adding complexity for no reason.

**Comment by eco-monk** [comment]
It's a thought on top of my head.

2 things on my mind for actions whose nature of execution is undetermined.
1. Response tab indication and linting errors.
2. preventing evaluation. (if that is desired in anywhere)

Let's see If there's any scenario, where we need something like this.

**Review by ApekshaBhosale — APPROVED** [review]

**Pull request merged**
