### PR TITLE
chore: Refactored the service method to get git branch list

### LINKED ISSUE #26876: Allow EE users to change the default branch

### PR DESCRIPTION
**Pull request by nayan-rafiq**
## Description
This PR refactors the service method to get the list of git branches. 

#### PR fixes following issue(s)
Fixes #26876

#### Type of change
- Chore (housekeeping or task changes that don't impact user perception)

- [x] Manual
- [x] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by Parthvi12 — APPROVED** [review]

**Review by AnaghHegde — APPROVED** [review]

**Comment by AnaghHegde** [comment]
@nayan-rafiq DO you think if we should move the logic to a helper or utility class? Just for the value of the boolean flag not the business logic though.

**Pull request merged**
