### PR TITLE
fix: Updated isPublic field to fetch from Permission groups 

### LINKED ISSUE #19131: [Bug]: Update Application API returns isPublic parameter as False always
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The `isPublic` field returned in the update application API - `/applications/{applicationId}` (PUT) always returns False irrespective of the current application state which creates an anomaly.

### Steps To Reproduce

1. Open an existing Application.
2. Click on the Share button in the top right corner and make the app public.
3. Open Chrome Debugger Tools (using CMD + Option + I), and go to the Network tab to inspect APIs.
4.  Rename the application from the left top corner and inspect the API `/applications/{applicationId}` (PUT) response.
5. The API response returns `isPublic` as `False` even when the app is public.

### Public Sample App

_No response_

### Issue video log

[_No response_](https://user-images.githubusercontent.com/25542733/209090181-797a1d71-4a18-4b92-9738-ce1eb4773394.mov)

### Version

v1.8.14-SNAPSHOT

### PR DESCRIPTION
**Pull request by NilanshBansal**
Fixes #19131 

### Media

https://user-images.githubusercontent.com/25542733/209096894-2d88d20d-6636-4d8a-9bf0-7a04a95f75dd.mov

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by trishaanand — DISMISSED** [review]

**Comment by nidhi-nair** [comment]
@NilanshBansal could we please assert tihis change in a test case so this does not get missed in the future?

**Review by nidhi-nair — CHANGES_REQUESTED** [review]
Requesting addition of a test case.

**Comment by SatishGandham** [comment]
/perf-test
Just testing perf infra

**Comment by SatishGandham** [comment]
/perf-test
Testing performance infra, ignore.

**Review by nidhi-nair — APPROVED** [review]

**Pull request merged**
