### PR TITLE
feat: debugger js pane navigation

### PR DESCRIPTION
**Pull request by akash-codemonk**
## Description

Navigates to the line,character in the editor if the error log has this information. Also if a function throws an error it will place the cursor at the start of the function name. 

Fixes https://github.com/appsmithorg/appsmith/issues/25463
Fixes https://github.com/appsmithorg/appsmith/issues/16408

#### Media

https://github.com/appsmithorg/appsmith/assets/67054171/860125cf-9627-4739-b204-89dbb559d475

#### Type of change
- Bug fix (non-breaking change which fixes an issue)

#### How Has This Been Tested?

- [x] Manual
- [ ] Jest
- [x] Cypress

#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Comment by shwetha-ramesh** [comment]
@akash-codemonk 

- [ ]  Debugger not able to navigate to widgets inside Modal widget
https://www.loom.com/share/7eeb1acc9ce04f42989faebd5adb777b

**Comment by shwetha-ramesh** [comment]
@akash-codemonk 
- [ ] Not able to navigate to functions from debugger
https://www.loom.com/share/02d65985fcf0453d89f295dc419b7f7b

**Comment by akash-codemonk** [comment]
> * [ ]  Not able to navigate to functions from debugger

These are expected. 
The function error wouldn't navigate to the line if the js is not parsable. One way to check this is if the function dropdown is disable. When it is enabled, function navigation will work.
invalid_js


Also non-function errors with information about the line number will work. If an error does not have this it will not work. Adding line number information is out of scope of this PR, but once it is added it expected to work. 
line_numbers

**Review by hetunandu — APPROVED** [review]

**Pull request merged**
