### PR TITLE
fix: Enable auto height by default for JSONForm widget

### LINKED ISSUE #18931: [Task]: Enable auto height by default for JSONForm widget
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- Enable auto height by default for JSONForm widget.

### PR DESCRIPTION
**Pull request by riodeuno**
## Description
- JSONForm by default now has auto height enabled
- Changed the CSS for the messages in JSONForm to a fixed height. This way, the JSONForm widget doesn't change height until the default form schema is first loaded.
- Made sure to leave the behaviour in fixed mode uneffected.

Fixes #18931

Media

https://user-images.githubusercontent.com/103687/207424195-47712381-2dd2-4aa2-a8b2-6fe159557482.mov

## Type of change
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
- Manual
- Cypress PENDING

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [PENDING] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [PENDING] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [NA] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by ashit-rath — APPROVED** [review]

**Review by ashit-rath — APPROVED** [review]

**Comment by kamakshibhat-appsmith** [comment]
Looks good, lets proceed @riodeuno

**Pull request merged**
