### PR TITLE
fix: Error: Could not load "marker"

### LINKED ISSUE #6315: [Bug] Error: Could not load "marker".
Sentry Issue: [APPSMITH-107](https://sentry.io/organizations/appsmith/issues/2547548505/?referrer=github_integration)

```
Error: Could not load "marker".
  at None (/maps/api/js:113:243)
```

### PR DESCRIPTION
**Pull request by wmdev0808**
## Description
This is caused due to the google maps related files not being loaded from the google endpoint.

Fixes #6315

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Test A
- Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/6315-could-not-load-marker 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 55.13 **(0)** | 37.18 **(0.01)** | 33.96 **(-0.01)** | 55.63 **(-0.01)**
 :green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.94 **(0.23)** | 41.67 **(0.84)** | 36.21 **(0)** | 56.99 **(0.25)**
 :red_circle: | app/client/src/widgets/MapWidget/component/index.tsx | 27.27 **(-2.28)** | 26.32 **(3.46)** | 0 **(0)** | 28.3 **(-2.65)**</details>

### CODE REVIEW

**Comment by YogeshJayaseelan** [comment]
@wmdev0808 @riodeuno Tested this PR by blocking the util.js , map.js and marker.js in the chrome dev tool and on refreshing the page i could still see the following error "Error could not load Util, Map and Marker" on the console and im not seeing any container with toast error message on the map widget. what is the expected behaviour here?

Screenshot 2021-12-07 at 3 45 40 PM

**Comment by wmdev0808** [comment]
> @wmdev0808 @riodeuno Tested this PR by blocking the util.js , map.js and marker.js in the chrome dev tool and on refreshing the page i could still see the following error "Error could not load Util, Map and Marker" on the console and im not seeing any container with toast error message on the map widget. what is the expected behaviour here?
> 
> Screenshot 2021-12-07 at 3 45 40 PM

@YogeshJayaseelan , @riodeuno,
- First, the current commit is just check if the loading of GMap JS API is successful or not
- The error scenario is just when the above script loading is successful, but the loading of relevant scripts following the api script is unsuccessful
- We can only observe the loading status of the API script, we cannot observe the loading status of these following scripts
- For @YogeshJayaseelan , you can see the error message only if you block the api request
- For @riodeuno, please give me your advice if you know any solution for detecting this scenario

**Comment by YogeshJayaseelan** [comment]
@riodeuno can you please help us on this

**Comment by riodeuno** [comment]
@wmdev0808 You're right, it is difficult to track the subsequent script load failures. 

@YogeshJayaseelan The errors seen in the console - only for the subsequent scripts, as @wmdev0808  mentioned - do not have to be supressed.

Overall, the main goal here, is to make sure that the user is able to recover from a bad state. So, let's focus on having the user be able to recover from a bad state when any of these scripts fail.

**Comment by dilippitchika** [comment]
@somangshu can we decide what to do about this? Looks like Abhinav has responded with the details. Is there any way for Yogesh to test, given that it only checks for API loading.

**Comment by somangshu** [comment]
@dilippitchika if the console errors can't be suppressed and the widget still does not get into a bad state, I believe we can let this move forward. I am not sure what else need to be tested here, @YogeshJayaseelan can you help

**Pull request closed without merging**
