### PR TITLE
feat: Deduplicate Manual Product Update Modal

### PR DESCRIPTION
**Pull request by rohitagarwal88**
This PR deduplicate Manual product update modal & upgrade icon & tooltip in the bottom bar.

https://www.loom.com/share/f78e477036ec4a19b3c301d4065b1f5d

Issue listed on [notion](https://www.notion.so/appsmith/f353d8c6bd664f79ad858a42010cdfc8?v=f04cde23f6424aeb9d5a6e389cd172bd&p=2d695457152f40af93a7ad40c2a762e5&pm=s)

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update

- Manual
- Jest
- Cypress

### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Comment by laveena-en** [comment]
@rohitagarwal88 1. Can we remove the dismiss button since we already have a close icon? https://www.notion.so/appsmith/Heading-colours-are-not-as-per-ADS2-0-2d695457152f40af93a7ad40c2a762e5?d=a2c6d7bb8ac846daabd971f2b974b17a#53328bb4d2244146bbc40632bd254c52

2. The modal is being dismissed on clicking outside the modal. Can we keep it consistent with release? (To be dismissed only when close icon/dismiss is clicked on)

**Comment by rohitagarwal88** [comment]
@laveena-en : fixed both the issues

> @rohitagarwal88 1. Can we remove the dismiss button since we already have a close icon? https://www.notion.so/appsmith/Heading-colours-are-not-as-per-ADS2-0-2d695457152f40af93a7ad40c2a762e5?d=a2c6d7bb8ac846daabd971f2b974b17a#53328bb4d2244146bbc40632bd254c52
> 
> 2. The modal is being dismissed on clicking outside the modal. Can we keep it consistent with release? (To be dismissed only when close icon/dismiss is clicked on)

**Comment by rohitagarwal88** [comment]
@laveena-en fixed both issues

> @rohitagarwal88 1. Can we remove the dismiss button since we already have a close icon? https://www.notion.so/appsmith/Heading-colours-are-not-as-per-ADS2-0-2d695457152f40af93a7ad40c2a762e5?d=a2c6d7bb8ac846daabd971f2b974b17a#53328bb4d2244146bbc40632bd254c52
> 
> The modal is being dismissed on clicking outside the modal. Can we keep it consistent with release? (To be dismissed only when close icon/dismiss is clicked on)

**Comment by laveena-en** [comment]
Re-tested and verified the fixes. LGTM!

**Pull request merged**
