### PR TITLE
fix: add analytics for git import application flow

### LINKED ISSUE #11619: [Task] Missing analytics events for Git Import

### PR DESCRIPTION
**Pull request by IAmAnubhavSaini**
## Description

Analytics tracking is missing for git import application. This PR adds event tracking as follows:

1. When git-import-application card is clicked 
 
Fixes #11619

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

No testing for it.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix-11619 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 56.57 **(0)** | 38.57 **(0.01)** | 35.89 **(0)** | 56.81 **(0)**
 :green_circle: | app/client/src/utils/WorkerUtil.ts | 89.76 **(0.78)** | 72.55 **(3.92)** | 100 **(0)** | 93.33 **(0.95)**
 :green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.94 **(0.23)** | 41.67 **(0.84)** | 36.21 **(0)** | 56.99 **(0.25)**</details>

### CODE REVIEW

**Review by ankitakinger — APPROVED** [review]

**Comment by RakshaKShetty** [comment]
@IAmAnubhavSaini @hiteshjoshi we are not tracking any test plan for the analytics so just added test plan approved tag to go ahead and merge this PR

**Comment by hiteshjoshi** [comment]
@Nikhil-Nandagopal Raksha mentioned about finding a strategy to do QA on mixpanel events. Anything you have in mind? Can we somehow test if events triggered are functional.

**Comment by Nikhil-Nandagopal** [comment]
@hiteshjoshi, on prod this is easy but on staging, we'll need to create a staging key on segment

**Pull request merged**
