### PR TITLE
feat: Only Date option

### LINKED ISSUE #3516: [Feature] Only Date option
## Summary

We need a way to allow users to enter only the date in the datepicker.

## Motivation
Today, the Datepicker allows users to enter the date and time. This becomes inconvenient in use-cases where only the date is needed. We need an option to disable time from the datepicker

## Additional Context
- The DatePicker property pane should have a toggle to enable time in the datepicker (disabled by default)
- The format options should show formats with time (when time is enabled), and without time (when time is disabled)
- Migrate existing widgets to have this property enabled.

### PR DESCRIPTION
**Pull request by wmdev0808**
## Description
We need a way to allow users to enter only the date in the datepicker

Fixes #3516 

-- Add a new property isTimeEnabled and its corresponding migration

## Type of change

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

## How Has This Been Tested?

- Test A
- Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: feat/3516-datepicker-only-date-option 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 55.17 **(-0.05)** | 36.95 **(-0.07)** | 34.02 **(-0.05)** | 55.67 **(-0.06)**
 :green_circle: | app/client/src/components/propertyControls/DatePickerControl.tsx | 26.32 **(0)** | 6.25 **(1.9)** | 13.33 **(0)** | 25.93 **(0)**
 :red_circle: | app/client/src/utils/DSLMigrations.ts | 73.14 **(-0.75)** | 64.99 **(-0.05)** | 70.21 **(0)** | 72.94 **(-0.77)**
 :red_circle: | app/client/src/utils/migrations/CheckboxGroupWidget.ts | 18.18 **(-54.55)** | 0 **(-66.67)** | 0 **(-100)** | 10 **(-60)**
 :sparkles: :new: | **app/client/src/utils/migrations/DatePickerWidget2.ts** | **18.18** | **0** | **0** | **10**
 :red_circle: | app/client/src/utils/migrations/TableWidget.ts | 80.67 **(-3.36)** | 70.75 **(-4.25)** | 83.33 **(-6.67)** | 81.82 **(-3.83)**
 :sparkles: :new: | **app/client/src/widgets/DatePickerWidget2/constants.ts** | **100** | **100** | **100** | **100**
 :red_circle: | app/client/src/widgets/DatePickerWidget2/component/index.tsx | 27.78 **(0)** | 3.08 **(-0.09)** | 6.25 **(0)** | 27.14 **(0)**
 :red_circle: | app/client/src/widgets/DatePickerWidget2/widget/index.tsx | 64.86 **(-19.14)** | 0 **(0)** | 54.55 **(-20.45)** | 64.71 **(-22.25)**</details>

### CODE REVIEW

**Review by somangshu — DISMISSED** [review]

**Review by jsartisan — APPROVED** [review]
LGTM!

**Review by somangshu — APPROVED** [review]

**Comment by somangshu** [comment]
https://github.com/appsmithorg/appsmith/actions/runs/1443428049

**Comment by vivekverma2312** [comment]
@wmdev0808 Feature is working fine on deploy preview.

**Review by jsartisan — APPROVED** [review]

**Comment by somangshu** [comment]
@wmdev0808 Update with latest release to fix the deploy preview error

**Review by somangshu — APPROVED** [review]

**Comment by somangshu** [comment]
@wmdev0808 seems like this change is breaking a related test, Please check

**Review by jsartisan — APPROVED** [review]

**Comment by somangshu** [comment]
Closing this as the changes are not required any more, For more context checkout the thread on the linked issue

**Pull request closed without merging**
