### PR TITLE
fix: change recaptcha key and type and add suggestion for recaptchaToken

### LINKED ISSUE #8890: [Bug]: Recaptcha V2 Issue
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

A user complained that the Recaptcha V2 does not work

### Steps To Reproduce

1. Drag a button
2. Configure a Recaptcha Key
3. Configure the key in the button
4. Click the button and there is an error about the recaptcha key

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by vicky-primathon**
## Description
Add recaptchaToken in autocomplete suggestion and fix recaptcha dropdown behaviour by changing recaptcha key and type.

Fixes #8890

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/recaptcha-type 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 55.1 **(0.01)** | 36.55 **(0.02)** | 34.49 **(0.01)** | 55.63 **(0.02)**
 :green_circle: | app/client/src/utils/DSLMigrations.ts | 74.15 **(0.15)** | 64.94 **(-0.05)** | 70.21 **(0)** | 73.98 **(0.16)**
 :red_circle: | app/client/src/utils/WorkerUtil.ts | 89.76 **(0)** | 70.59 **(-1.96)** | 100 **(0)** | 93.33 **(0)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.71 **(-0.23)** | 40.83 **(-0.84)** | 36.21 **(0)** | 56.74 **(-0.25)**
 :sparkles: :new: | **app/client/src/utils/migrations/ButtonWidgetMigrations.ts** | **92.86** | **85.71** | **100** | **92.31**
 :green_circle: | app/client/src/widgets/FormButtonWidget/widget/index.tsx | 65.71 **(1)** | 19.05 **(0)** | 62.5 **(0)** | 64.71 **(1.07)**</details>

### CODE REVIEW

**Comment by Tooluloope** [comment]
@vicky-primathon Could you help fix the conflicts

**Review by Tooluloope — DISMISSED** [review]
LGTM
Could you add cypress tests for this fix

**Review by Tooluloope — APPROVED** [review]

**Comment by vivekverma2312** [comment]
@vicky-primathon Observed few issues:
1. When i use v3 `recatchaKey` and keep `captcha version` as v2 it is still generating token
2. When I use v2 `recatchakey` and keep `captcha version` v3 it do not throw any error
3. Token is generating even after editing the `recatchakey` for `captcha version` v2
[LOOM DEMO](https://www.loom.com/share/922cbc89d509453080cfed563713706d)

**Comment by vicky-primathon** [comment]
> @vicky-primathon Observed few issues:
> 
> 1. When i use v3 `recatchaKey` and keep `captcha version` as v2 it is still generating token
> 2. When I use v2 `recatchakey` and keep `captcha version` v3 it do not throw any error
> 3. Token is generating even after editing the `recatchakey` for `captcha version` v2
>    [LOOM DEMO](https://www.loom.com/share/922cbc89d509453080cfed563713706d)

@vivekverma2312  this cross working of Google Recaptcha key for both v2 and v3 cannot be detected as no error is being generated when we use v2 key for v3 and vice versa. We get error only when key itself is invalid/incorrect. Can we find solution to this problem in a separate issue as the blockers are resolved in this PR.

**Comment by vicky-primathon** [comment]
> * When I use v2 `recatchakey` and keep `captcha version` v3 it do not throw any error
> * Token is generating even after editing the `recatchakey` for `captcha version` v2
@vivekverma2312  as discussed with you these two issues are tested on release also and behaviour is same. 
2. Same as on release
3. Same as on release

**Comment by vivekverma2312** [comment]
> Details

@vicky-primathon sure. I have raise a separate issue for this #10027

**Pull request merged**
