### PR TITLE
feat: Moved UserProfileImagePicker from ads folder

### PR DESCRIPTION
**Pull request by albinAppsmith**
## Description

This PR have moved UserProfileImagePicker component from ads folder to pages/UserProfile.

Fixes [#17110](https://github.com/appsmithorg/appsmith/issues/17110)

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Tested in local system

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by tanvibhakta — COMMENTED** [review]
oh - why are we leaving this component within the repository instead of moving it to the design-system repository?

**Review by tanvibhakta — DISMISSED** [review]

**Comment by shadabbuchh** [comment]
PR is tested, no issues found.

**Review by tanvibhakta — APPROVED** [review]

**Pull request merged**
