### PR TITLE
fix: commit icon of github on airgapped, the app crashes. #33812

### PR DESCRIPTION
**Pull request by VigneswarV**
Screenshot after Solving the app crash.
image

**Bug Fixes:**
Page crashes happened because of null pointer exception from front-end code, fixed that one.

Fixes : #33812 .

## Summary by CodeRabbit

- **Bug Fixes**
	- Improved error handling in the `ReconnectSSHError` component to prevent crashes due to undefined nested properties using optional chaining.

### CODE REVIEW

**Comment by akshayvijayjain** [comment]
@rohan-arthur , please assign reviewer to this small and easy to review pr

**Comment by akshayvijayjain** [comment]
@rohan-arthur , gentle reminder for reviewing @Nikhil-Nandagopal ,

it is a small fix. Let us know your feedback

**Comment by rohan-arthur** [comment]
Have passed this on to the concerned team, they'll be in touch

**Comment by brayn003** [comment]
@VigneswarV apologies for the late response. I will take a look at this PR

**Review by brayn003 — APPROVED** [review]

**Comment by brayn003** [comment]
CI tests running at https://github.com/appsmithorg/appsmith/pull/35454

**Pull request merged**
