### PR TITLE
chore: Update CI test to add CS release image instead of mocking CS response

### PR DESCRIPTION
**Pull request by abhvsn**
https://theappsmith.slack.com/archives/C0134BAVDB4/p1687775438002889

EE PR: https://github.com/appsmithorg/appsmith-ee/pull/1908

### CODE REVIEW

**Review by yatinappsmith — DISMISSED** [review]

**Comment by abhvsn** [comment]
TBP run is also successful on CE repo: https://github.com/appsmithorg/appsmith/actions/runs/5610966962

**Comment by abhvsn** [comment]
EE runs are failing https://github.com/appsmithorg/appsmith-ee/actions/runs/5658599590 and this needs much more efforts to replace the dependency from TED. For now as we want to ship the signature verification PR I'm creating 2 different env variables for setting the CS url. For CI purpose both will have different values till all the services are shifted to CS.

**Comment by abhvsn** [comment]
TBD running at: https://github.com/appsmithorg/appsmith/actions/runs/5671028740

**Review by vishnu-gp — APPROVED** [review]

**Pull request merged**
