### PR TITLE
fix: The date data in ISO 8601 format is throwing Invalid date on table widget

### LINKED ISSUE #9494: [Bug]: The date data in ISO 8601 format is throwing Invalid date on table widget
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Data.
[
  {
    "dt": "2021-05-26T09:37:17.918372Z"
  },
  {
    "dt": "2021-05-26T09:32:52.454223Z"
  }
]

Screenshot 2021-12-01 at 3 51 07 PM

### Steps To Reproduce

1. Drag and drop a table widget
2. Enter the above mentioned data in the table data
3. Open property pane and click on dt column
4. Change the type to Date
5. Change the date format to ISO 8601
6. Observe invalid date error on table widget

Discord link: https://discordapp.com/channels/725602949748752515/760761686549463060/915541160947253288

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by wmdev0808**
## Description

-- Fix on wrong ISO8601 format token

Fixes #9494 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Test A
- Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>
No changes to code coverage between the base branch and the head branch</details>

### CODE REVIEW

**Review by somangshu — APPROVED** [review]
change LGTM

**Comment by somangshu** [comment]
This works as expected on the deploy preview, You are good to go @wmdev0808

**Comment by tazmaniax** [comment]
This is great! When will this be live on the cloud version? thx

**Pull request merged**
