### PR TITLE
fix: page number calculation for the last page of table widget

### LINKED ISSUE #18574: [Bug]-[1280]:No. of pages change when i reach the last page of a table
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When a table with -
1. server side pagination turned on
2. total record count is set

If the last page of the table doesn't have the same number of records as previous page then the pages are recalculated and this leads to confusion

### Steps To Reproduce

1. Add a table with server side pagination configured
2. Configure the total record count
3. Make sure the last page has lesser records than previous page
4. Observe the calculation re-occurs when the user reaches the last page

### Public Sample App

_No response_

### Issue video log

https://www.loom.com/share/3eb6488b3e7944f2a475e667dcfcbfa7

### Version

Cloud

Front logo [Front conversations](https://app.frontapp.com/open/top_61fgs)

### PR DESCRIPTION
**Pull request by keyurparalkar**
## Description

The intention of this PR is to fix the incorrect page number on the last page of the table widget. When SSP(Server side pagination) is turned on and the last page of the table doesn't have the same number of records as previous page then the pages are recalculated and this leads to confusion.

The above bug was introduced with this PR: [fix: Incorrect page count when number of records in page is different from page size #17535](https://github.com/appsmithorg/appsmith/pull/17535) and the fix is to revert these changes.

Fixes #18574

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by sbalaji1192 — APPROVED** [review]

**Review by sbalaji1192 — APPROVED** [review]

**Comment by chandannkumar** [comment]
Tested this PR and LGTM

**Pull request merged**
