### PR TITLE
fix: allow ipv4 address in video widget

### LINKED ISSUE #25386: [Bug]:This value does not evaluate to type Video URL
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I try to give a static Ip address to the video widget, it returns: "This value does not evaluate to type Video URL."
The strange thing is when I bind the I.P. address to an Iframe with a 'video' tag, it works.
I'm on the latest version (1.9.27), self-hosted with Docker.

### Steps To Reproduce

1. Drag a video widget to the canvas
2. Try to use an IP address for the URL. 

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

Cloud & Self - Hosted 1.9.27

### PR DESCRIPTION
**Pull request by patrickdemers6**
## Description
Expands the Video Widget url field's regex to support ipv4 addresses.

The regex expects:
- protocol
- auth
- hostname or ip (required, all other portions optional)
- port
- path/params

#### PR fixes following issue(s)
Fixes #25386

#### Media

https://github.com/appsmithorg/appsmith/assets/12687723/ce216b40-c377-4432-a69e-7697ab273c7f

#### Type of change
- Bug fix (non-breaking change which fixes an issue)

#### How Has This Been Tested?
Tested a variety of valid URLs in an online regex editor to confirm they all continue to work. Also verified malformed strings fail.

- [X] Manual

#### Test Plan
New contributor, not sure what to put here.

#### Issues raised during DP testing
N/A

#### Dev activity
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

## Summary by CodeRabbit

- **Bug Fixes**
	- Enhanced video URL validation in the Video Widget to support a wider range of formats and IP addresses.

### CODE REVIEW

**Comment by patrickdemers6** [comment]
<activity>

Would appreciate a review of this PR.

**Comment by somangshu** [comment]
@patrickdemers6 did not see this earlier, can you please update this PR with the latest release branch?

**Review by somangshu — APPROVED** [review]

**Comment by somangshu** [comment]
@jnikhila do we need the documentation updated here?

**Comment by jnikhila** [comment]
> @jnikhila do we need the documentation updated here?

@harshilp24

**Comment by harshilp24** [comment]
> > @jnikhila do we need the documentation updated here?
> 
> @harshilp24

I'll update the Video reference doc

**Comment by somangshu** [comment]
I have tested this on the deploy preview, working fine. 
Change LGTM

**Comment by somangshu** [comment]
@sbalaji1192 some related tests have failed. Can you help the author?

**Review by sbalaji1192 — APPROVED** [review]

**Comment by patrickdemers6** [comment]
Struggling to get local environment setup right to get those failing tests to execute. I will work on it today/tomorrow and join Discord to ask questions as applicable.

**Comment by somangshu** [comment]
@patrickdemers6 before that, please merge the latest release here and let us know. 
Maybe something that we have changed on our as well.

**Comment by sbalaji1192** [comment]
@patrickdemers6 Let me know if you need help in merging this changes to release.

**Comment by patrickdemers6** [comment]
@sbalaji1192 thanks for the bump. I rebased with release.

I figured out the tests were failing due to updated regex not including subdomains. `appsmith.com` was passing but `assets.appsmith.com` was not. Added the missing `\.` to the regex.

**Review by sbalaji1192 — APPROVED** [review]

**Comment by sbalaji1192** [comment]
@patrickdemers6 I have triggered the tests. Lets wait for the results.

**Comment by sbalaji1192** [comment]
@patrickdemers6 We have merged your changes to the release. Thanks for working on this!
Feel free to go through our open issues.:)

**Pull request merged**
