### PR TITLE
feat: Add preview data for mongo mock db

### LINKED ISSUE #27030: [Feature]: Client side changes for Mock MongoDB Preview Page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Allow preview page to be shown in mock mongoDB datasources.

### Why should this be worked on?

To test out some hypothesis:

whether users are generating pages by the schema preview
whether after visualising the preview data, users are actually connecting to their actual mongo database

### PR DESCRIPTION
**Pull request by Irongade**
This PR introduces Preview data feature for Mock MongoDB Datasources.

Fixes #27030 

- New feature (non-breaking change which adds functionality)

- [x] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [x] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [x] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [x] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by sneha122 — APPROVED** [review]

**Review by sneha122 — APPROVED** [review]

**Review by ayushpahwa — APPROVED** [review]

**Comment by prapullc** [comment]
Enhancement : 
1) EE environment : We display the schema on the review page but the user does not know which schema  is being displayed (Prod or staging) specifying such environment details will bring in more user experience.
cc: @rohan-arthur

**Pull request merged**
