### PR TITLE
fix: Change the value of pageOffset when enabling server side pagination

### LINKED ISSUE #36022: [Bug]: The table displays incorrect data when server-side pagination is enabled, and the length of the last page is less than the pageSize value.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The pageOffset value is working incorrectly if the last page of the table widget has a length less than the pageSize value.

### Steps To Reproduce

1. Drag and drop a table widget
2. Using PostgreSQL as the datasource.
3. Click the 'Connect Data' button to select table, and Appsmith will automatically generate the query.
2567-08-30 at 22 38
4. Appsmith use the pageOffset prop for query offset
2567-08-30 at 22 39
5. Press the 'Next Page' button until reaching the last page, then press the 'Previous Page' button, the data displayed in the table will be incorrect, according to the example in the [video](https://www.loom.com/share/2036895ffb8941b1954183f982261f0e?sid=121fc0ef-e4f7-456c-9478-65173d7a534b).
6. The pageOffset value was 64 before changing to 80 on the pageNo = 9.

### Public Sample App

https://app.appsmith.com/app/server-side-pagination/page1-66d1dde63ec3612915d62a75

### Environment

Production

### Severity

Medium (Frustrating UX)

### Issue video log

https://www.loom.com/share/2036895ffb8941b1954183f982261f0e?sid=121fc0ef-e4f7-456c-9478-65173d7a534b

### Version

Cloud - 1.38.0

### PR DESCRIPTION
**Pull request by phennapa-saeliw**
## Description
Fixed issue  #36022 where incorrect data is displayed when navigating to the previous page after reaching the last page with fewer items in the table during server-side pagination enabled by using `props.pageSize` instead of `props.tableData?.length`.

Fix:

Replaced `props.tableData?.length` with `props.pageSize` to ensure consistent data display when navigating between pages, especially when dealing with the last page that has fewer items than the pageSize.

Fixes #36022

## Automation

/ok-to-test tags="@tag.Table"

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [x] No

## Summary by CodeRabbit

- **New Features**
	- Improved pagination logic for the table widget, simplifying the handling of page size.

- **Bug Fixes**
	- Resolved potential inconsistencies in pagination when server-side data is utilized.

### CODE REVIEW

**Comment by jacquesikot** [comment]
@phennapa can you please remove changes in cypress/scripts/.yarn. There should only be 1 file change in this PR

**Comment by phennapa-saeliw** [comment]
> @phennapa can you please remove changes in cypress/scripts/.yarn. There should only be 1 file change in this PR

Thanks. I have deleted the files as per your suggestion.

**Review by jacquesikot — APPROVED** [review]

**Pull request merged**
