### PR TITLE
feat: add clear all option to columns field in google sheets plugin

### LINKED ISSUE #15030: [Enhancement]: Google Sheets - Fetch Many, on choosing Sheet Rows, Columns section could have a Clear All option
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On choosing Fetch Many -> Sheet Rows, from a particular sheet, the user can choose specific columns that he wants to fetch. Here, for clearing the column selection all at once, a Clear All option will be a good to have. 

### Steps To Reproduce

1. Create a google sheets data source, and create a Query to that data source.
2. Choose Operation as Fetch Many , Entity as Sheet Rows, choose a spreadsheet and the sheet within it. 
3. Choose a few columns from that sheet, from Columns dropdown, and click RUN. Data from those specific columns will appear. 
Now, if we want data from all columns, we need to remove the columns one by one from the columns dropdown. If there was a Clear All option, would be easier for the user to remove the columns in one shot.

GSheets_ClearAll
 

### Public Sample App

_No response_

### Version

Release

### PR DESCRIPTION
**Pull request by AnnaHariprasad5123**
HI  @Nikhil-Nandagopal @rohan-arthur @btsgh ,

Fixes #15030 

What's in this PR?

- Add Clear all option to the columns field by using allowClear prop to select component in google sheets datasource.
- Add clearAllOptions function to apply the clear all options functionality.

**Screenshots :**

Earlier :
image

Now :
image

## Summary by CodeRabbit

- **New Features**
  - Added a clear selection functionality to the dropdown, allowing users to easily clear all selected options.

- **Tests**
  - Implemented new tests for the dropdown functionality to ensure proper rendering and user interactions, including selecting and clearing options.

### CODE REVIEW

**Comment by AnnaHariprasad5123** [comment]
HI @rohan-arthur, Could you assign anyone to review this pr.

**Comment by NilanshBansal** [comment]
@AnnaHariprasad5123 thanks for your contribution to Appsmith. We will review this PR in a few days. 
Thank You for your patience 🙏 
cc: @rohan-arthur @carinanfonseca

**Comment by NilanshBansal** [comment]
@AnnaHariprasad5123 the screenshots in the description are not visible, can you please update them.

**Comment by AnnaHariprasad5123** [comment]
HI @NilanshBansal, I updated the images. Could you check once.

**Comment by NilanshBansal** [comment]
https://github.com/user-attachments/assets/a6059f40-a1dc-47d4-80e4-44dd8204462f

Before
image

After
image

@carinanfonseca can you please review this from Design POV?

**Comment by NilanshBansal** [comment]
> Screen.Recording.2024-07-15.at.11.04.07.AM.mov 
> Before image
> 
> After image
> 
> DP link for testing: https://ce-34915.dp.appsmith.com/ @carinanfonseca can you please review this from Design POV?

As per discussion with Carina, the design is approved!
@AnnaHariprasad5123 you just need to add some unit tests as suggested by Sneha, and we should be good to go ahead with the merge

**Comment by AnnaHariprasad5123** [comment]
Sorry @NilanshBansal, I couldn't find the test file. Is there a test file already, or should I create a new one? If it exists, could you send me the path of the file?

**Comment by sneha122** [comment]
> Sorry @NilanshBansal, I couldn't find the test file. Is there a test file already, or should I create a new one? If it exists, could you send me the path of the file?

You would have to create one, there isn't existing test file for this component. You can create one `components/formControls/ `location

**Comment by AnnaHariprasad5123** [comment]
Hi @NilanshBansal, @sneha122 

I am having difficulty writing a test case for DropdownControl. I wrote two test cases: one is passing, but the other is failing because the options are not found in the DOM. I've tried different methods to resolve this issue but am unsure if I'm writing the test cases correctly for this component. Any guidance would be greatly appreciated.

image

**Comment by sneha122** [comment]
Hi @AnnaHariprasad5123 Can you please share the test cases you have written? It will be great if you can commit those changes.

**Comment by AnnaHariprasad5123** [comment]
Hi @sneha122, @NilanshBansal

I'm unable to locate the 'Clear All' button in the test case, which is why the second test case is failing. 

image

**Comment by sneha122** [comment]
> Hi @sneha122, @NilanshBansal
> 
> I'm unable to locate the 'Clear All' button in the test case, which is why the second test case is failing.
> 
> image

Hello @AnnaHariprasad5123 It is able to find the clear all button but not able to remove options for some reason, if it would have failed to find the clear all button, test would have failed in this line `expect(clearAllButton).toBeInTheDocument();`, but instead it failed after this where we check for options to be 0. You can further try adding console logs in clearAllOption function itself and try to debug at what point it is failing to clear option during test execution. Let me know if this doesn't help

**Comment by AnnaHariprasad5123** [comment]
HI @sneha122, Thanks for your suggestion. We just need to wait after click event 😅. Now tests are passed.
image
If everything is ok now, Could you merge this pr.

**Review by sneha122 — APPROVED** [review]

**Review by sneha122 — DISMISSED** [review]

**Review by NilanshBansal — APPROVED** [review]

**Comment by NilanshBansal** [comment]
@AnnaHariprasad5123 `Quality checks / client-lint / client-lint (pull_request)` linting check is failing in this PR.
Can you please fix that.
cc: @sneha122

**Comment by AnnaHariprasad5123** [comment]
> Hey @AnnaHariprasad5123, Can you please fix these linting errors ? Let us know if you need help to solve those.
> 
> Screenshot 2024-07-17 at 1 58 37 PM

Can you guide with instructions.

**Comment by AmanAgarwal041** [comment]
Hey @AnnaHariprasad5123 ,
For the `DropDownControl.test.tsx` : https://github.com/testing-library/eslint-plugin-testing-library/blob/main/docs/rules/prefer-find-by.md

For the `DropDownControl.tsx` you will have to arrange the props in the alphabetical order :
Screenshot 2024-07-17 at 2 05 23 PM

**Comment by AnnaHariprasad5123** [comment]
Hi @AmanAgarwal041, I got it. Could you check once by running the client-lint workflow.

**Comment by AnnaHariprasad5123** [comment]
Hi @NilanshBansal , could you check now.

**Comment by AnnaHariprasad5123** [comment]
Thanks @sneha122, @NilanshBansal, @AmanAgarwal041

**Comment by NilanshBansal** [comment]
Thanks @AnnaHariprasad5123 I have triggered the tests on the shadow PRs, once the tests pass will merge this PR in!

**Pull request merged**
