### PR TITLE
fix: #8911 auto complete property updated

### LINKED ISSUE #8911: [Feature] Include filteredTableData in table's autocomplete
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Include `filteredTableData` in autocomplete properties for a Table Widget entity.

### Why should this be worked on?

Some Appsmith developers do not realise that the filtered values from the table can be accessed using `filteredTableData`. So far this has only been an internal property.

### PR DESCRIPTION
**Pull request by vibhandikyash**
## Description

Include filteredTableData in autocomplete properties for a Table Widget entity. 

Fixes #8911 

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Tested manually.
- Cypress tests added to verify that `filteredTableData` can be bound correctly.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>

    // Code coverage diff between base branch:release and head branch: fix/8911-filteredTableData-in-autocomplete 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | app/client/src/selectors/commentsSelectors.ts | 85.25 **(1.64)** | 64.71 **(2.95)** | 73.33 **(0)** | 90.59 **(2.35)**</details>

### CODE REVIEW

**Comment by somangshu** [comment]
Request for reviews within the team is recommended. Also please keep track of you PRs that are getting stale

**Review by riodeuno — APPROVED** [review]

**Comment by riodeuno** [comment]
@vibhandikyash Let's add a cypress test which will test the `{{filteredTableData}}` binding. We just need to create a new DSL which will have a Table Widget with some search, sort and filters applied. We can then test the binding of `filteredTableData[0]` in a Text Widget

**Review by riodeuno — APPROVED** [review]
Looks good to me!

**Review by riodeuno — APPROVED** [review]

**Review by riodeuno — DISMISSED** [review]

**Review by jsartisan — APPROVED** [review]

**Pull request merged**
