### PR TITLE
test: bugAutomation4136

### PR DESCRIPTION
**Pull request by NandanAnantharamu**
## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: test/bug4136 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 55.72 **(0)** | 37.06 **(0.01)** | 35.79 **(0)** | 56.08 **(0)**
 :green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.94 **(0.23)** | 41.67 **(0.84)** | 36.21 **(0)** | 56.99 **(0.25)**</details>

### CODE REVIEW

**Review by Aishwarya-U-R — COMMENTED** [review]
Approving!

**Review by yatinappsmith — APPROVED** [review]

**Pull request merged**
