### PR TITLE
chore: Updating the logic for fetching workspace when share modal is opened

### PR DESCRIPTION
**Pull request by ankitakinger**
## Description

Updating the logic for fetching workspace when share modal is opened

#### PR fixes following issue(s)
Fixes [#27186](https://github.com/appsmithorg/appsmith/issues/27186)

#### Type of change
- Bug fix (non-breaking change which fixes an issue)

#### How Has This Been Tested?
- [x] Manual
- [ ] JUnit
- [ ] Jest
- [x] Cypress

#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Comment by RakshaKShetty** [comment]
@ankitakinger  tested below scenarios
1. Shared the app with Admin, Developer, app viewer access for different 3 users from Home page Share Modal, Edit mode share modal, share modal from view mode
2. So the users here has correct access and the Share modal in edit mode is displayed with the Workspace name and the required rams for app share and custom role 
3. for app viewer from edit mode when we deploy and also launch it from the home page in this both the scenario the share modal is displayed with the app name and followed by only app share ram and app viewer role in roles dropdown

Public app -> Share modal will be seen but no data is displayed when user is not signed in but when user is signed in  if the user have that app access based on the role that will be displayed in the roles dropdown with a app name as a title in share modal
Please let me know if i have missed anything here

**Comment by ankitakinger** [comment]
@RakshaKShetty What happens in case its a public app and a signed in user who doesn't have access to the app?

**Comment by RakshaKShetty** [comment]
@ankitakinger it doesn't show the dropdown 
image

**Comment by ankitakinger** [comment]
@RakshaKShetty Thanks. All looks good in that case. Lets wait for the tests to complete. After which I will merge the PR in.

**Review by dipyamanbiswas07 — DISMISSED** [review]
LGTM

**Review by dipyamanbiswas07 — APPROVED** [review]

**Pull request merged**
