### PR TITLE
feat: Spellcheck property for the input widget

### LINKED ISSUE #7328: [Feature] Spellcheck and autocomplete properties for the input widget
## Summary

HTML's API allows for some neat features which can be enabled or disabled in the input widget.

-  [ ] Spellcheck

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/spellcheck

These should be disabled by default.

De-scoped: 
-  [ ] Autocomplete - https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete

### PR DESCRIPTION
**Pull request by wmdev0808**
## Description
HTML's API allows for some neat features which can be enabled or disabled in the input widget.
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/spellcheck

Fixes #7328 

## Type of change

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

## How Has This Been Tested?

- Test A
- Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: feat/7328-spellcheck-autocomplete 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 54.86 **(0)** | 36.56 **(0)** | 33.62 **(0.01)** | 55.39 **(0)**
 :green_circle: | app/client/src/widgets/InputWidget/widget/index.tsx | 62.14 **(0.38)** | 41.67 **(0)** | 69.57 **(1.39)** | 64.29 **(0.37)**</details>

### CODE REVIEW

**Comment by riodeuno** [comment]
@somangshu @wmdev0808 Let's put the `spellcheck` after the `auto focus` toggle.

**Comment by wmdev0808** [comment]
> 1. abbreviations

1. spellcheck itself does not support any languages, it is a flag to identify whether a browser should spell check an input element. It doesn't support SMS abbreviations(It is browser-specific. if you add custom words in browser's Settings > Languages > Spellcheck > Customize spell check > Add a word you want to allow).
In addition, when I type the same string as yours, wat der is marked as errors
2. If this is really bug, @marks0351 I need your help

**Comment by shwetha-ramesh** [comment]
@wmdev0808 
1. I checked with other QA member abbreviations like 'wat' 'der' are not highlighted in red. I request you to discuss with other members and see how we can resolve this.
2. Can we please maintain the consistency in both edit and deploy mode.

**Comment by wmdev0808** [comment]
> @wmdev0808
> 
> 1. I checked with other QA member abbreviations like 'wat' 'der' are not highlighted in red. I request you to discuss with other members and see how we can resolve this.
> 2. Can we please maintain the consistency in both edit and deploy mode.

@shwetha-ramesh , @somangshu will give you the answer

**Comment by somangshu** [comment]
@Shwetha Ramesh for the issue pointed out
The words you are trying are either in the english language or present in the local keyboard dictionary, We have simple used the default provided by the system. You could also try doing the same with other apps on your machine and see its highlighted or not
Some functionality which are really functional / relevant on the deploy preview only can be prioritised lower. However if required you could create a new issue which could be prioritized in the future (if still relevant)

**Comment by shwetha-ramesh** [comment]
@wmdev0808 Tested the PR in Firefox browser both the issues seems to be working fine there. To conclude these two issues are noticed only to browser & machine specific (Chrome & Edge). 

Moving this to _Done._

**Pull request merged**
