### PR TITLE
Fixed bug #729: When email ID is long, 'invite' button starts peeking out of the window

### PR DESCRIPTION
**Pull request by ishaanmehta4**
Changed CSS to prevent share button from coming out of the dialog.
Decreased the width of the wrapper to a suitable value.

### CODE REVIEW

**Comment by ishaanmehta4** [comment]
#729 is targeted by this bug fix.

**Comment by hetunandu** [comment]
Hey @ishaanmehta4 we had an issue with our CI runs which did not run the tests properly. Can you rebase/merge the latest release branch into your branch to fix this?

**Comment by ishaanmehta4** [comment]
@hetunandu It seems the branch is up to date with the release branch already..


Screenshot 2020-10-06 120201

**Comment by hetunandu** [comment]
Can you pull new release changes? Seems like your release is out of date

**Comment by ishaanmehta4** [comment]
I have updated my local fork @hetunandu

**Comment by ishaanmehta4** [comment]
@hetunandu all checks passed!

**Comment by hetunandu** [comment]
Thanks for this as it helped me uncover one more issue. Can you pull the latest release and merge that again? Sorry to make you go through this 😕

**Comment by ishaanmehta4** [comment]
@hetunandu its ready.

**Comment by hetunandu** [comment]
Over to you @satbir121

**Comment by satbir121** [comment]
@ishaanmehta4 Please take the pull the latest release into this branch and push?

**Comment by ishaanmehta4** [comment]
@satbir121 done.

**Review by satbir121 — APPROVED** [review]

**Pull request merged**
