### PR TITLE
feat: added onboarding flow for admin users

### LINKED ISSUE #29310: [Task]: 1-click upgrade page, if the user clicks on Get Started, under Community, we show the step "How do you want to start?"
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

_No response_

### PR DESCRIPTION
**Pull request by AmanAgarwal041**
## Description

Earlier we were showing the onboarding experience for the non-admin users only. But we wanted to make it consistent to the admin users as well. After this Pr when the admin users signup/setup, they will see 3 options to start the application.
The following are the list of changes that will be impacted on the experience for the admin users for different edition of appsmith :
- For EE instances when the admin users start the first time setup they see the license screen where they can either start with the free version or enter license key to expeience the paid edition. When a user clicks on the free version get started button, they will be asked the 3 onboarding options to start creating the application. Temporary PR for the EE edition : https://github.com/appsmithorg/appsmith-ee/pull/3196
- For CE instances the same experience will be there when they finish the setup process i.e. they will be shown 3 onboarding options to start creating the application

#### PR fixes following issue(s)
Fixes #29310 
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
- [ ] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

## Summary by CodeRabbit

- **Refactor**
  - Simplified the logic for user role determination on the signup success page. 

- **Documentation**
  - Updated variable declarations to reflect changes in user role logic.

### CODE REVIEW

**Comment by pratapaprasanna** [comment]
> /build-deploy-preview

Just testing it. 
--- @pratapaprasanna

**Comment by AmanAgarwal041** [comment]
Task for removing the telemetry notification : https://github.com/appsmithorg/appsmith/issues/29899

**Review by NilanshBansal — APPROVED** [review]

**Pull request merged**
