### PR TITLE
feat: updated loading, nodata, failed states on preview data screen

### LINKED ISSUE #28986: [Bug]: Wrong Loading, Failed and Nodata states UI on preview data
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Preview data for postgres, mysql, or gsheet have wrong interim state UI 
No data screen : https://www.figma.com/file/kbU9xPv44neCfv1FFo9Ndu/User-Activation?type=design&node-id=3187-16096&mode=design&t=wrfB8fCBsihx665Z-4
Loading screen : https://www.figma.com/file/kbU9xPv44neCfv1FFo9Ndu/User-Activation?type=design&node-id=3187-16224&mode=design&t=wrfB8fCBsihx665Z-4
Failed screen : https://www.figma.com/file/kbU9xPv44neCfv1FFo9Ndu/User-Activation?type=design&node-id=3187-16310&mode=design&t=wrfB8fCBsihx665Z-4

### Steps To Reproduce

1. Create one of mysql, postgres, gsheet datasource
2. Go to view data tab of datasource view mode
3. Observe different states

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

Both

### PR DESCRIPTION
**Pull request by AmanAgarwal041**
## Description

No data screen : https://www.figma.com/file/kbU9xPv44neCfv1FFo9Ndu/User-Activation?type=design&node-id=3187-16096&mode=design&t=wrfB8fCBsihx665Z-4
Screenshot 2023-11-21 at 11 39 53 AM

Loading screen : https://www.figma.com/file/kbU9xPv44neCfv1FFo9Ndu/User-Activation?type=design&node-id=3187-16224&mode=design&t=wrfB8fCBsihx665Z-4
Screenshot 2023-11-21 at 9 40 23 PM

Failed screen : https://www.figma.com/file/kbU9xPv44neCfv1FFo9Ndu/User-Activation?type=design&node-id=3187-16310&mode=design&t=wrfB8fCBsihx665Z-4
Screenshot 2023-11-21 at 11 41 26 AM

#### Limitation
- Retry button on the failed state is not present. https://github.com/appsmithorg/appsmith/issues/29002

#### PR fixes following issue(s)
Fixes #28986
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
- [ ] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Comment by sneha122** [comment]
@AmanAgarwal041 Two things:
1. We should upload these assets.appsmith.com and use it from there
2. Can you please check out this [thread](https://theappsmith.slack.com/archives/C040LHZN03V/p1698740439651169) once? There was a lot of discussion and then Sumit had reverted these exact changes

**Comment by AmanAgarwal041** [comment]
https://github.com/appsmithorg/appsmith/pull/28987#issuecomment-1820858616
1. Updated the first
2. Connected with @carinanfonseca and we have consensus on the states ui.

**Review by sneha122 — APPROVED** [review]

**Comment by AmanAgarwal041** [comment]
Adding the `Test plan approved` label as it has been tested by @sneha122 and @carinanfonseca . Suggested changes by @carinanfonseca have also been addressed.

**Pull request merged**
