### PR TITLE
fix: Issue with the Segmented control in property pane

### LINKED ISSUE #18343: [Bug]: Icon tabs gets deselected on selecting an already selected items
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we select an already selected icon tab control, it gets deselected. At least one of the options should always be selected in most of the icon tab controls.

https://user-images.githubusercontent.com/10436935/203234436-bc0c6b2f-7c6a-451c-9527-420146c65d6d.mov

### Steps To Reproduce

1. Add any widget that has got an icon tab control in it (example: Button widget's buttonVariant property)
2. click the already selected option and notice that none of it is being selected.

### Public Sample App

_No response_

### Issue video log

_No response_

### Version

cloud

### LINKED ISSUE #19658: [Bug]: Can we add default selection when user tries t deselect the value in Scanner Layout in code scanner widget
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Can we add default selection when user tries t deselect the value in Scanner Layout in code scanner widget

### Steps To Reproduce

1. DnD a code scanner widget
2. try to click on the selected value in scanner layoyt

There shud not be any state where there is nothing selected in the scanner layout

### Public Sample App

_No response_

### Issue video log

https://www.loom.com/share/26ec927814a94f8ea74a5fd2a921aed0

### Version

Cloud

### PR DESCRIPTION
**Pull request by aswathkk**
## Description

In the case of IconButtons, clicking an already selected item causes the value to toggle with the last selected value.

- This PR make sure that clicking an already selected button doesn't trigger any events
- This PR adds a default selected value so that at least one value will be selected rather than clearing the entire option.

Fixes #18343
Fixes #19658

Before:

https://github.com/appsmithorg/appsmith/assets/10436935/9d727999-07fb-4985-8446-41cef457fb77

After:

https://github.com/appsmithorg/appsmith/assets/10436935/a3e3deb9-1725-46cf-9ccf-c36228f16390

## Type of change

- Bug fix (non-breaking change which fixes an issue)

- Manual
- Jest
- Cypress

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by dhruvikn — DISMISSED** [review]
LGTM!

**Comment by kamakshibhat-appsmith** [comment]
also, i dont see any DP generated  , can you check ? @aswathkk

**Comment by kamakshibhat-appsmith** [comment]
Button group--> Button settings-->Button type : Once you toggle into JS  mode and remove the value and toggle back, it is not selecting the default value
Screenshot 2023-03-29 at 10 40 34 AM

**Review by dhruvikn — APPROVED** [review]
Looks good to me! 💯

**Comment by rohitagarwal88** [comment]
@Sripriya93 : please test the pr

**Comment by tanvibhakta** [comment]
No ads review required

**Comment by Sripriya93** [comment]
1) All the cases mentioned as same as Case 1 are still happening - If we toggle JS and remove the value and toggle back default value isnt selected
2) For JSON Form: Reset and Submit button, Border radius and Box Shadow aren't highlighted when selected, but the widget's border is changing


https://github.com/appsmithorg/appsmith/assets/104895602/f49ae027-adac-45e1-b2c6-26b@rohitagarwal88 188ba7

@aswathkk @rohitagarwal88

**Review by dhruvikn — APPROVED** [review]

**Comment by aswathkk** [comment]
@Sripriya93 The first issue you mentioned is fixed. I've created an issue for JSON form related bug https://github.com/appsmithorg/appsmith/issues/24067. 
@vasanthappsmith, I've created a separate issue to fix it https://github.com/appsmithorg/appsmith/issues/24068

**Comment by Sripriya93** [comment]
We can close this PR QA done for the issues mentioned above and as other issues are raised separately. @aswathkk @rohitagarwal88

**Pull request merged**
