### PR TITLE
fix: firestore queries asterisk

### LINKED ISSUE #10640: [Bug]: Firestore queries show mandatory asterisk even when they are not
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Screenshot 2022-01-26 at 1 01 46 PM

### Steps To Reproduce

Go the Get documents in collection command in Firestore queries

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by devnamrits**
## Description

Removed asterisk from the non-mandatory fields of Firestore queries.

Fixes #10640 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Changes are being displayed on UI.
Screenshot 2022-03-03 at 6 08 04 PM

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by devnamrits** [comment]
@nidhi-nair @sumitsum Can you please review this PR and merge if it could be?? Eagerly waiting for my first contribution to be pushed in Appsmith. 😅

**Review by sumitsum — APPROVED** [review]

**Comment by devnamrits** [comment]
Thank you very much @sumitsum for approving it. 🙌🏻

**Comment by sumitsum** [comment]
> Thank you very much @sumitsum for approving it. 🙌🏻

@devnamrits we are very grateful for your contribution. We always look forward to our community to help improve Appsmith. We look forward to more such amazing contributions from you. Happy coding :)

**Comment by devnamrits** [comment]
@sumitsum  Sure I'll try to contribute as much as I can. It would be an honor for me!

**Pull request merged**
