### PR TITLE
fix: Adjust status details style in API Response view

### LINKED ISSUE #10959: [Bug]-[120000]:Status details section in the API Response view needs Adjustment
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The API Response view needs to show the success status scenario in its entirety

https://user-images.githubusercontent.com/25982036/152947924-5e6adc8f-a0fe-4dd0-a10c-b589108ffb81.mov

### Steps To Reproduce

1.  Create a GET Request
2. Check the status code.
3. Observe that the success status is not shown in full.

### Environment

Release

### Version

Cloud

### PR DESCRIPTION
**Pull request by danieldare**
## Description
 
- status details in section in the API Response view needs Adjustment

Fixes #10959

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Create a GET Request
- Check the status details.

Screenshot 2022-02-17 at 09 59 10
Screenshot 2022-02-17 at 09 59 17

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/status-code-style-adjustment 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 56.5 **(-0.02)** | 37.97 **(-0.03)** | 35.84 **(-0.02)** | 56.74 **(-0.02)**
 :red_circle: | app/client/src/components/editorComponents/ApiResponseView.tsx | 45.22 **(-4.3)** | 28.32 **(-2.16)** | 0 **(0)** | 46.79 **(-4.21)**
 :red_circle: | app/client/src/selectors/commentsSelectors.ts | 83.61 **(-1.64)** | 61.76 **(-2.95)** | 73.33 **(0)** | 88.24 **(-2.35)**
 :red_circle: | app/client/src/utils/WorkerUtil.ts | 89.76 **(0)** | 70.59 **(-1.96)** | 100 **(0)** | 93.33 **(0)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.71 **(-0.23)** | 40.83 **(-0.84)** | 36.21 **(0)** | 56.74 **(-0.25)**</details>

### CODE REVIEW

**Comment by nidhi-nair** [comment]
@danieldare Looks like this is hiding the right side pane that shows available datasources and connected entities for the 200 scenario. Also, is it possible to modify this logic to only hide the status code if there is a possible overlap?

**Review by Irongade — APPROVED** [review]

**Review by nidhi-nair — CHANGES_REQUESTED** [review]
Needs changes for smaller screen sizes

**Review by Irongade — APPROVED** [review]

**Comment by Irongade** [comment]
Please resolve all failing tests.

**Review by nidhi-nair — COMMENTED** [review]
Waiting on design approval, removing from the review queue.

**Pull request closed without merging**
