### PR TITLE
feat: Added auto commit feature

### LINKED ISSUE #26769: Integrate RTS Migration end point with AutoCommit flow
- Integrate with RTS end point for Applying the migration for the git file system resources
- Add tests for the migration changes
- API end point for the client to call on page load POST /auto-commit

### PR DESCRIPTION
**Pull request by nayan-rafiq**
## Description
This PR adds the auto commit feature for git connected applications.

#### PR fixes following issue(s)
Fixes #26769

#### Type of change
- New feature (non-breaking change which adds functionality)

#### How Has This Been Tested?
- [x] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress

#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

## Summary by CodeRabbit

- **New Features**
  - Introduced an interface to track auto-commit progress and initiate auto-commit for applications.
  - Users can now toggle auto-commit settings for their applications.

- **Bug Fixes**
  - Resolved issues related to branch protection during auto-commits.
  - Enhanced error handling for auto-commit events.

- **Refactor**
  - Removed deprecated method for auto-committing DSL migrations.
  - Streamlined the process of saving applications to local repositories with analytics.

- **Documentation**
  - Updated method comments to reflect changes in saving applications and handling transient fields.

- **Chores**
  - Cleaned up unused imports and variables to improve code clarity.

### CODE REVIEW

**Comment by nayan-rafiq** [comment]
> I have one comment, instead of fetching the entire app resource from the file system, can we just read page data? Although majority of the size comes from widget, we can still save about ~30% of IO. What are your thoughts on this?

@AnaghHegde Thank you for pointing this out. I completely agree with the idea. Bringing this change This will take sometime because we need to refactor the JSON construction code. I'll create a separate PR for that as the current PR is blocking the UI development.

**Comment by AnaghHegde** [comment]
> > I have one comment, instead of fetching the entire app resource from the file system, can we just read page data? Although majority of the size comes from widget, we can still save about ~30% of IO. What are your thoughts on this?
> 
> @AnaghHegde Thank you for pointing this out. I completely agree with the idea. Bringing this change This will take sometime because we need to refactor the JSON construction code. I'll create a separate PR for that as the current PR is blocking the UI development.

Can you please create github issue for this, so that we will not miss this?

**Review by AnaghHegde — APPROVED** [review]

**Pull request merged**
