### PR TITLE
fix: JSONForm RadioGroupField - support numeric values in the options

### LINKED ISSUE #12815: [Bug]-[16]:Unable to select option in Radio Group field type when value is Number on JSON Form widget
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

[LOOM DEMO](https://www.loom.com/share/25292713d76842da8e03b4a50b1f7d66)

### Steps To Reproduce

1. Add Json Form widget onto canvas
2. Add a Radio Group Field type
3. Under Options set value as Number to see the issue
4. Observe that option is not getting selecting on click

### Public Sample App

_No response_

### Version

Cloud/Production

### LINKED ISSUE #13392: [Bug]: JSONForm - Radio Group field - options validation does not validate like Radio Group widget
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The Radio Group field's options properties in the JSON form widget should adhere to the validation rules of the Radio Group widget's options property.

### Steps To Reproduce

1. Drag JSONForm
2. Modify a field to Radio Group
3. In the options property convert one of the option's value to a number
4. Ideally it should throw error `All value properties in options must have the same type`

### Public Sample App

_No response_

### Version

Cloud

### LINKED ISSUE #13393: [Bug]: JSONForm - Radio Group field - Missing validation for default selected value
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The Radio Group field's default selected value property validation is missing in the JSON form widget.

### Steps To Reproduce

1. Drag JSONForm
2. Modify a field to Radio Group
3. In the default selected value enter `{{true}}` (which is a boolean)
4. Ideally it should throw the error `This value does not evaluate to type: string or number`

### Public Sample App

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by ashit-rath**
## Description

This PR fixes 3 things in Radio Group field
1. Appropriate validation for default options
2. Validation for default value radio group
3. Support numeric values in options

Fixes #13392
Fixes #13393
Fixes #12815

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Cypress test
- Jest test

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/12815-jsonform-radio 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 56.49 **(0.06)** | 37.96 **(0.04)** | 35.83 **(0.01)** | 56.72 **(0.05)**
 :red_circle: | app/client/src/widgets/JSONFormWidget/fields/RadioGroupField.tsx | 47.06 **(-1.33)** | 0 **(0)** | 0 **(0)** | 48.48 **(-1.52)**
 :red_circle: | app/client/src/widgets/JSONFormWidget/widget/propertyConfig/properties/radioGroup.ts | 40.91 **(-4.54)** | 0 **(-100)** | 0 **(0)** | 40.91 **(-4.54)**
 :green_circle: | app/client/src/widgets/RadioGroupWidget/widget/index.tsx | 63.81 **(34.96)** | 51.28 **(46.15)** | 64.29 **(14.29)** | 63 **(33.71)**</details>

### CODE REVIEW

**Review by sbalaji1192 — DISMISSED** [review]

**Comment by vivekverma2312** [comment]
@ashit-rath I see this branch has conflicts. Can you please resolve it so that we can start testing it.

**Comment by vivekverma2312** [comment]
@ashit-rath Tested the mention issues and it's working fine.

**Review by sbalaji1192 — APPROVED** [review]

**Review by Ash1818 — COMMENTED** [review]
Owner

**Pull request merged**
