### PR TITLE
feat: Add keyboard navigation for dropdown

### LINKED ISSUE #6691: [Bug] Tab key control does not move to a dropdown value hence user cannot change value using keyboard
## Description
When using **Tab** key to move control through the property pane, control does not move inside of a dropdown hence user is unable to make a selection using keys

### Steps to reproduce the behaviour:
1. Drag and drop a text widget on to the canvas
2.  Use **tab** key to move control on the property pane of the widget and observe that control does not move to dropdown property

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Production

### PR DESCRIPTION
**Pull request by aswathkk**
## Description

Makes the dropdown keyboard accessible

Fixes #6691

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Tested manually by clicking above dropdown and then pressing Tab to focus the dropdown.
- Enter/Space keys to open dropdown
- ArrowUp/ArrowDown keys to select items from dropdown
- Enter/Space keys to select highlighted item

Added Jest tests as well.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: feat/dropdown-keyboard-navigation 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 55.05 **(0.11)** | 36.49 **(0.17)** | 34.45 **(0.22)** | 55.58 **(0.12)**
 :green_circle: | app/client/src/components/ads/Dropdown.tsx | 81.71 **(22.1)** | 61.34 **(13.99)** | 70.42 **(33.11)** | 80.97 **(21.61)**
 :green_circle: | app/client/src/selectors/commentsSelectors.ts | 85.25 **(1.64)** | 64.71 **(2.95)** | 73.33 **(0)** | 90.59 **(2.35)**
 :red_circle: | app/client/src/utils/WorkerUtil.ts | 89.76 **(0)** | 70.59 **(-1.96)** | 100 **(0)** | 93.33 **(0)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.71 **(-0.23)** | 40.83 **(-0.84)** | 36.21 **(0)** | 56.74 **(-0.25)**</details>

### CODE REVIEW

**Review by SatishGandham — APPROVED** [review]

**Comment by vivekverma2312** [comment]
@aswathkk Tested for drop-down and it's working fine with Tab key.

**Pull request merged**
