### PR TITLE
fix: Column tile reposition on focus state of Input element inside property pane configuration for Table and Tabs widget

### LINKED ISSUE #9188: [Bug]: Column name on property pane changes on changing the order
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[LOOM DEMO](https://www.loom.com/share/54029a63fe7143f6a86a5ccddf04993d)

### Steps To Reproduce

1. Drag and drop a table widget
2. Open the property pane
3. Click on any column name in property pane and drag to change the order
4. Observe that previous column name on property pane changes to same name

### Environment

Production

### Version

Cloud

### LINKED ISSUE #9826: [Bug]: Incorrect focused state while dragging the column sequence in table widget
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I try to change the sequence of columns for the table widget then the focus state does not appear for the column which was dragged but instead the column above the dragged one gets focused. 

Below video demonstrates this behaviour:

https://user-images.githubusercontent.com/14138515/146379775-fb01c6d5-0f41-4d7c-8e57-ee62badf6f4e.mp4

The above video will also demonstrates that it appears to happen in both the ways i.e. dragging from top to bottom or bottom to top.

### Steps To Reproduce

1. Drag and drop the table widget on the canvas.
2. Under the columns property of the table widget, try to change the sequence by first clicking the textfield to edit the row label, then drag the clicked row(mouse down state) down.
3. Similarly, try to move a column up in the sequence.

### Environment

Production

### Version

Cloud

### LINKED ISSUE #10030: [Bug]: Unable to edit the sub menu options in most of the widgets after repositioning the sub menus
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It is observed that unable to edit the sub menu options by clicking on the settings icon in most of the widgets like Button group widget, Table column edit, Tab widget

[LOOM DEMO](https://www.loom.com/share/c95928912e11456bab53751c8175fd54)

### Steps To Reproduce

1.Launch Appmsith app in release environment
2.Drag and drop button group widget 
3.Choose any of the sub button menu and click on setting options and observe

Similarly try for table widget and tab widget

### Environment

Release

### Version

Cloud

### LINKED ISSUE #10033: [Bug]: Columns in the property pane changes on repeated clicking. Focused state color is black
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I click on any of the columns in the columns property of the table widget repeatedly, then the columns change their position automatically i.e. columns swap automatically. 
Also, it is observed that the focused state color has changed to black, as previously it was orange.

Please find below for your reference the video for this issue:
https://loom.com/share/c06009491e534d499abfe9fff912c4c2

### Steps To Reproduce

1. Drag and drop the table widget.
2. Go to the columns property in the property pane.
3. Click repeatedly on any of the rows.
4. Observe that they gets swapped automatically.
5. Also observe the focused state color of the row which is selected in this property. 

### Environment

Release

### Version

Cloud

### PR DESCRIPTION
**Pull request by vicky-primathon**
## Description
Fix column tile reposition on focus state of Input element inside property pane configuration for Table and Tabs widget

Fixes #10030
Fixes #10033
Fixes #9826 
Fixes #9188

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/table-column-drag 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 54.96 **(0.02)** | 36.33 **(-0.07)** | 34.65 **(0.04)** | 55.35 **(0)**
 :red_circle: | app/client/src/components/ads/DraggableList.tsx | 35.87 **(-8.39)** | 18.64 **(-14.69)** | 26.67 **(5.24)** | 38.75 **(-12.27)**
 :sparkles: :new: | **app/client/src/components/ads/DraggableListCard.tsx** | **14.29** | **3.45** | **0** | **16.67**
 :red_circle: | app/client/src/components/ads/DraggableListComponent.tsx | 41.03 **(-1.39)** | 18.18 **(-31.82)** | 33.33 **(-4.17)** | 42.42 **(-2.02)**
 :green_circle: | app/client/src/components/propertyControls/ButtonListControl.tsx | 31.51 **(6.79)** | 27.27 **(2.27)** | 11.11 **(2.02)** | 30.99 **(4.07)**
 :green_circle: | app/client/src/components/propertyControls/MenuItemsControl.tsx | 29.58 **(6.59)** | 20.69 **(-1.53)** | 11.11 **(2.02)** | 28.99 **(3.99)**
 :green_circle: | app/client/src/components/propertyControls/PrimaryColumnsControl.tsx | 36 **(5.78)** | 12.31 **(1.2)** | 19.23 **(4.94)** | 34.97 **(4.79)**
 :green_circle: | app/client/src/components/propertyControls/TabControl.tsx | 52.5 **(11.01)** | 38.89 **(3.18)** | 35 **(8.91)** | 51.9 **(7.85)**</details>

### CODE REVIEW

**Comment by shwetha-ramesh** [comment]
@vicky-primathon below are the few issues observed. 

1. Clicking on any column tile in property pane, the tile jumps. Similarly for Page settings 
https://loom.com/share/d5615a9d8bdf455dbbe13264bbf8729c

2. Scrolling downwards is not smooth and there is endless scroll
https://loom.com/share/d14a110284ae45649aa1dcefef701843

3. Any new columns added is not visible, user needs to scroll down to view the new added column in the property pane
https://loom.com/share/40a767353153425a819bfd1be9590196

Testing in progress

**Review by sbalaji1192 — APPROVED** [review]

**Comment by somangshu** [comment]
@shwetha-ramesh I believe the issue for is not related and should be raised separately after checking on release

@vicky-primathon @shwetha-ramesh the issue pointed out also has another challenge also mentioned in #9826, Can we fix this too?

cc @dilippitchika

**Review by marks0351 — APPROVED** [review]
@vicky-primathon can u pls resolve conflicts.

**Review by marks0351 — APPROVED** [review]

**Comment by YogeshJayaseelan** [comment]
@vicky-primathon Tested this PR and please find the status below,

1) Issue #10030 - Fixed

2) Issue raised by @shwetha-ramesh - Issue 1 is fixed, Issue 2 is reopen(refer below video) , issue 3 fixed 

**Re-open**
Issue 2 raised by shwetha - Scrolling downwards is not smooth and there is endless scroll

https://loom.com/share/d14a110284ae45649aa1dcefef701843

**New issue** 

If more number of columns are available and the scroll top/bottom is not working

https://www.loom.com/share/f9a1f38da19b4772af68e250444cd825


3) Issue raised by @keyurparalkar #9826 - **is still open** 

4) Regarding issue #10033 - The tile colour should be Orange or black? currently the title colour is black both on release and prod if we are okay with black then we are good to go on this @somangshu 

5) Issue raised by @vivekverma2312  #9188 - Now this is not happening for table widget but the issue exists for Menu button Widget , Tab Widget and button group widget

**Comment by YogeshJayaseelan** [comment]
@vicky-primathon Tested this PR and please find the status below,

Point 1 - The original issue #10030 is fixed

Point 2 - Issues raised by @shwetha-ramesh 1,2,3 are fixed

Point 3 - Issue raised by myself - 'If more number of columns are available and the scroll top/bottom is not working' is fixed 

Point 4 - Issue raised by @keyurparalkar #9826 - This is fixed now the focused state is proper but there is a slight jump(1-2 seconds)

https://www.loom.com/share/b0f3e238df9b46ab947318b41ed92e95

Point 5 - Issue raised by @keyurparalkar #10033 is fixed 

Point 6 - Issue raised by @vivekverma2312 #9188 is fixed

New issues:

Point 7 - When the column fields focus are half either at the bottom or at the top the scroll is not working - Refer the video below

https://www.loom.com/share/4b26d63ea20f463ba865d342dec59c6d

Point 8 - The column flicks/jumps when the mouse focus is on the mid of the top or bottom outline on any of the column field and clicking on it 

https://www.loom.com/share/9040e2cc329a49a488d7ce71dda7f3bd

**Comment by YogeshJayaseelan** [comment]
@vicky-primathon As discussed will create separate issues for point 4 , 7 and 8

**Comment by somangshu** [comment]
@vicky-primathon is #4266 being taken care of here? I dont see it working on release and prod

**Pull request merged**
