### PR TITLE
fix: remove building blocks on canvas

### LINKED ISSUE #33756: Task: remove building blocks on canvas
Based on recent user testing findings by @carinanfonseca we are removing the building blocks on canvas in current state as they confuse users more than they help.

In addition to this, since we are close to launching drag and drop of BBs on canvas, these don't make sense any more.

[User testing video](https://app.usertesting.com/v/a5e92ded-cacd-4fdd-ad15-9df815257b2c?encrypted_video_handle=9988bfaa-fea1-407b-9c97-bde461f76f57#!/notes&shared_via=link&share_id=m54qWgdhGQ)

### PR DESCRIPTION
**Pull request by rahulbarwal**
## Description
Removes building blocks on canvas feature.

Fixes #33756
_or_  
Fixes `Issue URL`
> [!WARNING]  
> _If no issue exists, please create an issue first, and check with the maintainers if the issue is valid._

## Automation

/ok-to-test tags="@tag.All"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9312996633>
> Commit: f8059ccad5bc6e6297b935d26687b330a373cde8
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9312996633&attempt=2" target="_blank">Click here!</a>

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [x] No

### CODE REVIEW

**Review by jacquesikot — DISMISSED** [review]

**Comment by pratapaprasanna** [comment]
DP is failing here

**Comment by rahulbarwal** [comment]
> DP is failing here

@pratapaprasanna just saw this. What can we do about this? Is this a concern?
I can still access the DP.

**Review by jacquesikot — APPROVED** [review]

**Pull request merged**
