### PR TITLE
fix: Fix default selected row on a page change when primary key is selected in a table and is unavailable in new data

### LINKED ISSUE #24344: [Bug]: Table default selected index doesn't show up when generate CRUD app feature is used with TableV2
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

This issue is required for unblockling CRUD TableV2 PR.

### Steps To Reproduce

1. Generate a CRUD app using GenerateCRUDApp feature using TableV2.
2. Notice that the default selected index row at default selected index doesn't show up.

Expected behavior : The default selected row should show up.

This issue can be tested using cypress tests that are present. It may be difficult to verify this manually in QA Process since CRUD TableV2 changes aren't merged into release yet cc : @laveena-en 

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by rajatagrawal**
Fixes #24344

Steps to repro are in the connected issue.

### CODE REVIEW

**Comment by rajatagrawal** [comment]
> Workflow run: https://github.com/appsmithorg/appsmith/actions/runs/5123143438. Commit: `57d7505`. The following are new failures, please fix them before merging the PR:
> 
> 1. cypress/e2e/Regression/Apps/MongoDBShoppingCart_spec.js
> 2. cypress/e2e/Regression/ClientSide/Templates/Fork_Template_Existing_app_spec.js
> 
> To know the list of identified flaky tests - [Refer here](https://app.appsmith.com/applications/613868bedd7786286ddd4a6a/pages/63ec710e8e503f763651791a)

This test result is for just default selected index changes

**Review by vsvamsi1 — DISMISSED** [review]

**Review by sbalaji1192 — DISMISSED** [review]

**Comment by laveena-en** [comment]
@rajatagrawal 
Default selected row/s must stay intact in the following cases:

- On navigating between pages
- When columns are sorted
- When valid searches are made containing results that include the default selected row 
- When valid searches are removed
- When invalid searches are removed
- On filtering the table data and on deleting the filters set

These scenarios should hold good in case of both single and multiple default row/s.

**Comment by rajatagrawal** [comment]
> @rajatagrawal Default selected row/s must stay intact in the following cases:
> 
> * On navigating between pages
> * When columns are sorted
> * When valid searches are made containing results that include the default selected row
> * When valid searches are removed
> * When invalid searches are removed
> * On filtering the table data and on deleting the filters set
> 
> These scenarios should hold good in case of both single and multiple default row/s.

Had a discussion with @dilippitchika and @sbalaji1192 for resolving these issues. We decided that these issues need product input and can tracked in a separate issue. For the purposes of unblocking CRUD PR, only the test cases where default selected row doesn't show up when a table first loads up in a CRUD flow can be the only test case that needs to be verified for this fix. The issue for that bug is https://github.com/appsmithorg/appsmith/issues/24344

Issue for tracking all other cases of default index is https://github.com/appsmithorg/appsmith/issues/24343.

cc : @laveena-en @somangshu . As per the steps to verify the fix, the only way I think that might be possible to do this would in cypress tests that @keyurparalkar has in his CRUD TableV2 PR. It won't be possible to test this manually I think. Hence I think that this PR can be merged without manual QA. The cypress test suite is passing on it.

**Comment by rajatagrawal** [comment]
@keyurparalkar would you be able to take a pull of this PR in the CRUD PR and check if the blocker issues is fixed ? I think it won't be possible for the QA to verify this manually.

**Comment by rajatagrawal** [comment]
Had a discussion with @keyurparalkar and @sbalaji1192 regarding the callouts for pending test failures related to default selected row index. As per @sbalaji1192 , these failure are invalid and not as per expectations of the feature. Hence @keyurparalkar will be working on changing the assertion in cypress tests in the CRUD PR.

**Review by sbalaji1192 — APPROVED** [review]

**Pull request merged**
