### PR TITLE
test: Upgrade appsmith

### PR DESCRIPTION
**Pull request by arslanhaiderbuttar**
## Type of change

Added tests for updating from old version to latest version.

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Locally

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by NandanAnantharamu — DISMISSED** [review]
LGTM

**Review by yatinappsmith — DISMISSED** [review]

**Comment by yatinappsmith** [comment]
Please split the pr into 2 one for ci and other for cypress

**Pull request closed without merging**
