### PR TITLE
fix: Remove guided tour code

### PR DESCRIPTION
**Pull request by albinAppsmith**
## Description

Removed the guided tour code.

#### PR fixes following issue(s)
Fixes https://github.com/appsmithorg/appsmith/issues/30332

#### Type of change

- Bug fix (non-breaking change which fixes an issue)
- Chore (housekeeping or task changes that don't impact user perception)

- [ ] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

## Summary by CodeRabbit

- **Chores**
  - Streamlined onboarding process by removing guided tour features.
  - Refined action and message management for a more intuitive user experience.
  - Enhanced property controls generation for better user interaction.

- **Refactor**
  - Simplified various components by removing unnecessary guided tour logic.
  - Improved application and page sagas for more efficient operation.
  - Refined editor components for a smoother user interface.

- **Documentation**
  - Updated message constants for clearer user guidance.

### CODE REVIEW

**Review by hetunandu — COMMENTED** [review]
Fix build. Seems like some references still exist for deleted code

**Review by hetunandu — APPROVED** [review]

**Review by ayushpahwa — COMMENTED** [review]
LGTM from datasources perspective.

**Review by KelvinOm — APPROVED** [review]

**Pull request merged**
