### PR TITLE
External contri/issue #15030/feat google sheets clear all option

### PR DESCRIPTION
**Pull request by NilanshBansal**
Fixes #`Issue Number`  
_or_  
Fixes `Issue URL`
> [!WARNING]  
> _If no issue exists, please create an issue first, and check with the maintainers if the issue is valid._

## Automation

/ok-to-test tags="@tag.All"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9971518643>
> Commit: fe1eb8abd7772b655e71fb6488f65d430078af4b
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9971518643&attempt=1" target="_blank">Cypress dashboard</a>.
> Tags: `@tag.All`
> Spec:
> <hr>Wed, 17 Jul 2024 10:15:33 UTC

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by rajatagrawal** [comment]
Can we please have a react testing library jest test for this change ?

cc : @ApekshaBhosale @yatinappsmith

**Review by rajatagrawal — CHANGES_REQUESTED** [review]
Left comments

**Comment by NilanshBansal** [comment]
> Can we please have a react testing library jest test for this change ?
> 
> cc : @ApekshaBhosale @yatinappsmith

@rajatagrawal who is responsible for this task? Asking because we have [asked the contributor to add a unit test](https://github.com/appsmithorg/appsmith/pull/34620#issuecomment-2227907541) for this change which seems different from this task. 

Also, if it is something to work from appsmith qa team, is there an issue that we can track for this 🙏

**Comment by rajatagrawal** [comment]
@NilanshBansal 
Jest unit tests have to go as part of the PR. So the author would need to write the jest test case in the same PR.

**Pull request closed without merging**
