### PR TITLE
feat: clean up datasource review page

### LINKED ISSUE #31801: Task: Clean datasource review page
- Remove Generate CRUD page button

Checkout [Notion card](https://www.notion.so/appsmith/Clean-datasource-review-page-5b9f3fcee1ac4e448c89eb689d2740d2?pvs=4) for more details.

### PR DESCRIPTION
**Pull request by jacquesikot**
## Description
Remove the "Generate new page" button from the datasource review page and make the "New Query" button a primary button. Tests related to the removed generate CRUD page feature have been removed.

Fixes #31801 

## Automation

/ok-to-test tags="@tag.Datasource"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9772204191>
> Commit: 1d77326f4674abe6143d5c7031f91130a4bf5598
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9772204191&attempt=1" target="_blank">Cypress dashboard</a>.
> Tags: `@tag.Datasource`

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [ ] No

## Summary by CodeRabbit

- **New Features**
  - Introduced a feature flag to conditionally show the `Generate Page` button based on the drag and drop building blocks setting.
  
- **Tests**
  - Added tests to verify the rendering of components and buttons based on feature flags and plugin types.

### CODE REVIEW

**Review by rahulbarwal — COMMENTED** [review]
@jacquesikot can you point me to the fix that you've done to address the test that caused the EE failure?

**Comment by jacquesikot** [comment]
@rahulbarwal Line 556. There was a missing state - environment

**Review by rahulbarwal — APPROVED** [review]
LGTM, before merging please create an EE branch and run CI on that to make sure we don't have any more failures with this.

**Comment by jacquesikot** [comment]
@rahulbarwal I create an EE branch, pull the changes in from the CE remote, create a PR on that, and run CI?

**Comment by jacquesikot** [comment]
@rahulbarwal  I have created this PR on EE and tests are passing - https://github.com/appsmithorg/appsmith-ee/pull/4601

**Pull request merged**
