### PR TITLE
fix: update implementation as per design | git

### LINKED ISSUE #16975: [Task]: Git Repo Page UI Inconsistencies
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

If a user reaches 3 repo limit on Git, then we show them a the modal to either upgrade or delete an existing repo. The UI for this is not the same as the design.
Screen Shot 2022-09-21 at 8 36 36 AM

This is the expected UI

image (16)

### PR DESCRIPTION
**Pull request by IAmAnubhavSaini**
## Description

Update implementation as per the designs.

Fixes #16975

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Updated tests.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by IAmAnubhavSaini** [comment]
Four unrelated tests failing.

Screenshot 2022-10-10 at 12 24 36 PM

**Comment by RakshaKShetty** [comment]
@IAmAnubhavSaini the issue is not fixed here i am unable to see the repo names and revoke access link as in screenshot
image

**Review by berzerkeer — APPROVED** [review]

**Comment by RakshaKShetty** [comment]
This issue is not fixed
image

**Comment by RakshaKShetty** [comment]
The issue is resolved now 
image

**Review by mohanarpit — APPROVED** [review]

**Pull request merged**
