### PR TITLE
fix: rich text editor not working on airgapped instance

### LINKED ISSUE #22407: [Bug]: Air Gapped instance - Rich Text editor comes up blank on the canvas
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In an airgapped intstance, on DnD of Rich Text Editor widget, it comes up blank on canvas

### Steps To Reproduce

1. Pull the image with the command docker pull ankitakinger/appsmith:airgap
2. Switch off internet and execute the docker run command
3. Now do the set up
4. Add air gapped license key. 
5. Inside the application, try to DnD a Rich text editor widget. Note that it comes up blank

Screenshot 2023-04-14 at 10 03 08 AM

On Release it is like this - 
RTE_Release

### Public Sample App

_No response_

### Environment

Release

### Issue video log

_No response_

### Version

Self Hosted

### PR DESCRIPTION
**Pull request by berzerkeer**
## Description

- This will import tinymce editor as a module to support airgapped instances.

Fixes #22407 

Media

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by dipyamanbiswas07 — APPROVED** [review]

**Comment by berzerkeer** [comment]
@RakshaKShetty  @btsgh  can you check this DP url and see if rich text editor works as expected.

**Review by dipyamanbiswas07 — APPROVED** [review]

**Review by jsartisan — APPROVED** [review]

**Pull request merged**
