### PR TITLE
fix: codeditor scroll cursor into view 

### PR DESCRIPTION
**Pull request by akash-codemonk**
## Description

Was able to repro the issue on an isolated project where codemirror has auto height and has a scrollable container which does not take the full height of the viewport. Apparently scrolling for this scenario isn't handled in codemirror, related issue https://github.com/codemirror/codemirror5/issues/1104. https://github.com/codemirror/codemirror5/issues/2912#issuecomment-62161976 led me to figure out a solution using `scrollCursorIntoView` event.  
The original source of the solution is from https://github.com/WebKit/WebKit-http/blob/817c46e152af795d735678386db68805d0aa505e/Source/WebInspectorUI/UserInterface/Views/CodeMirrorAdditions.js#L354 .

The solution here partially works in the property pane while scrolling down, but the issue remains while scrolling up. The property pane is wrapped with a position static wrapper and has some sticky headers which might be causing some issues. The fix for the property pane will have to be figured out separately in https://github.com/appsmithorg/appsmith/issues/19293

The solution involves scrolling to the cursor(which is an html element). We use the scroll library to only scroll when the target element is out of view.

Fixes https://github.com/appsmithorg/appsmith/issues/6325

DP: https://appsmith-7fo141hgf-get-appsmith.vercel.app/

Media

https://user-images.githubusercontent.com/67054171/233363358-8622b59d-d573-451b-ab84-22181395f394.mov

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Comment by Richarex** [comment]
Tested the bug fix on the DP url and it looks good to me.

**Review by hetunandu — APPROVED** [review]

**Pull request merged**
