### PR TITLE
fix: all backlog fixes for ads v2

### PR DESCRIPTION
**Pull request by tanvibhakta**
## Description

1. [Text shift](https://www.notion.so/appsmith/Text-shifts-when-we-click-on-the-JS-Toggle-button-7b6b0d91a0d04bbd980762cc9f84931e)

https://github.com/appsmithorg/appsmith/assets/13763558/cbc1e668-83db-4b52-9691-67ce0f2c8e15

2. [Evaluated Value popup copy button compressed](https://theappsmith.slack.com/archives/C0293DVQACW/p1685949223985949)

https://github.com/appsmithorg/appsmith/assets/13763558/6cdbd0af-a509-4df2-8fe5-128716ef9013

3. [Select placeholder in git merge](https://github.com/appsmithorg/appsmith/issues/24091)

https://github.com/appsmithorg/appsmith/assets/13763558/a78fc5b2-eebb-4e53-834c-757102bb3f81

4. [Replace gif in Pagination](https://github.com/appsmithorg/appsmith/issues/24096)

https://github.com/appsmithorg/appsmith/assets/13763558/2e1d3962-24cf-40a4-88ff-718614e87c87

5. [Toast stays put on hover](https://github.com/appsmithorg/appsmith/issues/24222)

fixed by https://github.com/appsmithorg/design-system/pull/492 on design-system

https://github.com/appsmithorg/appsmith/assets/13763558/f562f151-f569-46a7-8cc2-1d2b48d332ea

6. [spacing between widget name and entity name](https://github.com/appsmithorg/appsmith/issues/24092)

before:
244291075-253e46a0-ab64-42b8-b9e3-f69a9c18eb09

after: 
244290897-0a84e254-3ec9-45e9-990d-adc00cc74082

#### Type of change
- Bug fix (non-breaking change which fixes an issue)
>
- [ ] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by albinAppsmith — APPROVED** [review]

**Review by albinAppsmith — APPROVED** [review]

**Comment by shadabbuchh** [comment]
Tested this PR:

1. Issue 1 - Still exists: https://www.loom.com/share/f680a3c9eb894bfb8710e8c3e4764ea6
2. Isue 2 - Fixed

https://github.com/appsmithorg/appsmith/assets/39921438/599d8c96-800a-4a22-bf8c-b90195983b56


3. Issue 3 - Fixed
Screenshot 2023-06-09 at 4 10 43 PM

4. Issue 4 - Fixed
Screenshot 2023-06-09 at 4 13 13 PM

5. Issue 5 - Fixed

https://github.com/appsmithorg/appsmith/assets/39921438/b2506615-60d1-473b-85c8-9233a0ac1255

6. Issue 6 - Fixed
Screenshot 2023-06-09 at 4 18 35 PM

**Comment by tanvibhakta** [comment]
> Issue 1 - Still exists: https://www.loom.com/share/f680a3c9eb894bfb8710e8c3e4764ea6

This is a different issue because it's for text area - can you please create a different issue and I'll pick it up? And we can merge this one?

**Comment by shadabbuchh** [comment]
Created a bug: https://github.com/appsmithorg/appsmith/issues/24338 for the same.
Rest looks good.

**Pull request merged**
