### PR TITLE
fix:copy paste issues in list widget v2

### LINKED ISSUE #15988: [Bug]: On changing Box radius/shadow of widgets added inside list vanishes the data on copy pasting list widget
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The data vanished on copy pasting list widget whenever Box radius/shadow is being changed on widgets added inside List widget.

Similar issue [#17815](https://github.com/appsmithorg/appsmith/issues/17815).

https://www.loom.com/share/f6f68a11cd4442aa81659c32f3056960

### Steps To Reproduce

1. Drag & Drop List widget
2. Click on image widget which is already added inside List widget
3. Change Box radius of image widget from property pane
4. Now copy the list widget and paste it
5. Observe that data populated on List widget is vanished from both List widget

### Public Sample App

_No response_

### Version

Cloud / Production

### PR DESCRIPTION
**Pull request by Tooluloope**
## Description

1. Copy-paste functionality of List widget v2. 
2. updated PrimaryKeys, MainContainerId, and MainCanvasid when pasting the widget
3. Fixed the scrolling in the list widget container when you delete the image widget

Fixes #15988

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Cypress

### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Comment by laveena-en** [comment]
@Tooluloope Some observations here:

1. The list widget went into some sort of empty state in regards to the source data. Copy pasted it twice and the two widgets have different behaviours. Trying to recreate the steps for it. But meanwhile can you have a look?
Sharing the app for reference: https://appsmith-7ivw0gc5f-get-appsmith.vercel.app/app/tests/page1-63a1493cadf7b0036b4aaef7

2. Also the theme colours haven’t been inherited over the pages.
https://ivp6ez0ljb.vmaker.com/record/yWlAdgleVEoJ5y2O

**Comment by Tooluloope** [comment]
1. I can't see any List widget on this page
Screenshot 2022-12-20 at 10 47 54
Screenshot 2022-12-20 at 10 49 24


2. Theming hasn't been integrated to ListV2, that's for another issue


Could you explain Point 1

**Comment by laveena-en** [comment]
@Tooluloope Hope this helps: https://ivp6ez0ljb.vmaker.com/record/IsgCr1Ecu4QGoKto
Also, can you re-check the app on page 3?

**Comment by laveena-en** [comment]
Tested and verified the fix on list v2 in this PR.

**Pull request merged**
