### PR TITLE
fix: Replace require with import statements

### LINKED ISSUE #7443: (JS-0359) Detected the use of require statements except in import statements
## Description
In other words, the use of forms such as `var foo = require(&quot;foo&quot;)` are banned. Instead use `ES6` style imports or `import foo = require(&quot;foo&quot;)` imports. Example - The not-preferred way :

## Occurrences
There are 5 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/appsmithorg/appsmith/issue/JS-0359/occurrences/](https://deepsource.io/gh/appsmithorg/appsmith/issue/JS-0359/occurrences/)

### PR DESCRIPTION
**Pull request by bharat-patodi**
## Description
Replaced `require` statements with `import` statements.
There were 5 instances:
- In one instance, I had to create an asynchronous conditional import. Ref: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#dynamic_import
- In another instance, I had to install the typings for the package **showdown**.
- In the instance with the `history` module, I tried multiple different ways of importing the module, including installing typings for the module separately. But it seems like there could be a typing mismatch as evidenced in this [issue](https://github.com/remix-run/history/issues/802). This is why, I have commented the instance and left it without change.
- In the last instance with the **fusionCharts** package, I faced some issues. Changing to the import statement causes TypeScript to not identify the different methods like `FusionCharts.options.license`, etc. I have tried multiple solutions including adding typings, but nothing has worked. At this point, I have two suggestions. Either we add a `.d.ts` file for `fusioncharts/core` or we leave the require as is as documented [here](https://stackoverflow.com/questions/41292559/could-not-find-a-declaration-file-for-module-module-name-path-to-module-nam/42505940#42505940).

Please guide.

Fixes #7443 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Manually

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by bharat-patodi** [comment]
Hi @mohanarpit @nidhi-nair 
Can you please review this?

**Comment by Rishabh-Rathod** [comment]
Hey @bharat-patodi,

Can you please check the typescript-related issue due to which the build is failing?

https://app.netlify.com/sites/appsmith-editor-ce/deploys/616538c3bfc91200073bd7d7

**Review by mohanarpit — APPROVED** [review]

**Comment by bharat-patodi** [comment]
@Rishabh-Rathod @mohanarpit can we do anything about this PR?

**Comment by Tooluloope** [comment]
Release build is failing cos of this https://github.com/appsmithorg/appsmith/runs/5357519688?check_suite_focus=true

**Pull request merged**
