### PR TITLE
fix: Remove empty space in embed apps when nav is set to sidebar

### LINKED ISSUE #23190: [Bug]: Embed apps leave space for side nav bar on Deployed mode
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When Navigation is set 'Side' and make the app `embed=true`, we can observe that the widgets in the app leave space for side nav bar

### Steps To Reproduce

1. Create an application
2.  Drop some widgets to left of the canvas
3. Go to App settings> Navigation
4. Select Orientation as 'Side'
5. Go to App Settings> Share & Embed
6. Copy the embed app link after making app public
7. Deploy the app
8. Paste the copied embed app link into browser
9. Observe that the widgets aren't covering entire screen and leaves space for side nav bar

### Public Sample App

_No response_

### Environment

Production

### Issue video log

https://www.loom.com/share/1cf3e968058841d78b10211726776a4b

### Version

Cloud/Production

### PR DESCRIPTION
**Pull request by dhruvikn**
## Description
When the navigation was set to sidebar and you tried to embed the app, the sidebar wouldn't show up but the canvas had some empty left margin. This PR fixes that.

#### PR fixes following issue(s)
Fixes #23190 

#### Type of change
- Bug fix (non-breaking change which fixes an issue)

#### How Has This Been Tested?
- [x] Manual
- [ ] Jest
- [ ] Cypress

#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [x] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Comment by dhruvikn** [comment]
Blocked until https://github.com/appsmithorg/appsmith/pull/23725 is merged.

**Comment by dhruvikn** [comment]
ADS review is not required. Removing @albinAppsmith and @tanvibhakta as reviewers.

**Review by rahulbarwal — APPROVED** [review]
Code changes look 👍 . 
But I am not able to login  to DP url.

**Comment by rahulbarwal** [comment]
Tested on DP url, working fine.

**Comment by laveena-en** [comment]
Verified, changes LGTM!

**Pull request merged**
