### PR TITLE
fix: Misplaced theming indicator & arrow in property pane

### LINKED ISSUE #22276: [Bug]: The indicator and arrow for "Value deviated from theme" looks misplaced in Release
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In any of the widgets having the style section, when I change the background color or any other property that is set by the theme, the positioning of the dot and arrow indicator is off and quite low as compared to production

### Steps To Reproduce

1. DnD any widget onto the canvas (e.g. menu button widget) on release.app.appsmith.com
2. Click on Style tab
3. Change the Button color for e.g. 
4. Note the arrow and dot indicator seem to have moved down as compared to Prod/

Releasedeviation
Productiondeviation

### Public Sample App

_No response_

### Environment

Release

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by aswathkk**
## Description

Fixes the misplaced theming indicator & reset value button in the property pane

Fixes #22276

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual
Followed the instructions provided in the issue and confirmed that it is fixed.

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Comment by arunvjn** [comment]
@aswathkk Can we remove the margin-bottom on the JS toggle button? It does align with with label. Rest looks good!

**Comment by aswathkk** [comment]
@arunvjn JS toggle button (t--js-toggle) is a design system component.
We can style it by overriding the DS styles in PropertyControl.tsx if needed. But I don't think it is not a good idea at the moment. Because, @yaldram is working on de-duplicating design system component usages in property pane and as a part of that, we are going to avoid style overrides in the main repo.
@yaldram correct me if I'm wrong here.

Can we keep this as it is for now? We will make sure things are properly aligned in https://github.com/appsmithorg/appsmith/pull/21988

**Review by arunvjn — DISMISSED** [review]

**Pull request merged**
