### PR TITLE
chore: Turn off Allow filtering property on Table widget

### LINKED ISSUE #34591: "Allow filtering" property should be off by default
People don’t understand they need to create a filter. [All details](https://www.notion.so/appsmith/People-don-t-understand-they-need-to-create-a-filter-a98c7240c5e543f9a15a630bee6c7859?pvs=4)

also, client-side filtering has several problems we need to rethink.

### PR DESCRIPTION
**Pull request by carinanfonseca**
https://github.com/appsmithorg/appsmith/issues/34591

## Description
Making _Allow filtering_ option false by default.

Allow filtering off

Fixes #34591
_or_  
Fixes `Issue URL`
> [!WARNING]  
> _If no issue exists, please create an issue first, and check with the maintainers if the issue is valid._

## Automation

/ok-to-test tags="@tag.Table, @tag.Widget, @tag.Binding, @tag.Sanity"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9795462304>
> Commit: e0c1e8376b702f13b9640c880cf5606af070a420
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9795462304&attempt=1" target="_blank">Cypress dashboard</a>.
> Tags: `@tag.Table, @tag.Widget, @tag.Binding, @tag.Sanity`

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [x] No

## Summary by CodeRabbit

- **Bug Fixes**
  - Filtering is now disabled by default for the `TableWidgetV2`.

- **Tests**
  - Updated test scripts to enable filtering for `TableWidgetV2` in multiple scenarios.

### CODE REVIEW

**Review by rahulbarwal — APPROVED** [review]
Looks good.

**Comment by nerbos** [comment]
@rahulbarwal, don't we have a test to check defaults? If yes, won't this break that test?

**Comment by rahulbarwal** [comment]
> @rahulbarwal, don't we have a test to check defaults? If yes, won't this break that test?

Yes @nerbos, In the initial tests run none of them failed which was surprising. In the second run we have 8 failing. @jacquesikot will take over this PR to ensure everything passes.

**Comment by nerbos** [comment]
> > @rahulbarwal, don't we have a test to check defaults? If yes, won't this break that test?
> 
> Yes @nerbos, In the initial tests run none of them failed which was surprising. In the second run we have 8 failing. @jacquesikot will take over this PR to ensure everything passes.

@rahulbarwal the tests that failed where jest or cypress tests?

**Comment by rahulbarwal** [comment]
> @rahulbarwal the tests that failed where jest or cypress tests?

Cypress tests are failing. You can check the description of this PR.

**Comment by nerbos** [comment]
@rahulbarwal is it worth having a jest to test defaults? Or this is not a practice in Engineer?

**Review by rahulbarwal — APPROVED** [review]

**Pull request merged**
