### PR TITLE
chore: Rewrite widget deprecation message

### LINKED ISSUE #20951: [Task]: Rewrite widget deprecation message
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Current widget deprecation message is to be rewritten to be a bit more positive.

### PR DESCRIPTION
**Pull request by vsvamsi1**
## Description

Updating widget deprecation message.

Fixes #20951 
## Type of change
- Chore (housekeeping or task changes that don't impact user perception)

## How Has This Been Tested?

- Manual

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Comment by dilippitchika** [comment]
@rahulramesha we changed the widget deprecation message, can you review and approve this? We are going to use this message going forward - “Drag the latest <name of widget> to unlock new features and prevent end-of-life headaches for this widget.”

**Comment by theparthacus** [comment]
> @rahulramesha we changed the widget deprecation message, can you review and approve this? We are going to use this message going forward - “Drag the latest <name of widget> to unlock new features and prevent end-of-life headaches for this widget.”

please make sure to replace `<name of widget>` with the name of the widget. So, for the List, it will read, "Darg the latest List to unlock..." and so on.

**Comment by dilippitchika** [comment]
Yes it's done, @theparthacus. Already checked it

**Comment by rahulramesha** [comment]
@vsvamsi1 before we had an option to not provide replacement widget in the config. Now that we absolutely require that to be present, can you please modify this test case such that it fails if `isDeprecated` is true but `replacement` is undefined or not a valid widget type.
https://github.com/appsmithorg/appsmith/blob/fde3d1e185c1baf78b55f13915efb839856d81f7/app/client/src/utils/testPropertyPaneConfig.test.ts#L166

**Review by rahulramesha — DISMISSED** [review]

**Comment by vsvamsi1** [comment]
/build-deploy-preview sha=25cf64a08659104cf52abc063f51154917b46c5a

**Comment by vsvamsi1** [comment]
/build-deploy-preview sha=92031534006b85043bda8064a21136abd0a4eb64

**Review by rahulramesha — DISMISSED** [review]

**Pull request merged**
