### PR TITLE
Comments feature updates

### LINKED ISSUE #4318: [Bug] Comments should be disabled for public applications
## Description

Comments should be disabled for public applications because it doesn't make a lot of sense for users to be able to see/add comments on public apps.

### Steps to reproduce the behaviour:
Add steps to reproduce this behaviour, include console / network logs & screenshots
1. Open any public app
2. Click on the the comments icon
3. Try to add a comment on a any widget on the page.
4. See error pop up saying "Unable to find organization ID xyz". This is because I don't have access to that organization & application.

### Important Details
 - Version: Cloud / Self-Hosted
 - OS: All
 - Browser: All

### PR DESCRIPTION
**Pull request by rishabhsaxena**
- App comments section
- Update thread and mentions list UI
- Refactor is thread visible to a global var instead of a thread level variable in store
- Perf update: update individual thread items instead of the app comments list
- Disable comments for public apps: (fixes #4318)
- Other minor fixes:
  - Update emoji picker component 
  - Show thread options on hover
  - Fix z-index for tooltips with app comments section
  - Link apis for mark-as-read, pin, delete

### CODE REVIEW

**Review by jsartisan — DISMISSED** [review]

**Review by mohanarpit — APPROVED** [review]

**Comment by mohanarpit** [comment]
Approving for the tests to run.

**Comment by rishabhsaxena** [comment]
Creating another branch clone

**Pull request closed without merging**
