### PR TITLE
fix: text font size for text widget inside modal & statbox.

### LINKED ISSUE #16758: [Bug]: Modal and Stat box widget - Text widget - default value is Large but displays Medium
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we check the default value of the Text widget inside the Modal and Stat box widgets is displayed as medium but when we click on the same value we are able to see the Text size changes

### Steps To Reproduce

1. D&D Stat box/Modal widget
2. Click on the Text inside the widget
3. Go to Font size of the Text widget in property pane
4. Click on the default selected value in the font size dropdown
5. Observe the Font size of the text changes

https://user-images.githubusercontent.com/104895602/190153667-dda30697-428a-4443-9297-d4be0ba40939.mp4

### Public Sample App

_No response_

### Version

Release

### PR DESCRIPTION
**Pull request by yaldram**
## Description

- The font size given to the text widgets inside the modal & stat box widgets was different than what we have in the property pane font size dropdown. 
- This Pull request uses appropriate font size values.

Fixes #16758

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual

### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by jsartisan — APPROVED** [review]

**Comment by kamakshibhat-appsmith** [comment]
Tested on DP, working fine

**Pull request merged**
