### PR TITLE
chore: Upgraded Snake YAML version to 2.0

### PR DESCRIPTION
**Pull request by nidhi-nair**
## Description
Upgrades SnakeYaml dependency version forcefully to 2.0 to overcome [this issue](https://github.com/spring-projects/spring-boot/issues/33457), as advised [here](https://github.com/spring-projects/spring-boot/issues/34405#issuecomment-1450280581).

This version tag can be reverted when we upgrade to Spring 6.1, which is when the library [aims](https://github.com/spring-projects/spring-framework/pull/30048#issuecomment-1555194087) to upgrade the version themselves.

Fixes https://github.com/appsmithorg/appsmith-ee/issues/1233

#### Type of change
- Chore (housekeeping or task changes that don't impact user perception)

## Testing
This PR will be tested during regression.

### CODE REVIEW

**Review by sharat87 — DISMISSED** [review]

**Comment by sharat87** [comment]
@mohanarpit @nidhi-nair, still failing from ff4j:

```
Caused by: java.lang.NoSuchMethodError: org.yaml.snakeyaml.constructor.SafeConstructor: method 'void <init>()' not found
	at org.ff4j.parser.yaml.YamlParser.<init>(YamlParser.java:55) ~[ff4j-config-yaml-2.0.0.jar:2.0.0]
	at com.appsmith.server.configurations.FeatureFlagConfig.ff4j(FeatureFlagConfig.java:13) ~[classes/:na]
	at com.appsmith.server.configurations.FeatureFlagConfig$$SpringCGLIB$$0.CGLIB$ff4j$0(<generated>) ~[classes/:na]
	at com.appsmith.server.configurations.FeatureFlagConfig$$SpringCGLIB$$2.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:258) ~[spring-core-6.0.8.jar:6.0.8]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-6.0.8.jar:6.0.8]
	at com.appsmith.server.configurations.FeatureFlagConfig$$SpringCGLIB$$0.ff4j(<generated>) ~[classes/:na]
	at jdk.internal.reflect.GeneratedMethodAccessor290.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:139) ~[spring-beans-6.0.8.jar:6.0.8]
	... 169 common frames omitted
```

**Comment by nidhi-nair** [comment]
Looks like this is because we're using a yaml parser to figure out ff4j flags. I can convert this to use an XML parser, it's been a while since the related [PR](https://github.com/ff4j/ff4j/pull/695) on the ff4j repo has seen any activity. Do you folks think we should go ahead with conversion to XML?

**Comment by sharat87** [comment]
@nidhi-nair, thanks. I like this. Irrespective of the priority of this dependency upgrade, and irrespective of when FF4J team decide to release support for the upgrade, I'd vote for moving to XML. As much as I prefer YAML syntax to XML, I have to admit that XML parsers are a lot more rock-solid and battle tested, than anything else. Can we make this permanent, instead of temporary? Then perhaps we can just exclude the SnakeYAML dependency completely?

**Review by sharat87 — APPROVED** [review]

**Pull request merged**
