### PR TITLE
reverting a change

### PR DESCRIPTION
**Pull request by ankitakinger**
Fixes #`Issue Number`  
_or_  
Fixes `Issue URL`
> [!WARNING]  
> _If no issue exists, please create an issue first, and check with the maintainers if the issue is valid._

## Automation

/ok-to-test tags=""

### :mag: Cypress test results

> [!CAUTION]  
> If you modify the content in this section, you are likely to disrupt the CI result for your PR.

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [ ] No

## Summary by CodeRabbit

- **New Features**
	- Updated test specifications to include new server-side and client-side visual tests.
	- Introduced a new layout structure in the `CommonEditorForm` component, consolidating functionality into a single `RequestTabs` component.
	- Enhanced vertical scrolling capability in the `UQIEditorForm` component.

- **Bug Fixes**
	- Adjusted tooltip positioning for improved visual alignment.

- **Chores**
	- Removed outdated styled components related to the previous tabbed interface.

### CODE REVIEW

**Comment by sagar-qa007** [comment]
/ci-test-limit-count run_count=5 update_snapshot=false specs_to_run=cypress/e2e/Regression/ServerSide/ApiTests/API_Edit_spec.js,cypress/e2e/Regression/ClientSide/VisualTests/JSEditorIndent_spec.js

**Review by alex-golovanov — CHANGES_REQUESTED** [review]
Please do not merge this, as it will revert a bug fix in favor of fixing a test. I will have a PR fixing the test, shortly.

**Pull request closed without merging**
