### PR TITLE
Remove unused redux actions 

### PR DESCRIPTION
**Pull request by Rishabh-Rathod**
## Description
- There is no listener attached to the UPDATE_CANVAS_STRUCTURE redux action which means it does not have any change and hence can be removed.

## Type of change

- Refactor.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>

    // Code coverage diff between base branch:release and head branch: refactor/remove_unused_redux_action 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | app/client/src/sagas/PageSagas.tsx | 23.64 **(-0.1)** | 6.35 **(0)** | 16.13 **(0)** | 25.53 **(-0.1)**</details>

### CODE REVIEW

**Comment by hetunandu** [comment]
There are many more like these. Can you remove all of them?

**Comment by Rishabh-Rathod** [comment]
> There are many more like these. Can you remove all of them?

Sure I will check and remove them all.

**Comment by hetunandu** [comment]
Are you still working on this @Rishabh-Rathod ? Can we close and reopen this when you are ready?

**Comment by Rishabh-Rathod** [comment]
> Are you still working on this @Rishabh-Rathod ? Can we close and reopen this when you are ready?

We can close it, for now, I will re-open it whenever I get time.

**Pull request closed without merging**
