### PR TITLE
feat: dynamic switch widget standardisation

### LINKED ISSUE #13602: [Task]: Standardise Structure of Switch widget to enable Dynamic Height.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

_No response_

### PR DESCRIPTION
**Pull request by ankurrsinghal**
## Description

1. Passed the `contentRef` to `SwitchComponent` from `SwitchWidget`.
2. Wrapped the `SwitchComponent` functional, component in the React.forwardRef.
3. Set the final `ref` from React.forwardRef to `SwitchComponentContainer` which is a styled `div`.

Fixes #13602

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Manually

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by riodeuno — APPROVED** [review]

**Review by rahulramesha — APPROVED** [review]

**Comment by btsgh** [comment]
Tested the properties of Switch widget. Works fine in comparison with Prod.

**Pull request merged**
