### PR TITLE
Feature/4135 table url column pretty link

### LINKED ISSUE #4135: [Feature] Table URL columns pretty link
## Summary
Allow users to configure a human readable text in the table widget's url type column configurations.

## Motivation
Today, the URL column works as is. Which means, that the url value is shown as is and is available as an anchor link.
Many common use-cases would require an alternative text to be shown which would still be an anchor link.

## Additional Context
It should have a new field which will be a computed text to be shown. If this is not configured, fallback to showing the url.

### PR DESCRIPTION
**Pull request by wmdev0808**
## Description
- Add displayText field into property pane
- Display urls based on the displayText
- Fix url alignment issue

Fixes #4135 

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: feature/4135-table-url-column-pretty-link 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 51.66 **(0)** | 32.83 **(-0.05)** | 29.57 **(0)** | 52.14 **(0)**
 :red_circle: | app/client/src/components/designSystems/appsmith/TableComponent/AutoToolTipComponent.tsx | 27.27 **(0)** | 14.29 **(-1.09)** | 0 **(0)** | 31.03 **(0)**
 :red_circle: | app/client/src/components/designSystems/appsmith/TableComponent/TableStyledWrappers.tsx | 35.37 **(-0.43)** | 15.75 **(-1.2)** | 0 **(0)** | 35.37 **(-0.43)**
 :red_circle: | app/client/src/components/designSystems/appsmith/TableComponent/TableUtilities.tsx | 28.16 **(0)** | 9.84 **(-0.87)** | 0 **(0)** | 26.04 **(0)**
 :green_circle: | app/client/src/widgets/TableWidget/TablePropertyPaneConfig.ts | 38.67 **(2.56)** | 13.73 **(0)** | 53.85 **(3.85)** | 40.85 **(2.61)**</details>

### CODE REVIEW

**Review by somangshu — CHANGES_REQUESTED** [review]
@wmdev0808 review from testing deploy preview:
 - When I click the link, the browser opens 2 tabs every time
 - When the URL is not present the display text can be greyed out.
 - When the URL is not present clicking on the display text should not redirect to view mode
 - Question: Should the display text not be converted to Uppercase

**Review by somangshu — CHANGES_REQUESTED** [review]
@wmdev0808 

 - The internal property `currentRow` is still now available inside the display text field
 - We should highlight the colour of the display text like before. Since that was a bug in my system and the table column gets empty if there is no value in the computed value.

**Comment by somangshu** [comment]
Deploy preview tested for changes. 

@SatishGandham review and approve.

**Review by SatishGandham — APPROVED** [review]

**Review by somangshu — APPROVED** [review]

**Review by jsartisan — APPROVED** [review]

**Comment by somangshu** [comment]
@wmdev0808 please merge latest release here, Test are failing because of that!

**Review by somangshu — APPROVED** [review]

**Pull request merged**
