### PR TITLE
FIX #3899 : added supported custom chart types list, validate chart t…

### LINKED ISSUE #3899: [Bug] Error: TypeError: d is not a constructor
Sentry Issue: [APPSMITH-NX](https://sentry.io/organizations/appsmith/issues/2321259866/?referrer=github_integration)

```
Error: TypeError: d is not a constructor
    at y (https://app.appsmith.com/static/js/12.d38247e2.chunk.js?__WB_REVISION__=3d10b7a1111926916541f6ac7f8fa284:2:181346)
    at e._render (https://app.appsmith.com/static/js/12.d38247e2.chunk.js?__WB_REVISION__=3...
  at y (../node_modules/fusioncharts/fusioncharts.js:13:182073)
  at _render (../node_modules/fusioncharts/fusioncharts.js:13:86049)
  at c (../node_modules/fusioncharts/fusioncharts.js:13:85470)
  at _renderChart (../node_modules/fusioncharts/fusioncharts.js:13:85634)
  at _setState (../node_modules/fusioncharts/fusioncharts.js:13:77545)
...
(2 additional frame(s) were not displayed)
```

Steps to reproduce:
- drop a chart widget on the canvas
- change the type to custom chart
- add chart data to this: `{{ { type: "LINE_CHART", datasource: {
}} }}`

### PR DESCRIPTION
**Pull request by vibhandikyash**
## Description
On adding a Custom Type of chart. Fusion Charts was throwing an error. Handled that by adding validation with fusion chart types.
 
Fixes #3899 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Tested Locally.
> Updated existing Test case.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: FIX/3899-typeerror-in-custom-chart 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 51.61 **(0.01)** | 32.66 **(0.01)** | 29.77 **(0)** | 52.13 **(0.01)**
 :sparkles: :new: | **app/client/src/constants/CustomChartConstants.ts** | **100** | **100** | **100** | **100**
 :green_circle: | app/client/src/workers/validations.ts | 37.94 **(0.68)** | 32.53 **(0.47)** | 42.22 **(0)** | 38.64 **(0.73)**</details>

### CODE REVIEW

**Comment by vivekverma2312** [comment]
@vibhandikyash Still getting error in custom chart if we use `{{ { type: "LINE_CHART", datasource: { }} }}`
I have tried the steps to repro on issue #3899 

Screenshot 2021-06-03 at 2 34 30 PM

**Comment by somangshu** [comment]
@vivekverma2312 this is not the bug that you have pointed out. @vibhandikyash can you provide some steps to reproduce?

**Review by riodeuno — APPROVED** [review]
Code, looks good to me. @vivekverma2312 Please verify the PR.

**Comment by vibhandikyash** [comment]
> @vivekverma2312 this is not the bug that you have pointed out. @vibhandikyash can you provide some steps to reproduce?

@vivekverma2312 What you are referring to seems unrelated to this ticket. I see that since it's an invalid datasource it's showing you this error which has resolved under issue #4573. We have added some default configuration for charts. Under this ticket, we are just checking if the name of the chart is correct (supported by Fusioncharts) or not.

P.S. To reproduce this issue you can try these steps:
image


cc: @somangshu

**Comment by vivekverma2312** [comment]
@vibhandikyash This has been tested and working fine now. Can be merged into release.

**Pull request merged**
