### PR TITLE
feat: Migrate DraggableListCard and DraggableListComponent from ads

### LINKED ISSUE #17201: [Task]: Migrate DraggableListCard and DraggableListComponent from ads folder to propertControl
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

_No response_

### PR DESCRIPTION
**Pull request by albinAppsmith**
## Description

Migrated DraggableListCard & DraggableListComponent from `ads` folder to `components/propertyControl`. Currently these components can't be migrated to design system package because the usage of propertyControl components inside these. This can be picked up later while refactoring if necessary.

Fixes #17201

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Tested in local

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by tanvibhakta — APPROVED** [review]

**Comment by shadabbuchh** [comment]
This PR has been tested. No issues found.

**Pull request merged**
