### PR TITLE
fix: Fix fetch datasource structure on datasource creation

### LINKED ISSUE #21889: [Bug]: client is not making get structure call after creating a new datasource
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

- Get structure call is required to show the DB schema on the left hand pane. However, at this point the client is not making get structure call when a datasource is created for the first time, due to which the left hand pane says `schema not available`.  However, the client makes get structure call when updating a datasource. 

### Steps To Reproduce
- create a valid postgres datasource. save the datasource
- create a new query on the datasource, don't run the query. The datasource should now be visible on the left hand pane. 
- check that the schema is not shown on the left hand pane but a msg saying `schema not available`
- click on the 3 dots on the database name on the left hand pane and click on `refresh` button and now the schema should become visible

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

cloud, latest

### PR DESCRIPTION
**Pull request by Irongade**
When a datasource is created the datasource structure is not fetched. This PR introduces this functionality when datasources are created.

Fixes #21889

- Bug fix (non-breaking change which fixes an issue)

- Manual

### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by sneha122 — APPROVED** [review]

**Comment by prapullac** [comment]
Hey @Irongade 
When the  datasource is closed and reopened on the entity pane the scheme appears is this expected. 
Adding the video for clarity 
https://www.loom.com/share/0a327fee7a594ab3b4bb52b7cbbbd2a2

**Comment by Irongade** [comment]
> https://www.loom.com/share/0a327fee7a594ab3b4bb52b7cbbbd2a2

Hi Prapulla, As seen in the video, the datasource was not created after you deleted it, I'm not sure why that is the case. Hence why the API was not called. The PR introduces calling the API when the datasource is created.

**Pull request merged**
