### PR TITLE
fix: fixed validation error for logo upload

### LINKED ISSUE #23168: [Bug]: Error message on uploading Logo shows 100MB instead of 1MB
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Since uploading logo limit size is 1MB, but on it throws error message saying `Payload too large: File size cannot exceed 100MB` instead of 1MB as uploading file more than 1mb is not allowed

Screenshot (278)

### Steps To Reproduce

1. create a application with multiple page
2. Go to App Settings> navigation> Upload Logo
3. Try to upload valid image larger than 1MB
4. Observe the error says 100MB instead of 1MB

### Public Sample App

_No response_

### Environment

Deploy Preview

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by harshitpandey0426**
#### PR fixes following issue(s)
Fixes #23168

- Bug fix (non-breaking change which fixes an issue)

>
- [x] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by dhruvikn — APPROVED** [review]

**Comment by chandannkumar** [comment]
Tested this PR and LGTM

**Comment by harshitpandey0426** [comment]
@dhruvikn I dont have the access, ig you will have to run the test

**Comment by dhruvikn** [comment]
Thanks a lot @harshitpandey0426 for contributing. Much appreciated! 🎉

**Pull request merged**
