### PR TITLE
chore: Return custom slug in other api

### LINKED ISSUE #14753: [Task] Add custom slugs info in page list and applications list API
- [ ] /new API needs to return the slug and customSlug of all the pages of the application
- [ ] /pages?pageId=?&applicationId=? API to return slug and customSlug info.

### PR DESCRIPTION
**Pull request by nayan-rafiq**
## Description

Adds custom slugs to the response of few APIs

Fixes #14753

## Type of change
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
- Manually

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by nayan-rafiq** [comment]
@AnaghHegde I've updated the PR. Would you please review this?

**Comment by AnaghHegde** [comment]
@nayan-rafiq Just a question on the implementation, with the custom slugs can the user have a different page/app name while keeping a different slug?

**Review by AnaghHegde — APPROVED** [review]

**Pull request merged**
