### PR TITLE
feat: 1st step to implement start with data onboarding option

### LINKED ISSUE #28552: [Feature]: Introduce list of datasources - 1st step for the flow
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

https://www.notion.so/appsmith/Task-breakdown-Start-with-data-787dd729e71e452abe14b46acae6e931?p=9711fda45ff94ed29470c01787d95874&pm=s

### Why should this be worked on?

activation - onboarding revamp

### LINKED ISSUE #28807: [Task]: On create datasource page, on plugin selection, avoid the redirection
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

https://www.notion.so/appsmith/Issue-breakdown-Start-with-data-787dd729e71e452abe14b46acae6e931?p=25c40eedc51b4b93a6378138ba250641&pm=s

### PR DESCRIPTION
**Pull request by AmanAgarwal041**
## Description
Added a new step to display the datasources when a user clicks on the `Start with data` option in the onboarding flow for creating new apps.

#### PR fixes following issue(s)
Fixes #28552
Fixes #28807
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
- [ ] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by sneha122 — APPROVED** [review]

**Comment by sneha122** [comment]
@AmanAgarwal041 I have tested this PR, observed a couple of things:
- UI has unnecessary white space at the bottom
Screenshot 2023-11-17 at 1 17 50 PM
- I think this start with data flow is shown only when we have both the flags of start with templates and start with data enabled, that is expected right? I signed up initially using integrations@appsmith.com, but did not see this flow at all, start with data flag was on but start with templates was not, thats why I did not know see the flow right?
- In the header, we have back, skip and a header, in the DP I am only seeing back button, other things we will be covering as part of different task is it?

https://github.com/appsmithorg/appsmith/assets/30018882/dc7d9746-9452-43c5-831c-2109e9a211bd

**Comment by AmanAgarwal041** [comment]
> @AmanAgarwal041 I have tested this PR, observed a couple of things:
> 
> * UI has unnecessary white space at the bottom
>   Screenshot 2023-11-17 at 1 17 50 PM
> * I think this start with data flow is shown only when we have both the flags of start with templates and start with data enabled, that is expected right? I signed up initially using [integrations@appsmith.com](mailto:integrations@appsmith.com), but did not see this flow at all, start with data flag was on but start with templates was not, thats why I did not know see the flow right?
> * In the header, we have back, skip and a header, in the DP I am only seeing back button, other things we will be covering as part of different task is it?
> 
>  Screen.Recording.2023-11-17.at.1.20.19.PM.mov

1. Will fix the ui
2. Yes, that correct. Both the flags should be true.
3. Yes, header and skip will be handled in another task

**Review by sneha122 — APPROVED** [review]

**Comment by AmanAgarwal041** [comment]
@sneha122 Fixed the UI issue and removed the secure banner from the onboarding flow.
Screenshot 2023-11-20 at 1 19 33 PM

**Review by sneha122 — APPROVED** [review]

**Comment by sneha122** [comment]
@AmanAgarwal041 UI issue is tested and looks good!

**Comment by AmanAgarwal041** [comment]
Mock datasources is not present on the 1st step page. Will be handling this in https://github.com/appsmithorg/appsmith/issues/28965 cc -@sneha122 
Adding `Test plan approved` label

**Pull request merged**
