### PR TITLE
fix: provide access to currentRow in table widget menubutton items

### LINKED ISSUE #12359: [Bug]-[8]:Unable to use `currentRow` inside Menu Color property of menu button in the table column
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Screenshot 2022-03-30 at 11 00 02 AM

### Steps To Reproduce

1. Create a table with the menu button column
2. Try to change the `Menu Color` property using `currentRow` 

### Public Sample App

_No response_

### Version

Cloud

### LINKED ISSUE #13808: [Bug]-[932]:Unable to access `currentRow` in Menu items of Menu Buttons in Table columns
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Steps To Reproduce

1. Create a table and set one of the columns to be Menu Button
2. Create or edit one of the menu items in the button
3. Try to access `currentRow` in any of the properties

### Public Sample App

_No response_

### Version

Cloud 1.6.23

### PR DESCRIPTION
**Pull request by sbalaji1192**
## Description
Menu items now have access to currentRow in backgroundColor, textColor, Disabled and Visible properties.

Fixes #13808
Fixes #12359

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

4 new cases have been written to check the bindings in said properties.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by jsartisan — DISMISSED** [review]

**Comment by chandannkumar** [comment]
Tested this PR and working as expected. This PR fixes
Fixes #13808
Fixes #12359

Tested this PR for
- Menu items now have access to currentRow in backgroundColor, textColor, Disabled and Visible properties
- Menu Variant property now have access to currentRow

**Review by jsartisan — APPROVED** [review]

**Pull request merged**
