### PR TITLE
Remove hardcoding of RTS server 

### LINKED ISSUE #32532: [Task]: Remove hardcoded RTS server url
### SubTasks

- [] Remove the hardcoded RTS server url at https://github.com/appsmithorg/appsmith/blob/021b4177eac01a445cacf8bfb4688de449366701/app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/CommonConfig.java#L137
and replace it with support for `APPSMITH_RTS_HOST` env var to better support containerization. The RTS server can currently only be run on the same VM as the backend, and cannot be run as an independent pod in kubernetes

### PR DESCRIPTION
**Pull request by SorsOps**
## Description
Removes the hardcoded RTS server url. Please double check to see that the value with the ':' in the annotations you are using will work, as  I don't write java frequently.

Fixes #32532 

## Automation

/ok-to-test tags=""

### :mag: Cypress test results

> [!CAUTION]  
> If you modify the content in this section, you are likely to disrupt the CI result for your PR.

## Summary by CodeRabbit

- **New Features**
	- Enhanced server configuration to support a new Real-Time Service (RTS) base URL setup.

### CODE REVIEW

**Comment by SorsOps** [comment]
This feels like this should be a relatively easy merge

**Comment by SorsOps** [comment]
Please review, this is a simple PR

**Comment by SorsOps** [comment]
@NilanshBansal

**Comment by SorsOps** [comment]
@nilanshbansal Please provide a review of this very simple PR

**Comment by NilanshBansal** [comment]
@sharat87 @brayn003 can you please check this out.

**Pull request closed without merging**
