### PR TITLE
fix: Fix JS object duplicate name issue

### LINKED ISSUE #14755: [Bug]: 400 error is returned on a newly defined JS function name
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

A newly defined function displays a message stating object and function name combination already exists when it does not.

### Steps To Reproduce

1. Go to app at [this](https://release.app.appsmith.com/app/scratch-pad/automation-test-cases-62987963c43c3d0bd6572185/edit/jsObjects/62b3f8abdd56222d3f8039b0?editName=false) location and observe the toast message and the browser logs display error for a newly defined function

image

### Public Sample App

_No response_

### Version

Cloud

## Test Plan
- [ ] [[Test Case]: verify that there is no 400 error appear on defining a new JS function name](https://github.com/appsmithorg/TestSmith/issues/1925)

Front logo [Front conversations](https://app.frontapp.com/open/top_5rtvw)

### PR DESCRIPTION
**Pull request by subrata71**
## Description
It's expected that the actions inside a JS collection should always have a `collectionId` if it's not deleted. (Even if it's deleted the`collectionId` should persist though). 

----------------
There were some documents found in the `newAction` collection which don't have any `collectionId` and `deletedAt` attributes. But those documents were having the same `pageId`. Thus when the front-end sends some new actions be created by the server, it finds the name conflicting with the existing ones. 

This could happen since several updates/inserts in the DB are taken place without sharing one single transaction. We haven't introduced transactional behavior in our application. 

During the creation of an action under JS collection, the action is created first in the DB without having a `collectionId`. After the creation of the action, the `collectionId` gets updated with a separate update query. The latter update might fail which puts the action document in such an expected state. 

This PR will ignore those JS actions that don't have any `collectionId` during the name-checking of new action creation.

[RCA](https://www.notion.so/appsmith/RCA-JSObject-name-already-exists-Please-use-a-different-name-e09c407f0ddb4653bd3974f3703408e6)

Fixes #14755 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual
- JUnit

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by riteshkew — APPROVED** [review]
The changes are patch fixes for faster resolution and once transactions are properly implemented on the backend, this needs to be taken up again. Further details are very well put in the RCA doc.

**Comment by ramsaptami** [comment]
Verified fix for JS object duplicate name issue
CC: @subrata71

**Pull request merged**
