### PR TITLE
fix: Added lazy loading icon in icon component

### PR DESCRIPTION
**Pull request by albinAppsmith**
## Description

Added back lazy loading for icons inside icon component.

#### PR fixes following issue(s)
Fixes # (issue number)
https://github.com/appsmithorg/appsmith/issues/23876

#### Type of change
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

- [ ] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by tanvibhakta — DISMISSED** [review]

**Comment by shadabbuchh** [comment]
Tested this PR. There seems to be a delay in loading the icons across menu, drop-down components & other places in general. Please have a look at the below video:
https://www.loom.com/share/9095e656ec5143a999678d3cd566abff
P.S: It might be helpful if the video is viewed with decreased speed to catch the late loading of icons.

**Comment by shadabbuchh** [comment]
Moving this PR to On Hold. Refer: https://theappsmith.slack.com/archives/C01SGCF8PM0/p1686224317553439

**Review by KelvinOm — APPROVED** [review]

**Comment by shadabbuchh** [comment]
Tested this PR. Looks good now.

**Comment by albinAppsmith** [comment]
Closing this since it was merged along with https://github.com/appsmithorg/appsmith/pull/24503

**Pull request closed without merging**
