### PR TITLE
fix: checkbox widget label right alignment issue.

### LINKED ISSUE #16126: [Bug]-[1568]:Checkbox widget - Label -> Position - On selecting Right, it still remains where it is.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I select the Right option from the Label -> Position property of Checkbox widget, it remains on the left. 
No difference is seen if we select Left or Right. 

Expected behavior - Previously, on selecting Right, the Label text used to be aligned to the right of the widget.

### Steps To Reproduce

1. Drag and drop a checkbox group widget and increase the width of the box.
2. Select the Right option from the Label -> Position property
3. Note that there is no change in the position of the Label text.
Checkbox_labelposition_right

Earlier behavior -
Screenshot 2022-07-14 at 10 59 25 AM

### Public Sample App

_No response_

### Version

Release

### PR DESCRIPTION
**Pull request by yaldram**
## Description

Label Position right option was not aligning the label to the right for the Checkbox widget.

Fixes #16126

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Tested Manually on the canvas

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by jsartisan — DISMISSED** [review]

**Comment by dilippitchika** [comment]
@yaldram @Sripriya93 this is not what i expected the fix to be. Can you check this loom - https://www.loom.com/share/2d508428f3e94ae6a329a55ca0738691

**Comment by yaldram** [comment]
Thanks @dilippitchika for the explanation. I have made the necessary changes and pushed the code please check the latest Deploy Preview. Thanks

**Review by jsartisan — APPROVED** [review]

**Comment by Sripriya93** [comment]
Position - changes the position of the label along with the checkbox
Alignment - Changes the alignment of the label alone
Working fine, moving to done

https://images.zenhubusercontent.com/275993885/7e6d3aba-c477-4dae-b9b8-934b8c766760/untitled_application_1___editor___appsmith___14_october_2022.mp4

**Review by jsartisan — APPROVED** [review]

**Pull request merged**
