### PR TITLE
fix: scrolling issue in container and modals for app view

### LINKED ISSUE #11415: [Bug]: Modal Widget scroll not working
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The scroll is not working in the modal widget

### Steps To Reproduce

Fork following app - 
https://app.appsmith.com/applications/62174f288a51871ac43aa737/pages/62174f288a51871ac43aa73a

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by Tooluloope**
## Description

- Fix view mode for vertical scroll in widget that uses the canvas widget, Modals, COntainer, Form
- Revert fix in #10796 which was the cause of the issue

Fixes #11415

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/Canvas-not-scrolling-vertically-app-view 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 55.74 **(0)** | 37.07 **(0.01)** | 35.8 **(0)** | 56.11 **(0.01)**
 :green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.94 **(0.23)** | 41.67 **(0.84)** | 36.21 **(0)** | 56.99 **(0.25)**
 :green_circle: | app/client/src/widgets/CanvasWidget.tsx | 95.92 **(0.47)** | 66.67 **(0)** | 100 **(0)** | 97.83 **(0.27)**</details>

### CODE REVIEW

**Comment by Tooluloope** [comment]
Revert fix in #10796 which was the cause of the issue

**Review by rahulramesha — APPROVED** [review]
LGTM

**Comment by vivekverma2312** [comment]
@Tooluloope Tested and scroll is working fine now.

**Pull request merged**
