### PR TITLE
fix: gs import export issue

### LINKED ISSUE #22501: [Bug] GSheets Fork/Import Bugs
The following ticket is to investigate the issues related to Google Sheets data source while forking and importing applications.

Note: Will update the estimates once I have had the chance to look at all the failing cases.

Please find the list of bugs below :
https://docs.google.com/spreadsheets/d/1XqFfLWt-_ydmurgpw1AE8ggb3fp-q6BwFsv-BhKqX7A/edit#gid=0

### PR DESCRIPTION
**Pull request by sneha122**
## Description

This PR fixes:
- when importing application which contains google sheets datasource with selected sheets scope, the file picker was not getting shown when authoring the datasource.

> Add a TL;DR when description is extra long (helps content team)

Fixes #22501 

Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manual

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by Irongade — APPROVED** [review]

**Review by AmanAgarwal041 — APPROVED** [review]

**Comment by Aishwarya-U-R** [comment]
@prapullc - Why is skip-testPlan label added? Is this not tested functionally?

**Pull request merged**
