### PR TITLE
chore: Remove feature flags for GIT

### PR DESCRIPTION
**Pull request by AnaghHegde**
## Description

> GIT feature is available to all users. It does not make sense to keep this in feature flags anymore.

### CODE REVIEW

**Review by vishnu-gp — APPROVED** [review]

**Comment by mohanarpit** [comment]
@AnaghHegde Has the client code base removed the feature flag as well? If not, then they will start seeing errors the minute we remove the feature flag from the server.

**Review by mohanarpit — APPROVED** [review]

**Comment by AnaghHegde** [comment]
@IAmAnubhavSaini Could you please remove the feature flag from the FE code as well?

**Pull request merged**
