### PR TITLE
fix: clicking on + in list view does not create a new query

### PR DESCRIPTION
**Pull request by a6hishekpandey**
## Description
This change adds a new state in ideReducer 'isListViewActive' to verify the active status of the list view on split screen mode. I am updating isListViewActive state to false when we click on `+` icon and are already in QUERY_ADD mode, to close the list view and switch back to the new query tab.

Fixes https://github.com/appsmithorg/appsmith/issues/36066
_or_  
Fixes `Issue URL`
> [!WARNING]  
> _If no issue exists, please create an issue first, and check with the maintainers if the issue is valid._

## Automation

/ok-to-test tags=""

### :mag: Cypress test results

> [!CAUTION]  
> If you modify the content in this section, you are likely to disrupt the CI result for your PR.

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [ ] No

## Summary by CodeRabbit

- **New Features**
	- Introduced a new action to manage the active state of the list view, enhancing user interface control.
	- Added a selector to retrieve the current state of the list view.

- **Improvements**
	- Updated the `useQueryAdd` and `useJSAdd` hooks to respond to the IDE's view mode, improving functionality when adding queries.
	- Shifted state management for the list view from local to global, ensuring consistent visibility across the application.

- **Bug Fixes**
	- Enhanced responsiveness of the list view based on the current interface state.

### CODE REVIEW

**Comment by a6hishekpandey** [comment]
@albinAppsmith can you please review the PR whenever you have sometime, and let me know if you have any suggestions on the same

**Comment by albinAppsmith** [comment]
@a6hishekpandey I'm looking into this :)

**Comment by a6hishekpandey** [comment]
@albinAppsmith okay, thankyou

**Comment by albinAppsmith** [comment]
@a6hishekpandey, I’ve identified an issue in the enterprise edition related to this PR. I will review and address it before proceeding with the merge.

**Comment by a6hishekpandey** [comment]
> @a6hishekpandey, I’ve identified an issue in the enterprise edition related to this PR. I will review and address it before proceeding with the merge.

Is that issue occurred due to my changes?

**Comment by albinAppsmith** [comment]
@a6hishekpandey, could you please apply the same changes made in app/client/src/ce/pages/Editor/IDE/EditorPane/Query/hooks.tsx to app/client/src/ce/pages/Editor/IDE/EditorPane/JS/hooks.ts as well? Thank you.

**Comment by a6hishekpandey** [comment]
> @a6hishekpandey, could you please apply the same changes made in `app/client/src/ce/pages/Editor/IDE/EditorPane/Query/hooks.tsx` to `app/client/src/ce/pages/Editor/IDE/EditorPane/JS/hooks.ts` as well?
> 
> Thank you.

@albinAppsmith, we don't need those changes in JS as we are generating entire object with a default name so whenever we click on the plus from listview it will add a new js object and make that tab active, this problem will occur only in the case of QUERY as we have to select one type (ex: REST API) after the add button clicked.

**Comment by albinAppsmith** [comment]
> > @a6hishekpandey, could you please apply the same changes made in `app/client/src/ce/pages/Editor/IDE/EditorPane/Query/hooks.tsx` to `app/client/src/ce/pages/Editor/IDE/EditorPane/JS/hooks.ts` as well?
> > Thank you.
> 
> @albinAppsmith, we don't need those changes in JS as we are generating entire object with a default name so whenever we click on the plus from listview it will add a new js object and make that tab active, this problem will occur only in the case of QUERY as we have to select one type (ex: REST API) after the add button clicked.

@a6hishekpandey the behaviour you explained is different in enterprise version and is you check the else part in `openAddJS` function you will see the similar structure as query add hook.

**Comment by a6hishekpandey** [comment]
> > > @a6hishekpandey, could you please apply the same changes made in `app/client/src/ce/pages/Editor/IDE/EditorPane/Query/hooks.tsx` to `app/client/src/ce/pages/Editor/IDE/EditorPane/JS/hooks.ts` as well?
> > > Thank you.
> > 
> > 
> > @albinAppsmith, we don't need those changes in JS as we are generating entire object with a default name so whenever we click on the plus from listview it will add a new js object and make that tab active, this problem will occur only in the case of QUERY as we have to select one type (ex: REST API) after the add button clicked.
> 
> @a6hishekpandey the behaviour you explained is different in enterprise version and if you check the else part in `openAddJS` function you will see the similar structure as query add hook.

okay, sure I will go through it and make the required changes.

**Comment by albinAppsmith** [comment]
All tests passed in both CE and EE.

CE: https://github.com/appsmithorg/appsmith/pull/36526
EE: https://github.com/appsmithorg/appsmith-ee/pull/5224

**Comment by a6hishekpandey** [comment]
@albinAppsmith and @hetunandu, I had fixed one more issue but closed it as no one looked into it and was not sure if the fix I did was to be did like that, If someone can help me with the PR I can reopen it #36367. Please have a look if you guys have sometime.

**Comment by albinAppsmith** [comment]
@a6hishekpandey This problem needs to be discussed internally before getting into that solution. I will get back to you on this.

**Comment by a6hishekpandey** [comment]
> @a6hishekpandey This problem needs to be discussed internally before getting into that solution. I will get back to you on this.

@albinAppsmith okay, sure

**Comment by albinAppsmith** [comment]
@a6hishekpandey This fix involves some internal discussions and design decisions, so it's best to set it aside for now. Feel free to explore other issues from our [Inviting Contribution](https://github.com/appsmithorg/appsmith/issues?q=is%3Aopen+is%3Aissue+label%3A%22Inviting+Contribution%22) list.

Happy contributing 🙂

**Comment by a6hishekpandey** [comment]
@albinAppsmith okay, thanks for the update.

**Pull request merged**
