### PR TITLE
chore: Add telemetry for error handling phase1

### LINKED ISSUE #20623: [Task]: Add telemetry for Error handling phase 1
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Add telemetry as per the requirements in this [doc](https://www.notion.so/appsmith/Instrumentation-specs-for-errors-0e1c27520d964ff59cc1b56f183b7c07)

### PR DESCRIPTION
**Pull request by ChandanBalajiBP**
## Description

> Telemetry for error handling phase 1 

- [x] Error log opened - **OPEN_DEBUGGER**
- [x] Error log entry expanded - **DEBUGGER_LOG_ITEM_EXPAND**
- [x] Entity link clicked - **DEBUGGER_ENTITY_NAVIGATION**
- [x] Help clicked - **DEBUGGER_HELP_CLICK**
- [x] Documentation clicked - **OPEN_OMNIBAR**
- [x] Error log entry resolved - **DEBUGGER_RESOLVED_ERROR_MESSAGE**

Fixes #20623

## Type of change

> Please delete options that are not relevant.

- Chore (housekeeping or task changes that don't impact user perception)

## How Has This Been Tested?

- Manual

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### CODE REVIEW

**Review by ayushpahwa — APPROVED** [review]

**Comment by ChandanBalajiBP** [comment]
Adding a `test plan` label myself as this PR only deals with telemetry and doesn't require either QA or test cases.

**Pull request merged**
