### PR TITLE
test: Select UI test cases

### PR DESCRIPTION
**Pull request by arslanhaiderbuttar**
> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Description

> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change.

Fixes # (issue)

> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: SelectUITestCases 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 55.25 **(-0.01)** | 37.23 **(-0.01)** | 34.26 **(0)** | 55.8 **(-0.01)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 50.47 **(-0.24)** | 38.26 **(-0.87)** | 36.21 **(0)** | 55.08 **(-0.27)**</details>

### CODE REVIEW

**Review by yatinappsmith — CHANGES_REQUESTED** [review]
Can you split the spec file into smaller chunk. Incase of failure, many tests would be skipped

**Review by NandanAnantharamu — APPROVED** [review]
Approved for test run

**Review by yatinappsmith — APPROVED** [review]
LGTM

**Review by NandanAnantharamu — DISMISSED** [review]
Approved for test run

**Comment by yatinappsmith** [comment]
Please update the PR for "Semantic Pull Request" check

**Review by yatinappsmith — CHANGES_REQUESTED** [review]
Please update PR title

**Review by yatinappsmith — APPROVED** [review]

**Pull request merged**
