### PR TITLE
fix:  Use unique id instead of indices as keys for DraggableList

### LINKED ISSUE #9991: [Bug]-[48000]:The other page name changes by default when users change any one page name
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The other  page name changes by default when users change any one-page name 
[LOOM DEMO](https://www.loom.com/share/af3e4e7d840e498385bac2ba8459e3d4)

### Steps To Reproduce

1. Go to page properties tab
2. Add 10 pages
3. Drag and drop the 10th page to the 3rd place
4. Now change the name of the 3rd page 
5. The name of the 4th page changes automatically

### Environment

Release

### Version

Cloud

### PR DESCRIPTION
**Pull request by berzerkeer**
## Description

> Reordering page list and then renaming a page won't update the targeted page's name due to key mismatch. We were using index as key for the DraggableList component. So changed the list to take unique page ids for the list items keys.

Fixes #9991 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Go to any application, create 3 pages, swap 2nd and 3rd page's order. Now rename the 3rd page, it works as expected. Previously, it was renaming the 2nd page instead of the 3rd page.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>

    // Code coverage diff between base branch:release and head branch: fix/pages-list-rename-bug 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | app/client/src/pages/Editor/PagesEditor/index.tsx | 46.81 **(-1.02)** | 42.86 **(-17.14)** | 0 **(0)** | 47.83 **(-1.06)**</details>

### CODE REVIEW

**Review by ankitakinger — APPROVED** [review]

**Comment by berzerkeer** [comment]
> This may lead to bugs at other places as pageId is not being passed at all places. Since this is a bug in just one file `app/client/src/pages/Editor/PagesEditor/index.tsx` you can use something similar here as file `app/client/src/components/propertyControls/FieldConfigurationControl.tsx` line no. 226 and have send id as well as pageId with both being equal to pageId itself:
> 
> ```
> const draggableComponentColumns = pages.map(
>       ({ identifier, isCustomField, isVisible, label }, index) => ({
>         id: identifier,
>         index,
>         isCustomField,
>         isVisible,
>         label,
>       }),
>     );
> ```

Thanks @ankitakinger , I have made those changes you suggested. Please review.

**Review by ankitakinger — APPROVED** [review]
LGTM

**Comment by rahulramesha** [comment]
@berzerkeer @ankitakinger I actually had another PR in the pipeline for this on a different (duplicate) issue.
Use of `items[i].id` should have been the best way to solve this but since the component `DraggableList` is used in a lot more places this breaks few of them, eg, Table Widget's `primaryColumns` in property Pane. Most of them don't seem to have reliable unique ids. here is a reference to my PR https://github.com/appsmithorg/appsmith/pull/13448.

**Pull request merged**
