### PR TITLE
chore: Widget select logic

### PR DESCRIPTION
**Pull request by hetunandu**
Removes the widget selection when dropping a widget on the canvas
Removes the widget search auto focus 

Fixes: #30578

## Summary by CodeRabbit

- **User Experience**
  - Enhanced the behavior of the search input in the widget sidebar to improve user interaction.

- **Refactor**
  - Optimized widget selection and dragging logic within the layout editor.

### CODE REVIEW

**Comment by riodeuno** [comment]
@marks0351 Could you review this? You have the most context on the files that have been modified.

**Comment by marks0351** [comment]
Code changes look good.
widget selection is done as soon as a widget is moved/added to show property pane of respective widget. In this PR we are removing widget selection when a widget is added. I think most DnD based test cases might fail coz they anticipate respective property pane to show up once a widget is added. pls do check for those cases. 
cc: @riodeuno @somangshu

**Review by marks0351 — APPROVED** [review]

**Comment by hetunandu** [comment]
@marks0351 is a similar change handled in Anvil already?

**Comment by marks0351** [comment]
> @marks0351 is a similar change handled in Anvil already?

yep we do select the newly added widget via sagas(anvilDraggingSagas/addWidgetsSaga).

**Review by albinAppsmith — DISMISSED** [review]

**Pull request closed without merging**
