### PR TITLE
fix: mongo schema collections order of mongo plugin

### PR DESCRIPTION
**Pull request by raushan3737**
### PR Description: 
- **File changes in the PR**:
  - Integrated the sorting feature to the mongo collections.
  - Added the unit test for sorting.

Fixes https://github.com/appsmithorg/appsmith/issues/35842

- **Snapshots**:
  
  **Before resolving bug:**
  
  image
  
  **After resolving bug:**
  
  image

## Summary by CodeRabbit

- **New Features**
	- Enhanced the MongoDB plugin to return collection names in a case-insensitive sorted order, improving predictability and user experience.
  
- **Tests**
	- Added a new test to validate that collections returned by the plugin are sorted correctly, ensuring consistent functionality.

### CODE REVIEW

**Comment by raushan3737** [comment]
Hi @NilanshBansal, @sagar-qa007, Could you please review this PR.
Thank you.

**Comment by raushan3737** [comment]
Hi @NilanshBansal , Could you please review the PR if possible. It has been opened since last 3 weeks.

**Comment by NilanshBansal** [comment]
Hey @raushan3737 apologies for the inconvenience, we are starting to review this PR and targeting to complete it by Next Friday.

**Comment by NilanshBansal** [comment]
Hi @raushan3737 thanks for your patience. We have created shadow PR [here](https://github.com/appsmithorg/appsmith/pull/36532) to run the tests.

**Comment by NilanshBansal** [comment]
Tested the DP, it looks good to me.
image

**Review by NilanshBansal — APPROVED** [review]

**Comment by NilanshBansal** [comment]
@raushan3737 thanks for taking out time to contribute to Appsmith! We highly appreciate your effort in making Appsmith better ❤️
You can find more issues to contribute from [this](https://github.com/appsmithorg/appsmith/issues?q=is%3Aopen+is%3Aissue+label%3A%22Inviting+Contribution%22) list!

**Pull request merged**
