### PR TITLE
chore: changes to render complete property pane post dragging or resizing

### LINKED ISSUE #12747: Perf: Open property pane post dragging or resizing of a widget.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

When a widget's property pane is not open and the user starts to drag that particular widget then, the propertyPane of that particular widget opens up at the moment of starting to drag or resize. This blocks the main UI thread and gives the perception of a lag at the start of drag or resize.
This can be solved by making sure the property pane renders or re-renders at the end of drag or resize.

### PR DESCRIPTION
**Pull request by rahulramesha**
## Description

When a widget is started to drag, the property pane starts to render. Rendering of property pane is expensive, So, Dragging or resizing a widget has an initial lag. In this PR, the widget, while dragging or resizing renders to property pane at the end of the Drag or resize.

Fixes #12747 

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
manual UI

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: renderPanePostDrag 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 56.46 **(-0.06)** | 37.99 **(-0.01)** | 35.8 **(-0.06)** | 56.7 **(-0.05)**
 :green_circle: | app/client/src/components/editorComponents/PropertyPaneSidebar.tsx | 96.36 **(0.62)** | 86.67 **(15.24)** | 100 **(0)** | 96.36 **(0.62)**
 :red_circle: | app/client/src/components/propertyControls/ButtonTabControl.tsx | 62.96 **(0)** | 27.27 **(-9.09)** | 60 **(0)** | 61.9 **(0)**
 :red_circle: | app/client/src/components/propertyControls/DropDownControl.tsx | 90 **(0)** | 61.9 **(-4.77)** | 71.43 **(0)** | 88.89 **(0)**
 :red_circle: | app/client/src/components/propertyControls/PrimaryColumnDropdownControl.tsx | 40 **(-40)** | 0 **(-42.86)** | 40 **(-20)** | 40.91 **(-36.36)**
 :red_circle: | app/client/src/components/propertyControls/PrimaryColumnsControl.tsx | 22.67 **(-13.33)** | 5.97 **(-5.97)** | 11.54 **(-7.69)** | 22.38 **(-12.59)**
 :red_circle: | app/client/src/components/utils/EmptyDataState.tsx | 83.33 **(-16.67)** | 100 **(0)** | 0 **(-100)** | 83.33 **(-16.67)**
 :red_circle: | app/client/src/icons/ControlIcons.tsx | 62.41 **(-2.25)** | 100 **(0)** | 23.08 **(-4.61)** | 62.41 **(-2.25)**
 :red_circle: | app/client/src/pages/Editor/PropertyPane/PropertySection.tsx | 87.1 **(-3.22)** | 56.25 **(0)** | 66.67 **(-16.66)** | 85.71 **(-3.58)**
 :red_circle: | app/client/src/sagas/WidgetEnhancementHelpers.ts | 38.36 **(-2.74)** | 27.45 **(-3.92)** | 14.29 **(0)** | 40.91 **(-3.03)**
 :green_circle: | app/client/src/selectors/widgetSelectors.ts | 66.67 **(4.17)** | 43.75 **(8.04)** | 62.5 **(5.36)** | 65.22 **(3.32)**
 :red_circle: | app/client/src/utils/validation/common.ts | 52.46 **(-1.64)** | 56.25 **(-0.63)** | 33.33 **(0)** | 51.67 **(-1.66)**</details>

### CODE REVIEW

**Review by SatishGandham — COMMENTED** [review]
Neat implementation @rahulramesha.
Is it possible to stick to the previously selected widgets property pane, instead showing the canvas property pane?

**Comment by rahulramesha** [comment]
@SatishGandham, yes it is possible but, It might confuse the user while dragging or resizing. Considering that rendering canvas takes only 15ms more than just sticking to the previous selected widget.

**Comment by SatishGandham** [comment]
@rahulramesha , Rendering is not a problem. Property pane flicker looks odd.

**Review by SatishGandham — APPROVED** [review]
LGTM code wise

**Comment by rahulramesha** [comment]
@SatishGandham, had to rework because of theming properties in propertyPane

**Review by SatishGandham — APPROVED** [review]

**Pull request merged**
